<div id="view-content">
    <div style="margin-bottom: 3px; width: 500px">
        <form action="/eu-objet/list" method="POST">
            <input type="text" id="produit" name="produit" />
            <input id="ok" type="submit" value="Recherche" />
        </form>     
  </div>
    <table id="tbl-objet"></table>
    <div id="pg-objet"></div>
</div>

<script type="text/javascript">
    
    $("#tbl-objet").jqGrid({
        url:'/eu-objet/listproduit?produit=<?php echo $this->produit ?>',
        editurl:'<?php echo $this->url(array('action' => 'save')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames:['Code','Designation'],
        height:440, width:800,
        colModel:[
            {name:'code_objet',index:'code_objet', width: 140, editable: true,align:"left"},
            {name:'design_objet',index:'design_objet', width: 300, editable: true,align:"left"},
        ],
        rowNum:10,
        rowList:[10,20,30],
        pager: '#pg-objet',
        sortname:"code_objet",
        viewrecords: true,
        sortorder: "DESC",
        caption:"Consultation de la liste des produits sur le réseau "
    });
    $("#tbl-objet").jqGrid('navGrid','#pg-objet',{edit:false,add:false,del:false,search:true});
    
    
    $(document).ready(function ()
    {
         $.get( "/eu-objet/produit",
                function success(data){
                $("input#produit").autocomplete({"source":data});
                }
        );
    })
     $('#ok').button();  
</script>