<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques2.js"></script>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/fondateurs.js"></script><?php */?>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/capasenrolement.js"></script><?php */?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banquespays.js"></script>
<script src="<?php echo $this->baseUrl();?>/bootstrap/js/jquery.js"></script>



<script type="text/javascript">
function submitform(){
document.getElementById('bon_neutre_appro_montant1').value = document.getElementById('bon_neutre_appro_montant').value;
document.getElementById('bon_neutre_email1').value = document.getElementById('bon_neutre_email').value;
document.getElementById('bon_neutre_mobile1').value = document.getElementById('bon_neutre_mobile').value;
document.getElementById('date_nais_membre1').value = document.getElementById('date_nais_membre').value;

if(document.getElementById('bon_neutre_personne_pp').checked == true){
  document.getElementById('pp1').style.display='block'; 
  document.getElementById('bon_neutre_nom1').value = document.getElementById('bon_neutre_nom').value;
  document.getElementById('bon_neutre_prenom1').value = document.getElementById('bon_neutre_prenom').value;
  document.getElementById('pm1').style.display='none';
  document.getElementById('bon_neutre_raison1').value = document.getElementById('bon_neutre_raison').value;
}
if(document.getElementById('bon_neutre_personne_pm').checked == true){
  document.getElementById('pp1').style.display='block'; 
  document.getElementById('bon_neutre_nom1').value = document.getElementById('bon_neutre_nom').value;
  document.getElementById('bon_neutre_prenom1').value = document.getElementById('bon_neutre_prenom').value;
  document.getElementById('pm1').style.display='block';
  document.getElementById('bon_neutre_raison1').value = document.getElementById('bon_neutre_raison').value;
}


}
</script>



<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menubanqueopi.phtml"); ?>

<blockquote><p>Approvisionnement de Bon d'Achat neutre (BAn) pour Compte Marchand (CM)</p></blockquote>
  <?php if(isset($sessionbanqueopi->error) && $sessionbanqueopi->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionbanqueopi->error; $sessionbanqueopi->error = ""; ?>
    </div>
  <?php } ?>

    <?php if(isset($sessionbanqueopi->code_BAn) && $sessionbanqueopi->code_BAn != "") { ?>
<blockquote>
  <a href="/bons/recudepayementdebanpdf/id/<?php echo $sessionbanqueopi->bon_neutre_detail_id; ?>" target="_blank"><span style="color:#800080;">Télécharger le reçu de votre Bon d'Achat neutre (<strong>BAn</strong>)</span></a> <br /><br />
    
  <?php $sessionbanqueopi->code_BAn = "";?>
</blockquote>
  <?php } ?>

  
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription1" name="addsouscription1">
<fieldset>
<legend>Remplir le formulaire </legend>

<div class="control-group">
  <label class="control-label" for="bon_neutre_personne">Type du souscripteur *</label>
  <div class="controls">

  <label class="radio">
  <input name="bon_neutre_personne" type="radio" id="bon_neutre_personne_pp" value="PP" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='none';
  document.getElementById('bon_neutre_raison').removeAttribute('required');
  ">
  Personne Physique</label>
  
  <label class="radio">
  <input type="radio" name="bon_neutre_personne" id="bon_neutre_personne_pm" value="PM" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='block';
  document.getElementById('bon_neutre_raison').setAttribute('required', true);
  " >
  Personne Morale</label>
  
</div>
</div>

<div id="pp" style="display:none;">
<div class="control-group">
<label class="control-label" for="bon_neutre_nom">Nom du souscripteur  * </label>
<div class="controls">
<input type="text" name="bon_neutre_nom" id="bon_neutre_nom" placeholder="Nom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required"  />
<span class="help-block"><p class="text-error">Veuillez saisir votre <strong>Nom</strong> réel. </p></span>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="bon_neutre_prenom">Prénoms du souscripteur * </label>
<div class="controls">
<input type="text" name="bon_neutre_prenom" id="bon_neutre_prenom" placeholder="Prénom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required"  />
<span class="help-block"><p class="text-error">Veuillez saisir vos <strong>Prénoms</strong> réels. </p></span>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="date_nais_membre">Date de naissance *</label>
<div class="controls">
<input type="text" name="date_nais_membre" id="date_nais_membre" placeholder="Date de naissance" class="input-large datepicker" data-provide="datepicker"  required="required"  readonly />
</div>
</div>  
</div>


<div id="pm" style="display:none;">
<div class="control-group">
<label class="control-label" for="bon_neutre_raison">Raison sociale du souscripteur * </label>
<div class="controls">
<input type="text" name="bon_neutre_raison" id="bon_neutre_raison" placeholder="Raison sociale du souscripteur" class="input-xxlarge" required="required" />
<span class="help-block"><p class="text-error">Veuillez saisir la <strong>Raison Sociale</strong> réelle de votre personne morale s'il y en a. </p></span>
</div>
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_mobile">Cellulaire du souscripteur  *</label>
<div class="controls">
<input type="number" name="bon_neutre_mobile" id="bon_neutre_mobile" placeholder="Cellulaire du souscripteur " class="input-xxlarge"  required="required" />
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_email">E-mail du souscripteur * </label>
<div class="controls">
<div class="input-prepend">
<span class="add-on"><i class="icon-envelope"></i></span>
<input type="email" name="bon_neutre_email" id="bon_neutre_email" placeholder="E-mail du souscripteur" class="input-xxlarge"  required="required" />
</div>
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_appro_montant">Montant à allouer * </label>
<div class="controls">
<input type="number" name="bon_neutre_appro_montant" id="bon_neutre_appro_montant" placeholder="Montant à allouer" class="input-xxlarge"  required="required" />
<span class="help-block"><p class="text-error">Veuillez saisir le montant à allouer</p></span>
</div>
</div>

</fieldset>

<!--<div id="qrcaptcha"></div>

<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<input name="confirmation" type="hidden" id="confirmation" value="1" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" id="submit" class="btn btn-primary">Valider</button>
</div>-->


<!-- Button trigger modal -->
<button id="button" type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" onclick="submitform();">Enregistrer l'approvisionnement de Bon d'Achat neutre  (BAn) pour Compte Marchand (CM)
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Veuillez bien vérifier les informations de l'approvisionnement.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        




<!--<div class="control-group">
  <label class="control-label" for="bon_neutre_personne1">Type du souscripteur *</label>
  <div class="controls">

  <label class="radio">
  <input name="bon_neutre_personne1" type="radio" id="bon_neutre_personne1_pp" value="PP" required disabled="disabled" onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='none';
  document.getElementById('bon_neutre_raison').removeAttribute('required');
  ">
  Personne Physique</label>
  
  <label class="radio">
  <input type="radio" name="bon_neutre_personne1" id="bon_neutre_personne1_pm" value="PM" required disabled="disabled" onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='block';
  document.getElementById('bon_neutre_raison').setAttribute('required', true);
  " >
  Personne Morale</label>
  
</div>
</div>-->

<div id="pp1" style="display:none;">
<div class="control-group">
<label class="control-label" for="bon_neutre_nom1">Nom du souscripteur  * </label>
<div class="controls">
<input type="text" name="bon_neutre_nom1" id="bon_neutre_nom1" placeholder="Nom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required" disabled="disabled"  />
<span class="help-block"><p class="text-error">Veuillez saisir votre <strong>Nom</strong> réel. </p></span>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="bon_neutre_prenom1">Prénoms du souscripteur * </label>
<div class="controls">
<input type="text" name="bon_neutre_prenom1" id="bon_neutre_prenom1" placeholder="Prénom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required" disabled="disabled"  />
<span class="help-block"><p class="text-error">Veuillez saisir vos <strong>Prénoms</strong> réels. </p></span>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="date_nais_membre1">Date de naissance *</label>
<div class="controls">
<input type="text" name="date_nais_membre1" id="date_nais_membre1" placeholder="Date de naissance" class="input-large datepicker" data-provide="datepicker"  required="required"  readonly disabled="disabled" />
</div>
</div>  
</div>


<div id="pm1" style="display:none;">
<div class="control-group">
<label class="control-label" for="bon_neutre_raison1">Raison sociale du souscripteur * </label>
<div class="controls">
<input type="text" name="bon_neutre_raison1" id="bon_neutre_raison1" placeholder="Raison sociale du souscripteur" class="input-xxlarge" required="required" disabled="disabled" />
<span class="help-block"><p class="text-error">Veuillez saisir la <strong>Raison Sociale</strong> réelle de votre personne morale s'il y en a. </p></span>
</div>
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_mobile1">Cellulaire du souscripteur  *</label>
<div class="controls">
<input type="number" name="bon_neutre_mobile1" id="bon_neutre_mobile1" placeholder="Cellulaire du souscripteur " class="input-xxlarge"  required="required" disabled="disabled" />
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_email1">E-mail du souscripteur * </label>
<div class="controls">
<div class="input-prepend">
<span class="add-on"><i class="icon-envelope"></i></span>
<input type="email" name="bon_neutre_email1" id="bon_neutre_email1" placeholder="E-mail du souscripteur" class="input-xxlarge"  required="required" disabled="disabled" />
</div>
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_appro_montant1">Montant à allouer * </label>
<div class="controls">
<input type="number" name="bon_neutre_appro_montant1" id="bon_neutre_appro_montant1" placeholder="Montant à allouer" class="input-xxlarge"  required="required" disabled="disabled" />
<span class="help-block"><p class="text-error">Veuillez saisir le montant à allouer</p></span>
</div>
</div>



  <label for="valide" class="checkbox">
  <input type="checkbox" name="valide" id="valide" value="1" required onclick="if(document.getElementById('valide').checked == true){
  document.getElementById('submit1').disabled = false;
  }else{
  document.getElementById('submit1').disabled = true;
    }">
  <strong>Etes vous sur de vouloir valider cette approvisionnement de BAn ? Si OUI cochez</strong></label>

      </div>
      <div class="modal-footer">
<input name="ok" type="hidden" id="ok" value="ok" />
<input name="confirmation" type="hidden" id="confirmation" value="1" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" id="submit1" class="btn btn-primary" disabled>Valider l'approvisionnement du BAn</button>
      </div>
    </div>
  </div>
</div>

</form>

<!--<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
outil_confirmation_biometrique_personelle('addsouscription1','qrcaptcha','submit',"Veuillez confirmer cette opération d'approvisionnement ?",'<?php echo $sessionbanqueopi->code_membre;?>');
</script>-->


<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>
