<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>
            
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques2.js"></script>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/fondateurs.js"></script><?php */?>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/capasenrolement.js"></script><?php */?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banquespays.js"></script>


<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">
<?php include("../application/layouts/scripts/menubanqueopi.phtml"); ?>

<?php 
$banque = new Application_Model_EuBanque();
$banque_mapper = new Application_Model_EuBanqueMapper();
$banque_mapper->find($sessionbanqueopi->code_banque, $banque);
          
$membre_morale = new Application_Model_EuMembreMorale();
$membre_morale_mapper = new Application_Model_EuMembreMoraleMapper();
$membre_morale_mapper->find($banque->code_membre_morale, $membre_morale);


 ?>

<blockquote><p>Souscription au Bon d'Achat neutre (BAn) en gros</p></blockquote>
  <?php if(isset($sessionbanqueopi->error) && $sessionbanqueopi->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionbanqueopi->error; $sessionbanqueopi->error = ""; ?>
    </div>
  <?php } ?>
  
    <?php if(isset($sessionbanqueopi->code_BAn) && $sessionbanqueopi->code_BAn != "") { ?>
<blockquote>
  <a href="/souscriptionbon/bonachatneutrepdf/code/<?php echo $sessionbanqueopi->code_BAn; ?>" target="_blank"><span style="color:#800080;">Télécharger votre Bon d'Achat neutre (<strong>BAn</strong>)</span></a> <br /><br />

  <?php $sessionbanqueopi->code_BAn = "";?>
</blockquote>
  <?php } ?>

  <?php if(!isset($sessionbanqueopi->code_BAn) || $sessionbanqueopi->code_BAn == "") { ?>
              <blockquote>Informations concernant le versement à la banque</blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription1" name="addsouscription1">
<fieldset>
<legend>Remplir le formulaire </legend>



  
<div class="control-group">
<label class="control-label" for="bon_neutre_code_membre">Code Membre du souscripteur  </label>
<div class="controls">
  <input type="text" name="bon_neutre_code_membre" id="bon_neutre_code_membre" placeholder="Code Membre du souscripteur" class="input-xxlarge" value="<?php echo $membre_morale->code_membre_morale; ?>" readonly />
<span class="help-block"><p class="text-error">Veuillez saisir votre <strong>Code Membre</strong> si vous disposez dèjà d'un Compte Marchand ESMC </p></span>
</div>
</div>

<?php /*?><div class="control-group">
<label class="control-label" for="bon_neutre_code_ban">Code BAn précèdent </label>
<div class="controls">
  <input type="text" name="bon_neutre_code_ban" id="bon_neutre_code_ban" placeholder="Code BAn précèdent" class="input-xxlarge" />
<span class="help-block"><p class="text-error">Veuillez saisir votre <strong>Code BAn précèdent</strong> si vous voulez le cumuler. </p></span>
</div>
</div><?php */?>

  <input type="hidden" name="bon_neutre_code_ban" id="bon_neutre_code_ban" value=""  />

<?php /*?><div class="control-group">
  <label class="control-label" for="bon_neutre_personne">Type du souscripteur *</label>
  <div class="controls">

  <label class="radio">
  <input name="bon_neutre_personne" type="radio" id="bon_neutre_personne_pp" value="PP" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='none';
  document.getElementById('bon_neutre_raison').removeAttribute('required');
  ">
  Personne Physique</label>
  
  <label class="radio">
  <input type="radio" name="bon_neutre_personne" id="bon_neutre_personne_pm" value="PM" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='block';
  document.getElementById('bon_neutre_raison').setAttribute('required', true);
  " >
  Personne Morale</label>
  
</div>
</div><?php */?>

  <input type="hidden" name="bon_neutre_personne" id="bon_neutre_personne" value="PM"  />

<?php /*?><div id="pp" style="display:none;"><?php */?>
<div class="control-group">
<label class="control-label" for="bon_neutre_nom">Nom du souscripteur  * </label>
<div class="controls">
<input type="text" name="bon_neutre_nom" id="bon_neutre_nom" placeholder="Nom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required" value="<?php echo $sessionbanqueopi->nom_banque_user; ?>"  />
<span class="help-block"><p class="text-error">Veuillez saisir votre <strong>Nom</strong> réel. </p></span>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="bon_neutre_prenom">Prénoms du souscripteur * </label>
<div class="controls">
<input type="text" name="bon_neutre_prenom" id="bon_neutre_prenom" placeholder="Prénom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required" value="<?php echo $sessionbanqueopi->prenom_banque_user; ?>"  />
<span class="help-block"><p class="text-error">Veuillez saisir vos <strong>Prénoms</strong> réels. </p></span>
</div>
</div>
<?php /*?></div>

<div id="pm" style="display:none;"><?php */?>
<div class="control-group">
<label class="control-label" for="bon_neutre_raison">Raison sociale du souscripteur * </label>
<div class="controls">
  <input type="text" name="bon_neutre_raison" id="bon_neutre_raison" placeholder="Raison sociale du souscripteur" class="input-xxlarge" required="required" readonly value="<?php echo $membre_morale->raison_sociale; ?>" />
<span class="help-block"><p class="text-error">Veuillez saisir la <strong>Raison Sociale</strong> réelle de votre personne morale s'il y en a. </p></span>
</div>
</div>
<?php /*?></div><?php */?>

<div class="control-group">
<label class="control-label" for="bon_neutre_mobile">Cellulaire du souscripteur  *</label>
<div class="controls">
<input type="text" name="bon_neutre_mobile" id="bon_neutre_mobile" placeholder="Cellulaire du souscripteur " class="input-xxlarge"  required="required"   />
</div>
</div>

<div class="control-group">
<label class="control-label" for="bon_neutre_email">E-mail du souscripteur * </label>
<div class="controls">
<div class="input-prepend">
      <span class="add-on"><i class="icon-envelope"></i></span>
    <input type="email" name="bon_neutre_email" id="bon_neutre_email" placeholder="E-mail du souscripteur" class="input-xxlarge"  required="required" />
    </div>
</div>
</div>
  
  
  

  <legend> Localités </legend>

                        <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Zone M.</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="code_zone" name="code_zone">
                                            <option value="">Choisir une zone monétaire</option>
                                            <?php foreach ($this->zones as $value) { ?>
                                            <option
                                                    value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Pays</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_pays" name="id_pays" onchange="ouvre_banquespays(this.value, 'nivo_banquespays');">
                                            <option value="">Choisir un pays</option>
                                            <?php foreach ($this->pays as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Régions</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_region" name="id_region">
                                            <option value="">Choisir une région</option>
                                            <?php foreach ($this->regions as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Préfectures</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_prefecture" name="id_prefecture">
                                            <option value="">Choisir une préfecture</option>
                                            <?php foreach ($this->prefectures as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Cantons *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_canton" name="id_canton" required="required">
                                            <option value="">Choisir un canton</option>
                                            <?php foreach ($this->cantons as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

  
  
  <legend> Le versement à la banque </legend>
  
  
<?php /*?><div id="nivo_banquespays"><?php */?>
<div class="control-group">
<label class="control-label" for="bon_neutre_banque">Moyen de payement *</label>
<div class="controls">
<?php /*?><select name="bon_neutre_banque" id="bon_neutre_banque"  class="input-xxlarge" required="required">
  <option value="">Choisir le moyen</option>
</select><?php */?>
  <input type="text" name="bon_neutre_banque" id="bon_neutre_banque" placeholder="Moyen de payement" class="input-xxlarge"  required="required" readonly value="<?php echo $sessionbanqueopi->code_banque; ?>" />
</div>
</div>
<?php /*?></div><?php */?>

<div class="control-group">
<label class="control-label" for="bon_neutre_numero">Numéro de reçu de banque ou Numéro de transaction  * </label>
<div class="controls">
  <input type="text" name="bon_neutre_numero" id="bon_neutre_numero" placeholder="Numero de reçu de banque ou Numéro de transaction" class="input-xxlarge"  required="required" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="bon_neutre_date_numero">Date de reçu de banque ou de transaction  * </label>
<div class="controls">
  <input type="text" name="bon_neutre_date_numero" id="bon_neutre_date_numero" placeholder="Date de reçu de banque ou de transaction" class="input-xxlarge datepicker" data-provide="datepicker"  required="required" readonly />
<span class="help-block"><p class="text-error">Cliquez dans le champ pour choisir la date du reçu de banque ou de transaction</p></span>
</div>
</div>

<?php /*?><div class="control-group">
<label class="control-label" for="bon_neutre_vignette">Scanne du reçu  </label>
<div class="controls">
  <input type="file" name="bon_neutre_vignette" id="bon_neutre_vignette" class="input-xxlarge"  />
<span class="help-block"><p class="text-error">JPEG, JPG, PNG et PDF sont les extentions autorisées</p></span>
</div>
</div><?php */?>
  
  <div class="control-group">
<label class="control-label" for="bon_neutre_montant">Montant du versement à la banque ou de la transaction * </label>
<div class="controls">
  <input type="number" name="bon_neutre_montant" id="bon_neutre_montant" placeholder="Montant du versement à la banque ou de la transaction" class="input-xxlarge"  required="required" />
<span class="help-block"><p class="text-error">Veuillez saisir le montant de votre reçu de banque ou de la transaction</p></span>
</div>
</div>

</fieldset>
<div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enregistrer la souscription au Bon d'Achat neutre BAn en gros</button>
</div>
 
                            
  
</form>
  <?php } ?>

    


<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php */?>
</div>
</div>
</div>








