<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menubanqueopi.phtml"); ?>
  <blockquote>
  <p>
      <strong>Administration</strong> 
  <small>Espace de banque pour les OPI</small>
  </p>
  </blockquote>







<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








