<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?> 

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menubanqueopi.phtml"); ?>

  <blockquote><p>Liste des utilisateurs de Banque OPI</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Banque</th>
								  <th>Nom</th>
								  <th>Prénom(s)</th>
								  <th>Code Membre</th>
								  <th>Login</th>
								  <th>Date création</th>
								  <th>Rôle</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php 
$banqueM = new Application_Model_EuBanqueMapper();
$banque = new Application_Model_EuBanque();
$banqueM->find($entry->getCodeBanque(), $banque);
?><?php echo ($entry->getCodeBanque()); ?> - <?php echo ($banque->libelle_banque); ?></td>
      <td><?php echo ($entry->getNomBanqueUser()); ?></td>
      <td><?php echo ($entry->getPrenomBanqueUser()); ?></td>
      <td><?php echo ($entry->getCode_membre()); ?></td>
      <td><?php echo ($entry->getLoginBanqueUser()); ?></td>
      <td><?php echo datefr($entry->getDateCreated()); ?></td>
      <td><?php echo ($entry->getRole()); ?></td>
		    <td><div align="center">
		    <?php if($entry->activer == 1) { ?>
		    <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/banqueopi/activerbanqueuser/id/<?php echo $entry->getIdBanqueUser(); ?>/activer/0"> <i class="icon-ok icon-white">  </i> Activé </a>&nbsp;
                    <?php } else { ?>
		    <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/banqueopi/activerbanqueuser/id/<?php echo $entry->getIdBanqueUser(); ?>/activer/1"> <i class="icon-off icon-white"> </i> Désactivé </a>&nbsp;
                    <?php } ?><?php /*?><?php */?>
		    
		    <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/banqueopi/editbanqueuser/id/<?php echo $entry->getIdBanqueUser(); ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<?php /*?><a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/banqueopi/suppbanqueuser/id/<?php echo $entry->getIdBanqueUser(); ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a><?php */?></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun banque user enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








