<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menubanqueopi.phtml"); ?>

  <blockquote><p>Liste des bons d'achat neutre BAn</p></blockquote>
  <?php if(isset($sessionbanqueopi->error) && $sessionbanqueopi->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionbanqueopi->error; $sessionbanqueopi->error = ""; ?>
    </div>
  <?php }?>
  
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Code</th>
								  <th>Nom et Prénom(s)</th>
								  <th>Montant</th>
								  <th>Utilisé</th>
								  <th>Solde</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datejourfr($entry->bon_neutre_date); ?></td>
      <td><?php echo ($entry->bon_neutre_code); ?></td>
      <td><?php echo ($entry->bon_neutre_nom); ?> <?php echo ($entry->bon_neutre_prenom); ?> (<?php echo ($entry->bon_neutre_raison); ?>)</td>
      <td><?php echo ($entry->bon_neutre_montant); ?></td>
      <td><?php echo ($entry->bon_neutre_montant_utilise); ?></td>
      <td><?php echo ($entry->bon_neutre_montant_solde); ?></td>
      <td><div align="center">
            <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/banqueopi/detailbonneutre/id/<?php echo $entry->bon_neutre_id; ?>"><i class="icon-cog icon-white"></i>  Détails</a>&nbsp;
            <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/banqueopi/utilisebonneutre/id/<?php echo $entry->bon_neutre_id; ?>"><i class="icon-cog icon-white"></i>  Utilisations</a>&nbsp;
            <a class="btn btn-mini btn-primary" href="<?php echo $this->baseUrl(); ?>/banqueopi/bonachatneutrepdf/id/<?php echo $entry->bon_neutre_id; ?>" target="_blank"><i class="icon-cog icon-white"></i>  Imprimer le bon</a>&nbsp;
		</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun bon enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








