<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">


<form method="post" id="connexion" action="<?php echo $this->baseUrl();?>/banqueopi/login">
    <?php if(isset($sessionbanqueopi->errorlogin) && $sessionbanqueopi->errorlogin != ""){?>
    <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionbanqueopi->errorlogin; ?>
	</div>
	<?php }?>


    <div class="controls">
      <input name="login" type="text" id="login" placeholder="Votre Login">
    </div>
    <div class="controls">
      <input name="pwd" type="password" id="pwd" placeholder="Votre Mot de Passe">
    </div>
    <div class="controls">
      <input name="ok" type="hidden" id="ok" value="ok" />
      <button type="submit" class="btn">Connexion Banque pour les OPI</button>
    </div>
</form>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








