<?php $sessionbanqueopi = new Zend_Session_Namespace('banqueopi');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menubanqueopi.phtml"); ?>

  <blockquote><p>Modification du mot de passe</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addbanqueopi">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    
<div class="control-group">
<label class="control-label" for="ancien">Ancien mot de passe *</label>
<div class="controls">
<input type="password" name="ancien" id="ancien" placeholder="Ancien mot de passe" required>
</div>
</div>

<div class="control-group">
<label class="control-label" for="nouveau">Nouveau mot de passe *</label>
<div class="controls">
<input type="password" name="nouveau" id="nouveau" placeholder="Nouveau mot de passe" required>
</div>
</div>

<div class="control-group">
<label class="control-label" for="confirmer">Confirmer le nouveau *</label>
<div class="controls">
<input type="password" name="confirmer" id="confirmer" placeholder="Confirmer le nouveau" required>
</div>
</div>



<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-success">Modifier le mot de passe</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








