<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script>
function nbremontantcmfh(type){
	if(type <= 5){
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome').checked == true){
			document.getElementById('souscription_nombre').value = 500 + 1;
			document.getElementById('souscription_montant').value = (500 * 2187.5) + 5000;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome').checked == true){
			document.getElementById('souscription_nombre').value = 500 + 1;
			document.getElementById('souscription_montant').value = (500 * 2187.5) + 70000;
		}else{
			document.getElementById('souscription_nombre').value = 500;
			document.getElementById('souscription_montant').value = 500 * 2187.5;
		}	
	}else if(type > 5 && type <= 7){
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome').checked == true){
			document.getElementById('souscription_nombre').value = 100 + 1;
			document.getElementById('souscription_montant').value = (100 * 2187.5) + 5000;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome').checked == true){
			document.getElementById('souscription_nombre').value = 100 + 1;
			document.getElementById('souscription_montant').value = (100 * 2187.5) + 70000;
		}else{
			document.getElementById('souscription_nombre').value = 100;
			document.getElementById('souscription_montant').value = 100 * 2187.5;
		}	
	}else if(type > 7){
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome').checked == true){
			document.getElementById('souscription_nombre').value = 10 + 1;
			document.getElementById('souscription_montant').value = (10 * 2187.5) + 5000;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome').checked == true){
			document.getElementById('souscription_nombre').value = 10 + 1;
			document.getElementById('souscription_montant').value = (10 * 2187.5) + 70000;
		}else{
			document.getElementById('souscription_nombre').value = 10;
			document.getElementById('souscription_montant').value = 10 * 2187.5;
		}	
	}
	}
	
function nbremontantkacm(){
	if(document.getElementById('souscription_personne_pp').checked == true){
		document.getElementById('souscription_nombre').value = 1;
		document.getElementById('souscription_montant').value = 5000;
	}
	if(document.getElementById('souscription_personne_pm').checked == true){
		document.getElementById('souscription_nombre').value = 1;
		document.getElementById('souscription_montant').value = 70000;
	}
	}
</script>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

  <blockquote><p>Modifier une souscription</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addappeloffres">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
<fieldset>
<legend>Formulaire de modification d'une souscription </legend>
    
<div class="control-group">
  <label class="control-label" for="souscription_personne">Type du souscripteur *</label>
  <div class="controls">
  <label for="souscription_personne_pp" class="radio">
  <input name="souscription_personne" type="radio"  id="souscription_personne_pp" onclick="document.getElementById('pp').style.display='block'; document.getElementById('pm').style.display='none';nbremontantkacm();" value="PP" <?php if($this->souscription->souscription_personne == "PP"){echo ' checked="checked"';}?>>
  Personne Physique</label>

  <label for="souscription_personne_pm" class="radio">
  <input type="radio" name="souscription_personne" id="souscription_personne_pm"  onclick="document.getElementById('pp').style.display='none'; document.getElementById('pm').style.display='block';nbremontantkacm();" value="PM" <?php if($this->souscription->souscription_personne == "PM"){echo ' checked="checked"';}?>>
  Personne Morale</label>
  
  </div>
  </div>
  
<div class="control-group">
  <label class="control-label" for="souscription_autonome">Souscripteur Autonome *</label>
  <div class="controls">
  <label for="souscription_autonome" class="checkbox">
  <input name="souscription_autonome" type="checkbox" required id="souscription_autonome" value="1" <?php if($this->souscription->souscription_autonome == "1"){echo ' checked="checked"';}?>>
  Oui </label>
  </div>
  </div>
  
  <div id="pp" style=' <?php if($this->souscription->souscription_personne == "PP"){?> display:block;<?php }else{?> display:none;<?php }?> '>
<div class="control-group">
<label class="control-label" for="souscription_nom">Nom du souscripteur  *</label>
<div class="controls">
<input type="text" name="souscription_nom" id="souscription_nom" placeholder="Nom du souscripteur " class="input-xxlarge"  value="<?php echo $this->souscription->souscription_nom; ?>" />
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="souscription_prenom">Prénom du souscripteur  *</label>
<div class="controls">
<input type="text" name="souscription_prenom" id="souscription_prenom" placeholder="Prénom du souscripteur " class="input-xxlarge"  value="<?php echo $this->souscription->souscription_prenom; ?>" />
</div>
</div>
</div>

  <div id="pm" style=' <?php if($this->souscription->souscription_personne == "PM"){?> display:block;<?php }else{?> display:none;<?php }?>'>
<div class="control-group">
<label class="control-label" for="souscription_raison">Raison sociale du souscripteur  </label>
<div class="controls">
  <input type="text" name="souscription_raison" id="souscription_raison" placeholder="Raison sociale du souscripteur" class="input-xxlarge" value="<?php echo $this->souscription->souscription_raison; ?>" />
</div>
</div>

<div class="control-group">
  <label class="control-label" for="type_acteur">Type Agrément OSE/OE *</label>
  <div class="controls">
  <select name="type_acteur" id="type_acteur" class="input-xxlarge" >
  <option value="">Choisir le type</option>
    <option value="EI" <?php if($this->souscription->code_type_acteur == 'EI'){echo ' selected="selected"';}?>>Entreprise Industrie</option>
    <option value="OE" <?php if($this->souscription->code_type_acteur == 'OE'){echo ' selected="selected"';}?>>Opérateur Economique</option>
    <option value="OSE" <?php if($this->souscription->code_type_acteur == 'OSE'){echo ' selected="selected"';}?>>Opérateur Socio-Economique</option>
    <option value="PEI" <?php if($this->souscription->code_type_acteur == 'PEI'){echo ' selected="selected"';}?>>Partenaire Entreprise Industrie</option>
    <option value="POE" <?php if($this->souscription->code_type_acteur == 'POE'){echo ' selected="selected"';}?>>Partenaire Opérateur Economique</option>
    <option value="POSE" <?php if($this->souscription->code_type_acteur == 'POSE'){echo ' selected="selected"';}?>>Partenaire Opérateur Socio-Economique</option>
</select>
  </div>
  </div>
  
<div class="control-group">
  <label class="control-label" for="statut_juridique">Statut juridique *</label>
  <div class="controls">
  <select  class="input-xxlarge" name="statut_juridique" id="statut_juridique" >
       <?php  $statutjuridique = new Application_Model_EuStatutJuridiqueMapper();
		$selectstatutjuridique = $statutjuridique->fetchAll();?>
               <option value="">Choisir un statut juridique</option>
    <?php foreach ($selectstatutjuridique as $selectstatutjuridique): ?>
               <option value="<?php echo $selectstatutjuridique->code_statut; ?>" <?php if($this->souscription->code_statut == $selectstatutjuridique->code_statut){echo ' selected="selected"';}?>><?php echo htmlentities($selectstatutjuridique->libelle_statut); ?></option>
    <?php endforeach; ?>
               </select>
  </div>
  </div>

</div>

<div class="control-group">
<label class="control-label" for="souscription_mobile">Cellulaire du souscripteur  *</label>
<div class="controls">
<input type="number" name="souscription_mobile" id="souscription_mobile" placeholder="Cellulaire du souscripteur" class="input-xxlarge"  value="<?php echo $this->souscription->souscription_mobile; ?>" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="souscription_email">E-mail du souscripteur  </label>
<div class="controls">
<input type="email" name="souscription_email" id="souscription_email" placeholder="E-mail du souscripteur" class="input-xxlarge"  value="<?php echo $this->souscription->souscription_email; ?>" />
</div>
</div>

    
<div class="control-group">
<label class="control-label" for="souscription_ville">Ville du souscripteur  </label>
<div class="controls">
<input type="text" name="souscription_ville" id="souscription_ville" placeholder="Ville du souscripteur " class="input-xxlarge" value="<?php echo $this->souscription->souscription_ville; ?>"  />
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="souscription_quartier">Quartier du souscripteur  </label>
<div class="controls">
<input type="text" name="souscription_quartier" id="souscription_quartier" placeholder="Quartier du souscripteur " class="input-xxlarge" value="<?php echo $this->souscription->souscription_quartier; ?>"  />
</div>
</div>

<div class="control-group">
  <label class="control-label" for="souscription_programme">Type de programme *</label>
  <div class="controls">
  <label for="souscription_programme_cmfh" class="radio">
  <input name="souscription_programme" type="radio"  id="souscription_programme_cmfh" value="CMFH" <?php if($this->souscription->souscription_programme == "CMFH"){echo ' checked="checked"';}?> onclick="document.getElementById('cmfh').style.display='block';">
  CMFH</label>

  <?php /*?><label for="souscription_programme_caps" class="radio">
  <input name="souscription_programme" type="radio"  id="souscription_programme_caps" value="CAPS" <?php if($this->souscription->souscription_programme == "CAPS"){echo ' checked="checked"';}?> onclick="document.getElementById('cmfh').style.display='none';">
  CAPS</label><?php */?>

  <label for="souscription_programme_kacm" class="radio">
  <input name="souscription_programme" type="radio"  id="souscription_programme_kacm" value="KACM" <?php if($this->souscription->souscription_programme == "KACM"){echo ' checked="checked"';}?> onclick="document.getElementById('cmfh').style.display='none';nbremontantkacm();">
  KACM</label>
  </div>
  </div>
  
  <div id="cmfh" style=' <?php if($this->souscription->souscription_programme == "CMFH"){?> display:block;<?php }else{?> display:none;<?php }?>'>
<div class="control-group">
<label class="control-label" for="souscription_type_candidat">Type CMFH </label>
<div class="controls">
<select name="souscription_type_candidat" id="souscription_type_candidat"  class="input-xxlarge" onchange="nbremontantcmfh(this.value);">
        <?php $ttype_candidat = new Application_Model_DbTable_EuTypeCandidat();
        $results = $ttype_candidat->fetchAll();?>
  <option value="">Choisir le type</option>
    <?php foreach ($results as $type_candidat): ?>
               <option value="<?php echo $type_candidat->id_type_candidat; ?>" <?php if($this->souscription->souscription_type_candidat == $type_candidat->id_type_candidat){echo ' selected="selected"';}?>><?php echo ($type_candidat->libelle_type_candidat); ?> (au moins <?php echo ($type_candidat->libelle_type_candidat); ?> Comptes Marchands)</option>
    <?php endforeach; ?>
</select>
</div>
</div>

</div>

<?php /*?><div class="control-group">
<label class="control-label" for="souscription_filiere">Filière </label>
<div class="controls">
<select name="souscription_filiere" id="souscription_filiere"  class="input-xxlarge">
        <?php $tfiliere = new Application_Model_DbTable_EuFiliere();
        $results = $tfiliere->fetchAll();?>
  <option value="">Choisir la filière</option>
    <?php foreach ($results as $filiere): ?>
               <option value="<?php echo $filiere->id_filiere; ?>" <?php if($this->souscription->souscription_filiere == $filiere->id_filiere){echo ' selected="selected"';}?>><?php echo ($filiere->nom_filiere); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div><?php */?>

<div class="control-group">
<label class="control-label" for="code_activite">Domaines d'activité</label>
<div class="controls">
<select name="code_activite" id="code_activite"  class="input-xxlarge"  onchange="ouvre_competences(this.value);">
        <?php $tactivite = new Application_Model_DbTable_EuActivite();
        $results = $tactivite->fetchAll();?>
  <option value="">Choisir le domaine </option>
    <?php foreach ($results as $activite): ?>
               <option value="<?php echo $activite->code_activite; ?>" <?php if($this->souscription->code_activite == $activite->code_activite){echo ' selected="selected"';}?>><?php echo ($activite->nom_activite); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

<div id="niv2">

<div class="control-group">
<label class="control-label" for="id_metier">Métier </label>
<div class="controls">
<select name="id_metier" id="id_metier"  class="input-xxlarge">
        <?php $tmetier = new Application_Model_DbTable_EuMetier();
        $select = $tmetier->select();
		$select->where("code_activite = ? ", $this->souscription->code_activite);
        $results = $tmetier->fetchAll($select);
		?>
  <option value="">Choisir le métier</option>
    <?php foreach ($results as $metier): ?>
               <option value="<?php echo $metier->id_metier; ?>" <?php if($this->souscription->id_metier == $metier->id_metier){echo ' selected="selected"';}?>><?php echo ($metier->libelle_metier); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="id_competence">Compétence </label>
<div class="controls">
<select name="id_competence" id="id_competence"  class="input-xxlarge">
        <?php $tcompetence = new Application_Model_DbTable_EuCompetence();
        $select = $tmetier->select();
		$select->where("code_activite = ? ", $this->souscription->code_activite);
        $results = $tcompetence->fetchAll($select);
		?>
  <option value="">Choisir la compétence</option>
    <?php foreach ($results as $competence): ?>
               <option value="<?php echo $competence->id_competence; ?>" <?php if($this->souscription->id_competence == $competence->id_competence){echo ' selected="selected"';}?>><?php echo ($competence->libelle_competence); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

</div>

<div class="control-group">
  <label class="control-label" for="souscription_type">Type de payement *</label>
  <div class="controls">
  <label for="souscription_type_banque" class="radio">
  <input name="souscription_type" type="radio"  id="souscription_type_banque" onclick="document.getElementById('banque').style.display='block'; document.getElementById('banque2').style.display='block';document.getElementById('flooz').style.display='none';" value="Banque" <?php if($this->souscription->souscription_type == "Banque"){echo ' checked="checked"';}?>>
  Banque</label>

  <label for="souscription_type_flooz" class="radio">
  <input type="radio" name="souscription_type" id="souscription_type_flooz" value="Flooz"  onclick="document.getElementById('banque').style.display='none'; document.getElementById('banque2').style.display='none'; document.getElementById('flooz').style.display='block';" <?php if($this->souscription->souscription_type == "Flooz"){echo ' checked="checked"';}?>>
  Flooz</label>
  
  </div>
  </div>
  
  <div id="banque" style=' <?php if($this->souscription->souscription_type == "Banque"){?> display:block;<?php }else{?> display:none;<?php }?>'>
<div class="control-group">
<label class="control-label" for="souscription_banque">Banque *</label>
<div class="controls">
<select name="souscription_banque" id="souscription_banque"  class="input-xxlarge">
        <?php $tbanque = new Application_Model_DbTable_EuBanque();
        $results = $tbanque->fetchAll();?>
  <option value="">Choisir la banque</option>
    <?php foreach ($results as $banque): ?>
               <option value="<?php echo $banque->code_banque; ?>" <?php if($this->souscription->souscription_banque == $banque->code_banque){echo ' selected="selected"';}?>><?php echo ($banque->libelle_banque); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>
</div>

  <div id="flooz" style=' <?php if($this->souscription->souscription_type == "Flooz"){?> display:block;<?php }else{?> display:none;<?php }?>'>
</div>

  <div class="control-group">
<label class="control-label" for="souscription_numero">Numero de reçu de banque ou de transation Flooz   </label>
<div class="controls">
  <input type="text" name="souscription_numero" id="souscription_numero" placeholder="Numero de reçu de banque ou de transation Flooz" class="input-xxlarge" value="<?php echo $this->souscription->souscription_numero; ?>" />
</div>
</div>

  <div class="control-group">
<label class="control-label" for="souscription_date_numero">Date de reçu de banque ou de transation Flooz   </label>
<div class="controls">
  <input type="date" name="souscription_date_numero" id="souscription_date_numero" placeholder="Date de reçu de banque ou de transation Flooz" class="input-large" value="<?php echo $this->souscription->souscription_date_numero; ?>" />
</div>
</div>

  <div id="banque2" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_vignette">Scanne du reçu   </label>
<div class="controls">
  <input type="file" name="souscription_vignette" id="souscription_vignette" class="input-xxlarge" />
<input type="hidden" name="souscription_vignetteold" id="souscription_vignetteold" value="<?php echo $this->souscription->souscription_vignette; ?>" />
</div>
</div>
</div>

  <div class="control-group">
<label class="control-label" for="souscription_nombre">Nombre de compte marchant souscris  </label>
<div class="controls">
  <input type="text" name="souscription_nombre" id="souscription_nombre" placeholder="Nombre de compte marchant souscris" class="input-xxlarge" value="<?php echo $this->souscription->souscription_nombre; ?>" />
</div>
</div>
  
  <div class="control-group">
<label class="control-label" for="souscription_montant">Montant de la souscription  </label>
<div class="controls">
  <input type="text" name="souscription_montant" id="souscription_montant" placeholder="Montant de la souscription" class="input-xxlarge" value="<?php echo $this->souscription->souscription_montant; ?>" />
</div>
</div>



</fieldset> 
   
    
    

<div class="form-actions">
<input type="hidden" name="souscription_id" id="souscription_id" value="<?php echo $this->souscription->souscription_id; ?>" />

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enregistrer</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








