
<form action="listintegrateur"  method="post" class="form-horizontal">

<div class="form-group">
	       <label class="form-control-label" for="integrateur_description_probleme" style="font-weight:bold">
	          Canton *:
	       </label>
	       <div class="controls">
              <input type="text" name="integrateur_addresse" class="form-control" value="<?php echo $this->posteditcanton ;?>"/>                 
	       </div>
</div>

</form>

