<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste des offres coincidences</p></blockquote>
<?php if(count($this->entries)>0){ echo count($this->entries);?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Type</th>
								  <th>Demandeur</th>
								  <th>Montant</th>
								  <th>Categorie</th>
								  <th>Terminal d'échange</th>
								  <th>Type compte</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->date_coincidence; ?></td>
      <td><?php echo $entry->type_bon_apporteur; ?>/<?php echo $entry->type_bon_beneficiaire; ?></td>
      <td><?php echo $entry->code_membre_beneficiaire; ?></td>
      <td><?php echo $entry->montant_apporteur; ?>/<?php echo $entry->montant_beneficiaire; ?></td>
      <td><?php echo $entry->cat_produit_apporteur; ?>/<?php echo $entry->cat_produit_beneficiaire; ?></td>
      <td><?php echo $entry->code_tegc_apporteur; ?>/<?php echo $entry->code_tegc_beneficiaire; ?></td>
      <td><?php echo $entry->type_compte_apporteur; ?>/<?php echo $entry->type_compte_beneficiaire; ?></td>
      <td><div align="center">
<?php if($entry->publier >= 1){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/coincidence/publiercoincidence/id/<?php echo $entry->coincidence_id; ?>/publier/1"><i class="icon-off icon-white"></i>  Confirmation</a>&nbsp;
<?php }?>
<?php /*?>
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/coincidence/detailcoincidence/id/<?php echo $entry->coincidence_id; ?>"><i class="icon-edit icon-white"></i>  Details</a>&nbsp;

			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/coincidence/editcoincidence/id/<?php echo $entry->coincidence_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini" href="<?php echo $this->baseUrl(); ?>/coincidence/listdetailcoincidence/id/<?php echo $entry->coincidence_id; ?>"><i class="icon-edit icon-white"></i>  Fichiers</a>&nbsp;
<?php */?>
			</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune coincidence  enregistrée 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








