<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Ajout du menu de la semaine</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addappeloffre">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
<?php for ($i=0; $i < 7; $i++) { ?>   

<label class="checkbox">
  <input type="checkbox" id="jour_semaine<?php echo $i + 1; ?>" name="jour_semaine[]" value="<?php echo $i + 1; ?>">
  <?php echo joursemaine($i + 1); ?>
</label>



<?php 
$repas = new Application_Model_EuRepasMapper();
$entries = $repas->fetchAllByCodeMembre($sessionmembre->code_membre);
if(count($entries) > 0){?>
<?php foreach ($entries as $value) { ?>

<label class="checkbox inline">
  <input type="checkbox" id="id_repas<?php echo $i + 1; ?><?php echo $value->id_repas; ?>" name="id_repas[<?php echo $i; ?>][]" value="<?php echo $value->id_repas; ?>"> <?php echo $value->libelle_repas; ?>
</label>

<?php } ?>
<?php }?>

<br />
<br />
<br />


    
<?php }?>

<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter le menu de la semaine</button>
</div>
  
</form>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








