<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Ajout un repas</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addappeloffre">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    
<div class="control-group">
<label class="control-label" for="libelle_repas">Libellé du repas *</label>
<div class="controls">
<input type="text" name="libelle_repas" id="libelle_repas" placeholder="Libellé du repas" required>
</div>
</div>
    


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter un nouveau repas</button>
</div>
  
</form>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








