<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>


  <blockquote><p>Liste de mes repas</p></blockquote>
<?php if(count($this->entries) > 0) { ?> <!-- style="font-size:9px;"-->
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
	   <thead>
							  <tr>
								  <th>Libellé</th>
								  <th>Code Membre</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->libelle_repas); ?></td>
      <td><?php echo ($entry->code_membre); ?></td>
      <td><div align="center"></div></td>  
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else {?>
<div class="alert alert-info">
     Aucun repas enregistré 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








