<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>


  <blockquote><p>Liste des recurrents journaliers</p></blockquote>
<?php if(count($this->entries) > 0) { ?> <!-- style="font-size:9px;"-->
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
	   <thead>
							  <tr>
								  <th>Date</th>
								  <th>Produit</th>
								  <th>Montant journalier</th>
								  <th>Montant total</th>
								  <th>Fréquence de cumul</th>
								  <th>Canton</th>
								  <th>Code Membre</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datejourfr($entry->date_creation); ?></td>
      <td><?php 
$bpsM = new Application_Model_EuBpsMapper();
$bps = new Application_Model_EuBps();
$bpsM->find($entry->id_type_produit, $bps);
?>
<?php echo ($bps->designation); ?></td>
      <td><?php echo ($entry->montant_journalier); ?></td>
      <td><?php echo ($entry->montant_total); ?></td>
      <td><?php echo ($entry->frequence_cumul); ?></td>
      <td><?php 
$cantonM = new Application_Model_EuCantonMapper();
$canton = new Application_Model_EuCanton();
$cantonM->find($entry->id_canton, $canton);
?>
<?php echo ($canton->nom_canton); ?></td>
		<td><?php echo ($entry->code_membre); ?></td>
      <td><div align="center"></div></td>  
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else {?>
<div class="alert alert-info">
     Aucun recurrent journalier enregistré 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








