<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>


  <blockquote><p>Liste des commandes nr</p></blockquote>
<?php if(count($this->entries) > 0) { ?> <!---->
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
	   <thead>
							  <tr>
								  <th>Date</th>
								  <th>Produit</th>
								  <th>Désignation</th>
								  <th>Prix Unitaire</th>
								  <th>Quantité</th>
								  <th>Total BPS</th>
								  <th>Total nr</th>
								  <th>PRK</th>
								  <th>Date Livraison</th>
								  <th>Code Membre</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datefr($entry->date_commande_nr); ?></td>
      <td><?php echo ($entry->produit); ?></td>
      <td><?php echo ($entry->designation); ?></td>
      <td><?php echo ($entry->prix_unitaire); ?></td>
      <td><?php echo ($entry->quantite); ?></td>
      <td><?php echo ($entry->total_bps); ?></td>
      <td><?php echo ($entry->total_nr); ?></td>
      <td><?php echo ($entry->prk); ?></td>
	  <td><?php echo datefr($entry->date_livraison_estimer); ?></td>
      <td><?php echo ($entry->code_membre); ?></td>
      <td><div align="center"></div></td>  
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else {?>
<div class="alert alert-info">
     Aucune commande nr enregistrée 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








