<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste de mes demandes de BPS</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Objet</th>
								  <!--<th>Code Membre</th>-->
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->date_demande; ?></td>
      <td><?php echo $entry->objet_demande; ?></td>
      <?php /*?><td><?php echo $entry->code_membre_morale; ?></td><?php */?>
      <td><div align="center"><?php if($entry->publier == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/publierdemande/id/<?php echo $entry->id_demande; ?>/publier/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/publierdemande/id/<?php echo $entry->id_demande; ?>/publier/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>&nbsp;
      
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/detailsdemande/id/<?php echo $entry->id_demande; ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;
            
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/editdemande/id/<?php echo $entry->id_demande; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;
            
			<a class="btn btn-mini btn-danger"  onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/espacepersonnel/suppdemande/id/<?php echo $entry->id_demande; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune demande enregistrée 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








