<div id="view-content" style="font-size: 12px;min-height: 520px;" title="Création des comptes acteurs">
     <form method="POST" action="/eu-compte-cyber/new" id="acteur_form">
           <table style="margin-left: 15px;">
               <tbody>
                     <tr>
                         <td colspan="2">
                         <fieldset>
                            <legend>Infos sur utilisateur</legend>
                            <table>
                                <tbody>
                                    <tr>
                                        <td><label>Nom utilisateur *</label></td><td><input type="text" id="nom" name="nom" size="30" required="true"></td>
                                        <td><label>Prénom utilisateur *</label></td><td><input type="text" id="prenom" name="prenom" required="true" size="30"></td>
                                    </tr>
                                    <tr>
                                        <td><label>Login *</label></td><td><input type="text" id="login" name="login" size="30" required="true"></td>
                                        <td><label>Mot de pass *</label></td><td><input type="password" id="pwd" name="pwd" required="true" size="30"></td>
                                    </tr>
                                    <tr>
                                        <td><label>Confirmer mot de pass *</label></td><td><input type="password" id="pwd1" name="pwd1" required="true" size="30"></td>
                                        <td><label><label>Code membre</label></td><td><input id="code_membre" name="code_membre" size="30" required="true"></td>
                                    </tr>
                                    <tr>
                                        <td><label>Raison sociale *</label></td><td><input type="text" id="raison_sociale" name="raison_sociale" size="30" required="true" readonly="true"></td>
                                        <td><label>Nom && Prénom *</label></td><td><input type="text" id="nom_prenom" name="nom_prenom" required="true" size="30" readonly="true"></td>
                                    </tr>
                                    <tr> 
                                        <td><label>Groupe *</label></td><td><select id="groupe" name="groupe" required="true"></td>
                                        <td><label>Agence *</label></td><td><select id="agence" name="agence" required="true"></td>
                                    </tr>
                                    <tr> 
                                        <td><label> Description </label></td>
                                        <td> <textarea id="desc" name="desc"> </textarea> </td>
                                        <td></td><td></td>
                                    </tr>
                                </tbody>
                            </table>
                        </fieldset>
                    </td>
                    </tr>
                    <tr>
                    <td colspan="2" align="center">
                        <input id="compte_val" type="submit" value="Valider"/>
                        <input id="acteur_reset" type="reset" value="Annuler"/>
                    </td>
                    </tr>
               </tbody>
           </table>      
     </form>    
</div>
<script>
$(document).ready(function() {
    
    $(function() {
      $('#view-content').puipanel();
      $('fieldset').puifieldset();
    });
  
    
    $.get('/eu-compte-cyber/membres',
    function success(data)
    {
      $('#code_membre').autocomplete({"source": data,change: displayItem});
    });
  
  
    function displayItem()
    {
       if ($(this).val() !== '')
       {
         $.get(
           '/eu-compte-cyber/recupnom',
         {
            num_membre: $(this).val()
         },
         function success(data)
         {
            $("#raison_sociale").val(data[0]);
            $("#nom_prenom").val(data[1]);
         });
      }
    }
    
    $.get('/eu-compte-cyber/groupe',
      function success(data)
      {
        var options = '<option></option>';
        for (var i = 0; i < data.length; i++) {
        options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
        }
        $('select#groupe').html(options);
      });
  
  
     $.get('/eu-compte-cyber/agence',
     function success(data)
     {
        var options = '<option></option>';
        for (var i = 0; i < data.length; i++) {
        options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
        }
        $('select#agence').html(options);
     });
  
  
  
  
  
  
})   
</script>    