<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>
            
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques2.js"></script>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/fondateurs.js"></script><?php */?>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/capasenrolement.js"></script><?php */?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banquespays.js"></script>


<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">
<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

<?php /*
$banque = new Application_Model_EuBanque();
$banque_mapper = new Application_Model_EuBanqueMapper();
$banque_mapper->find($sessionmembre->code_banque, $banque);
          
$membre_morale = new Application_Model_EuMembreMorale();
$membre_morale_mapper = new Application_Model_EuMembreMoraleMapper();
$membre_morale_mapper->find($banque->code_membre_morale, $membre_morale);
*/

 ?>

<blockquote><p>Souscription au Bon d'Achat neutre (BAn) par FLOOZ</p></blockquote>
  <?php if(isset($sessionmembre->error) && $sessionmembre->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = ""; ?>
    </div>
  <?php } ?>
  
    <?php if(isset($sessionmembre->code_BAn) && $sessionmembre->code_BAn != "") { ?>
<blockquote>
  <a href="/souscriptionbon/bonachatneutrepdf/code/<?php echo $sessionmembre->code_BAn; ?>" target="_blank"><span style="color:#800080;">Télécharger votre Bon d'Achat neutre (<strong>BAn</strong>)</span></a> <br /><br />

  <?php $sessionmembre->code_BAn = "";?>
</blockquote>
  <?php } ?>

  <?php if(!isset($sessionmembre->code_BAn) || $sessionmembre->code_BAn == "") { ?>
              <blockquote>Informations concernant le SMS de paiement</blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addbantmoneyflooz" name="addbantmoneyflooz">
<fieldset>
<legend>Remplir le formulaire</legend>
  


<div class="control-group">
<label class="control-label" for="code_membre">Code Membre  * </label>
<div class="controls">
  <input type="text" name="code_membre" id="code_membre" placeholder="Code Membre" class="input-xxlarge"  required="required" readonly />
</div>
</div>


<div class="control-group">
<label class="control-label" for="reference_tmoney">Reference du SMS de paiement  * </label>
<div class="controls">
  <input type="text" name="reference_tmoney" id="reference_tmoney" placeholder="Reference du SMS de paiement" class="input-xxlarge"  required="required" />
</div>
</div>



</fieldset>
<div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button id="submit" type="submit" class="btn btn-primary">Enregistrer la souscription au Bon d'Achat neutre BAn par FLOOZ</button>
</div>
 
                            
  
</form>
  
<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
//outilqr('addeli');
outilqrformobligatoire("addbantmoneyflooz","submit");
</script>

  <?php } ?>



    


</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








