<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Modification d'une demande de BPS</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="editdemande">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    
<div class="control-group">
<label class="control-label" for="objet_demande">Objet de la demande de BPS *</label>
<div class="controls">
<input class="input-xxlarge" type="text" name="objet_demande" id="objet_demande" placeholder="Objet de la demande de BPS" value="<?php echo $this->demande->objet_demande; ?>" required>
</div>
</div>


<div class="control-group">
<label class="control-label" for="description_demande">Description de la demande </label>
<div class="controls">
<textarea class="input-xxlarge" name="description_demande" id="description_demande" placeholder="Description de la demande de BPS"><?php echo $this->demande->description_demande; ?></textarea>
</div>
</div>
    


<div class="form-actions">
<input name="code_membre_morale" type="hidden" id="code_membre_morale" value="<?php echo $sessionmembre->code_membre; ?>" />  
<input name="id_demande" type="hidden" id="id_demande" value="<?php echo $this->demande->id_demande; ?>" />  
<input name="publier" type="hidden" id="publier" value="1" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier la demande</button>
</div>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








