<?php $sessionmembre = new Zend_Session_Namespace('membre');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste de mes bons</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>ZPPE</th>
								  <th>Numéro</th>
								  <th>Montant</th>
								  <th>Montant crédit</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->bon_date); ?></td>
      <td><?php $zppeM = new Application_Model_EuZppeMapper();
$zppe = new Application_Model_EuZppe();
$zppeM->find($entry->bon_zppe, $zppe);
?><?php echo ($zppe->zppe_libelle); ?></td>
      <td><?php echo ($entry->bon_numero); ?></td>
      <td><?php echo ($entry->bon_montant); ?></td>
      <td><?php echo ($entry->bon_montant_credit); ?></td>
      <td><div align="center"><?php if($entry->publier == 1){?>
            <a class="btn btn-mini btn-primary" href="<?php echo $this->baseUrl(); ?>/administration/telechargerbon/id/<?php echo $entry->bon_id; ?>"><i class="icon-cog icon-white"></i>  Télécharger</a>&nbsp;
			<?php }?></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun bon enrégistré 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








