<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Offres et Demandes d'échanges</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  <tr>
								  <th>Type</th>
								  <th>Type Offre vs Demande</th>
								  <th>Compte à débiter</th>
								  <th>Solde</th>
								  <th>Compte à créditer</th>
								  <th>Date</th>
								  <th>Discussion</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
<?php 
if(strpos($entry->id_credit, "CAPA") !== false){
$compte_ts_M = new Application_Model_EuCapaTsMapper();
$compte_ts = new Application_Model_EuCapaTs();
$compte_ts_M->find($entry->id_credit, $compte_ts);

$operationM = new Application_Model_EuOperationMapper();
$operation = new Application_Model_EuOperation();
$operationM->find($compte_ts->id_operation, $operation);

$code_produit = $compte_ts->code_produit;
$lib_op = htmlentities($operation->lib_op);
$datefin = substr($compte_ts->date_capa,0,9);
$montant = number_format($compte_ts->montant_solde, 0, ',', ' ');

}else if($entry->id_credit > 0){
$compte_ts_M = new Application_Model_EuCompteCreditTsMapper();
$compte_ts = new Application_Model_EuCompteCreditTs();
$compte_ts_M->find($entry->id_credit, $compte_ts);

$operationM = new Application_Model_EuOperationMapper();
$operation = new Application_Model_EuOperation();
$operationM->find($compte_ts->id_operation, $operation);

$code_produit = $compte_ts->code_produit;
$lib_op = htmlentities($operation->lib_op);
$datefin = substr($compte_ts->datefin,0,9);
$montant = number_format($compte_ts->montant, 0, ',', ' ');

}else{
$compte_M = new Application_Model_EuCompteMapper();
$compte = new Application_Model_EuCompte();
$compte_M->find($entry->code_compte, $compte);

$categorieM = new Application_Model_EuCategorieCompteMapper();
$categorie = new Application_Model_EuCategorieCompte();
$categorieM->find($compte->code_cat, $categorie);

$code_produit = $compte->code_cat;
$lib_op = htmlentities($categorie->lib_cat);
$datefin = "";//substr($compte->date_alloc,0,9)
$montant = number_format($compte->solde, 0, ',', ' ');
}
?>
    <tr>
      <td><?php echo $entry->type_offre_demande; ?></td>
      <td><?php echo $entry->type_credit_of; ?> vs <?php echo $entry->type_credit_de; ?></td>
      <td><?php echo $entry->type_credit_of; ?><?php //echo $code_produit; ?></td>
      <td><div align="right"><?php echo $montant; ?></div></td>
      <td><?php echo $entry->type_credit_de; ?><?php //echo $lib_op; ?></td>
      <td><?php echo $entry->date_offre_demande;//$datefin; ?></td>
      <td><div align="center">
      <?php $id_message = 0;$clotureresult = FALSE;
$offredemandeM = new Application_Model_EuOffreDemandeMapper();
$rowsoffredemande = $offredemandeM->fetchAllByMembre($sessionmembre->code_membre);
foreach ($rowsoffredemande as $rows) {
if($entry->type_offre_demande == "Demande"){
$messageM = new Application_Model_EuOffreDemandeMessageMapper();
$rowsmessage = $messageM->fetchAllByOffreDemande($rows->id_offre_demande, $entry->id_offre_demande);
foreach ($rowsmessage as $row) {
$id_message = $row->id_message;
}
$cloture = new Application_Model_EuOffreDemandeCloture();
$clotureM = new Application_Model_EuOffreDemandeClotureMapper();
$clotureresult = $clotureM->fetchAllByDemande($entry->id_offre_demande, $cloture);
}else if($entry->type_offre_demande == "Offre"){
$messageM = new Application_Model_EuOffreDemandeMessageMapper();
$rowsmessage = $messageM->fetchAllByOffreDemande($entry->id_offre_demande, $rows->id_offre_demande);
foreach ($rowsmessage as $row) {
$id_message = $row->id_message;
}
$cloture = new Application_Model_EuOffreDemandeCloture();
$clotureM = new Application_Model_EuOffreDemandeClotureMapper();
$clotureresult = $clotureM->fetchAllByOffre($entry->id_offre_demande, $cloture);
}
}
$message = new Application_Model_EuOffreDemandeMessage();
$messageM = new Application_Model_EuOffreDemandeMessageMapper();
$result = $messageM->find($id_message, $message);
	  ?>
	  <?php if($clotureresult !== FALSE){?>
      <a class="btn btn-mini btn-danger" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/listoffredemandecloture"><i class="icon-plus icon-white"></i>  Clôturer</a>
<?php } else if($result !== FALSE){?>
      <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/listoffredemandemessage/id/<?php echo $entry->id_offre_demande; ?>/offre/<?php echo $message->id_offre; ?>/demande/<?php echo $message->id_demande; ?>/type/<?php echo $entry->type_offre_demande; ?>"><i class="icon-plus icon-white"></i>  Continuer</a>
<?php } else {?>
      <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/espacepersonnel/addoffredemandemessage/id/<?php echo $entry->id_offre_demande; ?>"><i class="icon-plus icon-white"></i>  Entamer</a>
	  <?php }?>
      </div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune offre ou demande enrégistrée 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








