<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>


<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>


<?php if(count($this->entries)>0){?> 
<?php 
if($this->ctc == "NB"){
$color = "#00F";
$btncolor = "primary";
}else if($this->ctc == "NR"){
$color = "#F00";
$btncolor = "danger";
}else if($this->ctc == "NN"){
$color = "#000";
$btncolor = "inverse";
}
?>

  <?php 
$categoriecompteM = new Application_Model_EuCategorieCompteMapper();
$categoriecompte = new Application_Model_EuCategorieCompte();
$categoriecompteM->find($this->code_cat, $categoriecompte);
?>

  <blockquote><p>Opérations <strong style="color:<?php echo $color; ?>;"><?php echo htmlentities($this->ctc); ?>-<?php echo htmlentities($categoriecompte->code_cat); ?></strong>
<small>Opérations effectuées sur le compte <strong><?php echo htmlentities($this->ctc); ?>-<?php echo htmlentities($categoriecompte->code_cat); ?> </strong></small></p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
  <thead>
    <tr>
      <th>Opérations Effectuées</th>
      <th><div align="center">Date</div></th>
      <th><div align="center">Montant</div></th>
      <th><div align="center">Utiliser</div></th>
      <th><div align="center">Solde</div></th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php 
$operationM = new Application_Model_EuOperationMapper();
$operation = new Application_Model_EuOperation();
$operationM->find($entry->id_operation, $operation);
?><?php echo htmlentities($operation->lib_op); ?></td>
      <td><div align="center"><?php echo $entry->date_capa; ?></div></td>
      <td><div align="right"><?php echo number_format($entry->montant, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format($entry->montant_utiliser, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format($entry->montant_solde, 0, ',', ' '); ?></div></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php }else{?>
<div class="alert alert-info">
  Aucune opératon effectuée sur ce compte
</div>
<?php }?>






</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








