<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Modification du code secret</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addmembre">
  <?php if(isset($sessionmembre->error) && $sessionmembre->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = "";?>
    </div>
  <?php }?>
  
    
<?php /* ?><div class="control-group">
<label class="control-label" for="ancien">Ancien code secret *</label>
<div class="controls">
<input type="password" name="ancien" id="ancien" placeholder="Ancien code secret" required>
</div>
</div><?php */ ?>

<div class="control-group">
<label class="control-label" for="nouveau">Nouveau code secret *</label>
<div class="controls">
<input type="password" name="nouveau" id="nouveau" placeholder="Nouveau code secret" required>
</div>
</div>

<div class="control-group">
<label class="control-label" for="confirmer">Confirmer le nouveau *</label>
<div class="controls">
<input type="password" name="confirmer" id="confirmer" placeholder="Confirmer le nouveau" required>
</div>
</div>



<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-success">Modifier le code secret</button>
</div>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








