<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Modification du profil</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addmembre">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
<?php if (substr($sessionmembre->code_membre, -1) == "P") {?>

<fieldset>  

  <legend>Etat civil</legend>
<div class="">
  
  
<div class="span6">
    
  <div class="control-group">
  <label class="control-label" for="sitfam_membre">Situation matrimoniale *</label>
  <div class="controls">
  <select name="sitfam_membre" id="sitfam_membre"  required="required">
<option value="">Choisir situation</option>
<option value="C" <?php if($this->membre->sitfam_membre == 'C'){echo ' selected="selected"';}?>>Célibataire</option>
<option value="D" <?php if($this->membre->sitfam_membre == 'D'){echo ' selected="selected"';}?>>Divorcé(e)</option>
<option value="M" <?php if($this->membre->sitfam_membre == 'M'){echo ' selected="selected"';}?>>Marié(e)</option>
<option value="V" <?php if($this->membre->sitfam_membre == 'V'){echo ' selected="selected"';}?>>Veuf(ve)</option>
</select>
  </div>
  </div>
  
</div>
  <div class="span6">
     
  <div class="control-group">
  <label class="control-label" for="nbr_enf_membre">Nombre d'enfant *</label>
  <div class="controls">
  <input type="text" name="nbr_enf_membre" id="nbr_enf_membre" value="<?php echo $this->membre->nbr_enf_membre; ?>" placeholder="Nombre d'enfant"  required="required" />
  </div>
  </div>
    
  
  </div>

  </div>


  <legend>Adresse</legend>


<div class="">

  <div class="span6">

  <div class="control-group">
  <label class="control-label" for="bp_membre">BP</label>
  <div class="controls">
  <input type="text" name="bp_membre" id="bp_membre" value="<?php echo $this->membre->bp_membre; ?>" placeholder="BP" />
  </div>
  </div>

  <div class="control-group">
  <label class="control-label" for="quartier_membre">Quartier *</label>
  <div class="controls">
  <input type="text" name="quartier_membre" id="quartier_membre" value="<?php echo $this->membre->quartier_membre; ?>" placeholder="Quartier"  required="required" />
  </div>
  </div>


  <div class="control-group">
  <label class="control-label" for="ville_membre">Ville *</label>
  <div class="controls">
  <input type="text" name="ville_membre" id="ville_membre" value="<?php echo $this->membre->ville_membre; ?>" placeholder="Ville"  required="required" />
  </div>
  </div>

  </div>
<div class="span6">

  <div class="control-group">
  <label class="control-label" for="email_membre">Email</label>
  <div class="controls">
<div class="input-prepend">
      <span class="add-on"><i class="icon-envelope"></i></span>
  <input type="email" name="email_membre" id="email_membre" value="<?php echo $this->membre->email_membre; ?>" placeholder="Email"  />
  </div>
  </div>
  </div>
    
  <?php /*?><div class="control-group">
  <label class="control-label" for="tel_membre">Téléphone</label>
  <div class="controls">
  <input type="text" name="tel_membre" id="tel_membre" value="<?php echo $this->membre->tel_membre; ?>" placeholder="Téléphone" />
  </div>
  </div><?php */?>
    

    <div class="control-group">
  <label class="control-label" for=""></label>
  <div class="controls">
&nbsp;<br />&nbsp;
  </div>
  </div>


  </div>
  
  </div>  
  
  <legend>Autres informations</legend>




<div class="">

  <div class="span6">

  <div class="control-group">
  <label class="control-label" for="profession_membre">Profession *</label>
  <div class="controls">
  <input type="text" name="profession_membre" id="profession_membre" value="<?php echo $this->membre->profession_membre; ?>" placeholder="Profession"  required="required" />
  </div>
  </div>

  </div>
<div class="span6">

  <div class="control-group">
  <label class="control-label" for="formation">Formation</label>
  <div class="controls">
  <input type="text" name="formation" id="formation" value="<?php echo $this->membre->formation; ?>" placeholder="Formation" />
  </div>
  </div>
  
</div>  

  </div>  


</fieldset>

<?php } else if (substr($sessionmembre->code_membre, -1) == "M") {?>


<fieldset>
 
  <legend>Informations membres morales</legend>
<div class="">
  
  
<div class="span6">
    
    
  <div class="control-group">
  <label class="control-label" for="domaine_activite">Domaine d'activité </label>
  <div class="controls">
  <input type="text" name="domaine_activite" id="domaine_activite" value="<?php echo $this->membre->domaine_activite; ?>" placeholder="Domaine d'activité" />
  </div>
  </div>
   
  
</div>
  <div class="span6">
    

  <div class="control-group">
  <label class="control-label" for="site_web">Site web</label>
  <div class="controls">
  <input type="text" name="site_web" id="site_web" value="<?php echo $this->membre->site_web; ?>" placeholder="Site web" />
  </div>
  </div>
         
  
  </div>

  </div>


  <legend>Adresse</legend>


<div class="">

  <div class="span6">

  <div class="control-group">
  <label class="control-label" for="bp_membre">BP</label>
  <div class="controls">
  <input type="text" name="bp_membre" id="bp_membre" value="<?php echo $this->membre->bp_membre; ?>" placeholder="BP" />
  </div>
  </div>

  <div class="control-group">
  <label class="control-label" for="quartier_membre">Quartier *</label>
  <div class="controls">
  <input type="text" name="quartier_membre" id="quartier_membre" value="<?php echo $this->membre->quartier_membre; ?>" placeholder="Quartier"  required="required" />
  </div>
  </div>


  <div class="control-group">
  <label class="control-label" for="ville_membre">Ville *</label>
  <div class="controls">
  <input type="text" name="ville_membre" id="ville_membre" value="<?php echo $this->membre->ville_membre; ?>" placeholder="Ville"  required="required" />
  </div>
  </div>


  
    </div>
<div class="span6">

  <div class="control-group">
  <label class="control-label" for="email_membre">Email *</label>
  <div class="controls">
<div class="input-prepend">
      <span class="add-on"><i class="icon-envelope"></i></span>
  <input type="text" name="email_membre" id="email_membre" value="<?php echo $this->membre->email_membre; ?>" placeholder="Email"  required="required" />
  </div>
  </div>
  </div>

    
  <?php /*?><div class="control-group">
  <label class="control-label" for="tel_membre">Téléphone</label>
  <div class="controls">
  <input type="text" name="tel_membre" id="tel_membre" value="<?php echo $this->membre->tel_membre; ?>" placeholder="Téléphone" />
  </div>
  </div><?php */?>
    
    
       
  <div class="control-group">
  <label class="control-label" for=""></label>
  <div class="controls">
&nbsp;<br />&nbsp;
  </div>
  </div>
  
  </div>
  
  </div>  
 

</fieldset> 



<?php }?>

<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-success">Modifier le profil</button>
</div>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








