<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Vérification des questions et réponses secrètes</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addreponse">
  <?php if(isset($sessionmembre->error) && $sessionmembre->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = "";?>
    </div>
  <?php }?>
  

<?php 
$reponse = new Application_Model_EuReponseMapper();
$entries = $reponse->fetchAllByMembre($sessionmembre->code_membre);
if(count($entries) > 0){?>
<?php $i = 0; ?>
<?php foreach ($entries as $value) { ?>
<?php $i++; ?>
<legend>Question <?php echo $i; ?></legend>
<div class="">

<div class="span6">
<div class="control-group">
<label><?php echo $value->question_libelle; ?></label>
<input name="question_id[]" type="hidden" id="question_id<?php echo $i; ?>" value="<?php echo $value->question_id; ?>" />
</div>
</div>

<div class="span6">
<div class="control-group">
<label class="control-label" for="reponse_libelle">Réponse *</label>
<div class="controls">
<input class="input-large" type="text" name="reponse_libelle[]" id="reponse_libelle<?php echo $i; ?>" placeholder="Réponse" required>
</div>
</div>

</div>
</div>
<?php }?>
<?php } ?>






<legend></legend>



<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Vérifier les réponses</button>
</div>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








