<div id="view-content" class="ui-widget">
    <div class="ui-widget-header ui-corner-top" style="height: 25px;padding-bottom: 7px; padding-left: 7px;">
        <h3>Domiciliation PRE au TEGCp</h3>
    </div>
    <div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <form action="/eu-tegcp/domicilierimm" name="fm_domicil" method="POST" id="fm_domicil">
            <input type="hidden" name="cpteur" id="cpteur" value="1"/>
            <div>
                <fieldset>
                    <legend>Informations sur la domiciliation</legend>
                    <table>
                        <tr>
                        <table border="1" style="margin: 5px;" id="tab_salaire">
                            <thead>
                                <tr style="text-align: left;">
                                    <th style="width: 180px;">Code membre</th><th style="width: 260px;">Nom</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><input id="num_membre1" type="text" name="num_membre1" value="" required="true" style="width: 185px;"/></td>
                                    <td><input id="nom1" type="text" name="nom1" value="" style="width: 260px;" readonly="readonly"/></td>
                                </tr>
                            </tbody>
                        </table>   
                        <table>
                            <div align="center">
                                <input id="add" type="button" value="Ajouter" onclick="addRow('tab_salaire')"/>
                                <input id="remove" type="button" value="Supprimer" onclick="deleteRow('tab_salaire')"/>
                                <input type='button' value="Afficher" name="afficher" id="afficher" />
                                <input type="reset" value="Rafraichir" name="refresh" id="refresh"   />
                            </div>
                        </table>
                        </tr>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Informations sur le cumul des crédits domiciliés</legend>
                    <table>
                        <tr>
                            <td>Montant total domicilié *</td><td><input name="mt_obtenu" id="mt_obtenu" class="" value="" disabled="disabled"/></td>
                            <td>Périodes de remboursement *</td><td><input name="nb_periode" id="nb_periode" class="" value="" disabled="disabled" size="15"/></td>
                        </tr>
                    </table>
                </fieldset>
            </div>
            <table id="tbl-credit"></table>
            <div id="pg-credit"></div>
            <br>
            <div style="margin-left: 150px">
                <input type="button" value="Valider" name="valider" id="valider"   />
                <input id="t_annuler" type="button" value="Annuler" />
            </div>
        </form>
    </div>
    <script type="text/javascript">
        $("#tbl-credit").jqGrid({
            url:'<?php echo $this->url(array('action' => 'creditsimm')); ?>',
            datatype: "json",
            mtype: 'GET',
            colNames:['Numéro membre','Ressource','Montant placé','Montant crédit','Montant utilisé','Date dépôt','Code crédit','Periode','Investissement'],
            height:'100%', width:810,
            colModel:[
                {name:'num_membre',index:'num_membre', width: 160, editable: false,align:"left"},
                {name:'produit',index:'produit', width: 110, align:"left", editable: false},
                {name:'mt_place',index:'mt_place', width: 150, align:"right", editable: false,formatter:'number'},
                {name:'mt_credit',index:'mt_credit', width: 150, align:"right", editable: false,formatter:'number'},
                {name:'mt_utilise',index:'mt_utilise', width: 150, align:"right", editable: true,formatter:'number' , hidden:true},
                {name:'date_depot',index:'date_depot', width: 120, align:"left", editable: false},
                {name:'code_credit',index:'code_credit', width: 50, align:"left", editable: false, hidden:true},
                {name:'periode',index:'periode', width: 5, align:"left", editable: false, hidden:true},
                {name:'mont_invest',index:'mont_invest', width: 15, align:"left", editable: false, hidden:true}
            ],
            rowNum:30,
            rowList:[30,50,100],
            rownumbers:true,
            pager: '#pg-credit',
            sortname:"date_octroi",
            viewrecords: true,
            multiselect:true,
            sortorder: "ASC",
            caption:"Comptes des crédits des membres",
            forceFit : true, 
            cellEdit: true, 
            cellsubmit: 'clientArray',
            onSelectRow: function(id,status){
                var montant = $('#mt_obtenu').val();
                var period=$('#nb_periode').val();
                if(id != 0 || id != null){
                    var data = jQuery('#tbl-credit').jqGrid('getRowData',id);
                    var value = 0;
                    var nb=0;
                    var mt_credit = data.mont_invest;
                    var periode=data.periode;
                    montant = 0;
                    if(montant == ''){
                        montant = 0;
                    }else{
                        montant = parseInt(montant,10);
                    }if(period==''){
                        period=0;
                    }else{
                        period = parseInt(period,10);
                    }
                    if(status == true){
                        value = parseInt(montant) + parseInt(mt_credit);
                        nb = parseInt(period) + parseInt(periode);
                        $('#mt_obtenu').val(value);
                        $('#nb_periode').val(nb);
                    }else{
                        value = montant - parseInt(mt_credit);
                        nb = parseInt(period) - parseInt(periode);
                        $('#mt_obtenu').val(value);
                        $('#nb_periode').val(nb);
                    }
                    lastsel=id; 
                }
            },
            onSelectAll: function(ids,status){
                var montant = $('#mt_obtenu').val();
                var period=$('#nb_periode').val();
                if(status == true){
                    montant = 0;
                    if(montant == ''){
                        montant = 0;
                    }else{
                        montant = parseInt(montant,10);
                    }
                    period=0;
                    if(period==''){
                        period=0;
                    }else{
                        period = parseInt(period,10);
                    }
                    for(var i = 0;i < ids.length;i++){
                        var id = ids[i];
                        var data = jQuery('#tbl-credit').jqGrid('getRowData',id);
                        var mt_credit = data.mont_invest;
                        var periode=data.periode;
                        montant += parseInt(mt_credit);
                        period += parseInt(periode);
                    }
                    $('#mt_obtenu').val(montant);
                    $('#nb_periode').val(period);
                }else{
                    $('#mt_obtenu').val(0); 
                    $('#nb_periode').val(0);
                }
            }
        });
        $("#tbl-credit").jqGrid('navGrid','#pg-credit',{edit:false,add:false,del:false,search:true});
        
        var compteur = 1;
        $(document).ready(function ()
        {
            $('#refresh').button();
            $('#valider').button();
            $('#t_annuler').button();
            $('#add').button();
            $('#remove').button();
            $('#afficher').button();
                        
            $('#t_annuler').click(function()
            {
                window.location="/eu-tegcp/";
            }); 
           
            $.get( "/eu-tegcp/change",
            function success(data)           
            {
                $("input#num_membre1").autocomplete({"source":data});                  
            });
            
            $('#num_membre1').blur(function(e)
            {
                if($(this).val() != '')
                {
                    $.get(
                    '/eu-tegcp/recupnom',
                    {
                        num_membre: $(this).val()
                    },
                    function success(data)
                    {
                        $("#nom1").val(data);
                    });
                }
                e.preventDefault();
            });
            
            $('#afficher').click(function(){
                var tab=new Array();
                for(var i=1;i<=compteur;i++)
                {
                    tab[i-1]=$('#num_membre' + i).val();           
                }
                jQuery("#tbl-credit").jqGrid('setGridParam',{url:"/eu-tegcp/creditsimm?lignes="+tab}).trigger('reloadGrid');
            });
        });
        
        function addRow(tableID) {

            var table = document.getElementById(tableID);
            var rowCount = table.rows.length;
            var cpte = rowCount;
            var row = table.insertRow(rowCount);
            
            var cell1 = row.insertCell(0);
            var element0 = document.createElement("input");
            element0.type = "text";
            element0.setAttribute("id","num_membre" + cpte);
            element0.setAttribute("name","num_membre" + cpte); 
            element0.setAttribute("style","width:185px;");
            cell1.appendChild(element0);

            var cell2 = row.insertCell(1);
            var element1 = document.createElement("input");
            element1.type = "text";
            element1.setAttribute("id","nom" + cpte);
            element1.setAttribute("name","nom" + cpte);
            element1.setAttribute("style","width:260px;");
            element1.setAttribute("readonly","true");
            cell2.appendChild(element1);
            
            $.get( "/eu-tegcp/change",
            function success(data)
            {
                $("#num_membre"+ cpte).autocomplete({"source":data});
            });
            
            $('#num_membre' + cpte).blur(function(e)
            {
                if($(this).val() != '')
                {
                    $.get(
                    '/eu-tegcp/recupnom',
                    {
                        num_membre: $(this).val()
                    },
                    function success(data)
                    {
                        $("#nom"+cpte).val(data);
                    });
                }
                e.preventDefault();
            });
            
            compteur = compteur + 1;
            document.getElementById("cpteur").setAttribute('value',compteur);
        }

        function deleteRow(tableID) {
            try {
                var table = document.getElementById(tableID);
                var rowCount = table.rows.length - 1;
                if(rowCount>1){
                    table.deleteRow(rowCount);
                }
                compteur = compteur - 1;
                document.getElementById("cpteur").setAttribute('value',compteur);
            }catch(e) {
                alert(e);
            }
        }
        
        $('#valider').click(
        function(){
            var sel;
            sel = jQuery("#tbl-credit").jqGrid('getGridParam','selarrrow');
            var tab=new Array();  
            var rowsel;
            rowsel = jQuery("#tbl-credit").jqGrid('getGridParam','selrow');
            for(var i=0; i<sel.length; i++) {
                tab[i]=jQuery("#tbl-credit").jqGrid('getRowData',sel[i]);   
            };
            if(rowsel)
            {
                $.get('/eu-tegcp/createimm?mt_obtenu='+$('#mt_obtenu').val()+'&nb_periode='+$('#nb_periode').val(),{
                    lignes:tab
                },
                function success(data){
                    var tab=new Array();
                    for(var i=1;i<=10;i++)
                    {
                        tab[i-1]=$('#num_membre' + i).val();           
                    }
                    if(data == 'good'){
                        jQuery("#tbl-credit").jqGrid('setGridParam',{url:"/eu-tegcp/creditsimm?lignes="+tab}).trigger('reloadGrid');
                        $("#mt_obtenu").val('');
                        $("#nb_periode").val('');
                        alert('Opération effectuée avec succes');
                    }
                    else if(data=="cool"){
                        alert("Ce client à déjà domicilié son payement");
                    }
                    else if(data=="bad_domi"){
                        alert("Ce crédit a été domicilié déjà et la domiciliation est en cours.");
                    }
                    else if(data=="vol"){
                        alert("Impossible de domicilier votre investissement sur votre TEGCP");
                    }
                    else if(data == 'bad'){
                        alert("Echec de l'opération");
                    }
                    else if(data == "err_domici"){
                        alert("Le montant du crédit est inférieur à celui de la domiciliation");
                    }
                });
            }else{
                alert('Aucune ligne de crédit sélectionnée');
            }                
        });
    </script>
</div>