<div id="view-content" class="ui-widget">
    <div class="ui-widget-header ui-corner-top" style="height: 25px;padding-bottom: 7px; padding-left: 7px;">
        <h3>Domiciliation au TEGCp (KrR en Nature) </h3>
    </div>
    <div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <form action="/eu-tegcp/domicilier" name="fm_domicil"  id="fm_domicil">
            <!--<input type="hidden" name="cpteur" id="cpteur" value="1"/>-->
            <div>
                <fieldset>
                    <legend>Informations sur la domiciliation</legend>
					<table>
					       <tr>
						       <td>Code membre Bénéficiaire *</td><td><input name="code_membre_benef" id="code_membre_benef" required="true" size="30"/></td>
							   <td>Raison sociale </td>
							   <td><input name="raison_benef" id="raison_benef" readonly="true" size="30" /></td>
						   
						   </tr>
					</table>
                    <table>
                        <tr>
							<td>Type de ressource *</td>
                            <td>
                                <select id="type_ressource" name="type_ressource" class="validate[required]" value="">
                                    <option value="r">Récurrent</option>
<!--                                    <option value="nr">Non récurrent</option>-->
                                </select>
                            </td>
							<td>Type de crédit *</td>
                            <td>
                                <select id="type_credit" name="type_credit" class="validate[required]" value="">
                                    <option value="standard">Standard</option>
                                    <option value="sqmaxui">SQMAXUI</option>
                                </select>
                            </td>
                        </tr>
                    </table>
                    <table border="1" style="margin: 5px;" id="tab_salaire">
                        <thead>
                            <tr style="text-align: left;">
                                <th style="width: 180px;">Code membre</th><th style="width: 260px;">Nom</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input id="num_membre1" type="text" name="num_membre1" value="<?php echo $this->code_membre ?>" readonly="true" style="width: 185px;"/></td>
                                <td><input id="nom1" type="text" name="nom1" style="width: 260px;" value="<?php echo $this->nom ?>"  readonly="readonly"/></td>
                            </tr>
                        </tbody>
                    </table>
                    <table>
                        <div align="center">
                            <!--<input id="add" type="button" value="Ajouter" onclick="addRow('tab_salaire')"/>-->
                            <!--<input id="remove" type="button" value="Supprimer" onclick="deleteRow('tab_salaire')"/>-->
                            <input type='button' value="Afficher" name="afficher" id="afficher" />
                            <input type="reset" value="Rafraichir" name="refresh" id="refresh"   />
                        </div>
                    </table>
                </fieldset>
                <fieldset>
                    <legend>Informations sur le cumul des crédits domiciliés</legend>
                    <table>
                        <tr>
                            <td>Montant total domicilié *</td><td><input name="mt_obtenu" id="mt_obtenu" class="validate[required,custom[onlyNumberSp]]" value="<?php echo $this->mt_obtenu ?>" readonly="true"/></td>
                        </tr>
                    </table>
                </fieldset>
            </div>
            <table id="tbl-credit"></table>
            <div id="pg-credit"></div>
            <br>
            <div style="margin-left: 150px">
                <input type="button" value="Valider" name="valider" id="valider" />
                <input id="t_annuler" type="button" value="Annuler" />
            </div>
        </form>
    </div>
    <script type="text/javascript">
        $("#tbl-credit").jqGrid({
            url:'<?php echo $this->url(array('action' => 'credits')); ?>',
            datatype: "json",
            mtype: 'GET',
            colNames:['Numéro membre','Ressource','Montant placé','Montant crédit','Date dépôt','Code crédit','Type credit'],
            height:'100%', width:810,
            colModel:[
                {name:'num_membre',index:'num_membre', width: 150, editable: false,align:"left"},
                {name:'produit',index:'produit', width: 100, align:"left", editable: false},
                {name:'mt_place',index:'mt_place', width: 150, align:"right", editable: false,formatter:'number'},
                {name:'mt_credit',index:'mt_credit', width: 150, align:"right", editable: false,formatter:'number'},
                //{name:'mt_utilise',index:'mt_utilise', width: 150, align:"right", editable: true,formatter:'number'},
                {name:'date_depot',index:'date_depot', width: 120, align:"left", editable: false},
                {name:'code_credit',index:'code_credit', width: 50, align:"left", editable: false, hidden:true},
				{name:'type_credit',index:'type_credit', width: 50, align:"left", editable: false, hidden:true}
            ],
            rowNum:30,
            rowList:[30,50,100],
            rownumbers:true,
            pager: '#pg-credit',
            sortname:"date_octroi",
            viewrecords: true,
            multiselect:true,
            sortorder: "ASC",
            caption:"Comptes des crédits des membres",
            forceFit : true, 
            cellEdit: true, 
            cellsubmit: 'clientArray',
            onSelectRow: function(id,status){
                var montant = $('#mt_obtenu').val();
                if(id != 0 || id != null){
                    var data = jQuery('#tbl-credit').jqGrid('getRowData',id);
                    var value = 0;
                    var mt_credit = data.mt_credit;
                    if(montant == '') {
                        montant = 0;
                    }else{
                        montant = parseInt(montant,10);
                    }
                    if(status == true){
                        value = parseInt(montant) + parseInt(mt_credit);
                        $('#mt_obtenu').val(value);
                    }else{
                        value = montant - parseInt(mt_credit);
                        $('#mt_obtenu').val(value);
                    }
                    lastsel=id; 
                }
            },
            onSelectAll: function(ids,status){
                var montant = $('#mt_obtenu').val();
                if(status == true){
                    montant = 0;
                    if(montant == ''){
                        montant = 0;
                    }else{
                        montant = parseInt(montant,10);
                    }
                    for(var i = 0;i < ids.length;i++){
                        var id = ids[i];
                        var data = jQuery('#tbl-credit').jqGrid('getRowData',id);
                        var mt_credit = data.mt_credit;
                        montant += parseInt(mt_credit);
                    }
                    $('#mt_obtenu').val(montant);
                }else{
                    $('#mt_obtenu').val(0); 
                }
            }
        });
        $("#tbl-credit").jqGrid('navGrid','#pg-credit',{edit:false,add:false,del:false,search:true});
		
        var compteur = 1;
        $(document).ready(function () {
		    $('#view-content').puipanel();
            $('fieldset').puifieldset();
           
                        
            $('#t_annuler').click(function()
            {
                window.location="/eu-tegcp/";
            }); 
            
            $('#code_membre_benef').blur(function(e) {
                if($(this).val() != '') {
                    $.get(
                    '/eu-tegcp/recupnom',
                   {
                       num_membre: $(this).val()
                   },
                   function success(data)
                    {
                       $("#raison_benef").val(data);
                    });
                }
                e.preventDefault();
            });
            
            $.get( "/eu-tegcp/change",
            function success(data) {
            $("input#code_membre_benef").autocomplete({"source":data});                  
           });
            
            $('#afficher').click(function() {
                var tab=new Array();
                $('#mt_obtenu').val(0)
                for(var i=1;i<=compteur;i++) {
                    tab[i-1]=$('#num_membre' + i).val();           
                }
                jQuery("#tbl-credit").jqGrid('setGridParam',{url:"/eu-tegcp/credits?ress="+$('#type_ressource').val()+"&lignes="+tab+"&type_credit="+$('#type_credit').val()}).trigger('reloadGrid');
            });
			
			
			$('#valider').click(function(e) {
		        if($('#code_membre_benef').val() =='')  {
                   alert('Préciser le code du membre bénéficiaire');
				}  else {   
			        var sel;
                    sel = jQuery("#tbl-credit").jqGrid('getGridParam','selarrrow');
                    var tab = new Array();  
                    var rowsel;
                    rowsel = jQuery("#tbl-credit").jqGrid('getGridParam','selrow');
                    for(var i=0; i<sel.length; i++) {
                       tab[i]=jQuery("#tbl-credit").jqGrid('getRowData',sel[i]);   
                    }
                    if(rowsel) {
                      $.get('/eu-tegcp/create?ress='+$('#type_ressource').val()+'&mt_obtenu='+$('#mt_obtenu').val()+"&code_membre_benef="+$('#code_membre_benef').val(),{
                      lignes:tab
                    },
                    function success(data){
                        if(data == 'good'){
                            //jQuery("#tbl-credit").jqGrid('setGridParam',{url:"/eu-tegcp/credits?ress="+$('#type_ressource').val()+"&lignes="+tab+"&code_membre_benef="+$('#code_membre_benef').val()}).trigger('reloadGrid');
                            //$("#mt_obtenu").val('');
                            alert('Opération effectuée avec succes');
							$(location).attr("href", "/eu-tegcp/index");
                        }
                        else if(data=="cool"){
                            alert("Ce client a déjà domicilié son payement.");
                        }
                        else if(data=="bad_domi") {
                            alert("Ce crédit a été domicilié déjà et la domiciliation est en cours.");
                        }
                        else if(data=="vol"){
                            alert("Impossible de domicilier votre investissement sur votre TEGCP.");
                        }
                        else if(data == 'bad'){
                            alert("Echec de l'opération");
                        }
                        else if(data == "err_domici") {
                            alert("Le montant du crédit est inférieur à celui de la domiciliation.");
                        }
                    });
                } else {
                    alert('Aucune ligne de crédit sélectionnée');
                }					
		    }
		        e.preventDefault();
		    });
			
			
			
        });
        
		
        function addRow(tableID) {

            var table = document.getElementById(tableID);
            var rowCount = table.rows.length;
            var cpte = rowCount;
            var row = table.insertRow(rowCount);
            
            var cell1 = row.insertCell(0);
            var element0 = document.createElement("input");
            element0.type = "text";
            element0.setAttribute("id","num_membre" + cpte);
            element0.setAttribute("name","num_membre" + cpte); 
            element0.setAttribute("style","width:185px;");
            cell1.appendChild(element0);
			$('#num_membre'+ cpte).puiinputtext();

            var cell2 = row.insertCell(1);
            var element1 = document.createElement("input");
            element1.type = "text";
            element1.setAttribute("id","nom" + cpte);
            element1.setAttribute("name","nom" + cpte);
            element1.setAttribute("style","width:260px;");
            element1.setAttribute("readonly","true");
            cell2.appendChild(element1);
			$('#nom'+ cpte).puiinputtext();
            
            $.get( "/eu-tegcp/change",
            function success(data) {
                $("#num_membre"+ cpte).autocomplete({"source":data});
            });
            
            $('#num_membre' + cpte).blur(function(e)
            {
                if($(this).val() != '')
                {
                    $.get(
                    '/eu-tegcp/recupnom',
                    {
                        num_membre: $(this).val()
                    },
                    function success(data)
                    {
                        $("#nom"+cpte).val(data);
                    });
                }
                e.preventDefault();
            });
            
            compteur = compteur + 1;
            document.getElementById("cpteur").setAttribute('value',compteur);
        }

		
        function deleteRow(tableID) {
            try {
                var table = document.getElementById(tableID);
                var rowCount = table.rows.length - 1;
                if(rowCount>1){
                    table.deleteRow(rowCount);
                }
                compteur = compteur - 1;
                document.getElementById("cpteur").setAttribute('value',compteur);
            }catch(e) {
                alert(e);
            }
        }
        
		
		
        
    </script>
</div>