<div id="view-content" class="ui-widgets">
    <div class="cntError">
        <?php
           echo $this->message;
        ?>
    </div>
    <div class="ui-widget-header ui-corner-top" style="height: 25px;padding-bottom:10px; padding-left: 5px;">
        <h3>Etablissement de la fiche de facturation</h3>
    </div>
    <div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <form action="/eu-facture/new" name="fm_facture" method="POST" id="fm_facture">
             <br>
             <?php  if(isset($this->data[0][1])) { ?>
             <fieldset style="border-color:#000"><legend style=" font-weight:bold">Produits</legend>    
             <table style="font-family:verdana;font-weight:normal;margin: 5px"  border="1">
                        <thead>
                              <tr style="text-align: left;">
                                 <th>Désignation</th><th>Quantité</th><th>Prix unitaire</th><th colspan="2">Remise</th>
                              </tr>
                        </thead>
                 <?php    
                     for($i=0;$i<count($this->data);$i++) {   ?>
                 <tr>
                    <td><input type="text"  name="<?php echo "design_produit".$i ?>" value="<?php echo $this->data[$i][2] ;?>" readonly="true" size="60"/></td> 
                    <td><input type="text" name="<?php echo "qte_objet".$i ?>" value="<?php echo $this->data[$i][3] ;?>" size="7" readonly="true"/></td>
                    <td><input type="text" name="<?php echo "pu".$i ?>" size="15" value="<?php echo $this->data[$i][4] ;?>" readonly="true"/></td>
                    <td><input type="text" value="<?php echo $this->data[$i][5] ;?>" name="<?php echo "remise".$i ?>" size="6" readonly="true"/></td><td><input type="text" value="%" disabled size="1"></td>
                    <input type="hidden"  name="<?php echo "id_objet".$i ?>" value="<?php echo $this->data[$i][1];?>"/>
                 </tr>
                <?php } ?>
                    <input type="hidden" value="<?php echo count($this->data); ?>" name="compteur">
                    <input type="hidden" value="<?php echo $this->data[0][6] ;?>" name="code_commande">
            </table>   
            </fieldset>
          <?php } ?>
            <br>
            <?php  if(isset($this->data[0][1])) {  ?>
            <fieldset style="border-color:#000"><legend style=" font-weight:bold">Autres Informations</legend>    
            <table style="font-family:verdana;font-weight:normal">
                <tr>
                   <td valign="top">Taxe à imputer </td>
							<td><select name="taxe" id="taxe"></select></td>
                    </tr>
            </table>
            </fieldset>
            <table style="margin-left: 310px">
                   <tr><td><input type="submit" id="valide" value="Valider"></td></tr>
            </table>
            <?php } ?>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function ()
    {
     $('#valide').button();
	 $.get(
         '/eu-facture/taxe',
         function success(data)
         {
             var options = '<option value=""></option>';
             for( var i = 0; i < data.length; i++) {
             options += '<option value="' + data[i][1] + '">' + data[i][2] + '-' +  data[i][3] +' </option>';
             }
             $('select#taxe').html(options);
         });
})
       
</script>    