<div id="view-content" class="ui-widget">
    <div class="ui-widget-header ui-corner-top" style="padding-left: 5px;height: 35px;">
        <h3>Ajout d'une section</h3> 
    </div>
    <div id="formdiv" class="ui-widget-content">
        <?php
        $this->form->setAction($this->url());
        echo $this->form;
        ?>
    </div>
</div>	
<script type="text/javascript">
    $('#submit').button();
    $('#cancel').button();
</script>
