<?php

$month = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
$true_month = "";
$ex_date = explode('-',$this->entriesgerant[0]->date_demande);

foreach ($month as $key => $value) {
  if($ex_date[1] == $key){
    $true_month = $value;
  }
}
$next_ex_date = explode(' ', $ex_date[2]);
$true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0];

?>

<h3> FACTURE N° <?php echo $this->entriesgerant[0]->reference_demande_achat ;?></h3>

<p style="text-align: right;font-weight: bold;">Date:<?php echo $true_date ;?></p>

<table class="table table-stripped">
    <thead>
        <tr>
			<th>Références</th>
			<th>Désignation des Articles </th>
			<th>Quantité </th>
			<th>Prix Unitaire</th>
			<th>TOTAL</th>
		</tr> 
    </thead>
    <tbody>
     <?php foreach ($this->detailachatgerant as $key => $value): ?>
     <?php
       $quantite = $value[0]->quantite;
       $prix_unitaire = $value->prix_unitaire;
       $total = $quantite * $prix_unitaire;
      ?>
      <tr>
        
        <td><?php echo $value->reference_article ;?></td>
        <td><?php echo $value->designation_article ;?></td>
        <td><?php echo $value->quantite;?></td>
        <td><?php echo $value->prix_unitaire;?></td>
        <td id="total_visa_demande_achat"><?php echo $total;?></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><label for="">Montant demande d’Achat</label></td>
		<td id="montant_total_visa_demande_achat"><?php echo $this->entriesgerant[0]->montant_demande_achat;?></td>			                     
	 </tr>
    </tbody>
 	<?php endforeach ?>
</table>
<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
  <strong ><i><span style="text-decoration:underline">NB</span>: Cadre reservé au gérant.</i></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
 <strong style="margin-bottom:15px;"> Visa du gérant <input type="text" style="border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 80%;height: 28px;font-size: 1.8em;font-family: Matura MT Script Capitals;text-transform:uppercase;margin-top: -29px;margin-left: 176px;background: transparent;padding: 0;" id="visa_technofiliere_demande_achat_gerant" value="ok" readonly="true"></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
<strong style="margin-bottom:15px;"> Avis du gérant
  <textarea name="name" style="border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 100%;font-size: 1.8em;width:100%;font-family: Matura MT Script Capitals;" id="avistechnofilieredemandeachatgerant" placeholder="..............................................................................................................................................................................................." rows="8" cols="40"></textarea></strong>
</div>

<!--Apposer le visa sur la demande d'achat qui a été préalablement viser par la technopole -->
<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
   <a class="btn btn-primary" href="" data-numvisademandeachatgerant="<?php echo $this->entriesgerant[0]->reference_demande_achat ;?>" data-iddemandeachatgerant="<?php echo $this->entriesgerant[0]->id_demande_achat; ?>" id="visa_demande_achat_gerant"><i class="icon-cog icon-white"></i>Apposer le visa</a>
</div>
