<h3> FACTURE N° <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->numero_interne ;?></h3>

<div class="control-group">
	  <label class="control-label" for="reference de la facture proforma" style="font-weight:bold;display:inline-block">
	        Référence de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->numero_facture ;?>	 
      </div>
	
</div>

<div class="control-group">
	  <label class="control-label" for="libellé de la facture proforma" style="font-weight:bold;display:inline-block">
	        Libellé de la facture:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->libelle ;?>	 
      </div>
	
</div>


<div class="control-group">
	  <label class="control-label" for="date d'établissement de la facture proforma" style="font-weight:bold;display:inline-block">
	        Date d'établissement de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->date_facture ;?>	 
      </div>
	
</div>

<div class="control-group">
	  <label class="control-label" for="date de paiement de la facture proforma" style="font-weight:bold;display:inline-block">
	        Date de paiement de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->date_paiement ;?>	 
      </div>
	
</div>


<div class="control-group">
	  <label class="control-label" for="date d'arrivée de la facture proforma" style="font-weight:bold;display:inline-block">
	        Date d'arrivée de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->date_arrivee ;?>	 
      </div>
	
</div>


<div class="control-group">
	  <label class="control-label" for="le montant de la facture proforma" style="font-weight:bold;display:inline-block">
	    Le montant de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->montant ;?>	 
      </div>
	
</div>

<div class="control-group">
	  <label class="control-label" for="le montant de la facture proforma" style="font-weight:bold;display:inline-block">
	    Le montant de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->montant ;?>	 
      </div>
	
</div>


<div class="control-group">
	  <label class="control-label" for="le montant de paiement de la facture proforma" style="font-weight:bold;display:inline-block">
	    Le montant de paiement de la facture proforma:
	  </label>
	  <div class="controls" style="display:inline-block">
      <?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->modalite_paiement ;?>	 
      </div>
	
</div>

<button class="btn btn-danger" id="btn_facture_filiere_to_acnev" data-idfacturefilieretoacnev="<?php echo $this->dbeditiondelafactureavaliderparlafiliere[0]->id_factures_procedure ;?>">Transmettre cette facture à l'agent acnev</button>