<?php $sessionterminal = new Zend_Session_Namespace('terminal');?>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuterminal.phtml"); ?>
  <blockquote>
  <p>
      <strong>Espace Terminal d'Echange </strong> 
  <small>Espace de terminal d'échange</small>
  </p>
  </blockquote>







<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








