<?php $sessionterminal = new Zend_Session_Namespace('terminal');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
        "sPaginationType": "full_numbers",
		"aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuterminal.phtml"); ?>


  <blockquote><p>Liste des commandes d'aujourd'hui</p></blockquote>
<?php if(count($this->entries) > 0) { ?> 
<a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl();?>/terminal/listarticlecommandetodayexcel">Exporter en Excel</a>
<br>
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Code Membre</th>
                  <th>Nom & prenom(s) / Raison sociale</th>
                  <th>Désignation</th>
                  <th>Quantité</th>
                  <th>Prix</th>
                  <th>Complement</th>
                  <th>Commande</th>
                  <th>Livraison</th>
                </tr>
              </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
    <?php 
$commandeM = new Application_Model_EuCommandeMapper();
$commande = new Application_Model_EuCommande();
$commandeM->find($entry->code_commande, $commande);
/**/?>
      <td><?php echo ($commande->date_commande); ?></td>
      <td><?php echo $commande->code_membre_acheteur; ?></td>
      <td><?php if(substr($commande->code_membre_acheteur, -1) == "P"){
$membreM = new Application_Model_EuMembreMapper();
$membre = new Application_Model_EuMembre();
$membreM->find($commande->code_membre_acheteur, $membre);
?><?php echo ($membre->nom_membre." ".$membre->prenom_membre); $email = $membre->email_membre; ?>
  <?php }else{
$membremoraleM = new Application_Model_EuMembreMoraleMapper();
$membremorale = new Application_Model_EuMembreMorale();
$membremoraleM->find($commande->code_membre_acheteur, $membremorale);
?><?php echo ($membremorale->raison_sociale); $email = $membremorale->email_membre;  } ?>
</td>
      <td><?php echo ($entry->designation); ?></td>
      <td><div align="right"><?php echo number_format($entry->qte, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format(($entry->qte * $entry->prix_unitaire), 0, ',', ' '); ?></div></td>
      <td>
<?php 
                $detail_commande_additif = new Application_Model_EuDetailCommandeAdditifMapper();
                $entries3 = $detail_commande_additif->fetchAllByDetailCommande($entry->id_detail_commande);
                if(count($entries3) > 0) {
                    foreach($entries3 as $entry3){
                        $article_stockes_additif = new Application_Model_EuArticleStockesAdditif();
                        $m_article_stockes_additif = new Application_Model_EuArticleStockesAdditifMapper();
                        $m_article_stockes_additif->find($entry3->id_article_stockes_additif, $article_stockes_additif);

                      echo $article_stockes_additif->nom_article_stockes_additif." : ".$entry3->reference_additif."<br>";
                        $j++;
                    }
                }
 ?>
</td>

      <td><?php if($entry->commander >= 1){?>
      <a class="btn btn-mini btn-success">Déja Commandé</a>&nbsp;
<?php }else{?>
      <a class="btn btn-mini btn-warning">Non Commandé</a>&nbsp;
<?php }?></td>
      <td><div id="nivo<?php echo $entry->id_detail_commande; ?>"><?php if($entry->livrer == 1){?>
      <a class="btn btn-mini btn-success" onclick="ouvre_livrercommandedetails('<?php echo $entry->id_detail_commande; ?>_0', 'nivo<?php echo $entry->id_detail_commande; ?>');"><i class="icon-ok icon-white"></i>  Déja Livré</a>&nbsp;
<?php }else{?>
      <a class="btn btn-mini btn-warning" onclick="ouvre_livrercommandedetails('<?php echo $entry->id_detail_commande; ?>_1', 'nivo<?php echo $entry->id_detail_commande; ?>');"><i class="icon-off icon-white"></i>  Non Livré</a>&nbsp;
<?php }?></div></td>
    </tr>
<?php endforeach; ?>
</tbody>
            </table>
			
<?php /*?><?php }else{?>
<div class="alert alert-info">
  Aucun article acheté 
</div><?php */?>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








