<?php $sessionterminal = new Zend_Session_Namespace('terminal');?>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">


<form method="post" id="connexion" action="<?php echo $this->baseUrl();?>/terminal/login">
    <?php if(isset($sessionterminal->errorlogin) && $sessionterminal->errorlogin != ""){?>
    <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionterminal->errorlogin; ?>
	</div>
	<?php }?>


    <div class="controls">
      <input name="login" type="text" id="login" placeholder="Votre Login">
    </div>
    <div class="controls">
      <input name="pwd" type="password" id="pwd" placeholder="Votre Mot de Passe">
    </div>
    <div class="controls">
      <input name="ok" type="hidden" id="ok" value="ok" />
      <button type="submit" class="btn">Connexion Terminal d'Echange</button>
    </div>
</form>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








