<div id="view-content" class="ui-widget">
    <div id="c_header" class="ui-widget-header ui-corner-top" style="padding-left: 5px; height: 35px;">
        <h4>Ventes</h4>
    </div>
    <div class="ui-widget-content ui-corner-bottom" style="height: 500px;">
        <form id="gcsc_form" method="post" action="/eu-consommation/newgcsc">
            <table id="tab_fact" style="width: 400px; margin-top: 17px;margin-left: auto; margin-right: auto;">
                <tr>
                    <td><label for="vendeur">Distributeur :</label></td><td><input type="text" id="vendeur" name="vendeur" value="<?php echo $this->dist; ?>"/></td>
                </tr>
                <tr>
                    <td><label for="acheteur">Acheteur :</label></td><td><input type="text" id="acheteur" name="acheteur" value="<?php echo $this->membre; ?>" /></td>
                </tr>
                <tr>
                    <td><label for="compte">Compte :</label></td>
                    <td>
                        <select id="compte" name="compte[]" multiple="multiple" value="<?php echo $this->comptes; ?>">
                        </select>
                    </td>
                </tr>
                <tr><td><label for="montant">Montant total :</label></td>
                    <td><input type="text" id="montant" name="montant" value="<?php echo $this->montant; ?>"/></td>
                </tr>
                <tr><td></td><td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="Réinitialiser"/></td></tr>
            </table>
        </form>
    </div>
    <script>
        
        $(document).ready(function ()
        {
            $.get( "/eu-consommation/membre",{type:'M'},
            function success(data)
            {
                $('#vendeur').autocomplete({"source":data});
            });
            
            $.get( "/eu-consommation/membre",{type:'%'},
            function success(data)
            {
                $('#acheteur').autocomplete({"source":data});
            });
            
            $('#val').button();
            $('#reset').button();
            
            $("#compte").multiselect({
                header: "",
                noneSelectedText: "",
                selectedList:4
            });
            
            $('#acheteur').blur(function(e)
            {
                if($(this).val() != '')
                {
                    $.get(
                    '/eu-consommation/compte',
                    {
                        membre: $(this).val()
                    },
                    function success(data)
                    {
                        var options = '<option value=""></option>';
                        for( var i = 0; i < data.length; i++) {
                            options += '<option value="' + data[i] + '">' + data[i] +' </option>';
                        }
                        $('select#compte').html(options);
                        $("#compte").multiselect('refresh');
                    });
                }
                e.preventDefault();
            });
           
        });

    </script>
</div>	