<div id="view-content" title="Liste des operations d'achat du CAPA MF" style="font-size: 12px;min-height: 520px;">
     <fieldset id="carte_field" style="margin-bottom: 2px;"><legend>Recherche</legend>
        <table>
               <tbody>
			          <tr>
                         <td style="text-align: right;"><label>Credit code</label></td>
                         <td><input type="text" id="credit_code" name="credit_code"/></td>
                         <td><button id="bt_show">Afficher</button></td>
					  </tr>
			   </tbody>
                
        </table>
    </fieldset> 
    <table id="tbl-mf"></table>
    <div id="pg-mf"></div>
</div>
<script type="text/javascript">
    $("#tbl-mf").jqGrid({
        url:'/eu-mf/dataverifier',
        datatype: "json",
        mtype: 'GET',
        colNames:['ID','Compte Source','Code SMS','Type','Entrée','Sortie','Solde'],
        height:500, width:827,
        colModel:[
            {name:'neng',index:'neng', width: 100, align:"left", editable: true,visible:false},
            {name:'code_compte',index:'code_compte', width:280, align:"left", editable: true},
            {name:'creditcode',index:'creditcode', width:100, align:"left", editable: true},
            {name:'motif',index:'motif', width: 100, editable: true,align:"left"},
            {name:'montant_entrer',index:'montant_entrer', width: 120, editable: true,align:"left"},
			{name:'montant_sortie',index:'montant_sortie', width: 120, editable: true,align:"left"},
			{name:'solde',index:'solde', width: 120, editable: true,align:"left"},
            
        ],
        rowNum:20,
        rowList:[20,30,40],
        pager: '#pg-mf',
        sortname:"num_op",
        viewrecords: true,
        sortorder: "ASC",
        caption:"Achat du MF"
    });
    $("#tbl-mf").jqGrid('navGrid','#pg-mf',{edit:false,add:false,del:false,search:true});
	$(function() {
	   $('#view-content').puipanel();
	})
	
	$('#bt_show').button().click(function(e){
            e.preventDefault();
            jQuery("#tbl-mf").jqGrid('setGridParam', {url: "/eu-mf/dataverifier?code="+$('#credit_code').val()}).trigger('reloadGrid');
    });
    
</script>