<div id="view-content" class="ui-widget" style="font-size:12px">
    <div class="ui-widget-header ui-corner-top" style="height: 25px; padding-bottom: 7px; padding-left: 7px;">
        <h3>Domiciliation nrPRE de remboursement de la <font color="red">SMCIPN</font>w<font color="blue">i</font> / <font color="red">SMCIPN</font>p</h3>
    </div>
    <div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <form action="/eu-domiciliation/domicilierpre" name="fm_domicil" method="POST" id="fm_domicil">
            <input type="hidden" name="cpteur" id="cpteur" value="1"/>
            <fieldset>
                <legend>Informations sur le bénéficiaire</legend>
                <table>
                    <tr>
                        <td>Code membre bénéficiaire *</td><td><input name="num_benef" id="num_benef" class="validate[required]" value="<?php echo $this->num_benef ?>" size=30/></td>
                        <td>Raison sociale</td><td><input name="raison_sociale" id="raison_sociale" class="" readonly="readonly" size=35/></td>
                    </tr>
                    <tr>
                        <td>Type SMCIPN *</td>
                        <td>
                        <select id="type_domi" type="text" name="type_domi" required="true" />
                    <option value=""></option>
                    <option value="SMCIPNP">SMCIPNp</option>
                    <option value="SMCIPNWI">SMCIPNwi</option>
                    </select>	  
                    </td>
                    </tr>
                </table>
                <table style="display: none;" id="pre3">
                    <tr>
                        <td>Appel d'offre *</td><td><select id="id_proposition" name="id_proposition" class="validate[required]" ></select></td>
                        <td>Montant projet</td><td><input name="mt_projet" id="mt_projet" class="validate[required,custom[onlyNumberSp]]" readonly="readonly" size=15/></td>
                        <td>Montant à domicilier</td><td><input name="mt_domi" id="mt_domi" class="validate[required,custom[onlyNumberSp]]" readonly="readonly" size=15/></td>
                    </tr>
                </table>
            </fieldset>
            <fieldset style="margin-top: 5px;">
                <legend>Informations sur le crédits des apporteurs</legend>
                <div align="center" style="margin-bottom: 5px;">
                    <table border="1" id="tab_salaire">
                        <thead>
                        <th>Type membre</th><th>Code membre</th><th>Nom / Raison sociale</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <select id="type_membre1" type="text" name="type_membre1" required="true"/>
                        <option value=""></option>
                        <option value="P">Physique</option>
                        <option value="M">Morale</option></select>
                        </td>
                        <td><input id="num_membre1" type="text" name="num_membre1" value="" required="true" size="28" class="validate[required]" style="text-align: left"/></td>
                        <td><input id="nom1" type="text" name="nom1" value="" size="43" readonly="true"/></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div align="center" style="margin-bottom: 5px;">
                    <input id="add" type="button" value="Ajouter" onclick="addRow('tab_salaire')"/>
                    <input id="remove" type="button" value="Supprimer" onclick="deleteRow('tab_salaire')"/> 
                    <input type='button' value="Afficher" name="afficher" id="afficher"/>

                </div>
                <div align="center" style="margin-top: 5px;">
                    <table id="tbl-credit"></table>
                    <div id="pg-credit"></div>
                </div>
            </fieldset>
            <div style="margin-left: 105px; margin-top: 5px">
                <input type="button" value="Valider" name="valider" id="valider"/>
                <input type="reset" value="Rafraichir" name="refresh" id="refresh"/>
                <input id="t_annuler" type="button" value="Annuler"/>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("#tbl-credit").jqGrid({
        url: '<?php echo $this->url(array('action' => 'creditsimm')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames: ['Code membre', 'Ressource', 'Montant placé', 'Montant crédit', 'Période', 'Total', 'Date dépôt', 'Code crédit'],
        height: '100%', width: 775,
        colModel: [
            {name: 'code_membre', index: 'code_membre', width: 185, editable: false, align: "left"},
            {name: 'produit', index: 'produit', width: 90, align: "left", editable: false},
            {name: 'mt_place', index: 'mt_place', width: 125, align: "right", editable: false, formatter: 'number'},
            {name: 'mt_credit', index: 'mt_credit', width: 125, align: "right", editable: false, formatter: 'number'},
            {name: 'reste_duree', index: 'reste_duree', width: 60, align: "right", editable: false},
            {name: 'total', index: 'total', width: 125, align: "right", editable: false, formatter: 'number'},
            {name: 'date_depot', index: 'date_depot', width: 100, align: "left", editable: false},
            {name: 'code_credit', index: 'code_credit', width: 50, align: "left", editable: false, hidden: true}
        ],
        rowNum: 30,
        rowList: [30, 50, 100],
        rownumbers: true,
        pager: '#pg-credit',
        sortname: "date_octroi",
        viewrecords: true,
        multiselect: true,
        sortorder: "ASC",
        caption: "Comptes des crédits des membres",
        forceFit: true,
        cellEdit: true,
        cellsubmit: 'clientArray',
        afterSaveCell: function(rowid, name, val, iRow, iCol) {
            if (name == 'reste_duree') {
                var amtval = jQuery("#tbl-credit").jqGrid('getCell', rowid, iCol - 1);
                jQuery("#tbl-credit").jqGrid('setRowData', rowid, {total: parseFloat(val) * parseFloat(amtval)});
            }
        }
    });
    $("#tbl-credit").jqGrid('navGrid', '#pg-credit', {edit: false, add: false, del: false, search: true});

    $(document).ready(function() {
        $('#view-content').puipanel();
        $('fieldset').puifieldset();

        $('#refresh').button();
        $('#valider').button();
        $('#t_annuler').button();
        $('#add').button();
        $('#remove').button();
        $('#afficher').button();

        $('#t_annuler').click(function() {
            window.location = "/eu-domiciliation/";
        });

        $(function() {
            var pickerOpts = {
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                showOtherMonths: true
            };
            $.datepicker.setDefaults($.datepicker.regional[ "fr" ]);
            $("#date_fin").datepicker(pickerOpts);
        });

        $.get("/eu-domiciliation/changemoral",
                function success(data)
                {
                    $("input#num_benef").autocomplete({"source": data});
                });

        $('#num_benef').blur(function() {
            if ($(this).val() != '') {
                $.get(
                        '/eu-domiciliation/recupnom',
                        {
                            num_membre: $(this).val(), type_membre: 'M'
                        },
                function success(data) {
                    if (data !== '') {
                        $('#raison_sociale').val(data[1]);
                    } else {
                        alert('Ce membre n\existe pas!!!');
                    }
                });
            }
        });

        $("#type_domi").change(function(e) {
            e.preventDefault();
            if ($(this).val() == 'SMCIPNWI') {
                $('#pre3').css('display', 'block');
            }
            else {
                $('#pre3').css('display', 'none');
            }
        });

        $.get("/eu-domiciliation/offrechange",
                function success(data) {
                    var options = '<option/>';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i][1] + '">' + data[i][2] + ' </option>';
                    }
                    $('select#id_proposition').html(options);
                });

        $('#id_proposition').change(function() {
            if ($(this).val() != '') {
                $.get(
                        '/eu-domiciliation/montantprojet',
                        {
                            id_proposition: $(this).val()
                        },
                function success(data)
                {
                    $('#mt_projet').val(data);
                });
                $.get(
                        '/eu-domiciliation/montantdomi',
                        {
                            id_proposition: $(this).val()
                        },
                function success(data)
                {
                    $('#mt_domi').val(data);
                });
            } else {
                $('#mt_projet').val('');
                $('#mt_domi').val('');
            }
        });

        $('#num_membre1').attr('readonly', true);
        $("#type_membre1").change(function(e) {
            e.preventDefault();
            $('#num_membre1').val('');
            $('#nom1').val('');
            if ($(this).val() != '') {
                $('#num_membre1').attr('readonly', false);
                $.get("/eu-domiciliation/membreapporteur", {
                    type_membre: $('#type_membre1').val()
                },
                function success(data) {
                    $("#num_membre1").autocomplete({minLength: 5, "source": data});
                });
            } else {
                $('#num_membre1').attr('readonly', true);
            }
        })
        $('#num_membre1').blur(function(e) {
            if ($(this).val() != '') {
                $.get(
                        '/eu-domiciliation/recupnom',
                        {
                            num_membre: $(this).val(), type_membre: $("#type_membre1").val()
                        },
                function success(data)
                {
                    if (data != '') {
                        $("#nom1").val(data[1]);
                    } else {
                        alert('Ce membre n\existe pas!!!');
                    }
                });
            }
            e.preventDefault();
        });

        $('#afficher').click(function() {
            var tab = new Array();
            for (var i = 1; i <= compteur; i++) {
                tab[i - 1] = $('#num_membre' + i).val();
            }
            jQuery("#tbl-credit").jqGrid('setGridParam',{url: "/eu-domiciliation/creditsimm?lignes=" + tab}).trigger('reloadGrid');
        });
    });

    var compteur = 1;
    function addRow(tableID) {
        var table = document.getElementById(tableID);
        var rowCount = table.rows.length;
        var cpte = rowCount;
        var row = table.insertRow(rowCount);

        var cell1 = row.insertCell(0);
        var element0 = document.createElement("select");
        element0.setAttribute("id", "type_membre" + cpte);
        element0.setAttribute("name", "type_membre" + cpte);
        element0.setAttribute("required", "true");
        cell1.appendChild(element0);
        $('#type_membre' + cpte).button();
        var options = '<option/>';
        var tab = [];
        var tab1 = [];
        tab[0] = 'P';
        tab[1] = 'M';
        tab1[0] = 'Physique';
        tab1[1] = 'Morale';

        for (var i = 0; i < 2; i++) {
            options += '<option value="' + tab[i] + '">' + tab1[i] + ' </option>';
        }
        $('select#type_membre' + cpte).html(options);

        var cell2 = row.insertCell(1);
        var element1 = document.createElement("input");
        element1.type = "text";
        element1.setAttribute("id", "num_membre" + cpte);
        element1.setAttribute("class", "validate[required]");
        element1.setAttribute("style", "text-align:left");
        element1.setAttribute("style", "font-weight:normal");
        element1.setAttribute("name", "num_membre" + cpte);
        element1.setAttribute("size", "25");
        element1.setAttribute("readonly", "true");
        cell2.appendChild(element1);
        $('#num_membre' + cpte).button();

        var cell3 = row.insertCell(2);
        var element2 = document.createElement("input");
        element2.type = "text";
        element2.setAttribute("id", "nom" + cpte);
        element2.setAttribute("name", "nom" + cpte);
        element2.setAttribute("size", "40");
        element2.setAttribute("readonly", "true");
        cell3.appendChild(element2);
        $('#nom' + cpte).button();

        $('#num_membre' + cpte).attr('readonly', true);
        $("#type_membre" + cpte).change(function(e) {
            e.preventDefault();
            $('#num_membre' + cpte).val('');
            $('#nom' + cpte).val('');
            if ($(this).val() != '') {
                $('#num_membre' + cpte).attr('readonly', false);
                $.get("/eu-domiciliation/membreapporteur", {
                    type_membre: $('#type_membre' + cpte).val()
                },
                function success(data) {
                    $("#num_membre" + cpte).autocomplete({minLength: 5, "source": data});
                });
            } else {
                $('#num_membre' + cpte).attr('readonly', true);
            }
        })
        $('#num_membre' + cpte).blur(function(e) {
            if ($(this).val() !== '') {
                $.get(
                        '/eu-domiciliation/recupnom',
                        {
                            num_membre: $(this).val(), type_membre: $("#type_membre" + cpte).val()
                        },
                function success(data)
                {
                    if (data !== '') {
                        $("#nom" + cpte).val(data[1]);
                    } else {
                        alert('Ce membre n\existe pas!!!');
                    }
                });
            }
            e.preventDefault();
        });

        compteur = compteur + 1;
        document.getElementById("cpteur").setAttribute('value', compteur);
    }

    function deleteRow(tableID) {
        try {
            var table = document.getElementById(tableID);
            var rowCount = table.rows.length - 1;
            if (rowCount > 1) {
                table.deleteRow(rowCount);
            }
            compteur = compteur - 1;
            document.getElementById("cpteur").setAttribute('value', compteur);
        } catch (e) {
            alert(e);
        }
    }

    $('#valider').click(
        function() {
                var sel;
                sel = jQuery("#tbl-credit").jqGrid('getGridParam', 'selarrrow');
                var tab = new Array();
                var rowsel;
                rowsel = jQuery("#tbl-credit").jqGrid('getGridParam', 'selrow');
                for (var i = 0; i < sel.length; i++) {
                    tab[i] = jQuery("#tbl-credit").jqGrid('getRowData', sel[i]);
                };
                if ($('#num_benef').val() == '' || $('#type_domi').val() == '') {
                    alert('Renseignez les champs obligatoires');
                } else if ($('#mt_projet').val() == '' && $('#type_domi').val() == 'SMCIPNWI') {
                    alert('Sélectionnez un appel d\'offre');
                } else {
                    if (rowsel) {
                        $.get('/eu-domiciliation/createimm?num_benef=' + $('#num_benef').val() + '&type_domi=' + $('#type_domi').val() + '&id_proposition=' + $('#id_proposition').val() + '&mt_domi=' + $('#mt_domi').val(), {
                            lignes: tab
                        },
                        function success(data) {
                            var tab = new Array();
                            for (var i = 1; i <= 10; i++)
                            {
                                tab[i - 1] = $('#num_membre' + i).val();
                            }
                            if (data == 'good') {
                                jQuery("#tbl-credit").jqGrid('setGridParam', {url: "/eu-domiciliation/creditsimm?lignes=" + tab}).trigger('reloadGrid');
                                alert('Opération effectuée avec succès');
                            }
                            else if (data == 'bad') {
                                alert("Echec de l'opération");
                            }
                        });
                    } else {
                           alert('Aucune ligne de crédit sélectionnée');
                    }
                }

            });
</script>