<div id="view-content" class="ui-widget" style="font-size:10px">
    <div class="ui-widget-header ui-corner-top" style="height: 25px; padding-bottom: 7px; padding-left: 7px;">
        <h4>Domiciliation nrPRE kit assurance de remboursement de la <font color="red">SMCIPN</font>w<font color="blue">i</font></h4>
    </div>
	<div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <form action="/eu-domiciliation/domicilierassurance" name="fm_domicil" method="POST" id="fm_domicil">
		    <fieldset>
                <legend>Informations sur le bénéficiaire</legend>
                <table>
                    <tr>
                        <td>Code membre bénéficiaire *</td><td><input name="num_benef" id="num_benef" class="validate[required]" value="<?php echo $this->num_benef ?>" size=30/></td>
                        <td>Raison sociale</td><td><input name="raison_sociale" id="raison_sociale" class="" readonly="readonly" size=35/></td>
                    </tr>
				</table>
			</fieldset>
            <fieldset>
			    <legend>Informations sur le DAO</legend>
                <table>
                    <tr>
                        <td colspan="2">Appel d'offre * <select id="id_proposition" name="id_proposition" class="validate[required]" ></select></td>
                    </tr>
					<tr>
					    <td>Montant projet <input name="mt_projet" id="mt_projet" class="validate[required,custom[onlyNumberSp]]" readonly="readonly" size="25"/></td>
					</tr>
                </table>
            </fieldset>
            <div style="margin-left: 105px; margin-top: 5px">
                <input type="button" value="Valider" name="valider" id="valider"/>
                <input type="reset" value="Rafraichir" name="refresh" id="refresh"/>
                <input id="t_annuler" type="button" value="Annuler"/>
            </div>			
        </form>
    </div>







</div>

<script>
    $(document).ready(function() {
	 $('#view-content').puipanel();
     $('fieldset').puifieldset();
    });
	
	$('#id_proposition').change(function() {
        if ($(this).val() != '') {
            $.get(
                        '/eu-domiciliation/montantprojet',
                        {
                            id_proposition: $(this).val()
                        },
                function success(data)
                {
                    $('#mt_projet').val(data);
                });
                
            } else {
                $('#mt_projet').val('');
            }
        });
	
	
	
	
	$.get("/eu-domiciliation/offrechangeass",
      function success(data) {
      var options = '<option/>';
      for (var i = 0; i < data.length; i++) {
        options += '<option value="' + data[i][1] + '">' + data[i][2] + ' </option>';
      }
      $('select#id_proposition').html(options);
    });
	
	$('#valider').click(
	function() {
	    if ($('#num_benef').val() == '') {
           alert('Renseignez les champs obligatoires');
        } else if ($('#mt_projet').val() == '') {
           alert('Sélectionnez un appel d\'offre');
        } else {
	        $.get('/eu-domiciliation/createassurance?num_benef='+$('#num_benef').val()+'&id_proposition='+$('#id_proposition').val()+'&mt_projet=' + $('#mt_projet').val(),{
            },
            function success(data) {
                if (data == 'good') {
                   alert('Opération effectuée avec succès');
				   $(location).attr("href", "/eu-domiciliation/domiass");
                } else if (data == 'insuffisant') {
                   alert("Le total des crédits non consommés est insuffisant");
                } else if (data == 'bad') {
                   alert("Echec de l'opération");
                }
            });   
	   }
		
	})
	
	
	
	
	
	$.get("/eu-domiciliation/changemoral",
                function success(data)
                {
                    $("input#num_benef").autocomplete({"source": data});
                });

        $('#num_benef').blur(function()
        {
            if ($(this).val() != '')
            {
                $.get(
                        '/eu-domiciliation/recupnom',
                        {
                            num_membre: $(this).val(), type_membre: 'M'
                        },
                function success(data) {
                    if (data !== '') {
                        $('#raison_sociale').val(data[1]);
                    } else {
                        alert('Ce membre n\existe pas!!!');
                    }
                });
            }
        });


</script>