<div id="view-content" class="ui-widget">
    <div class="ui-widget-header ui-corner-top" style="padding-left: 5px;height: 35px;">
        <h3>Ajout de secteur</h3> 
    </div>
    <div id="formdiv" class="ui-widget-content">
        <?php $this->form->setAction($this->url());echo $this->form; ?>
    </div>
</div>	
<script type="text/javascript">
    $('#submit').button();
    $('#cancel').button();
    $('#id_pays').change(function(e){
        if($(this).val() == ''){
            $('#id_region').attr('disabled', false);
        }else{
           $('#id_region').attr('disabled', true); 
        }
    });
    
    $('#id_region').change(function(e){
        if($(this).val() == ''){
            $('#id_pays').attr('disabled', false);
        }else{
           $('#id_pays').attr('disabled', true); 
        }
    });
    
</script>