<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <?php if(isset($sessionmembre->error) && $sessionmembre->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = "";?>
    </div>
  <?php }?>

  <blockquote><p>Liste des messages reçus</p></blockquote>

<?php if(count($this->entries)>0){ //echo count($this->entries);?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Titre</th>
								  <!--<th>Description</th>-->
								  <th>Code Membre Expediteur</th>
								  <th>Message reçu</th>
								  <!--<th>Alerte</th>
								  <th>Admin</th>-->
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->date_message; ?></td>
      <td><?php echo $entry->titre_message; ?></td>
      <!--<td><?php echo $entry->description_message; ?></td>-->
      <td><?php echo $entry->code_membre_expediteur; ?></td>
<?php 
        $message = new Application_Model_EuMessage();
        $messageM = new Application_Model_EuMessageMapper();
        $messageM->find($entry->id_message_envoi, $message);
?>
      <td><?php echo $message->titre_message; ?></td>
      <!--<td><div align="center">
<?php if($entry->alerte == 1){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i></a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i></a>&nbsp;
<?php }?>
			</div></td>
      <td><div align="center">
<?php if($entry->admin == 1){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i></a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i></a>&nbsp;
<?php }?>
			</div></td>-->

      <td><div align="center">
<!--<?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/message/etatmessage/id/<?php echo $entry->id_message; ?>/etat/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/message/etatmessage/id/<?php echo $entry->id_message; ?>/etat/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>-->

			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/message/detailmessage/id/<?php echo $entry->id_message; ?>"><i class="icon-edit icon-white"></i>  Details</a>&nbsp;

<?php if($entry->admin == 0){?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/message/repondremessage/id/<?php echo $entry->id_message; ?>"><i class="icon-edit icon-white"></i>  Repondre</a>&nbsp;
<?php }?>

			</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun message  enregistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








