<?php
  $auth = Zend_Auth::getInstance()->setStorage(new Zend_Auth_Storage_Session('admin'));
  $user = $auth->getIdentity();
?>
<div id="view-content" title='Creation:GAC &nbsp<?php echo strtoupper($this->type_gac); ?>' style="font-size: 12px;min-height: 520px;">
     <form id="fmm_membre" action="/eu-membre/deploiementgac" method="POST">
        <fieldset style="margin-bottom: 2px;">
            <legend>Informations GAC</legend>
			<table>
			       <tr>
					    <td>Désignation Gac *</td><td><input size="30" name="designation_gac" id="designation_gac" class="validate[required]" value="<?php echo $this->designation ?>"/></td>
                   </tr>

                   <tr><td rowspan="1"></td></tr>
				   
                   <!--
                   <tr>
                       <td>Code membre GAC *</td>
                       <td><input size="30" name="code_membre_gac" id="code_membre_gac" class="validate[required]" /></td>

                   </tr>
                               
				   <tr><td rowspan="1"></td></tr>
				   -->
				   
				   <tr>
					    <td>Code membre représentant *</td><td><input size="30" name="code_membre" id="code_membre" class="validate[required]" value="<?php echo $this->designation ?>"/></td>
                   <tr>
				   <tr><td rowspan="1"></td></tr>
				   <tr>
                        <td>Type gac *</td>
                        <td>
						<select name="type_gac" id="type_gac" required >
                           <option value="">Choisir le type de gac </option>
						   <?php if(strtoupper($this->type_gac) == "GAC_DETENTRICE") { ?>
                           <option value="GAC_DETENTRICE">Détentrice</option>
						   <?php } ?>
						   
						   <?php if(strtoupper($this->type_gac) == "GAC_SURVEILLANCE") { ?>
                           <option value="GAC_SURVEILLANCE">Surveillance</option>
						   <?php } ?>
						   
						   <?php if(strtoupper($this->type_gac) == "GAC_EXECUTANTE") { ?>
		                   <option value="GAC_EXECUTANTE">Exécutance</option>
						   <?php } ?>
                        </select>
                        </td>
					</tr>
					<tr><td rowspan="1"></td></tr>
					<tr>
                        <td>Appartenance Gac *</td>
                        <td>
						<select name="niveau_gac" id="niveau_gac" required>
                           <option value="">Choisir l'appartenance </option>
						   <?php if($user->code_groupe == 'gacd' || $user->code_groupe == 'gacs' || $user->code_groupe == 'gacex') { ?>
                           <option value="SOURCE">Source</option>
						   <?php } ?>
						   
						   <?php if($user->code_groupe == 'gacdm' || $user->code_groupe == 'gacsm' || $user->code_groupe == 'gacexm') {  ?>
                           <option value="MONDE">Monde</option>
						   <?php } ?>
						   
						   <?php if($user->code_groupe == 'gacdz' || $user->code_groupe == 'gacsz' || $user->code_groupe == 'gacexz') { ?>
		                   <option value="ZONE">Zone</option>
						   <?php } ?>
						   
						   <?php if($user->code_groupe == 'gacdp' || $user->code_groupe == 'gacsp' || $user->code_groupe == 'gacexp') { ?>
                           <option value="PAYS">Pays</option>
						   <?php } ?>
						   
						   <?php if($user->code_groupe == 'gacdregion' || $user->code_groupe == 'gacsregion' || $user->code_groupe == 'gacexregion') { ?>
            		       <option value="REGION">Région</option>
						   <?php } ?>
						   
						   <?php if($user->code_groupe == 'gacdsecteur' || $user->code_groupe == 'gacssecteur' || $user->code_groupe == 'gacexsecteur') { ?>
            		       <option value="PREFECTURE">Préfecture</option>
						   <?php } ?>
						   
						   <?php if($user->code_groupe == 'gacdagence' || $user->code_groupe == 'gacsagence' || $user->code_groupe == 'gacexagence') { ?>
            		       <option value="CANTON">Canton</option>
						   <?php } ?>
                        </select>
                        </td>
					</tr>
                    <tr><td rowspan="1"></td></tr>
					<tr>
                        <td>Agence *</td>
				        <td>
						   <select  id="code_agence" name="code_agence" required="true">
                           <option value="">Choisir une agence</option>
                           <?php foreach ($this->agences as $value) { ?>
                           <option
                               value="<?php echo $value->code_agence; ?>"><?php echo $value->libelle_agence; ?></option>                         
                           <?php } ?>
                           </select>
						</td>
					</tr>
                    <tr><td rowspan="1"></td></tr>
                    <tr>
					    <td>Login Gac *</td><td><input size="30" name="gac_login" id="gac_login" class="validate[required]" /></td>
					</tr>

                    <tr><td rowspan="1"></td></tr>					
                    <tr>
					   <td>Mot de passe Gac *</td><td><input type="password" size="30" name="gac_passe" id="gac_passe" class="validate[required]" /></td> 
					</tr>
					
					<tr><td rowspan="1"></td></tr>					
                    <tr>
					   <td>Confirmer Mot de passe Gac  *</td><td><input type="password" name="confirme" id="confirme" class="validate[required]" /></td> 
					</tr>
					
			</table>
        </fieldset>
		
        <fieldset style="margin-bottom: 2px;">
            <legend>Découpage géographique</legend>
			<table>
			       <tr>
                        <td>Zone M *</td>
				        <td>
						   <select  id="code_zone" name="code_zone" required="true">
                           <option value="">Choisir une zone monétaire</option>
                           <?php foreach ($this->zones as $value) { ?>
                           <option
                               value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>                         
                           <?php } ?>
                           </select>
						</td>
					</tr>
					<tr><td rowspan="1"></td></tr>
					<tr>
                        <td>Pays *</td>
				        <td>
						   <select  id="id_pays" name="id_pays" required="true" >
                           <option value="">Choisir un pays</option>
                           <?php foreach ($this->pays as $value) { ?>
                           <option
                              value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>                         
                           <?php } ?>
                           </select>
						</td>
					</tr>
					<tr><td rowspan="1"></td></tr>
					<tr>
                        <td>Région *</td>
				        <td>
						    <select  id="id_region" name="id_region" required="true">
                            <option value="">Choisir une région</option>
                            <?php foreach ($this->regions as $value) { ?>
                            <option
                                  value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>                         
                            <?php } ?>
                            </select>
						</td>
					</tr>
					<tr><td rowspan="1"></td></tr>
					<tr>
                        <td>Préfecture *</td>
				        <td>
						   <select  id="id_prefecture" name="id_prefecture" required="true"> 
                           <option value="">Choisir une préfecture</option>
                           <?php foreach ($this->prefectures as $value) { ?>
                           <option
                           value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>                         
                           <?php } ?>
                           </select>
						</td>
					</tr>
					<tr><td rowspan="1"></td></tr>
					<tr>
                        <td>Canton *</td>
				        <td>
						   <select  id="id_canton" name="id_canton" required="true">
                           <option value="">Choisir un canton</option>
                           <?php foreach ($this->cantons as $value) { ?>
                           <option
                             value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>                         
                            <?php } ?>
                       </select>
						</td>
					</tr>
			
            </table>
        </fieldset>
		 
        <div style="margin-top: 10px;">
            <input type="submit" value="Valider" name="valider" id="valider"   />
            <input type="reset" value="Rafraichir" name="refresh" id="refresh"   />
            <input id="t_annuler" type="button" value="Annuler" />
        </div>
    </form>
</div>

<script type="text/javascript">
        $(document).ready(function() {
            $(function() {
              $('#view-content').puipanel();
              $('fieldset').puifieldset();
            });
				   
           //binds form submission and fields to the validation engine
           jQuery("#fmm_membre").validationEngine();
        
		   $('#valider').button();
           $('#t_annuler').button();
           $('#refresh').button();
           $('#add').button();
           $('#remove').button();
		   
		   $("#code_zone").change(function(e) {
               var code = $(this).val();       
               $.get("/eu-membre/listpays", {type: code},
                 function success(data) {
                    var options = '<option/>';
                    for(var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                    }
                    $('select#id_pays').html(options);
                 });
                 e.preventDefault();
           })
		   
		   $("#id_pays").change(function(e) {
               var code = $(this).val();       
               $.get("/eu-membre/listregion", {type: code},
                 function success(data) {
                    var options = '<option/>';
                    for(var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                    }
                    $('select#id_region').html(options);
                 });
                 e.preventDefault();
           })
		   
		   $("#id_region").change(function(e) {
               var code = $(this).val();       
               $.get("/eu-membre/listprefecture", {type: code},
                 function success(data) {
                    var options = '<option/>';
                    for(var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                    }
                    $('select#id_prefecture').html(options);
                 });
                 e.preventDefault();
           })
		   
		   
		   
		   
		   $("#id_prefecture").change(function(e) {
               var code = $(this).val();       
               $.get("/eu-membre/listcanton", {type: code},
                 function success(data) {
                    var options = '<option/>';
                    for(var i = 0; i < data.length; i++) {
                       options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                    }
                    $('select#id_canton').html(options);
                 });
                 e.preventDefault();
           })

      });
							
							
							$.get("/eu-membre/pays",
                              function success(data) {
                                            var options = '<option/>';
                                            for (var i = 0; i < data.length; i++) {
                                                options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                                            }
                                            $('select#id_pays').html(options);
                            });
							
							if(($('#code_groupe').val() == 'gacdp') || ($('#code_groupe').val() == 'gacsp') || ($('#code_groupe').val() == 'gacexp')) {  
							     $.get("/eu-membre/pays",
                                 function success(data) {
                                   var options = 
								   '<option></option>'+
								   '<option value="pays">Gac Pays</option>';
                                   $('select#categorie_gac').html(options);
                                });
							} else if(($('#code_groupe').val() == 'gacd') || ($('#code_groupe').val() == 'gacs') || ($('#code_groupe').val() == 'gacex')) {  
							     $.get("/eu-membre/pays",
                                 function success(data) {
                                   var options = 
								   '<option></option>'+
								   '<option value="source">Gac Source</option>';
                                   $('select#categorie_gac').html(options);
                                });
							} else if(($('#code_groupe').val() == 'gacdm') || ($('#code_groupe').val() == 'gacsm') || ($('#code_groupe').val() == 'gacexm')) {  
							     $.get("/eu-membre/pays",
                                 function success(data) {
                                   var options = 
								   '<option></option>'+
								   '<option value="monde">Gac Monde</option>';
                                   $('select#categorie_gac').html(options);
                                });
							} else if(($('#code_groupe').val() == 'gacdz') || ($('#code_groupe').val() == 'gacsz') || ($('#code_groupe').val() == 'gacexz')) {  
							     $.get("/eu-membre/pays",
                                 function success(data) {
                                   var options = 
								   '<option></option>'+
								   '<option value="zone">Gac Zone</option>';
                                   $('select#categorie_gac').html(options);
                                });
							}								
							  						  
							  
							
														
							
							
							
							
							
							
							
							
						   
						   $.get( "/eu-membre/membrephys",
                                 function success(data) {
                                 $("#code_rep").autocomplete({"source":data});
                            });
							
							
							
						   
						   
	
							
							
							
                            
                            
                            
</script>
