<div id="view-content" title="Identification:Nouveau Membre Personne Physique" style="font-size: 12px">
     <form id="fm_membre" action="/eu-membre/newcaps" method="POST" enctype="multipart/form-data">
           <input type="hidden" name="cpteur" id="cpteur" value="1"/>
		   <input name="code_caps" id="code_caps" type="hidden" value="<?php echo $this->code; ?>">
           <fieldset style="margin-bottom: 2px;"><legend>CM</legend>
           <table>
              <tr>
				    <td>CAPS *</td><td><input size="6"  class="validate[required number]" maxlength="10" name="frais_identification" id="frais_identification" readonly="true"  value="<?php echo $this->caps; ?>"/></td>
                    <td><input  type="hidden" name="code_caps" id="code_caps" maxlength="13" value="<?php echo $this->code; ?>"></td>
                    <td><label>Règlement *: </label></td>
                    <td>
                        <select name="reglement_membre" id="reglement_membre" class="validate[required]" value="<?php echo $this->reglement_membre ?>">
                        <option value="N">Numéraire</option>
                        <option value="CNP" disabled="true">CNP(RPG/I)</option>
                        </select>
                    </td>
                    <?php if ($this->code == '') { ?>
                        <td><label id="sms_label">Code SMS *: </label></td>
                        <td>
                            <div id="sms_div"><input name="code_sms" id="code_sms" class="validate[required]" maxlength="8" value="<?php echo $this->code_sms; ?>" ></div>
                        </td>
                    <?php } else { ?>
					    <td><input type="hidden" name="membre_reg" id="membre_reg"  value="<?php echo $this->apporteur; ?>"></td>
					<?php } ?>
                    <td>
                        <div id="membre_div" style="display:none">
						     <table>
							        <thead>
									
									</thead>
							        <tbody>
									<tr>
									<td>
						            <select id="type_membre">
											  <option value=""></option>
                                              <option value="P">Physique</option>
                                              <option value="M">Morale</option>
                                     </select>
									 </td>
									 <td>
						                 <input name="membre_reg" id="membre_reg" class="validate[required]" >
							         </td>
                                     </tr>
									 </tbody>
									 
							 </table>
						</div>
                    </td>
					<td>
					    <div id="nn_div" style="display:none">
						     <table>
							 <tbody>
							 <tr>
							 <td><label>Apporteur*</label></td>
					         <td><input name="membre_nn" id="membre_nn" class="validate[required]" size="25"></td>
						     <td>Compte*</td>
					         <td><select id="type_mf" class="validate[required]" name="type_mf"></select></td> 
							 </tr>
							 </tbody>
							 </table> 
						</div>
					</td>
                </tr>
            </table>
            </fieldset>
            <fieldset style="margin-bottom: 2px;">
            <legend>Etat civil</legend>
            <table>
                <tr><td>Nom *</td><td><input size="30" name="nom_membre"  id="nom_membre" class="validate[required]" value="<?php echo $this->nom_membre ?>"/></td> <td>Prénoms *</td><td><input size="30" name="prenom_membre" id="prenom_membre" value="<?php echo $this->prenom_membre ?>"/></td></tr>
                <tr><td>Genre *</td>
                    <td><select name="sexe_membre" id="sexe_membre" class="validate[required]" value="<?php echo $this->sexe ?>">
                            <option value=""></option>
                            <option value="M">Masculin</option>
                            <option value="F">Féminin</option>
                        </select>
                    </td>
                    <td>Date de naissance *</td>
                    <td><input style="text-align: right" name="date_nais_membre" id="date_nais_membre" class="validate[required]" value="<?php echo $this->datenais ?>"/></td></tr>
                <tr>
                    <td>Nationalité *</td><td><select id="nationalite_membre" name="nationalite_membre" class="validate[required]" value="<?php echo $this->nation ?>"/></td> 
                    <td>Lieu de naissance *</td><td><input size="30" name="lieu_nais_membre" id="lieu_nais_membre" class="validate[required]" value="<?php echo $this->lieu_nais ?>"></td></tr>
                <tr><td>Nom du père</td><td><input size="30" name="pere_membre" value="<?php echo $this->pere ?>"/></td> <td>Nom de la mère</td><td><input size="30" name="mere_membre" value="<?php echo $this->mere ?>"></td></tr>

                <tr><td>Situation matrimoniale *</td>
                    <td><select name="sitfam_membre" class="validate[required]" value="<?php echo $this->sitfam ?>">
                            <option value=""></option>
                            <option value="C">Célibataire</option>
                            <option value="D">Divorcé(e)</option>
                            <option value="M">Marié(e)</option>
                            <option value="V">Veuf(ve)</option>
                        </select></td> 
                    <td>Nombre d'enfant *</td><td><input name="nbr_enf_membre" maxlength="2" class="validate[required,custom[onlyNumberSp]]" value="<?php echo $this->nbre_enf ?>"></td></tr>
            </table>
        </fieldset>
        <fieldset style="margin-bottom: 2px;">
            <legend>Adresse</legend>
            <table>
                <tr>
                    <td><label>BP : </label><input id="bp_membre" name="bp_membre" value="<?php echo $this->bp ?>"/></td>
                    <td><label>Quartier * : </label><input size="25" name="quartier_membre" value="<?php echo $this->quartier_membre ?>" class="validate[required]"/></td> 
                    <td><label>Ville * : </label><input size="25" name="ville_membre" id="ville_membre" class="validate[required]" value="<?php echo $this->ville_membre ?>"/></td>
                </tr>
                <tr>
                    <td><label>Email : </label><input size="25" name="email_membre" class="validate[custom[email]]" value="<?php echo $this->email ?>"/></td> 
                    <td><label>Cellulaire * : </label><input style="text-align: right" id="portable_membre" name="portable_membre" class="validate[required]" value="<?php echo $this->portable ?>"></td>
                    <td><label>Téléphone</label><input style="text-align: right" id="tel_membre" name="tel_membre" class="validate[custom[onlyNumberSp]]" value="<?php echo $this->tel ?>"/></td>
                </tr>
            </table>
        </fieldset>
		
		<fieldset style="margin-bottom: 2px;">
            <legend>Acteurs</legend>
			<table>
                <tbody>
                    <tr>
					    <td><input type="checkbox" id="actcmfh" name="actcmfh" value="CMFH"></td>
					    <td><label>CMFH ( Conseiller Membre Fondateur d'Honneur ) </label></td>
						<!--<td width="160px"></td>
						<td><input type="checkbox" id="actenro" name="actenro" value="DSMS"></td>
						<td>Enrôleur</td>-->
					</tr>
				</tbody>	
			</table>
		</fieldset>
		
        <fieldset style="margin-bottom: 2px;">
            <legend>Autres informations</legend>
            <table>
                <tbody>
                    <tr>
                        <td>Profession *</td><td><input size="30" name="profession_membre" class="validate[required]" value="<?php echo $this->profession ?>"/></td> 
                        <td>Formation</td><td><input size="30" name="formation" value="<?php echo $this->formation ?>"></td>
                        <td>Religion *</td><td><select id="religion_membre" class="validate[required]" name="religion_membre" value="<?php echo $this->religion ?>"></select></td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
        <fieldset style="margin-bottom: 2px;">
            <legend>Comptes bancaires</legend>
            <table id="tab_banque">
                <thead>
                <th>Banque</th><th>Nom</th><th>Numéro du Compte</th>
                </thead>
                <tbody>
                    <tr>
                        <td><select id="code_banque1" type="text" name="code_banque1" value=""/></td>
                        <td><input id="nom_banque1" type="text" name="nom_banque1" value="" size="40" readonly="true"/></td>
                        <td><input id="num_compte1" type="text" name="num_compte1" value="" size="30" /></td>
                        <td><input id="add" type="button" value="+" onclick="addRow('tab_banque');"/><input id="remove" type="button" value="-" onclick="deleteRow('tab_banque');"/></td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
        <div style="margin-top: 10px;">
<input name="codesecret" type="hidden" id="codesecret" value="<?php echo $this->codesecret; ?>" />
             <input type="submit" value="Valider" id="valider"   />
             <input type="reset" value="Rafraichir" id="refresh"   />
             <input id="t_annuler" type="button" value="Annuler" />
        </div>
    </form>
</div>

<script type="text/javascript">
        $(document).ready(function() {
         $(function() {
            if ($('#code_caps').val() !== '') {
               $("#reglement_membre option[value='CAPS']").attr('selected','selected');
               $('#reglement_membre').attr('disabled',true);
			   $('#membre_app').css('display','block');                   
               $('#membre_reg').attr('size',30);
            }
			
			$('#actcmfh').change(function() {
              if(document.getElementById('actcmfh').checked) {
                $('#actenro').attr('disabled',true);} 
			  else {
				$('#actenro').attr('disabled',false);
			  }
            });
								
		    $('#actenro').change(function() {
               if(document.getElementById('actenro').checked) {
                 $('#actcmfh').attr('disabled',true);} 
			   else {
				 $('#actcmfh').attr('disabled',false);
			   }
            });
			
			$('#refresh').click(function() {
                $('#actcmfh').attr('disabled',false);
			    $('#actenro').attr('disabled',false);
			});
			
			
            var pickerOpts = {
                         dateFormat: "dd/mm/yy",
                         changeMonth: true,
                         changeYear: true,
                         showOtherMonths: true,
                         maxDate: $(this).datepicker('getDate')
                                    };
                                    $.datepicker.setDefaults($.datepicker.regional[ "fr" ]);
                                    $("#date_nais_membre").inputmask("d/m/y").datepicker(pickerOpts);
                                    $('#view-content').puipanel();
                                    $('fieldset').puifieldset();
                                });
								
                                $("#fm_membre").validationEngine();
                                $('#valider').button();
                                $('#refresh').button();
                                $('#t_annuler').button();
                                $('#add').button();
                                $('#remove').button();
								
                                //$("#tel_membre").inputmask({"mask": "99 99 99 99"});
                                //$("#portable_membre").inputmask({"mask": "99 99 99 99"});

                                $.get("/eu-membre/compte",
                                        function success(data) {
                                            var options = '<option/>';
                                            for (var i = 0; i < data.length; i++) {
                                                options += '<option value="' + data[i] + '">' + data[i] + ' </option>';
                                            }
                                            $('select#code_banque1').html(options);
                                        });

                                $.get("/eu-membre/nation",
                                 function success(data) {
                                   var options = '<option/>';
                                   for (var i = 0; i < data.length; i++) {
                                       options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                                   }
                                   $('select#nationalite_membre').html(options);
                                });

                                $.get("/eu-membre/religion",
                                        function success(data)
                                        {
                                            var options = '<option/>';
                                            for (var i = 0; i < data.length; i++) {
                                                options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                                            }
                                            $('select#religion_membre').html(options);
                                        });
										
								$.get("/eu-membre/typemf",
                                        function success(data)
                                        {
                                            var options = '<option/>';
                                            for (var i = 0; i < data.length; i++) {
                                                options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
                                            }
                                            $('select#type_mf').html(options);
                                        });		
										

                                $('#code_banque1').change(function(e)
                                {
                                    if ($(this).val() !== '')
                                    {
                                        $.get(
                                                '/eu-membre/nomcompte',
                                                {
                                                    code: $(this).val()
                                                },
                                        function success(data)
                                        {
                                            if (data !== false) {
                                                $('#nom_banque1').val(data);
                                            } else {
                                                alert('Pas de banque correspondant à ce code');
                                            }

                                        });
                                    }
                                    e.preventDefault();
                                });

                                $('#reglement_membre').change(function(e) {
                                    if ($(this).val() !== '') {
                                        if ($(this).val() === 'N') {
                                          $('#sms_label').html('Code SMS * : ');
                                          $('#membre_div').css('display', 'none');
										  $('#nn_div').css('display', 'none');
                                          $('#membre_reg').val('');
                                          $('#sms_div').css('display', 'block');
										   $('#sms_label').css('display', 'block');
                                        } else if ($(this).val() === 'CAPS') { 
										  $('#sms_label').css('display','block');
                                          $('#sms_label').html('Membre Apporteur * : ');
                                          $('#membre_div').css('display', 'block');
                                          $('#sms_div').css('display','none');
										  $('#nn_div').css('display','none');
                                          $('#code_sms').val('');
                                          $('#membre_reg').attr('size', 30);
                                        } else {
										  $('#membre_div').css('display','none');
                                          $('#sms_div').css('display','none');
										  $('#sms_label').css('display','none');
										  $('#nn_div').css('display','block');
                                          $('#code_sms').val('');
                                          $('#membre_nn').attr('size',30);   
										}
                                   }
                                   e.preventDefault();
                                });
                                
								$('#membre_reg').attr('readonly',true);
                                $("#type_membre").change(function(e) {
                                       e.preventDefault();
			                           $('#membre_reg').val('');
                                       if ($(this).val() != '') {
		                                    $('#membre_reg').attr('readonly',false);
				                            $.get("/eu-carte/membreapporteur",{
                                            type_membre : $('#type_membre').val()
                                        },
                                        function success(data) {
                                            $("#membre_reg").autocomplete({minLength: 5, "source": data});
                                        });
			                    }
			                    else {
			                         $('#membre_reg').attr('readonly',true);	  
			                    }
        
                            })

                                $('#code_sms').blur(function(e)
                                {
                                    if ($(this).val() !== '')
                                    {
                                        $.get(
                                                '/eu-membre/codesms',
                                                {
                                                    code: $(this).val()
                                                },
                                        function success(data)
                                        {
                                            if (data[0] === 0) {
                                                $("#message").html('Ce code ' + data[1] + ' est invalide')
                                            } else {
                                                if (data[0] !== $('#frais_identification').val()) {
                                                    $("#message").html("La valeur de ce code :" + data[0] + " " + data[1] + " ne correspond pas à la valeur du FS");
                                                }
                                            }


                                        });
                                    }
                                    e.preventDefault();
                                });
                            });
                            var compteur = 1;
                            function addRow(tableID) {

                                var table = document.getElementById(tableID);
                                var rowCount = table.rows.length;
                                var cpte = rowCount;
                                var row = table.insertRow(rowCount);

                                var cell1 = row.insertCell(0);
                                var element0 = document.createElement("select");
                                element0.setAttribute("id", "code_banque" + cpte);
                                element0.setAttribute("name", "code_banque" + cpte);
                                cell1.appendChild(element0);
								$('#code_banque'+ cpte).puiinputtext();

                                var cell2 = row.insertCell(1);
                                var element1 = document.createElement("input");
                                element1.type = "text";
                                element1.setAttribute("id", "nom_banque" + cpte);
                                element1.setAttribute("name", "nom_banque" + cpte);
                                element1.setAttribute("size", "40");
                                element1.setAttribute("readonly", "true");
                                cell2.appendChild(element1);
								$('#nom_banque'+ cpte).puiinputtext();

                                var cell3 = row.insertCell(2);
                                var element2 = document.createElement("input");
                                element2.type = "text";
                                element2.setAttribute("id", "num_compte" + cpte);
                                element2.setAttribute("name", "num_compte" + cpte);
                                element2.setAttribute("size", "30");
                                cell3.appendChild(element2);
								$('#num_compte'+ cpte).puiinputtext();

                                $.get("/eu-membre/compte",
                                        function success(data) {
                                            var options = '<option/>';
                                            for (var i = 0; i < data.length; i++) {
                                                options += '<option value="' + data[i] + '">' + data[i] + ' </option>';
                                            }
                                            $('select#code_banque' + cpte).html(options);
                                });

                                $('#code_banque' + cpte).change(function(e)
                                {
                                    if ($(this).val() !== '')
                                    {
                                        $.get(
                                                '/eu-membre/nomcompte',
                                                {
                                                    code: $(this).val()
                                                },
                                        function success(data)
                                        {
                                            if (data !== false) {
                                                $('#nom_banque' + cpte).val(data);
                                            }
                                            else {
                                                alert('Pas de banque correspondant à ce code');
                                            }
                                        });
                                    }
                                    e.preventDefault();
                                });
                                compteur = compteur + 1;
                                document.getElementById("cpteur").setAttribute('value', compteur);
                            }

                            function deleteRow(tableID) {
                                try {
                                    var table = document.getElementById(tableID);
                                    var rowCount = table.rows.length - 1;
                                    if (rowCount > 1) {
                                        table.deleteRow(rowCount);
                                        compteur = compteur - 1;
                                        document.getElementById("cpteur").setAttribute('value', compteur);
                                    }
                                } catch (e) {
                                    alert(e);
                                }
                            }
</script>
