<style>

#article_condition_felm{

    font-size:1.2rem;

    text-align:justify;

}

</style>


<article id="article_condition_felm">

<header style="display:block;text-align:center;font-weight:bold;font-size:1.5rem;margin-bottom:20px">CONDITIONS FRANCHISE LOCALE DE BASE (FLB)</header>  


<ul>
    <li>Etre une Entreprise Commerciale ;</li>

    <li>Etre équipé de :
    
     <ul>
         <li>Ordinateur,  </li>

         <li>Téléphone Android avec lecteur d’empreinte biométrique,</li>

         <li>Lecteur d’empreinte biométrique,</li>

         <li>Multiport USB,</li>

         <li>Camera (photo et lecture QR CODE),</li>

         <li>Licence biométrique,</li>

         <li>Connexion internet haut débit ;</li>
     </ul>
    
    </li>

    <li>Disposer de son espace personnel et de son espace professionnel du « Travail Industriel Humain Universel » (TIHU) matérialisé par le « Kit de Solvabilité Universel » (KSU) sur la plateforme GIE <span style="color:#950707">ESMC</span>. A défaut les acheter au prix unitaire de 70.000 FCFA soit au total 140.000 FCFA ;</li>


    <li>Remplir dans son KSU les conditions de l’activation des : 
    
    <ul>

        <li>Activité Génératrice de Revenus Offreurs de Biens Produits et Services Dématérialisés (AGR OBPSD) ou </li>

        <li>Activité Génératrice de Revenus Offreurs de Biens Produits et Services (AGR OBPS) ; </li>

    </ul>
    
    </li>

    <li>Acheter le Bon d’Achat neutre (BAn) de réapprovisionnement (à revendre aux Acteurs de l’Activité Génératrice de Revenus Offreurs de Kit de Solvabilité Universel (AGR OKSU)) d’une valeur minimale de dix (10) projets au prix unitaire de 1.305.250 FCFA soit un total de 13.052.500 FCFA à titre de fonds de roulement ; </li>
    
    <li>Disposer de 35.000.000 de Bons de Consommation non récurrente (BCnr) ou de Bons de Consommation interne (BCi) pour acheter la Franchise. A défaut l’acheter auprès des Franchisés qui en disposent sur la plateforme GIE <span style="color:#950707">ESMC</span> ou auprès de tout adhérent par l’intermédiaire des Franchisés ;</li>

    <li>Renseigner les formulaires du contrat de la Franchise et valider.</li>
</ul>


</article>