<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
  <div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Details d'une fiche de stock</p></blockquote>
  
    
  

  
<div class="control-group">
<label class="control-label" for="nom_article">Nom article </label>
<div class="controls">
<?php echo $this->fiche_stock->nom_article; ?>
</div>
</div>


    








<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








