<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modifier  une fiche de stock</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="editeli">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
  
    

<div class="control-group">
<label class="control-label" for="nom_article">Nom article *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="nom_article" id="nom_article" placeholder="Nom article" value="<?php echo $this->fiche_stock->nom_article;?>" required>
</div>
</div>








<input name="validation_ggsm" type="hidden" id="validation_ggsm" value="0" />
<input name="validation_agent_comptable" type="hidden" id="validation_agent_comptable" value="0" />
<input name="validation_rsf" type="hidden" id="validation_rsf" value="0" />

<div class="form-actions">
<input name="id_fiche_stock" type="hidden" id="id_fiche_stock" value="<?php echo $this->fiche_stock->id_fiche_stock; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier  la fiche de stock</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








