<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste des  lettres de relance</p></blockquote>
<?php //echo $sessionmembre->id_canton;?> 
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
                  <th>Nom article</th>
                  <th>QQSM</th>
                  <th>Agent comptable</th>
                  <th>RSF</th>
                  <!--<th>Validation</th>-->
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->nom_article; ?></td>
      <td><?php if($entry->validation_ggsm == 1){?>
      <a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
      <a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?></td>
      <td><?php if($entry->validation_agent_comptable == 1){?>
      <a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
      <a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?></td>
      <td><?php if($entry->validation_rsf == 1){?>
      <a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
      <a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?></td>
      <?php /*?><td><div align="center">
<?php 
        $a_formulaireM = new Application_Model_EuAttributionUserGroupFormulaireMapper();
        $a_formulaire = $a_formulaireM->fetchAllByNom("listfichestockadmin");

        $formulaire = new Application_Model_EuFormulaire();
        $formulaireM = new Application_Model_EuFormulaireMapper();
        $formulaireM->find($entry->formulaire_id, $formulaire);

        $attribution_user_group_formulaireM = new Application_Model_EuAttributionUserGroupFormulaireMapper();
        $attribution_user_group_formulaire2 = $attribution_user_group_formulaireM->fetchAllByFormulaireDepart($formulaire->formulaire_id, $sessionmembre->code_groupe);
$attribution_user_group_formulaire = $attribution_user_group_formulaire2[0];

        $attribution_user_group_formulaire1M = new Application_Model_EuAttributionUserGroupFormulaireMapper();
        $attribution_user_group_formulaire12 = $attribution_user_group_formulaire1M->fetchAllByFormulaireDepartAutre($formulaire->formulaire_id, $sessionmembre->code_groupe, $sessionmembre->code_groupe);
$attribution_user_group_formulaire1 = $attribution_user_group_formulaire12[0];
?>

<?php if(count($attribution_user_group_formulaire2[0]) > 0){?>
<?php if($entry->valid == $attribution_user_group_formulaire2[0]->code_groupe_depart){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/stock/validfichestockadmin/id/<?php echo $entry->id_fiche_stock; ?>/valid/<?php echo $attribution_user_group_formulaire2[0]->code_groupe_depart; ?>"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/stock/validfichestockadmin/id/<?php echo $entry->id_fiche_stock; ?>/valid/<?php echo $attribution_user_group_formulaire2[0]->code_groupe_depart; ?>"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
<?php }?>
<?php if(count($attribution_user_group_formulaire12[0]) > 0){?>
<?php if($entry->valid == $attribution_user_group_formulaire12[0]->code_groupe_depart){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
<?php }?>

			</div></td><?php */?>
      <td><div align="center"><?php /*?>
<?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/stock/etatfichestockadmin/id/<?php echo $entry->id_fiche_stock; ?>/etat/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/stock/etatfichestockadmin/id/<?php echo $entry->id_fiche_stock; ?>/etat/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>

			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/stock/detailfichestockadmin/id/<?php echo $entry->id_fiche_stock; ?>"><i class="icon-edit icon-white"></i>  Details</a>&nbsp;

			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/stock/editfichestockadmin/id/<?php echo $entry->id_fiche_stock; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<?php */?></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune fiche de stock  enregistrée 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








