<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des details de fiches de stock</p></blockquote>
<?php //echo $sessionutilisateur->id_canton;?> 
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Fiche Stock</th>
								  <th>Reference</th>
								  <th>Entrée</th>
                  <th>Sortie</th>
								  <th>Stocks</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->date_article; ?></td>
<?php 
        $fiche_stock = new Application_Model_EuFicheStock();
        $fiche_stockM = new Application_Model_EuFicheStockMapper();
        $fiche_stockM->find($entry->id_fiche_stock, $fiche_stock);
?>
      <td><?php echo $fiche_stock->nom_article; ?></td>
      <td><?php echo $entry->reference_article_fiche_stock; ?></td>
      <td><?php echo $entry->entree_valeur; ?></td>
      <td><?php echo $entry->sortie_valeur; ?></td>
      <td><?php echo $entry->stocks_valeur; ?></td>
      <td><div align="center">
<?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/stock/etatdetailfichestockadmin/id/<?php echo $entry->id_detail_fiche_stock; ?>/etat/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/stock/etatdetailfichestockadmin/id/<?php echo $entry->id_detail_fiche_stock; ?>/etat/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>

			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/stock/detaildetailfichestockadmin/id/<?php echo $entry->id_detail_fiche_stock; ?>"><i class="icon-edit icon-white"></i>  Details</a>&nbsp;

			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/stock/editdetailfichestockadmin/id/<?php echo $entry->id_detail_fiche_stock; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun detail de fiche de stock  enregistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








