<div id="view-content" title="Echange <?php echo $this->cat; ?>" style="font-size: 12px;min-height: 520px;">
    <form id="echange_form" method="POST" action="/eu-echange/echangecncs">
        <table width="700" style="margin-top: 50px;margin-left: 100px;">
            <tr>
                <td><label for="compte" style="width: 100px;">Cartes numériques :</label></td>
                <td>
                    <select  id="compte" name="compte" value="<?php echo $this->compte ?>">
                        <option value="TCNCS">TCNCS</option>
                        <option value="TCNCSEI">TCNCSEI</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td><label for="e_membre">Membre :</label></td><td><input type="text" size="30" id="e_membre" name="e_membre" value="<?php echo $this->e_membre ?>" required="true"/></td>
            </tr>
            <tr>
                <td><label for="e_membre">Nom Membre :</label></td>
                <td><input size="30" type="text" id="nom_membre" name="nom_membre" value="<?php echo $this->nom_membre ?>" readonly="true"/>
                    <input size="30" type="text" id="prenom_membre" name="prenom_membre" value="<?php echo $this->prenom_prenom ?>" readonly="true"/></td>
            </tr>
            <tr><td><label for="montant">Montant :</label></td><td><input style="text-align: right;" type="text" size="25" id="montant" name="montant" value="<?php echo $this->montant ?>" required="true"/></td></tr>
            <tr><td></td><td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="annuler"/></td></tr>
        </table>
    </form>
</div>
<script type="text/javascript">
    $(document).ready(function()
    {
        $(function() {
            $('#view-content').puipanel();
            $('fieldset').puifieldset();
        });
        if ($('#compte').val() === 'TCNCS') {
            $.get("/eu-echange/membre?type=P",
                    function success(data)
                    {
                        $('#e_membre').autocomplete({"source": data});
                    });
                } else {
            $.get("/eu-echange/membre?type=M",
                    function success(data)
                    {
                        $('#e_membre').autocomplete({"source": data});
                    });
                }
        $('#e_membre').blur(function(e)
        {
            e.preventDefault();
            if ($(this).val() !== '')
            {
                $.get(
                        '/eu-echange/recupnom',
                        {
                            num_membre: $(this).val()
                        },
                function success(data)
                {
                    $("#nom_membre").val(data[0]);
                    $("#prenom_membre").val(data[1]);
                });

                $.get(
                        '/eu-echange/solde',
                        {
                            code_membre: $(this).val(), type_compte: $("#compte").val()
                        },
                function success(data)
                {
                    if (data !== false) {
                        $("#montant").val(data);
                    }
                });
            }
        });
        $('#compte').change(function(e) {
            e.preventDefault();
            if ($(this).val() === 'TCNCS') {
                $.get("/eu-echange/membre?type=P",
                        function success(data)
                        {
                            $('#e_membre').autocomplete({"source": data});
                        });
                    } else {
                $.get("/eu-echange/membre?type=M",
                        function success(data)
                        {
                            $('#e_membre').autocomplete({"source": data});
                        });
                    }
        });
    });
</script>