<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des ventes chez soi même</p></blockquote>
<?php if(count($this->entries)>0) { ?>

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  <tr>
								  <th>Vendeurs</th>
									<th>Acheteurs</th>
									<th>Date</th>
								  <th>Réference</th>
								  <th>Désignation</th>
								  <th>Prix unitaire</th>
									<th>Quantité</th>
									<th>Actions</th>
							  </tr>
						  </thead>
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php if (substr($entry->code_membre_morale, -1) == "P") {
			$membreM = new Application_Model_EuMembreMapper();
			$membre = new Application_Model_EuMembre();
			$membreM->find($entry->code_membre_morale, $membre);?>
			<?php echo htmlentities($membre->nom_membre); ?> <?php echo htmlentities($membre->prenom_membre); ?>
			<?php } else if (substr($entry->code_membre_morale, -1) == "M") {
			$membremoraleM = new Application_Model_EuMembreMoraleMapper();
			$membremorale = new Application_Model_EuMembreMorale();
			$membremoraleM->find($entry->code_membre_morale, $membremorale);?>
			<?php echo htmlentities($membremorale->raison_sociale);?>
			<?php }	?></td>
			<td><?php if (substr($entry->code_membre_acheteur, -1) == "P") {
			$membreM = new Application_Model_EuMembreMapper();
			$membre = new Application_Model_EuMembre();
			$membreM->find($entry->code_membre_acheteur, $membre);?>
			<?php echo htmlentities($membre->nom_membre); ?> <?php echo htmlentities($membre->prenom_membre); ?>
			<?php } else if (substr($entry->code_membre_acheteur, -1) == "M") {
			$membremoraleM = new Application_Model_EuMembreMoraleMapper();
			$membremorale = new Application_Model_EuMembreMorale();
			$membremoraleM->find($entry->code_membre_acheteur, $membremorale);?>
			<?php echo htmlentities($membremorale->raison_sociale);?>
			<?php }	?></td>
      <td><?php echo datejourfr($entry->date_vente); ?></td>
			<td><?php echo $entry->reference; ?></td>
      <td><?php echo htmlentities($entry->designation); ?></td>
      <td><?php echo $entry->prix_unitaire; ?></td>
			<td><?php echo $entry->quantite; ?></td>
      <td></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else {?>
<div class="alert alert-info">
  Aucun article vendu
</div>
<?php }?>
<br />
<br />
<br />
<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>
