<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des informations additives</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  <tr>
								  <th>Réference</th>
								  <th>Désignation</th>
								  <th>L'information additive</th>
								  <th>Code Membre</th>
								  <th>Intégrateurs</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
	<?php       
    $article_stockes_M = new Application_Model_EuArticleStockesMapper();
    $article_stockes = $article_stockes_M->fectchByReference($entry->reference); ?>
	<?php       
    $membreasso = new Application_Model_EuMembreasso();
    $membreasso_M = new Application_Model_EuMembreassoMapper();
    $membreasso_M->find($entry->membreasso_id, $membreasso); ?>
    <tr>
      <td><?php echo $entry->reference; ?></td>
      <td><?php echo $article_stockes->designation; ?></td>
      <td><?php echo $entry->libelle_information_additif; ?></td>
      <td><?php echo $entry->code_membre; ?></td>
      <td><?php echo $membreasso->membreasso_nom; ?> <?php echo $membreasso->membreasso_prenom; ?></td>
      <td><div align="center"><?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="#"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="#"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?><?php /*?>&nbsp;
      
			<a class="btn btn-mini btn-danger"  onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/boutiqueligne/suppinformationadditif/id/<?php echo $entry->id_information_additif; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a><?php */?></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune information additive enregistrée 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








