<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
<?php $sessionpanier = new Zend_Session_Namespace('panier');?>
	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Formulaire de livraison des commandes encours</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addmembre">
  <?php if(isset($sessionmembre->errorlogin) && $sessionmembre->errorlogin!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->errorlogin; $sessionmembre->errorlogin = ""; ?>
    </div>
  <?php }?>

  <blockquote>Veuillez saisir le code de livraison dans le formulaire. Merci</blockquote>

<?php if(!isset($_POST['code_livraison2'])){?>
<div class="control-group">
<label class="control-label" for="code_livraison2">Code de livraison *</label>
<div class="controls">
<input type="text" name="code_livraison2" id="code_livraison2" placeholder="Code de livraison" required>
</div>
</div>

<?php }else if(isset($_POST['code_livraison2']) && $_POST['code_livraison2'] != ""){?>



<?php if(count($this->detail_commande)>0){?> 
  <blockquote>Details Commande</blockquote>

<?php 
$commandeM = new Application_Model_EuCommandeMapper();
$commande = new Application_Model_EuCommande();
$commandeM->find($this->commande->code_commande, $commande);
/**/?>
<div>Date Commande : <?php echo ($commande->date_commande); ?></div>
<div>Montant Commande : <?php echo ($commande->montant_commande); ?></div>
<div>Telephone Commande : <?php echo ($commande->tel_acheteur); ?></div>
<div>Quartier Commande : <?php echo ($commande->quartier_acheteur); ?></div>
<div>Ville Commande : <?php echo ($commande->ville_acheteur); ?></div>
<div>Adresse de livraison : <?php echo ($commande->adresse_livraison); ?></div>
<br />

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  
							  
							  <tr>
								  <th>Date</th>
								  <th>Code Membre</th>
								  <th>Nom & prenom(s) / Raison sociale</th>
								  <th>Désignation</th>
								  <th>Quantité</th>
								  <th>Prix</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->detail_commande as $entry): ?>
    <tr>
    <?php 
$commandeM = new Application_Model_EuCommandeMapper();
$commande = new Application_Model_EuCommande();
$commandeM->find($entry->code_commande, $commande);
/**/?>
      <td><?php echo ($commande->date_commande); ?></td>
      <td><?php echo $commande->code_membre_acheteur; ?></td>
      <td><?php if(substr($commande->code_membre_acheteur, -1) == "P"){
$membreM = new Application_Model_EuMembreMapper();
$membre = new Application_Model_EuMembre();
$membreM->find($commande->code_membre_acheteur, $membre);
?><?php echo ($membre->nom_membre." ".$membre->prenom_membre); ?>
	<?php }else{
$membremoraleM = new Application_Model_EuMembreMoraleMapper();
$membremorale = new Application_Model_EuMembreMorale();
$membremoraleM->find($commande->code_membre_acheteur, $membremorale);
?><?php echo ($membremorale->raison_sociale); } ?>
</td>
      <td><?php echo ($entry->designation); ?></td>
      <td><div align="right"><?php echo number_format($entry->qte, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format($entry->prix_unitaire, 0, ',', ' '); ?></div></td>
      <td><?php if($entry->livrer == 1){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Déja Livré</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Non Livré</a>&nbsp;
<?php }?></td>
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun article acheté 
</div>
<?php }?>











<div class="control-group">
<label class="control-label" for="code_livraison">Code de livraison *</label>
<div class="controls">
<input type="text" name="code_livraison" id="code_livraison" placeholder="Code de livraison" required>
</div>
</div>
<?php }?>


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<!--<button type="reset" class="btn">Annuler</button>-->
<button type="submit" class="btn btn-success">Livrer</button>
</div>



</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>
