<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modifier  une lettre d'annulation</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="editeli">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
  
    

<div class="control-group">
<label class="control-label" for="id_eli">ELI * </label>
<div class="controls">
<?php 
$eli_m = new Application_Model_EuEliMapper();
$eli = $eli_m->fetchAll();
if(count($eli) > 0){?>
<select name="id_eli" id="id_eli" required >
<option value="">Choisir l'ELI' </option>
<?php foreach ($eli as $value) { ?>
<option value="<?php echo $value->id_eli; ?>" <?php if($this->lettre_annulation->id_eli == $value->id_eli){?> selected="selected"<?php }?>><?php echo $value->libelle_eli;?> - <?php echo $value->numero_eli;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>



<div class="control-group">
<label class="control-label" for="code_membre">Code Membre *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="code_membre" id="code_membre" placeholder="Code Membre" value="<?php echo $this->lettre_annulation->code_membre;?>" required>
</div>
</div>


    
<div class="control-group">
<label class="control-label" for="libelle">Libellé  de la lettre *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="libelle" id="libelle" placeholder="Libellé de la lettre" value="<?php echo $this->lettre_annulation->libelle;?>" required>
</div>
</div>

<div class="control-group">
<label class="control-label" for="description">Description * </label>
<div class="controls">
<textarea name="description" id="description" placeholder="Description" class="ckeditor" required><?php echo $this->lettre_annulation->description;?></textarea>
</div>
</div>
   
<div class="control-group">
<label class="control-label" for="fichier">Document  de la lettre *</label>
<div class="controls">
<input name="fichier" type="file" id="fichier" class="input-xxlarge"   />
</div>
</div>

   







<div class="form-actions">
<input name="fichierold" type="hidden" id="fichierold" value="<?php echo $this->lettre_annulation->fichier; ?>" />  
<input name="id_lettre_relance" type="hidden" id="id_lettre_relance" value="<?php echo $this->lettre_annulation->id_lettre_relance; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier  la lettre d'annulation</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








