<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste des  lettres d'annulation</p></blockquote>
<?php //echo $sessionmembre->id_canton;?> 
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>ELI</th>
								  <th>Libelle</th>
                  <!--<th>Utilisateur</th>
								  <th>Validation</th>-->
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->datecreation; ?></td>
<?php 
        $eli = new Application_Model_EuEli();
        $eliM = new Application_Model_EuEliMapper();
        $eliM->find($entry->id_eli, $eli);
?>
      <td><?php echo $eli->libelle_eli; ?> - <?php echo $eli->numero_eli; ?></td>
      <td><?php echo $entry->libelle; ?></td>
      <?php /*?><?php 
        $utilisateur = new Application_Model_EuUtilisateur();
        $utilisateurM = new Application_Model_EuUtilisateurMapper();
        $utilisateurM->find($entry->id_utilisateur, $utilisateur);
?>
      <td><?php echo $utilisateur->nom_utilisateur; ?> <?php echo $utilisateur->prenom_utilisateur; ?></td>
      <td><div align="center">
<?php 
        $a_formulaireM = new Application_Model_EuAttributionUserGroupFormulaireMapper();
        $a_formulaire = $a_formulaireM->fetchAllByNom("listlettreannulationadmin");

        $formulaire = new Application_Model_EuFormulaire();
        $formulaireM = new Application_Model_EuFormulaireMapper();
        $formulaireM->find($entry->formulaire_id, $formulaire);

        $attribution_user_group_formulaireM = new Application_Model_EuAttributionUserGroupFormulaireMapper();
        $attribution_user_group_formulaire2 = $attribution_user_group_formulaireM->fetchAllByFormulaireDepart($formulaire->formulaire_id, $sessionmembre->code_groupe);
$attribution_user_group_formulaire = $attribution_user_group_formulaire2[0];

        $attribution_user_group_formulaire1M = new Application_Model_EuAttributionUserGroupFormulaireMapper();
        $attribution_user_group_formulaire12 = $attribution_user_group_formulaire1M->fetchAllByFormulaireDepartAutre($formulaire->formulaire_id, $sessionmembre->code_groupe, $sessionmembre->code_groupe);
$attribution_user_group_formulaire1 = $attribution_user_group_formulaire12[0];
?>

<?php if(count($attribution_user_group_formulaire2[0]) > 0){?>
<?php if($entry->valid == $attribution_user_group_formulaire2[0]->code_groupe_depart){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/lettrerelance/validlettreannulationadmin/id/<?php echo $entry->id_lettre_relance; ?>/valid/<?php echo $attribution_user_group_formulaire2[0]->code_groupe_depart; ?>"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/lettrerelance/validlettreannulationadmin/id/<?php echo $entry->id_lettre_relance; ?>/valid/<?php echo $attribution_user_group_formulaire2[0]->code_groupe_depart; ?>"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
<?php }?>
<?php if(count($attribution_user_group_formulaire12[0]) > 0){?>
<?php if($entry->valid == $attribution_user_group_formulaire12[0]->code_groupe_depart){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
<?php }?>

			</div></td><?php */?>
      <td><div align="center"><?php /*?>
<?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/lettrerelance/etatlettreannulationadmin/id/<?php echo $entry->id_lettre_relance; ?>/etat/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/lettrerelance/etatlettreannulationadmin/id/<?php echo $entry->id_lettre_relance; ?>/etat/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>


			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/lettrerelance/editlettreannulationadmin/id/<?php echo $entry->id_lettre_relance; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<?php */?>
     
      <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/lettrerelance/detaillettreannulation/id/<?php echo $entry->id_lettre_relance; ?>"><i class="icon-edit icon-white"></i>  Details</a>&nbsp;

      </div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune lettre d'annulation  enregistrée 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








