<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Attribution de procedure</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addposte">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    


<div class="control-group">
<label class="control-label" for="centrale_id">Centrale *</label>
<div class="controls">
<?php 
$centrale = new Application_Model_EuCentraleMapper();
$entries = $centrale->fetchAll();
if(count($entries) > 0){?>
<select id="centrale_id" name="centrale_id" required>
  <option value="">Choisir la centrale</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->centrale_id; ?>"><?php echo $value->centrale_libelle; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
    

<div class="control-group">
<label class="control-label" for="code_groupe">Code groupe *</label>
<div class="controls">
<?php 
$liste = array("detentrice_technopole","surveillance_filiere","executante_acnev","agrement_technopole","agrement_filiere","agrement_acnev","cm","secretariat","gerant","comite_selection","comite_evaluation");
$t_code_groupe = new Application_Model_DbTable_EuUserGroup();
$select = $t_code_groupe->select();
$select->where("code_groupe IN (?) ", $liste);
$entries = $t_code_groupe->fetchAll($select);
if(count($entries) > 0){?>
<select id="code_groupe" name="code_groupe" required>
  <option value="">Choisir le groupe</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->code_groupe; ?>"><?php echo $value->libelle_groupe; ?> - <?php echo $value->code_groupe; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
  

<div class="control-group">
<label class="control-label" for="procedure_id">Procedure *</label>
<div class="controls">
<?php 
$procedure = new Application_Model_EuProcedureMapper();
$entries = $procedure->fetchAll();
if(count($entries) > 0){?>
<select id="procedure_id" name="procedure_id" required>
  <option value="">Choisir la procedure</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->procedure_id; ?>"><?php echo $value->procedure_libelle; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
    

<div class="control-group">
<label class="control-label" for="formulaire_id">Formulaire *</label>
<div class="controls">
<?php 
$formulaire = new Application_Model_EuFormulaireMapper();
$entries = $formulaire->fetchAll();
if(count($entries) > 0){?>
<select id="formulaire_id" name="formulaire_id" required>
  <option value="">Choisir la formulaire</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->formulaire_id; ?>"><?php echo $value->formulaire_libelle; ?> - <?php echo $value->formulaire_nom; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>




    
<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Attribuer la procedure</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








