<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?> 
	<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modification du formulaire </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addformulaire">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
  

    
    
<div class="control-group">
<label class="control-label" for="formulaire_procedure">Type *</label>
<div class="controls">
<?php 
$procedure = new Application_Model_EuProcedureMapper();
$entries = $procedure->fetchAll();
if(count($entries) > 0){?>
<select id="formulaire_procedure" name="formulaire_procedure" required>
  <option value="">Choisir la procedure</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->procedure_id; ?>" <?php if($this->formulaire->formulaire_procedure == $value->procedure_id){?> selected="selected"<?php }?>><?php echo $value->procedure_libelle; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
        

<div class="control-group">
<label class="control-label" for="formulaire_libelle">Libellé du formulaire *</label>
<div class="controls">
<input type="text" name="formulaire_libelle" id="formulaire_libelle" placeholder="Libellé du formulaire" class="input-xxlarge" value="<?php echo $this->formulaire->formulaire_libelle; ?>" required />
</div>
</div>

    
<div class="control-group">
<label class="control-label" for="formulaire_nom">Nom du formulaire *</label>
<div class="controls">
<input type="text" name="formulaire_nom" id="formulaire_nom" placeholder="Nom du formulaire" class="input-xxlarge" value="<?php echo $this->formulaire->formulaire_nom; ?>" required />
</div>
</div>


 <div class="control-group">
<label class="control-label" for="formulaire_description">Description du formulaire *</label>
<div class="controls">
<textarea name="formulaire_description" id="formulaire_description" placeholder="Description du formulaire" class="ckeditor" required><?php echo $this->formulaire->formulaire_description; ?></textarea>
</div>
</div>
    
   
    
<div class="control-group">
<label class="control-label" for="formulaire_url">Url du formulaire </label>
<div class="controls">
<input name="formulaire_url" type="file" id="formulaire_url" class="input-xxlarge" />  
</div>
</div>
    



<div class="form-actions">
<input name="formulaire_id" type="hidden" id="formulaire_id" value="<?php echo $this->formulaire->formulaire_id; ?>" />  
<input name="formulaire_url_old" type="hidden" id="formulaire_url_old" value="<?php echo $this->formulaire->formulaire_url; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier le formulaire </button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








