<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?> 
	<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modification de la procedure </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addprocedure">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
  

    
    
<div class="control-group">
<label class="control-label" for="procedure_type">Type *</label>
<div class="controls">
<?php 
$procedure_type = new Application_Model_EuProcedureTypeMapper();
$entries = $procedure_type->fetchAll();
if(count($entries) > 0){?>
<select id="procedure_type" name="procedure_type" required>
  <option value="">Choisir le type</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->procedure_type_id; ?>" <?php if($this->procedure->procedure_type == $value->procedure_type_id){?> selected="selected"<?php }?>><?php echo $value->procedure_type_libelle; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
        

<div class="control-group">
<label class="control-label" for="procedure_libelle">Libellé de la procedure *</label>
<div class="controls">
<input type="text" name="procedure_libelle" id="procedure_libelle" placeholder="Libellé de la procedure" class="input-xxlarge" value="<?php echo $this->procedure->procedure_libelle; ?>" required />
</div>
</div>

    
<div class="control-group">
<label class="control-label" for="procedure_nom">Nom de la procedure *</label>
<div class="controls">
<input type="text" name="procedure_nom" id="procedure_nom" placeholder="Nom de la procedure" class="input-xxlarge" value="<?php echo $this->procedure->procedure_nom; ?>" required />
</div>
</div>


 <div class="control-group">
<label class="control-label" for="procedure_description">Description de la procedure *</label>
<div class="controls">
<textarea name="procedure_description" id="procedure_description" placeholder="Description de la procedure" class="ckeditor" required><?php echo $this->procedure->procedure_description; ?></textarea>
</div>
</div>
    
   
    
<div class="control-group">
<label class="control-label" for="procedure_url">Url de la procedure </label>
<div class="controls">
<input name="procedure_url" type="file" id="procedure_url" class="input-xxlarge" />  
</div>
</div>
    



<div class="form-actions">
<input name="procedure_id" type="hidden" id="procedure_id" value="<?php echo $this->procedure->procedure_id; ?>" />  
<input name="procedure_url_old" type="hidden" id="procedure_url_old" value="<?php echo $this->procedure->procedure_url; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier de la procedure </button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








