<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modification Attribution Niveau de validation</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addposte">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    

<div class="control-group">
<label class="control-label" for="formulaire_id">Formulaire *</label>
<div class="controls">
<?php 
$formulaire = new Application_Model_EuFormulaireMapper();
$entries = $formulaire->fetchAll();
if(count($entries) > 0){?>
<select id="formulaire_id" name="formulaire_id" required>
  <option value="">Choisir la formulaire</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->formulaire_id; ?>" <?php if($this->attribution_user_group_formulaire->formulaire_id == $value->formulaire_id){?> selected="selected"<?php }?>><?php echo $value->formulaire_libelle; ?> - <?php echo $value->formulaire_nom; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>


<div class="control-group">
<label class="control-label" for="code_groupe_depart">Code groupe départ *</label>
<div class="controls">
<?php 
$liste = array("detentrice_technopole","surveillance_filiere","executante_acnev","agrement_technopole","agrement_filiere","agrement_acnev","cm","secretariat","gerant","comite_selection","comite_evaluation","comite_reception");
$t_code_groupe_depart = new Application_Model_DbTable_EuUserGroup();
$select = $t_code_groupe_depart->select();
$select->where("code_groupe IN (?) ", $liste);
$entries = $t_code_groupe_depart->fetchAll($select);
if(count($entries) > 0){?>
<select id="code_groupe_depart" name="code_groupe_depart" required>
  <option value="">Choisir le groupe départ</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->code_groupe; ?>" <?php if($this->attribution_user_group_formulaire->code_groupe_depart == $value->code_groupe){?> selected="selected"<?php }?>><?php echo $value->libelle_groupe; ?> - <?php echo $value->code_groupe; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
    

<div class="control-group">
<label class="control-label" for="code_groupe_arrivee">Code groupe d'arrivée *</label>
<div class="controls">
<?php 
$liste = array("detentrice_technopole","surveillance_filiere","executante_acnev","agrement_technopole","agrement_filiere","agrement_acnev","cm","secretariat","gerant","comite_selection","comite_evaluation","comite_reception");
$t_code_groupe_arrivee = new Application_Model_DbTable_EuUserGroup();
$select = $t_code_groupe_arrivee->select();
$select->where("code_groupe IN (?) ", $liste);
$entries = $t_code_groupe_arrivee->fetchAll($select);
if(count($entries) > 0){?>
<select id="code_groupe_arrivee" name="code_groupe_arrivee" required>
  <option value="">Choisir le groupe d'arrivée</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->code_groupe; ?>" <?php if($this->attribution_user_group_formulaire->code_groupe_arrivee == $value->code_groupe){?> selected="selected"<?php }?>><?php echo $value->libelle_groupe; ?> - <?php echo $value->code_groupe; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
  

<div class="control-group">
<label class="control-label" for="code_groupe_autre">Code groupe Autre </label>
<div class="controls">
<?php 
$liste = array("detentrice_technopole","surveillance_filiere","executante_acnev","agrement_technopole","agrement_filiere","agrement_acnev","cm","secretariat","gerant","comite_selection","comite_evaluation","comite_reception");
$t_code_groupe_autre = new Application_Model_DbTable_EuUserGroup();
$select = $t_code_groupe_autre->select();
$select->where("code_groupe IN (?) ", $liste);
$entries = $t_code_groupe_autre->fetchAll($select);
if(count($entries) > 0){?>
<select id="code_groupe_autre" name="code_groupe_autre" >
  <option value="">Choisir le groupe Autre</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->code_groupe; ?>" <?php if($this->attribution_user_group_formulaire->code_groupe_autre == $value->code_groupe){?> selected="selected"<?php }?>><?php echo $value->libelle_groupe; ?> - <?php echo $value->code_groupe; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
    




    
<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<input name="attribution_user_group_formulaire_id" type="hidden" id="attribution_user_group_formulaire_id" value="<?php echo $this->attribution_user_group_formulaire->attribution_user_group_formulaire_id; ?>" />  
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Attribuer le niveau de validation</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








