<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?> 

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des formulaires </p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Procedure</th>
								  <th>Libellé</th>
								  <th>Nom</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php $procedureM = new Application_Model_EuProcedureMapper();
$procedure = new Application_Model_EuProcedure();
$procedureM->find($entry->formulaire_procedure, $procedure);
?><?php echo ($procedure->procedure_libelle); ?></td>
      <td><?php echo ($entry->formulaire_libelle); ?></td>
      <td><?php echo ($entry->formulaire_nom); ?></td>
      <td><div align="center"><?php if($entry->publier == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/attribution/publierformulaire/id/<?php echo $entry->formulaire_id; ?>/publier/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/attribution/publierformulaire/id/<?php echo $entry->formulaire_id; ?>/publier/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
	  
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/attribution/detailsformulaire/id/<?php echo $entry->formulaire_id; ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;

			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/attribution/editformulaire/id/<?php echo $entry->formulaire_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/attribution/suppformulaire/id/<?php echo $entry->formulaire_id; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune formulaire enrégistrée 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








