<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des attributions des niveaux de validation</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>#</th>
								  <th>Formulaire</th>
								  <th>Code Groupe Départ</th>
								  <th>Code Groupe Arrivée</th>
								  <th>Code Groupe Autre</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->attribution_user_group_formulaire_id); ?></td>
      <td><?php $formulaireM = new Application_Model_EuFormulaireMapper();
$formulaire = new Application_Model_EuFormulaire();
$formulaireM->find($entry->formulaire_id, $formulaire);
?><?php echo ($formulaire->formulaire_libelle); ?></td>
      <td><?php if($entry->code_groupe_depart != ""){
      	$usergroupM = new Application_Model_EuUserGroupMapper();
$usergroup = new Application_Model_EuUserGroup();
$usergroupM->find($entry->code_groupe_depart, $usergroup);
?><?php echo ($usergroup->libelle_groupe);} ?></td>
      <td><?php if($entry->code_groupe_arrivee != ""){
      	$usergroupM = new Application_Model_EuUserGroupMapper();
$usergroup = new Application_Model_EuUserGroup();
$usergroupM->find($entry->code_groupe_arrivee, $usergroup);
?><?php echo ($usergroup->libelle_groupe);} ?></td>
      <td><?php if($entry->code_groupe_autre != ""){
      	$usergroupM = new Application_Model_EuUserGroupMapper();
$usergroup = new Application_Model_EuUserGroup();
$usergroupM->find($entry->code_groupe_autre, $usergroup);
?><?php echo ($usergroup->libelle_groupe);} ?></td>
      <td><div align="center">
			<?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/attribution/etatattributionusergroup/id/<?php echo $entry->attribution_user_group_formulaire_id; ?>/etat/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/attribution/etatattributionusergroup/id/<?php echo $entry->attribution_user_group_formulaire_id; ?>/etat/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/attribution/editattributionusergroup/id/<?php echo $entry->attribution_user_group_formulaire_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;
</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune attribution des niveaux de validation enrégistrée 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








