<div id="view-content" class="ui-widget">
    <div class="ui-widget-header ui-corner-top" style="height: 25px;padding-bottom: 7px; padding-left: 7px;">
        <h3>Domiciliation des MF11000</h3>
    </div>
    <div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <form action="/eu-domiciliation-mf/domicilier" name="fm_domicil" method="POST" id="fm_domicil">
            <input type="hidden" name="cpteur" id="cpteur" value="1"/>
            <div>
                <fieldset>
                    <legend>Informations sur la domiciliation</legend>
                    <table>
                        <tr>
                            <td>Montant à domicilier *</td><td><input name="mt_domici" id="mt_domici" class="validate[required number]" value="<?php echo $this->mt_domici ?>" size="25"/></td>          
                            <td>Membre bénéficiaire *</td><td><input class="validate[required]" type="text" id="code_membre" name="code_membre" value="<?php echo $this->code_membre; ?>" size="30"/></td>
                        </tr>
                        <tr>
                            <td>Nom Membre</td><td><input class="" type="text" id="nom_membre" name="nom_membre" value="<?php echo $this->nom_membre; ?>" readonly size="25"/></td>
                            <td>Prénoms</td><td><input class="" type="text" id="prenom_membre" name="prenom_membre" value="<?php echo $this->prenom_membre; ?>" readonly size="35"/></td>
                        </tr>
                    </table>   
                    <table border="1" style="margin: 5px;" id="tab_salaire">
                        <thead>
                            <tr style="text-align: left;">
                                <th style="width: 170px;">Code membre</th><th style="width: 250px;">Nom</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><input id="num_membre1" type="text" name="num_membre1" value="" required="true" style="width: 170px;"/></td>
                                <td><input id="nom1" type="text" name="nom1" value="" style="width: 260px;" readonly="readonly"/></td>
                            </tr>
                        </tbody>
                    </table>
                    <table>
                        <div align="center">
                            <input id="add" type="button" value="Ajouter" onclick="addRow('tab_salaire')"/>
                            <input id="remove" type="button" value="Supprimer" onclick="deleteRow('tab_salaire')"/> 
                            <input type='button' value="Afficher" name="afficher" id="afficher" />
                            <input type="reset" value="Rafraichir" name="refresh" id="refresh"   />
                        </div>
                    </table>
                </fieldset>
            </div>
            <table id="tbl-credit"></table>
            <div id="pg-credit"></div>
            <br>
            <div style="margin-left: 150px">
                <input type="button" value="Valider" name="valider" id="valider"   />
                <input id="t_annuler" type="button" value="Annuler" />
            </div>
        </form>
    </div>  
</div>
<script type="text/javascript">
    $("#tbl-credit").jqGrid({
        url:'/eu-domiciliation-mf/credits?lignes=',
        datatype: "json",
        mtype: 'GET',
        colNames: ['Id_mf11000','Numéro bon','Code membre','Montant apporté','Quota en %','Montant domicilié','Répartitions','Nb_init'],
        height: '100%', width: 816,
        colModel: [
            {name: 'id_mf', index: 'id_mf', width:10, editable: false, align: "left", hidden:true},
            {name: 'numbon', index: 'numbon', width:115, editable: false, align: "left"},
            {name: 'code_membre', index: 'code_membre', width:170, sorttype: "int", editable: false, align: "left"},
            {name: 'mont_apport', index: 'mont_apport', width:150, editable: false, align: "right",formatter:'number'},
            {name: 'quota', index: 'quota', width:100, editable: false, align: "right"},  
            {name: 'mont_domi', index: 'mont_domi', width:150, editable: true, align: "right",formatter:'number'},
            {name: 'repartition', index: 'repartition', width:100, editable: true, align: "right"},
            {name: 'nb_init', index: 'nb_init', width:100, editable: true, align: "right", hidden:true},
        ],
        rowNum: 100,
        rowList: [100, 200, 300],
        rownumbers:true,
        pager: '#pg-credit',
        sortname:"numbon",
        viewrecords: true,
        multiselect:true,
        sortorder: "ASC",
        caption:"Liste des apports des membres",
        forceFit : true, 
        cellEdit: true, 
        cellsubmit: 'clientArray'
    });
    $("#tbl-credit").jqGrid('navGrid','#pg-credit',{edit:false,add:false,del:false,search:true});    
        
    $(document).ready(function ()
    {
        $('#refresh').button();
        $('#afficher').button();
        $('#add').button();
        $('#remove').button();
        $('#valider').button();
        $('#t_annuler').button();
        
        $.get("/eu-domiciliation-mf/membre",
        function success(data)
        {
            $('#code_membre').autocomplete({"source": data,
                change: displayItem});
        });

        function displayItem()
        {
            if ($(this).val() !== '')
            {
                $.get(
                '/eu-domiciliation-mf/recupnom2',
                {
                    code_membre: $(this).val()
                },
                function success(data)
                {
                    $("#nom_membre").val(data[0]);
                    $("#prenom_membre").val(data[1]);
                });
            }
        }
        
        $('#num_membre1').blur(function(e)
        {
            if($(this).val() != '')
            {
                $.get(
                '/eu-domiciliation-mf/recupnom',
                {
                    num_membre: $(this).val()
                },
                function success(data)
                {
                    $("#nom1").val(data);
                });
            }
            e.preventDefault();
        }); 
        
        $.get( "/eu-domiciliation-mf/change",
        function success(data)           
        {
            $("input#num_membre1").autocomplete({"source":data});                  
        });
            
        $('#afficher').click(function(){
            var tab=new Array();
            for(var i=1;i<=compteur;i++)
            {
                tab[i-1]=$('#num_membre' + i).val();           
            }
            jQuery("#tbl-credit").jqGrid('setGridParam',{url:"/eu-domiciliation-mf/credits?lignes="+tab}).trigger('reloadGrid');
        });
    })
  
    var compteur = 1;
    function addRow(tableID) {

        var table = document.getElementById(tableID);
        var rowCount = table.rows.length;
        var cpte = rowCount;
        var row = table.insertRow(rowCount);
            
        var cell1 = row.insertCell(0);
        var element0 = document.createElement("input");
        element0.type = "text";
        element0.setAttribute("id","num_membre" + cpte);
        element0.setAttribute("name","num_membre" + cpte); 
        element0.setAttribute("style","width:170px;");
        cell1.appendChild(element0);

        var cell2 = row.insertCell(1);
        var element1 = document.createElement("input");
        element1.type = "text";
        element1.setAttribute("id","nom" + cpte);
        element1.setAttribute("name","nom" + cpte);
        element1.setAttribute("style","width:260px;");
        element1.setAttribute("readonly","true");
        cell2.appendChild(element1);
            
        $.get( "/eu-domiciliation-mf/change",
        function success(data)
        {
            $("#num_membre"+ cpte).autocomplete({"source":data});
        });
            
        $('#num_membre' + cpte).blur(function(e)
        {
            if($(this).val() != '')
            {
                $.get(
                '/eu-domiciliation-mf/recupnom',
                {
                    num_membre: $(this).val()
                },
                function success(data)
                {
                    $("#nom"+cpte).val(data);
                });
            }
            e.preventDefault();
        });
            
        compteur = compteur + 1;
        document.getElementById("cpteur").setAttribute('value',compteur);
    }

    function deleteRow(tableID) {
        try {
            var table = document.getElementById(tableID);
            var rowCount = table.rows.length - 1;
            if(rowCount>1){
                table.deleteRow(rowCount);
            }
            compteur = compteur - 1;
            document.getElementById("cpteur").setAttribute('value',compteur);
        }catch(e) {
            alert(e);
        }
    }
        
    $('#valider').click(
    function(){
        var sel;
        sel = jQuery("#tbl-credit").jqGrid('getGridParam','selarrrow');
        var tab=new Array();  
        var rowsel;
        rowsel = jQuery("#tbl-credit").jqGrid('getGridParam','selrow');
        for(var i=0; i<sel.length; i++) {
            tab[i]=jQuery("#tbl-credit").jqGrid('getRowData',sel[i]);   
        };
        if($('#mt_domici').val()==''){
            alert('Préciser le montant à domicilier');
        }else if($('#code_membre').val()==''){
            alert('Préciser le code membre du bénéficiaire');
        }
        else{
            if(rowsel)
            {
                $.get('/eu-domiciliation-mf/create?benef='+$('#code_membre').val()+'&mt_domici='+$('#mt_domici').val(),{
                    lignes:tab
                },
                function success(data){
                    var tab=new Array();
                    for(var i=1;i<=10;i++)
                    {
                        tab[i-1]=$('#num_membre' + i).val();           
                    }
                    if(data == 'good'){
                        jQuery("#tbl-credit").jqGrid('setGridParam',{url:"/eu-domiciliation-mf/credits?lignes="+tab}).trigger('reloadGrid');
                        alert('Opération effectuée avec succes');
                    }
                    else if(data == "err_domici"){
                        alert("Le cumul des répartitions en fin de période est inférieur au montant à domicilier");
                    }
                    else if(data == 'bad'){
                        alert("Echec de l'opération");
                    }
                });
            }else{
                alert('Aucune ligne de crédit sélectionnée');
            }                
        }

    });
</script>    