<div id="view-content" class="ui-widget" title='Gestion des représentations' style="font-size: 10px;min-height: 520px;">
     <form id="representation_form" method="Post" action="/eu-representation/representer">
	       <fieldset>
		    <legend>Représentation</legend>
            <input type="hidden" name="cpteur" id="cpteur" value="1"/>
		   <table id="tab_fact" style="margin: 5px;">
               <tr>
				   <td><label>Code membre représentant * :</label></td>
                   <td><input id="code_rep" type="text" name="code_rep"  required="true"  size="30"/></td>
				   <td><label for="raison_soc">Nom & Prénom *:</label></td>
                  <td>
                    <input class="validate[required]" readonly  type="text" id="nom_rep" name="nom_rep"  size="40"/>
                  </td>   
               </tr>   
            </table>
		    </fieldset>
		   
		    <table align="center">
            <tr>
                <td></td>
                <td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="Réinitialiser"/></td>
            </tr>
            </table>
     </form>
</div>

<script type="text/javascript">
   $(document).ready(function () {
	    $("#representation_form").validationEngine();
        $('#view-content').puipanel();
        $('fieldset').puifieldset();
	  
	    $.get( "/eu-representation/membrephys",
            function success(data) {
            $("#code_rep").autocomplete({"source":data});
        });
							
							
		$('#code_rep').blur(function(e) {
            if($(this).val() !== '') {
                $.get(
                  '/eu-representation/recupnom',{
                  num_membre: $(this).val()
                },
                function success(data) {
                    $("#nom_rep").val(data);
                });
        }
        e.preventDefault();
        }); 
	   
	    $('form#representation_form').submit(function(e) {
        $.ajax({
          url: $('form').attr("action"),
          data: $('form').serialize(),
          type: 'post',
          success: processServerResponse
        });
        e.preventDefault();
        });
		
		function processServerResponse(data) {
            if(data === 'bad'){
              alert('Un membre personne physique  ne peut appartenir  plusieurs fois à une même maison !!!');
            }
		    else if(data === 'verifiertitre'){
		      alert('Ce membre personne morale a déjà un representant');
		    }
		    else if(data === 'echec'){
		      alert('Echec de l\'opération, vérifier votre saisie');
		    }
            else if(data === 'good') {
              alert('Opération effectuée avec succès');
              $(location).attr("href","/eu-representation/index");
            }
            else {
                $('#message').html(data);
            }
        };   
    });
</script>