<div id="view-content" class="ui-widget" title='Gestion des représentations' style="font-size: 10px;min-height: 520px;">
     <form id="representation_form" method="Post" action="/eu-maison/representer">
           <input type="hidden" name="cpteur" id="cpteur" value="1"/>
		   <table id="tab_fact" style="margin: 5px;">
               <tr>
                   <td><label>Code membre maison * :</label></td>
                   <td><input id="code_memb" type="text" name="code_memb"  required="true"  size="30"/></td>
               </tr>
               <tr>
                  <td><label for="raison_soc">Raison Sociale *:</label></td>
                  <td>
                    <input class="validate[required]" readonly  type="text" id="raison_soc" name="raison_soc" value="<?php echo $this->raison_soc; ?>" size="40"/>
                  </td>
               </tr>   
           </table>
		   <fieldset>
           <table border="1" style="margin: 5px 5px 5px 5px;" id="tab_representation">
		          <thead>
		                 <tr style="text-align: left;">
						     <th>Code membre *</th><th>Nom & Prénom *</th><th>Titre</th>
						 </tr>
                  </thead>
				  <tbody>
						 <tr>
				               <td><input type="text" id="code_res1" name="code_res1" required="true"  size="30"/></td>
                               <td><input type="text" id="nom_res1" name="nom_res1" required="true"   size="30"/></td>
							   <td><input id="titre1" type="text" name="titre1"   value="" size="30"/></td>
							   
					     </tr>
				  </tbody>
           </table>
		   </fieldset>
		   <table align="center">
            <tr>
                <td>
				   <input id="add_resident" type="button" value="Ajouter" onclick="addRow('tab_representation')"/>
				   <input id="del_resident" type="button" value="Supprimer" onclick="deleteRow('tab_representation')"/>
				</td>
                <td></td>
                <td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="Réinitialiser"/></td>
            </tr>
        </table>
     </form>
</div>

<script type="text/javascript">
   $(document).ready(function () {
	  $("#representation_form").validationEngine();
      $('#view-content').puipanel();
      $('fieldset').puifieldset();
	  
	  $.get( "/eu-maison/membremoral",
        function success(data)
        {
            $("#code_memb").autocomplete({"source":data,
                change: displaymoral});
        });
            
        function displaymoral() {
            if ($(this).val() !== '')
            {
                $.get(
                '/eu-maison/recupnom1',
                {
                    num_membre: $(this).val()
                },
                function success(data)
                {
                    $("#raison_soc").val(data[2]);
                });
            }
        }
	  
	  
	  
	  $.get( "/eu-maison/membrephys",
            function success(data) {
               $("#code_res1").autocomplete({"source":data});
      });
	  
	  $('#code_res1').blur(function(e) {
         if($(this).val() !== '') {
         $.get(
              '/eu-maison/recupnom',{
              num_membre: $(this).val()
         },
          function success(data) {
            $("#nom_res1").val(data);
          });
         }
         e.preventDefault();
       }); 
	   
	   $('form#representation_form').submit(function(e) {
        $.ajax({
          url: $('form').attr("action"),
          data: $('form').serialize(),
          type: 'post',
          success: processServerResponse
        });
        e.preventDefault();
        });
		
		function processServerResponse(data) {
           if(data === 'bad'){
              alert('Un membre personne physique  ne peut appartenir  plusieurs fois à une même maison !!!');
           }
		   else if(data === 'verifiertitre'){
		      alert('Ce membre personne morale a déjà un representant');
		   }
		   else if(data === 'echec'){
		      alert('Echec de l\'opération, vérifier votre saisie');
		   }
           else if(data === 'good') {
              alert('Opération effectuée avec succès');
              $(location).attr("href","/eu-maison/representation");
           }
           else {
                $('#message').html(data);
           }
    }; 
		
	   
	   
	   
	    
   });
   
   var compteur = 1;
	   function addRow(tableID) {
	       var table = document.getElementById(tableID);
           var rowCount = table.rows.length;
           var cpte = rowCount;
           var row = table.insertRow(rowCount);
		   var cell1 = row.insertCell(0);
           var element0 = document.createElement("input");
           element0.type = "text";
		   element0.setAttribute("required", "true");
           element0.setAttribute("id", "code_res" + cpte);
           element0.setAttribute("name", "code_res" + cpte);
           element0.setAttribute("size", "30");
           cell1.appendChild(element0);
		   $('#code_res'+ cpte).puiinputtext();
		   
		   var cell2 = row.insertCell(1);
           var element1 = document.createElement("input");
           element1.type = "text";
	       element1.setAttribute("required", "true");
           element1.setAttribute("id", "nom_res" + cpte);
           element1.setAttribute("name", "nom_res" + cpte);
           element1.setAttribute("size", "30");
           element1.setAttribute("readonly", "true");
           cell2.appendChild(element1);
		   $('#nom_res'+ cpte).puiinputtext();
		   
		   var cell3 = row.insertCell(2);
           var element2 = document.createElement("input");
           element2.type = "text";
	       //element2.setAttribute("required", "true");
           element2.setAttribute("id", "titre" + cpte);
           element2.setAttribute("name", "titre" + cpte);
           element2.setAttribute("size", "30");
           cell3.appendChild(element2);
		   $('#titre'+ cpte).puiinputtext();
		   
		   $.get( "/eu-maison/membrephys",
             function success(data) {
             $("#code_res"+ cpte).autocomplete({"source":data});
           });
		   
		   $('#code_res'+ cpte).blur(function(e) {
            if($(this).val() !== '') {
              $.get(
                    '/eu-maison/recupnom',{
                    num_membre: $(this).val()
                },
                function success(data) {
                    $("#nom_res"+ cpte).val(data);
                });
            }
            e.preventDefault();
            });
			compteur = compteur + 1;
            document.getElementById("cpteur").setAttribute('value', compteur); 
	   }
	   
	   function deleteRow(tableID) {
           try {
               var table = document.getElementById(tableID);
               var rowCount = table.rows.length - 1;
               if (rowCount > 1) {
                  table.deleteRow(rowCount);
                  compteur = compteur - 1;
                  document.getElementById("cpteur").setAttribute('value', compteur);
               }
           } catch(e) {
                alert(e);
            }
      }
   
   
   
       

</script>