<br /><br />
<div id="view-content">
    <p>View script for controller <b>Compte</b> and script/action name <b>delete</b></p>
    <div id="formdiv">
        <h1>Supprimer un compte</h1>
        <p>Utilisez ce formulaire pour confirmer la suppression d'un compte.</p>

        <?php
        $this->form->setAction($this->url());
// Overwrite the default value used in
// the New Employee form
        $this->form->getElement("submit")->setLabel("Supprimer");

        echo $this->form;
        ?>
    </div>
</div>