<div id="view-content" class="ui-widget">
    <div class="ui-widget-header ui-corner-top" style="height: 25px;padding-bottom: 10px; padding-left: 5px;">
        <h3>Achat du pouvoir d'achat</h3>
    </div>
    <div id="formdiv" class="ui-widget-content ui-corner-bottom">
        <?php
        $this->form->setAction($this->url());
        echo $this->form;
        ?>
    </div>
    <script type="text/javascript">
        $(document).ready(function ()
        {

            $('#montant_op').blur(function(e)
            {
                if($(this).val() != '')
                {
                    if($('#categorie').val() == '' || $('#ressource').val() == ''){
                        alert("Le type du pouvoir d'achat et le produit doivent être renseignés");
                        return false;
                    }
                    $.get(
                    '/eu-placement/calcul',
                    {
                        montant: $(this).val(),cat: $('#categorie').val(),prod : $('#ressource').val()
                    },
                    function success(data)
                    {
                        $('#credit').val(data);
                    });
                }
                e.preventDefault();
            });
            
            $('#credit').change(function(e)
            {
                if($(this).val() != '')
                {
                    if($('#categorie').val() == '' || $('#ressource').val() == ''){
                        alert("Le type du pouvoir d'achat et du produit doivent être renseignés");
                        return false;
                    }
                    $.get(
                    '/eu-placement/calcul',
                    {
                        credit: $(this).val(),cat: $('#categorie').val(),prod : $('#ressource').val(),montant :''
                    },
                    function success(data)
                    {
                        $('#montant_op').val(data);
                    });
                }
                e.preventDefault();
            });
        });
    </script>
</div>