<div id="view-content" title="Recharge du compte de transfert" style="min-height: 520px;padding: 1px;margin: 1px;font-size: 12px;">
    <form id="rec_form" method="post" action="/eu-placement/rechargetr">
        <table id="tab_capa" style="width: 800px; margin-top: 17px;margin-left: auto; margin-right: auto;">
            <tr>
                <td><label>Code SMS </label></td>
                <td><input id="code_sms" name="code_sms" value="<?php echo $this->code_sms; ?>" /></td>
                <td><div id="id_message" style="width: 150px; color:red;"></div></td>
            </tr>
            <tr>
                <td><label for="code_recu">Type de transfert :</label></td>
                <td>
                    <input size="30" type="text" id="code_recu" name="code_recu" value="<?php echo $this->code_recu; ?>" readonly="true"/>
                </td>
            </tr>
            <tr>
                <td><label for="val_nat" style="color: red;">Montant *:</label></td>
                <td>
                    <input size="30" class="validate[required]" type="text" id="mont_rec" name="mont_rec" value="<?php echo $this->mont_capa; ?>" readonly="true"/>
                    <input class="validate[required]" type="text" id="dev_capa" name="dev_capa" value="" readonly="true"></input>
                </td>
            </tr>
            <tr><td></td><td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="Annuler"/></td></tr>
        </table>
    </form>
</div>
<script>
    $(document).ready(function() {
        $(function() {
            $('#view-content').puipanel();
        });
        $("#rec_form").validationEngine();
        $('#val').button();
        $('#reset').button().click(function(e) {
            $(location).attr("href", "/eu-placement/index");
        });

        function displayItem()
        {
            if ($(this).val() !== '')
            {
                $.get(
                        '/eu-placement/recupnom',
                        {
                            num_membre: $(this).val()
                        },
                function success(data)
                {
                    $("#raison_membre").val(data[0]);
                });
            }
        }

        $('#code_sms').blur(function(e)
        {
            if ($(this).val() !== '')
            {
                $.get(
                        '/eu-placement/sms',
                        {
                            code: $(this).val()
                        },
                function success(data)
                {
                    if (data[0] > 0) {
                        $('#mont_rec').val(data[0]);
                        $('#code_recu').val(data[1]);
                        $("#dev_capa").val(data[2]);
                    } else {
                        $("#id_message").html("<label>Ce code est invalide</label>");
                    }

                });
            } else {
                $('#mont_rec').attr('readonly', false);
                $('#mont_capa').val('');
            }
            e.preventDefault();
        });
    });
</script>