<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Ajouter un poste</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addpostepointage">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    
<div class="control-group">
<label class="control-label" for="libelle_poste_pointage">Désignation du poste *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="libelle_poste_pointage" id="libelle_poste_pointage" placeholder="Désignation du poste" required>
</div>
</div>


<div class="control-group">
<label class="control-label" for="taux_horaire">Taux Horaire *</label>
<div class="controls">
<input class="input-xlarge" type="number" name="taux_horaire" id="taux_horaire" placeholder="Taux Horaire" required>
</div>
</div>
    


<div class="form-actions">
<input name="code_membre_employeur" type="hidden" id="code_membre_employeur" value="<?php echo $sessionmembre->code_membre; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter le poste</button>
</div>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








