<?php $sessionmembre = new Zend_Session_Namespace('membre');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste de mes bons d'achat interne BAi</p></blockquote>
  <?php if(isset($sessionmembre->error) && $sessionmembre->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = ""; ?>
    </div>
  <?php }?>
  
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Code</th>
								  <th>Montant</th>
								  <th>Utilisé</th>
								  <th>Solde</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php 
$montant_capa = 0;
$montant_utiliser = 0;
$montant_solde = 0;
 ?>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datejourfr($entry->date_capa." ".$entry->heure_capa); ?></td>
      <td><?php echo ($entry->code_capa); ?></td>
      <td><?php echo ($entry->montant_capa); ?></td>
      <td><?php echo ($entry->montant_utiliser); ?></td>
      <td><?php echo ($entry->montant_solde); ?></td>
      <td><div align="center">
            <?php /*?><a class="btn btn-mini btn-primary" href="<?php echo $this->baseUrl(); ?>/souscriptionbon/bonachatneutrepdf/id/<?php echo $entry->bon_neutre_id; ?>" target="_blank"><i class="icon-cog icon-white"></i>  Imprimer le bon</a><?php */?>&nbsp;
		</div></td>
      
    </tr>
<?php 
$montant_capa += $entry->montant_capa;
$montant_utiliser += $entry->montant_utiliser;
$montant_solde += $entry->montant_solde;
 ?>
<?php endforeach; ?>
</tbody>

<tfooter>
      <th>&nbsp;</th>
      <th align="right">Total : &nbsp;</th>
      <th><?php echo ($montant_capa); ?></th>
      <th><?php echo ($montant_utiliser); ?></th>
      <th><?php echo ($montant_solde); ?></th>
      <th>&nbsp;</th>
</tfooter>
</table>
<?php }else{?>
<div class="alert alert-info">
  Aucun bon d'achat interne trouvé 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








