<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/montantcodesms.js"></script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

  <blockquote><p class="text-info">Achat de Codes SMS chez <?php 
$membremoraleM = new Application_Model_EuMembreMoraleMapper();
$membremorale = new Application_Model_EuMembreMorale();
$membremoraleM->find($this->code_membre_vendeur, $membremorale);
?><strong><?php echo htmlentities($membremorale->raison_sociale); ?></strong></p></blockquote>
<?php //echo $this->code_envoi; ?>
<blockquote>
<p>
  <i class="icon-home"></i> <strong><?php echo htmlentities($membremorale->raison_sociale); ?></strong>
</p>
<small>
  <?php echo htmlentities($membremorale->domaine_activite); ?> - 
  <abbr title="Quartier">Qt:</abbr> <?php echo htmlentities($membremorale->quartier_membre); ?> - <abbr title="Ville">Ville:</abbr> <?php echo htmlentities($membremorale->ville_membre); ?>
</small>
<small>
  <abbr title="Boite Postale">BP:</abbr> <?php echo $membremorale->bp_membre; ?> - 
  <abbr title="Téléphone">Tel:</abbr> <?php echo $membremorale->tel_membre; ?> - 
  <abbr title="Portable">Cel:</abbr> <?php echo $membremorale->portable_membre; ?> - 
  <abbr title="E-mail">E-mail:</abbr> <a href="mailto:<?php echo $membremorale->email_membre; ?>"><?php echo $membremorale->email_membre; ?></a>
</small>
</blockquote>



<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="codesms">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
  <legend>Achat de Code SMS</legend>
<div class="">
  
<div class="span8">
  
  <div class="control-group">
  <label class="control-label" for="type_transfert">Type Code SMS *</label>
  <div class="controls">
  <label for="type_transfertERL" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertERL" value="ERL" required onclick="ouvre_montantcodesms(this.value)">
  Enrôlement</label>

  <label for="type_transfertCAPA" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertCAPA" value="CAPA" required onclick="ouvre_montantcodesms(this.value)">
  Capital d’Achat du Pouvoir d’Achat</label>

  <label for="type_transfertCPS" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertCPS" value="CPS" required onclick="ouvre_montantcodesms(this.value)">
  Carte Privative de Solvabilité</label>

  <label for="type_transfertFKIT" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertFKIT" value="FKIT" required onclick="ouvre_montantcodesms(this.value)">
  Frais de kits</label>

  <label for="type_transfertMF107" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertMF107" value="MF107" required onclick="ouvre_montantcodesms(this.value)">
  Membres Fondateurs 107</label>

  <label for="type_transfertMF11000" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertMF11000" value="MF11000" required onclick="ouvre_montantcodesms(this.value)">
  Membres Fondateurs 11000</label>

  <label for="type_transfertMFL" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertMFL" value="MFL" required onclick="ouvre_montantcodesms(this.value)">
  Membres Fondateurs Licences</label>

  <label for="type_transfertAutres" class="radio">
  <input type="radio" name="type_transfert" id="type_transfertAutres" value="Autres" required onclick="ouvre_montantcodesms(this.value)">
  Autres Frais</label>

  </div>
  </div>
  
  <div class="control-group">
  <label class="control-label" for="mont_transfert">Montant Code SMS *</label>
  <div class="controls" id="niv2">
<div class="input-append">
  <input type="text" name="mont_transfert" id="mont_transfert" placeholder="Montant Code SMS" required>
  <span class="add-on">XOF</span>
</div>
  </div>
  </div>
  
  <div class="control-group">
  <label class="control-label" for="tel_dest">Téléphone portable *</label>
  <div class="controls">
<div class="input-prepend">
  <span class="add-on">Cel.</span>
  <input type="text" name="tel_dest" id="tel_dest" placeholder="Téléphone portable" required>
</div>
  </div>
  </div>
  
</div>
  <div class="span4">
  
  <label class="control-label">Mode de paiement *</label>
  
  <div>
  <label for="paiement1"><img src="<?php echo $this->baseUrl();?>/images/flooz.jpg" class="img-polaroid"></label>
  <input type="radio" name="paiement" id="paiement1" value="flooz" required>
    <br />
  <label for="paiement2"><img src="<?php echo $this->baseUrl();?>/images/visa.jpg" class="img-polaroid"></label>
  <input type="radio" name="paiement" id="paiement2" value="visa" required>
  </div>
    
  </div>

  </div>
  
  <legend></legend>
  

<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Achat de Code SMS</button>
</div>


</form>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








