<style type="text/css">
<!--
p.MsoNoSpacing {
margin:0cm;
margin-bottom:.0001pt;
font-size:11.0pt;
font-family:"Calibri","sans-serif";
}
p.MsoNormal {
margin-top:0cm;
margin-right:0cm;
margin-bottom:10.0pt;
margin-left:0cm;
line-height:115%;
font-size:11.0pt;
font-family:"Calibri","sans-serif";
}
p.Default {
margin:0cm;
margin-bottom:.0001pt;
text-autospace:none;
font-size:12.0pt;
font-family:"Times New Roman","serif";
color:black;
}
p.MsoListParagraphCxSpFirst {
margin-top:0cm;
margin-right:0cm;
margin-bottom:.0001pt;
margin-left:36.0pt;
line-height:115%;
font-size:11.0pt;
font-family:"Calibri","sans-serif";
}
p.MsoListParagraphCxSpLast {
margin-top:0cm;
margin-right:0cm;
margin-bottom:10.0pt;
margin-left:36.0pt;
line-height:115%;
font-size:11.0pt;
font-family:"Calibri","sans-serif";
}
p.MsoListParagraphCxSpMiddle {
margin-top:0cm;
margin-right:0cm;
margin-bottom:.0001pt;
margin-left:36.0pt;
line-height:115%;
font-size:11.0pt;
font-family:"Calibri","sans-serif";
}
p.MsoSubtitle {
margin-top:0cm;
margin-right:0cm;
margin-bottom:10.0pt;
margin-left:0cm;
line-height:115%;
font-size:12.0pt;
font-family:"Cambria","serif";
color:#4F81BD;
letter-spacing:.75pt;
font-style:italic;
}
p.MsoListParagraph {
margin-top:0cm;
margin-right:0cm;
margin-bottom:10.0pt;
margin-left:36.0pt;
line-height:115%;
font-size:11.0pt;
font-family:"Calibri","sans-serif";
}
-->
</style>
<p class="MsoNoSpacing">&nbsp; </p>
<div>
  <h2 align="center" style="text-align:center;"><span style="line-height:115%; font-size:24.0pt; ">CONTRAT</span><span style="font-size:24.0pt; "> D&rsquo;ACHAT DU compte MARCHAND <span style="color:red; ">MCNP</span></span></h2>
</div>
<br clear="all" style="page-break-before:always;" />
</p>
<p class="MsoNormal" style="margin-top:12.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="line-height:115%; font-family:'Cambria','serif'; font-size:14.0pt; ">Ce contrat tient lieu de droit d&rsquo;exploitation du Compte  Marchand <span style="color:red; ">MCNP</span> (Marché de Crédit en Nature  Pérenne) pour toute Personne Physique ou Morale. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le <span style="color:red; ">MCNP</span> est le progiciel conçu pour la gestion de la  solvabilité intégrée des transactions marchandes entre acteurs offreurs et  demandeurs du marché global.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le  Compte Marchand <span style="color:red; ">MCNP</span> est le compte servant pour  toute Personne Physique ou Morale à investir, à travailler contre salaire, à  vendre et à acheter grâce aux unités numériques émises par le <span style="color:red; ">MCNP</span>. Ces unités sont le pouvoir d&rsquo;achat, contrepartie  de la monnaie bancaire dépensée par toute personne physique ou morale acteur du <span style="color:red; ">MCNP</span>. La monnaie bancaire dépensée pour  l&rsquo;acquisition des unités forme le Fonds de Garantie du Financement en Nature,  caution du Marché de Crédit en Nature Pérenne.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="line-height:115%; font-family:'Cambria','serif'; font-size:14.0pt; background:white; ">Les Comptes Marchands  Personnes Morales se regroupent en divisions selon leur produit spécifique. Il  y a les Comptes Marchands qui vendent</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> appelés Opérateurs Economiques  et ceux qui ne vendent pas appelés Opérateurs Socio – Economiques. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">On  distingue deux sortes de divisions :</span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">les&nbsp;  divisions qui administrent le <span style="color:red; ">MCNP</span> et</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">les  divisions qui animent  le <span style="color:red; ">MCNP</span>. </span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les  divisions s&rsquo;organisent en Créneaux Producteurs, Transformateurs et  Distributeurs et regroupent&nbsp;:</span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">la  Filière,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">l&rsquo;ACNEV  (Achat Crédit en Nature Entrepôt et Ventes),</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">la  Technopole,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">les  Grossistes,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">les  Semi – Grossistes et</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">les  Détaillants.</span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le  Compte Marchand Personne Physique est le compte de tout individu sur le <span style="color:red; ">MCNP</span>.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">CONDITIONS  GENERALES </span></u></em></strong></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Peuvent  acheter le Compte Marchand les personnes morales et les personnes physiques qui  adhèrent au mode d&rsquo;entreprendre de L&rsquo;Economie Sociale de Marché Commun (ESMC)/<span style="color:red; ">MCNP</span> dont les conditions sont les suivantes :<strong></strong></span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></em></strong></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Principes</span></em></strong></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Accepter que le Revenu Périodique Garanti p</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">renne pour tous entretenu par le travail productif sur le march</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">est un investissement,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Accepter le mode de payement en nature g</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">r</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; "> par la comptabilit</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; "> int</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">gr</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">e au progiciel </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; "> dont la constitution du  Fonds qui Garantit le Financement en Nature (FGFN) est le gage,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Accepter la solvabilit</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; "> absolue de l&rsquo;Humain par la  monétisation du travail productif dont il est porteur, </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Accepter que l&rsquo;employ</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é <em>soit </em></span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">entrepreneur et que l&rsquo;entrepreneur <em>soit</em> employ</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; "> vis-à-vis des responsabilités de l&rsquo;entreprise qui  bénéficie du crédit productif, Crédit en Nature Convertible Salaire (</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCS</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">) et de l&rsquo;investissement en nature (</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">I</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">) sur le </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Production et consommation respectant la nature,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Solvabilit</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é absolue assurée par la compensation en  nature entre Divisions organisées comme suit&nbsp;: Fili</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">è</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">re, Technopole, ACNEV, Grossistes, Semi-grossistes et Détaillants dans les  créneaux Producteur, Transformateur et Distributeur&nbsp;;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; "> </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Production et consommation respectant l&rsquo;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">conomie d&rsquo;usage qui avorte l&rsquo;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">pargne et la th</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">saurisation,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Production et consommation respectant l&rsquo;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">conomie de service qui implique l&rsquo;achat de services plutôt que  l&rsquo;achat-possession,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Production et consommation respectant l&rsquo;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">conomie circulaire qui implique le renouvelable et le recyclable plutôt  que  l&rsquo;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">conomie lin</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">aire (consommer et jeter),</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Production et consommation respectant l&rsquo;</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">é</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">conomie de circuit court (produire localement) et de cycle court  (formation et apprentissage brefs ou  accélérés) et </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">Respecter les principes,   les conventions ESMC et les normes d&rsquo;utilisation du progiciel </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">.</span></li>
</ul>
<p class="Default" style="margin-left:18.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:windowtext; ">&nbsp;</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "><span style="text-decoration:none; ">&nbsp;</span></span></u></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "><span style="text-decoration:none; ">&nbsp;</span></span></u></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">CONDITIONS <span style="background:white; ">D&rsquo;ACHAT</span> DU compte MARCHAND </span></u></em></strong><em><u><span style="line-height:115%; font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span></u></em><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></u></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; background:white; ">L&rsquo;achat </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">du  Compte Marchand <span style="color:red; ">MCNP</span> est conditionné par le  versement des frais suivants&nbsp;: </span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Frais  de Solvabilité à (montant)&nbsp;: ……………………………………………. FCFA</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Frais de Licence à (montant)&nbsp;:  ……………………………………..………… FCFA</span></li>
</ul>
<p class="MsoNormal" style="margin-top:12.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le paiement de ces frais donne droit à : </span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left:0cm;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">- l&rsquo;accès irrévocable au <strong><span style="color:red; ">MCNP</span></strong> grâce  au Frais de Licence, </span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left:0cm;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">-  l&rsquo;ouverture irrévocable du Compte Marchand <strong><span style="color:red; ">MCNP</span></strong>,</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les frais payés  sont  non récupérables.<strong><span style="color:red; "> </span></strong></span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les avantages du détenteur du Compte  Marchand </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le  Compte Marchand <span style="color:red; ">MCNP</span> permet à son détenteur d&rsquo;obtenir les avantages   suivants : </span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">l&rsquo;Achat  du Pouvoir d&rsquo;Achat <span style="color:#00B0F0; ">CNP</span>,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">le  Bail Nue – Propriété (BNP), c&rsquo;est-à-dire au prêt financier ou bancaire  cautionné par <span style="color:#00B0F0; ">CNP</span>,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">l&rsquo;investissement  nrPRE,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">l&rsquo;emploi  social marchand rémunéré en unités <span style="color:red; ">MCNP</span> dites Crédit en Nature Convertible Salaire (<span style="color:red; ">CNCS</span>) et</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">l&rsquo;enrôlement  des entreprises et industries à l&rsquo;investissement alloué en unités <span style="color:red; ">MCNP</span> dites Subvention  Marchande des Coûts d&rsquo;Investissement et de Production Nouvelle (<span style="color:red; ">SMCIPN</span>). La <span style="color:red; ">SMCIPN</span> est composée de  l&rsquo;investissement qui rembourse les biens immédiats consommés par les  entreprises et industries auprès d&rsquo;autres entreprises et industries ainsi que  le salaire qui rémunère les forces de production (travailleurs du social  marchand).</span></li>
</ul>
<p class="MsoNormal" style="margin-top:12.0pt;text-align:justify;text-justify:inter-ideograph;"><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les obligations du détenteur  du Compte Marchand </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></strong></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Personne Physique&nbsp;:</span></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La  Personne Physique titulaire du Compte Marchand<span style="color:red; "> MCNP </span>est  seule responsable de la gestion de son Compte et est garante de la productivité  de sa communauté. A cet effet, elle dispose de l&rsquo;outil d&rsquo;enrôlement dit nrPRE  Kit Technopole pour&nbsp;: </span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">s&rsquo;éduquer, </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">apprendre,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">se  former,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">faire  les stages,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">se  recycler,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">faire  des recherches visant le développement,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">s&rsquo;enrôler  à l&rsquo;emploi dans l&rsquo;une au moins des divisions au service de l&rsquo;industrialisation  du travail sur le <span style="color:red; ">MCNP</span>.</span></li>
</ul>
<p class="MsoNormal" style="margin-top:12.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Elle est garante en dernier ressort de la solvabilité  absolue et pérenne, de la liquidité absolue ainsi que de la disponibilité  absolue du travail sur le marché <span style="color:red; ">MCNP</span> dans le respect des normes du modèle de l&rsquo;Economie  Universelle(EU) liées aux modalités de paiement en  réponse aux attentes de sa communauté.  </span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Personne Morale</span></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">En ce  qui concerne les Personnes Morales regroupées en divisions (division  administratrice et division animatrice du <strong><span style="color:red; ">MCNP</span></strong>),  leurs obligations sont les suivantes : </span></p>
<ul>
  <li><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour la FILIERE</span></u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Elle est garante en dernier ressort&nbsp;sur le  marché </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">:</span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la <em>liquidité</em> absolue de son Bien, Produit  et Service, </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la <em>disponibilité</em> absolue de son Bien,  Produit et Service, <em>(la liquidité et la  disponibilité absolues qui sous entendent la qualité et la quantité du Bien  Produit et Service sont <strong>gage de lasolvabilité</strong> absolue et pérenne de ladite Filière)</em>,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">du respect des règles de gestion, des normes de  l&rsquo;économie circulaire, de l&rsquo;économie d&rsquo;usage, de l&rsquo;économie de service et de  l&rsquo;économie de cycle court ainsi que le respect des normes du modèle EU liées  aux modalités de paiement,</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la réponse aux attentes du </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> face à la division.</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La Filière tout comme l&rsquo;ACNEV et la Technopole sont  les trois entités, têtes de division qui agréent la mise sur chaîne des  Entreprises et Industries membres et partenaires dans leurs Créneaux&nbsp;:  Production, Transformation et Distribution composé chacun de Grossistes,  Semi-Grossistes et Détaillants grâce à son Compte Marchand PM. </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-justify:inter-ideograph;line-height:normal;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-justify:inter-ideograph;line-height:normal;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:justify;text-justify:inter-ideograph;line-height:normal;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<ul>
  <li><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour l&rsquo;ACNEV</span></u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">L&rsquo;ACNEV se charge de l&rsquo;achat des intrants, de la  centralisation des demandes et des ventes du BPS de la division sur le marché </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> dans le respect des  normes du modèle EU liées aux modalités de paiement.</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Il est garant en dernier ressort&nbsp;:</span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la <em>solvabilité</em> absolue et pérenne de son  BPS, </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la <em>liquidité</em> absolue de son BPS ainsi que </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la <em>disponibilité</em> absolue de son BPS sur le  marché </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> dans le respect des normes du modèle EU en réponse  aux attentes du </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> face à la division. </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
</ul>
<p class="MsoNormal" style="margin-top:12.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">L&rsquo;ACNEV tout comme la Filière et  la Technopole sont les trois entités, têtes de division qui agréent la mise sur  chaîne des Entreprises et Industries membres et partenaires dans leurs  Créneaux&nbsp;: Production, Transformation et Distribution composé chacun de Grossistes,  Semi-Grossistes et Détaillants grâce à son Compte Marchand PM.  </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></p>
<ul>
  <li><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour la TECHNOPOLE</span></u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
</ul>
<p class="MsoNormal" style="margin-top:12.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La Technopole est garante:</span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de l&rsquo;éducation,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de l&rsquo;apprentissage, </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">de la formation,</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">des stages, </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">du recyclage, </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">des recherche et développement et</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">du plein emploi de la division au service de  l&rsquo;industrialisation du BPS sur le marché </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> dans le  respect des normes du modèle EU liées aux modalités de paiement. </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Elle est garante en dernier ressort de la <em>solvabilité</em> absolue et pérenne, de la <em>liquidité</em> absolue ainsi que de la <em>disponibilité</em> absolue du BPS sur le marché </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> dans le respect des normes du modèle EU en réponse  aux attentes du </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> face à la division. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La Technopole tout comme la Filière et l&rsquo;ACNEV sont  les trois entités, têtes de division qui agréent la mise sur chaîne des  Entreprises et Industries membres et partenaires dans leurs Créneaux&nbsp;:  Production, Transformation et Distribution composé chacun de Grossistes,  Semi-Grossistes et Détaillants grâce à son Compte Marchand PM.</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour la  sécurité de tous sur le<span style="color:red; "> MCNP</span>, tout titulaire de  Compte Marchand est responsable de toute utilisation de ses moyens  d&rsquo;authentification (biométrie et cartes) ainsi que du rôle pour lequel le  compte lui est affecté. </span></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">CARACTERISTIQUES  DES UNITES <span style="color:red; ">MCNP</span></span></u></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les  unités <strong><span style="color:red; ">MCNP</span></strong> sont les titres privatifs de solvabilité qui se regroupent en deux  catégories&nbsp;: le pouvoir d&rsquo;achat </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">appelé Crédit en Nature Prépayé</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(</span><strong><span style="line-height:115%; font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNP</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">) et le crédit productif appelé </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Crédit en Nature  Convertible Salaire (<strong><span style="color:red; ">CNCS</span></strong></span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">).</span></p>
<ul>
  <li><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le  Crédit en Nature Prépayé (</span></em></strong><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNP</span></strong><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">)</span></em></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le <strong><span style="color:#00B0F0; ">CNP</span></strong> est le Titre Privatif Numérique qui fait office de pouvoir d&rsquo;achat libérateur, c&rsquo;est-à-dire soldé d&rsquo;avance par le  bénéficiaire sur le <strong><span style="color:red; ">MCNP</span></strong>. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Cependant, le <strong><span style="color:#00B0F0; ">CNP</span></strong> est la créance du <strong><span style="color:red; ">MCNP</span></strong> à <strong><em>solder  en nature</em></strong> grâce à l&rsquo;usage du titre privatif de solvabilité le <strong><span style="color:red; ">CNCS</span></strong> qui lui fait office de crédit productif.       </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le Titre <strong><span style="color:#00B0F0; ">CNP</span></strong> peut être récurrent ou non récurrent. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">C&rsquo;est le <strong><span style="color:#00B0F0; ">CNP</span></strong> qui permet de former le Fonds qui Garantit le Financement en Nature (FGFN)  nominal non décaissable, tandis que le <strong><span style="color:red; ">CNCS</span></strong> permet de former le FGFN réel, Biens, Produits et Services, c&rsquo;est-à-dire que le <strong><span style="color:red; ">CNCS</span></strong> est la rémunération des forces  productrices des entreprises et industries contre les Biens, Produits et  Services (BPS). </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le FGFN en ses  deux versions (nominal et réel) est le gage du <strong><span style="color:red; ">MCNP</span></strong> vis-à-vis de tout partenaire bancaire et financier ainsi que de tout  fournisseur extérieur de Biens, Produits et Services.</span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">LE CREDIT EN NATURE PREPAYE récurrent (<span style="color:#00B0F0; ">CNPr</span>)</span></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le <strong><span style="color:#00B0F0; ">CNPr </span></strong><span style="color:black; ">est un revenu récurrent affecté  directement aux <strong>BPS</strong>. Son prix d&rsquo;achat est fonction de la Période de Constitution  du Capital (PCK) aujourd&rsquo;hui à 5.6. La PCK peut varier.  L&rsquo;achat du </span><strong><span style="color:#00B0F0; ">CNPr </span></strong><span style="color:black; ">est un débours et non une épargne.</span></span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="line-height:115%; font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNPr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; "> ne se cumule pas mais se renouvelle à chaque période  de façon illimitée. </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">Cependant, le cumul du </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNPr </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">est  autorisé en cas de suspension de son renouvellement pérenne par le titulaire. A  cet effet, le cumul observe le renouvellement pendant la période PCK pour la  reconstitution en unité NN et PRK pour la reconstitution en nature.</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">La période de renouvellement  est de trente jours à ce jour. Elle peut varier en fonction du niveau de  solvabilité sur le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">,  c&rsquo;est-à-dire en fonction de la capacité de production effective des BPS.</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;line-height:normal;"><span style="font-family:'Cambria','serif'; font-size:7.0pt; color:black; ">&nbsp;</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">La version </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNPr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; "> dont le  renouvellement est limité est destinée d&rsquo;une part aux entreprises et industries  (douze fois à ce jour) et d&rsquo;autre part aux ménages, variable selon le cas du </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">kit Technopole nrPRE</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; ">. Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNPr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; "> limité ne se reconstitue qu&rsquo;en cas de non expression.</span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">LE CREDIT EN NATURE PREPAYE non récurrent (<span style="color:#00B0F0; ">CNPnr</span>)</span></strong></li>
</ul>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le Crédit en Nature  Prépayé non récurrent (<strong><span style="color:#00B0F0; ">CNPnr</span></strong>) <span style="color:black; ">est la version non  renouvelable du</span> Crédit en Nature  Prépayé récurrent. Contrairement au <strong><span style="color:#00B0F0; ">CNPr</span></strong>, le <strong><span style="color:#00B0F0; ">CNPnr</span></strong> s&rsquo;obtient de façon cumulée, non  renouvelable et vise la réduction des coûts des BPS aux bénéficiaires.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le <strong><span style="color:#00B0F0; ">CNPnr</span></strong> désigne le <strong><span style="color:#00B0F0; ">RPGnr</span></strong> et le  <strong><span style="color:#00B0F0; ">Inr</span></strong>. On distingue à cet effet,  le <strong><span style="color:#00B0F0; ">CNPnrPRK</span></strong> et le <strong><span style="color:#00B0F0; ">CNPnrPRE</span></strong>.  En fonction de ses variables PRK et PRE, le <strong><span style="color:#00B0F0; ">CNPnr</span></strong> se reconstitue par simple  voie de conversion en d&rsquo;autres unités sur le <strong><span style="color:red; ">MCNP</span></strong>.</span></p>
<ul>
  <li><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">LE CREDIT EN  NATURE CONVERTIBLE SALAIRE</span></em></strong><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:red; ">CNCS</span></strong>)&nbsp;:<span style="color:black; "> </span></span></li>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">LE CREDIT EN NATURE CONVERTIBLE SALAIRE non    </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:black; "> </span></li>
</ul>
<p class="MsoListParagraphCxSpLast" style="margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:49.65pt;text-align:justify;text-justify:inter-ideograph;"><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">       récurrent </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:red; ">CNCSnr</span></strong>)<span style="color:black; "> </span></span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le Crédit en Nature Convertible Salaire non récurrent </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:red; ">CNCSnr</span></strong>)  est le Titre Privatif de Solvabilité des salariés (forces de production) qui  s&rsquo;obtient par voie d&rsquo;achat par les employeurs secteurs public et privé pour le  compte de leurs salariés (<strong><span style="color:#00B0F0; ">CNPnr</span></strong>). Il est la contrepartie  du travail effectif fourni aux entreprises et  industries qui l&rsquo;ont acheté.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCSnr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> aux mains des salariés est destiné à l&rsquo;achat des Titres Privatifs </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNPnr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCSnr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> doit observer la période de maturité. Il peut cependant s&rsquo;échanger  librement (contre toute offre) sur le marché en ligne du </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">.</span><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">CONVENTIONS</span></u></em></strong></p>
<p class="MsoSubtitle"><strong><u><span style="line-height:115%; font-size:14.0pt; color:windowtext; ">Convention  N° 1</span></u></strong><strong><span style="font-size:14.0pt; color:windowtext; ">&nbsp;:<u> </u></span></strong></p>
<p class="MsoListParagraph" style="margin:0cm;margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Entre les  structures Têtes de Division Exécutante Partenaires Bancaires et Financiers  (S-CM Exécutante PBF) et les Acteurs</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">CONSOMMATEURS du <span style="color:red; ">MCNP</span></span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">, il est convenu ce qui suit&nbsp;: </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Dans le but de former continuellement le  déposit et le DAT convenus avec les PBF, les structures ESMC  têtes de Division PBF se mettent d&rsquo;accord  avec  les acteurs consommateurs du marché  (individus, ménages, entreprises et industries)   pour  consommer   permanemment   les marchandises  auprès des  Distributeurs-Fournisseurs. En guise d&rsquo;optimisation du pouvoir d&rsquo;achat des  consommateurs, les modalités de consommation convenues sont la consommation  récurrente et la consommation non récurrente.</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le capital d&rsquo;achat variable de ces deux  pouvoirs d&rsquo;achat de consommation se fait 5,6 fois la consommation périodique  pour le récurrent et  5,6(1/8) fois la  consommation une fois de bon pour le non récurrent. </span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le Crédit en Nature Convertible Salaire récurrent </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:red; ">CNCSr</span></strong>)<span style="color:black; "> </span></span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le Crédit en Nature Convertible Salaire récurrent </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:red; ">CNCSr</span></strong>)  est le Titre Privatif de Solvabilité des salariés (forces de production) qui  s&rsquo;obtient par voie de la <strong><span style="color:red; ">SMCPN</span></strong>  pour  le cas du  salaire social. Il est la  contrepartie  du travail effectif fourni  aux entreprises et industries qui l&rsquo;ont acquis.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Conservé auprès de l&rsquo;employeur, le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCSr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> ne se transforme pas et peut être utilisé à tout moment. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCSr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> aux mains des salariés est destiné à l&rsquo;achat des Titres Privatifs </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">CNPnr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">.  Dans ce cas, il doit observer la période de  maturité. </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Mature ou non, le </span></em></strong><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCS</span></em></strong><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> peut s&rsquo;échanger librement (contre toute offre) sur le marché en  ligne du </span></em></strong><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span></em></strong><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">.</span></em></strong></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></em></strong></p>
<p class="MsoSubtitle"><strong><u><span style="font-size:14.0pt; color:windowtext; ">Convention  N° 2</span></u></strong><strong><span style="font-size:14.0pt; color:windowtext; ">&nbsp;: </span></strong></p>
<p class="MsoListParagraph" style="margin:0cm;margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Entre les  structures Têtes de Division Exécutante Subvention Marchande des Coûts de  Production Nouvelle (S-CM Exécutante <span style="color:red; ">SMCPN</span>)  et les Acteurs salariés du <span style="color:red; ">MCNP</span></span></em></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">, il est convenu ce  qui suit :<strong></strong></span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les structures  ESMC Têtes de Division Exécutante (<strong>S-CM  Exécutante <span style="color:red; ">SMCPN</span></strong>) se mettent d&rsquo;accord avec  les acteurs salariés des trois créneaux&nbsp;: Producteurs, Transformateurs et  Distributeurs du marché pour continuellement rémunérer leur travail  effectivement accompli, à condition que la rémunération serve à la consommation  récurrente et non récurrente sur le <strong><span style="color:red; ">MCNP</span></strong>.</span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La Grande  Consommation préfinancée </span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:#00B0F0; ">GC</span>p</strong>) <span style="color:black; "> </span></span></li>
</ul>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La Grande Consommation  préfinancée (<strong><span style="color:#00B0F0; ">GC</span>p</strong>) est le Titre Privatif de Solvabilité  qui s&rsquo;obtient contre le <strong><span style="color:#00B0F0; ">CNP</span></strong> des acheteurs grâce à l&rsquo;échange des BPS préfinancés par les entreprises  et industries distributrices agréées par les têtes de divisions. La <strong><span style="color:#00B0F0; ">GC</span></strong>p est destinée à l&rsquo;achat des Titres Privatifs <strong><span style="color:#00B0F0; ">CNPnr</span></strong> et <strong><span style="color:red; ">CNCS</span></strong> pour la  consommation des BPS de production et la rémunération des forces productrices  pour le compte des entreprises et industries titulaires. S&rsquo;agissant de l&rsquo;achat  du <strong><span style="color:red; ">CNCS</span></strong>, la <strong><span style="color:#00B0F0; ">GC</span></strong>p doit observer la période de maturité. Elle peut cependant s&rsquo;échanger  librement (contre toute offre) sur le marché en ligne du <strong><span style="color:red; ">MCNP</span></strong>.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">CNCS</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> et la </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">GC</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">p à la période de maturité peuvent valablement participer à  l&rsquo;investissement coopératif ou collectif InrPRE (Investissement non récurrent  Période de Reconstitution Effective). </span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">L&rsquo;investissement récurrent (<span style="color:red; ">Ir</span>)</span></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">L&rsquo;Investissement récurrent </span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">(<strong><span style="color:red; ">Ir</span></strong>) est le Titre Privatif de Solvabilité des Entreprises  et Industries (forces de production) qui s&rsquo;obtient par voie de la <strong><span style="color:red; ">SMCI</span></strong>. Il  est la contrepartie  des BPS effectifs obtenus  des fournisseurs par les entreprises et industries qui l&rsquo;ont acquis.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">Ir</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> aux mains des Entreprises et Industries est destiné à l&rsquo;achat des Titres  Privatifs </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:#00B0F0; ">Inr</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">.  </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">Ir</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> ne se transforme pas. Non utilisé, il peut l&rsquo;être à tout moment. </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><strong><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; "><span style="text-decoration:none; ">&nbsp;</span></span></u></strong></p>
<p class="MsoSubtitle"><strong><u><span style="font-size:14.0pt; color:windowtext; ">Convention  N° 3</span></u></strong><strong><span style="font-size:14.0pt; color:windowtext; ">&nbsp;:<u> </u></span></strong></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Entre les  structures Têtes de Division Exécutante Subvention Marchande des Coûts  d&rsquo;Investissement (S-CM Exécutante <span style="color:red; ">SMCI</span>) et les  Producteurs-Transformateurs des BPS du <span style="color:red; ">MCNP</span></span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">, il est convenu  ce qui suit&nbsp;:</span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les structures  ESMC Têtes de Division Exécutante Subvention Marchande des Coûts  d&rsquo;Investissement <strong>(S-CM Exécutante <span style="color:red; ">SMCI</span>) </strong> se  mettent d&rsquo;accord avec les Producteurs-Transformateurs des BPS du marché pour  commander continuellement les marchandises destinées aux réapprovisionnements  des Distributeurs-Fournisseurs. La condition convenue est que les  Producteurs-Transformateurs obtiennent la <span style="color:red; ">SMCI</span> pour acheter en retour les BPS auprès des Distributeurs-Fournisseurs des BPS de  consommation industrielle pour répondre aux commandes.</span></p>
<ul>
  <li><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Entre les  structures Têtes de Division Exécutante Partenaires Bancaires et Financiers  (S-CM Exécutante PBF)  et les Partenaires  Bancaires et Financiers du <span style="color:red; ">MCNP</span></span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">, il est convenu ce qui suit&nbsp;:</span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les structures  ESMC Têtes de Division Exécutante <strong>(S-CM  Exécutante PBF) </strong> se mettent d&rsquo;accord  avec les Partenaires Bancaires et Financiers du marché pour acheter  continuellement les créances de leurs divers produits financiers (les escomptes  des traites aux Distributeurs-Fournisseurs du marché et les crédits divers  accordés aux clients) à condition que les bénéficiaires de ces produits  financiers fassent en retour toutes leurs dépenses de consommation et de  production sur le <strong><span style="color:red; ">MCNP</span></strong>.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La modalité  convenue est celle du paiement par traites aux fournisseurs dont l&rsquo;escompte par  les banques est payé par échéance à ces dernières. A titre d&rsquo;exemple, 8  échéances par unité de traite escomptée et 22,4 échéances pour tous crédits  faits aux membres en vue du financement de leur capital d&rsquo;achat du pouvoir  d&rsquo;achat. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour cela, les  structures ESMC Têtes de Division Exécutante <strong>(S-CM Exécutante PBF) </strong> s&rsquo;engagent à   former la garantie FGFN en guise de DAT en dehors du déposit.</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Cependant, il est obtenu des Partenaires Bancaires et Financiers  dans le cadre du marché commun le procédé de l&rsquo;achat en retour des biens,  produits et services de leurs consommations usuelles auprès des structures ESMC  Têtes de Division Exécutante <strong>(S-CM </strong>Exécutante<strong> BPS)</strong>, grâce à leurs intérêts et frais  divers perçus sur le <strong><span style="color:red; ">MCNP</span></strong>.</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<ul>
  <li><a name="_Ref402771327" id="_Ref402771327"><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Entre les  structures Têtes de Division Exécutante</span></strong></a><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> <strong>Sous-Compte Marchand Exécutante Biens,  Produits et Services (S-CM Exécutante BPS) et les Distributeurs-Fournisseurs  des BPS du <span style="color:red; ">MCNP</span></strong></span><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">, il est convenu ce qui suit&nbsp;:</span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></strong></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Les structures  ESMC Têtes de Division Exécutante <strong>(S-CM </strong>Exécutante<strong> BPS) </strong> se mettent d&rsquo;accord avec les  Distributeurs-Fournisseurs des BPS du marché pour acheter continuellement leurs  marchandises à condition que ceux-ci achètent en retour leurs marchandises en  guise de réapprovisionnement auprès des structures ESMC Têtes de Division  Exécutante <strong>(S-CM </strong>Exécutante<strong> BPS)</strong>.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">La modalité  convenue est celle du paiement par traites (8 traites par exemple).</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour cela, les structures ESMC Têtes de Division Exécutante <strong>(S-CM </strong>Exécutante<strong> BPS) </strong> s&rsquo;engagent à faire  avaliser lesdites traites par les banques en guise de garantie. Cependant,  l&rsquo;exigibilité des redevances aux Distributeurs-Fournisseurs est et reste le  procédé de l&rsquo;achat de BPS en retour auprès des structures ESMC Têtes de  Division Exécutante <strong>(S-CM </strong>Exécutante<strong> BPS)</strong>. </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><u><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">DISPOSITIONS  FINALES </span></u></em></strong></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Au vu de tout ce qui précède et étant  donné que la disponibilité des unités incombe aux divisions administratrices,  que la disponibilité de l&rsquo;espèce bancaire incombe à la division PBF et que la  disponibilité des BPS incombe aux divisions animatrices, la disponibilité des  unités, de l&rsquo;espèce bancaire et des BPS n&rsquo;incombe nullement au vendeur de  Compte Marchand et de la licence <strong><span style="color:red; ">MCNP</span></strong>. La  détention irrévocable du Compte Marchand désengage entièrement le donneur de  licence et le bénéficiaire des Frais de Solvabilité de toute responsabilité  découlant de l&rsquo;usage qu&rsquo;en font les détenteurs. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">En effet, la liquidité des unités, la liquidité de l&rsquo;espèce  bancaire et la disponibilité des BPS sont exclusivement de la responsabilité  des têtes de Divisions&nbsp;: Filières, Technopoles, ACNEV et même de la  personne physique, chapeautés par les divisions de l&rsquo;Exécutante, de la  Surveillance et de la Détentrice.   </span></em></strong></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Cependant, le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> étant un Marché de Crédit en Nature  Pérenne comme son nom l&rsquo;indique, aucune créance n&rsquo;est due en espèce bancaire et  reste en nature pour la simple raison qu&rsquo;il n&rsquo; y a que les Biens, Produits et  Services réels en demande qui soldent de façon absolue les redevances. </span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">En outre, le </span><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; color:red; ">MCNP</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> est conçu pour que personne ne doive à personne.</span></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">En signant ce contrat, le détenteur accepte l&rsquo;achat irrévocable de  son Compte Marchand contre les Frais de Solvabilité et de Licence et s&rsquo;engage à  respecter toutes les conditions liées à son usage,&nbsp;conditions qui toutes  concourent  à ce que personne ne doive à  personne.</span></em><span style="font-family:'Cambria','serif'; font-size:14.0pt; "> </span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;line-height:150%;"><strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Coordonnées du  souscripteur</span></strong><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;:</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Nom&nbsp;……..……………………………………………………………….………………………………..</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Prénom&nbsp;: …………………..……………………………………………………………………………...</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Profession&nbsp;……………….…………………………………………………………………….…….….</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Raison sociale ……………………………………………………………………………………..….</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Objet social ………………………………….…………………………………………………………</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">N° RCCM/RECEPISSE ……………………………………………………………………………….</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Nationalité …………………………………..………………………………………………………….</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">…B.P.&nbsp;:……………Tél.&nbsp;:…………………...………Ville&nbsp;: …………………………………………  Adresse&nbsp;:  .........................................................................................................................................</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">N° Contrat ………………..………………………………………………………………………………</span></p>
<p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">N° Agréments&nbsp;:</span></p>
<ul>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">ACNEV  ….………………………………………………………………………………………..</span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">TECHNOPOLE ………………………………………………………………………………..     </span></li>
  <li><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Filière  …………..………………………………………………………………………………   </span></li>
</ul>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">N° CM  ……………………………………………………………………………………………………...</span></p>
<p class="MsoNormal" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:180.0pt;text-align:justify;text-justify:inter-ideograph;"><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Fait  ……….……………, le ……………….……………..</span></p>
<p class="MsoNormal" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:180.0pt;text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">&nbsp;</span></em></strong></p>
<p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph;"><strong><em><span style="font-family:'Cambria','serif'; font-size:14.0pt; ">Pour l&rsquo;acheteur                                                                      Pour  le Vendeur </span></em></strong></p>
<h2 align="center" style="text-align:center;line-height:150%;"><em><span style="line-height:150%; font-size:14.0pt; "> (Signature précédée de la mention Lu et  approuvé)</span></em></h2>
