<style> 
    /* CUSTOMIZE THE CAROUSEL
    -------------------------------------------------- */

    /* Carousel base class */
    .carousel {
      margin-bottom: 20px;
    }

    .carousel .container {
      position: relative;
      z-index: 9;
    }

    .carousel-control {
      /*height: 80px;*/
      margin-top: 0;
      /*font-size: 120px;*/
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
      /*background-color: transparent;*/
      border: 0;
      z-index: 10;
    }
    .carousel .item {
      height: 350px;
        width: auto;
    }
    .carousel img {
      position: absolute;
      top: 0;
      left: 0;
      min-width: 100%;
      height: 350px;
        width: auto;
    }

    .carousel-caption {
		background: rgba(0, 0, 0, 0.75);
      /*background-color: transparent;*/
      /*position: static;*/
      /*max-width: 250px;*/
      padding: 0 20px;
      margin-top: 0px;
    }

    .carousel-caption h4,
    .carousel-caption .lead p {
      margin: 0;
      line-height: 1.25;
      color: #fff;
      text-shadow: 0 1px 1px rgba(0,0,0,.4);
    }
    .carousel-caption .btn {
      margin-top: 0px;
    }


/*
*/



    /* MARKETING CONTENT
    -------------------------------------------------- */

    /* Center align the text within the three columns below the carousel */
    .marketing .span4 {
      text-align: center;
    }
    .marketing h2 {
      font-weight: normal;
    }
    .marketing .span4 p {
      margin-left: 10px;
      margin-right: 10px;
    }


    /* Featurettes
    ------------------------- */

    .featurette-divider {
      margin: 40px 0; /* Space out the Bootstrap <hr> more */
    }
    .featurette {
      padding-top: 30px; /* Vertically center images part 1: add padding above and below text. */
      overflow: hidden; /* Vertically center images part 2: clear their floats. */
    }
    .featurette-image {
      margin-top: -30px; /* Vertically center images part 3: negative margin up the image the same amount of the padding to center it. */
    }

    /* Give some space on the sides of the floated elements so text doesn't run right into it. */
    .featurette-image.pull-left {
      margin-right: 30px;
    }
    .featurette-image.pull-right {
      margin-left: 30px;
    }

    /* Thin out the marketing headings */
    .featurette-heading {
      font-size: 30px;
      font-weight: 200;
      line-height: 1;
      letter-spacing: -1px;
    }



</style>

	<?php /*?><?php /////////////////PUB BOX////////////////
$date = Zend_Date::now();
$publicite = new Application_Model_EuPubliciteMapper();
$entries = $publicite->fetchAll5(1, 1);
if(count($entries) > 0){?>
<div class="container">
        <!-- Jssor Slider Begin -->
        <!-- You can move inline styles to css file or css block. -->
        <!-- ================================================== -->
        <div id="slider1_container" style="display: none; position: relative; margin: 0 auto; width: 980px;
        height: 380px; overflow: hidden;">

            <!-- Loading Screen -->
            <div u="loading" style="position: absolute; top: 0px; left: 0px;">
                <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;

                background-color: #000; top: 0px; left: 0px;width: 100%; height:100%;">
                </div>
                <div style="position: absolute; display: block; background: url(<?php echo $this->baseUrl();?>/site/slider/img/loading.gif) no-repeat center center;

                top: 0px; left: 0px;width: 100%;height:100%;">
                </div>
            </div>

            <!-- Slides Container -->
            <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1140px; height: 442px;
            overflow: hidden;">
                <?php $a = 0;?>
<?php foreach ($entries as $value) {?>
<?php $a++;?><?php */?>
<?php 
/*$datedebut = $value->date_publicite;
$datefin = $date->toString('yyyy-MM-dd');

list($datedebut,$heure) = explode(' ', $datedebut);

list($annee1,$mois1,$jour1) = explode('-', $datedebut);
switch(strtolower($mois1)) { 
    case 'jan': $mois1 = '01'; break; 
    case 'feb': $mois1 = '02'; break; 
    case 'mar': $mois1 = '03'; break; 
    case 'apr': $mois1 = '04'; break; 
    case 'may': $mois1 = '05'; break; 
    case 'jun': $mois1 = '06'; break; 
    case 'jul': $mois1 = '07'; break; 
    case 'aug': $mois1 = "08"; break; 
    case 'sep': $mois1 = "09"; break; 
    case 'sept': $mois1 = "09"; break; 
    case 'oct': $mois1 = '10'; break; 
    case 'nov': $mois1 = '11'; break; 
    case 'dec': $mois1 = '12'; break; 
  } 
$datedebut = date("Y-m-d", mktime(0, 0, 0, $mois1, $jour1, $annee1));
 
list($annee1,$mois1,$jour1) = explode('-', $datedebut);
list($annee2,$mois2,$jour2) = explode('-', $datefin);

$timestamp1 = mktime(0,0,0,$mois1,$jour1,$annee1); 
$timestamp2 = mktime(0,0,0,$mois2,$jour2,$annee2); 
$duree = intval(abs($timestamp2 - $timestamp1)/86400); 

if($duree <= $value->duree_publicite){*/
?>
                <?php /*?><div>
                    <a href="http://<?php echo ($value->lien_publicite); ?>" target="_blank"><img src="<?php echo $this->baseUrl(); ?>/<?php echo ($value->desc_publicite); ?>" alt="<?php echo ($value->libelle_publicite); ?>" title="<?php echo ($value->libelle_publicite); ?>" /></a>
                </div>
<?php //}?>
<?php }?>
            </div>
            <!-- Bullet Navigator Skin Begin -->
            <style>
                .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
                    background: url(<?php echo $this->baseUrl();?>/site/slider/img/b05.png) no-repeat;
                    overflow: hidden;
                    cursor: pointer;
                }

                .jssorb05 div {
                    background-position: -7px -7px;
                }

                    .jssorb05 div:hover, .jssorb05 .av:hover {
                        background-position: -37px -7px;
                    }

                .jssorb05 .av {
                    background-position: -67px -7px;
                }

                .jssorb05 .dn, .jssorb05 .dn:hover {
                    background-position: -97px -7px;
                }
            </style>
            <!-- bullet navigator container -->
            <div u="navigator" class="jssorb05" style="position: absolute; bottom: 16px; right: 6px;">
                <!-- bullet navigator item prototype -->
                <div u="prototype" style="POSITION: absolute; WIDTH: 16px; HEIGHT: 16px;"></div>
            </div>
            <!-- Bullet Navigator Skin End -->
            <!-- Arrow Navigator Skin Begin -->
            <style>
                .jssora11l, .jssora11r, .jssora11ldn, .jssora11rdn {
                    position: absolute;
                    cursor: pointer;
                    display: block;
                    background: url(<?php echo $this->baseUrl();?>/site/slider/img/a11.png) no-repeat;
                    overflow: hidden;
                }

                .jssora11l {
                    background-position: -11px -41px;
                }

                .jssora11r {
                    background-position: -71px -41px;
                }

                .jssora11l:hover {
                    background-position: -131px -41px;
                }

                .jssora11r:hover {
                    background-position: -191px -41px;
                }

                .jssora11ldn {
                    background-position: -251px -41px;
                }

                .jssora11rdn {
                    background-position: -311px -41px;
                }
            </style>
            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora11l" style="width: 37px; height: 37px; top: 123px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora11r" style="width: 37px; height: 37px; top: 123px; right: 8px">
            </span>
            <!-- Arrow Navigator Skin End -->
            <!--<a style="display: none" href="http://www.jssor.com">bootstrap slider</a>-->
        </div>
        <!-- Jssor Slider End -->
    </div>

      <hr />
<?php }?><?php */?>
	
    
    
	<?php /////////////////PUB BOX////////////////
$date = Zend_Date::now();
$publicite = new Application_Model_EuPubliciteMapper();
$entries = $publicite->fetchAll5(1, 1);
if(count($entries) > 0){?>
      <div id="myCarousel" class="carousel slide">
                <ol class="carousel-indicators">
				<?php for ($i = 0; $i < count($entries); $i++){?>
                  <li data-target="#myCarousel" data-slide-to="<?php echo $i; ?>" <?php if($i == 0){?> class="active"<?php }?>></li>
				  <?php }?>
                </ol>
                <div class="carousel-inner">
                <?php $a = 0;?>
<?php foreach ($entries as $value) {?>
<?php $a++;?>
<?php 
/*$datedebut = $value->date_publicite;
$datefin = $date->toString('yyyy-MM-dd');

list($datedebut,$heure) = explode(' ', $datedebut);

list($annee1,$mois1,$jour1) = explode('-', $datedebut);
switch(strtolower($mois1)) { 
    case 'jan': $mois1 = '01'; break; 
    case 'feb': $mois1 = '02'; break; 
    case 'mar': $mois1 = '03'; break; 
    case 'apr': $mois1 = '04'; break; 
    case 'may': $mois1 = '05'; break; 
    case 'jun': $mois1 = '06'; break; 
    case 'jul': $mois1 = '07'; break; 
    case 'aug': $mois1 = "08"; break; 
    case 'sep': $mois1 = "09"; break; 
    case 'sept': $mois1 = "09"; break; 
    case 'oct': $mois1 = '10'; break; 
    case 'nov': $mois1 = '11'; break; 
    case 'dec': $mois1 = '12'; break; 
  } 
$datedebut = date("Y-m-d", mktime(0, 0, 0, $mois1, $jour1, $annee1));
 
list($annee1,$mois1,$jour1) = explode('-', $datedebut);
list($annee2,$mois2,$jour2) = explode('-', $datefin);

$timestamp1 = mktime(0,0,0,$mois1,$jour1,$annee1); 
$timestamp2 = mktime(0,0,0,$mois2,$jour2,$annee2); 
$duree = intval(abs($timestamp2 - $timestamp1)/86400); 

if($duree <= $value->duree_publicite){*/
?>
                  <div class="item  <?php if($a == 1){?> active<?php }?>">
                    <a href="http://<?php echo ($value->lien_publicite); ?>" target="_blank"><img src="<?php echo $this->baseUrl(); ?>/<?php echo ($value->desc_publicite); ?>" alt="<?php echo ($value->libelle_publicite); ?>" width="1170" height="350" /></a>
                    <div class="carousel-caption">
                      <h4><a href="http://<?php echo ($value->lien_publicite); ?>" target="_blank"><?php echo ($value->libelle_publicite); ?></a></h4>
                    </div>
                  </div>
<?php //}?>
<?php }?>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
              </div>

      <hr />
<?php }?>



        <?php 
        $page = new Application_Model_EuPageMapper();
        $entriespage = $page->fetchAll4("ESMC");
	?>
<?php if(count($entriespage)>0){?> 
      <!-- Example row of columns -->
<div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
<?php foreach ($entriespage as $entrypage): ?>
        <div class="span4">
          <?php if($entrypage->vignette != ""){?><img class="img-circle" src="<?php echo $this->baseUrl();?>/timthumb.php?src=<?php echo $this->baseUrl();?>/<?php echo ($entrypage->vignette); ?>&w=150&h=150&zc=1" /><?php }?>
          <?php $menusous = new Application_Model_EuMenuSous();
        $menusousM = new Application_Model_EuMenuSousMapper();
        $menusousM->find($entrypage->menusous, $menusous);?>
          <h2><?php echo ($menusous->menusous_libelle); ?></h2>
          <p><?php echo ($entrypage->resume); ?></p>
          <p><a class="link" href="<?php echo $this->baseUrl();?>/index/pageesmc/id/<?php echo $entrypage->id_page; ?>">Voir plus &raquo;</a></p>
        </div><!-- /.span4 -->
<?php endforeach; ?>
      </div><!-- /.row -->



      <hr class="featurette-divider" />


    </div>
		<?php }?>

<div class="span12">
	<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?>
      <hr class="featurette-divider" />
</div>



