<?php $sessionzppe = new Zend_Session_Namespace('zppe');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuzppe.phtml"); ?>

  <blockquote><p>Liste des bons</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Numéro</th>
								  <th>Montant</th>
								  <th>Code Membre</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->bon_date); ?></td>
      <td><?php echo ($entry->bon_numero); ?></td>
      <td><?php echo ($entry->bon_montant); ?></td>
      <td><?php echo ($entry->bon_code_membre); ?></td>
      <td><div align="center"><?php if($entry->publier == 1){?>
			<span class="label label-success"><i class="icon-ok icon-white"></i>  Le bon est émis</span>&nbsp;
<?php }else{?>
			<span class="label label-warning"><i class="icon-off icon-white"></i>  Le bon n'est pas encore émis</span>&nbsp;
<?php }?>

</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun bon enrégistré 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








