<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Ajout d'un Terminal d'Echange (TE) </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addacteurinterim">
      
      <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $sessionutilisateur->error; ?>
      </div>
      <?php } ?>

      <?php if(isset($this->error) && $this->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $this->error; ?>
      </div>
      <?php } ?>	  
	   
	
      <legend>Terminal d'Echanges (TE)  de produits</legend>

      <div class="control-group">
	       <label class="control-label" for="nom">Code Membre *</label>
		   <div class="controls">
		        <input type="text" name="code_membre" class="input-xxlarge" id="code_membre" placeholder="Code Membre " value=""  required />
		   </div>
	  </div>
	  
      <div class="control-group">
      <label class="control-label" for="nom">Désignation TE *</label>
      <div class="controls">
      <input type="text" name="nom" id="nom" class="input-xxlarge" placeholder="Désignation TE" required />
	  <!--<input type="hidden" name="code_membre" id="code_membre" placeholder="Code Membre" value="0010010010010000003M"  required />-->
      </div>
      </div>
	  
	  <div class="control-group">
      <label class="control-label">Filière *</label>
      <div class="controls">
      <select  id="id_filiere" name="id_filiere" class="input-xxlarge" required>
      <option value="">Choisir une filière</option>
      <?php foreach ($this->divisions as $value) { ?>
      <option
          value="<?php echo $value->id_filiere; ?>"><?php echo $value->nom_filiere; ?>
	  </option>                         
      <?php } ?>
      </select>
      </div>
      </div>
	  
      <div class="control-group">
      <label class="control-label" for="nom">Nom du Produit *</label>
      <div class="controls">
      <input type="text" name="nom_produit" id="nom_produit" class="input-xxlarge" placeholder="Nom du Produit" required />
      </div>
      </div>

	  
	  <legend>Configuration</legend>
	  
	  <!--
      <legend>Configuration</legend>	  
      <div class="control-group">
      <label class="control-label">PRK </label>
      <div class="controls">
      <?php //$x =1;$compteur=0; ?>
	 
	  <?php //foreach ($this->typeprks as $value) : ?>
	       <input type="checkbox" name="<?php //echo "prk".$x ?>" id="<?php //echo "prk".$x ?>" value="<?php //echo $value->valeur_prk; ?>"/>
		   <?php //echo $value->valeur_prk; ?> &nbsp;&nbsp;
	  <?php //$x++;$compteur++;endforeach; ?>
      </div>
      </div>
	  -->
	  
      <div class="control-group">
      <label class="control-label">Type r&eacute;current </label>
      <div class="controls">
      <input type="checkbox"  name="produit1" id="produit1" value="ri"/>
         R&eacute;current Illimit&eacute; &nbsp;&nbsp;				                         
      <input type="checkbox"  name="produit2" id="produit2" value="rl"/>
         R&eacute;current limit&eacute; &nbsp;&nbsp;				 
      <input type="checkbox"  name="produit3" id="produit3" value="nr"/>
         Non R&eacute;current				                               
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">P&eacute;riode </label>
      <div class="controls">
      <input type="checkbox"  name="periode1" id="periode1" value="11.2"/>
         11.2 &nbsp;&nbsp;				                     
      <input type="checkbox"  name="periode2" id="periode2" value="22.4" />
         22.4 &nbsp;&nbsp
      <input type="checkbox"  name="periode3" id="periode3" value="1" />
         1				 
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">Situation</label>
      <div class="controls">
      <input type="radio"  name="situation" id="situation1" value="1"/>
      Formelle &nbsp;&nbsp 
      <input type="radio"  name="situation" id="situation2" value="0"/>
      Non Formelle &nbsp;&nbsp		   
      </div>
      </div>
	  
     <div class="control-group">
     <label class="control-label">Exonéré de TVA</label>
     <div class="controls">
     <input type="radio"  name="tva" id="tva1" value="0"/>
     Oui &nbsp;&nbsp 	
     <input type="radio"  name="tva" id="tva2" value="1"/>
     Non		   
     </div>
     </div>
      

      <!--<div class="control-group">
      <label class="control-label">Cat&eacute;gorie </label>
      <div class="controls">
      <input type="checkbox"  name="categorie1" id="categorie1" value="special"/>
      Sp&eacute;cial	&nbsp;&nbsp;			                        
      <input type="checkbox"  name="categorie2" id="categorie2" value="ordinaire"/>
      Ordinaire				 				 
      </div>
      </div>-->
	  
	  <div class="control-group">
      <label class="control-label">Produit *</label>
      <div class="controls">
	       <select name="id_prk[]" id="id_prk" multiple="multiple"  class="input-xxlarge" required="required">
              <?php foreach ($this->produits as $produit) { ?>
              <option value="<?php echo $produit->code_type_credit; ?>"> <?php echo utf8_encode($produit->lib_type_credit);?> </option>
               <?php } ?>
           </select>
	  </div>
	  </div>
	  
	  <div class="control-group">
      <label class="control-label" for="type_fournisseur">Type Fournisseur * </label>
      <div class="controls">
      <select name="type_fournisseur" id="type_fournisseur" class="input-xxlarge" required>
         <option value=""> Choisir un type de fournisseur </option>
		 <option value="EXTERNE">Externe</option>
                 <option value="DISTRIBUTEUR">Distributeur</option>
	     <option value="INTERIM">Intérim</option>
	     <option value="SPECIFIQUE">Spécifique</option>
      </select>
      </div>
      </div>
      
	  <!--
      <div class="control-group">
      <label class="control-label" for="mdv">Nombre des tranches &agrave; payer *</label>
      <div class="controls">
      <input type="text" name="mdv" id="mdv" placeholder="Nombre des tranches &agrave; payer" class="input-large"   required />
      </div>
      </div>


      <div class="control-group">
      <label class="control-label" for="mdv">Nombre de payement des tranches *</label>
      <div class="controls">
      <input type="text" name="tranche" id="tranche" placeholder="Nombre de payements des tranches" class="input-large"   required />
      </div>
      </div>
	  -->

      <legend>Découpage géographique</legend>
	  <div class="row-fluid">
           <div class="span4">
                <div class="control-group">
                <label class="control-label span4">Zone Monétaire </label>
                <div class="controls span8">
                     <select class="input-block-level" id="code_zone" name="code_zone" >
                     <option value="">Choisir une zone monétaire</option>
                     <?php foreach ($this->zones as $value) { ?>
                           <option
                                  value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>                         
                     <?php } ?>
                     </select>
                     </div>
                     </div>
            </div>
            <div class="span4">
                 <div class="control-group">
                 <label class="control-label span4">Pays </label>
                 <div class="controls span8">
                      <select class="input-block-level" id="id_pays" name="id_pays" >
                      <option value="">Choisir un pays</option>
                      <?php foreach ($this->pays as $value) { ?>
                      <option
                            value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>                         
                      <?php } ?>
                      </select>
                  </div>
                  </div>
              </div>
              </div>
			  
              <div class="row-fluid">
                   <div class="span4">
                   <div class="control-group">
                   <label class="control-label span4">Régions </label>
                   <div class="controls span8">
                   <select class="input-block-level" id="id_region" name="id_region" >
                   <option value="">Choisir une région</option>
                           <?php foreach ($this->regions as $value) { ?>
                           <option
                                 value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>                         
                           <?php } ?>
                   </select>
               </div>
               </div>
               </div>
			   
               <div class="span4">
                    <div class="control-group">
                    <label class="control-label span4">Préfectures </label>
                    <div class="controls span8">
                         <select class="input-block-level" id="id_prefecture" name="id_prefecture" >
                         <option value="">Choisir une préfecture</option>
                                 <?php foreach ($this->prefectures as $value) { ?>
                         <option
                                 value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>                         
                         <?php } ?>
                         </select>
                         </div>
                         </div>
                </div>
				
                <div class="span4">
                     <div class="control-group">
                     <label class="control-label span4">Cantons </label>
                     <div class="controls span8">
                     <select class="input-block-level" id="id_canton" name="id_canton">
                             <option value="">Choisir un canton</option>
                             <?php foreach ($this->cantons as $value) { ?>
                             <option
                                   value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>                         
                             <?php } ?>
                     </select>
                     </div>
                     </div>
                     </div>
                  </div>

	  
      <div class="form-actions">  
      <input name="ok" type="hidden" id="ok" value="ok" />
      <input type="hidden" name="compteur" value="<?php echo $compteur ?>"/>
      <button type="reset" class="btn">Annuler</button>
      <button type="submit" class="btn btn-primary">Enrégistrer</button>
      </div>
  
</form>
<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








