<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Ajout de compte pour tiers</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addacteurinterim">
      
      <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $sessionutilisateur->error; ?>
      </div>
      <?php } ?>

      <?php if(isset($this->error) && $this->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $this->error; ?>
      </div>
      <?php } ?>	  
	   
	
      <legend>Ajout de compte pour tiers</legend>  
      <div class="control-group">
      <label class="control-label" for="nom">Numéro de quittance *</label>
      <div class="controls">
      <input type="text" name="numero_quittance" id="numero_quittance" placeholder="Numéro Quittance" required />
      </div>
      </div>
	  
      <div class="form-actions">  
      <input name="ok" type="hidden" id="ok" value="ok" />
      <button type="reset" class="btn">Annuler</button>
      <button type="submit" class="btn btn-primary">Enrégistrer</button>
      </div>
  
</form>
<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








