<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?> 
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p> Ajout de la galerie </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addgalerie">
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php } ?>
  


<div class="control-group">
<label class="control-label" for="libelle_galerie">Libellé de la galerie *</label>
<div class="controls">
<input type="text" name="libelle_galerie" id="libelle_galerie" placeholder="Libellé de la galerie" class="input-xxlarge" required />
</div>
</div>

<div class="control-group">
<label class="control-label" for="resume_galerie">Description de la galerie </label>
<div class="controls">
<textarea name="resume_galerie" id="resume_galerie" placeholder="Description de la galerie" ></textarea>
</div>
</div>
    
<div class="form-actions">
<input name="id_utilisateur" type="hidden" id="id_utilisateur" value="<?php echo $sessionutilisateur->id_utilisateur; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary"> Ajouter la galerie </button>
</div>
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








