<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Ajout d'une licence</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addlicence">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
    
<div class="control-group">
<label class="control-label" for="num_licence">Numéro de la détentrice<!--licence--> *</label>
<div class="controls">
<input type="text" name="num_licence" id="num_licence" placeholder="Numéro de la licence" class="input-xxlarge" value="<?php $a = new Application_Model_EuLicence();
        $ma = new Application_Model_EuLicenceMapper();
            echo $ma->findConuterAnnee() + 1;?>/<?php echo date("Y"); ?>/LI/MCNP/<?php $p = new Application_Model_EuPays();
        $mp = new Application_Model_EuPaysMapper();
            $mp->find($sessionutilisateur->pays, $p); echo strtoupper($p->getCode_pays()); ?>" readonly>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="libelle_licence">Libellé de la licence *</label>
<div class="controls">
<input type="text" name="libelle_licence" id="libelle_licence" placeholder="Libellé de la licence" class="input-xxlarge" required>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="desc_licence">Fichier de la licence *</label>
<div class="controls">
<input name="desc_licence" type="file" id="desc_licence" class="input-xxlarge" required />  
</div>
</div>

<div class="form-actions">
<input name="id_utilisateur" type="hidden" id="id_utilisateur" value="<?php echo $sessionutilisateur->id_utilisateur; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter la licence</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








