<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/menus.js"></script>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Ajout de partenaire</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addpartenaire">
  <?php if(isset($this->error) && $this->error!="") {  ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php }  ?>
  
  
<div class="control-group">
<label class="control-label" for="titre">Titre *</label>
<div class="controls">
<input type="text" name="titre" class="input-xxlarge" id="titre" placeholder="Titre" required />
</div>
</div>  
  
  
<div class="control-group">
<label class="control-label" for="resume">Résumé *</label>
<div class="controls">
  <textarea name="resume" class="input-xxlarge" id="resume" placeholder="Résumé" required></textarea>
</div>
</div>


<div class="control-group">
<label class="control-label" for="vignette">Vignette </label>
<div class="controls">
<input name="vignette" type="file" id="vignette" class="input-xxlarge" />  
</div>
</div>

<div class="control-group">
<label class="control-label" for="lien_publicite">Url du partenaire </label>
<div class="controls">
<div class="input-prepend">
  <span class="add-on">http://</span>
<input type="text" name="lien_partenaire" id="lien_partenaire" placeholder="Url du partenaire" class="input-xxlarge" />
</div>
</div>
</div>

<div class="control-group">
<label class="control-label" for="description">Description </label>
<div class="controls">
<textarea name="description" id="description" placeholder="Description" class="ckeditor"></textarea>
</div>
</div>
   
<div class="form-actions">
<input name="publier" type="hidden" id="publier" value="0" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter un partenaire</button>
</div>
  
</form>

<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








