<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>
            
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques2.js"></script>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/fondateurs.js"></script><?php */?>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/capasenrolement.js"></script><?php */?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banquespays.js"></script>


<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml");?>


<blockquote> <p> Ajout d'un pays </p> </blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; ?>
  </div>
  <?php } ?>

  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php } ?>
  

              
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription1" name="addsouscription1">
<fieldset>
<legend> Remplir le formulaire </legend>

<div class="control-group">
<label class="control-label" for="code_pays"> Code pays * </label>
<div class="controls">
     <input type="text" name="code_pays" id="code_pays" placeholder="Code du pays" class="input-xxlarge" required=true />
</div>
</div>


<div class="control-group">
<label class="control-label" for="">Libellé * </label>
<div class="controls">
     <input type="text" name="libelle_pays" id="libelle_pays" placeholder="Libellé du pays" class="input-xxlarge" required=true />
</div>
</div>
 
<div class="control-group">
<label class="control-label" for=""> Nationalité * </label>
<div class="controls">
     <input type="text" name="nat_pays" id="nat_pays" placeholder="Nationalité du pays" class="input-xxlarge" required=true />
</div>
</div>


<div class="control-group">
<label class="control-label" for="">Code téléphonique * </label>
<div class="controls">
     <input type="text" name="code_tel" id="code_tel" placeholder="Code téléphonique" class="input-xxlarge" required=true />
</div>
</div>


<div class="control-group">
<label class="control-label" for="">Zone *</label>
<div class="controls">
     <select class="input-xlarge" id="code_zone" name="code_zone" required>
             <option value="">Choisir une zone</option>
             <?php foreach($this->zones as $value) { ?>
             <option value="<?php echo $value->code_zone;?>">
				<?php echo $value->nom_zone; ?>
			 </option>                         
             <?php } ?>
     </select>
</div>
</div>

</fieldset>
<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter un pays</button>
</div> 
</form>

</div>

</div>
</div>








