<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Ajout d'un utilisateur de Terminal d'Echanges (TE)</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="adduserte">
      
      <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $sessionutilisateur->error; ?>
      </div>
      <?php } ?>

      <?php if(isset($this->error) && $this->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $this->error; ?>
      </div>
      <?php } ?>	  
	   
      <legend> Utilisateur des TE intérim </legend>  
      
	  <div class="control-group">
      <label class="control-label" for="nom">Nom utilisateur *</label>
      <div class="controls">
      <input type="text" name="nom" id="nom" class="input-xxlarge" placeholder="Nom utilisateur" required>
      </div>
      </div>

      <div class="control-group">
      <label class="control-label" for="prenom">Pr&eacute;nom utilisateur *</label>
      <div class="controls">
      <input type="text" name="prenom" id="prenom" class="input-xxlarge"  placeholder="Prenom utilisateur" required />
      </div>
      </div>

      <div class="control-group">
      <label class="control-label" for="login">Login utilisateur *</label>
      <div class="controls">
      <input type="text" name="login" id="login" class="input-xxlarge" placeholder="Login utilisateur" required />
      </div>
      </div>

      <div class="control-group">
      <label class="control-label" for="pwd">Mot de passe *</label>
      <div class="controls">
      <input type="password" name="pwd" id="pwd" class="input-xxlarge" placeholder="Mot de passe" required />
      </div>
      </div>

      <div class="control-group">
      <label class="control-label" for="pwd">Confirmer Mot de passe *</label>
      <div class="controls">
      <input type="password" name="pwd1" id="pwd1" class="input-xxlarge" placeholder="Confirmer le mot de passe" required />
      </div>
      </div>

      <div class="control-group">
      <label class="control-label" for="pwd">Terminal de Vente *</label>
      <div class="controls">
      <select  id="code_tegc" name="code_tegc" class="input-xxlarge" required>
      <option value="">Choisir un terminal de vente </option>
      <?php foreach($this->tegc as $value) { ?>
      <option
        value="<?php echo $value->code_tegc; ?>"><?php echo $value->nom_tegc; ?>
	  </option>                         
      <?php } ?>
      </select>
      </div>
      </div>
	  
	  <div class="control-group">
      <label class="control-label" for="pwd">Code Membre utilisateur *</label>
      <div class="controls">
      <input type="text" name="code_membre" id="code_membre" class="input-xxlarge"  placeholder="Code Membre Utilisateur" required />
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">Zone Mon&eacute;taire *</label>
      <div class="controls">
      <select  id="code_zone" name="code_zone" class="input-xxlarge" required>
      <option value="">Choisir une zone mon&eacute;taire</option>
      <?php foreach ($this->zones as $value) { ?>
      <option
          value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>                         
      <?php } ?>
      </select>
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">Pays *</label>
      <div class="controls">
      <select  id="id_pays" name="id_pays" class="input-xxlarge" required>
      <option value="">Choisir un pays</option>
      <?php foreach ($this->pays as $value) { ?>
      <option
          value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>                         
      <?php } ?>
      </select>
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">R&eacute;gions *</label>
      <div class="controls">
      <select  id="id_region" name="id_region" class="input-xxlarge" required>
      <option value="">Choisir une r&eacute;gion</option>
      <?php foreach ($this->regions as $value) { ?>
      <option
          value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>                         
      <?php } ?>
      </select>
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">Pr&eacute;fectures *</label>
      <div class="controls">
      <select  id="id_prefecture" name="id_prefecture" class="input-xxlarge" required>
      <option value="">Choisir une pr&eacute;fecture</option>
      <?php foreach ($this->prefectures as $value) { ?>
      <option
          value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>                         
      <?php } ?>
      </select>
      </div>
      </div>

      <div class="control-group">
      <label class="control-label">Cantons *</label>
      <div class="controls">
      <select  id="id_canton" name="id_canton" class="input-xxlarge" required>
      <option value="">Choisir un canton</option>
      <?php foreach ($this->cantons as $value) { ?>
      <option
          value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>                         
      <?php } ?>
      </select>
      </div>
      </div>
	  
      <div class="form-actions">  
      <input name="ok" type="hidden" id="ok" value="ok" />
      <button type="reset" class="btn">Annuler</button>
      <button type="submit" class="btn btn-primary">Enrégistrer</button>
      </div>
  
</form>
<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








