<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Detail d'une tâche</p></blockquote>
  
    
  <blockquote><?php echo $this->tache->tache_libelle; ?> 
  <small><?php 
$tachecodeM = new Application_Model_EuUserGroupMapper();
$tachecode = new Application_Model_EuUserGroup();
$tachecodeM->find($this->tache->tache_code, $tachecode);
?><?php echo ($tachecode->libelle_groupe); ?></small></blockquote>

<div>
<?php echo $this->tache->tache_description; ?>
</div>

<div>
<?php echo $this->tache->tache_url; ?>
</div>


<?php /*?><div>
<a href="<?php echo $this->baseUrl();?>/<?php echo $this->tache->tache_url; ?>">Télécharger</a>
</div><?php */?>



</div>
<?php /*?><div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div><?php */?>
</div>
</div>








