<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
    "aaSorting": []
    } );
} );
    </script>
        


<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
                        
            
<?php if(count($this->traites)>0){?> 
  <blockquote><p>Liste des écheances de traites</p></blockquote>
<table class="table table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
              <thead>
                <tr>
                  <th>Tranche</th>
                  <th>Désignation</th>
                  <th>Numéro</th>
                  <!--<th>Banque</th>-->
                  <th>Montant Tranche</th>
                  <th>Début</th>
                  <th>Fin</th>
                  <!--<th>Bons</th>-->
                  <th>Mode Paiement</th>
                  <th>Référence Paiement</th>
                  <th>Actions</th>
                </tr>
              </thead>  
                    <tbody>
<?php foreach ($this->traites as $entry): ?>
<?php 
$date_id = new Zend_Date(Zend_Date::ISO_8601);
   
        $tpagcp = new Application_Model_DbTable_EuTpagcp();
        $select = $tpagcp->select();//Zend_Db_Table::SELECT_WITH_FROM_PART
        //$select->setIntegrityCheck(false);
        //$select->join('eu_membre_morale', 'eu_membre_morale.code_membre_morale = eu_tpagcp.code_membre',array('eu_tpagcp.*','eu_membre_morale.*'));
        $select->where('eu_tpagcp.id_tpagcp = ?', $entry->traite_tegcp); 
        $data = $tpagcp->fetchRow($select);
        $donnees = $data;

          if (substr($donnees->code_membre, -1) == "P") {
          $membre = new Application_Model_EuMembre();
           $membreM = new Application_Model_EuMembreMapper();
           $membreM->find($donnees->code_membre, $membre);
}else{
          $membremorale = new Application_Model_EuMembreMorale();
           $membremoraleM = new Application_Model_EuMembreMoraleMapper();
           $membremoraleM->find($donnees->code_membre, $membremorale);
}
           $banque = new Application_Model_EuBanque();
           $banqueM = new Application_Model_EuBanqueMapper();
           $banqueM->find($entry->traite_code_banque, $banque);

        $date_id = new Zend_Date(Zend_Date::ISO_8601);
            $date_traite = new Zend_Date(Zend_Date::ISO_8601);
            $date_deb = new Zend_Date($entry->traite_date_debut,Zend_Date::ISO_8601);
            $date_fin = new Zend_Date($entry->traite_date_fin,Zend_Date::ISO_8601);
            $periodes = Util_Utils::getParametre('periode', 'valeur');

$bon = new Application_Model_EuBon();
           $bonM = new Application_Model_EuBonMapper();
           $bonM->find($entry->bon_id, $bon);

$numero_opi = substr($donnees->code_membre, 9, -1).$entry->traite_id;
?>
    <tr 
    <?php if($entry->traite_date_fin <= $date_id->toString('yyyy-MM-dd') && $entry->traite_imprimer == 1) {// class="success"?>
    <?php }else if($entry->traite_date_fin <= $date_id->toString('yyyy-MM-dd') && $entry->traite_imprimer == 0) {// class="success"?> style="background-color: rgba(95, 189, 95, 0.69);"
    <?php }else if($entry->traite_disponible == 1) { // class="info"?> style="background-color: rgba(73, 175, 205, 0.74);"
    <?php }else if($entry->traite_avant_vte == 1)  { // class="error"?> style="background-color: rgba(189, 54, 47, 0.68);"
    <?php } ?>
    >
      <td><?php echo $entry->traiter; ?></td>
      <td><?php if (substr($donnees->code_membre, -1) == "P") {echo $membre->nom_membre." ".$membre->prenom_membre;}else{echo $membremorale->raison_sociale;} ?></td>
      <td><?php echo $numero_opi; ?></td>
      <?php /*?><td><?php echo $banque->code_banque; ?></td><?php */?>
      <td><?php echo number_format($donnees->mont_tranche,0,',',' ').''; ?></td>
      <td><?php echo datefr($entry->traite_date_debut); ?></td>
      <td><?php echo datefr($entry->traite_date_fin); ?></td>
      <?php /*?><td><?php echo $donnees->numero_bl; ?></td><?php */?>
      <td><?php echo $entry->mode_paiement; ?></td>
      <td><?php echo $entry->reference_paiement; ?></td>
      <td>
      <?php if($entry->bon_id > 0 && $entry->traite_disponible == 1 && $entry->traite_imprimer == 1 && $entry->traite_date_fin <= $date_id->toString('yyyy-MM-dd')){//$entry->traite_imprimer > 1?>
      <a title="Pour imprimer un OPI" class="btn btn-mini btn-success" target="_blank" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir imprimer cet OPI?')) location='<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $entry->traite_id; ?>'"><i class="icon-cog icon-white"></i> PDF</a><br /> 
<?php }else if($entry->bon_id > 0 && $entry->traite_disponible == 1 && $entry->traite_imprimer == 0 && $entry->traite_date_fin >= $date_id->toString('yyyy-MM-dd')){//$entry->traite_imprimer > 1?>
<?php $comptebancaireM = new Application_Model_EuCompteBancaireMapper();
if (substr($donnees->code_membre, -1) == "P") {
      $comptebancaire = $comptebancaireM->fetchAllByMembre($donnees->code_membre);
}else{
      $comptebancaire = $comptebancaireM->fetchAllByMembreMorale($donnees->code_membre);
}
if(count($comptebancaire) > 0){
foreach ($comptebancaire as $value) {
           ?>
      <abbr title="Pour mettre à jour le mode de paiement de l'OPI de <?php echo $value->code_banque; ?> : <?php echo $value->num_compte_bancaire; ?>"><a class="btn btn-mini btn-success" target="_blank" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir mettre à jour cet OPI de <?php echo $value->code_banque; ?>?')) location='<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $entry->traite_id; ?>/banque/<?php echo $value->id_compte; ?>'"><i class="icon-cog icon-white"></i> <?php echo $value->code_banque; ?> : <?php echo $value->num_compte_bancaire; ?></a></abbr><br /> 
<?php }?>
<?php }?>

<abbr title="Pour mettre à jour le mode de paiement de l'OPI "><form method="post" role="form" name="opi<?php echo $entry->traite_id; ?>" id="opi<?php echo $entry->traite_id; ?>" action="<?php echo $this->baseUrl(); ?>/administration/pdftraite" class="<?php echo $this->baseUrl(); ?>/administration/pdftraite">
<?php         
    $banque = new Application_Model_EuBanqueMapper();
        $entriesbanque = $banque->fetchAll();
?>
         <select name="code_banque" id="code_banque" required class="input-mini">
               <option value="">Choisir un mode</option>
    <?php foreach ($entriesbanque as $entrybanque): ?>
               <option value="<?php echo $entrybanque->code_banque; ?>"><?php echo ($entrybanque->code_banque); ?></option>
    <?php endforeach; ?>
               </select>
<input name="num_compte_bancaire" id="num_compte_bancaire" type="text" required class="input-medium" />
<input name="traite_id" type="hidden" id="traite_id" value="<?php echo $entry->traite_id; ?>" />
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary">Mettre à jour</button>
</form></abbr>

      <?php }?><?php /*?><?php */?>
      </td>
      
    </tr>
<?php endforeach; ?>
</tbody>
            </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune traite  
</div>
<?php }?>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








