<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
        

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
            
<form method="post" enctype="multipart/form-data" role="form" name="traite" id="traite" action="<?php echo $this->baseUrl();?>/administration/banquetraite">
        Sélectionner une banque

<?php         
    $banque = new Application_Model_EuBanqueMapper();
        $entriesbanque = $banque->fetchAll();
?>
         <select name="code_banque" id="code_banque" class="input-xlarge" required="required">
               <option value="">Choisir une banque</option>
    <?php foreach ($entriesbanque as $entrybanque): ?>
               <option value="<?php echo $entrybanque->code_banque; ?>" <?php if(isset($_POST['code_banque']) && $_POST['code_banque'] == $entrybanque->code_banque){echo ' selected="selected"';}?>><?php echo ($entrybanque->libelle_banque); ?></option>
    <?php endforeach; ?>
               </select>
               
            
             
<?php if(count($this->traites)>0){?> 
  <blockquote><p>Liste des écheances de traites</p></blockquote>
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Raison sociale</th>
								  <th>Libelle</th>
								  <th>Banque</th>
								  <th>Montant Tranche</th>
								  <th>Période</th>
								  <th>Bons</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->traites as $entry): ?>
<?php 
$date_id = new Zend_Date(Zend_Date::ISO_8601);
   
        $tpagcp = new Application_Model_DbTable_EuTpagcp();
        $select = $tpagcp->select(Zend_Db_Table::SELECT_WITH_FROM_PART);
        $select->setIntegrityCheck(false)        
               ->join('eu_membre_morale', 'eu_membre_morale.code_membre_morale = eu_tpagcp.code_membre',array('eu_tpagcp.*','eu_membre_morale.*')) 
               ->where('eu_tpagcp.id_tpagcp = ?', $entry->traite_tegcp); 
        $data = $tpagcp->fetchRow($select);
        $donnees = $data;
            
           

        $date_id = new Zend_Date(Zend_Date::ISO_8601);
            $date_traite = new Zend_Date(Zend_Date::ISO_8601);
            $date_deb = new Zend_Date($donnees->date_deb,Zend_Date::ISO_8601);
            $date_fin = new Zend_Date($donnees->date_fin,Zend_Date::ISO_8601);
            $periodes = Util_Utils::getParametre('periode', 'valeur');

            
?>
    <tr>
      <td><?php echo $donnees->raison_sociale; ?></td>
      <td><?php echo $donnees->id_tpagcp.'/0'.$entry->traiter; ?></td>
      <td><?php if($entry->traite_code_banque != "" && $entry->traite_code_banque != NULL){
            $banque = new Application_Model_EuBanque();
           $banqueM = new Application_Model_EuBanqueMapper();
           $banqueM->find($entry->traite_code_banque, $banque);
           echo $banque->libelle_banque.' ('.$banque->code_banque.')';
         } ?></td>
      <td><?php echo number_format($donnees->mont_tranche,0,',',' ').''; ?></td>
      <td><?php echo datefr($date_traite->addDay($entry->traiter * $periodes)->toString('yyyy-MM-dd')).''; ?></td>
      <td><?php if($entry->bon_id > 0){
        $bon = new Application_Model_EuBon();
           $bonM = new Application_Model_EuBonMapper();
           $bonM->find($entry->bon_id, $bon);
          echo $bon->bon_numero;
          } ?></td>
      <td>
        <?php if($entry->bon_id > 0){?>
        <a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/opi/pdftraite/id/<?php echo $entry->traite_tegcp; ?>/codeb/<?php echo $entry->traite_code_banque; ?>/periode/<?php echo $entry->traiter; ?>"><i class="icon-cog icon-white"></i>Pdf</a>
        <?php }else{?>
        <input name="traiter<?php echo $entry->traite_id; ?>" id="traiter<?php echo $entry->traite_id; ?>" type="checkbox" value="1" />
        <?php }?>
      </td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune traite  
</div>
<?php }?>
<input name="id" type="hidden" value="<?php echo $entry->traite_tegcp; ?>" />
            <input name="ok" type="hidden" value="ok" />
<button type="submit" class="btn btn-primary" style="float:right;">Valider</button>
    </form>
  



<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








