<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Modification d'une division </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="update">
<?php if(isset($sessionmembre->errorlogin) && $sessionmembre->errorlogin!="") { ?>
<div class="alert alert-success">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<?php echo $sessionmembre->errorlogin; $sessionmembre->errorlogin = ""; ?>
</div>
<?php } ?>

<?php if(isset($this->error) && $this->error!="") { ?>
<div class="alert alert-error">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<?php echo $this->error; ?>
</div>
<?php } ?>

<legend>Divisions</legend>  
<div class="control-group">
<label class="control-label" for="nom">Nom de la division *</label>
<div class="controls">
<input type="text" name="nom_division" id="nom_division" placeholder="Nom de la division" value="<?php if(isset($this->division)) echo $this->division->nom_division;?>" required />
<input type="hidden" name="id_division" id="id_division" value="<?php if(isset($this->division)) echo $this->division->id_division;?>">
</div>
</div>
	  
<div class="control-group">
<label class="control-label" for="nom">Code division *</label>
<div class="controls">
<input type="text" name="code_division" id="code_division" placeholder="Code division" value="<?php if(isset($this->division)) echo $this->division->code_division;?>" required />
</div>
</div>
	  
<div class="control-group">
<label class="control-label" for="nom">Description</label>
<div class="controls">
<textarea name="desc" id="desc"><?php if(isset($this->division)) echo $this->division->desc_division;?></textarea>
</div>
</div>	  

<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok"/>
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier</button>
</div>
	  	  
</form>
</div>
</div>
</div>