<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left" charset="utf-8">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p> Modification d'un secteur </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="update">
<?php if(isset($sessionmembre->errorlogin) && $sessionmembre->errorlogin!="") { ?>
<div class="alert alert-success">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<?php echo $sessionmembre->errorlogin; $sessionmembre->errorlogin = ""; ?>
</div>
<?php } ?>

<?php if(isset($this->error) && $this->error!="") { ?>
<div class="alert alert-error">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<?php echo $this->error; ?>
</div>
<?php } ?>

<legend>Secteur</legend>  
<div class="control-group">
<label class="control-label" for="nom">Nom du secteur *</label>
<div class="controls">
<input type="text" name="nom_secteur" id="nom_secteur" placeholder="Nom du secteur" value="<?php if(isset($this->secteur)) echo $this->secteur->nom_secteur;?>" required />
<input type="hidden" name="code_secteur" id="code_secteur" value="<?php if(isset($this->secteur)) echo $this->secteur->code_secteur;?>">
</div>
</div>

	  
<div class="control-group">
<label class="control-label">Region *</label>
<div class="controls">
<select  id="id_region" name="id_region" >
<option value="">Choisir une region</option>
<?php foreach($this->regions as $value) { ?>
<option
  value="<?php echo $value->id_region; ?>" <?php if($this->secteur->id_region == $value->id_region) {echo 'selected="selected"';}?> > <?php echo $value->nom_region; ?>
</option>                         
<?php } ?>
</select>
</div>
</div>	

<div class="control-group">
<label class="control-label">Prefecture *</label>
<div class="controls">
<select  id="id_prefecture" name="id_prefecture" >
<option value="">Choisir une prefecture</option>
<?php foreach($this->prefectures as $value) { ?>
<option
  value="<?php echo $value->id_prefecture; ?>" <?php if($this->secteur->id_prefecture == $value->id_prefecture) {echo 'selected="selected"';}?> > <?php echo $value->nom_prefecture; ?>
</option>                         
<?php } ?>
</select>
</div>
</div>


  


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok"/>
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier</button>
</div>
	  	  
</form>
</div>
</div>
</div>