<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Modification du Terminal d'Echanges (TE) de produits </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="update">
      <?php if(isset($sessionmembre->errorlogin) && $sessionmembre->errorlogin!="") { ?>
      <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $sessionmembre->errorlogin; $sessionmembre->errorlogin = ""; ?>
      </div>
      <?php } ?>

      <?php if(isset($this->error) && $this->error!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $this->error; ?>
      </div>
      <?php } ?>	  
	  	  
<div class="control-group">
<label class="control-label" for="nom">D&eacute;signation TE *</label>
<div class="controls">
<input type="text" name="nom" id="nom" placeholder="D&eacute;signation TE" value="<?php if(isset($this->tegc)) echo $this->tegc->nom_tegc;?>" required />
<input type="hidden" name="code_tegc" id="code_tegc" value="<?php if(isset($this->tegc)) echo $this->tegc->code_tegc;?>">
</div>
</div>

<div class="control-group">
<label class="control-label">Fili&egrave;re *</label>
<div class="controls">
     <select  id="id_filiere" name="id_filiere">
     <option value="">Choisir une fili&egrave;re </option>
     <?php foreach ($this->divisions as $value) { ?>
     <option
       value="<?php echo $value->id_filiere; ?>" <?php if($this->tegc->id_filiere == $value->id_filiere) {echo 'selected="selected"';}?> >
	   <?php echo $value->nom_filiere; ?>
	 </option>                         
     <?php } ?>
     </select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="nom">Nom du Produit *</label>
<div class="controls">
<input type="text" name="nom_produit" id="nom_produit" placeholder="Nom du Produit" value="<?php if(isset($this->tegc)) echo $this->tegc->nom_produit;?>" required />
</div>
</div>


<!--
<div class="control-group">
<label class="control-label">PRK </label>
<div class="controls">
	 <?php //$x = 1;$compteur = 0; ?>
	 <?php //foreach ($this->typeprks as $value) : ?>
	       <input type="checkbox" name="<?php //echo "prk".$x ?>" id="<?php //echo "prk".$x ?>" value="<?php //echo $value->valeur_prk; ?>" <?php //if($this->prks != false) {foreach ($this->prks as $prk) { if($prk->valeur == $value->valeur_prk) { echo 'checked="checked"';} }} ?>/>
		   <?php //echo $value->valeur_prk; ?> &nbsp;&nbsp;
	 <?php //$x++;$compteur++;endforeach; ?>
</div>
</div>
-->

<legend>Configuration</legend>


<div class="control-group">
<label class="control-label">Type r&eacute;current </label>
<div class="controls">
     <input type="checkbox"  name="produit1" id="produit1" value="ri" <?php if(isset($this->tegc) && ($this->tegc->recurrent_illimite == 1)) {echo 'checked="checked"';} ?> />
     R&eacute;current Illimit&eacute; &nbsp;&nbsp;				                         
     <input type="checkbox"  name="produit2" id="produit2" value="rl" <?php if(isset($this->tegc) && ($this->tegc->recurrent_limite == 1)) {echo 'checked="checked"';} ?> />
     R&eacute;current limit&eacute; &nbsp;&nbsp;				 
     <input type="checkbox"  name="produit3" id="produit3" value="nr" <?php if(isset($this->tegc) && ($this->tegc->nonrecurrent == 1)) {echo 'checked="checked"';} ?> />
     Non R&eacute;current				                               
</div>
</div>

<div class="control-group">
<label class="control-label">P&eacute;riode </label>
<div class="controls">
     <input type="checkbox"  name="periode1" id="periode1" value="11.2" <?php if(isset($this->tegc) && ($this->tegc->periode1 == 1)) {echo 'checked="checked"';} ?> />
     11.2 &nbsp;&nbsp;				                     
	 <input type="checkbox"  name="periode2" id="periode2" value="22.4" <?php if(isset($this->tegc) && ($this->tegc->periode2 == 1)) {echo 'checked="checked"';} ?> />
     22.4 &nbsp;&nbsp;	
     <input type="checkbox"  name="periode3" id="periode3" value="1" <?php if(isset($this->tegc) && ($this->tegc->periode3 == 1)) {echo 'checked="checked"';} ?> />
     1 				 
</div>
</div>

<div class="control-group">
<label class="control-label">Situation</label>
<div class="controls">
     <input type="radio" name="situation" id="situation1" value="1" <?php if(isset($this->tegc) && ($this->tegc->formel == 1)) {echo 'checked="checked"';} ?> />
     Formelle	&nbsp;&nbsp;			                        
	 <input type="radio"  name="situation" id="situation2" value="0" <?php if(isset($this->tegc) && ($this->tegc->formel == 0)) {echo 'checked="checked"';} ?> />
     Non Formelle				 				 
</div>
</div>


<div class="control-group">
<label class="control-label">Exon&eacute;r&eacute; de TVA</label>
<div class="controls">
     <input type="radio" name="tva" id="tva1" value="0" <?php if(isset($this->tegc) && ($this->tegc->regime_tva == 0)) {echo 'checked="checked"';} ?> />
     Oui &nbsp;&nbsp;			                        
     <input type="radio"  name="tva" id="tva2" value="1" <?php if(isset($this->tegc) && ($this->tegc->regime_tva == 1)) {echo 'checked="checked"';} ?> />
     Non				 				 
</div>
</div>

<!--
<div class="control-group">
<label class="control-label">Cat&eacute;gorie </label>
<div class="controls">
     <input type="checkbox"  name="categorie1" id="categorie1" value="special" <?php if(isset($this->tegc) && ($this->tegc->special == 1)) {echo 'checked="checked"';} ?> />
     Sp&eacute;cial	&nbsp;&nbsp;			                        
	 <input type="checkbox"  name="categorie2" id="categorie2" value="ordinaire" <?php if(isset($this->tegc) && ($this->tegc->ordinaire == 1)) {echo 'checked="checked"';} ?> />
     Ordinaire				 				 
</div>
</div>
-->

<div class="control-group">
      <label class="control-label">Produit *</label>
      <div class="controls">
	       <select name="id_prk[]" id="id_prk" multiple="multiple"  class="input-xxlarge" required="required">
              <?php foreach ($this->produits as $produit) { ?>
              <option value="<?php echo $produit->code_type_credit; ?>" <?php if($this->prks != false) {foreach ($this->prks as $prk) { if($prk->code_type_credit == $produit->code_type_credit) { echo 'checked="checked"';}}}?> > <?php echo utf8_encode($produit->lib_type_credit);?> </option>
               <?php } ?>
           </select>
	  </div>
</div>

<div class="control-group">
	 <label class="control-label">Type fournisseur *</label>
	 <div class="controls">
     <select name="type_tegcp" id="type_tegcp" class="input-xxlarge"  required >
        <option value="">Choisir un type d'acteur</option>
        <option value="EXTERNE" <?php if($this->tegc->type_tegc == "EXTERNE") {echo 'selected="selected"';}?> >Externe</option>
	    <option value="DISTRIBUTEUR" <?php if($this->tegc->type_tegc == "DISTRIBUTEUR") {echo 'selected="selected"';}?> >Distributeur</option>
	    <option value="INTERIM" <?php if($this->tegc->type_tegc == "INTERIM") {echo 'selected="selected"';}?> >Int&eacute;rim</option>
		<option value="SPECIFIQUE" <?php if($this->tegc->type_tegc == "SPECIFIQUE") {echo 'selected="selected"';}?>>Sp&eacute;cifique</option>
        <option value="PRESTATAIRE" <?php if($this->tegc->type_tegc == "PRESTATAIRE") {echo 'selected="selected"';}?>>Prestataire</option>
     
	 </select>
     </div>
</div>

<!--
<div class="control-group">
<label class="control-label" for="mdv">Nombre des tranches &agrave; payer *</label>
<div class="controls">
<input type="text" name="mdv" id="mdv" placeholder="Nombre des tranches &agrave; payer" class="input-large" value="<?php if(isset($this->tegc)) echo $this->tegc->mdv;?>"  required />
</div>
</div>


<div class="control-group">
<label class="control-label" for="mdv">Nombre de payement des tranches *</label>
<div class="controls">
<input type="text" name="tranche" id="tranche" placeholder="Nombre de payements des tranches" class="input-large" value="<?php if(isset($this->tegc)) echo $this->tegc->tranche_payement;?>"  required />
</div>
</div>
-->

<legend>D&eacute;coupage g&eacute;ographique</legend>
<div class="row-fluid">
<div class="span4">
<div class="control-group">
<label class="control-label span4">Zone Mon&eacute;taire </label>
<div class="controls span8">
<select class="input-block-level" id="code_zone" name="code_zone" >
<option value="">Choisir une zone mon&eacute;taire</option>
<?php foreach ($this->zones as $value) { ?>
<option
value="<?php echo $value->code_zone; ?>" <?php if($this->tegc->code_zone == $value->code_zone) {echo 'selected="selected"';}?>  ><?php echo $value->nom_zone; ?></option>                         
<?php } ?>
</select>
</div>
</div>
</div>
<div class="span4">
<div class="control-group">
<label class="control-label span4">Pays </label>
<div class="controls span8">
<select class="input-block-level" id="id_pays" name="id_pays" >
<option value="">Choisir un pays</option>
<?php foreach ($this->pays as $value) { ?>
<option
value="<?php echo $value->id_pays; ?>" <?php if($this->tegc->id_pays == $value->id_pays) { echo 'selected="selected"'; }?> ><?php echo $value->libelle_pays; ?></option>                         
<?php } ?>
</select>
</div>
</div>
</div>
</div>

<div class="row-fluid">
<div class="span4">
<div class="control-group">
<label class="control-label span4">R&eacute;gions </label>
<div class="controls span8">
<select class="input-block-level" id="id_region" name="id_region" >
<option value="">Choisir une r&eacute;gion</option>
<?php foreach ($this->regions as $value) { ?>
<option
value="<?php echo $value->id_region; ?>" <?php if($this->tegc->id_region == $value->id_region) { echo 'selected="selected"'; } ?> ><?php echo $value->nom_region; ?></option>                         
<?php } ?>
</select>
</div>
</div>
</div>
			   
<div class="span4">
<div class="control-group">
<label class="control-label span4">Pr&eacute;fectures </label>
<div class="controls span8">
<select class="input-block-level" id="id_prefecture" name="id_prefecture" >
<option value="">Choisir une pr&eacute;fecture</option>
<?php foreach ($this->prefectures as $value) { ?>
<option
value="<?php echo $value->id_prefecture; ?>" <?php if($this->tegc->id_prefecture == $value->id_prefecture) { echo 'selected="selected"'; } ?> ><?php echo $value->nom_prefecture; ?></option>                         
<?php } ?>
</select>
</div>
</div>
</div>
				
<div class="span4">
<div class="control-group">
<label class="control-label span4">Cantons </label>
<div class="controls span8">
<select class="input-block-level" id="id_canton" name="id_canton">
<option value="">Choisir un canton</option>
<?php foreach ($this->cantons as $value) { ?>
<option
value="<?php echo $value->id_canton; ?>" <?php if($this->tegc->id_canton == $value->id_canton) { echo 'selected="selected"'; } ?> ><?php echo $value->nom_canton; ?></option>                         
<?php } ?>
</select>
</div>
</div>
</div>
</div>


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<!--<input type="hidden" name="compteur" value="<?php //echo $compteur ?>"/>-->
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier</button>
</div>	  
	  
</form>
</div>
</div>
</div>