<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?> 
	<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modification de la tache guichet</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addtache">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
  
<div class="control-group">
<label class="control-label" for="tache_asso">L'integrateur *</label>
<div class="controls">
<?php 
$association = new Application_Model_EuAssociation();
$association_mapper = new Application_Model_EuAssociationMapper();
$association_mapper->find(1, $association);
if(count($association) > 0){?>
<select id="tache_asso" name="tache_asso" required>
  <option value="">Choisir L'integrateur</option>
  <option value="<?php echo $association->association_id; ?>" <?php if($this->tache->tache_asso == $association->association_id){?> selected="selected"<?php }?>><?php echo $association->association_nom; ?></option>
</select>
<?php }?>
</div>
</div>

    
    
<div class="control-group">
<label class="control-label" for="tache_type">Type *</label>
<div class="controls">
<?php 
$tache_type = new Application_Model_EuTacheTypeMapper();
$entries = $tache_type->fetchAll();
if(count($entries) > 0){?>
<select id="tache_type" name="tache_type" required>
  <option value="">Choisir le type</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->tache_type_id; ?>" <?php if($this->tache->tache_type == $value->tache_type_id){?> selected="selected"<?php }?>><?php echo $value->tache_type_libelle; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>
        

<div class="control-group">
<label class="control-label" for="tache_libelle">Libellé de la tache *</label>
<div class="controls">
<input type="text" name="tache_libelle" id="tache_libelle" placeholder="Libellé de la tache" class="input-xxlarge" value="<?php echo $this->tache->tache_libelle; ?>" required />
</div>
</div>

 <div class="control-group">
<label class="control-label" for="tache_description">Description de la tache *</label>
<div class="controls">
<textarea name="tache_description" id="tache_description" placeholder="Description de la tache" class="ckeditor" required><?php echo $this->tache->tache_description; ?></textarea>
</div>
</div>
    
   
    
<div class="control-group">
<label class="control-label" for="tache_url">Url de la tache </label>
<div class="controls">
<input name="tache_url" type="file" id="tache_url" class="input-xxlarge" />  
</div>
</div>
    



<div class="form-actions">
<input name="tache_id" type="hidden" id="tache_id" value="<?php echo $this->tache->tache_id; ?>" />  
<input name="tache_url_old" type="hidden" id="tache_url_old" value="<?php echo $this->tache->tache_url; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier de la tache guichet</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








