<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left" charset="utf-8">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p> Modification d'un pays </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="update">
<?php if(isset($sessionmembre->errorlogin) && $sessionmembre->errorlogin!="") { ?>
<div class="alert alert-success">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<?php echo $sessionmembre->errorlogin; $sessionmembre->errorlogin = ""; ?>
</div>
<?php } ?>

<?php if(isset($this->error) && $this->error!="") { ?>
<div class="alert alert-error">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<?php echo $this->error; ?>
</div>
<?php } ?>

<legend>Pays</legend>

<div class="control-group">
<label class="control-label" for="code_pays"> Code pays * </label>
<div class="controls">
     <input type="text" name="code_pays" id="code_pays" placeholder="Code du pays" value="<?php if(isset($this->pays)) echo $this->pays->code_pays;?>" class="input-xlarge"  required=true />
     <input type="hidden" name="id_pays" id="id_pays" value="<?php if(isset($this->pays)) echo $this->pays->id_pays;?>">
</div>
</div>


<div class="control-group">
<label class="control-label" for="">Libelle * </label>
<div class="controls">
     <input type="text" name="libelle_pays" id="libelle_pays" placeholder="Libelle du pays" value="<?php if(isset($this->pays)) echo $this->pays->libelle_pays;?>" class="input-xlarge" required=true />
</div>
</div>
 
<div class="control-group">
<label class="control-label" for=""> Nationalite * </label>
<div class="controls">
     <input type="text" name="nat_pays" id="nat_pays" placeholder="Nationalite du pays" value="<?php if(isset($this->pays)) echo $this->pays->nationalite;?>" class="input-xlarge" required=true />
</div>
</div>


<div class="control-group">
<label class="control-label" for="">Code telephonique * </label>
<div class="controls">
     <input type="text" name="code_tel" id="code_tel" placeholder="Code telephonique" value="<?php if(isset($this->pays)) echo $this->pays->code_telephonique;?>" class="input-xxlarge" required=true />
</div>
</div>


<div class="control-group">
<label class="control-label" for="">Zone *</label>
<div class="controls">
     <select class="input-xlarge" id="code_zone" name="code_zone" required>
             <option value="">Choisir une zone</option>
             <?php foreach($this->zones as $value) { ?>
             <option value="<?php echo $value->code_zone;?>" <?php if($this->pays->code_zone == $value->code_zone) {echo 'selected="selected"';}?> >
				<?php echo $value->nom_zone; ?>
			 </option>                         
             <?php } ?>
     </select>
</div>
</div>	  


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok"/>
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier</button>
</div>
	  	  
</form>
</div>
</div>
</div>