<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Activer guichet d'un agrément OSE/OE</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addappeloffres">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
<fieldset>
<legend>Formulaire de modification de l'option guichet d'un agrément OSE/OE</legend>
    
<div class="control-group">
<label class="control-label" for="code_agence">Agence *</label>
<div class="controls">
<select name="code_agence" id="code_agence" required>
        <?php $tagence = new Application_Model_DbTable_EuAgence();
        $results = $tagence->fetchAll();?>
  <option value="">Choisir l'agence</option>
    <?php foreach ($results as $agence): ?>
               <option value="<?php echo $agence->code_agence; ?>" <?php if($this->association->code_agence == $agence->code_agence){echo ' selected="selected"';}?>><?php echo ($agence->libelle_agence); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

    
<div class="control-group">
<label class="control-label" for="code_membre">Code Membre  *</label>
<div class="controls">
<input type="text" name="code_membre" id="code_membre" placeholder="Code Membre " class="input-xxlarge" required value="<?php echo ($this->association->code_membre); ?>" />
<span class="help-block"><p class="text-error"><?php if($this->association->code_membre != ""){$membremorale = new Application_Model_EuMembreMorale();
$membremorale_mapper = new Application_Model_EuMembreMoraleMapper();
$membremorale_mapper->find($this->association->code_membre, $membremorale);
echo $membremorale->raison_sociale;}
?></p></span>
</div>
</div>


<div class="control-group">
  <label class="control-label" for="guichet">Guichet ? *</label>
  <div class="controls">
  <select name="guichet" id="guichet" class="input-xxlarge" required>
    <option value="0" selected="selected">Non</option>
    <option value="1">Oui</option>
</select>
  </div>
  </div>
  

</fieldset> 
   
    
    

<div class="form-actions">
<input type="hidden" name="association_id" id="association_id" value="<?php echo $this->association->association_id; ?>" />

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enregistrer</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








