<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modification du sous menu</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addmenusous">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  
<div class="control-group">
<label class="control-label" for="menusous_menu">Menu *</label>
<div class="controls">
<?php 
$menu = new Application_Model_EuMenuMapper();
$entries = $menu->fetchAll();
if(count($entries) > 0){?>
<select id="menusous_menu" name="menusous_menu">
  <option value="0">Choisir le menu</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->menu_id; ?>" <?php if($this->menusous->menusous_menu == $value->menu_id){?> selected="selected"<?php }?>><?php echo $value->menu_libelle; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>

        


<div class="control-group">
<label class="control-label" for="menusous_libelle">Libellé du sous menu *</label>
<div class="controls">
<input type="text" name="menusous_libelle" id="menusous_libelle" placeholder="Libellé du sous menu" class="input-xxlarge" value="<?php echo $this->menusous->menusous_libelle; ?>" required />
</div>
</div>


<div class="control-group">
<label class="control-label" for="menusous_url">Lien direct</label>
<div class="controls">
<input type="text" name="menusous_url" id="menusous_url" placeholder="Lien direct" class="input-xxlarge" value="<?php echo $this->menusous->menusous_url; ?>" />
</div>
</div>
   
    


<div class="form-actions">
<input name="menusous_id" type="hidden" id="menusous_id" value="<?php echo $this->menusous->menusous_id; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier le sous menu</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








