<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left">
		
		<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

            <blockquote>
               <p> <strong> Etat des opérations de BAn exprimé </strong></p>
            </blockquote>
			
			<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
			    <thead>
			        <tr>
				        <th>Montant BAn Exprimé</th>
						<!--<th>Montant BAn Non Anticipé Exprimé </th>
						<th>Montant BAn Anticipé Exprimé </th>
				        <th><div align="right">Détails</div></th>
						-->
			        </tr>
		        </thead>
				
				<tbody>
				    <tr>
						<td><div align="right"><?php echo number_format($this->ban_montant_utilise,0,',',' ');?></div></td>
						<!--<td><div align="right"><?php //echo number_format($this->ban_montant_utilise_na,0,',',' ');?></div></td>
						<td><div align="right"><?php //echo number_format($this->ban_montant_utilise_a,0,',',' ');?></div></td>-->
						
						<td>
						   <div align="right">
						   <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/etatopexp"><i class="icon-info-sign icon-white"></i>Détails</a>
						   </div>
						</td>
						
					</tr>	
				</tbody>
			</table>
</div>
</div>
</div>