<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left">
		
		<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

            <blockquote>
               <p> <strong> Etat des Opérations des BAi Exprimés </strong></p>
            </blockquote>
			
			<?php 
			    if(count($this->entries) > 0) {
			        $montant = 0;
			?>
			
			<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
			    <thead>
			        <tr>
					    <th>Date </th>
						<th>Activité</th>
				        <th>Code membre</th>
				        <th>NOM & PRENOM / RAISON</th>
					    <th>Montant BAi Exprimé </th>
			        </tr>
		        </thead>
				
				<tbody>
				  <?php 
					foreach($this->entries as $entry):
					  $membre = new Application_Model_EuMembre();
	                  $m_map  = new Application_Model_EuMembreMapper();
				      $membremorale = new Application_Model_EuMembreMorale();
	                  $m_mapmorale  = new Application_Model_EuMembreMoraleMapper();
                      $nom = '';
                      if(substr($entry->code_membre,19,1) == 'P')  {
                        $findmembre = $m_map->find($entry->code_membre,$membre);
					    if($findmembre != false) {
						   $nom = $membre->nom_membre."".$membre->prenom_membre;
					    }
                      } else {
                        $findmembre = $m_mapmorale->find($entry->code_membre,$membremorale);
					    if($findmembre != false) {
						   $nom = $membremorale->raison_sociale;
					    }
                      }
				  ?>
				  
				  <tr>
					    <td><?php echo datejourfr($entry->date_capa);?></td>
						<td>&nbsp;</td>
						<td><?php echo $entry->code_membre; ?></td>
					    <td><?php echo $nom ?></td>
						<td><div align="right"><?php echo $entry->montant_utiliser; ?></div></td>
				  </tr>
					<?php 
					    $montant += $entry->montant_utiliser;
					    endforeach; 
					?>
				    	
				</tbody>
				
				<tfoot>
				    <tr><td colspan="5">&nbsp;</td></tr>
				    <tr>
                        <td colspan="4"><div align="right" style="font-size:20px;"><strong> Total Montant BAi Exprimé </strong></div></td>
                        <td><div align="right" style="font-size:20px;"><strong><?php echo number_format($montant,0,',',' ');?></strong></div></td>
                    </tr>
				</tfoot>
				
			</table>
			
			<?php } else { ?>
            <div class="alert alert-info">
                Aucun enrégistrement de BAi Exprimé
            </div>
			<?php } ?>
    </div>
</div>
</div>