<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left">
		
		<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

            <blockquote>
               <p> <strong> Recherche des états quotidiens d'expression des BAn en KACM </strong></p>
            </blockquote>
			
			<div>
			<form method="post" id="frm_rech_bankacm" action="" class="form-horizontal">
			    <?php if (isset($this->message) && $this->message != "") { ?>
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?php
                            echo $this->message;$this->message = "";
                        ?>
                    </div>
                <?php } ?>
				
				<div class="well">
				    <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Date début</label>
                                    <div class="controls span8">
                                    <input type="text" name="date_debut" id="date_debut"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date début" />    
                                    </div>
                                </div>
                            </div>
							
							<div class="span4">
                                <div class="control-group">
                                     <label class="control-label span4">Date fin</label>
                                     <div class="controls span8">
                                     <input type="text" name="date_fin" id="date_fin"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date fin"/>        
                                     </div>
                                </div>
                            </div>
							
							<div class="controls">
                                <button id="btn_valider"   class="btn btn-primary"> Valider </button>
                                <button type="reset" class="btn">Annuler</button>

<?php if (isset($_POST['date_debut'])) {?>
<a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/administration/etatqbankacmexcel/date_debut/<?php echo $_POST['date_debut']; ?>/date_fin/<?php echo $_POST['date_fin']; ?>">Exporter en Excel</a>
<a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/administration/listdetailkacmexcel/date_debut/<?php echo $_POST['date_debut']; ?>/date_fin/<?php echo $_POST['date_fin']; ?>">Exporter en Excel Détails</a>
<?php }?>
                            </div>
                    </div>   
				</div>
			</form>
			</div>
			
			<?php if(count($this->entries) > 0) { 
			    $montant = 0;
			?>
			
			<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
			    <thead>
			    <tr>
				    <th>Nom & Prénoms Client</th>
				    <th>Date</th>
				    <!--<th>Banque</th>
				    <th>Référence Reçu</th>-->
				    <th>Code BAn</th>
					<th>Date d'expression</th>
					<th>Montant BAn en KACM</th>
					<th>Détails BAn</th>
			    </tr>
		        </thead>
				
				<tbody>
				    <?php foreach ($this->entries as $entry): 
					
					   $euban = new Application_Model_DbTable_EuBonNeutre();
                       $select = $euban->select();
                       $select->where("bon_neutre_id = ? ", $entry->bon_neutre_id);
                       $select->limit(1);
                       $rowseuban = $euban->fetchRow($select);
					   
					   $euband = new Application_Model_DbTable_EuBonNeutreDetail();
                       $select = $euband->select();
                       $select->where("bon_neutre_id = ? ", $entry->bon_neutre_id);
                       $select->limit(1);
                       $rowseuband = $euband->fetchRow($select);
					?>
				    <tr>
					    <td><?php echo $rowseuban->bon_neutre_nom." ".$rowseuban->bon_neutre_prenom; ?></td>
						<td><?php echo datejourfr($rowseuban->bon_neutre_date);?></td>
						<td><?php echo $rowseuban->bon_neutre_code; ?></td>
						<td><?php echo datejourfr($entry->bon_neutre_utilise_date);?></td>
						<td><div align="right"><?php echo $entry->bon_neutre_utilise_montant; ?></div></td>
						<td> 
						<div align="center">
						    <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/listdetailkacm/id/<?php echo $entry->bon_neutre_id; ?>"><i class="icon-plus icon-white"></i> Détails</a>&nbsp;
						</div>
						</td>
					</tr>
					<?php 
					    $montant += $entry->bon_neutre_utilise_montant;
					    endforeach; 
					?>	
				</tbody>
				
				<tfoot>
				    <tr><td colspan="6">&nbsp;</td></tr>
				    <tr>
                        <td><div align="left">&nbsp;</div></td>
					    <td><div align="center">&nbsp;</div></td>
					    <td><div align="center">&nbsp;</div></td>
                        <td><div align="right" style="font-size:20px;"><strong> Total Montant BAn en KACM </strong></div></td>
                        <td><div align="right" style="font-size:20px;"><strong><?php echo number_format($montant,0,',',' ');?></strong></div></td>
					    <td><div align="center">&nbsp;</div></td>
                    </tr>
				</tfoot>
				
			</table>
			<?php } else { ?>
            <div class="alert alert-info">
                Aucun enrégistrement BAn
            </div>
			<?php } ?>
    </div>
</div>
</div>