<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left"> 
	<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
	
	<blockquote>
      <p><strong> Recherche des états quotidiens des BAn restants non exprimés </strong></p>
    </blockquote>
	
	<div>
	    <form method="post" id="frm_rech_bankacm" action="" class="form-horizontal">
			<?php if (isset($this->message) && $this->message != "") { ?>
                <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php
                echo $this->message;$this->message = "";
            ?>
            </div>
            <?php } ?>
				
		    <div class="well">
				<div class="row-fluid">
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label span4">Date début</label>
                            <div class="controls span8">
                                <input type="text" name="date_debut" id="date_debut"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date début" />    
                            </div>
                        </div>
                    </div>
							
				    <div class="span4">
                        <div class="control-group">
                            <label class="control-label span4">Date fin</label>
                            <div class="controls span8">
                                <input type="text" name="date_fin" id="date_fin"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date fin"/>        
                            </div>
                        </div>
                    </div>
							
					<div class="controls">
                        <button id="btn_valider"   class="btn btn-primary">Valider</button>
                        <button type="reset" class="btn">Annuler</button>

<?php if (isset($_POST['date_debut'])) {?>
<a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/administration/etatqbanrexcel/date_debut/<?php echo $_POST['date_debut']; ?>/date_fin/<?php echo $_POST['date_fin']; ?>">Exporter en Excel</a>
<?php }?>
                    </div>
                </div>   
			</div>
			</form>
	</div>
	
	<?php if(count($this->entries) > 0) {
		$ttmontant = 0;
		$ttmontantut = 0;
		$ttmontantsolde = 0;
	?>
	
	<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
	        <thead>
			    <tr>
				    <th> Nom & Prénoms Client </th>
				    <th> Date </th>
				    <th> Code BAn </th>
					<!--<th>Montant BAn reçu</th>
					<th>Montant BAn utilisé</th>-->
					<th>Montant BAn Non Exprimés</th>
					<th>Détails BAn</th>
			    </tr>
		    </thead>

            <tbody>
			    <?php foreach($this->entries as $entry) : 
					$euband = new Application_Model_DbTable_EuBonNeutreDetail();
                    $select = $euband->select();
                    $select->where("bon_neutre_id = ? ", $entry->bon_neutre_id);
                    $select->limit(1);
                    $rowseuband = $euband->fetchRow($select);
				?>
                <tr>
			        <td><?php if($entry->bon_neutre_nom != NULL)  { echo $entry->bon_neutre_nom." ".$entry->bon_neutre_prenom;} else {echo $entry->bon_neutre_raison;} ?></td>
				    <td><?php echo datejourfr($entry->bon_neutre_date);?></td>
					<td><?php echo $entry->bon_neutre_code; ?></td>
					<td><div align="right"><?php echo $entry->bon_neutre_montant_solde;?></div></td>
                    <td> 
						<div align="center">
						    <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/listdetailban/id/<?php echo $entry->bon_neutre_id; ?>"><i class="icon-plus icon-white"></i>Détails</a>&nbsp;
						</div>
					</td>					
                </tr>
				<?php 
					//$ttmontant += $entry->bon_neutre_montant;
					//$ttmontantut += $entry->bon_neutre_montant_utilise;
					$ttmontantsolde += $entry->bon_neutre_montant_solde;
					endforeach; 
				?>
				
            </tbody>
            <tfoot>
			    <tr>
				    <td colspan="5">&nbsp;</td>
				</tr>
			    <tr>
                    <td colspan="3"><div align="right" style="font-size:20px;"><strong>Total</strong></div></td>
					<td><div align="right" style="font-size:20px;"><strong><?php echo number_format($ttmontantsolde,0,',',' ');?></strong></div></td>
					<td><div align="center">&nbsp;</div></td>
                </tr>
			</tfoot>
            			
	</table>
	
	<?php } else { ?>
        <div class="alert alert-info">
            Aucun enrégistrement BAn
        </div>
	<?php } ?>
	
	
	
	
	
</div>
</div>
</div>	