<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
<script type="text/javascript" charset="utf-8">
	$(document).ready(function() {
    $('#example').dataTable( {
      "sPaginationType": "full_numbers",
	  "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
            
            
<?php if(count($this->traites)>0){?> 
  <blockquote><p>Liste des traites à escompter</p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Code Membre</th>
								  <th>Compte</th>
								  <th>Début</th>
								  <th>Fin</th>
								  <th>Montant GCP</th>
								  <th>Montant Tranche</th>
								  <th>Montant Echu</th>
								  <th>Montant Solde</th>
								  <th>Eligible</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->traites as $row): ?>
<?php 
		    if($row->escomptable ==3) {
			  $escomptable = 'Oui';
			}elseif($row->escomptable ==2) {
			  $escomptable = 'En cours';
			}elseif($row->escomptable ==1) {
			  $escomptable = 'En cours';
			}elseif($row->escomptable ==0) {
			  $escomptable = 'Non';
			}
?>
    <tr>
      <td><?php echo $row->code_membre; ?></td>
      <td><?php echo $row->code_compte; ?></td>
      <td><?php echo datejourfr($row->date_deb); ?></td>
      <td><?php echo datejourfr($row->date_fin); ?></td>
      <td><?php echo $row->mont_gcp; ?></td>
      <td><?php echo $row->mont_tranche; ?></td>
      <td><?php echo $row->mont_echu; ?></td>
      <td><?php echo $row->solde; ?></td>
      <td><?php echo $escomptable; ?></td>
	  
      <td>
	  <div align="center">
           <?php /*?><a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl();?>/administration/detailstpagcp1/id/<?php echo $row->id_tpagcp; ?>"><i class="icon-search icon-white"></i> Détails</a>&nbsp;	  
           <a class="btn btn-mini btn-success"  onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de  vouloir rendre éligible ?')) location='<?php echo $this->baseUrl(); ?>/administration/escomptable/id/<?php echo $row->id_tpagcp; ?>/escomptable/2'"><i class="icon-cog icon-white"></i>Rendre Eligible</a><?php */?>
	  </div>
      </td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune traite  
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








