<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des payements de commissions pour les intégrateurs</p></blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php }?>
  


<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date du payement</th>
                  <th>Date début</th>
                  <th>Date fin</th>
								  <th>L'intégrateur</th>
								  <th>Type commission</th>
								  <th>Mode payement</th>
								  <th>Montant</th>
								  <th>Payer</th>
								  <?php /*?><th>Actions</th><?php */?>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
<?php         
        $membreasso = new Application_Model_EuMembreasso();
        $m_membreasso = new Application_Model_EuMembreassoMapper();
		$m_membreasso->find($entry->membreasso_id, $membreasso);

        $association = new Application_Model_EuAssociation();
        $m_association = new Application_Model_EuAssociationMapper();
    $m_association->find($membreasso->membreasso_association, $association);
?>
<?php         
        $typecommission = new Application_Model_EuTypeCommission();
        $m_typecommission = new Application_Model_EuTypeCommissionMapper();
		$m_typecommission->find($entry->id_type_commission, $typecommission);
?>
<?php         
        $modepayement = new Application_Model_EuModePayement();
        $m_modepayement = new Application_Model_EuModePayementMapper();
		$m_modepayement->find($entry->id_mode_payement, $modepayement);
?>
    <tr>
      <td><?php echo ($entry->payement_commission_date_payer); ?></td>
      <td><?php echo ($entry->payement_commission_date_debut); ?></td>
      <td><?php echo ($entry->payement_commission_date_fin); ?></td>
<?php  if($entry->payement_commission_type == 1){ ?>
      <td><?php echo ($association->association_nom); ?> (<?php echo ($membreasso->membreasso_nom); ?> <?php echo ($membreasso->membreasso_prenom); ?>)</td>
<?php  }else if($entry->payement_commission_type == 2){  ?>     
      <td><?php echo ($membreasso->membreasso_nom); ?> <?php echo ($membreasso->membreasso_prenom); ?></td>
<?php  }  ?>     
      <td><?php echo ($typecommission->libelle_type_commission); ?></td>
      <td><?php echo ($modepayement->libelle_mode_payement); ?></td>
      <td><?php echo ($entry->payement_commission_montant); ?></td>
      <td><div align="center">
	  <?php if($entry->payement_commission_payer == 1){?>			<i class="icon-ok"></i>  Déjà payé
<?php /*?><?php }else{?>			<i class="icon-off"></i>  Pas Valider<?php */?>
<?php }?>
</div></td>
      <?php /*?><td><div align="center">
			<a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/association/supppayementcommission/id/<?php echo $entry->payement_commission_id; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a></div></td><?php */?>
</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun payement enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








