<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript">		
$(document).ready(function() {
  $('#example').dataTable( {
   "sPaginationType": "full_numbers",
   "aaSorting": []
  });
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Liste des filières</p></blockquote>

<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error !="") { ?>
  <div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
  <?php } ?>


  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
  </div>
  <?php } ?>



<?php if(count($this->entries) > 0) { 

$sousdivision = new Application_Model_EuSousDivision();
$sousdivision_mapper = new Application_Model_EuSousDivisionMapper();

$division = new Application_Model_EuDivision();
$division_mapper = new Application_Model_EuDivisionMapper();


?>
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
       <thead>
			 <tr>
				<th>Nom Filière</th>
				<th>Nom Sous Division</th>
				<th>Nom Division</th>
				<th>Description Filière</th>
				<th>Actions</th>
			 </tr>
		</thead>
		<tbody>
              <?php foreach ($this->entries as $entry) : 
			        if($entry->id_sous_division != null) {
					  $sousdivision_mapper->find($entry->id_sous_division,$sousdivision);
					  $division_mapper->find($sousdivision->id_division,$division); 
					}  
					
                    
			  
			  ?>
              <tr>
			      <td><?php echo $entry->nom_filiere; ?></td>
                  <td><?php if($entry->id_sous_division != null) { echo $sousdivision->nom_sous_division; } else {echo "";} ?></td>
				  <td><?php if($entry->id_sous_division != null) { echo $division->nom_division; } else {echo "";} ?></td>
                  <td><?php echo $entry->descrip_filiere; ?></td>
				  <td>
					  <div align="center">
	                       <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/editfiliere/id/<?php echo $entry->id_filiere; ?>"><i class="icon-edit icon-white"></i>Modifier</a>&nbsp;	   
                      </div>
				  </td>
			  </tr>
			  <?php endforeach; ?>
        </tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucun enrégistrement 
</div>
<?php } ?>









</div>
</div>
</div>