<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur'); ?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
        "sPaginationType": "full_numbers",
        "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">
<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
<blockquote><p> Liste des Partenaires ou Opérateurs Socio-Economique (POSE/OSE)</p></blockquote>



<?php if(count($this->entries) > 0 ) { ?>
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
    <thead>
		<tr>
			<th>Raison sociale</th>
		    <th>Représentant</th>
		    <th>Cellulaire</th>
		    <th>E-mail</th>
		    <th>Ville</th>
		    <th>Quartier</th>
			<th>Canton</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	    foreach($this->entries as $entry):		
	        $canton = new Application_Model_EuCanton();
	        $m_canton = new Application_Model_EuCantonMapper();
		
		    $prefecture = new Application_Model_EuPrefecture();
	        $m_prefecture = new Application_Model_EuPrefectureMapper();
		
		    $region = new Application_Model_EuRegion();
	        $m_region = new Application_Model_EuRegionMapper();
		
		    $pays = new Application_Model_EuPays();
	        $m_pays = new Application_Model_EuPaysMapper();
		
		    $zone = new Application_Model_EuZone();
	        $m_zone = new Application_Model_EuZoneMapper();
			
			$nom_zone = "";
			$libelle_pays = "";
			$nom_region = "";
			$nom_prefecture = "";
			$nom_canton = "";
			
			if($entry->id_canton != NULL &&  $entry->id_canton != "") {
			    $findcanton = $m_canton->find($entry->id_canton,$canton);
		        $findprefecture = $m_prefecture->find($canton->id_prefecture,$prefecture);
		        $findregion = $m_region->find($prefecture->id_region,$region);
		        $findpays = $m_pays->find($region->id_pays,$pays);
		        $findzone = $m_zone->find($pays->code_zone,$zone);
				
				$nom_zone = $zone->nom_zone;
			    $libelle_pays = $pays->libelle_pays;
			    $nom_region = $region->nom_region;
			    $nom_prefecture = $prefecture->nom_prefecture;
				$nom_canton = $canton->nom_canton;
			}
	
	?>
	

    <tr> 
	    <td><?php echo ($entry->raison_sociale); ?></td>
		<td>
	   <?php 
	     $m_representation = new Application_Model_EuRepresentationMapper();
		 $membre = new Application_Model_EuMembre();
		 $m_membre = new Application_Model_EuMembreMapper();
		 $representant = $m_representation->findbyrep($entry->code_membre_morale);
		 
		 if($representant != false) {
		   $m_membre->find($representant->code_membre,$membre);
	       echo $membre->nom_membre." ".$membre->prenom_membre;
		 }	
	   ?>
	   
	</td>
		<td><?php echo ($entry->portable_membre); ?></td>
		<td><?php echo ($entry->email_membre); ?></td>
		<td><?php echo ($entry->ville_membre); ?></td>
		<td><?php echo utf8_encode($entry->quartier_membre); ?></td>
        <td><?php echo ($nom_canton); ?></td>
	</tr>	
	
    <?php	endforeach; ?>
	</tbody>
</table>

<?php } else { ?>
<div class="alert alert-info">
  Aucun OSE/POSE enrégistré 
</div>
<?php } ?>

</div>
<div class="span3">
<?php //include("../application/layouts/scripts/droite_esmc.phtml"); ?>
</div>
</div>
</div>
       










