<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf-8">		
 $(document).ready(function() {
    $('#example').dataTable({
        "sPaginationType": "full_numbers",
		"aaSorting": []
    });
 });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>          
            
<?php if(count($this->traites) > 0) { ?> 
<blockquote><p>Liste des traites</p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
<thead>
	  <tr>
	     <th>#</th>
		 <th>Code Membre</th>
		 <th>Compte</th>
		 <th>Début</th>
		 <th>Fin</th>
		 <th>Montant GCP</th>
		 <th>Montant Tranche</th>
		 <th>Montant Echu</th>
		 <th>Montant Solde</th>
		 <th>Eligible</th>
		 <th>Actions</th>
	  </tr>
</thead> 
 
<tbody>
       <?php foreach ($this->traites as $row) : ?>
	   <?php 
		    if($row->escomptable ==3) {
			  $escomptable = 'Oui';
			} elseif($row->escomptable ==2) {
			  $escomptable = 'En cours';
			} elseif($row->escomptable ==1) {
			  $escomptable = 'En cours';
			}
       ?>
       <tr>
          <td><?php echo $row->id_tpagcp; ?></td>
          <td><?php echo $row->code_membre; ?></td>
          <td><?php echo $row->code_compte; ?></td>
          <td><?php echo $row->date_deb; ?></td>
          <td><?php echo $row->date_fin; ?></td>
          <td><?php echo $row->mont_gcp; ?></td>
          <td><?php echo $row->mont_tranche; ?></td>
          <td><?php echo $row->mont_echu; ?></td>
          <td><?php echo $row->solde; ?></td>
          <td><?php echo $escomptable; ?></td>
          <td><?php /*?><div align="center">
          <?php 
              $mapper_traite = new Application_Model_EuTraiteMapper();
		      $traite = $mapper_traite->findTraiteTegcp($row->id_tpagcp);
	      ?>
		  
		  <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $row->traite_code_banque; ?>/periode/1"><i class="icon-cog icon-white"></i>Traite 1</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/2"><i class="icon-cog icon-white"></i>Traite 2</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/3"><i class="icon-cog icon-white"></i>Traite 3</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/4"><i class="icon-cog icon-white"></i>Traite 4</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/5"><i class="icon-cog icon-white"></i>Traite 5</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/6"><i class="icon-cog icon-white"></i>Traite 6</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/7"><i class="icon-cog icon-white"></i>Traite 7</a>&nbsp;<?php ?>
          <?php ?><a class="btn btn-mini btn-success" target="_blank" href="<?php echo $this->baseUrl(); ?>/administration/pdftraite/id/<?php echo $row->id_tpagcp; ?>/codeb/<?php echo $_POST['code_banque']; ?>/periode/8"><i class="icon-cog icon-white"></i>Traite 8</a>&nbsp;<?php ?><?php */?>
      
		  

          </td>
      </tr>	  


	   <?php endforeach; ?>
</tbody>

</table>
<?php }else{?>
<div class="alert alert-info">
  Aucune traite  
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








