<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
       "sPaginationType": "full_numbers",
	   "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des Membres Acheteurs-Revendeurs</p>
  </blockquote>

<?php if(count($this->entries)>0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
<thead>
<tr>
    <th>Nom && Prenoms / Raison sociale</th>
    <th>Cellulaire</th>
	<th>E-mail</th>
</tr>
</thead>  
<tbody>
<?php foreach ($this->entries as $entry) : 
      $membre = new Application_Model_EuMembre();
	  $m_membre = new Application_Model_EuMembreMapper();
	  
	  $membremorale = new Application_Model_EuMembreMorale();
	  $m_membremorale = new Application_Model_EuMembreMoraleMapper();
	  
	  if(substr($entry->code_membre,19,1) == "P") {
	     $m_membre->find($entry->code_membre,$membre);
	  } else {
         $m_membremorale->find($entry->code_membre,$membremorale);
      }	  

?>
<tr>
    <td><?php if(substr($entry->code_membre,19,1) == "P") { echo ($membre->nom_membre." ".$membre->prenom_membre); } 
	    else {echo $membremorale->raison_sociale;}
	    ?></td>
    <td><?php if(substr($entry->code_membre,19,1) == "P") { echo ($membre->portable_membre);} else {echo ($membremorale->portable_membre);} ?></td>
    <td><?php if(substr($entry->code_membre,19,1) == "P") { echo ($membre->email_membre);} else {echo ($membremorale->email_membre);} ?></td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucun membre acheteur-revendeur enrégistré 
</div>
<?php } ?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








