<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
        

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des commissions </p></blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php }?>
  
                                    <form class="form-inline span4" method="post" enctype="multipart/form-data" role="form" name="souscription" id="souscription" action="">

<label for="periode">Quinzaine *</label>
<select name="periode" id="periode" required>
<?php         
		$partagea = new Application_Model_EuPartageaMapper();
        $entries = $partagea->findMoisAnnee();
?>

  <option value="">Choisir la periode</option>

<?php foreach ($entries as $entry): ?>
<?php 
// Configuration du fuseau horaire. Disponible depuis PHP 5.1
date_default_timezone_set('Europe/London');

$mois = $entry['MOIS'];
$annee = $entry['ANNEE'];

$lastday = strftime("%Y%m%d",mktime(0,0,0,$mois+1,0,$annee));
$firstday = strftime("%Y%m%d",mktime(0,0,0,$mois,1,$annee));

$mois15 = strftime("%Y%m%d",mktime(0,0,0,$mois,15,$annee));

$jour1 = 01;
$jour15 = 15;
$jour16 = 16;
$jourlast = strftime("%d",mktime(0,0,0,$mois+1,0,$annee));
?>
               <option value="<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-0<?php echo $jour1; ?>/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour15; ?>" <?php if(isset($_POST['periode']) && $_POST['periode'] == $annee."-".ajoute1zero($mois)."-0".$jour1."/".$annee."-".ajoute1zero($mois)."-".$jour15){?> selected="selected"<?php }?>>Du 0<?php echo $jour1; ?> au <?php echo ($jour15); ?> <?php echo moisfr($mois); ?> <?php echo ($annee); ?></option>

               <option value="<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour16; ?>/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jourlast; ?>" <?php if(isset($_POST['periode']) && $_POST['periode'] == $annee."-".ajoute1zero($mois)."-".$jour16."/".$annee."-".ajoute1zero($mois)."-".$jourlast){?> selected="selected"<?php }?>>Du <?php echo $jour16; ?> au <?php echo ($jourlast); ?> <?php echo moisfr($mois); ?> <?php echo ($annee); ?></option>

<?php endforeach; ?>
               
</select>

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary" style="float:right;">Trier</button>
</form><br />
<br />


<?php if(count($this->entries)>0){?> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
						  <thead>
							  <tr>
								  <th>OSE/OE</th>
								  <th>L'intégrateur</th>
								  <th>Date</th>
								  <th>Nom & prénom(s) / Raison sociale</th>
								  <th>Commission</th>
								  <th>Payé</th>
								  <th>Impôts</th>
								  <th>Solde</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php 
$partagem_montant = 0;
$partagem_montant_utilise = 0;
$partagem_montant_solde = 0;
$partagem_montant_impot = 0;
?>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php 
        $membreasso = new Application_Model_EuMembreasso();
        $membreassoM = new Application_Model_EuMembreassoMapper();
        $membreassoM->find($entry->partagem_membreasso, $membreasso);
	  
        $association = new Application_Model_EuAssociation();
        $associationM = new Application_Model_EuAssociationMapper();
        $associationM->find($membreasso->membreasso_association, $association);
	  echo $association->association_nom;?></td>
      <td><?php echo $membreasso->membreasso_nom." ".$membreasso->membreasso_prenom;?></td>
      <td><?php 
        $souscription = new Application_Model_EuSouscription();
        $souscriptionM = new Application_Model_EuSouscriptionMapper();
        $souscriptionM->find($entry->partagem_souscription, $souscription);
	  echo datejourfr($souscription->souscription_date); ?></td>
      <td><?php if($souscription->souscription_personne == "PP"){?><?php echo ($souscription->souscription_nom); ?> <?php echo ($souscription->souscription_prenom); ?><?php }else{?><?php echo ($souscription->souscription_raison); ?><?php }?></td>
      <td><?php echo ($entry->partagem_montant); ?></td>
      <td><?php echo ($entry->partagem_montant_utilise); ?></td>
      <td><?php echo ($entry->partagem_montant_impot); ?></td>
      <td><?php echo ($entry->partagem_montant_solde); ?></td>
      <td><div align="center"></div></td>      
    </tr>
<?php 
$partagem_montant += $entry->partagem_montant;
$partagem_montant_utilise += $entry->partagem_montant_utilise;
$partagem_montant_solde += $entry->partagem_montant_solde;
$partagem_montant_impot += $entry->partagem_montant_impot;
?>
<?php endforeach; ?>

</tbody>
<tfoot>
<tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>TOTAUX</td>
      <td><?php echo ($partagem_montant); ?></td>
      <td><?php echo ($partagem_montant_utilise); ?></td>
      <td><?php echo ($partagem_montant_impot); ?></td>
      <td><?php echo ($partagem_montant_solde); ?></td>
      <td><div align="center"></div></td>      
    </tr>
</tfoot>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune commission enregistrée 
</div>
<?php }?>


<br />
<br />
<br />





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








