<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
    "aaSorting": []
    } );
} );
    </script>
        

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des commissions par utilisateurs</p></blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php }?>
  
                                    <form class="form-inline span4" method="post" enctype="multipart/form-data" role="form" name="souscription" id="souscription" action="">

<label for="periode">Quinzaine *</label>
<select name="periode" id="periode" required>
<?php         
    $partagea = new Application_Model_EuPartageaMapper();
        $entries = $partagea->findMoisAnnee3();
?>

  <option value="">Choisir la periode</option>

<?php foreach ($entries as $entry): ?>
<?php 
// Configuration du fuseau horaire. Disponible depuis PHP 5.1
date_default_timezone_set('Europe/London');

$mois = $entry['MOIS'];
$annee = $entry['ANNEE'];

$lastday = strftime("%Y%m%d",mktime(0,0,0,$mois+1,0,$annee));
$firstday = strftime("%Y%m%d",mktime(0,0,0,$mois,1,$annee));

$mois15 = strftime("%Y%m%d",mktime(0,0,0,$mois,15,$annee));

$jour1 = 01;
$jour15 = 15;
$jour16 = 16;
$jourlast = strftime("%d",mktime(0,0,0,$mois+1,0,$annee));
?>
               <option value="<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-0<?php echo $jour1; ?>/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour15; ?>" <?php if(isset($_POST['periode']) && $_POST['periode'] == $annee."-".ajoute1zero($mois)."-0".$jour1."/".$annee."-".ajoute1zero($mois)."-".$jour15){?> selected="selected"<?php }?>>Du 0<?php echo $jour1; ?> au <?php echo ($jour15); ?> <?php echo moisfr($mois); ?> <?php echo ($annee); ?></option>

               <option value="<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour16; ?>/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jourlast; ?>" <?php if(isset($_POST['periode']) && $_POST['periode'] == $annee."-".ajoute1zero($mois)."-".$jour16."/".$annee."-".ajoute1zero($mois)."-".$jourlast){?> selected="selected"<?php }?>>Du <?php echo $jour16; ?> au <?php echo ($jourlast); ?> <?php echo moisfr($mois); ?> <?php echo ($annee); ?></option>

<?php endforeach; ?>
               
</select>

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary" style="float:right;">Trier</button>
</form><br />
<br />

<?php //echo ($this->debut); ?>
<?php //echo ($this->fin); ?>
<?php if(count($this->entries_partagemall)>0){?> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
              <thead>
                <tr>
                  <th>Intégrateurs</th>
                  <th>Utilisateurs</th>
                  <th>Commission</th>
                  <th>Payé</th>
                  <th>Solde</th>
                  <th>Observations</th>
                </tr>
              </thead>  
                    <tbody>
<?php 
$partagem_montant_partagem = 0;
$partagem_montant_utilise_partagem = 0;
$partagem_montant_solde_partagem = 0;
?>
<?php foreach ($this->entries_partagemall as $entry){ ?>
    <tr>
      <td><?php 
        $membreasso = new Application_Model_EuMembreasso();
        $membreassoM = new Application_Model_EuMembreassoMapper();
        $membreassoM->find($entry->partagem_membreasso, $membreasso);
    
        $association = new Application_Model_EuAssociation();
        $associationM = new Application_Model_EuAssociationMapper();
        $associationM->find($membreasso->membreasso_association, $association);
    
    echo $association->association_nom; ?></td>
      <td><?php echo $membreasso->membreasso_nom." ".$membreasso->membreasso_prenom;?></td>
      <td><?php 
        $activation_t = new Application_Model_DbTable_EuActivation();
        $select = $activation_t->select();
        $select->from($activation_t, array('COUNT(id_activation) as nombre'));
        $select->where("membreasso_id = ? ", $membreasso->membreasso_id);
        $select->where("date_activation >= '".$this->debut."' AND date_activation <= '".$this->fin."'");
        $select->where("code_membre NOT IN (SELECT membre_doublon_code_membre2 FROM eu_membre_doublon)");
        $entries_activation = $activation_t->fetchAll($select);
        //var_dump($entries_activation);
if(count($entries_activation)>0){
    $entry2 = $entries_activation[0];
if($association->guichet == 1){
$activation_montant = floor(480 * 25 / 100);
}else{
$activation_montant = floor(109 * 25 / 100); 
}
$activation_montant_activation = $activation_montant * $entry2['nombre'];
//echo $activation_montant_activation;
}/**/

        $code_activation_t = new Application_Model_DbTable_EuCodeActivation();
        $select = $code_activation_t->select();
        $select->from($code_activation_t, array('COUNT(id_code_activation) as nombre'));
        $select->where("membreasso_id = ? ", $membreasso->membreasso_id);
        $select->where("date_generer >= '".$this->debut."' AND date_generer <= '".$this->fin."'");
        $select->where("code_membre NOT IN (SELECT membre_doublon_code_membre2 FROM eu_membre_doublon)");
        $entries_code_activation = $code_activation_t->fetchAll($select);
        //var_dump($entries_code_activation);
if(count($entries_code_activation)>0){
    $entry2 = $entries_code_activation[0];
if($association->guichet == 1){
$code_activation_montant = floor(480 * 25 / 100);
}else{
$code_activation_montant = floor(109 * 25 / 100); 
}
$code_activation_montant_code_activation = $code_activation_montant * $entry2['nombre'];
//echo $code_activation_montant_code_activation;
}/**/

echo ($activation_montant_activation + $code_activation_montant_code_activation);
      ?></td>
      <td></td>
      <td></td>
      <td><div align="center"><a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/listactivationutilisateur/id/<?php echo $entry->partagem_membreasso; ?>/periode/<?php echo str_replace("/", "_", $_POST['periode']); ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;</div></td>      
    </tr>
<?php 
//$partagem_montant_partagem += $this->tab_partagem[$i][2];
//$partagem_montant_utilise_partagem += $this->tab_partagem[$i][3];
//$partagem_montant_solde_partagem += $this->tab_partagem[$i][4];
?>
<?php } ?>

</tbody>
<tfoot>
<tr>
      <td>&nbsp;</td>
      <td>TOTAUX</td>
      <td><?php //echo ($partagem_montant_partagem); ?></td>
      <td><?php //echo ($partagem_montant_utilise_partagem); ?></td>
      <td><?php //echo ($partagem_montant_solde_partagem); ?></td>
      <td><div align="center"></div></td>      
    </tr>
</tfoot>
            </table>
<?php }else{?>
<!--<div class="alert alert-info">
  Aucune commission enregistrée 
</div>-->
<?php }?>


<br />
<br />
<br />







<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








