<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
    "aaSorting": []
    } );
} );
    </script>
       

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Etats des Comptes Marchands </p></blockquote>

<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Formulaire de trie par critères
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse <?php if (!isset($_POST['ok'])) {?> in <?php }?>">
      <div class="accordion-inner">
<form method="post" enctype="multipart/form-data" role="form" name="souscription" id="souscription" action="" class="">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php } ?>
  
<div class="">
  <div class="span4">
  
    <div class="control-group">
  <label class="control-label" for="date_identification1">Date Début  </label>
  <div class="controls">
    <input type="text" name="date_identification1" id="date_identification1" placeholder="Date Début" class="input-medium datepicker" data-provide="datepicker" value="<?php 
                        $eumemb = new Application_Model_DbTable_EuMembreMorale();
                        $select = $eumemb->select();
                        $select->order(array('date_identification ASC'));
                        $select->limit(1);
                        $rowseumemb = $eumemb->fetchRow($select);
                        echo substr($rowseumemb->date_identification, 0, 10); ?>" readonly />
  </div>
  </div>

  <div class="control-group">
  <label class="control-label" for="date_identification2">Date Fin  </label>
  <div class="controls">
    <input type="text" name="date_identification2" id="date_identification2" placeholder="Date Fin" class="input-medium datepicker" data-provide="datepicker" value="<?php 
                        $eumemb = new Application_Model_DbTable_EuMembreMorale();
                        $select = $eumemb->select();
                        $select->order(array('date_identification DESC'));
                        $select->limit(1);
                        $rowseumemb = $eumemb->fetchRow($select);
                        echo substr($rowseumemb->date_identification, 0, 10); ?>" readonly />
  </div>
  </div>

</div>


<div class="span4">
  
    <div class="control-group">
  <label class="control-label" for="periode">Quinzaine  </label>
  <div class="controls">
  <select name="periode" id="periode">
<?php         
    $eumemb = new Application_Model_DbTable_EuMembreMorale();
    $select = $eumemb->select();
    $select->distinct();
    $select->setIntegrityCheck(false);
    $select->from($eumemb, array('MONTH(date_identification) as MOIS, YEAR(date_identification) as ANNEE'));
    $select->order(array("date_identification DESC"));
    $resultSet = $eumemb->fetchAll($select);
    $entries = array();
    foreach ($resultSet as $row) {
    $entry = array();
    $entry['MOIS'] = $row['MOIS'];
    $entry['ANNEE'] = $row['ANNEE'];
    $entries[] = $entry;
    }
?>

  <option value="">Choisir la periode</option>

<?php foreach ($entries as $entry): ?>
<?php 
// Configuration du fuseau horaire. Disponible depuis PHP 5.1
date_default_timezone_set('Europe/London');

$mois = $entry['MOIS'];
$annee = $entry['ANNEE'];

$lastday = strftime("%Y%m%d",mktime(0,0,0,$mois+1,0,$annee));
$firstday = strftime("%Y%m%d",mktime(0,0,0,$mois,1,$annee));

$mois15 = strftime("%Y%m%d",mktime(0,0,0,$mois,15,$annee));

$jour1 = 01;
$jour15 = 15;
$jour16 = 16;
$jourlast = strftime("%d",mktime(0,0,0,$mois+1,0,$annee));
?>
               <option value="<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-0<?php echo $jour1; ?>/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour15; ?>" <?php if(isset($_POST['periode']) && $_POST['periode'] == $annee."-".ajoute1zero($mois)."-0".$jour1."/".$annee."-".ajoute1zero($mois)."-".$jour15){?> selected="selected"<?php }?>>Du 0<?php echo $jour1; ?> au <?php echo ($jour15); ?> <?php echo moisfr($mois); ?> <?php echo ($annee); ?></option>

               <option value="<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour16; ?>/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jourlast; ?>" <?php if(isset($_POST['periode']) && $_POST['periode'] == $annee."-".ajoute1zero($mois)."-".$jour16."/".$annee."-".ajoute1zero($mois)."-".$jourlast){?> selected="selected"<?php }?>>Du <?php echo $jour16; ?> au <?php echo ($jourlast); ?> <?php echo moisfr($mois); ?> <?php echo ($annee); ?></option>

<?php endforeach; ?>
               
</select>

    </div>
  </div>

</div>
    
    </div>
    
 <div class="">
  <div class="span12">
   
<div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<!--<button type="reset" class="btn">Annuler</button>-->
<button type="submit" class="btn btn-primary">Trier</button>
</div>    

    </div>
    </div>

</form>


      </div>
    </div>
  </div>
  
</div>



<table class="table table-striped table-bordered table-hover table-condensed">
<tfoot>
<?php if(count($this->entries_membre2)>0){?> 
<tr>
      <td><strong>Activation Personne Physique (Auto-enrôlement ESMC)</strong></td>
      <td><strong>Nombre Total</strong> :</td>
      <td><strong><?php echo number_format(count($this->entries_membre2), 0, ',', ' '); ?></strong></td>
      <td><strong>Montant Unitaire </strong> :</td>
      <td><strong><?php echo number_format(5000, 0, ',', ' '); ?></strong></td>
      <td><strong>Montant Total </strong> :</td>
      <td><strong><?php echo number_format((count($this->entries_membre2) * 5000), 0, ',', ' '); ?></strong></td>
    </tr>
<tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
<?php }?>
<?php if(count($this->entries_membre3)>0){?> 
<tr>
      <td><strong>Activation pour Tiers ESMC</strong></td>
      <td><strong>Nombre Total</strong> :</td>
      <td><strong><?php echo number_format(count($this->entries_membre3), 0, ',', ' '); ?></strong></td>
      <td><strong>Montant Unitaire </strong> :</td>
      <td><strong><?php echo number_format(2187.5, 1, ',', ' '); ?></strong></td>
      <td><strong>Montant Total </strong> :</td>
      <td><strong><?php echo number_format((count($this->entries_membre3) * 2187.5), 1, ',', ' '); ?></strong></td>
    </tr>
<tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
<?php }?>
<?php if(count($this->entries_membremorale2)>0){?> 
<tr>
      <td><strong>Activation Personne Morale (Auto-enrôlement ESMC)</strong></td>
      <td><strong>Nombre Total</strong> :</td>
      <td><strong><?php echo number_format(count($this->entries_membremorale2), 0, ',', ' '); ?></strong></td>
      <td><strong>Montant Unitaire </strong> :</td>
      <td><strong><?php echo number_format(70000, 0, ',', ' '); ?></strong></td>
      <td><strong>Montant Total </strong> :</td>
      <td><strong><?php echo number_format((count($this->entries_membremorale2) * 70000), 0, ',', ' '); ?></strong></td>
    </tr>
<tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
<?php }?>
</tfoot>
            </table>
                      <br />


<br />
<br />




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








