<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
        

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des demandes de réactivations de MCNP</p></blockquote>
<?php if(count($this->entries)>0){?> 

<div class="accordion" id="accordion2">
<?php foreach ($this->entries as $entry_agence): ?>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?php echo $entry_agence->code_agence; ?>">
        <i class="icon-arrow-right"></i> <?php echo ($entry_agence->libelle_agence); ?>
      </a>
    </div>
    <div id="collapse<?php echo $entry_agence->code_agence; ?>" class="accordion-body collapse in" align="left">
      <div class="accordion-inner">

<?php 
        $souscription = new Application_Model_EuSouscriptionMapper();
        if($sessionutilisateur->code_agence != "001001001001"){
        $entriessouscription = $souscription->fetchAllByPublierReactivation(0, $sessionutilisateur->code_agence, 20);
			}else{
        $entriessouscription = $souscription->fetchAllByPublierReactivation(0, "", 20);
				}
?>
<?php if(count($entriessouscription)>0){?> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Personne</th>
								  <th>Nom & prénom(s) / Raison sociale</th>
								  <th>Cellulaire</th>
								  <th>Programme</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($entriessouscription as $entry): ?>
    <tr <?php if($entry->souscription_ancien_membre != ""){?> class="info"<?php }?>>
      <td><?php echo datejourfr($entry->souscription_date); ?></td>
      <td><?php echo ($entry->souscription_personne); ?></td>
      <td><?php if($entry->souscription_personne == "PP"){?><?php echo ($entry->souscription_nom); ?> <?php echo ($entry->souscription_prenom); ?><?php }else{?><?php echo ($entry->souscription_raison); ?><?php }?></td>
      <td><?php echo ($entry->souscription_mobile); ?></td>
      <td><?php echo ($entry->souscription_programme); ?></td>
      <td><div align="center">
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/detailssouscription/id/<?php echo $entry->souscription_id; ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;
            </div></td>
    </tr>
<?php endforeach; ?>

</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun membre enregistré 
</div>
<?php }?>

      </div>
    </div>
  </div>
<?php endforeach; ?>

</div>

                                    <br />
<br />
<br />
<br />
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








