<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des relevés bancaires</p></blockquote>
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Banque</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->relevebancaire_date); ?></td>
      <td><?php echo $entry->relevebancaire_banque; ?> - <?php 
        $banque = new Application_Model_EuBanque();
        $banqueM = new Application_Model_EuBanqueMapper();
        $banqueM->find($entry->relevebancaire_banque, $banque);
echo $banque->libelle_banque; ?></td>
      <td><div align="center"><?php if($sessionutilisateur->code_groupe == "surveillance_technopole"){?>
<?php if($entry->publier == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/publierrelevebancaire/id/<?php echo $entry->relevebancaire_id; ?>/publier/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/publierrelevebancaire/id/<?php echo $entry->relevebancaire_id; ?>/publier/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
	  <?php }?>
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/listrelevebancairedetail/id/<?php echo $entry->relevebancaire_id; ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;

			<?php if($sessionutilisateur->code_groupe == "surveillance_technopole"){?>
<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/editrelevebancaire/id/<?php echo $entry->relevebancaire_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/administration/supprelevebancaire/id/<?php echo $entry->relevebancaire_id; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a><?php }?></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun relevé bancaire enrégistré
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








