<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
        

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des doublons de membres personnes physiques ou morales activés</p></blockquote>
<?php if(count($this->entries)>0){?> 
      <table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
					    <thead>
						    <tr>
							    <th>#</th>
							    <th>Code Membre 1</th>
							    <th>&nbsp;</th>
							    <th>Cellulaire</th>
							    <th>Code Membre 2</th>
							    <th>&nbsp;</th>
							    <th>Cellulaire</th>
							    <th>Utilisateurs</th>
							    <th>Actions</th>
						    </tr>
					    </thead>  
                  <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->membre_doublon_id); ?></td>
      <td><?php echo ($entry->membre_doublon_code_membre1); ?></td>
      <td><?php 
if (substr($entry->membre_doublon_code_membre1, -1) == "P") {
$membre = new Application_Model_EuMembre();
$mapper_membre = new Application_Model_EuMembreMapper();
$mapper_membre->find($entry->membre_doublon_code_membre1, $membre);
echo ($membre->nom_membre)." ".($membre->prenom_membre);
} else if (substr($entry->membre_doublon_code_membre1, -1) == "M") {
$membre = new Application_Model_EuMembreMorale();
$mapper_membre = new Application_Model_EuMembreMoraleMapper();
$mapper_membre->find($entry->membre_doublon_code_membre1, $membre);
echo ($membre->raison_sociale);
}
	   ?></td>
      <td><?php echo ($membre->portable_membre); ?></td>
      <td><?php echo ($entry->membre_doublon_code_membre2); ?></td>
      <td><?php 
if (substr($entry->membre_doublon_code_membre2, -1) == "P") {
$membre = new Application_Model_EuMembre();
$mapper_membre = new Application_Model_EuMembreMapper();
$mapper_membre->find($entry->membre_doublon_code_membre2, $membre);
echo ($membre->nom_membre)." ".($membre->prenom_membre);
} else if (substr($entry->membre_doublon_code_membre2, -1) == "M") {
$membre = new Application_Model_EuMembreMorale();
$mapper_membre = new Application_Model_EuMembreMoraleMapper();
$mapper_membre->find($entry->membre_doublon_code_membre2, $membre);
echo ($membre->raison_sociale);
}
	   ?></td>
      <td><?php echo ($membre->portable_membre); ?></td>
      <td><?php if ($entry->membreasso_id > 0) {
$membreasso = new Application_Model_EuMembreasso();
$mapper_membreasso = new Application_Model_EuMembreassoMapper();
$mapper_membreasso->find($entry->membreasso_id, $membreasso);
echo ($membreasso->membreasso_nom)." ".($membreasso->membreasso_prenom);
} ?></td>
      <td><div align="center"><?php if($entry->membre_doublon_etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/etatmembredoublon/id/<?php echo $entry->membre_doublon_id; ?>/etat/0"><i class="icon-ok icon-white"></i>  Actif</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/etatmembredoublon/id/<?php echo $entry->membre_doublon_id; ?>/etat/1"><i class="icon-off icon-white"></i>  Inactif</a>&nbsp;
<?php }?>

			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/detailsmembredoublon/id/<?php echo $entry->membre_doublon_id; ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;
</div></td>
    </tr>
<?php endforeach; ?>

</tbody>
      </table>
      <br />

<br />
<br />

<?php }else{?>
<div class="alert alert-info">
  Aucun doublon enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








