<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Liste des demandes de configuration des Terminaux d'Echanges (TE) déjà validées</p></blockquote>
<?php if(isset($sessionutilisateur->errorlogin) && $sessionutilisateur->errorlogin!="") { ?>
      <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $sessionutilisateur->errorlogin; $sessionutilisateur->errorlogin = ""; ?>
      </div>
      <?php } ?>
	  
<div align="right"><a href="<?php echo $this->baseUrl(); ?>/administration/adddemandeconfig"> Faire la demande de configuration </a> </div>
<br/>	  
	 
<?php if(count($this->entries)>0){?> 
                                    
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Code Membre</th>
								  <th>Raison sociale</th>
								  <th>Produit</th>
								  <th>Type</th>
								  <th>Spécial</th>
								  <th>Ordinaire</th>
								  <th>Validation</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datejourfr($entry->date_demande); ?></td>
      <td><?php echo ($entry->code_membre_morale); ?></td>
      <?php $mappermorale = new Application_Model_EuMembreMoraleMapper();
						$membremorale = new Application_Model_EuMembreMorale();
						$mappermorale->find($entry->code_membre_morale, $membremorale);
						 ?>
      <td><?php echo ($membremorale->raison_sociale); ?></td>
      <td><?php echo ($entry->nom_produit); ?></td>
      <td><?php $i = 0; $typeancien = array();
		$offreur_mapper = new Application_Model_EuOffreurProjetMapper();
        $offreur = $offreur_mapper->fetchAllByMembre($entry->code_membre_morale);
        foreach ($offreur as $offreur_entry){
        	if(array_search($offreur_entry->offreur_projet_type, $typeancien) == NULL){
        	$typeancien[$i] = $offreur_entry->offreur_projet_type;
        	$mappertype = new Application_Model_EuTypeOffreurProjetMapper();
			$type = new Application_Model_EuTypeOffreurProjet();
			$mappertype->find($offreur_entry->offreur_projet_type, $type);
        	echo $type->libelle_type_offreur_projet."<br />";
        	}

        $i++;	
        }
       ?></td>
      <td><div align="center"><?php if($entry->produit_special == 1){?><span class="label label-success"><i class="icon-ok icon-white"></i>  Spécial</span><?php }?></div></td>
      <td><div align="center"><?php if($entry->produit_ordinaire == 1){?><span class="label label-success"><i class="icon-ok icon-white"></i>  Ordinaire</span><?php }?></div></td>
      <td><div align="center"><?php if($entry->valider == 3){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/validerdemandeconfigte/id/<?php echo $entry->id_demande; ?>/valider/0"><i class="icon-ok icon-white"></i>  Valider</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/validerdemandeconfigte/id/<?php echo $entry->id_demande; ?>/valider/<?php echo $this->valider; ?>"><i class="icon-off icon-white"></i>  Pas Valider</a>&nbsp;
<?php }?></div></td>
      <td>
	  <div align="center">
	       <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/detaildemandeconfigte/id/<?php echo $entry->id_demande; ?>"><i class="icon-edit icon-white"></i>  Détails</a>
      </div>

          <?php //if($sessionutilisateur->code_groupe == 'executante_acnev') { ?>
	  <div align="center">
	       <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/configte/id/<?php echo $entry->id_demande; ?>"><i class="icon-edit icon-white"></i>Ajouter TE</a>	   
          </div>
          <?php //} ?>
          
	  </td>
      </tr>
<?php endforeach; ?>
</tbody>
					  </table>
                                    <br />

                                    
<br />
<br />
<br />
<?php }else{?>
<div class="alert alert-info">
  Aucune demande de configuration enrégistrée 
</div>
<?php }?>




</div>
<?php /*?><div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div><?php */?>
</div>
</div>








