<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
        
<script type="text/javascript">
function checkAllInput(form, action)
{
   var i = document.forms[form].getElementsByTagName("input"); 
    for ( var cpt = 0; cpt < i.length; cpt++) 
                              i[cpt].checked = (action)? true : false ;
}

//onclick="checkAllInput('form1', true);" //coche
//onclick="checkAllInput('form1', false);" //decoche

</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des souscriptions erronnées</p></blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php }?>
  
<?php if(count($this->entries)>0){?> 
                                    <form method="post" enctype="multipart/form-data" role="form" name="souscription" id="souscription" action="<?php echo $this->baseUrl();?>/administration/publiersouscription">

<div class="accordion" id="accordion2">
<?php foreach ($this->entries as $entry_agence): ?>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?php echo $entry_agence->code_agence; ?>">
        <i class="icon-arrow-right"></i> <?php echo ($entry_agence->libelle_agence); ?>
      </a>
    </div>
    <div id="collapse<?php echo $entry_agence->code_agence; ?>" class="accordion-body collapse in" align="left">
      <div class="accordion-inner">

<?php 
        $souscription = new Application_Model_EuSouscriptionMapper();
        if($sessionutilisateur->code_agence != "001001001001"){
        $entriessouscription = $souscription->fetchAllByPublierErreur($this->publier, $sessionutilisateur->code_agence);
			}else{
        $entriessouscription = $souscription->fetchAllByPublierErreur($this->publier, "");
				}
?>
<?php if(count($entriessouscription)>0){?> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
						  <thead>
							  <tr>
								  <th>OSE/OE</th>
								  <th>Date</th>
								  <th>Nom & prénom(s) / Raison sociale</th>
								  <th>Cellulaire</th>
								  <th>Type</th>
								  <th>Numero</th>
								  <th>Date Numero</th>
								  <th>Programme</th>
								  <th>Nombre</th>
								  <th>Montant</th>
								  <th>Description</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($entriessouscription as $entry): ?>
    <tr <?php if($entry->souscription_ancien_membre != ""){?> class="info"<?php }?>>
      <td><?php 
        $membreasso = new Application_Model_EuMembreasso();
        $membreassoM = new Application_Model_EuMembreassoMapper();
        $membreassoM->find($entry->souscription_membreasso, $membreasso);
	  
        $association = new Application_Model_EuAssociation();
        $associationM = new Application_Model_EuAssociationMapper();
        $associationM->find($membreasso->membreasso_association, $association);
	  echo $association->association_nom;?></td>
      <td><?php echo datejourfr($entry->souscription_date); ?></td>
      <td><?php if($entry->souscription_personne == "PP"){?><?php echo ($entry->souscription_nom); ?> <?php echo ($entry->souscription_prenom); ?><?php }else{?><?php echo ($entry->souscription_raison); ?><?php }?></td>
      <td><?php echo ($entry->souscription_mobile); ?></td>
      <td><?php echo ($entry->souscription_type); ?></td>
      <td><?php echo ($entry->souscription_numero); ?></td>
      <td><?php echo ($entry->souscription_date_numero); ?></td>
      <td><?php echo ($entry->souscription_programme); ?></td>
      <td><?php echo ($entry->souscription_nombre); ?></td>
      <td><?php echo ($entry->souscription_montant); ?></td>
      <td><?php echo ($entry->erreurdescription); ?></td>
      <td><div align="center">
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/detailssouscription/id/<?php echo $entry->souscription_id; ?>"><i class="icon-search icon-white"></i>  Détails</a>&nbsp;

			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/editsouscription/id/<?php echo $entry->souscription_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

	  <?php if($entry->erreur == 1){?>
			<a class="btn btn-mini btn-danger" href="<?php echo $this->baseUrl(); ?>/administration/erreursouscription1/id/<?php echo $entry->souscription_id; ?>/erreur/2"><i class="icon-off icon-white"></i>  Corriger Erreur</a>&nbsp;
<?php }?>
            </div></td>
      
    </tr>
<?php endforeach; ?>

</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun membre enregistré 
</div>
<?php }?>

      </div>
    </div>
  </div>
<?php endforeach; ?>

</div>

                                    <br />
      <input name="id" type="hidden" id="id" value="1" />
      <input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary" style="float:right;">Valider</button>
</form>
<br />
<br />
<br />
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








