<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left">
		
		<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

            <blockquote>
            <p> <strong> LISTE DES ACHATS FOURNISSEUR OU SERVICE <?php if($_POST['date_debut'] == $_POST['date_fin']) { echo " DU ".datejourfr($_POST['date_fin']); } ELSE { echo " DU ".datejourfr($_POST['date_debut'])." AU ".datejourfr($_POST['date_fin']); }  ?>  </strong></p>
            </blockquote>
			
		<div>
	    <form method="post" id="frm_rech_bankacm" action="" class="form-horizontal">
			<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error !="") { ?>
            <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
            </div>
            <?php } ?>


            <?php if(isset($this->error) && $this->error!="") { ?>
            <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php echo $this->error; ?>
            </div>
            <?php } ?>
				
		    <div class="well">
				<div class="row-fluid">
                    <div class="controls span">
                        <div class="controls span8">
                            <input type="text" name="date_debut" id="date_debut"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date début" />    
                        </div>
                    </div>
							
				    <div class="controls span">
                        <div class="controls span8">
                            <input type="text" name="date_fin" id="date_fin"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date fin"/>        
                        </div>
                    </div>
					
					<br/><br/>
							
					<div class="controls">
                        <button id="btn_valider"   class="btn btn-primary">Valider</button>
                        <button type="reset" class="btn">Annuler</button>
                    </div>
                </div>   
			</div>
			</form>
	</div>
			
			
			
			
			<table class="table table-striped table-bordered table-hover table-condensed" id="example0" style="font-size:11px;">
			    <thead>
			        <tr>
					    <th>DATE</th>
					    <th>REFERENCE</th>
						<th>LIBELLE ACHAT</th>
						<th>MONTANT ACHAT</th>
				        <th>NOM & PRENOM / RAISON </th>
						<th>ACTION</th>
			        </tr>
		        </thead>
				
				<?php 
			    if(count($this->entries) > 0)   {
                    					
			    ?>
				
				<tbody>
				    <?php
                        foreach($this->entries as $entry) :
						    $date_demande = new Zend_Date($entry->date_demande,Zend_Date::ISO_8601);
                            $membremorale = new Application_Model_EuMembreMorale();
                            $membremoraleM = new Application_Model_EuMembreMoraleMapper();
					        $membre = new Application_Model_EuMembre();
                            $membreM = new Application_Model_EuMembreMapper();
					        $demandeur = "";
                            if(substr($entry->code_membre, -1) == "P") {
							    $membreM->find($entry->code_membre,$membre);
							    $demandeur = $membre->nom_membre." ".$membre->prenom_membre; 
						    } else {
							    $membremoraleM->find($entry->code_membre,$membremorale);
							    $demandeur = $membremorale->raison_sociale;
						    }

                            $t_imputation = new Application_Model_DbTable_EuImputation();
							$select = $t_imputation->select();
							$select->where('type_operation like ?',"ACHAT");
							$select->where('id_traitement = ?',$entry->id_demande_achat);
							$resultat = $t_imputation->fetchAll($select);
							
					?>
					
				    <tr>
					   <td><?php echo $date_demande->toString('ddMMyyyy'); ?></td>
					   <td><?php echo $entry->reference_demande_achat; ?></td>
					   <td><?php echo $entry->libelle_demande_achat;  ?></td>
					   <td><?php echo $entry->montant_demande_achat; ?></td>
					   <td><?php echo $demandeur;  ?></td>
					    <td>
						    <div align="center">
							    <?php if(count($resultat) > 0) { ?>
								<a class="btn btn-mini btn-success" href=""><i class="icon-ok icon-white"></i>Traité</a>&nbsp;

								<?php } else { ?>
					                <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/addimputachat/id/<?php echo $entry->id_demande_achat; ?>/operation/ACHAT"><i class="icon-edit icon-white"></i>Imputer</a>
						        <?php }  ?>
							</div>
						</td>
					</tr>
					
                    <?php
                        $i++;					
					    endforeach; 
					?>					
				</tbody>
				<?php } ?>
			</table>
    </div>
</div>
</div>