<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des utilisateurs  de </p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Nom & prénom(s)</th>
								  <th>Cellulaire</th>
								  <th>E-mail</th>
								  <th>Login</th>
								  <th>Type</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->membreasso_date); ?></td>
      <td><?php echo ($entry->membreasso_nom); ?> <?php echo ($entry->membreasso_prenom); ?></td>
      <td><?php echo ($entry->membreasso_mobile); ?></td>
      <td><?php echo ($entry->membreasso_email); ?></td>
      <td><?php echo ($entry->membreasso_login); ?></td>
      <td><?php if($entry->membreasso_type == 1){echo "Représentant";}else{echo "Membre";} ?></td>
      <td><div align="center">
	  <?php if($entry->local == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/localmembreasso/id/<?php echo $entry->membreasso_id; ?>/local/0"><i class="icon-ok icon-white"></i>  Accès Local</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/localmembreasso/id/<?php echo $entry->membreasso_id; ?>/local/1"><i class="icon-off icon-white"></i>  Accès Exterieur</a>&nbsp;
<?php }?>
	  
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/detailsmembreasso/id/<?php echo $entry->membreasso_id; ?>"><i class="icon-search icon-white"></i>  Détails</a><?php /*?>&nbsp;

	  <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/association/editmembreasso/id/<?php echo $entry->membreasso_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/association/suppmembreasso/id/<?php echo $entry->membreasso_id; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a><?php */?></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun utilisateur enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








