<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript">		
$(document).ready(function() {
  $('#example').dataTable( {
   "sPaginationType": "full_numbers",
   "aaSorting": []
  });
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Liste des agences</p></blockquote>

<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error !="") { ?>
  <div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
  <?php } ?>


  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
  </div>
  <?php } ?>



<?php if(count($this->entries) > 0) { 

$pays = new Application_Model_EuPays();
$pays_mapper = new Application_Model_EuPaysMapper();

$region = new Application_Model_EuRegion();
$region_mapper = new Application_Model_EuRegionMapper();

$prefecture = new Application_Model_EuPrefecture();
$prefecture_mapper = new Application_Model_EuPrefectureMapper();

$secteur = new Application_Model_EuSecteur();
$secteur_mapper = new Application_Model_EuSecteurMapper();


?>
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
<thead>
	  <tr>
		 <th>Code</th>
		 <th>Nom</th>
		 <th>Pays</th>
		 <th>Région</th>
		 <th>Préfecture</th>
		 <th>Secteur</th>
		 <th>Actions</th>
	  </tr>
</thead>

<tbody>
      <?php 
	     foreach($this->entries as $entry) : 
		   if($entry->id_pays != null) {
			 $pays_mapper->find($entry->id_pays,$pays); 
		   }
		   
           if($entry->id_region != null) {
			  $region_mapper->find($entry->id_region,$region); 
		   }
           
		   if($entry->id_prefecture != null) {
			  $prefecture_mapper->find($entry->id_prefecture,$prefecture); 
		   }
		   
		   if($entry->code_secteur != null) {
			  $secteur_mapper->find($entry->code_secteur,$secteur); 
		   }
		   
	  ?>
	  
      <tr>
	      <td><?php echo $entry->code_agence; ?></td>
		  <td><?php echo $entry->libelle_agence; ?></td>
	      <td><?php echo $pays->libelle_pays; ?></td>
		  <td><?php echo $region->nom_region; ?></td>
		  <td><?php echo $prefecture->nom_prefecture; ?></td>
		  <td><?php echo $secteur->nom_secteur; ?></td>
		  <td>
			  <div align="center">
	               <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/editagence/id/<?php echo $entry->code_agence; ?>"><i class="icon-edit icon-white"></i>Modifier</a>&nbsp;	   
              </div>
		  </td>
	  </tr>
	  <?php endforeach; ?>
      </tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucun enrégistrement 
</div>
<?php } ?>

</div>
</div>
</div>