<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur'); ?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
        "sPaginationType": "full_numbers",
        "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">
<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
<blockquote><p> Liste des Offreurs de Projet </p></blockquote>

<?php if(count($this->entries) > 0 ) { ?>
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
    <thead>
		<tr>
			<th>Souscripteur</th>
			<th>Produits</th>
			<th>CM Souscrits</th>
			<th>Cellulaire</th>
			<th>Zone</th>
			<th>Pays</th>
			<th>Région</th>
			<th>Préfecture</th>
			<th>Canton</th>
		</tr>
	</thead>
	
	
	<tbody>
	
	<?php 
	    $i = 0;
		$tab = array();
	    foreach($this->entries as $entry):
			$trouve = false;
            $depotvente = new Application_Model_EuDepotVente();
	        $m_depotvente = new Application_Model_EuDepotVenteMapper();		
	       
	        $canton = new Application_Model_EuCanton();
	        $m_canton = new Application_Model_EuCantonMapper();
		
		    $prefecture = new Application_Model_EuPrefecture();
	        $m_prefecture = new Application_Model_EuPrefectureMapper();
		
		    $region = new Application_Model_EuRegion();
	        $m_region = new Application_Model_EuRegionMapper();
		
		    $pays = new Application_Model_EuPays();
	        $m_pays = new Application_Model_EuPaysMapper();
		
		    $zone = new Application_Model_EuZone();
	        $m_zone = new Application_Model_EuZoneMapper();
			
			for($k = 0; $k < sizeof($tab); $k++) {
				if($tab[$k] == $entry->code_membre_morale) {
				     $trouve = true;
					 break;
				}
			}
			
			
			$nbrecm = 0;
			$nom_zone = "";
			$libelle_pays = "";
			$nom_region = "";
			$nom_prefecture = "";
			$nom_canton = "";
			
			if($entry->offreur_projet_canton != NULL &&  $entry->offreur_projet_canton != "") {
			    $findcanton = $m_canton->find($entry->id_canton,$canton);
		        $findprefecture = $m_prefecture->find($canton->id_prefecture,$prefecture);
		        $findregion = $m_region->find($prefecture->id_region,$region);
		        $findpays = $m_pays->find($region->id_pays,$pays);
		        $findzone = $m_zone->find($pays->code_zone,$zone);
				
				$nom_zone = $zone->nom_zone;
			    $libelle_pays = $pays->libelle_pays;
			    $nom_region = $region->nom_region;
			    $nom_prefecture = $prefecture->nom_prefecture;
				$nom_canton = $canton->nom_canton;
			}
			
			$finddepotvente = $m_depotvente->fetchAllByMembre($entry->offreur_projet_code_membre);
			if($finddepotvente != NULL) {
				
				 $nbrecm = $m_depotvente->CumulCM($entry->offreur_projet_code_membre)/70000;
				 if($trouve == false) {
	
	?>
	<tr> 
	    <td><?php echo ($entry->raison_sociale); ?></td>
		<td><?php echo ($entry->offreur_projet_produit); ?></td>
		<td><?php echo ($nbrecm); ?></td>
		<td><?php echo ($entry->portable_membre); ?></td>
		<td><?php echo ($nom_zone); ?></td>
		<td><?php echo ($libelle_pays); ?></td>
		<td><?php echo ($nom_region); ?></td>
		<td><?php echo ($nom_prefecture); ?></td>
		<td><?php echo ($nom_canton); ?></td>
	</tr>	
	
    <?php	
				 }}
	  $tab[$i] = $entry->code_membre_morale;
      $i++;	  
	  endforeach; 
	?>
	</tbody>
</table>

<?php } else { ?>
<div class="alert alert-info">
  Aucun Souscripteur Offreur Projet enrégistré 
</div>
<?php } ?>

</div>
<div class="span3">
<?php //include("../application/layouts/scripts/droite_esmc.phtml"); ?>
</div>
</div>
</div>
       










