<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
        "sPaginationType": "full_numbers",
		"aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Liste des notifications</p></blockquote>
<?php if(count($this->entries) > 0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
<thead>
<tr>
    <th>Date</th>
	<th>To </th>
	<th>Titre </th>
	<th>Message</th>
	<th>Message Id</th>
	<th>Error </th>
	<th>Actions</th>
</tr>
</thead> 

 
<tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
        <td><?php echo ($entry->date_notification); ?></td>
		<td><?php echo ($entry->to); ?></td>
		<td><?php echo ($entry->titre); ?></td>
		<td><small><?php echo ($entry->message); ?></small></td>
		<td><?php echo ($entry->message_id); ?></td>
		<td><?php echo ($entry->error); ?></td>
		<td>
		    <div align="center">
		    <?php if($entry->statut == 1) { ?>
		    <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/statutnotification/id/<?php echo $entry->id_notification; ?>/statut/0"> <i class="icon-ok icon-white">  </i> Activé </a>&nbsp;
                    <?php } else { ?>
		    <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/statutnotification/id/<?php echo $entry->id_notification; ?>/statut/1"> <i class="icon-off icon-white"> </i> Désactivé </a>&nbsp;
                    <?php } ?>
		    <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/editnotification/id/<?php echo $entry->id_notification; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;
		    <a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/administration/suppnotification/id/<?php echo $entry->id_notification; ?>'"><i class="icon-trash icon-white"></i>Supprimer</a>
		    </div>
		</td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucune notification enrégistrée
</div>
<?php } ?>


</div>
</div>
</div>








