<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
    "aaSorting": []
    } );
} );
    </script>
       

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Tableau de bord des Bons d'Achats neutres BAn </p></blockquote>

<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Formulaire de trie par critères
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse <?php if (!isset($_POST['ok'])) {?> in <?php }?>">
      <div class="accordion-inner">
<form method="post" enctype="multipart/form-data" role="form" name="souscription" id="souscription" action="" class="">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php } ?>
  
   
  <div class="">

  <div class="span4">
    
  <div class="control-group">
  <label class="control-label" for="bon_neutre_detail_banque">Banque </label>
  <div class="controls">
  <select name="bon_neutre_detail_banque" id="bon_neutre_detail_banque" >
    <?php $tbanque = new Application_Model_DbTable_EuBanque();
        $results = $tbanque->fetchAll();?>
    <option value="">Choisir la banque</option>
    <?php foreach ($results as $banque): ?>
    <option value="<?php echo $banque->code_banque; ?>"><?php echo ($banque->libelle_banque); ?></option>
    <?php endforeach; ?>
  </select>
  </div>
  </div>
    
    <div class="control-group">
  <label class="control-label" for="bon_neutre_detail_montant1">Montant minimum  </label>
  <div class="controls">
    <input type="number" name="bon_neutre_detail_montant1" id="bon_neutre_detail_montant1" placeholder="Montant minimum" class="input-medium" />
  </div>
  </div>
  

  <div class="control-group">
  <label class="control-label" for="bon_neutre_detail_montant2">Montant maximum  </label>
  <div class="controls">
    <input type="number" name="bon_neutre_detail_montant2" id="bon_neutre_detail_montant2" placeholder="Montant maximum" class="input-medium" />
  </div>
  </div>
    
    </div>


  <div class="span4">
    
  
    
    <div class="control-group">
  <label class="control-label" for="bon_neutre_code_membre">Code Membre  </label>
  <div class="controls">
    <input type="text" name="bon_neutre_code_membre" id="bon_neutre_code_membre" placeholder="Code Membre" class="input-medium" />
  </div>
  </div>
  


    <div class="control-group">
  <label class="control-label" for="bon_neutre_detail_date1">Date Début  </label>
  <div class="controls">
    <input type="text" name="bon_neutre_detail_date1" id="bon_neutre_detail_date1" placeholder="Date Début" class="input-medium datepicker" data-provide="datepicker" value="<?php 
                        $eubon = new Application_Model_DbTable_EuBonNeutreDetail();
                        $select = $eubon->select();
                        $select->order(array('bon_neutre_detail_date ASC'));
                        $select->limit(1);
                        $rowseubon = $eubon->fetchRow($select);
                        echo substr($rowseubon->bon_neutre_detail_date, 0, 10); ?>" readonly />
  </div>
  </div>
  

  <div class="control-group">
  <label class="control-label" for="bon_neutre_detail_date2">Date Fin  </label>
  <div class="controls">
    <input type="text" name="bon_neutre_detail_date2" id="bon_neutre_detail_date2" placeholder="Date Fin" class="input-medium datepicker" data-provide="datepicker" value="<?php 
                        $eubon = new Application_Model_DbTable_EuBonNeutreDetail();
                        $select = $eubon->select();
                        $select->order(array('bon_neutre_detail_date DESC'));
                        $select->limit(1);
                        $rowseubon = $eubon->fetchRow($select);
                        echo substr($rowseubon->bon_neutre_detail_date, 0, 10); ?>" readonly />
  </div>
  </div>


  <div class="control-group">
  <label class="control-label" for="bon_neutre_tiers_id">Bon d'Achat neutre pour tiers </label>
  <div class="controls">
  <select name="bon_neutre_tiers_id" id="bon_neutre_tiers_id" >
    <option value="0">Non</option>
    <option value="1">Oui</option>
  </select>
  </div>
  </div>
    
    </div>

  <div class="span4">
  
    <div class="control-group">
  <label class="control-label" for="id_region">R&eacute;gion du souscripteur  </label>
  <div class="controls">
  <select name ="id_region" id="id_region" onchange="ouvre_decoupage(this.value);">
    <?php  $region_mapper = new Application_Model_EuRegionMapper();
        $selectregions = $region_mapper->fetchAll();?>
    <option value="">Choisir la région </option>
    <?php foreach ($selectregions as $selectregion): ?>
    <option value="<?php echo $selectregion->id_region; ?>"><?php echo $selectregion->nom_region; ?></option>
    <?php endforeach; ?>
  </select>
  </div>
  </div>
    
  <div id="nivpref">
  <div class="control-group">
  <label class="control-label" for="id_prefecture">Pr&eacute;fecture du souscripteur </label>
  <div class="controls">
  <select name="id_prefecture" id="id_prefecture" >
    <option value="">Choisir la Pr&eacute;fecture</option>
  </select>
  </div>
  </div>
  </div>
    
    
  <div id="nivcant">
  <div class="control-group">
  <label class="control-label" for="id_canton">Canton du Souscripteur </label>
  <div class="controls">
  <select name="id_canton" id="id_canton" >
    <option value="">Choisir le canton </option>
  </select>
  </div>
  </div>
  </div>
    
  
 
    </div>
    </div>
    
 <div class="">
  <div class="span12">
   
<div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<!--<button type="reset" class="btn">Annuler</button>-->
<button type="submit" class="btn btn-primary">Rechercher</button>
</div>    

    </div>
    </div>

</form>


      </div>
    </div>
  </div>
  
</div>



<?php  if(count($this->entries)>0){?> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Nom & prénom(s) / Raison sociale</th>
                  <th>Code Membre</th>
                  <th>Montant versé</th>
                  <th>Montant utilisé</th>
                  <th>Montant solde</th>
                  <th>Banque</th>
                  <th>Canton</th>
                  <th>Actions</th>
                </tr>
              </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datejourfr($entry->bon_neutre_detail_date); ?></td>
      <?php $bon = new Application_Model_EuBonNeutre();
          $m_bon = new Application_Model_EuBonNeutreMapper();
          $m_bon->find($entry->bon_neutre_id, $bon);
      if (substr($bon->bon_neutre_code_membre, -1) == "P") {
          $m_membre = new Application_Model_EuMembreMapper();
          $membre = new Application_Model_EuMembre();
          $m_membre->find($bon->bon_neutre_code_membre, $membre);
          $designation = $membre->nom_membre." ".$membre->prenom_membre;
          }else if (substr($bon->bon_neutre_code_membre, -1) == "M") {
          $m_membre = new Application_Model_EuMembreMoraleMapper();
          $membre = new Application_Model_EuMembreMorale();
          $m_membre->find($bon->bon_neutre_code_membre, $membre);
          $designation = $membre->raison_sociale;
          }else{
          $designation = "";  
            } ?>
      <td><?php echo ($designation); ?></td>
      <td><?php echo ($bon->bon_neutre_code_membre); ?></td>
      <td><div align="right"><?php echo number_format($entry->bon_neutre_detail_montant, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format($entry->bon_neutre_detail_montant_utilise, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format($entry->bon_neutre_detail_montant_solde, 0, ',', ' '); ?></div></td>
      <td><?php echo ($entry->bon_neutre_detail_banque); ?></td>
      <td><?php  $canton = new Application_Model_EuCanton();
      $canton_mapper = new Application_Model_EuCantonMapper();
      $canton_mapper->find($entry->id_canton, $canton);
      echo $canton->nom_canton;?></td>
      <td><div align="center">&nbsp;</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
<tfoot>
<tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      
    </tr>
<tr>
      <td><strong>Nombre</strong> :</td>
      <td><strong><?php echo count($this->entries); ?></strong></td>
      <td><strong>Total</strong> : </td>
      <td><div align="right"><strong><?php echo number_format($this->entriestotal["MONTANT"], 0, ',', ' '); ?></strong></div></td>
      <td><div align="right"><strong><?php echo number_format($this->entriestotal["UTILISE"], 0, ',', ' '); ?></strong></div></td>
      <td><div align="right"><strong><?php echo number_format($this->entriestotal["SOLDE"], 0, ',', ' '); ?></strong></div></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><div align="center">&nbsp;</div></td>
      
    </tr>
</tfoot>
            </table>
                      <br />


<br />
<br />
<?php }else{?>
<div class="alert alert-info">
  Aucun membre enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








