<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des contrats archivés<!--dossiers d'appels d'offres--></p></blockquote>
<?php /*?><?php 
            $table = new Application_Model_DbTable_EuAppeloffres();
$select = $table->select(Zend_Db_Table::SELECT_WITH_FROM_PART);
        $select->setIntegrityCheck(false);
		$select->join('eu_utilisateur', 'eu_utilisateur.id_utilisateur = eu_appeloffres.id_utilisateur');
		$select->join('eu_acteur', 'eu_acteur.code_acteur = eu_utilisateur.code_acteur');
		
		$select->where("(eu_appeloffres.selection = ? ", 1);
		$select->where("eu_appeloffres.id_document IN (SELECT id_document FROM eu_document WHERE accord <= 2))");
		
		
		
		$select->orwhere("(eu_appeloffres.selection = ? ", 0);
		$select->where("eu_appeloffres.id_document IN (SELECT id_document FROM eu_document WHERE accord <= 1))");
		
		
		
		$select->order(array("eu_appeloffres.id_document DESC", "eu_appeloffres.date_appeloffres DESC"));
        $resultSet = $table->fetchAll($select);
		echo $select; ?><?php */?>
<?php if(count($this->entries)>0){?> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Canevas</th>
								  <th>Numero</th>
								  <th>Libellé</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php $date_id = new Zend_Date(Zend_Date::ISO_8601);
$documentM = new Application_Model_EuDocumentMapper();
$document = new Application_Model_EuDocument();
$documentM->find3($entry->id_document, $document);
?><?php echo htmlentities($document->nom_document); ?></td>
      <td><?php if($entry->preselection == 1 && $entry->selection == 1){?>
	  <span class="label label-mini label-important"><?php echo htmlentities($entry->num_appeloffres); ?></span>
	  <?php }else{?><?php echo htmlentities($entry->num_appeloffres); ?><?php }?>
      </td>
      <td><?php echo htmlentities($entry->libelle_appeloffres); ?></td>
      <td><div align="center">
      <?php //if(($document->date_fin <= $date_id->toString('yyyy-MM-dd'))){?>
      <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/<?php echo $entry->desc_appeloffres; ?>"><i class="icon-download icon-white"></i>  Télécharger</a>&nbsp;

	  <?php if($entry->preselection == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/preselectionappeloffres3/id/<?php echo $entry->id_appeloffres; ?>/preselection/0"><i class="icon-ok icon-white"></i>  Pré-selectionné</a>&nbsp;

	  <?php if($entry->selection == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/selectionappeloffres3/id/<?php echo $entry->id_appeloffres; ?>/selection/0"><i class="icon-ok icon-white"></i>  Selectionné</a>&nbsp;

	  <?php if($entry->okfinal == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/administration/okfinalappeloffres3/id/<?php echo $entry->id_appeloffres; ?>/okfinal/0"><i class="icon-ok icon-white"></i>  Choisie</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/okfinalappeloffres3/id/<?php echo $entry->id_appeloffres; ?>/okfinal/1"><i class="icon-off icon-white"></i>  Pas Choisie</a>&nbsp;
<?php }?>

<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/selectionappeloffres3/id/<?php echo $entry->id_appeloffres; ?>/selection/1"><i class="icon-off icon-white"></i> Pas  Selectionné</a>&nbsp;
<?php }?>

<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/administration/preselectionappeloffres3/id/<?php echo $entry->id_appeloffres; ?>/preselection/1"><i class="icon-off icon-white"></i>  Pas Pré-selectionné</a>&nbsp;
<?php }?>


			<?php //}?>

      
      		<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/editappeloffres3/id/<?php echo $entry->id_appeloffres; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/administration/suppappeloffres3/id/<?php echo $entry->id_appeloffres; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a>
            </div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun contrat<!--dossier d'appel d'offre--> enrégistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








