<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$('#example').dataTable();
			} );
			/*$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []*/
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des quinzaines des offreurs de projets</p></blockquote>

<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Jour</th>
								  <th>Mois</th>
								  <th>Année</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
<?php 
// Configuration du fuseau horaire. Disponible depuis PHP 5.1
date_default_timezone_set('Europe/London');

$mois = $entry['MOIS'];
$annee = $entry['ANNEE'];

$lastday = strftime("%Y%m%d",mktime(0,0,0,$mois+1,0,$annee));
$firstday = strftime("%Y%m%d",mktime(0,0,0,$mois,1,$annee));

$mois15 = strftime("%Y%m%d",mktime(0,0,0,$mois,15,$annee));

$jour1 = 01;
$jour15 = 15;
$jour16 = 16;
$jourlast = strftime("%d",mktime(0,0,0,$mois+1,0,$annee));
?>
    <tr>
      <td><?php echo ($jour15); ?></td>
      <td><?php echo moisfr($mois); ?></td>
      <td><?php echo ($annee); ?></td>
      <td><div align="center">
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/etatoffreurprojet/debut/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-0<?php echo $jour1; ?>/fin/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour15; ?>"><i class="icon-search icon-white"></i>  Etats par Agréments OSE/OE</a>&nbsp;
      </div></td>
    </tr>
    <tr>
      <td><?php echo ($jourlast); ?></td>
      <td><?php echo moisfr($mois); ?></td>
      <td><?php echo ($annee); ?></td>
      <td><div align="center">
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/administration/etatoffreurprojet/debut/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jour16; ?>/fin/<?php echo $annee; ?>-<?php echo ajoute1zero($mois); ?>-<?php echo $jourlast; ?>"><i class="icon-search icon-white"></i>  Etats par Agréments OSE/OE</a>&nbsp;
      </div></td>
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun offreur de projet enrégistré 
</div>
<?php }?>
<br />
<br />
<br />




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








