<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml");?>


<blockquote><p> Recharge par TMONEY ou par FLOOZ </p></blockquote>

  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
  </div>
  <?php } ?>

              
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription1" name="addagence">
<fieldset>
<legend> Remplir le formulaire </legend>


    
<div class="control-group">
<label class="control-label" for="operateur">Opérateur *</label>
<div class="controls">
     <select class="input-xlarge" id="operateur" name="operateur" required>
       <option value="">Choisir un opérateur</option>
       <option value="TMONEY">TMONEY</option>                         
       <option value="FLOOZ">FLOOZ</option>                         
     </select>
</div>
</div>

  
  
<div class="control-group">
<label class="control-label" for="montant">Montant à payer * </label>
<div class="controls">
     <input type="number" name="montant" id="montant" placeholder="Montant à payer" class="input-xlarge" required />
</div>
</div>



</fieldset>
<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Recharger</button>
</div> 
</form>

</div>

</div>
</div>








