<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>

<script type="text/javascript" charset="utf-8">			
$(document).ready(function() {
    $('#example').dataTable({
      "sPaginationType": "full_numbers",
      "aaSorting": []
    });
});
</script>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
     <blockquote><p class="text-info">Règlement des credits RPG/I</p></blockquote>
	 
<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="ancienpp">
      
	<?php if(isset($sessionutilisateur->errorlogin) && $sessionutilisateur->errorlogin!="") { ?>
    <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->errorlogin; $sessionutilisateur->errorlogin = ""; ?>
    </div>
    <?php } ?>
    <?php if(isset($this->message) && $this->message!="") { ?>
    <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->message; ?>
    </div>
    <?php } ?>
	
	<legend>Règlement des credits RPG/I</legend>
	<div class="control-group">
      	<?php if (isset($_POST['code_membre']) && $_POST['code_membre']!="" && isset($this->code_membre)) { 
	        $x =1;
            $compteur=0;
	    ?>
        <label class="control-label" for="code_membre">Ancien Code Membre *</label>
            <div class="controls">
               <input type="text" name="membre" id="membre" placeholder="Ancien Code Membre" value="<?php echo $this->code_membre; ?>" readonly required>
	        </div>
            <br/>
            <br/>
			<table class="table table-striped table-bordered table-hover table-condensed" id="example">
			    <thead>
	                <tr>
					    <th>#</th>
						<th><div align="left">N°Credit</div></th>
						<th><div align="left">Produit</div></th>
						<th><div align="left">Distributeur</div></th>
						<th><div align="left">Montant</div></th>
					</tr>
		        </thead>
				<tbody>
				    <?php foreach ($this->gcps as $entry): ?>
					<tr>
					    <td><div><input type="checkbox" name="<?php echo "gcp".$x ?>" id="<?php echo "gcp".$x ?>" value="<?php echo $entry->id_gcp;?>"/></div></td>
						<td><div align="left"><?php echo $entry->id_credit;?></div></td>
						<td><div align="left"><?php echo $entry->code_produit;?></div></td>
						<td><div align="left"><?php echo $entry->code_membre;?></div></td>
						<td><div align="left"><?php echo $entry->mont_gcp;?></div></td>
					</tr>
				    <?php 
			            $x++;
						$compteur++;
						endforeach; 
			        ?>
					<tr>
			            <td colspan="5">
		                <div align="center">
                           <input type="hidden" name="compteur" value="<?php echo $compteur ?>"/>
                           <input name="ok1" type="hidden" id="ok1" value="ok1"/>
                           <button type="submit" class="btn btn-success">Regler</button>
		                </div>
			            </td>   
		   	</tr>
					
				</tbody>
		    </table>
		<?php } else { ?>
		    <label class="control-label" for="code_membre">Ancien Code Membre *</label>
            <div class="controls">
            <input  type="text"   name="code_membre" id="code_membre" placeholder="Ancien Code Membre" value="<?php echo $this->code_membre; ?>" required>
            <input  name="ok"     type="hidden" id="ok" value="ok" />
            <button type="submit" class="btn btn-primary">Valider</button>
            </div>
	    <?php } ?>
	</div> 
</form>
</div>
<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>