<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>        
<script type="text/javascript">
function checkAllInput(form, action) {
   var i = document.forms[form].getElementsByTagName("input"); 
    for( var cpt = 0; cpt < i.length; cpt++) 
        i[cpt].checked = (action)? true : false ;
}

</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p> Règlement Engagement Livraison Irrévocable (ELI) </p></blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php } ?>
  
  
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; $this->error = ""; ?>
    </div>
  <?php } ?>
  

<form method="post" enctype="multipart/form-data" role="form" name="reglereli" id="reglereli" action=""> 
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
  <thead>
	     <tr>
			 <th> DETAILS : <?php echo "ENGAGEMENT DE LIVRAISON IRREVOCABLE N° ".$this->eli->numero_eli." du ".datejourfr($this->eli->date_eli); ?></th> 
	     </tr>
  </thead>
</table>

<div class="control-group">
<label class="control-label" for="">Numero ELI *</label>
<div class="controls">
<input type="text" name="numero_eli" id="numero_eli" class="input-xxlarge" placeholder="Numero ELI" value="<?php if(isset($this->eli)) echo $this->eli->numero_eli;?>"  readonly />
</div>
</div>

<div class="control-group">
<label class="control-label" for=""> Libellé ELI *</label>
<div class="controls">
<input type="text" name="libelle_eli" id="libelle_eli" class="input-xxlarge" placeholder="Libelle ELI" value="<?php if(isset($this->eli)) echo $this->eli->libelle_eli;?>"  readonly />
</div>
</div>
<div class="control-group">
<label class="control-label" for="">Montant ELI *</label>
<div class="controls">
<input type="text" name="montant_eli" id="montant_eli" class="input-xxlarge" placeholder="Montant ELI" value="<?php if(isset($this->eli)) echo $this->eli->montant_eli;?>"  readonly />
<input type="hidden" name="id_eli" id="id_eli" value="<?php if(isset($this->eli)) echo $this->eli->id_eli;?>" />
</div>
</div>

<?php if($this->eli->montant_ban > 0 ) { ?>
<div class="control-group">
<label class="control-label" for="">Montant BAn *</label>
<div class="controls">
<input type="text" name="montant_ban" id="montant_ban" class="input-xxlarge" placeholder="Montant BAn" value="<?php if(isset($this->eli)) echo $this->eli->montant_ban;?>"  readonly />
</div>
</div>
<?php } ?>

<?php if($this->eli->montant_bai > 0 ) { ?>
<div class="control-group">
<label class="control-label" for="">Montant BAi *</label>
<div class="controls">
<input type="text" name="montant_bai" id="montant_bai" class="input-xxlarge" placeholder="Montant BAi" value="<?php if(isset($this->eli)) echo $this->eli->montant_bai;?>"  readonly />
</div>
</div>
<?php } ?>

<?php if($this->eli->montant_opi > 0 ) { ?>
<div class="control-group">
<label class="control-label" for="">Montant OPI *</label>
<div class="controls">
<input type="text" name="montant_opi" id="montant_opi" class="input-xxlarge" placeholder="Montant OPI" value="<?php if(isset($this->eli)) echo $this->eli->montant_opi;?>"  readonly />
</div>
</div>
<?php } ?>



<input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary" style="float:right;">Regler</button>
</form>

</div>
</div>
</div>
