<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left">
		
		<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

            <blockquote>
            <p> <strong> JOURNAUX RELATIFS AUX OPI RESTANT A APURER <?php if($_POST['date_debut'] == $_POST['date_fin']) { echo " DU ".datejourfr($_POST['date_fin']); } ELSE { echo " DU ".datejourfr($_POST['date_debut'])." AU ".datejourfr($_POST['date_fin']); }  ?>  </strong></p>
            </blockquote>
			
			<div>
	    <form method="post" id="frm_rech_bankacm" action="" class="form-horizontal">
			<?php if (isset($this->message) && $this->message != "") { ?>
                <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php
                echo $this->message;$this->message = "";
            ?>
            </div>
            <?php } ?>
				
		    <div class="well">
				<div class="row-fluid">
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label span4">Date début</label>
                            <div class="controls span8">
                                <input type="text" name="date_debut" id="date_debut"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date début" />    
                            </div>
                        </div>
                    </div>
							
				    <div class="span4">
                        <div class="control-group">
                            <label class="control-label span4">Date fin</label>
                            <div class="controls span8">
                                <input type="text" name="date_fin" id="date_fin"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date fin"/>        
                            </div>
                        </div>
                    </div>
							
					<div class="controls">
                        <button id="btn_valider"   class="btn btn-primary">Valider</button>
                        <button type="reset" class="btn">Annuler</button>

<?php if(isset($_POST['date_debut'])) { ?>
<a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/administration/tbdopimaturexcel/date_debut/<?php echo $_POST['date_debut'];?>/date_fin/<?php echo $_POST['date_fin']; ?>">Exporter en Excel</a>
<?php }  ?>
</div>
                </div>   
			</div>
			</form>
	</div>
			
			
			
			
			<table class="table table-striped table-bordered table-hover table-condensed" id="example0" style="font-size:11px;">
			    <thead>
			        <tr>
					    <th>JOUR</th>
					    <th>N°PIECE</th>
						<th>N°FACTURE</th>
						<th>REFERENCE</th>
				        <th>N°COMPTE GENERAL</th>
						<th>N°COMPTE TIERS</th>
				        <th>LIBELLE ECRITURE</th>
					    <th>DATE</th>
					    <th>DEBIT</th>
						<th>CREDIT</th>
			        </tr>
		        </thead>
				
				<?php 
			    if(count($this->entries) > 0) {
                    $i = 1;	
                    					
			    ?>
				
				<tbody>
				    <?php
                        foreach($this->entries as $entry) :
						
						    $date_echeance = new Zend_Date($entry->traite_date_fin,Zend_Date::ISO_8601);
							$designation_membre = "";
                            $portable = "";				
				            if(substr($entry->code_membre, -1) == "P") {
                                $membre = new Application_Model_EuMembre();
                                $membreM = new Application_Model_EuMembreMapper();
                                $membreM->find($entry->code_membre, $membre);
                                $designation_membre = $membre->nom_membre." ".$membre->prenom_membre;
					            $portable = $membre->portable_membre;
                            } else if(substr($entry->code_membre, -1) == "M") {
                                $membre = new Application_Model_EuMembreMorale();
                                $membreM = new Application_Model_EuMembreMoraleMapper();
                                $membreM->find($entry->code_membre, $membre);
                                $designation_membre = $membre->raison_sociale;
					            $portable = $membre->portable_membre;
                            }
                     							
					?>
					
					<?php if($entry->ntf == 12) { ?>
				    <tr>
					   <td> <?php echo $date_echeance->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNALOPIRESTANT".$date_echeance->toString('ddMMyyyy').$i; ?> </td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php  echo "402202"; ?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "OPI RESTANT A APURER DE ".$designation_membre; ?></div></td>
					   <td><?php echo $date_echeance->toString('ddMMyyyy');?></td>
					   <td><div align="left"><?php echo $entry->traite_montant; ?></div></td>
					   <td>&nbsp;</td>
					</tr>
					
					<tr>
					   <td> <?php echo $date_echeance->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNALOPIRESTANT".$date_echeance->toString('ddMMyyyy').$i; ?> </td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "52".$entry->mode_paiement;?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "OPI RESTANT A APURER DE ".$designation_membre;  ?></div></td>
					   <td><?php echo $date_echeance->toString('ddMMyyyy');?></td>
					   <td>&nbsp;</td>
					   <td><div align="left"><?php echo $entry->traite_montant; ?></div></td>
					</tr>
					<?php } else if($entry->ntf == 23) { ?>
					
					<tr>
					   <td> <?php echo $date_echeance->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNALOPIRESTANT".$date_echeance->toString('ddMMyyyy').$i; ?> </td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php  echo "1681001181"; ?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "OPI RESTANT A APURER DE ".$designation_membre; ?></div></td>
					   <td><?php echo $date_echeance->toString('ddMMyyyy');?></td>
					   <td><div align="left"><?php echo $entry->traite_montant; ?></div></td>
					   <td>&nbsp;</td>
					</tr>
					
					<tr>
					   <td> <?php echo $date_echeance->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNALOPIRESTANT".$date_echeance->toString('ddMMyyyy').$i; ?> </td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "402202";?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "OPI RESTANT A APURER DE ".$designation_membre;  ?></div></td>
					   <td><?php echo $date_echeance->toString('ddMMyyyy');?></td>
					   <td>&nbsp;</td>
					   <td><div align="left"><?php echo $entry->traite_montant; ?></div></td>
					</tr>
					
					
					<tr>
					   <td> <?php echo $date_echeance->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNALOPIRESTANT".$date_echeance->toString('ddMMyyyy').$i; ?> </td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php  echo "402202"; ?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "OPI RESTANT A APURER DE ".$designation_membre; ?></div></td>
					   <td><?php echo $date_echeance->toString('ddMMyyyy');?></td>
					   <td><div align="left"><?php echo $entry->traite_montant; ?></div></td>
					   <td>&nbsp;</td>
					</tr>
					
					<tr>
					   <td> <?php echo $date_echeance->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNALOPIRESTANT".$date_echeance->toString('ddMMyyyy').$i; ?> </td>
					   <td>&nbsp;</td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "52".$entry->mode_paiement;?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo "OPI RESTANT A APURER DE ".$designation_membre;  ?></div></td>
					   <td><?php echo $date_echeance->toString('ddMMyyyy');?></td>
					   <td>&nbsp;</td>
					   <td><div align="left"><?php echo $entry->traite_montant; ?></div></td>
					</tr>
					
					<?php } ?>
					
                    <?php
                        $i++;					
					    endforeach; 
					?>					
				</tbody>
				<?php } ?>
			</table>
    </div>
</div>
</div>