<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
$(document).ready(function() {
  $('#example').dataTable({
    "sPaginationType": "full_numbers",
    "aaSorting": []
  }); 
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align: left">
		
		<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

            <blockquote>
            <p> <strong> JOURNAUX RELATIFS AU REGLEMENT DE FACTURE <?php if($_POST['date_debut'] == $_POST['date_fin']) { echo " DU ".datejourfr($_POST['date_fin']); } ELSE { echo " DU ".datejourfr($_POST['date_debut'])." AU ".datejourfr($_POST['date_fin']); }  ?>  </strong></p>
            </blockquote>
			
			<div>
	    <form method="post" id="frm_rech_bankacm" action="" class="form-horizontal">
			<?php if (isset($this->message) && $this->message != "") { ?>
                <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php
                echo $this->message;$this->message = "";
            ?>
            </div>
            <?php } ?>
				
		    <div class="well">
				<div class="row-fluid">
                    <div class="controls span">
                        <div class="controls span8">
                            <input type="text" name="date_debut" id="date_debut"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date début" />    
                        </div>
                    </div>
							
				    <div class="controls span">
                        <div class="controls span8">
                            <input type="text" name="date_fin" id="date_fin"  class="input-large datepicker" data-provide="datepicker"  placeholder="Date fin"/>        
                        </div>
                    </div>
					
					<div class="controls span">
                        <div class="controls span12">
						    <select name="code_banque" id="code_banque" class="input-large">
                                <option value="">Choisir une mode de paiement</option>
                                    <?php foreach ($this->banques as $value) { ?>
                                <option
                                    value="<?php echo $value->code_banque; ?>"><?php echo $value->libelle_banque; ?>
                                </option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
					
					<br/><br/>
							
					<div class="controls">
                        <button id="btn_valider"   class="btn btn-primary">Valider</button>
                        <button type="reset" class="btn">Annuler</button>

                        <?php if(isset($_POST['date_debut'])) { ?>
                          <a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/administration/tbdrgmfactexcel/date_debut/<?php echo $_POST['date_debut']; ?>/date_fin/<?php echo $_POST['date_fin']; ?>/code_banque/<?php echo $this->code_banque;?>">Exporter en Excel</a>
                        <?php }  ?>
                    </div>
                </div>   
			</div>
			</form>
	</div>
			
			
			
			
			<table class="table table-striped table-bordered table-hover table-condensed" id="example0" style="font-size:11px;">
			    <thead>
			        <tr>
					    <th>JOUR</th>
					    <th>N°PIECE</th>
						<th>N°FACTURE</th>
						<th>REFERENCE</th>
				        <th>N°COMPTE GENERAL</th>
						<th>N°COMPTE TIERS</th>
				        <th>LIBELLE ECRITURE</th>
					    <th>DATE</th>
					    <th>DEBIT</th>
						<th>CREDIT</th>
			        </tr>
		        </thead>
				
				<?php 
			    if(count($this->entries) > 0) {
                    $i = 1;	
                    					
			    ?>
				
				<tbody>
				    <?php
                        foreach($this->entries as $entry) :
						    $date_imputation = new Zend_Date($entry->date_imputation,Zend_Date::ISO_8601);					
					?>
					
				    <tr>
					   <td><?php echo $date_imputation->toString('dd'); ?> </td>
					   <td><?php echo "JOURNAL".$entry->type_operation.$date_imputation->toString('ddMMyyyy').$i; ?> </td>
					   <td><div align=""><?php echo $entry->id_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->numero_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->num_compte_debit1;?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo $entry->libelle_imputation; ?></div></td>
					   <td><?php echo $date_imputation->toString('ddMMyyyy');?></td>
					   <td><div align="left"><?php echo $entry->montant_imputation; ?></div></td>
					   <td>&nbsp;</td>
					</tr>
					
					<tr>
					   <td> <?php echo $date_imputation->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNAL".$entry->type_operation.$date_imputation->toString('ddMMyyyy').$i;?> </td>
					   <td><div align=""><?php echo $entry->id_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->numero_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->num_compte_credit1; ?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo $entry->libelle_imputation;  ?></div></td>
					   <td><?php echo $date_imputation->toString('ddMMyyyy');?></td>
					   <td>&nbsp;</td>
					   <td><div align="left"><?php echo $entry->montant_imputation; ?></div></td>
					</tr>
					
					
					<tr>
					   <td> <?php echo $date_imputation->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNAL".$entry->type_operation.$date_imputation->toString('ddMMyyyy').$i; ?> </td>
					   <td><div align=""><?php echo $entry->id_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->numero_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->num_compte_debit2;?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo $entry->libelle_imputation; ?></div></td>
					   <td><?php echo $date_imputation->toString('ddMMyyyy');?></td>
					   <td><div align="left"><?php echo $entry->montant_imputation; ?></div></td>
					   <td>&nbsp;</td>
					</tr>
					
					
					<tr>
					   <td> <?php echo $date_imputation->toString('dd'); ?> </td>
					   <td> <?php echo "JOURNAL".$entry->type_operation.$date_imputation->toString('ddMMyyyy').$i;?> </td>
					   <td><div align=""><?php echo $entry->id_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->numero_facture_prestation;?></div></td>
					   <td><div align=""><?php echo $entry->num_compte_credit2;?></div></td>
					   <td>&nbsp;</td>
					   <td><div align=""><?php echo $entry->libelle_imputation;  ?></div></td>
					   <td><?php echo $date_imputation->toString('ddMMyyyy');?></td>
					   <td>&nbsp;</td>
					   <td><div align="left"><?php echo $entry->montant_imputation; ?></div></td>
					</tr>
					
                    <?php
                        $i++;					
					    endforeach; 
					?>					
				</tbody>
				<?php } ?>
			</table>
    </div>
</div>
</div>