<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
<div class="alert alert-error">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
</div>
<?php } ?>






