<?php $sessionsouscription = new Zend_Session_Namespace('souscription');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menutiers.phtml"); ?>

  <blockquote><p>Liste des caractéristiques</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Libellé</th>
								  <th>Description</th>
								  <th>Type</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->caracteristique_date); ?></td>
      <td><?php echo ($entry->caracteristique_libelle); ?></td>
      <td><?php echo ($entry->caracteristique_description); ?></td>
      <td><div align="center"><?php 
$caracteristiquecodeM = new Application_Model_EuTypeCaracteristiqueMapper();
$caracteristiquecode = new Application_Model_EuTypeCaracteristique();
$caracteristiquecodeM->find($entry->caracteristique_type, $caracteristiquecode);
?><?php echo ($caracteristiquecode->libelle_type_caracteristique); ?></div></td>
      <td><div align="center">
      <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/souscription/editcaracteristique/id/<?php echo $entry->caracteristique_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini btn-danger" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir supprimer?')) location='<?php echo $this->baseUrl(); ?>/souscription/suppcaracteristique/id/<?php echo $entry->caracteristique_id; ?>'"><i class="icon-trash icon-white"></i>  Supprimer</a></div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune caractéristique enrégistrée 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








