<?php $sessionsouscription = new Zend_Session_Namespace('souscription');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menutiers.phtml"); ?>

  <blockquote><p>Liste de mes souscriptions </p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Nom & prénom(s) / Raison sociale</th>
								  <th>Cellulaire</th>
								  <th>Type</th>
								  <th>Numero</th>
								  <th>Date Numero</th>
								  <th>Programme</th>
								  <th>Nombre</th>
								  <th>Montant</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->souscription_date); ?></td>
      <td><?php if($entry->souscription_personne == "PP"){?><?php echo ($entry->souscription_nom); ?> <?php echo ($entry->souscription_prenom); ?><?php }else{?><?php echo ($entry->souscription_raison); ?><?php }?></td>
      <td><?php echo ($entry->souscription_mobile); ?></td>
      <td><?php echo ($entry->souscription_type); ?></td>
      <td><?php echo ($entry->souscription_numero); ?></td>
      <td><?php echo ($entry->souscription_date_numero); ?></td>
      <td><?php echo ($entry->souscription_programme); ?></td>
      <td><?php echo ($entry->souscription_nombre); ?></td>
      <td><?php echo ($entry->souscription_montant); ?></td>
      <td><div align="center">
			<?php /*?><a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/souscription/addmembretiers/id/<?php echo $entry->souscription_id; ?>"><i class="icon-search icon-white"></i>  Ajouter un membre tiers</a>&nbsp;<?php */?>

	  <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/souscription/listmembretiers/id/<?php echo $entry->souscription_id; ?>"><i class="icon-edit icon-white"></i>  Liste des membres tiers</a>
      </div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucune souscription enrégistrée 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








