<?php $sessionsouscription = new Zend_Session_Namespace('souscription');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menutiers.phtml"); ?>

  <blockquote><p>Liste des codes d'activation de comptes marchands générés de mes membres tiers</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Code</th>
								  <!--<th>Membre Tiers</th>-->
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->membretierscode_code); ?></td>
      <?php /*?><td><?php if($entry->membretierscode_membretiers != ""){
        $membretiers = new Application_Model_EuMembretiers();
        $membretiersM = new Application_Model_EuMembretiersMapper();
        $membretiersM->find($entry->membretierscode_membretiers, $membretiers);
?><?php echo ($membretiers->membretiers_date); ?> - <?php echo ($membretiers->membretiers_nom); ?> <?php echo ($membretiers->membretiers_prenom); ?> - <?php echo ($membretiers->membretiers_mobile); ?><?php }?></td><?php */?>
      <td><div align="center">
	  <?php if($entry->publier == 1){?>
			<span class="label label-success"><i class="icon-ok icon-white"></i> Utilisé</span>&nbsp;
<?php }else{?>
			<span class="label label-warning"><i class="icon-off icon-white"></i> Pas encore utilisé</span>&nbsp;
<?php }?>
	  </div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>

</table>
<?php }else{?>
<div class="alert alert-info">
  Aucun membre tiers enrégistré
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








