<div id="view-content" title="Gestion des collectes à numeriques noirs" style="min-height: 520px;padding: 1px;margin: 1px;font-size: 12px;">
     <div id="nn_tabview" style="padding: 1px;">
	      <ul>
             <li><a href="#tab_apport">Collecte</a></li>
          </ul>
		  <div style="padding: 1px;margin: 1px;">
		       <div id="tab_apport" style="padding: 1px;">
			         <fieldset id="rech_emp_field" style="margin-bottom: 2px;">
                             <legend>Recherche</legend>
                             <table>
                                  <tr>
                                    <td>
                                      <label>Numero appel offre : </label> <select id="numero_offre" name="numero_offre" />
                                      
                                    </td>
									<td>
									    <input id="bt_afficher" type="button" value="Afficher"/>
									</td>
                                   </tr>
                             </table>
                     </fieldset>
			   </div>
		  </div>
	 </div>
     <table id="tbl-appel-nn"></table>
     <div id="pg-appel-nn"></div>
	 <table id="tbl-appel-nnp"></table>
     <div id="pg-appel-nnp"></div>
</div>
<script type="text/javascript">
        $("#tbl-appel-nn").jqGrid({
        url: '<?php echo $this->url(array('action' => 'data')); ?>',
        editurl: '<?php echo $this->url(array('action' => 'save')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames: ['ID','Code Membre', 'Raison sociale', 'Montant apporté','Date apport'],
        height: '100%', width: 800,
        colModel: [
            {name: 'id_detail_appel_nn', index: 'id_detail_appel_nn', width: 50, sorttype: "int", align: "left",hidden:true},
            {name: 'code_membre', index: 'code_membre', width: 150, editable: true, align: "left"},
            {name: 'nom', index: 'nom', width: 80, editable: true, align: "left"},
            {name: 'montant_apport', index: 'montant_apport', width: 100, editable: true, align: "left"},
            {name: 'date_apport', index: 'date_apport', width: 80, align: "left", editable: true}
        ],
        rowNum: 20,
        rowList: [20, 40, 60],
        rownumbers: true,
        pager: '#pg-appel-nn',
        sortname: "id_detail_appel_nn",
        viewrecords: true,
        sortorder: "ASC",
        caption: "Liste des collectes NN membres personnes morales"
    });
	
	$("#tbl-appel-nnp").jqGrid({
        url: '<?php echo $this->url(array('action' => 'datap')); ?>',
        editurl: '<?php echo $this->url(array('action' => 'save')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames: ['ID','Code Membre', 'Nom', 'Montant apporté','Date apport'],
        height: '100%', width: 800,
        colModel: [
            {name: 'id_detail_appel_nn', index: 'id_detail_appel_nn', width: 50, sorttype: "int", align: "left",hidden:true},
            {name: 'code_membre', index: 'code_membre', width: 150, editable: true, align: "left"},
            {name: 'nom', index: 'nom', width: 80, editable: true, align: "left"},
            {name: 'montant_apport', index: 'montant_apport', width: 100, editable: true, align: "left"},
            {name: 'date_apport', index: 'date_apport', width: 80, align: "left", editable: true}
        ],
        rowNum: 20,
        rowList: [20, 40, 60],
        rownumbers: true,
        pager: '#pg-appel-nnp',
        sortname: "id_detail_appel_nn",
        viewrecords: true,
        sortorder: "ASC",
        caption: "Liste des collectes NN membres personnes physiques"
    });

    $("#tbl-appel-nnp").jqGrid('navGrid', '#pg-appel-nnp', {edit: true, add: false, del: false, search: true}); 
	
	$(document).ready(function() {
	       $(function() { 
               $('#view-content').puipanel();	
               $('#nn_tabview').puitabview();
               $('#rech_emp_field').puifieldset();		 
	       })
		   
		   $.get("/eu-appel-nn/offre",
              function success(data) {
              var options = '<option/>';
              for (var i = 0; i < data.length; i++) {
                 options += '<option value="' + data[i][0] + '">' + data[i][1] + ' </option>';
              }
              $('select#numero_offre').html(options);
           });
		   
		   
		   $('#bt_afficher').click(function(e) {
                  e.preventDefault();
				  jQuery("#tbl-appel-nnp").jqGrid('setGridParam',{url: "/eu-appel-nn/datap?numero_offre="+$('#numero_offre').val()}).trigger('reloadGrid');
                  jQuery("#tbl-appel-nn").jqGrid('setGridParam',{url: "/eu-appel-nn/data?numero_offre="+$('#numero_offre').val()}).trigger('reloadGrid');
				  
           });
	
	
	
	})	
</script>