<div id="view-content" style="font-size:11px">
    <table id="tbl-ressource"></table>
    <div id="pg-ressource"></div>
</div>

<script type="text/javascript">
    $("#tbl-ressource").jqGrid({
        url:'/eu-acteur-creneau/listalloc',
        editurl:'<?php echo $this->url(array('action' => 'save')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames:['Code membre','Nom acteur','Type acteur','Ressource','Montant','Date','Heure'],
        height:450, width:827,       
        colModel:[
            {name:'code_membre',index:'code_membre', width:170, editable: true,align:"left"},
            {name:'nom_acteur',index:'nom_acteur', width: 250, editable: true,align:"left"},
            {name:'type_acteur',index:'type_acteur', width: 100, editable: true,align:"left"},
            {name:'ressource',index:'ressource', width: 90, editable: true,align:"left"},
            {name:'montant_op',index:'montant_op', width: 140, editable: true,align:"right",sorttype:'number',formatter:'number'},
            {name:'date_op',index:'date_op', width: 100, editable: true,align:"left"},
            {name:'heure_op',index:'heure_op', width: 70, editable: true,align:"left"},
        ],
        rowNum:50,
        rowList:[50,100,300],
        rownumbers:true,
        pager: '#pg-ressource',
        sortname:"date_op",
        viewrecords: true,
        sortorder: "desc",
        caption:"Liste des resources allouées aux acteurs des créneaux d'activités",
        grouping: true,
        groupingView : {
            groupField : ['nom_acteur'],
            groupColumnShow : [true],
            groupText : ['<b>{0}</b>'],
            groupCollapse : false,
            groupOrder: ['asc'],
            groupSummary : [false],
            groupDataSorted : true
        }
    });
    $("#tbl-ressource").jqGrid('navGrid','#pg-ressource',{edit:false,add:false,del:false,search:true});
   
        
</script>
