<div class="row-fluid">
<div class="span12">

      <legend>Formulaire de Recrutement des opérateurs de saisie (A REMPLIR HONNETEMENT ET CORRECTEMENT)</legend>
	  <div class="alert alert-danger">
       	           <strong>veuillez mettre correctement les informations s'il vous plaît pour éviter tout désagrément:</strong>
      </div>
	  <?php if (isset($_SESSION["validationpertesuccess"])): ?>
				<div class="alert alert-success">
					<li><?php echo implode('<br>',$_SESSION['validationpertesuccess']) ?></li>
				</div>
	 <?php unset($_SESSION['validationpertesuccess']); endif ?>
	 <?php if (isset($_SESSION["validationfilesuploaderrors"])): ?>
				<div class="alert alert-danger">
					<li><?php echo implode('<br>',$_SESSION['validationfilesuploaderrors']) ?></li>
				</div>
	 <?php unset($_SESSION['validationfilesuploaderrors']); endif ?>
	 <?php if (isset($_SESSION["validationerrors"])): ?>
				<div class="alert alert-danger">
					<li><?php echo implode('<br>',$_SESSION['validationerrors']) ?></li>
				</div>
	 <?php unset($_SESSION['validationerrors']); endif ?>
      <form action="#" enctype="multipart/form-data" method="post" class="form-horizontal">
			 <div class="span6">
              <div class="control-group">
	 	       <label for="code_membre_recrutement_operateur" style="font-weight:bold;float:left">
	 	         Code Membre (si vous en avez): </label>
	 		       <input type="text" name="code_membre_recrutement_operateur" placeholder="Mettre ici Votre code membre" class="input-block-level input_nom_recrutement_operateur"/>
                 <div class="alert alert-danger">
       	           <strong>veuillez mettre un code membre correct pour éviter tout désagrément:</strong>
                </div>
             </div>
				 <div class="control-group">
	 	       <label for="nom_recrutement_operateur" style="font-weight:bold;float:left">
	 	         Nom*: </label>
	 		       <input type="text" name="nom_recrutement_operateur" placeholder="Mettre ici Votre nom" class="input-block-level input_nom_recrutement_operateur" required="required"/>
	 	    </div>
				<div class="control-group">
					<label  for="prenoms_recrutement_operateur" style="font-weight:bold;float:left">
						Prenoms*: </label>
					<input type="text" name="prenoms_recrutement_operateur" placeholder="Mettre ici Votre prenom" class="input-block-level input_prenom_recrutement_operateur" required="required"/>
			 </div>
	<div class="control-group">
		<label for="date_naissance_recrutement_operateur" style="font-weight:bold;float:left">
			Date de naissance*: </label>
		<input type="text" name="date_naissance_recrutement_operateur" placeholder="Mettre ici la date de naissance" class="input-block-level input_date_naissance_recrutement_operateur datepicker" date-provide="datepicker" required="required"/>
 </div>
 <div class="control-group">
	 <label for="lieu_naissance_recrutement_operateur" style="font-weight:bold;float:left">
		 Lieu de naissance*: </label>
	 <input type="text" name="lieu_naissance_recrutement_operateur" placeholder="Mettre ici Votre lieu de naissance" class="input-block-level input_lieu_naissance_recrutement_operateur" required="required"/>
 </div>
 <div class="control-group">
	 <label for="lieu_naissance_perte" style="font-weight:bold;float:left">
		 Curriculum Vitae*: </label>
		 <input type="file" name="cv_upload_recrutement_operateur" required="required">
		 <div class="alert alert-danger">
       	           <strong>Seul les fichiers word,pdf et images sont autorisés:</strong>
      </div>
</div>
<div class="control-group">
	 <label for="lieu_naissance_perte" style="font-weight:bold;float:left">
		 Lettre de motivation*: </label>
		 <input type="file" name="motivation_upload_recrutement_operateur" required="required">
		 <div class="alert alert-danger">
       	           <strong>Seul les fichiers word,pdf et images sont autorisés:</strong>
      </div>
</div>
 <blockquote style="text-transform:uppercase;font-weight:bold;font-size:1.3em;text-align:left">
				 AVEZ VOUS UN ORDINATEUR ?
			    </blockquote>
			    <div class="control-group">
					<label class="radio">
						 <input type="radio" name="confirmation_ordinateur_recrutement_operateur" id="piece_perte_personne" value="1">
						 <span style="inline-block;font-size:1.2em;font-style:italic;font-weight:bold;float:left">Oui</span>
					</label>
					<label class="radio">
						 <input type="radio" name="confirmation_ordinateur_recrutement_operateur" id="piece_innexistant_personne" value="0">
						 <span style="inline-block;font-size:1.2em;font-style:italic;font-weight:bold;float:left">Non</span>
					</label>
                </div>
				<blockquote style="text-transform:uppercase;font-weight:bold;font-size:1.3em;text-align:left">
				 ETES VOUS DISPONIPLE IMMEDIATEMENT ?
			    </blockquote>
			    <div class="control-group">
					<label class="radio">
						 <input type="radio" name="disponible_informatique_recrutement_operateur" id="disponibilite_recrutement_operateur" value="1">
						 <span style="inline-block;font-size:1.2em;font-style:italic;font-weight:bold;float:left">Oui</span>
					</label>
					<label class="radio">
						 <input type="radio" name="disponible_informatique_recrutement_operateur" id="piece_innexistant_personne" value="0">
						 <span style="inline-block;font-size:1.2em;font-style:italic;font-weight:bold;float:left">Non</span>
					</label>
                </div>
 <!--
	<div class="control-group">
			<label for="adresse_perte" style="font-weight:bold;float:left">
				Adresse*: </label>
				<textarea name="adresse_perte" class="input-block-level input_adresse_perte" placeholder="Mettre ici votre adresse" rows="8" cols="40"></textarea>
	 </div>
     -->
	</div>
       <div class="span6">
                 <div class="control-group">
						<label for="telephone_recrutement_operateur" style="font-weight:bold;float:left">
							Numero de telephone*: </label>
							 <input type="text" name="telephone_recrutement_operateur" placeholder="Mettre ici votre numero de telephone" class="input-block-level input_telephone_recrutement_operateur" required="required"  />
				 </div>
				 <div class="control-group">
						<label for="email_recrutement_operateur" style="font-weight:bold;float:left">
							Email*: </label>
						<input type="text" name="email_recrutement_operateur" placeholder="Mettre ici votre email" class="input-block-level input_email_recrutement_operateur" required="required"/>
				 </div>

				 <div class="control-group">
						<label for="whatsapp_recrutement_operateur" style="font-weight:bold;float:left">
							Numero Whatsapp: </label>
							 <input type="text" name="whatsapp_recrutement_operateur" placeholder="Mettre ici votre Numero whatsapp" class="input-block-level input_whatsapp_recrutement_operateur"/>
				 </div>
                 <div class="control-group">
						<label for="last_diplome_recrutement_operateur" style="font-weight:bold;float:left">
							Dernier diplôme: </label>
							 <input type="text" name="last_diplome_recrutement_operateur" placeholder="Mettre ici le dernier diplome" class="input-block-level input_last_diplome_recrutement_operateur"/>
				 </div>
				 <div class="control-group">
						<label for="langue_local_recrutement_operateur" style="font-weight:bold;float:left">
							Langues locales parlées: </label>
							 <input type="text" name="langue_local_recrutement_operateur" placeholder="Mettre ici les langues parlées" class="input-block-level input_langue_local_recrutement_operateur"/>
				 </div>

                 <div class="control-group">
						 <label for="region_recrutement_operateur" style="font-weight:bold;float:left">
							 Region*: </label>
							 <select class="input-block-level" name="region_recrutement_operateur" id="input_region_perte">
 								<option value>Choisir votre region </option>
 								 <?php foreach ($this->re_all_entry as $key => $value): ?>
 									<option value="<?php echo $value->id_region ?>" data-idpays="<?php echo $value->id_pays ?>"><?php echo $value->nom_region ?></option>
 								 <?php endforeach; ?>
 							</select>
					</div>

				 <div class="control-group">
						<label for="canton_recrutement_operateur" style="font-weight:bold;float:left">
							Canton de residence*: </label>
							<select class="input-block-level" name="canton_recrutement_operateur" id="input_canton_perte" required="required">
								<option value>Choisir votre canton</option>
								 <?php foreach ($this->can_all_entry as $key => $value): ?>
									<option value="<?php echo $value->id_canton ?>" data-idprefecture="<?php echo $value->id_prefecture ?>"><?php echo $value->nom_canton ?></option>
								 <?php endforeach; ?>
							</select>
				 </div>
				 <div class="control-group">
						<label for="canton_afectation_recrutement_operateur" style="font-weight:bold;float:left">
							Canton d'affectation*: </label>
							<select class="input-block-level" name="canton_afectation_recrutement_operateur" id="input_canton_perte" required="required">
								<option value>Choisir votre canton</option>
								 <?php foreach ($this->can_all_entry as $key => $value): ?>
									<option value="<?php echo $value->id_canton ?>" data-idprefecture="<?php echo $value->id_prefecture ?>"><?php echo $value->nom_canton ?></option>
								 <?php endforeach; ?>
							</select>
				 </div>

                <blockquote style="text-transform:uppercase;font-weight:bold;font-size:1.3em;text-align:left">
				 AVEZ VOUS EFFECTUE UNE FORMATION EN INFORMATIQUE ?
			    </blockquote>
			    <div class="control-group">
					<label class="radio">
						 <input type="radio" name="formation_informatique_recrutement_operateur" id="formation_informatique_recrutement_operateur" value="1">
						 <span style="inline-block;font-size:1.2em;font-style:italic;font-weight:bold;float:left">Oui</span>
					</label>
					<label class="radio">
						 <input type="radio" name="formation_informatique_recrutement_operateur" id="piece_innexistant_personne" value="0">
						 <span style="inline-block;font-size:1.2em;font-style:italic;font-weight:bold;float:left">Non</span>
					</label>
                </div>

       </div>
      <div class="control-group" >
          <button type="submit" class="btn btn-large btn-primary" style="position:relative;float:left">
          Valider le formulaire
          </button>
      </div>

</form>
	</div>
</div>

