<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">
<h1>Le listing des postulants </h1>
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
   <thead>
 	<tr>
 		<th>Code Membre ?</th>
		<th>Nom de l'opérateur</th>
		<th>Prénoms de l'opérateur</th>
		<th>Numéro de téléphone</th>
		<th>Numéro Whatsapp</th>
        
		<th>Email </th>
    
 	</tr>
   </thead>
   <tbody>
<?php foreach ($this->listoperateurs as $key => $value): ?>
    <?php if ($value->nom_recrutement_operateur != "" || $value->prenoms_recrutement_operateur != ""): ?>
 
   <tr>
     <td style="font-size:1.2em">
     <?php if ($value->code_membre_recrutement != ""): ?>

       <?php echo $value->code_membre_recrutement ;?>
     <?php elseif($value->code_membre_recrutement == "Mettre ici Votre code membre"): ?>
     Aucune
     
     <?php else: ?>
     

     Aucune
       
     <?php endif;?>
    </td>
    <td >
       <?php echo $value->nom_recrutement_operateur; ?>
    </td>
    <td >
       <?php echo $value->prenoms_recrutement_operateur; ?>
    </td>
    <td >

    <?php echo $value->telephone_recrutement_operateur; ?>
    
    </td>
    <td >

    <?php echo $value->whatsapp_recrutement_operateur; ?>
    
    </td>
    <td >
    <?php echo $value->email_recrutement_operateur; ?>

    </td>
   </tr>
   <?php endif;?>
  
<?php endforeach ?>

</div>

</div>
</div>