<style>
table {
  max-width: 100%;
  background-color: transparent;
  border-collapse: collapse;
  border-spacing: 0;
}

.table {
  width: 100%;
  margin-bottom: 20px;
}

.table th,
.table td {
  padding: 8px;
  line-height: 20px;
  text-align: left;
  vertical-align: top;
  border-top: 1px solid #dddddd;
}

.table th {
  font-weight: bold;
}

.table thead th {
  vertical-align: bottom;
}

.table caption + thead tr:first-child th,
.table caption + thead tr:first-child td,
.table colgroup + thead tr:first-child th,
.table colgroup + thead tr:first-child td,
.table thead:first-child tr:first-child th,
.table thead:first-child tr:first-child td {
  border-top: 0;
}

.table tbody + tbody {
  border-top: 2px solid #dddddd;
}

.table .table {
  background-color: #ffffff;
}

.table-condensed th,
.table-condensed td {
  padding: 4px 5px;
}

.table-bordered {
  border: 1px solid #dddddd;
  border-collapse: separate;
  *border-collapse: collapse;
  border-left: 0;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.table-bordered th,
.table-bordered td {
  border-left: 1px solid #dddddd;
}

.table-bordered caption + thead tr:first-child th,
.table-bordered caption + tbody tr:first-child th,
.table-bordered caption + tbody tr:first-child td,
.table-bordered colgroup + thead tr:first-child th,
.table-bordered colgroup + tbody tr:first-child th,
.table-bordered colgroup + tbody tr:first-child td,
.table-bordered thead:first-child tr:first-child th,
.table-bordered tbody:first-child tr:first-child th,
.table-bordered tbody:first-child tr:first-child td {
  border-top: 0;
}

.table-bordered thead:first-child tr:first-child > th:first-child,
.table-bordered tbody:first-child tr:first-child > td:first-child,
.table-bordered tbody:first-child tr:first-child > th:first-child {
  -webkit-border-top-left-radius: 4px;
          border-top-left-radius: 4px;
  -moz-border-radius-topleft: 4px;
}

.table-bordered thead:first-child tr:first-child > th:last-child,
.table-bordered tbody:first-child tr:first-child > td:last-child,
.table-bordered tbody:first-child tr:first-child > th:last-child {
  -webkit-border-top-right-radius: 4px;
          border-top-right-radius: 4px;
  -moz-border-radius-topright: 4px;
}

.table-bordered thead:last-child tr:last-child > th:first-child,
.table-bordered tbody:last-child tr:last-child > td:first-child,
.table-bordered tbody:last-child tr:last-child > th:first-child,
.table-bordered tfoot:last-child tr:last-child > td:first-child,
.table-bordered tfoot:last-child tr:last-child > th:first-child {
  -webkit-border-bottom-left-radius: 4px;
          border-bottom-left-radius: 4px;
  -moz-border-radius-bottomleft: 4px;
}

.table-bordered thead:last-child tr:last-child > th:last-child,
.table-bordered tbody:last-child tr:last-child > td:last-child,
.table-bordered tbody:last-child tr:last-child > th:last-child,
.table-bordered tfoot:last-child tr:last-child > td:last-child,
.table-bordered tfoot:last-child tr:last-child > th:last-child {
  -webkit-border-bottom-right-radius: 4px;
          border-bottom-right-radius: 4px;
  -moz-border-radius-bottomright: 4px;
}

.table-bordered tfoot + tbody:last-child tr:last-child td:first-child {
  -webkit-border-bottom-left-radius: 0;
          border-bottom-left-radius: 0;
  -moz-border-radius-bottomleft: 0;
}

.table-bordered tfoot + tbody:last-child tr:last-child td:last-child {
  -webkit-border-bottom-right-radius: 0;
          border-bottom-right-radius: 0;
  -moz-border-radius-bottomright: 0;
}

.table-bordered caption + thead tr:first-child th:first-child,
.table-bordered caption + tbody tr:first-child td:first-child,
.table-bordered colgroup + thead tr:first-child th:first-child,
.table-bordered colgroup + tbody tr:first-child td:first-child {
  -webkit-border-top-left-radius: 4px;
          border-top-left-radius: 4px;
  -moz-border-radius-topleft: 4px;
}

.table-bordered caption + thead tr:first-child th:last-child,
.table-bordered caption + tbody tr:first-child td:last-child,
.table-bordered colgroup + thead tr:first-child th:last-child,
.table-bordered colgroup + tbody tr:first-child td:last-child {
  -webkit-border-top-right-radius: 4px;
          border-top-right-radius: 4px;
  -moz-border-radius-topright: 4px;
}

.table-striped tbody > tr:nth-child(odd) > td,
.table-striped tbody > tr:nth-child(odd) > th {
  background-color: #f9f9f9;
}

.table-hover tbody tr:hover > td,
.table-hover tbody tr:hover > th {
  background-color: #f5f5f5;
}

table td[class*="span"],
table th[class*="span"],
.row-fluid table td[class*="span"],
.row-fluid table th[class*="span"] {
  display: table-cell;
  float: none;
  margin-left: 0;
}

.table td.span1,
.table th.span1 {
  float: none;
  width: 44px;
  margin-left: 0;
}

.table td.span2,
.table th.span2 {
  float: none;
  width: 124px;
  margin-left: 0;
}

.table td.span3,
.table th.span3 {
  float: none;
  width: 204px;
  margin-left: 0;
}

.table td.span4,
.table th.span4 {
  float: none;
  width: 284px;
  margin-left: 0;
}

.table td.span5,
.table th.span5 {
  float: none;
  width: 364px;
  margin-left: 0;
}

.table td.span6,
.table th.span6 {
  float: none;
  width: 444px;
  margin-left: 0;
}

.table td.span7,
.table th.span7 {
  float: none;
  width: 524px;
  margin-left: 0;
}

.table td.span8,
.table th.span8 {
  float: none;
  width: 604px;
  margin-left: 0;
}

.table td.span9,
.table th.span9 {
  float: none;
  width: 684px;
  margin-left: 0;
}

.table td.span10,
.table th.span10 {
  float: none;
  width: 764px;
  margin-left: 0;
}

.table td.span11,
.table th.span11 {
  float: none;
  width: 844px;
  margin-left: 0;
}

.table td.span12,
.table th.span12 {
  float: none;
  width: 924px;
  margin-left: 0;
}

.table tbody tr.success > td {
  background-color: #dff0d8;
}

.table tbody tr.error > td {
  background-color: #f2dede;
}

.table tbody tr.warning > td {
  background-color: #fcf8e3;
}

.table tbody tr.info > td {
  background-color: #d9edf7;
}

.table-hover tbody tr.success:hover > td {
  background-color: #d0e9c6;
}

.table-hover tbody tr.error:hover > td {
  background-color: #ebcccc;
}

.table-hover tbody tr.warning:hover > td {
  background-color: #faf2cc;
}

.table-hover tbody tr.info:hover > td {
  background-color: #c4e3f3;
}

	
</style>
<script type="text/javascript">
function formSubmit() {
   document.getElementById("form1").submit()
}
</script>
<strong>Tableau de bord des <?php if($this->etat == 'A'){echo " anciens ";}else if($this->etat == 'N'){echo " nouveaux ";} ?> membres personnes morales enrôlées </strong><br />
<br />
<?php //echo $this->select; ?>
<table class="table table-striped table-bordered table-hover table-condensed">
<thead>
  <tr>
    <td><strong>
      <?php 
	if (substr($this->code_membre, -1) == "P") {
$membre_mapper = new Application_Model_EuMembreMapper();
$membre = new Application_Model_EuMembre();
$membre_mapper->find($this->code_membre, $membre);
echo $membre->nom_membre." ".$membre->prenom_membre;
	}else if (substr($this->code_membre, -1) == "M") {
$membre_mapper = new Application_Model_EuMembreMoraleMapper();
$membre = new Application_Model_EuMembreMorale();
$membre_mapper->find($this->code_membre, $membre);
echo $membre->raison_sociale." ";

$filiere_mapper = new Application_Model_EuFiliereMapper();
$filiere = new Application_Model_EuFiliere();
$filiere_mapper->find($membre->id_filiere, $filiere);
echo "(".$filiere->nom_filiere.")";
	}
	?>
      </strong></td>
    <td>
	    <?php 
			$tableannee = new Application_Model_DbTable_EuMembreMorale();
			$select = $tableannee->select();
			$select->distinct();
            $select->from('eu_membre_morale', array('YEAR(date_identification) as Annee'));
		    $annee = $tableannee->fetchAll($select);
			if(count($annee) > 0) {
		?>
		<form id="form1" name="form1" method="get" action="<?php echo $_SERVER['REQUEST_URI'];?>">
        <label for="select">Année</label>
        <select name="annee" id="annee" >
        <option value="">Choisir</option>
        <?php foreach ($annee as $rowannee) { 
		      $date_encours = $rowannee->Annee;
		?>
        <option value="<?php echo $date_encours; ?>" <?php if($_GET['annee'] == $date_encours) { echo ' selected="selected"';}?>><?php echo $date_encours; ?></option>
        <?php } ?>
        </select>
		<select name="mois" id="mois">
                <option value="">Choisir</option>
                <option value="01" <?php if($_GET['mois'] == "01") { echo ' selected="selected"';}?>><?php echo moisfr("01"); ?></option>
                <option value="02" <?php if($_GET['mois'] == "02") { echo ' selected="selected"';}?>><?php echo moisfr("02"); ?></option>
                <option value="03" <?php if($_GET['mois'] == "03") { echo ' selected="selected"';}?>><?php echo moisfr("03"); ?></option>
                <option value="04" <?php if($_GET['mois'] == "04") { echo ' selected="selected"';}?>><?php echo moisfr("04"); ?></option>
                <option value="05" <?php if($_GET['mois'] == "05") { echo ' selected="selected"';}?>><?php echo moisfr("05"); ?></option>
                <option value="06" <?php if($_GET['mois'] == "06") { echo ' selected="selected"';}?>><?php echo moisfr("06"); ?></option>
                <option value="07" <?php if($_GET['mois'] == "07") { echo ' selected="selected"';}?>><?php echo moisfr("07"); ?></option>
                <option value="08" <?php if($_GET['mois'] == "08") { echo ' selected="selected"';}?>><?php echo moisfr("08"); ?></option>
                <option value="09" <?php if($_GET['mois'] == "09") { echo ' selected="selected"';}?>><?php echo moisfr("09"); ?></option>
                <option value="10" <?php if($_GET['mois'] == "10") { echo ' selected="selected"';}?>><?php echo moisfr("10"); ?></option>
                <option value="11" <?php if($_GET['mois'] == "11") { echo ' selected="selected"';}?>><?php echo moisfr("11"); ?></option>
                <option value="12" <?php if($_GET['mois'] == "12") { echo ' selected="selected"';}?>><?php echo moisfr("12"); ?></option>
        </select>	
	    <input name="" type="submit" value="Ok" />		
    </form><?php } ?></td>
  </tr>
  <tr style="background-color:#D7EBF9;">
    <td><strong>Dates Enrôlements des membres personnes morales</strong></td>
    <td><strong>Effectifs</strong></td>
  </tr>
</thead>
<tbody>
<?php if(count($this->achat) > 0){?>
<?php 
        $totmontant = 0;
?>
<?php foreach ($this->achat as $row) {?>
<?php 
$totmontant+=$row->nombre;

$cellule1 = $row->date_identification;
$cellule2 = $row->nombre;
?>
  <tr>
    <td><?php echo $cellule1; ?></td>
    <td><div align="right"><strong><?php echo number_format($cellule2, 0, ',', ' '); ?></strong></div></td>
  </tr>
<?php }?>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td><div align="right"><strong>Total : </strong></div></td>
    <td><div align="right"><strong><?php echo number_format($totmontant, 0, ',', ' '); ?></strong></div></td>
  </tr>
<?php }else{?>
  <tr>
    <td colspan="2"><strong>Pas de résultat</strong></td>
  </tr>
<?php }?>
</tbody>
</table>
