<div id="view-content">
    <div style="margin-bottom: 3px;">
        <input id="editer" type="button" value="Editer" class="ui-widget button"/>
        <input id="user" type="button" value="Utilisateur" class="ui-widget button"/>
    </div>
    <table id="tbl-gac-filiere"></table>
    <div id="pg-gac-filiere"></div>
</div>
<script type="text/javascript">
    $("#tbl-gac-filiere").jqGrid({
        url:'<?php echo $this->url(array('action' => 'data')); ?>',
        editurl:'<?php echo $this->url(array('action' => 'save')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames:['Code','Nom','Code membre','Gestionnaire','Nom GAC','Date création'],
        height:440, width:827,
        colModel:[
            {name:'code_gac_filiere',index:'code_gac_filiere', width:100, editable: true,align:"left", hidden:true},
            {name:'nom_gac_filiere',index:'nom_gac_filiere', width:250, editable: true,align:"left"},
            {name:'code_membre',index:'code_membre', width: 170, editable: true,align:"left"},
            {name:'nom_gestion',index:'nom_gestion', width: 150, editable: true,align:"left"},
            {name:'code_gac',index:'code_gac', width: 180, align:"left", editable: true},
            {name:'date_creation',index:'date_creation', width: 110, align:"left", editable: false},
        ],
        rowNum:100,
        rowList:[100,200,300],
        rownumbers:true,
        pager: '#pg-gac-filiere',
        sortname:"code_gac_filiere",
        viewrecords: true,
        sortorder: "desc",
        caption:"Liste des GAC filières"
    });
  
    $("#tbl-gac-filiere").jqGrid('navGrid','#pg-gac-filiere',{edit:false,add:false,del:false,search:true});
    
    $('#editer').click(function()
    {
        var rowsel;
        rowsel = jQuery("#tbl-gac-filiere").jqGrid('getGridParam','selrow');
        if(rowsel)
        {
            data=jQuery("#tbl-gac-filiere").jqGrid('getRowData',rowsel);
            $.get('/eu-gac-filiere/edit',{
                gac_fil:data.code_gac_filiere,code_membre:data.code_membre
            },function success(data){
                $("#content").html(data);
            });             
        }else{
            alert('Aucune ligne sélectionnée');
        }
    });
    $('#editer').button();
    $('#user').button();
    $('#user').click(function()
    {
        var rowsel;
        rowsel = jQuery("#tbl-gac-filiere").jqGrid('getGridParam','selrow');
        if(rowsel)
        {
            $.get('/eu-user/adduser',{
                gac:rowsel
            },function success(data){
                $("#content").html(data);
            });             
        }else{
            alert('Aucune ligne sélectionnée');
        }
    });
</script>