<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

    <div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

  <blockquote><p>Demander un KIT</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addeli">
  <?php if(isset($sessionmembreasso->error) && $sessionmembreasso->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembreasso->error; $sessionmembreasso->error = "";?>
    </div>
  <?php }?>
  
  


<div class="control-group">
<label class="control-label" for="type_kit">Type KIT * </label>
<div class="controls">
<?php 
$type_kit_m = new Application_Model_EuTypeKitMapper();
$type_kit = $type_kit_m->fetchAll();
if(count($type_kit) > 0){?>
<select name="type_kit" id="type_kit" required >
<option value="">Choisir le type </option>
<?php foreach ($type_kit as $value) { ?>
<option value="<?php echo $value->id_type_kit; ?>"><?php echo $value->libelle_type_kit;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>

  

<div class="control-group">
<label class="control-label" for="materiel_kit">Materiel * </label>
<div class="controls">
<?php 
$materiel_kit_m = new Application_Model_EuMaterielKitMapper();
$materiel_kit = $materiel_kit_m->fetchAll();
if(count($materiel_kit) > 0){?>
<select name="materiel_kit" id="materiel_kit" required >
<option value="">Choisir le materiel </option>
<?php foreach ($materiel_kit as $value) { ?>
<option value="<?php echo $value->id_materiel_kit; ?>"><?php echo $value->libelle_materiel_kit;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>
  
  <div class="control-group">
  <label class="control-label" for="qte_kit">Quantité *</label>
  <div class="controls">
  <input type="text" name="qte_kit" id="qte_kit" placeholder="Quantité" required>
  </div>
  </div>
 
  <div class="control-group">
  <label class="control-label" for="licence">Licence </label>
  <div class="controls">
  <input type="text" name="licence" id="licence" placeholder="Licence">
  </div>
  </div>

  
  <div class="control-group">
  <label class="control-label" for="observation">Observations </label>
  <div class="controls">
  <input type="text" name="observation" id="observation" placeholder="Observations">
  </div>
  </div>
 


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Demander le KIT</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








