<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modifier  un KIT</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="editeli">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
  
    

<div class="control-group">
<label class="control-label" for="id_utilisateur">Utilisateur *</label>
<div class="controls">
<?php 
$liste = array("detentrice_technopole","surveillance_filiere","executante_acnev","agrement_technopole","agrement_filiere","agrement_acnev","cm","secretariat","gerant","comite_selection","comite_evaluation","comite_reception");
$t_id_utilisateur = new Application_Model_DbTable_EuUtilisateur();
$select = $t_id_utilisateur->select();
$select->where("code_groupe IN (?) ", $liste);
$entries = $t_id_utilisateur->fetchAll($select);
if(count($entries) > 0){?>
<select id="id_utilisateur" name="id_utilisateur" required>
  <option value="">Choisir un utilisateur</option>
<?php foreach ($entries as $value) {?>
  <option value="<?php echo $value->id_utilisateur; ?>" <?php if($this->kit->id_utilisateur == $value->id_utilisateur){?> selected="selected"<?php }?>><?php echo $value->nom_utilisateur; ?> <?php echo $value->prenom_utilisateur; ?></option>
<?php }?>
</select>
<?php }?>
</div>
</div>



<div class="control-group">
<label class="control-label" for="type_kit">Type KIT * </label>
<div class="controls">
<?php 
$type_kit_m = new Application_Model_EuTypeKitMapper();
$type_kit = $type_kit_m->fetchAll();
if(count($type_kit) > 0){?>
<select name="type_kit" id="type_kit" required >
<option value="">Choisir le type </option>
<?php foreach ($type_kit as $value) { ?>
<option value="<?php echo $value->id_type_kit; ?>" <?php if($this->kit->type_kit == $value->id_type_kit){?> selected="selected"<?php }?>><?php echo $value->libelle_type_kit;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>

   

<div class="control-group">
<label class="control-label" for="materiel_kit">Materiel * </label>
<div class="controls">
<?php 
$materiel_kit_m = new Application_Model_EuMaterielKitMapper();
$materiel_kit = $materiel_kit_m->fetchAll();
if(count($materiel_kit) > 0){?>
<select name="materiel_kit" id="materiel_kit" required >
<option value="">Choisir le materiel </option>
<?php foreach ($materiel_kit as $value) { ?>
<option value="<?php echo $value->id_materiel_kit; ?>" <?php if($this->kit->materiel_kit == $value->id_materiel_kit){?> selected="selected"<?php }?>><?php echo $value->libelle_materiel_kit;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>


  
  <div class="control-group">
  <label class="control-label" for="qte_kit">Quantité *</label>
  <div class="controls">
  <input type="text" name="qte_kit" id="qte_kit" placeholder="Quantité" value="<?php echo $this->kit->qte_kit; ?>" required>
  </div>
  </div>
 
  
  <div class="control-group">
  <label class="control-label" for="licence">Licence </label>
  <div class="controls">
  <input type="text" name="licence" id="licence" placeholder="Licence" value="<?php echo $this->kit->licence; ?>">
  </div>
  </div>

  
  <div class="control-group">
  <label class="control-label" for="observation">Observations </label>
  <div class="controls">
  <input type="text" name="observation" id="observation" placeholder="Observations" value="<?php echo $this->kit->observation; ?>">
  </div>
  </div>
 





<div class="form-actions">
<input name="id_kit" type="hidden" id="id_kit" value="<?php echo $this->kit->id_kit; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier  le KIT</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








