<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des  KIT</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Type</th>
								  <th>Materiel</th>
                  <th>Quantité</th>
                  <th>Licence</th>
								  <th>Guichet</th>
                  <th>Utilisateur</th>
								  <th>Livraison</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->date_kit; ?></td>
<?php 
        $type_kit = new Application_Model_EuTypeKit();
        $type_kitM = new Application_Model_EuTypeKitMapper();
        $type_kitM->find($entry->type_kit, $type_kit);
?>
      <td><?php echo $eli->libelle_type_kit; ?></td>
      
<?php 
        $materiel_kit = new Application_Model_EuMaterielKit();
        $materiel_kitM = new Application_Model_EuMaterielKitMapper();
        $materiel_kitM->find($entry->materiel_kit, $materiel_kit);
?>
      <td><?php echo $eli->libelle_materiel_kit; ?></td>
      <td><?php echo $entry->qte_kit; ?></td>

      <td><?php echo $entry->licence; ?></td>
      <td><?php if($entry->code_membre != ""){
        $membre_morale = new Application_Model_EuMembreMorale();
        $membre_moraleM = new Application_Model_EuMembreMoraleMapper();
        $membre_moraleM->find($entry->code_membre, $membre_morale);
        echo $membre_morale->raison_sociale;} ?></td>
      <td><?php if($entry->membreasso_id > 0){
        $membreasso = new Application_Model_EuMembreasso();
        $membreassoM = new Application_Model_EuMembreassoMapper();
        $membreassoM->find($entry->membreasso_id, $membreasso);
        echo $membreasso->membreasso_nom." ".$membreasso->membreasso_prenom;} ?></td>

      <td><div align="center">
        <?php if($entry->livrer == 1){?>
      <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/kit/livrerkitadmin/id/<?php echo $entry->id_kit; ?>/livrer/0"><i class="icon-ok icon-white"></i>  Livré</a>&nbsp;
<?php }else{?>
      <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/kit/livrerkitadmin/id/<?php echo $entry->id_kit; ?>/livrer/1"><i class="icon-off icon-white"></i>  Non livré</a>&nbsp;
<?php }?></div></td>
      <td><div align="center">
<?php if($entry->etat == 1){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/kit/etatkitadmin/id/<?php echo $entry->id_kit; ?>/etat/0"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/kit/etatkitadmin/id/<?php echo $entry->id_kit; ?>/etat/1"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>

			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/kit/editkitadmin/id/<?php echo $entry->id_kit; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun KIT  enregistré
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








