
<div class="row-fluid">

	<div class="span12">
<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
	
      <legend style="text-align:center"> 
      DEMANDE D’ACHAT 
     </legend>
      <?php if (isset($_SESSION["validationerrors"])): ?>
				<div class="alert alert-danger">
					<?php echo implode('<br>', $_SESSION['validationerrors']) ?>
				</div>
			<?php unset($_SESSION['validationerrors']); endif ?>
			<?php if (isset($_SESSION["validationsuccess"])): ?>
				<div class="alert alert-success">
					<li><?php echo implode('<br>',$_SESSION['validationsuccess']) ?></li>
				</div>
	    <?php unset($_SESSION['validationsuccess']); endif ?>
        <form action="#" method="post" class="form-horizontal">

	   <div class="control-group">
	      <label class="control-label" for="code_membre_demandeur" style="font-weight:bold">
	        Code membre du demandeur *:
	      </label>
	      <div class="controls">
		     <input type="text" name="code_membre_demandeur" class="input-block-level code_membre_demandeur" placeholder="Mettre ici le Votre code membre" required="required"/>
	      </div>
	   </div>

       	<div class="control-group">
	      <label class="control-label" for="libelle_demandeur_achat" style="font-weight:bold">
	        Libellé de la demande d'achat *:
	      </label>
	      <div class="controls">
		     <input type="text" name="libelle_demandeur_achat" class="input-block-level libelle_demandeur_achat" placeholder="Mettre ici le libellé de la demande d'achat" required="required"/>
	      </div>
	   </div>

	   	 <div class="control-group">
		 <label for="type_demande_achat" style="font-weight:bold;float:left">
			 Type de la demande d'achat*: </label>
			   <select class="input-block-level input_type_demande_achat" name="type_demande_achat">
                <option value>Choisir le type de votre demande</option>
			  	<option value="Biens">Biens</option>
			  	<option value="Produits">Produits</option>
			  	<option value="Services">Services</option>
			  </select>
	    </div>

        <div class="control-group">
		   <table class="table table-bordered">
             <thead>
                 <tr>
					 <th>Références</th>
					 <th>Désignation des Articles </th>
					 <th>Quantité </th>
					 <th>Prix Unitaire</th>
					 <th>Total</th>
					 <th>Plus</th>					 
				 </tr> 
             </thead>
             <tbody>
                 <tr id="clone_article_demande_achat">
					 <td><input type="text"  id="ref_article_demande_achat" name="ref_article_demande_achat[]" required="required"></td>
					 <td><input type="text" id="designation_article_demande_achat" name="designation_des_Articles[]" required="required"></td>
					 <td><input type="text" id="quantite_article_demande_achat" name="quantite_article_demande_achat[]" value="0" required="required"></td>
					 <td><input type="text" id="prix_unitaire_article_demande_achat" name="prix_unitaire_article_demande_achat[]" value="0" required="required"></td>
					 <td><input type="text" id="total_article_demande_achat" name="total_article_demande_achat[]" readonly="true" value="0" required="required"></td>
                     
					 <td><button class="btn btn-primary" id="clone_article">Ajouter</button></td>
				 </tr>
             </tbody>
			 </table>
			 <div class="control-group" style="position: relative;width: 252px;left: 40rem;">
	            <label class="control-label" for="montant total de la demande d'achat" style="font-weight:bold">
		         Montant total de la demande d’achat*:
	            </label>
	            <div class="controls">
		         <input type="text" name="montant_demande_achat" id="montant_demande_achat" value="0" class="input-block-level montant_hors_taxe" required="required" readonly="true"/>
	            </div>
	        </div>
			 <button class="btn btn-danger" style="width:133px">Valider</button>
		</div>
        </form>
  
    </div>
</div>
