<div class="row-fluid">
	<div class="span9">
      <legend>Formulaire de Ticket de Support</legend>
			<?php if (isset($_SESSION["validationerrors"])): ?>
				<div class="alert alert-danger">
					<?php echo implode('<br>', $_SESSION['validationerrors']) ?>
				</div>
			<?php unset($_SESSION['validationerrors']); endif ?>
			<?php if (isset($_SESSION["validationsuccess"])): ?>
				<div class="alert alert-success">
					<li><?php echo implode('<br>',$_SESSION['validationsuccess']) ?></li>
				</div>
			<?php unset($_SESSION['validationsuccess']); endif ?>
    <form action="#" enctype="multipart/form-data" method="post" class="form-horizontal">
    <div class="control-group"> 
			<label for="bps_vendu" style="font-weight:bold;float:left">
				BPS vendu*: 
            </label>
			<select class="input-block-level" name="bps_vendu" id="input_bps_vendu">
 			  <option value>Choisir le bps vendu </option>
 				<?php foreach ($this->bpsvendu as $key => $value): ?>
 				  <option value="<?php echo $value->id_bps_vendu_achat_vente_reciproque ?>" data-idbpsavr="<?php echo $value->id_bps_vendu_achat_vente_reciproque ?>"><?php echo $value->nom_bps_vendu ?></option>
 				<?php endforeach; ?>
 			</select>
		</div>
		<div id="avr_cocher_header" name="bps_achete_container">

		</div>
		</form>
    </div>
</div>