<h2>Liste de suivie des fournisseurs</h2>

    <form action="#"  method="post" class="form-horizontal">
        <div class="control-group"> 
			<label for="bps_vendu" style="font-weight:bold;float:left">
               Opérateurs Economique ( PP/PM )*: 
            </label>
			<select class="input-block-level" name="bps_vendu" id="input_bps_vendu">
 			  <option value>Choisir l'opérateurs économique </option>
 				  <option value="CEET" data-idbpsavr="CEET">CEET</option>
 			</select>
		</div>
		<div id="avr_cocher_header" name="bps_achete_container">

		</div>
		</form>