<style>
  article{
      font-size: 1.2em;
      text-align:justify
  }
  #franchise_title{
    text-align: center;
    font-size: 2.9em;
    font-weight: lighter;
  }
  #franchise_article_title{
      color: #c30c60;
      font-weight: bold;
      text-decoration: underline;
  }
  #franchise_sus_article_title{
      color: #1c92f6;          
      font-weight: lighter;
      text-decoration: underline;
      
  }
  #sigle_color{
    color: #c30c60;
    font-weight: bold;
      
  }
  #second_sigle_color{
    color: #1c92f6;      
    font-weight: bold;
  }

  #select_text_franchise p,li{
    -webkit-touch-callout: none; 
    -webkit-user-select: none;
     -khtml-user-select: none; 
       -moz-user-select: none; 
        -ms-user-select: none; 
        -o-user-select:none;
          user-select: none;
  }


</style>

<form action="#" method="post">

<article oncontextmenu="return false;" id="select_text_franchise">
<header id="franchise_title">Contrat de Franchise</header>
<section>
  <p id="franchise_article_title">Entre les soussignés :</p>
  <p>
    <span id="sigle_color">ESMC</span> (Entreprise Sociale de Marché Commun) SARL U au capital de 1 000 000
    FCFA ; Siège social : Lomé (TOGO), Wuiti-Atchati, Angle rues Sagouda, Kiyéou
    et Bandjéli,03 BP 30038 ; Immatriculée au RCCM sous le numéro TG-LOM 2018
    M203 ;Représentée par son Gérant Monsieur <strong>Essohamlon SAMA</strong>,
  </p>
  <p>
    Ci-après dénommée « Franchiseur » « <span id="sigle_color">ESMC</span> »,
  </p>
  <p style="text-align:right">D’une part</p>
  <p>et</p>
  <p><span  id="sigle_color">Raison sociale du franchisé: <textarea name="" id="" cols="30" rows="10" placeholder="…………………………………………………………………………………...………..…………………………………...................................................................................................……………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………...……………………………………………………………………………………………………………………………...……………………………………………………………………………………………………………………………...…………………………………………………………………………………………………………………………….."></textarea> </span> </p>
  <p>Ci-après dénommée « Franchisé »,</p>
  <p style="text-align:right">D’autre part</p>
  <p>Après avoir exposé :</p>
  <p>Les Parties ont signé la convention intitulée : ‘’Convention de collaboration entre
    l’<span id="sigle_color;font-weight:bold">ESMC</span> et les Fournisseurs de biens, produits et services : Utilisateurs, Fournisseurs
    Spécifiques et Fournisseurs Externes pour la réalisation par le marché des 17
    Objectifs de Développement Durable ‘’</p>
    <p>Pour assurer la mise en œuvre de la Production Commune et satisfaire autant que
     faire se peut tous ses Utilisateurs, la société <span id="sigle_color">ESMC</span> a mis en place une marque
     dénommée Guichet Unique d’Intégration Universelle Interface Communautés
     Opérateurs Economiques Offreurs de projets <span id="second_sigle_color">(GUIUC/OE/OP)</span>.</p>
   <p>
     Pour une utilisation efficiente de la marque <span id="second_sigle_color">GUIUC/OE/OP</span>, <span id="sigle_color">ESMC</span> a décidé de
     franchiser ladite marque en confiant son exploitation à des personnes morales
     autonomes qui le désirent
     Pour une utilisation efficiente de la marque <span id="second_sigle_color">GUIUC/OE/OP</span>, <span id="sigle_color">ESMC</span> a décidé de
     franchiser ladite marque en confiant son exploitation à des personnes morales
     autonomes qui le désirent
   </p>
   <p>
   La personne morale ………………...........................................étant intéressée par la
franchise de <span id="second_sigle_color">GUIUC/OE/OP</span>, les deux parties ont convenu et arrêté ce qui suit :
   </p>
</section>

<section>
<p id="franchise_article_title">Article 1. Concession de franchise</p>
<p>Le franchiseur, donne au franchisé, le droit d’exploiter des Guichets Uniques
d’Intégration Universelle Interface Communautés Opérateurs Economiques
Offreurs de Projets <span id="second_sigle_color">(GUIUC/OE/OP)</span> qui doivent être destinés essentiellement à la
souscription aux deux (02) activités de la plateforme <span id="sigle_color">ESMC</span> que sont : souscriptions
pour soi et pour tiers aux Comptes Marchands et aux Bons de Consommation et
Prestataires de la Production Commune.</p>
<p id="franchise_article_title">Article 2. Marque et Enseigne</p>
<p id="franchise_sus_article_title">2.1. Licence de marque</p>
<p>Le franchiseur est le seul et unique propriétaire de la marque <span id="second_sigle_color">GUIUC/OE/OP</span>.</p>
<p>La franchise octroyée implique licence à titre d’enseigne de la marque dénominative
et figurative, ainsi que de tous les procédés, formules, éléments publicitaires, slogans
établis par les soins du franchiseur, et ce pour la durée du contrat dans le point
d’exploitation désigné <span id="second_sigle_color">GUIUC/OE/OP</span></p>
<p id="franchise_sus_article_title">2.2. Conditions d’utilisations</p>
<p>Le franchisé aura à sa charge, le coût de la réalisation de l’infrastructure devant
abriter le <span id="second_sigle_color">GUIUC/OE/OP</span>. L’infrastructure doit être réalisée selon le format uniforme
décidé par le franchiseur. En conséquence, à l’expiration du contrat et en cas de non
renouvellement, le franchisé aura l’obligation, entre autres, de changer les couleurs
des locaux ayant abrité le GUIU. Bref, le franchisé devra supprimer toutes traces
représentant la franchise <span id="second_sigle_color">GUIUC/OE/OP</span>.</p>
<p>La marque <span id="second_sigle_color">GUIUC/OE/OP</span> et les enseignes <span id="sigle_color">ESMC</span> ne pourront être inscrites au
Registre de Commerce et du Crédit mobilier du franchisé sous quelque rubrique
que ce soit. Elles seront utilisées par le franchisé à titre d’enseigne ainsi que comme
signe de ralliement de sa clientèle sans qu’elles puissent être confondues avec sa
dénomination propre.</p>
<p>Le franchisé sera tenu de faire état de sa propre raison sociale ainsi que de sa qualité
de franchisé de la plateforme <span id="sigle_color">ESMC</span> sur ses documents commerciaux ainsi que sur
sa vitrine.</p>
<p>Le franchisé sera tenu de faire état de sa propre raison sociale ainsi que de sa qualité
de franchisé de la plateforme <span id="sigle_color">ESMC</span> sur ses documents commerciaux ainsi que sur
sa vitrine.</p>
<p id="franchise_article_title">Article 3. Exploitation</p>
<p>L’exploitation de cette franchise se fera notamment :</p>
<ul>
<li>Par la présentation du <span id="second_sigle_color">GUIUC/OE/OPP</span> selon une architecture bien définie par le
franchiseur.</li>
<li>Par la fourniture d’une liste du matériel devant équiper le <span id="second_sigle_color">GUIUC/OE/OPP</span></li>
<li>Par la formation du personnel du franchisé</li>
</ul>
</section>

<section>
<p>En toute circonstance, le franchisé traite en son nom personnel et en qualité de
commerçant indépendant. Il sera donc seul responsable des conséquences de la
réalisation et de l’exploitation des <span id="second_sigle_color">GUIUC/OE/OP</span> du franchisé.</p>
<p>L’affectio-societatis est à cet effet exclu. Cela veut dire que chacun supporte seul ses
propres charges ; en aucun cas, le franchiseur ne peut donc être considéré comme
associé de fait à la gestion ou à l’exploitation des <span id="second_sigle_color">GUIUC/OE/OP</span> du franchisé.</p>
<p>Le franchisé devra appliquer strictement la méthode d’utilisation de la plateforme
<span id="sigle_color">ESMC</span>.</p>

<p id="franchise_sus_article_title">Article 4. Aspect général de l’image de marque</p>

<p>Le franchisé déclare expressément avoir conscience de faire partie d’un ensemble de
franchisés dont chacun doit assurer un service et une présentation aussi uniforme
que possible et de la meilleure qualité possible, de telle sorte à être, pour le public,
un standard de prestation de qualité.</p>

<p>Ce standard doit s’appliquer à tous les niveaux de ce qu’un Utilisateur peut attendre
d’un GUIU, qu’il s’agisse de l’architecture du local, du positionnement des affiches
que de la qualité des services.</p>

<p id="franchise_sus_article_title">Article 5. Obligations du franchiseur</p>
<p id="franchise_sus_article_title">5.1. Services apportés par le franchiseur pour l’ouverture du GUIUC/OE/OP</p>

<p>A la signature des présentes, le franchiseur mettra à la disposition du franchisé, le
savoir-faire nécessaire à l’exploitation des <span id="second_sigle_color">GUIUC/OE/OP</span>.</p>
<p>Le savoir-faire s’accompagne, à la demande du franchisé, d’une formation de son
personnel. Le cas échéant, le coût de la formation sera entièrement supporté par le
franchisé.</p>

<p>Le savoir-faire sera, en cas de besoin, périodiquement mis au point et renouvelé</p>

<p>Le franchiseur mettra à la disposition du franchisé, une ou des personnes à l’ouverture
et au cours de l’exécution du présent contrat, à l’effet de contrôler le respect des
conditions d’utilisation et d’exploitation du <span id="second_sigle_color">GUIUC/OE/OP</span></p>

<p id="franchise_sus_article_title">5.2. Services apportés par le franchiseur après l’ouverture du GUIUC/OE/OP</p>
<p>Pendant toute la durée du présent contrat, le franchiseur s’engage à mettre à la
disposition du franchisé, les services suivants :</p>
<ul>
<li>A assurer périodiquement l’assistance technique et les applications informatiques
nécessaires à l’exploitation, l’assistance commerciale du franchisé, notamment en
lui faisant bénéficier des perfectionnements dont il disposerait et en éditant des brochures et des prospectus commerciaux de diffusion générale qu’il remettra
au franchisé.</li>
</ul>

</section>
<section>
<ul>
<li>A communiquer régulièrement au franchisé les perfectionnements et/ou lui
fournir les informations dont il aurait besoin, notamment afin d’éviter des dérives
de procédé.</li>
<li>Toutes prestations de services non prévus au présent contrat et que le franchiseur
viendra à fournir au franchisé sur sa demande et, après accord de ce dernier,
seront facturées a un prix convenu d’avance.</li>
</ul>
<p id="franchise_sus_article_title">Article 6. Obligations du franchisé : Respect des procédures, de l’image de la
marque</p>
<p>Il est bien vrai que le présent contrat n’implique aucune restriction quelconque à
la liberté du franchisé dans la direction et l’exploitation de son fonds de commerce
qui est entièrement sous sa responsabilité, à ses seuls avantages et risques et dont
il reste seul juge.</p>
<p>Cependant, les parties conviennent expressément que, pour obtenir une meilleure
organisation et une promotion plus dynamique de la chaîne de franchise, et pour
une bonne exécution du contrat, il est dans l’intérêt des parties au présent contrat
que les méthodes et les procédures édictées par le franchiseur soient, par tous
moyens, mises à la disposition du franchisé.</p>
<p>En tout état de cause, le franchisé s’engage à :</p>
<ul>
<li>Consacrer le temps et les activités nécessaires à l’exploitation de franchise
qui lui est consentie et à ne pas s’intéresser directement ou indirectement, à
l’exploitation d’un savoir-faire concurrent à celui du franchiseur dans un domaine
semblable.</li>
<li>Mener son exploitation commerciale, conformément aux règles, méthodes et
procédures définies par le franchiseur.</li>
<li>A respecter scrupuleusement les prix, les normes de qualité dictées par le
franchiseur</li>
<li>A mettre en place au voisinage, à l’entrée et à l’intérieur du <span id="second_sigle_color">GUIUC/OE/OP</span>, des
éléments d’identification tels que des enseignes, des affiches et autres qui lui
seront indiqués par le franchiseur.</li>
<li>A respecter l’unité de style (couleurs, matériaux, etc.…) défini par le franchiseur,</li>
<li>A entretenir régulièrement les <span id="second_sigle_color">GUIUC/OE/OP.</span></li>
<li>A respecter l’image de marque, de qualité en veillant à l’excellente présentation
du personnel, à ce que le personnel respecte scrupuleusement les normes de
qualité et applique strictement les méthodes faisant l’originalité du savoir-faire et respecte la législation prévue pour l’exploitation de <span id="second_sigle_color">GUIUC/OE/OP</span>.</li>

</section>

<section>
<li>A inscrire impérativement sur son papier en tête, ses documents commerciaux,
ainsi que sur tous supports de communication à l’égard de sa clientèle quelle
qu’elle soit ainsi que sur sa porte d’entrée et sa vitrine, sa qualité de commerçant
indépendant, franchisé de l’<span id="sigle_color">ESMC</span>.</li>
<li>A respecter toutes les directives données par le franchiseur et à adapter
immédiatement toute modification apportée par le franchiseur.</li>
</ul>

<p id="franchise_sus_article_title">Article 7. Dispositions financières à la charge du franchisé</p>

<p id="franchise_sus_article_title">7.1. Droit de franchise.</p>
<p>Le droit de franchise, élément incorporel temporaire correspond :</p>
<ul>
<li>Au droit d’accès à la plateforme <span id="sigle_color">ESMC</span> équivalent au droit de bénéficier de la
notoriété acquise par la marque <span id="second_sigle_color">GUIUC/OE/OP.</span></li>
<li>Au droit pour le franchisé de bénéficier pour son exploitation, pendant la durée
du contrat, des méthodes commerciales innovantes et d’une clientèle fidèle du
franchiseur.</li>
</ul>
<p id="franchise_sus_article_title">7.2. Redevance de franchise</p>
<p>En contrepartie des droits qui lui sont accordés pour l’utilisation de la marque
<span id="second_sigle_color">GUIUC/OE/OP</span> et de la mise à disposition du savoir-faire, le franchisé versera au
franchiseur, une redevance correspondant à ……% des commissions à lui payer par
ce dernier</p>
<p>Cette redevance sera retenue par le franchiseur lors du paiement des commissions
à verser au franchisé.</p>

<p id="franchise_sus_article_title">Article 8. Dispositions financières à la charge du franchiseur</p>

<p>En contrepartie de la souscription des Utilisateurs aux deux (02) activités précitées
disponibles sur la plateforme <span id="sigle_color">ESMC</span>, le franchiseur paiera au franchisé, des
commissions dont les modalités sont fixées à l’article 7.1.4 alinéas 2 et 3 de la
convention sus visée.</p>

<p id="franchise_sus_article_title">Article 9. Secret et confidentialité</p>

<p>Par les présentes, le franchisé reconnaît :</p>
<ul>
<li>Que les droits du franchiseur sur tous les éléments protégés ou non afférents au
savoir-faire sont réputés lui être communiqués à titre confidentiel.</li>
<li>Que le savoir-faire est un ensemble de secrets commerciaux et de technique dont il n’est que dépositaire et qui lui sont révélés à titre confidentiel uniquement
pour l’assister dans l’exploitation de sa structure sous franchise <span id="second_sigle_color">GUIUC/OE/OP</span>.</li>
</ul>

</section>
<section>
<ul>
<li>En conséquence, le franchisé s’engage durant toute la durée du présent contrat et
à l’expiration de celui-ci, quelle qu’en soit la cause :</li>
<li>A respecter scrupuleusement le secret sur le présent contrat, sur la méthode
d’exploitation du <span id="second_sigle_color">GUIUC/OE/OP</span>, sur les documents qui lui sont adressés par
le franchiseur, sur le Compte Marchand des Utilisateurs de la plateforme <span id="sigle_color">ESMC</span>
dont il pourrait avoir connaissance.</li>
<li>A n’utiliser directement ou indirectement aucun de ces secrets dans une
entreprise autre que celle habilitée à exploiter un <span id="second_sigle_color">GUIUC/OE/OP.</span>
</li>
<li>A obtenir de ses employés, dirigeants et associés qu’ils ne divulguent pas le
savoir-faire qui leur sera communiqué.</li>
</ul>
<p>A cet effet, il devra notamment inclure dans les contrats de travail de ses employés
une clause de confidentialité</p>
<p id="franchise_sus_article_title">Article 10. Responsabilité</p>
<p>Il est expressément convenu que le franchisé sera tenu pour seul responsable de
tout sinistre ou dommage susceptible d’intervenir à l’occasion de l’installation ou
de l’exploitation des <span id="second_sigle_color">GUIUC/OE/OP</span> ainsi que des dommages causés par des actes
ou des omissions du franchisé ou de l’un quelconque de ses agents employés,
préposés, mandataires, contractants ou autres en rapport avec les prestations de
services effectuées dans ses <span id="second_sigle_color">GUIUC/OE/OP.</span></p>
<p>Il assumera seul la charge, les frais et conséquences des procès en cas d’action
en dommages et intérêt intentés ou de réclamation formulée par un client en vue
d’obtenir la réparation notamment de dommages matériels ou corporels provoqués
directement ou indirectement par les dits actes ou omissions.</p>
<p id="franchise_sus_article_title">Article 11. Durée du contrat</p>
<p>Le présent contrat est conclu pour une durée de un (01) an qui commence à courir
à la signature du présent contrat. A défaut de préavis de deux (02) mois avant
l’expiration du terme, il se renouvellera par tacite reconduction sans donner lieu à
contrepartie financière, pour de nouvelles périodes successives de un (01) an.</p>
<p>La résiliation anticipée du présent contrat interviendra sans préjudice des dommages
et intérêts qui pourront être réclamés à la partie fautive, en réparation de l’intégralité
du préjudice causé.</p>
<p>Le franchiseur ne remboursera aucune somme d’argent au franchisé en cas de
rupture du contrat par ce dernier.</p>
<p>En cas de rupture du contrat de la part du franchiseur pour cause de non-respect</p>
</section>
<section>
<p>du franchisé des obligations inhérentes au présent contrat, le franchisé ne pourra
prétendre, ni à un remboursement, ni au paiement d’une indemnité.</p>
<p id="franchise_sus_article_title">Article 12. Résiliation du contrat</p>
<p>En cas d’inexécution ou de violation par l’une des Parties de l’une quelconque des
dispositions de la convention, celle-ci pourra être résiliée unilatéralement et de
plein droit par l’autre partie, trente (30) jours après l’envoi d’une mise en demeure
restée sans effet.</p>
<p>La présente convention sera résiliée automatiquement et de plein droit dans
l’hypothèse où, par suite d’une modification législative ou règlementaire concernant
ses activités, l’une ou l’autre partie se trouverait dans l’impossibilité de poursuivre
la convention.</p>
<p id="franchise_sus_article_title">Article 13. Cessation du contrat de franchise</p>
<p>A son expiration, sa résiliation ou sa cessation pour quelque cause que ce soit :
Le franchisé cessera immédiatement d’exploiter la franchise <span id="second_sigle_color">GUIUC/OE/OP</span> et ne
pourra plus se présenter ou se prévaloir de la qualité de cette franchise.
Le franchisé cessera immédiatement toute utilisation, de quelque manière que ce
soit, des méthodes, techniques et formules liées à la franchise <span id="second_sigle_color">GUIUC/OE/OP</span> qui
lui avaient été communiquées par le franchiseur.</p>
<p>Le franchisé cessera immédiatement toute utilisation, à quelque titre que ce soit,
de la marque <span id="second_sigle_color">GUIUC/OE/OP</span> ainsi que des posters, affiches et de tout élément
publicitaire ou promotionnel distinctif lié à la franchise et en particulier, de tout
matériel ou documents portant la marque <span id="second_sigle_color">GUIUC/OE/OP.</span></p>
<p>Dans tous les cas, le franchisé devra procéder au retrait de l’enseigne <span id="second_sigle_color">GUIUC/OE/
OP</span>. Le franchiseur peut, en cas d’inaction du franchisé, supprimer en ses lieux et
place la ou les enseignes physiques revêtant la marque <span id="second_sigle_color">GUIUC/OE/OP</span> ainsi que
le droit de récupérer et d’enlever l’ensemble des éléments, articles, installation
et meubles spécifiques à la franchise et notamment : les enseignes et affiches
extérieures portant la marque <span id="second_sigle_color">GUIUC/OE/OP</span>, tout panneau ou signe relatif à la
qualité ou à la nature des activités <span id="sigle_color">ESMC</span>.</p>
<p>Dès la cessation du contrat, pour quelque raison que ce soit, le franchisé procédera
aux modifications nécessaires, de telle sorte qu’aucun risque de confusion n’existe
entre lui et le franchiseur.</p>
<p id="franchise_sus_article_title">Article 14. Indépendance des parties</p>
<p>Le franchisé est, et demeure un commerçant indépendant qui assure personnellement
avec le concours de tout préposé de son choix la pleine et entière liberté de
gestion et d’exploitation de son entreprise et conserve, en conséquence, l’exclusive
responsabilité des résultats de son exploitation.</p>
</section>
<section>
<p>Le franchisé veillera à ce qu’il ne puisse y avoir, en aucun cas aucune confusion
entre le franchiseur et lui</p>
<p>Le franchisé s’engage à justifier de sa qualité de commerçant indépendant par :</p>
<ul>
  <li>La production de son inscription au registre du commerce et du crédit mobilier</li>
  <li>La production de sa carte d’opérateur économique,</li>
  <li>La production de son acte de propriété ou de son bail commercial,</li>
  <li>La production, le cas échéant, des statuts de sa société.</li>
</ul>
<p>Le franchisé devra veiller au parfait respect des dispositions légales de toutes sortes,
et notamment des réglementations applicables à son activité, à propos de l’hygiène,
de la sécurité, de l’urbanisme et autre ; étant seul responsable de toute violation de
la réglementation.</p>
<p id="franchise_sus_article_title">Article 15. Modification du contrat</p>
<p>Au cas où, en raison de la promulgation d’une nouvelle loi ou réglementation, une
obligation quelconque serait mise à la charge du franchisé comme au cas où un
droit quelconque serait accordé au franchiseur, les parties s’engagent à modifier le
contrat à l’effet de le rendre compatible avec les nouvelles dispositions légales.</p>

<p id="franchise_sus_article_title">Article 16. Enregistrement</p>

<p>Le présent contrat sera enregistré par le franchiseur et supporté par moitié par les
parties.</p>

<p id="franchise_sus_article_title">Article 17. Intégration du présent contrat</p>

<p>Outre les conditions spécifiques ci-dessus nécessaires au partenariat entre
l’ESMC et le franchisé, le présent contrat s’intègre entièrement à la Convention de
collaboration sus visée.</p>

<p id="franchise_sus_article_title">Article 18. Clause compromissoire d’arbitrage</p>
<p>Les parties conviennent de tout mettre en œuvre pour résoudre par des négociations
amiables, toutes contestations pouvant surgir à l’occasion de l’exécution ou de
l’interprétation du présent contrat.</p>
<p>A défaut de règlement amiable, les parties conviennent de soumettre le litige à
l’arbitrage sous l’égide de la Cour d’Arbitrage du Togo (CATO) à laquelle elles
déclarent expressément se référer.</p>
<p>Le nombre d’arbitre est fixé à un (01).</p>
</section>
<section>
<p style="text-align:right">Fait à Lomé en deux (02) exemplaires originaux,</p>
<p style="text-align:right">Le ……………………………………………………………………</p>
<p>
<span tyle="display:inline-block;text-align:left">Le Franchiseur </span>
<span style="display:block;text-align:right;position: relative;top: -27px;">Le Franchisé</span>
</p>
<p>M. SAMA Essohamlon</p>
<p style="display:block;text-align:right;position: relative;top: -42px;">M/Mme ……………………………………….......</p>
</section>
</article>


</form>