<?php $sessionmembre = new Zend_Session_Namespace('utilisateur');?>

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<h3 id="page_title">TITRE DU POSTE : <?php echo $this->pagetitle ;?></h3>

<div id="page_direction_container">

  <div id="page_direction_container_left">

    <h4>SUPERIEUR HIERARCHIQUE : <?php echo $this->postehierarchique ;?></h3>
  
  </div>

  <div id="page_direction_container_right">

    <h4>COLLABORATEURS : Tout le reste du personnel</h3>
    
  </div>
</div>

<h4>PRINCIPALES TACHES :</h4>

<ul>
  <li>-	Opération Annulation Vente des projets d’achat</li>
  <li>-	Opération Annulation Vente des projets  de production</li>
  <li>-	Opération Annulation Vente des projets de transformation</li>
  <li>-	Opération Annulation Vente des projets de vente (distribution : logistique, transports sur toute gamme : BNOP offre financière/ offre technique PLUS BNOT. Tout cela pour les rentabilités escomptées par l’opération rapprochement.</li>
</ul>

<h4>
PROCEDURES A UTILISER
</h4>
