<style>
#page_title{
    text-align: center;
    margin-bottom: 35px;
}

#page_direction_container{
    clear:both;
    width: 100%;
}

#page_direction_container_left{
    width: 50%;
    position: relative;
    left:0;
}

#page_direction_container_right{
    width: 50%;
    position: relative;
    right: 0;
    float: right;
    top: -67px;
}


</style>




<h3 id="page_title">TITRE DU POSTE : <?php echo $this->pagetitle ;?></h3>

<div id="page_direction_container">

  <div id="page_direction_container_left">

    <h3>SUPERIEUR HIERARCHIQUE : <?php echo $this->postehierarchique ;?></h3>
  
  </div>

  <div id="page_direction_container_right">

    <h3>COLLABORATEURS : Tout le reste du personnel</h3>
    
  </div>
</div>


<blockquote>  PRINCIPALES TACHES :</blockquote>

<ol>
    <li>Budget de fonctionnement  ESMC </li>
    <li>Budget d’investissement ESMC</li>
    <li>Budget de fonctionnement  PC</li>
    <li>
    Budget  d’investissement PC 
     <ul>
         <li>Exécutions <span style="color:#FF0000">SMCIPN</span> VS Activités Souscription pour Soi et pour Tiers aux CM et aux BC</li>
         <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> VS Activités Acheteur-Revendeur en Ligne contre OPI</li>
         <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> VS Activités Achat et Vente </li>
         <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> VS Activités Prestataires de PC :
           <ul>
               <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> des projets de la Centrale d’Achat Commune validés</li>
               <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> des projets de la Centrale de Production  Commune validés</li>
               <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> des projets de la Centrale de Transformation  Commune validés</li>
               <li>Exécutions  <span style="color:#FF0000">SMCIPN</span> des projets de la Centrale de Vente Commune validés</li>
           </ul>
         </li>
     </ul>
    </li>
    <li>Suivi des Contrats</li>
    <li>Réception d’une Livraison</li>
    <li>Traitement d’une facture fournisseur</li>
</ol>


<h3>PROCEDURES A UTILISER</h3>

<ul>
    <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : ELABORATION ET APPROBATION DES PLANS D’ACTIONS ET BUDGETS ANNUELS</a></li>
    <li><a href="/administration/detailstachemembreasso/id/4" target= "_blanc">PROCEDURE : Contrôle des engagements et Suivi budgétaire/analytique sous le logiciel</a></li>
    <li><a href="/administration/detailstachemembreasso/id/5" target= "_blanc">PROCEDURE : CONTROLE DES ENGAGEMENTS ET SUIVI BUDGETAIRE/ANALYTIQUE SOUS LE LOGICIEL</a> </li>
</ul>