<style>
#page_title{
    text-align: center;
    margin-bottom: 35px;
}

#page_direction_container{
    clear:both;
    width: 100%;
}

#page_direction_container_left{
    width: 50%;
    position: relative;
    left:0;
}

#page_direction_container_right{
    width: 50%;
    position: relative;
    right: 0;
    float: right;
    top: -67px;
}


</style>




<h3 id="page_title">TITRE DU POSTE : <?php echo $this->pagetitle ;?></h3>

<div id="page_direction_container">

  <div id="page_direction_container_left">

    <h3>SUPERIEUR HIERARCHIQUE : <?php echo $this->postehierarchique ;?></h3>
  
  </div>

  <div id="page_direction_container_right">

    <h3>COLLABORATEURS : Tout le reste du personnel</h3>
    
  </div>
</div>




<blockquote>  PRINCIPALES TACHES :</blockquote>

<ol>
    <li>Organisation et système Comptables </li>
    <li>Etats Quotidien</li>
    <li>Opérations :
     <ul>
         <li>Souscriptions</li>
         <li>Souscriptions</li>
         <li>Règlement</li>
         <li>Rapprochements 1</li>
         <li>Compensations 1</li>
         <li>Annulations 1</li>
         <li>Rapprochements 2</li>
         <li>Compensations 2</li>
         <li>Compensations 2</li>
         <li>Compensations 2</li>
         <li>Destruction</li>
     </ul>
    </li>
    <li>Achats de Fournitures ou Services</li>
    <li>Approvisionnement de la Caisse</li>
    <li>Règlement des Factures</li>
    <li>Achat d’Immobilisations sans avance</li>
    <li>Achat d’Immobilisations avec avance règlement de la facture d’avance/ d’acompte</li>
    <li>Achat d’Immobilisations avec avance comptabilisation de la facture définitive : solde des comptes d’avance/ d’acompte</li>
    <li>Suivi des Immobilisations financières</li>
    <li>Centralisation et paiement des salaires</li>
    <li>Règlement des salaires</li>
    <li>Stocks/ Entrée en stocks</li>
    <li>Stocks/consommation des stocks</li>
</ol>

<blockquote>Les procédures à utiliser</blockquote>

<h3>PROCEDURES D'ACHAT</h3>

<ul>
    <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : ACHAT DE PETITS MATERIELS FOURNITURES ET SERVICES DONT LE MONTANT EST INFERIEUR A 50 000 FCFA</a></li>
    <li><a href="/administration/detailstachemembreasso/id/4" target= "_blanc">PROCEDURE : RECEPTION D’UNE LIVRAISON</a></li>
    <li><a href="/administration/detailstachemembreasso/id/5" target= "_blanc">PROCEDURE : SUIVI DES DELAIS DE LIVRAISON DES COMMANDES</a> </li>
    <li><a href="/administration/detailstachemembreasso/id/6" target= "_blanc">PROCEDURE : GESTION DE CARBURANT</a></li>
    <li><a href="/administration/detailstachemembreasso/id/21" target= "_blanc">PROCEDURE : GESTION DES AUTRES FOURNITURES ET CONSOMMABLES</a></li>
    <li><a href="/administration/detailstachemembreasso/id/7" target= "_blanc">PROCEDURE : PASSATION DE CONTRATS DE FOURNISSEURS</a></li>
    <li><a href="/administration/detailstachemembreasso/id/8" target= "_blanc">PROCEDURE : SUIVI DES CONTRATS</a></li>
</ul>

<h3>PROCEDURES D'IMMOBILISATION</h3>

<ul>
    <li><a class="dropdown-item" href="<?php echo $this->baseUrl();?>/administration/detailstachemembreasso/id/10" target= "_blanc">PROCEDURE : GESTION DES SORTIES DES IMMOBILISATIONS ET DU MATERIEL ROULANT.</a></li>
    <li><a class="dropdown-item" href="<?php echo $this->baseUrl();?>/administration/detailstachemembreasso/id/18" target= "_blanc">PROCEDURE : ENTRETIEN ET REPARATION DES IMMOBILISATIONS</a></li>
    <li><a class="dropdown-item" href="<?php echo $this->baseUrl();?>/administration/detailstachemembreasso/id/19" target= "_blanc">PROCEDURE : SECURISATION DES IMMOBILISATIONS</a></li>
    <li><a class="dropdown-item" href="<?php echo $this->baseUrl();?>/administration/detailstachemembreasso/id/20" target= "_blanc">PROCEDURE : GESTION DES VEHICULES ET DES MOTOS</a></li>
</ul>

<h3>PROCEDURES A UTILISER</h3>

<ul>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : PRINCIPES COMPTABLES</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : COMPTABILITE INFORMATISEE / COMPTABILITE INTEGREE</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : DESCRIPTION DU FONCTIONNEMENT DU SYSTEME COMPTABLE</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : JOURNAUX COMPTABLES ET SYSTEME DE  CLASSEMENT DES PIECES</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : PLANS COMPTABLES</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Versement espèces du MSCM par voie de BAn</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Formation de DAT</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Envoi Demande de Ligne de Découvert (EDLD) en fonction du niveau du DAT</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Constatation des Dettes Fournisseurs (CDF)</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Prélèvement Direct des OPI matures</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Prélèvement Direct des Traites non avalisées (PDTNA)</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Facturation des Frais de Transaction (FFT)</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Chiffre d’Affaires de la Production Commune (CAPC)</a></li>

   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Apurement de la Ligne de Découvert Utilisée (ALDU)</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Etat quotidien des tranches d’OPI restant à apurer</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Etat quotidien des tranches de Traites Non Avalisées  restant à apurer</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Etat quotidien des OPI matures</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Etat quotidien des traites non avalisées matures</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Niveau des recettes sur le Compte Courant  maintenant de façon pérenne le niveau de découvert inférieur au niveau de DAT</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Achat de fournitures ou services</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Approvisionnement de la caisse</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : TRAITEMENT D’UNE FACTURE FOURNISSEUR</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Règlement des factures</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Achat d’immobilisation sans avance</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Achat d’immobilisations avec avance règlement de la facture d’avance/d’acompte</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Achat d’immobilisations avec avance Comptabilisation de la facture définitive : Solde des comptes d’avance/ d’acompte</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Immobilisation financière</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Centralisation et paiement des salaires</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Règlement des salaires</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Stock/ Entrées en stock</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : Stocks/Consommations de stock</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : TRAVAUX PERIODIQUES ET ANNUELS</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : QUELQUES CONTROLES USUELS</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : AUTO-CONTROLE DE L’ESMC & CONTROLE DU PARTENAIRE BANCAIRE ET FINANCIER</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : CONTROLE FINANCIER INTERNE</a></li>
   <li><a href="/administration/detailstachemembreasso/id/1" target= "_blanc">PROCEDURE : AUDIT EXTERNE</a></li>
   
</ul>