<?php 

$agent_principal = $this->current_user;

$collaborateur_direct = $this->direct_collaborator;

?>


<style>

#article_container{

   font-size:1.2rem;

   border:1px solid #2e2e2e;

   text-align:justify;
    
}

#article_container_header {

    height:450px;

    position:relative;

    clear:both;
}

#article_container_header_left {

   width:25%;

   line-height:450px;

   height:450px;

   float:left;

   text-align:center;

   border-right:1px solid #2e2e2e;


}

#article_container_header_middle{

   float:left;

   width:50%;

   height:450px;

}

#article_container_header_middle span {

    display:block;

    text-align:center;

    padding-top:3px;

    padding-bottom:3px;

    font-weight:bold;

    border-bottom:1px solid #2e2e2e;
}

#article_container_header_right {

    width:25%;

    height:450px;

    line-height:450px;

    float:left;

    text-align:center;

    border-left:1px solid #2e2e2e;

}

#article_container_section {

    padding:20px;

    border-top:1px solid #2e2e2e;


}

</style>


<article id="article_container">

<header id="article_container_header">

    <div id="article_container_header_left"> <strong>GIE</strong> ESMC</div>

    <div id="article_container_header_middle">
    
       <span>MANUEL DE PROCEDURES METIERS GIE ESMC </span>

       <span>PROCEDURES D’EXPLOITATION DU PROGICIEL MCNP </span>

       <span>PROCEDURE DES ORGANES GIE ESMC </span>

       <span>PROCEDURES DIVISIONS : DETENTRICE / SURVEILLANCE /EXECUTANTE  </span>

       <span>PROCEDURE : DESCRIPTION DE POSTES </span>

       <span>CYCLE : DESCRIPTION DU POSTE </span>

       <span>TITRE DU POSTE : <?php echo $agent_principal ?></span>

       <span>COLLABORATEUR DIRECT : <?php echo $collaborateur_direct ?></span>

       <span>COLLABORATEURS : Tout le reste des Agents</span>
    </div>

    <div id="article_container_header_right">Janv. 2021</div>

</header>


<section id="article_container_section">


   <p style="margin-left:30px;font-weight:bold">MISSION</p>

   <p>
   
      <span>Il collabore dans les <?php echo $agent_principal ?>  avec le <?php echo $collaborateur_direct ?> dans le cadre de l’exécution de la mission du GIE ESMC, des deux (2) Mécanismes (Intégration et Mise sur Chaînes), des trois (3) Volets (Mobilisation, Déploiement et Exploitation), de leurs actions respectives (la mise à disposition et disponibilité, mise en place et opérationnalité, mise en œuvre et maintien dans la pérennité), des activités respectives de chacune de ses actions et des tâches respectives desdites activités, liés aux Aspects (Espaces, Matériels, Outils et Ressources Humaines) grâce aux flux (Supports Marchands, Monnaies Espèce et Virtuelle et Biens, Produits et Services) ; en vue des trois (3) colonnes (Centres, Agences ODD, Chaînes de Valeurs et de Distributions) dans chaque localité de chaque Entité Localité Membre du GIE ESMC.</span>

      <span>Il assure, au niveau de son découpage géographique indiqué dans la dénomination de son poste, la gestion de la structure organisationnelle dont il est le collaborateur direct. </span>

      
   </p>

   <p>
   
    <span>PRINCIPALES TACHES </span>

    <ul>
        <li>Veiller à représenter le GIE ESMC dans ses rapports avec ses adhérents, ses membres et avec les tiers dans son découpage géographique ;</li>


        <li>Veiller, dans le respect des lois en vigueur dans son découpage géographique, à exercer les tâches inhérentes aux Statuts, à l’objet, au règlement intérieur, aux contrats du GIE ESMC, aux directives des Assemblées Générales et du Conseil d’Administration ainsi que toutes décisions adoptées par ces organes du GIE ESMC ;</li>

        <li>Veiller au suivi de ses tâches ;</li>

        <li>Veiller à l’évaluation de ses tâches ;</li>

        <li>Veiller à la réalisation des 17 ODD, leurs 169 cibles et 244 indicateurs dans son découpage géographique ;</li>

        <li>Veiller à l’exécution de(s)(la) rubrique(s) de(s) Tête(s) de Division(s) dont il a la charge dans son découpage géographique ;</li>

        <li>Veiller à l’implication de tout souscripteur aux engagements « lu et approuvé » ;</li>

        <li>Veiller au respect scrupuleux des engagements du GIE ESMC ODD dans le découpage géographique concerné vis-à-vis du souscripteur ;</li>
        
        <li>Veiller au respect scrupuleux des engagements du souscripteur vis-à-vis du GIE ESMC ODD dans le découpage géographique ;</li>

        <li>Veiller au suivi et à l’évaluation des AGENTS Collaborateurs d’AGENT <?php echo $agent_principal ?>, face à leurs divers rôles, axés sur les ODD, les rubriques des Têtes de Divisions, qui concourent à la Mise sur Chaîne des entreprises et industries spécialisées dans chaque domaine d’AGENT <?php echo $agent_principal ?>, et à l’intégration des individus et ménages, OI, dans le Kit de Solvabilité Universelle chargé de Bons de Consommation récurrente conséquents ;</li>

        <li>Veiller à réceptionner, examiner, certifier la conformité aux procédures adaptées et apposer la validation de l’ AGENT <?php echo $agent_principal ?> sur tous les fichiers concernant le GIE ESMC ODD dans son découpage géographique ;</li>
    
        <li>Veiller à ce que toute validation de projet de la Production Commune soit conditionnée par le rapprochement effectué sur le formulaire du Budget en Nature qui dégage le minimum d’écarts possibles ;</li>

        <li>Veiller à ce que chaque projet de la Production Commune soit affecté au gestionnaire indiqué pour une application systématique et rigoureuse des Opérations MCNP ;</li>

        <li>Veiller à ce que la mise à disposition des Outils (documents) de la Production Commune soit subordonnée à la signature préalable de l’engagement de confidentialité par chacun de leurs utilisateurs ;</li>

        <li>Veiller à assurer la bonne fin d’exécution de ses tâches d’AGENT <?php echo $agent_principal ?> et la satisfaction globale de chacun des acteurs sur le terrain dans son découpage géographique.</li>
    </ul>
   
   </p>

   <p style="margin-left:30px;font-weight:bold">RESULTATS ATTENDUS</p>

   <p>
   
     <ul>
     
         <li>Le suivi de ses tâches est fait ;</li>
        
        <li>L’évaluation de ses tâches est faite ;</li>

        <li>La veille à la réalisation des 17 ODD, leurs 169 cibles et 244 indicateurs dont il a la charge est assurée ;</li>

        <li>La veille à l’exécution de(s)(la) rubrique(s) de(s) Tête(s) de Division(s) dont il a la charge est assurée ;</li>

        <li>La veille à l’exécution de(s)(la) rubrique(s) de(s) Tête(s) de Division(s) dont il a la charge est assurée ;</li>

        <li>Les engagements du GIE ESMC ODD dans son découpage géographique vis-à-vis du souscripteur sont scrupuleusement respectés ;</li>

        <li>Les engagements du souscripteur vis-à-vis du GIE ESMC ODD dans son découpage géographique sont scrupuleusement respectés ;</li>

        <li>La veille au suivi et à l’évaluation des AGENTS Collaborateurs d’AGENT <?php echo $agent_principal ?>, face à leurs divers rôles, axés sur les ODD, les rubriques des Têtes de Divisions, qui concourent à la Mise sur Chaîne des entreprises et industries spécialisées dans chaque domaine d’AGENT <?php echo $agent_principal ?>, et à l’intégration des individus et ménages, OI, dans le Kit de Solvabilité Universelle chargé de Bons de Consommation récurrente conséquents est faite;</li>
     
        <li>La veille à la réception, l’examen, la certification de la conformité aux procédures adaptées et l’apposition de la validation de l’ AGENT <?php echo $agent_principal ?> sur tous les fichiers, sont assurés ;</li>

        <li>La veille à ce que toute validation de projet de la Production Commune soit conditionnée par le rapprochement effectué sur le formulaire du Budget en Nature qui dégage le minimum d’écarts possibles est assurée ;</li>

        <li>La veille à ce que chaque projet de la Production Commune soit affecté au gestionnaire indiqué pour une application systématique et rigoureuse des Opérations MCNP est assurée ;</li>

        <li>La veille à ce que la mise à disposition des Outils (documents) de la Production Commune soit subordonnée à la signature préalable de l’engagement de confidentialité par chacun de leurs utilisateurs est assurée ;</li>

        <li>La bonne fin d’exécution de ses tâches d’AGENT <?php echo $agent_principal ?> et la satisfaction globale de chacun des acteurs sur le terrain dans son découpage géographique sont assurées.
</li>


     </ul>
   
   </p>


   <p style="margin-left:30px;font-weight:bold">CONNAISSANCES ET APTITUDES</p>

   <ul>
   
      <li>Etre titulaire au minimum d’un BAC+5 en sciences de gestion et/ou spécialisé en management des projets ou tout autre diplôme équivalent ; </li>
   
      <li>Justifier d’au moins trois (3) années d’expérience dans son domaine de spécialité ; </li>

      <li>Bonne aptitude à travailler en équipe et sous pression ; </li>

      <li>Bonne expression écrite et orale ; </li>

      <li>Parfaite maitrise du Progiciel MCNP, des logiciels de gestion et de traitement de texte. </li>

   </ul>

   <p style="margin-left:30px;font-weight:bold">LANGUES</p>

   <ul>
   
       <li>Parfaite connaissance de la langue française </li>

       <li>Parfaite connaissance des langues officielles dans les zones de couverture du GIE ESMC</li>

       <li>La connaissance de toute autre langue est un atout.</li>
   
   </ul>

</section>


</article>