<style>
#page_title{
    text-align: center;
    margin-bottom: 35px;
}

#page_direction_container{
    clear:both;
    width: 100%;
}

#page_direction_container_left{
    width: 50%;
    position: relative;
    left:0;
}

#page_direction_container_right{
    width: 50%;
    position: relative;
    right: 0;
    float: right;
    top: -67px;
}


</style>




<h3 id="page_title">TITRE DU POSTE : Agent Technopole Juridique</h3>

<div id="page_direction_container">

  <div id="page_direction_container_left">

    <h3>SUPERIEUR HIERARCHIQUE : Gérant </h3>
  
  </div>

  <div id="page_direction_container_right">

    <h3>COLLABORATEURS : Tout le reste du personnel</h3>
    
  </div>
</div>


<blockquote>  PRINCIPALES TACHES :</blockquote>

<ol>
    <li>Contrats et Convention (Négociation ; Formalisation et Gestion des Relations Contractuelles et Conventionnelles)</li>
    <li>Protections Légales</li>
    <li>Titres Divers</li>
    <li>Assurances</li>
    <li>Garanties</li>
    <li>Pré Contentieux et Contentieux (y Compris le recouvrement de créances)</li>
    <li>Portefeuille de la Propriété Intellectuelle MCNP/ESMC/PC</li>
    <li>Portefeuille des Suretés </li>
    <li>Veille Juridique et règlementaire</li>
    <li>Intégration de la Plateforme ESMC dans l’environnement Economico- Social National Communautaire et International.</li>
    <li>Documentation Juridique</li>
    <li>Assistance et des Concours Divers</li>
    <li>Alertes</li>
    <li>Réclamations</li>
    <li>Recouvrements</li>
    <li>Règlements</li>
    <li>Tickets de Supports</li>
    
    
</ol>

