<style>
#page_title{
    text-align: center;
    margin-bottom: 35px;
}

#page_direction_container{
    clear:both;
    width: 100%;
}

#page_direction_container_left{
    width: 50%;
    position: relative;
    left:0;
}

#page_direction_container_right{
    width: 50%;
    position: relative;
    right: 0;
    float: right;
    top: -67px;
}


</style>




<h3 id="page_title">TITRE DU POSTE : Agent Technopole Stocks</h3>

<div id="page_direction_container">

  <div id="page_direction_container_left">

    <h3>SUPERIEUR HIERARCHIQUE : Agent Technopole Administratif </h3>
  
  </div>

  <div id="page_direction_container_right">

    <h3>COLLABORATEURS : Tout le reste du personnel</h3>
    
  </div>
</div>


<blockquote>  PRINCIPALES TACHES :</blockquote>

<ol>
    <li>Gestion des Fournitures et Consommables </li>
    <li>Gestion du carburant</li>
    <li>Gestion des Kits</li>
</ol>


<h3>PROCEDURES A UTILISER</h3>

<ul>
    <li><a href="/administration/detailstachemembreasso/id/15" target= "_blanc">PROCEDURE : GESTION DES FOURNITURES ET CONSOMMABLES</a></li>
    <li><a href="/administration/detailstachemembreasso/id/6" target= "_blanc">PROCEDURE : GESTION DU CARBURANT</a></li>
    <li><a href="/administration/detailstachemembreasso/id/5" target= "_blanc">PROCEDURE : GESTION DES KITS</a> </li>
</ul>
