<h3 style="text-align:center">LA TECHNOPOLE</h3>
<p>
La Technopole s’occupe, sur la plateforme ESMC, de l’<strong>>Administration et de la Réglementations </strong> qui s’appliquent aux biens, produits et services liés aux 17 ODD, à leurs 169 cibles et aux 244 indicateurs, à travers les aspects de la Production Commune que sont :
<ul>
    <li>Aspect Outils de la Production Commune (Site internet, plateforme ESMC ; progiciel MCNP, manuels de procédures, d’utilisation et de déploiement intégrés ; autres logiciels et progiciels ;  périphériques, KIT de solvabilité universelle et KIT technopole ; édition de livres, d’audio et vidéos ; multimédias ; certificats de propriété intellectuelle ; divers contrats, visuels …), </li>
    <li>Aspect Espaces de la Production Commune (Centres ESMC ; Unités industrielles ; centrales d’achat ; centrales de production, centrales de transformation ; centrales de vente, entrepôts ; marchés ; magasins ; boutiques et guichets uniques),</li>
    <li>Aspect Matériels de la Production Commune (TIC industrielles, centres de données ; connectivité ;  périphériques ; équipements industriels mécaniques fixes et roulants ; immeubles, meubles et autres matériels.)</li>
    <li>Aspect Ressources Humaines de la Production Commune (Pionniers, collaborateurs : salariés, prestataires de la PC, consultants ; Membres Fondateurs : MF 107, MF 11 000, CMFH et tout titulaire de Comptes Marchands MCNP).</li>
</ul>

</p>
<p><u>Tâches</u></p>

<p>La Technopole a pour tâches de : 
 <ul>
   <li>•	Mobiliser : les ressources suivant les Aspects sur les interfaces via les Activités qui s’y exercent par les clients,</li>
   <li>•	Déployer : Mettre en place et rendre opérationnels les aspects de la Production Commune : Outils, Espaces, Matériels et Ressources Humaines, </li>
   <li>•	Exploiter : Traduire dans les faits les résultats de la Production Commune, dans son rôle de Technopole lié aux aspects dans les rubriques administratives des <a class="dropdown-item" href="<?php echo $this->baseUrl();?>/administration/detailstachemembreasso/id/1"> achats</a>, des stocks, des immobilisations, des techniques (système, réseau et développement), des services généraux, de la sécurité, gestion des ressources humaines, et la rubrique réglementation (procédures juridiques, ….), de même que des Opérations Exploitation MCNP TECHNOPOLE : Souscriptions, Expressions, Règlements, Rapprochements, Compensations, Annulations, Archivages, Destructions et Tableaux de Bords,  sur la plateforme ESMC, afin que ses résultats soient conformes à la déclaration universelle des Droits humains dans son article 25, aux 17 ODD, aux PND et à tous les programmes de développement durable.</li>
 </ul>
 <p>Il s’agit de : 
   <ul>
       <li>Mettre sur la chaîne de la Production Commune, les entreprises et industries publiques/privées/sociales et les maisons d’habitation à travers le mécanisme mise sur chaîne grâce aux KIT  de Solvabilité Universelle (personnes morales).  </li>
       <li>Intégrer tout individu dans la Production Commune au moyen des types d’acteurs des étapes obligatoires : n°1, Offreurs d’Intégration (OI) et n°2,  Offreurs de KIT  de Solvabilité Universelle (OKSU) : </li>
       <li>Cautionner l’enlèvement des BPS auprès des fournisseurs utilisateurs, spécifiques et externes contre Ventes Réciproques.</li>
       <li>Réceptionner, examiner, certifier la conformité aux procédures adaptées et valider les fichiers des dossiers des souscripteurs pour soi et pour tiers, des Acheteurs Revendeurs en ligne contre OPI, des Prestataires de la Production Commune et ceux des Achat-Vente Réciproques, en tant que fournisseurs selon les six catégories d’acteurs des étapes obligatoires de la PC : OI, OKSU, OBPSD (Offreurs de Biens, Produits et Services Dématérialisés), OBPS (Offreurs de Biens, Produits et Services), OP (Offreurs de Projets) et OT (Offreurs de Travail)  et assurer la bonne fin d’exécution des tâches visant la satisfaction globale de chacune de ces catégories d’acteurs.</li>
       <li>Faire coïncider les offres et les demandes des fournisseurs utilisateurs, spécifiques et externes. </li>
       <li>Assurer l’opération de compensation pour dégager le minimum d’écarts possibles.</li>
       <li>Faire combler ces écarts en collaboration avec les services de la FILIERE/ACNEV qui orientent les fournisseurs utilisateurs, spécifiques et externes vers l’achat en centrale conformément à la convention de collaboration entre l’ESMC…et ces derniers dans le cadre de la réalisation par le marché des 17 ODD.</li>
   </ul>
 </p>
</p>

<p><strong><u>Exécution des tâches de la Technopole, <span style="color:#FF0000">étape par étape</span> </u></strong></p>

<p>Ces tâches seront exécutées depuis les Guichets Uniques (GUUI) jusqu’aux Centres en passant respectivement par les Boutiques, les Magasins, les Marchés, les Entrepôts et les Centrales selon les six catégories d’acteurs des étapes obligatoires de la PC : OI, OKSU, OBPSD (Offreurs de Biens, Produits et Services Dématérialisés), OBPS (Offreurs de Biens, Produits et Services), OP (Offreurs de Projets) et OT (Offreurs de Travail) Offreurs qui sont tous, Souscripteurs aux quatre (04) Activités ESMC, soumis à l’un des deux mécanismes grâce à leur KIT de Solvabilité Universelle.</p>

<p><strong> NB : LA MENTION « PROCEDURES ADAPTEES » CI-DESSOUS, FAIT REFERENCE AU MANUEL D’UTILISATEURS DU PROGICIEL <span style="color:#FF0000">MCNP</span>.</strong></p>

<p><strong><u>Par rapport aux Offreurs d’intégration </u></strong></p>
<p>
 <ul>
     <li>Réceptionner, examiner, certifier la conformité à la procédure adaptée et apposer la validation de la Technopole sur les fichiers mis à jour des Offreurs d’intégration avec liste et sans liste, depuis les GUIU jusqu’aux Centres,</li>
     <li>Réceptionner, examiner, certifier la conformité à la procédure adaptée et apposer la validation de la TECHNOPOLE sur les fichiers KIT de solvabilité universelle et KIT Technopole des Offreurs d’intégration avec liste et sans liste depuis les GUIU jusqu’aux Centres, </li>
     <li>Apposer la validation de la TECHNOPOLE depuis les GUIU jusqu’aux Centres sur le dossier des OKSU marchands personnes physiques et/ou OKT (Offreurs de KIT Technopole) au profit des offreurs d’intégration sans liste,  </li>
     <li>Apposer la validation de la TECHNOPOLE depuis les GUIU jusqu’aux Centres sur le dossier des OKSU non marchands personnes physiques et/ou OKT au profit des offreurs d’intégration sans liste,  </li>
     <li>Apposer la validation de la TECHNOPOLE depuis les GUIU jusqu’aux Centres sur le dossier de leur police d’assurances, </li>
     <li>Apposer la validation de la TECHNOPOLE depuis les GUIU jusqu’aux Centres sur le dossier OKSU marchands pour les PBF et/ou OKT au profit des Offreurs d’Intégration sans liste, </li>
     <li>Apposer la validation de la TECHNOPOLE depuis les GUIU jusqu’aux Centres sur le dossier OKSU non marchands pour les Partenaires ODD et/ou OKT au profit des Offreurs d’Intégration sans liste  et </li>
     <li>Assurer la bonne fin d’exécution de ces tâches et la satisfaction globale de chacun des acteurs de la catégorie OI sur le terrain.</li>
 </ul>
</p>

<p><strong><u>Par rapport aux OKSU </u></strong></p>

<p>
  <ul><li>•	Réceptionner, examiner, certifier la conformité aux procédures adaptées et apposer la validation de la TECHNOPOLE sur les fichiers des dossiers des OKSU avec liste et sans liste, </li></ul>
  
</p>
<p>Contre BPS :	
  <ul>
    <li>à acheter : Achat Réciproques  (Appliquer les procédures adaptées), </li>
    <li>à produire : Budget en Nature  (Appliquer les procédures adaptées</li>
    <li>à transformer : Budget en Nature  (Appliquer les procédures adaptées), </li>
    <li>à vendre : Vente Réciproques  (Appliquer les procédures adaptées).</li>
  </ul>
</p>

<p>Contre OPI :
 <ul>
   <li>Souscription récurrente et pérenne (Appliquer les procédures de contrôle adaptées) </li>
   <li>Souscription non récurrente (Appliquer les procédures de contrôle adaptées) et </li>
 </ul>
</p>
<p>
 <ul>
  <li>Assurer la bonne fin d’exécution de ces tâches et la satisfaction globale de chacun des acteurs de la catégorie OKSU sur le terrain.</li>
</ul>
</p>
<p><strong><u>Par rapport aux OBPSD</u></strong>
  <ul>
    <li>Réceptionner, examiner, certifier la conformité aux procédures adaptées et  apposer la validation de la TECHNOPOLE sur les fichiers des dossiers des OBPSD :</li>
    <li>Souscription récurrente et pérenne (Appliquer les procédures de contrôle adaptées) </li>
    <ul>
      <li>Souscription non récurrente (Appliquer les procédures de contrôle adaptées) et  </li>
    </ul>
    <li>Assurer la bonne fin d’exécution de ces tâches et la satisfaction globale de chacun des acteurs de la catégorie OBPSD sur le terrain.</li>
  </ul>
</p>

<p><strong><u>Par rapport aux OBPS</u></strong>
<ul>
  <li>Réceptionner, examiner, certifier la conformité aux procédures adaptées et   apposer la validation de la TECHNOPOLE sur les fichiers des dossiers des souscripteurs OBPS :</li>
  <span>Contre BPS :</span>
  <ul>
    <li>à acheter : Achat Réciproques  (Appliquer les procédures adaptées), </li>
    <li>à produire : Budget en Nature  (Appliquer les procédures adaptées), 
      <ul>
        <li>à transformer : Budget en Nature  (Appliquer les procédures adaptées), </li>
        <li>à vendre : Vente Réciproques  (Appliquer les procédures adaptées).</li>
      </ul>
    </li>
  </ul>
  <span>Contre OPI :</span>
  <ul>
    <li>Caution d’enlèvement :</li>
    <ul>
      <li>Avec Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn non anticipé</li>
      <li>(Appliquer les procédures adaptées)</li>
      <li>Sans Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn non anticipé (Appliquer les procédures adaptées)</li>
      <li>Avec Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn  anticipé (Appliquer les procédures adaptées)</li>
    </ul>
    <li>Sans Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn anticipé (Appliquer les procédures adaptées) et  </li>
  </ul>
  <li>Assurer la bonne fin d’exécution de ces tâches et la satisfaction globale de chacun des acteurs de la catégorie OBPS sur le terrain.</li>
</ul>

</p>

<p>
<strong><u>Par rapport aux OP</u></strong>
<li>Réceptionner, examiner, certifier la conformité aux procédures adaptées et   apposer la validation de la TECHNOPOLE sur les fichiers des dossiers des OP : </li>
<span>Contre BPS :</span>
<ul>
  <li>	à acheter : Achat Réciproques  (Appliquer les procédures adaptées), </li>
  <li>	à produire : Budget en Nature/ OP (Appliquer les procédures adaptées</li>
  <li>	à transformer : Budget en Nature /OP (Appliquer les procédures adaptées), </li>
  <li>	à vendre : Vente Réciproques  (Appliquer les procédures adaptées).</li>
</ul>
<span>Contre OPI :</span>
<ul>
 <li>BNOP :</li>
  <ul>
    <li>o	Avec Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn non anticipé,</li>
    <li>o	(Appliquer les procédures adaptées),</li>
    <li>o	Sans Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn non anticipé (Appliquer les procédures adaptées),</li>
    <li>o	Avec Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn  anticipé (Appliquer les procédures adaptées),</li>
    <li>o	Sans Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn anticipé (Appliquer les procédures adaptées) et </li>
  </ul>
  <li>•	Assurer la bonne fin d’exécution de ces tâches et la satisfaction globale de chacun des acteurs de la catégorie OP sur le terrain.</li>
</ul>
</p>

<p>
  <strong>NB : </strong>
  <ul>
    <li><i>Toute validation de projet de la Production Commune est conditionnée par le rapprochement effectué sur le formulaire du Budget en Nature qui dégage le minimum d’écarts possibles.</i></li>
    <li><i>Chaque projet de la Production Commune est affecté au gestionnaire indiqué pour application systématique et rigoureuse des Opérations MCNP : souscription, expression, règlement, rapprochement… assorties de tableau de bord.</i></li>
  </ul>
</p>
<p><strong><u>Par rapport aux OT</u></strong>
<ul>
  <li>Réceptionner, examiner, certifier la conformité aux procédures adaptées et   apposer la validation de la TECHNOPOLE sur les fichiers des dossiers des OT : </li>
  <span>Contre BPS :</span>
  <ul>
    <li>à acheter : Achat Réciproques  (Appliquer les procédures adaptées), </li>
    <li>à produire : Budget en Nature/ OT (Appliquer les procédures adaptées), </li>
    <li>à transformer : Budget en Nature /OT (Appliquer les procédures adaptées), </li>
    <li>à vendre : Vente Réciproques  (Appliquer les procédures adaptées).</li>
  </ul>
  <span>Contre OPI :
    <ul>
      <li>BNOT :
        <ul>
          <li>Avec Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn non anticipé,</li>
          <li>(Appliquer les procédures adaptées),</li>
          <li>Sans Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn non anticipé (Appliquer les procédures adaptées),</li>
          <li>Avec Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn  anticipé (Appliquer les procédures adaptées),</li>
        </ul>
      </li>
      <li>Sans Engagement de Livraison Irrévocable/ELI contre OPI/BAi/BAn anticipé (Appliquer les procédures adaptées) et </li>
    </ul>

  </span>
  <li>Assurer la bonne fin d’exécution de ces tâches et la satisfaction globale de chacun des acteurs de la catégorie OT sur le terrain.</li>
</ul>

</p>

