<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modifier un mobilisateur</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="editmobilisateur">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
  
    





<div class="form-actions">
<input name="id_mobilisateur" type="hidden" id="id_mobilisateur" value="<?php echo $this->mobilisateur->id_mobilisateur; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier le mobilisateur</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








