<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

    <div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Ajouter un TDR</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addtdr">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
  
  

<div class="control-group">
<label class="control-label" for="id_filiere">Filière * </label>
<div class="controls">
<?php 
$filiere_m = new Application_Model_EuFiliereMapper();
$filiere = $filiere_m->fetchAll();
if(count($filiere) > 0){?>
<select name="id_filiere" id="id_filiere" required >
<option value="">Choisir la filière </option>
<?php foreach ($filiere as $value) { ?>
<option value="<?php echo $value->id_filiere; ?>"><?php echo $value->nom_filiere;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>

    
<div class="control-group">
<label class="control-label" for="libelle">Libellé du TDR *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="libelle" id="libelle" placeholder="Libellé du TDR" required>
</div>
</div>

<div class="control-group">
<label class="control-label" for="description">Description * </label>
<div class="controls">
<textarea name="description" id="description" placeholder="Description" class="ckeditor" required></textarea>
</div>
</div>
   
<div class="control-group">
<label class="control-label" for="fichier">Document du TDR *</label>
<div class="controls">
<input name="fichier" type="file" id="fichier" class="input-xxlarge" required  />
</div>
</div>

    
<div class="control-group">
<label class="control-label" for="code_membre">Code Membre Fournisseur </label>
<div class="controls">
<input class="input-xlarge" type="text" name="code_membre" id="code_membre" placeholder="Code Membre Fournisseur">
</div>
</div>



<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter le TDR</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








