<?php $sessionmembre = new Zend_Session_Namespace('membre');?>
  <div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Details d'une proposition</p></blockquote>
  
    
  
<div class="control-group">
<label class="control-label" for="id_tdr">TDR</label>
<div class="controls">
<?php if($this->tdr_propo->id_tdr > 0){
        $tdr = new Application_Model_EuTdr();
        $tdrM = new Application_Model_EuTdrMapper();
        $tdrM->find($this->tdr_propo->id_tdr, $tdr);
        echo $tdr->libelle;
      }
?>
</div>
</div>

  
<div class="control-group">
<label class="control-label" for="type_propo">Type de la proposition</label>
<div class="controls">
<?php if($this->tdr_propo->type_propo > 0){
        $tdr = new Application_Model_DbTable_EuTypePropo();
        $tdr->find($this->tdr_propo->type_propo);
        $row = $result->current();
        echo $row->libelle_type_propo;
      }
?>
</div>
</div>

<div class="control-group">
<label class="control-label" for="libelle">Libelle  de la proposition</label>
<div class="controls">
<?php echo $this->tdr_propo->libelle; ?>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="description">Description </label>
<div class="controls">
<?php echo $this->tdr_propo->description; ?>
</div>
</div>

<div class="control-group">
<label class="control-label" for="fichier">Document  de la proposition</label>
<div class="controls">


</div>
</div>
    
    
    echo $this->tdr_propo->code_membre;
<div class="control-group">
<label class="control-label" for="code_membre">Code Membre </label>
<div class="controls">
<?php if($this->tdr_propo->code_membre != ""){
        $membremorale = new Application_Model_EuMembreMorale();
        $membremoraleM = new Application_Model_EuMembreMoraleMapper();
        $membremoraleM->find($this->tdr_propo->code_membre, $membremorale);
        echo $membremorale->raison_sociale;
      }
?>
</div>
</div>



<div class="control-group">
<label class="control-label" for="datecreation">Date  </label>
<div class="controls">
<?php echo $this->tdr_propo->datecreation; ?>
</div>
</div>
    
    
<div class="control-group">
<label class="control-label" for="id_utilisateur">Utilisateur</label>
<div class="controls">
<?php if($this->tdr_propo->id_utilisateur > 0){
        $utilisateur = new Application_Model_EuUtilisateur();
        $utilisateurM = new Application_Model_EuUtilisateurMapper();
        $utilisateurM->find($this->tdr_propo->id_utilisateur, $utilisateur);
        echo $utilisateur->nom_utilisateur." ".$utilisateur->prenom_utilisateur;
      }
?>
</div>
</div>

    








</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








