<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Modifier  un proces verbal</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="edittdr">
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = "";?>
    </div>
  <?php }?>
  
    

<div class="control-group">
<label class="control-label" for="id_tdr">TDR * </label>
<div class="controls">
<?php 
$tdr_m = new Application_Model_EuTdrMapper();
$tdr = $tdr_m->fetchAll();
if(count($tdr) > 0){?>
<select name="id_tdr" id="id_tdr" required >
<option value="">Choisir le TDR </option>
<?php foreach ($tdr as $value) { ?>
<option value="<?php echo $value->id_tdr; ?>" <?php if($this->tdr_pv->id_tdr == $value->id_tdr){?> selected="selected"<?php }?>><?php echo $value->libelle;?></option>
<?php } ?>
</select>
<?php } ?>
</div>
</div>



<div class="control-group">
<label class="control-label" for="code_membre">Code Membre *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="code_membre" id="code_membre" placeholder="Code Membre" value="<?php echo $this->tdr_pv->code_membre;?>" required>
</div>
</div>


    
<div class="control-group">
<label class="control-label" for="libelle">Libellé  de la demande *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="libelle" id="libelle" placeholder="Libellé de la demande" value="<?php echo $this->tdr_pv->libelle;?>" required>
</div>
</div>

<div class="control-group">
<label class="control-label" for="description">Description * </label>
<div class="controls">
<textarea name="description" id="description" placeholder="Description" class="ckeditor" required><?php echo $this->tdr_pv->description;?></textarea>
</div>
</div>
   
<div class="control-group">
<label class="control-label" for="fichier">Document  de la demande *</label>
<div class="controls">
<input name="fichier" type="file" id="fichier" class="input-xxlarge"   />
</div>
</div>

   


<div class="control-group">
<label class="control-label" for="montant_retenu">Montant retenu *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="montant_retenu" id="montant_retenu" placeholder="Montant retenu" value="<?php echo $this->tdr_pv->montant_retenu;?>" required>
</div>
</div>




<div class="control-group">
<label class="control-label" for="montant_revu">Montant revu </label>
<div class="controls">
<input class="input-xlarge" type="text" name="montant_revu" id="montant_revu" placeholder="Montant revu" value="<?php echo $this->tdr_pv->montant_revu;?>" >
</div>
</div>






<div class="form-actions">
<input name="fichierold" type="hidden" id="fichierold" value="<?php echo $this->tdr_pv->fichier; ?>" />  
<input name="id_tdr_pv" type="hidden" id="id_tdr_pv" value="<?php echo $this->tdr_pv->id_tdr_pv; ?>" />  
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Modifier  le proces verbal</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








