<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<script src="<?php echo $this->baseUrl();?>/approuver.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf-8">
		
  $(document).ready(function() {
    $('#example').dataTable({
       "sPaginationType": "full_numbers",
       "aaSorting":[]
    });
  });
  
</script>
        
<script type="text/javascript">

function checkAllInput(form,action) {
   var i = document.forms[form].getElementsByTagName("input"); 
   for(var cpt = 0; cpt < i.length; cpt++) { 
      i[cpt].checked = (action)? true : false ;
   }
}

</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p> Liste des Engagements de Livraisons Irrévocables (ELI) proposés  </p></blockquote>
  
  <?php if(isset($sessionmembre->error) && $sessionmembre->error!="") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = ""; ?>
    </div>
  <?php } ?>
  
<?php 

if(count($this->entries) > 0)  { 
?> 


<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
	   <thead>
			  <tr>
				  <th>Date</th>
				  <th>TDR</th>
				  <th>Référence</th>
				  <th>Désignation</th>
				  <th>Montant</th>
				  <th>Détails</th>				  
			  </tr>
	   </thead>
<tbody>
<?php 
foreach ($this->entries as $entry):
$membremoral = new Application_Model_EuMembreMorale();
$m_mapmoral = new Application_Model_EuMembreMoraleMapper();
$findmembre = $m_mapmoral->find($entry->code_membre,$membremoral);

$tdr = new Application_Model_EuTdr();
$m_tdr = new Application_Model_EuTdrMapper();
$m_tdr->find($entry->id_tdr,$tdr);
?>
<tr>
    <td> <?php echo datejourfr($entry->date_eli); ?> </td>
    <td> <?php echo($entry->libelle); ?></td>
    <td> <?php echo($entry->numero_eli); ?></td>
    <td> <?php echo($entry->libelle_eli); ?></td>
    <td> <?php echo($entry->montant_eli);?></td>
	
    <td>
	    <div align="center">
		     <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/tdr/detaileli/id/<?php echo $entry->id_eli; ?>"><i class="icon-info-sign icon-white"></i>Détails</a>
		</div>
	</td>
</tr>
<?php 
endforeach; 
?>
</tbody>
</table>

<?php } else { ?>
<div class="alert alert-info">
  Aucun Engagement de Livraison Irrévocable enregistré 
</div>
<?php } ?>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








