<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste des AVR</p></blockquote>
<?php if(count($this->entries)>0){ //echo count($this->entries);?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size: 10px;">
						  <thead>
							  <tr>
								  <th>BPS Vendu</th>
								  <th>BPS Acheté</th>
								  <th>Code Membre</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php if($entry->id_bps_vendu_achat_vente_reciproque > 0){
      	$t_bps_vendu_avr =  new Application_Model_DbTable_EuBpsVenduAvr();
       $select = $t_bps_vendu_avr->select();
       $select->where('id_bps_vendu_achat_vente_reciproque = ?', $entry->id_bps_vendu_achat_vente_reciproque);
       $bps_vendu_avr = $t_bps_vendu_avr->fetchAll($select);
echo $bps_vendu_avr[0]->nom_bps_vendu;} ?></td>
      <td><?php if($entry->id_bps_achete_achat_vente_reciproque > 0){
      	$t_bps_achete_avr =  new Application_Model_DbTable_EuBpsAcheteAvr();
       $select = $t_bps_achete_avr->select();
       $select->where('id_bps_achete_achat_vente_reciproque = ?', $entry->id_bps_achete_achat_vente_reciproque);
       $bps_achete_avr = $t_bps_achete_avr->fetchAll($select);
echo $bps_achete_avr[0]->nom_bps_achete;} ?></td>
      <td><?php echo $entry->code_membre_avr; ?></td>
      <td><div align="center">
<?php if($entry->validationachatetventereciproque == 1){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>
			</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun avr  enregistré 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








