<style>
blockquote > h3{
   text-transform: uppercase;
}

</style>

<article>
<blockquote>
  <h3>Accord de partenariat</h3>
</blockquote>

<p>ENTRE LES SOUSSIGNEES :</p>
<section>
<p><strong>ESMC (Entreprise Sociale de Marché Commun) SARL U</strong> au capital de 1 000 000 FCFA ; Siège social : Lomé (TOGO), Wuiti-Atchati, Angle rues Sagouda, Kiyeou et Bandjeli, BP 30038 ; Immatriculée au RCCM sous le numéro TG-LOM 2018 M 203 ; Représentée par son Gérant <strong>Monsieur Essohamlon SAMA,</strong>  </p>
<p>Ci-après dénommée <strong>« ESMC »</strong> ;</p>
<p>D’une part,</p>
<p>Et</p>
<textarea name="" id="" cols="30" rows="10" placeholder="…………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………, "></textarea>
<p>Ci-après dénommée <input type="text" placeholder="« ……………………… »."></p>
<p>D’autre part, </p>
<p>Ci-dessous collectivement désignées <strong>« Parties »</strong> et individuellement <strong>« Partie »</strong>. </p>
<p><strong>Article 1 : Objet</strong></p>
<p>Le présent Contrat a pour objet de poser les bases du partenariat entre ESMC et ………. </p>
<p><strong>Article 2 : Déploiement de la plateforme ………………</strong></p>
<p style="margin-left:61px"><strong>2.1. Engagement de ………………</strong></p>
<p>………………… s’engage à déployer sa plateforme au profit des partenaires personnes morales de ESMC (SFD, etc ….).</p>
<p>…………………… signera des contrats d’exploitation avec chacun desdits partenaires.</p>
<p style="margin-left:61px"><strong>2.2. Engagement de ESMC</strong></p>
<p>
ESMC s’engage à :
<ul>
<li>Se servir de la plateforme de ………….. pour digitaliser les services à rendre aux Utilisateurs de sa plateforme,</li>
<li>Héberger les serveurs de ……….. dans ses locaux,</li>
<li>Assurer la connectivité à …………. pour ses prestations,</li>
<li>Héberger dans ses Guichets Uniques d’Intégration Universelle (GUIU), ses Boutiques, ses Magasins, ses Marchés et ses Entrepôts, les Terminaux de Paiement Electronique (TPE) de ………...</li>
</ul>
</p>
<p style="margin-left:61px">2.3. Mise en œuvre du déploiement</p>
<p>Pour le déclenchement du partenariat, ……………… installera dans les locaux de ESMC et partout où besoin sera, la logistique appropriée de sa plateforme. </p>
<p>A chaque fois qu’un service est désigné par ESMC pour être digitalisé, les Parties s’engagent réciproquement :</p>
<ul>
<li> A arrêter de commun accord, les modalités de paramétrage de leurs logiciels respectifs,</li>
<li>A affecter leur capital humain respectif nécessaire à la digitalisation dudit service.</li>
</ul>
</section>

<section>
<p style="margin-left:61px"><strong><u>2.4. Coût de la clientèle apportée par ESMC</u></strong></p>
<p>Pour avoir bénéficié de sa clientèle, ………… servira à ESMC une commission de 30% sur les frais d’adhésion à la plateforme de ……………… payés par ladite clientèle constituée des partenaires personnes morales de ESMC (SFD, etc ….). </p>
<p style="margin-left:61px"><strong><u>Article 3 : Emission de Cartes Magnétiques</u></strong></p>
<p>……………. émettra, contre paiement des Utilisateurs de la plateforme ESMC, des Cartes Magnétiques à leur profit. </p>
<p>Ces Cartes Magnétiques seront distribuées par les Systèmes Financiers Décentralisés partenaires de ESMC.</p>
<p>Ces Cartes Magnétiques porteront les logos de …………. et de ESMC. </p>
<p>…………………. paiera à ESMC, une commission de 10% sur le prix de vente de ces Cartes Magnétiques.</p>
<p style="margin-left:61px"><strong><u>Article 4 : Sous-traitance de l’émission des Bons d’Achat neutres (BAn)</u></strong></p>
<p>Par le présent contrat, ESMC confie à ……………….., la sous-traitance non-exclusive de l’émission des BAn au profit des Utilisateurs de la plateforme ESMC.</p>
<p>……………….. ayant volontairement accepté cette mission, les deux parties ont convenu ce qui suit :  </p>
<p style="margin-left:61px"><strong><u>4.1. Paiement par avance sur les comptes bancaires de ESMC</u></strong></p>
<p>Avant de pouvoir sous-traiter les BAn, ……………… payera sur l’un des comptes de ESMC ouverts dans les livres des banques de la place, le montant correspondant.</p>
<p>A chaque fois que le paiement est effectué par ……………., ESMC lui affectera le BAn correspondant majoré d’une marge.</p>
<p>Au cas où le montant payé par ……………… sur l’un des comptes bancaires de ESMC est supérieur ou égal à deux cent millions (200.000.000) francs CFA, cette marge est d’au moins 6,5% dudit montant.</p>
<p>Au cas où le montant payé par ……………….. sur l’un des comptes bancaires de ESMC est inférieur à deux cent millions (200.000.000) francs CFA, cette marge est d’au plus 6,5% dudit montant.</p>
<p style="margin-left:61px"><strong><u>4.2. Encaissement par ………….. des paiements des Utilisateurs de la plateforme ESMC contre affectation de BAn à leur profit </u></strong></p>
<p>…………… encaissera les paiements des Utilisateurs de la plateforme ESMC sur le compte de ESMC préalablement ouvert dans les livres de ……………..    </p>
</section>
<section>
<p>Contre les paiements des Utilisateurs de la plateforme ESMC destinés à la souscription aux activités de cette dernière, ………… leur affectera les BAn correspondants.  </p>
<p>Les BAn affectés par ………… aux Utilisateurs de la plateforme ESMC ont un lien direct avec leur Compte Marchand MCNP. Par conséquent…….. n’est en aucun cas engagé par la réalisation des activités de ESMC. </p>
<p>Au cas où pour une raison ou une autre il est avéré que le BAn affecté par ESMC à ………… ne pourra pas être utilisé, ESMC retournera le montant correspondant au reliquat du BAn non utilisé après  déduction de la marge correspondante.   </p>
<p style="margin-left:61px"><strong><u>Article 5 : Confidentialité</u></strong></p>
<p>Les deux parties s’engagent à protéger toute information communiquée par l’une à l’autre à titre strictement confidentiel.</p>
<p>Les deux parties s’engagent à n’utiliser les informations mises à leur disposition que dans le cadre strict de leurs relations telles que convenues dans le présent contrat. </p>
<p>Les engagements de confidentialité énoncés au présent article s'appliquent pendant toute la durée du présent Contrat et de ses prorogations et restent en vigueur sans limite de temps après sa résiliation ou son expiration.</p>
<p><strong><u>Article 6 : Comportement loyal et bonne foi</u></strong></p>
<p>Les deux parties s’engagent  mutuellement à un  partenariat de bonne foi et notamment, à porter sans délai à la connaissance de l’autre, tout différend ou toute difficulté qui pourrait résulter de l’exécution de cet accord.</p>
<p><strong><u>Article 7 : Durée du contrat </u></strong></p>
<p>Le présent Contrat conclu pour une durée de deux (02) ans à compter de la date de signature par les Parties, est renouvelable autant de fois par tacite reconduction à charge pour la partie qui voudrait y mettre fin, de prévenir l'autre partie dans un délai de deux (02) mois par acte extrajudiciaire ou par lettre recommandée avec avis de réception ou par tout moyen permettant d’établir la réception effective par le destinataire.</p>
<p><strong><u>Article 8 : Entrée en vigueur </u></strong></p>
<p>Le présent contrat entre en vigueur à la date de sa signature et tient lieu de loi aux parties qui doivent l’exécuter de bonne foi.</p>
<p><strong><u>Article 9 : Règlement des litiges</u></strong></p>
<p>Tout litige pouvant survenir entre les parties et relatif à l'interprétation ou à l'exécution du présent contrat sera réglé à l’amiable.</p>
<p>A défaut de règlement à l’amiable, il sera soumis à l’arbitrage sous l’égide de la Cour d’Arbitrage du Togo (CATO), et sera définitivement tranché suivant son règlement d’arbitrage tel qu’il est en vigueur à la date de signature du présent contrat. Le nombre d’arbitres est fixé à trois (03).</p>
<p style="text-align:right">Fait à Lomé, en trois (03) exemplaires </p>
<p style="text-align:right">Le …………………………………………………….</p>
<p>Pour ESMC</p>
<p style="text-align:right">Pour ………………</p>
<p>Son Gérant, </p>
<p style="text-align:right;margin-top:-38px">Son ………….., </p>
<p>M. Essohamlon SAMA </p>
<p style="text-align:right;margin-top:-38px">M. …………………………..</p>
</section>

</article>