<style>
.img_procedure_post_centrale{
   width: 100%;
}
</style>

<h2>Centrale d'achat commune</h2>


<?PHP
	   if ($_SERVER["HTTP_X_FORWARDED_HOST"] == NULL) {
        $src_file = "http://webfiles.gacsource.net/procedure_post_centrale";
?>    
           <img src="<?PHP echo $src_file;?>/00.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/01.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/02.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/03.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/04.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/05.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/06.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/07.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/08.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/09.PNG"  class="img_procedure_post_centrale" alt="">
           <img src="<?PHP echo $src_file;?>/10.PNG"  class="img_procedure_post_centrale" alt="">
       <?PHP        
      }else{
        $src_file = "http://webfiles.esmcgacsource.com/procedure_post_centrale";
        ?>
	<img src="<?PHP echo $src_file;?>/00.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/01.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/02.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/03.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/04.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/05.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/06.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/07.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/08.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/09.PNG"  class="img_procedure_post_centrale" alt="">
    <img src="<?PHP echo $src_file;?>/10.PNG"  class="img_procedure_post_centrale" alt="">
<?PHP  } ?>