
<img src="/publicites/communique_six_CNEPC-TOGO.png" style="width:100%" alt="coordination national des entités">
<hr>

<img src="/publicites/communique_cinq_CNEPC-TOGO.png" style="width:100%" alt="coordination national des entités">
<hr>
<div class="row">
<div class="col-xl-8">
<img src="/publicites/communique_quatre_CNEPC-TOGO.png" style="width:100%" alt="coordination national des entités">
</div>
<div class="col-xl-4">
<a href="/publicites/LISTE_DES_150_PREMIERS_BENEFICIAIRES_DE_BONS_DE_CONSOMMATION_MENSUELS_SUR_LA_PLATEFORME_ESMC.pdf" style="display:block;width:100%;height:50px;line-height:50px;text-align:center;text-transform:uppercase;border-radius:25px;-webkit-border-radius:25px;moz-border-radius:25px;-o-border-radius:25px;background-color:#AD2D59;color:#FFF" target="_blank">
 Telecharger la liste
</a>
</div>
<hr style="clear:both">
</div>


<img src="/publicites/communique_trois_CNEPC-TOGO.png" style="width:100%" alt="coordination national des entités">

<hr >


<img src="/publicites/communique_deux_CNEPC-TOGO.jpg" style="width:100%" alt="coordination national des entités">
<hr>

<img src="/publicites/communique_CNEPC-TOGO_nouveau.jpg" style="width:100%" alt="coordination national des entités">
