
<div class="row">
   <div class="col-lg-9">
   <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/428142924&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
    </div>
   <div class="col-lg-3">
     <a href="/publicites/legalite_esmc.pdf">Telecharger la legalite de l'ESMC</a> <br>
     <a href="/bons/framevideolegaliteesmc">Lire la video sur la legalite de l'ESMC</a> <br>
   </div>

</div>