<div class="row">
   <div class="col-lg-9">
<iframe width="560" height="315" src="https://www.youtube.com/embed/ooC8uLVJMHk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
   <div class="col-lg-3">
      <blockquote>Réponse à l'appel mondial odd (Personne Physique ou Personne Morale)</blockquote>
         <a href="/publicites/REPONSE_A_APPEL_MONDIAL_ODD_PP_ou_PM.pdf">Telecharger la Réponse à l'appel mondial odd pour la personne physique ou la personne morale</a> <br>
         <a href="/bons/framevideoappelmondialpppm">Lire la video sur la réponse à l'appel mondial ODD (Personne Physique ou Personne Morale)</a> <br>
         <a href="/bons/frameaudioappelmondialpppm">Ecouter l'audio sur la réponse à l'appel mondial ODD (Personne Physique ou Personne Morale)</a> <br>

      <blockquote>Réponse à l'appel mondial odd (Ancien Membre Personne Physique ou Personne Morale)</blockquote>

         <a href="/publicites/REPONSE_A_APPEL_MONDIAL_ODD_POUR_LES_PP_OU_PM_ANCIENS.pdf">Telecharger la réponse à l'appel mondial ODD (Ancien Membre Personne Physique ou Personne Morale)</a> <br>
         <a href="/bons/framevideoappelmondialancienpppm">Lire la réponse à l'appel mondial ODD (Personne Physique ou Personne Morale)</a> <br>
         <a href="/bons/frameaudioappelmondialancienpppm">Ecouter l'audio sur la réponse à l'appel mondial ODD (Personne Physique ou Personne Morale)</a> <br>
         
      <blockquote>Réponse à l'appel mondial odd (FOADDIP)</blockquote>

         <a href="/publicites/REPONSE_MONDIAL_A_APPEL_ODD_POUR_LES_F-BPS-PEI.pdf">Telecharger la réponse à l'appel mondial odd (FOADDIP)</a> <br>
         <a href="/bons/framevideoappelmondialfoaddip">Lire la video sur la réponse à l'appel mondial odd (FOADDIP)</a> <br>
         <a href="/bons/frameaudioappelmondialfoaddip">Ecouter l'audio sur la réponse à l'appel mondial odd (FOADDIP)</a> <br>
         
      <blockquote>Réponse à l'appel mondial odd (PBF)</blockquote>
         <a href="/publicites/REPONSE_A_APPEL_MONDIAL_ODD_POUR_LES_PBF.pdf">Telecharger la réponse à l'appel mondial odd (PBF)</a> <br>
         <a href="/bons/framevideoappelmondialpbf">Lire la video sur la réponse à l'appel mondial odd (PBF)</a> <br>
         <a href="/bons/frameaudioappelmondialpbf">Ecouter l'audio sur la réponse à l'appel mondial odd (PBF)</a> <br>
         
      <blockquote>Legalité de l'ESMC</blockquote>
        <a href="/publicites/legalite_esmc.pdf">Telecharger la legalite de l'ESMC</a> <br>
        <a href="/bons/framevideolegaliteesmc">Lire la video sur la legalite de l'ESMC</a> <br>
        <a href="/bons/frameaudiolegaliteesmc">Ecouter l'audio sur la legalite de l'ESMC</a> <br>

   </div>

</div>

