<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/articles.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addarticle_stockes">
  <?php if(isset($this->error) && $this->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->error; ?>
    </div>
  <?php }?>
  

<div class="control-group">
<label class="control-label" for="code_membre_morale">Code Membre Morale du fournisseur *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="code_membre_morale" id="code_membre_morale" placeholder="Code Membre Morale du fournisseur" required >
</div>
</div>


<div id="nivfour">
<div class="control-group">
<label class="control-label" for="reference">L'article *</label>
<div class="controls">
<select id="reference" name="reference" required>
  <option value="">Choisir l'article</option>
</select>
</div>
</div>
</div>


  
    <div class="control-group">
  <label class="control-label" for="date_debut">Date Début  </label>
  <div class="controls">
    <input type="text" name="date_debut" id="date_debut" placeholder="Date Début" class="input-medium datepicker" data-provide="datepicker" value="<?php 
                        $eumemb = new Application_Model_DbTable_EuCommande();
                        $select = $eumemb->select();
                        $select->order(array('date_commande ASC'));
                        $select->limit(1);
                        $rowseumemb = $eumemb->fetchRow($select);
                        echo substr($rowseumemb->date_commande, 0, 10); ?>" readonly />
  </div>
  </div>
  

  <div class="control-group">
  <label class="control-label" for="date_fin">Date Fin  </label>
  <div class="controls">
    <input type="text" name="date_fin" id="date_fin" placeholder="Date Fin" class="input-medium datepicker" data-provide="datepicker" value="<?php 
                        $eumemb = new Application_Model_DbTable_EuCommande();
                        $select = $eumemb->select();
                        $select->order(array('date_commande DESC'));
                        $select->limit(1);
                        $rowseumemb = $eumemb->fetchRow($select);
                        $date_fin = new Zend_Date(substr($rowseumemb->date_commande, 0, 10));
                        $date_fin->addDay(1);
                        echo $date_fin->toString('yyyy-MM-dd'); ?>" readonly />
  </div>
  </div>

<div class="control-group">
<label class="control-label" for="commander">Déja commandé</label>
<div class="controls">
<select id="commander" name="commander">
  <option value="0">Non</option>
  <option value="1">Oui</option>
</select>
</div>
</div>


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary">Trier la liste des articles commandés</button>

<?php if (isset($_POST['date_debut'])) {?>
<a target="_blank" class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/boutiqueligne/listarticlecommandeexcel/date_debut/<?php echo $_POST['date_debut']; ?>/date_fin/<?php echo $_POST['date_fin']; ?>/designation/<?php echo $_POST['designation']; ?>/code_membre_vendeur/<?php echo $sessionmembre->code_membre; ?>/commander/<?php echo $_POST['commander']; ?>">Exporter en Excel</a>
<?php }?>

</div>
 
                            
  
</form>


  <blockquote><p>Liste des articles commandés</p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Code Membre</th>
								  <th>Nom & prenom(s) / Raison sociale</th>
								  <th>Désignation</th>
								  <th>Quantité</th>
								  <th>Prix</th>
                  <th>Telephone</th>
                  <th>E-mail</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
    <?php 
$commandeM = new Application_Model_EuCommandeMapper();
$commande = new Application_Model_EuCommande();
$commandeM->find($entry->code_commande, $commande);
/**/?>
      <td><?php echo ($commande->date_commande); ?></td>
      <td><?php echo $commande->code_membre_acheteur; ?></td>
      <td><?php if(substr($commande->code_membre_acheteur, -1) == "P"){
$membreM = new Application_Model_EuMembreMapper();
$membre = new Application_Model_EuMembre();
$membreM->find($commande->code_membre_acheteur, $membre);
?><?php echo ($membre->nom_membre." ".$membre->prenom_membre); $email = $membre->email_membre; ?>
	<?php }else{
$membremoraleM = new Application_Model_EuMembreMoraleMapper();
$membremorale = new Application_Model_EuMembreMorale();
$membremoraleM->find($commande->code_membre_acheteur, $membremorale);
?><?php echo ($membremorale->raison_sociale); $email = $membremorale->email_membre;  } ?>
</td>
      <td><?php echo ($entry->designation); ?></td>
      <td><div align="right"><?php echo number_format($entry->qte, 0, ',', ' '); ?></div></td>
      <td><div align="right"><?php echo number_format(($entry->qte * $entry->prix_unitaire), 0, ',', ' '); ?></div></td>
      <td><?php $telephoneM = new Application_Model_EuTelephoneMapper();
$telephone = $telephoneM->fetchAllByCodeMembre($commande->code_membre_acheteur);
$portable_membre = "";
foreach ($telephone as $telephonevalue) {
$portable_membre .= $telephonevalue->numero_telephone." / ";
}
echo $portable_membre = substr($portable_membre, 0, -3);
 ?></td>
      <td><?php echo ($email); ?></td>
      <td><?php if($entry->commander >= 1){?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Déja Commandé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Non Commandé</a>&nbsp;
<?php }?></td>
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun article acheté 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








