<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur'); ?>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p> Formulaire d'Etablissement de la demande </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addfichebesoin">
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php } ?>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
  <?php } ?>



<legend> Expression du Besoin </legend>
  
<div class="control-group">
<label class="control-label" for="libelle_besoin"> Désignation du Besoin </label>
<div class="controls">
<input type="text" name="libelle_besoin" id="libelle_besoin" placeholder="Désignation du besoin" class="input-xxlarge" value="<?php echo $this->fiche->designation_besoin;?>" readonly />
</div>
</div>

<div class="control-group">
<label class="control-label" for="date_acquisition">Début période </label>
<div class="controls">
<input type="text" name="debut_periode" id="debut_periode" placeholder="Debut Période" class="input-xxlarge" value="<?php echo $this->fiche->debut_periode_besoin;?>"  readonly />
</div>
</div> 

<legend> Etablissement de la demande </legend>

<div class="control-group">
<label class="control-label" for="libelle_demande">Code membre Prestataire * </label>
<div class="controls">
<input type="text" name="code_membre" id="code_membre" placeholder="Code membre du Prestataire" class="input-xxlarge" required />
</div>
</div>

<div class="control-group">
<label class="control-label" for="libelle_demande"> Désignation de la demande * </label>
<div class="controls">
<input type="text" name="libelle_demande" id="libelle_demande" placeholder="Désignation de la demande" class="input-xxlarge" required />
</div>
</div>   
 
<div class="form-actions">  
<input name="ok" type="hidden" id="ok" value="ok" />
<input type="hidden" name="id_fiche_besoin" id="id_fiche_besoin" placeholder="" value="<?php echo $this->fiche->id_fiche_besoin; ?>" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Valider</button>
</div>                           
  
</form>

</div>
<div class="span3">
<?php //include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








