<?php //$sessionmembre = new Zend_Session_Namespace('membre'); ?>

<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<script type="text/javascript">

   function ouvreprestation0()  {
	 $('#div_prestation').css('display','none');
	 $('#designation_prestation').attr("required",false);
	 $('#montant_prestation').attr("required",false);    
   }
   
   function ouvreprestation1()  {
	 $('#div_prestation').css('display','block');
	 $('#designation_prestation').attr("required",true);
	 $('#montant_prestation').attr("required",true);
   }
   
   function ouvredevis() {
	   montant_devis = 0;
	   for(var i = 0; i < document.getElementById("cpteur").value; i++) {
          montant_devis += Math.floor(document.getElementById("prix_unitaire" + i).value * document.getElementById("qte_article" + i).value);		 
       }
	   if(document.getElementById('prestation_1').checked) {
		  montant_devis += Math.floor(document.getElementById("montant_prestation").value);
	   }
	   document.getElementById('montant_devis').value = montant_devis;
   }



   var compteur = 1;
   function addRow(tableID) {
	  var table = document.getElementById(tableID);
      var rowCount = table.rows.length;
      var cpte = rowCount;
      var row = table.insertRow(rowCount);
	   
	  var cell1 = row.insertCell(0);
      var element0 = document.createElement("input");
      element0.type = "text";
      element0.setAttribute("id", "designation_article" + cpte);
	  element0.setAttribute("name", "designation_article[]");
	  element0.setAttribute("class","input-block-level");
	  element0.setAttribute("placeholder","Désignation article");
	  element0.setAttribute("required","true");
      cell1.appendChild(element0);
	 
	  var cell2 = row.insertCell(1);
      var element1 = document.createElement("input");
     element1.type = "number";
     element1.setAttribute("id", "qte_article" + cpte);
	 element1.setAttribute("name", "qte_article[]");
	 element1.setAttribute("class","input-block-level");
	 element1.setAttribute("placeholder","Quantité Article");
	 element1.setAttribute("required","true");
     cell2.appendChild(element1);
	 
	 var cell3 = row.insertCell(2);
     var element2 = document.createElement("input");
     element2.type = "number";
     element2.setAttribute("id", "prix_unitaire" + cpte);
	 element2.setAttribute("name", "prix_unitaire[]");
	 element2.setAttribute("class","input-block-level");
     element2.setAttribute("placeholder","Prix unitaire");
	 element2.setAttribute("required","true");
     cell3.appendChild(element2);
	   
	 compteur = compteur + 1;
     document.getElementById("cpteur").setAttribute('value',compteur);  
   }
   
   
   function deleteRow(tableID)  {
	  try {
         var table = document.getElementById(tableID);
         var rowCount = table.rows.length - 1;
         if (rowCount >= 1) {
            table.deleteRow(rowCount);
            compteur = compteur - 1;
            document.getElementById("cpteur").setAttribute('value', compteur);
         }
      } catch (e) {
         alert(e);
      }    
   }
</script>


<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

<blockquote><p> Formulaire d'Etablissement du devis </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="adddevis">
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php } ?>
  
  <?php if(isset($sessionmembre->error) && $sessionmembre->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionmembre->error; $sessionmembre->error = ""; ?>
  </div>
  <?php } ?>


<fieldset>

<legend> Remplir le Formulaire d'Etablissement du devis </legend> 
<div class="control-group">
<label class="control-label" for="libelle_devis">Libellé du devis * </label>
<div class="controls">
<input type="text" name="libelle_devis" id="libelle_devis" placeholder="Libellé du devis" class="input-block-level" required />
</div>
</div> 
  
<legend>Détails des articles</legend>
<div class="control-group" id="display_article">
     <label class="control-label" for="article"> Détails articles du devis * </label>
	 <div class="controls">
	      <table id="tab_article">
		         <tr>
				 <input type="hidden" name="cpteur" id="cpteur" value="1"/>
				 <td>
				 <input type="text" id="designation_article0" name="designation_article[]" placeholder="Désignation Article"  class="input-block-level" required />
			     </td>
				 <td>
				 <input type="number" id="qte_article0" name="qte_article[]" placeholder="Quantité Article"  class="input-block-level" required />
			     </td>
				 <td>
				 <input type="number" id="prix_unitaire0" name="prix_unitaire[]" placeholder="Prix Unitaire"  class="input-block-level" required />
			     </td>    
				 <td>
				     <input class="btn btn-mini"  id="add"     type="button"  value="+"  onclick ="addRow('tab_article');"   /> 
					 <input class="btn btn-mini"  id="remove"  type="button"  value="-"  onclick="deleteRow('tab_article');" /> 
				 </td>
				 </tr>
		  </table>
	 </div>
</div>

<legend> Autre prestation </legend>
<div class="controls">
<label class="control-label"> Avez-vous à ajouter les frais de prestation ? </label>
<div class="controls">
	 <label for="non" class="radio">
     <input name="prestation"  type="radio" id="prestation_0" value="0" checked="checked" required onclick="ouvreprestation0()"  />
             NON
     </label>

     <label for="ok" class="radio">
     <input type="radio" name="prestation" id="prestation_1" value="1" required onclick="ouvreprestation1()" />
             OUI         
     </label>

	 <div class="control-group" id="div_prestation" style="display:none;">
     <div>
		 <div class="controls">
		 <label class="control-label">Désignation prestation * </label>
         <div class="controls">
              <input type="text" name="designation_prestation" id="designation_prestation" placeholder="Désignation Prestation"  class="input-block-level" />
         </div>
		 </div>						 
	 </div>

     <div>
		 <div class="controls">
		 <label class="control-label">Montant prestation * </label>
         <div class="controls">
              <input type="number" name="montant_prestation" id="montant_prestation" placeholder="Montant Prestation"  class="input-block-level" />
         </div>
		 </div>						 
	 </div>	 
     </div>	 
</div>
</div>

<legend> TOTAL </legend>
<div class="control-group">
     <label class="control-label"> Montant Devis * </label>
	 <div class="controls">
	 <input type="text" onclick="ouvredevis()"  name="montant_devis" id="montant_devis" placeholder="Montant Devis"  class="input-block-level" value="0" readonly />
     </div>
</div>
</fieldset>  
 
<div class="form-actions">  
<input name="ok" type="hidden" id="ok" value="ok" />
<input type="hidden" name="id_fiche_besoin" id="id_fiche_besoin" value="<?php echo $this->fiche->id_fiche_besoin; ?>" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enrégistrer</button>
</div>                           
  
</form>

</div>
<div class="span3">
<?php //include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








