<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p> Etablissement d'un Procès verbal de restitution </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addlettre">
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php } ?>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
  <?php } ?>

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">  
<thead>
      <tr>
	      <th colspan="5">Immobilisation intitulé : <?php echo ($this->entry->designation_immobilisation); ?> du  <?php echo ($this->entry->date_entree); ?></th>
	  
	  </tr>
	  
	  <tr>
		  <th>Codification</th>
		  <th>Famille</th>
		  <th>Nature</th>
		  <th>Valeur acquisition</th>
		  <th>Fournisseur</th>
	  </tr>
</thead>

<?php 

$morale = new Application_Model_EuMembreMorale();
$m_morale  = new Application_Model_EuMembreMoraleMapper();
$m_morale->find($this->entry->code_membre_fournisseur,$morale);

?>

<tbody>
      <tr>
	     <td><?php echo ($this->entry->code_identification); ?></td>
	     <td><?php echo ($this->entry->famille_immobilisation); ?></td>
	     <td><?php echo ($this->entry->nature_immobilisation); ?></td>
	     <td><?php echo ($this->entry->valeur_acquisition); ?></td>
		 <td><?php echo ($morale->raison_sociale); ?></td>
	  </tr>
</tbody>  
</table>

<br/>

<legend> Cadre réservé à l'Administration ESMC </legend>

<div class="control-group">
<label class="control-label" for="designation_pv">Désignation du Procès verbal * </label>
<div class="controls">
<input type="text" name="designation_pv" id="designation_pv" placeholder="Désignation du Procès verbal" class="input-xxlarge" required />
</div>
</div>

<div class="control-group">
<label class="control-label" for="contenu"> Message </label>
<div class="controls">
<textarea  name="contenu" id="contenu" placeholder="Contenu du message" class="ckeditor" required></textarea>
</div>
</div>


 
<div class="form-actions">  
<input name="ok" type="hidden" id="ok" value="ok" />
<input type="hidden" name="id_lettre" id="id_lettre" placeholder="" value="<?php echo $this->entry->id_lettre; ?>" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enrégistrer</button>
</div>                           
  
</form>

</div>
</div>
</div>








