<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>
    <script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/detailprojets.js"></script>

	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php //include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Ajouter une offre de projet</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addprojet">
  <?php if(isset($sessionmcnp->error) && $sessionmcnp->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->error; $sessionmcnp->error = "";?>
    </div>
  <?php }?>
  
    
<div class="control-group">
<label class="control-label" for="projet_code_membre">Code Membre *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="projet_code_membre" id="projet_code_membre" placeholder="Code Membre" required>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="projet_libelle">Désignation du projet *</label>
<div class="controls">
<input class="input-xlarge" type="text" name="projet_libelle" id="projet_libelle" placeholder="Désignation du projet" required>
</div>
</div>



<div class="control-group">
<label class="control-label" for="projet_stockage"> Entreposage * </label>
<div class="controls">
<select id="projet_stockage" name="projet_stockage" required class="input-xxlarge">
<option value="">Choisir un type</option>
<option value="Entrepots">Entrepots</option>
<option value="Marches">Marches</option>
<option value="Magasins">Magasins</option>
<option value="Boutiques">Boutiques</option>
</select>     
</div>     
</div>


<div class="control-group">
<label class="control-label" for="projet_description">Description du projet * </label>
<div class="controls">
<textarea name="projet_description" id="projet_description" placeholder="Description du projet" class="ckeditor"></textarea>
</div>
</div>

<div class="control-group">
<label class="control-label" for="projet_montant">Montant du projet *</label>
<div class="controls">
<input class="input-xlarge" type="number" name="projet_montant" id="projet_montant" placeholder="Montant du projet" required>
</div>
</div>
    

  <legend> Localités </legend>
  

                        <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Zone M.</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="code_zone" name="code_zone">
                                            <option value="">Choisir une zone monétaire</option>
                                            <?php foreach ($this->zones as $value) { ?>
                                            <option
                                                    value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Pays *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_pays" name="id_pays" required="required" onchange="ouvre_paystelephones2(this.value);">
                                            <option value="">Choisir un pays</option>
                                            <?php foreach ($this->pays as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Régions</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_region" name="id_region">
                                            <option value="">Choisir une région</option>
                                            <?php foreach ($this->regions as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Préfectures</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_prefecture" name="id_prefecture">
                                            <option value="">Choisir une préfecture</option>
                                            <?php foreach ($this->prefectures as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Cantons *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_canton" name="id_canton" required="required">
                                            <option value="">Choisir un canton</option>
                                            <?php foreach ($this->cantons as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>


<legend>Fichiers du projet </legend>
<div class="row-fluid">
<div class="span5">Libellé du fichier</div>
<div class="span5">Fichier du projet</div>
<div class="span2">Actions</div>
</div>

<?php $b = 0;?>
<div id="nivdetail<?php echo $b;?>">
<div class="row-fluid">
<div class="span5"><input class="input-xlarge" type="text" name="detail_projet_libelle[]" id="detail_projet_libelle<?php echo $b;?>" placeholder="Libellé du fichier" >
</div>
<div class="span5"><input name="detail_projet_fichier<?php echo $b;?>" type="file" id="detail_projet_fichier<?php echo $b;?>" class="input-xxlarge"  />  
</div>
<div class="span2"><a class="btn btn-mini" onclick="document.getElementById('nivdetail<?php echo $b;?>').style.display='none';"><i class="icon-minus"></i></a>
<a class="btn btn-mini" onclick="ouvre_detailprojets('<?php echo $b + 1;?>','nivdetail<?php echo $b + 1;?>');"><i class="icon-plus"></i></a><br />
&nbsp;
</div>
</div>
</div>
<div id="nivdetail<?php echo $b + 1;?>"></div>


<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Ajouter l'offre de projet</button>
</div>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








