<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script src="<?php echo $this->baseUrl();?>/pv.js"></script>

<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
       "sPaginationType": "full_numbers",
	   "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">


<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>


<blockquote><p> Liste des lettres de restitutions d'immobilisation initiées </p></blockquote>
  
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
<?php } ?>
  
<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
<?php } ?>

<?php if(count($this->entries) > 0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
<thead>
	  <tr>
		  <th>Date Emission lettre</th>
		  <th>Code immobilisation</th>
		  <th>Désignation immobilisation</th>
		  <th>Montant acquisition</th>
		  <th>Fournisseur</th>
		  <th>Actions</th>
	  </tr>
</thead>
  
<tbody>
<?php foreach($this->entries as $entry): 

$fiche = new Application_Model_EuFicheImmobilisation();
$m_fiche = new Application_Model_EuFicheImmobilisationMapper();
$m_fiche->find($entry->id_fiche_immobilisation,$fiche);

$morale = new Application_Model_EuMembreMorale();
$m_morale  = new Application_Model_EuMembreMoraleMapper();
$m_morale->find($entry->code_membre_fournisseur,$morale);


?>
    <tr>
	  <td><?php echo ($entry->date_creation); ?></td>
	  <td><?php echo ($fiche->code_identification); ?></td>
	  <td><?php echo ($fiche->designation_immobilisation); ?></td>
	  <td><?php echo ($fiche->valeur_acquisition); ?></td>
	  <td><?php echo ($morale->raison_sociale); ?></td>
	  
	  <td>
	      <div align="center">
			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/immobilisation/detailimmo/id/<?php echo $entry->id_lettre; ?>"><i class="icon-edit icon-white"></i> Details </a>&nbsp;  
		    <?php if($entry->valider == 2) { ?>
			<a class="btn btn-mini btn-danger" href="<?php echo $this->baseUrl(); ?>/immobilisation/addpvrestitution/id/<?php echo $entry->id_lettre; ?>"><i class="icon-plus icon-white"></i>Etablir PV</a>&nbsp;
		    <?php } else { ?>
			      <a class="btn btn-mini btn-success" onclick=""><i class="icon-ok icon-white"></i> Restitué </a>&nbsp;
			<?php } ?>
		  </div>
	  </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucune lettre de restitution initée
</div>
<?php } ?>

</div>
</div>
</div>


