<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script src="<?php echo $this->baseUrl();?>/pv.js"></script>

<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
       "sPaginationType": "full_numbers",
	   "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">


<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>


  <blockquote><p> Liste des Procés verbaux de restitution d'immobilisation </p></blockquote>
  
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php } ?>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
  <?php } ?>

<?php if(count($this->entries) > 0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
<thead>
	  <tr>
		  <th>Date</th>
		  <th>Désignation</th>
		  <th>Actions</th>
	  </tr>
</thead>
  
<tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
	   <td> <?php echo ($entry->date_pvrestitution);?></td>
	   <td> <?php echo ($entry->designation_pvrestitution);?></td>
	   <td>
	       <div align="center">
	           <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/immobilisation/detailimmorestituer/id/<?php echo $entry->id_pvrestitution; ?>"><i class="icon-edit icon-white"></i> Details </a>&nbsp;  
		       <?php if(($entry->valider == 2) && ($entry->rejeter == 0))  { ?>    
			   <a class="btn btn-mini btn-danger" href="<?php echo $this->baseUrl(); ?>/immobilisation/addaccordfiliere/id/<?php echo $entry->id_pvrestitution; ?>"><i class="icon-plus icon-white"></i>Approbation</a>&nbsp;
		       <?php } else if($entry->valider == 3) { ?>
			   <a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i> Approuvé </a>&nbsp;
			   <?php } else if($entry->rejeter == 1) { ?>
			   <a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i> Rejeté </a>&nbsp;   
               <?php } else if($entry->valider == 4) { ?>
			   <a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i> Restitué </a>&nbsp;     			   
			   <?php } else { ?>
			   <a class="btn btn-mini btn-info"><i class="icon-off icon-white"></i> En Cours de traitement </a>&nbsp;
			   <?php } ?>
		   </div>
	   </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucun procés verbal enrégistré 
</div>
<?php } ?>

</div>
</div>
</div>


