<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script src="<?php echo $this->baseUrl();?>/pv.js"></script>

<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
    $('#example').dataTable({
       "sPaginationType": "full_numbers",
	   "aaSorting": []
    });
    });
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">


<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>


<blockquote><p> Details du Procès verbal mis dans le régistre d'immobilisation </p></blockquote>
  
  <?php if(isset($this->error) && $this->error!="") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $this->error; ?>
  </div>
  <?php } ?>
  
<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
  </div>
<?php } ?>


<?php if(count($this->entries) > 0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:11px;">
<thead> 
      <tr>
	       <th colspan="5">Procès verbal intitulé : <?php echo ($this->pv->designation_pvacquisition); ?> du  <?php echo ($this->pv->date_pvacquisition); ?></th>
	  </tr>
	  <tr>
		  <th>Date</th>
		  <th>Codification</th>
		  <th>Désignation</th>
		  <th>Valeur acquisition</th>
		  <th>Actions</th>
	  </tr>
</thead> 
<tbody>
<?php foreach($this->entries as $entry): ?>
    <tr>
	  <td><?php echo ($entry->date_codification); ?></td>
	  <td><?php echo ($entry->code_identification); ?></td>
	  <td><?php echo ($entry->designation_immobilisation); ?></td>
	  <td><?php echo ($entry->valeur_acquisition); ?></td>
	  <td>
	      <div align="center">
		  <?php if($entry->traiter == 1) { ?>
			<a class="btn btn-mini btn-success" onclick=""><i class="icon-ok icon-white"></i> Traité </a>&nbsp;
			<a class="btn btn-mini btn-danger" href="<?php echo $this->baseUrl(); ?>/immobilisation/addlettre/id/<?php echo $entry->id_fiche_immobilisation; ?>"><i class="icon-plus icon-white"></i>Initier une lettre</a>&nbsp;
		  <?php } ?>
		  </div>
	  </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucune fiche immobilisation enrégistrée 
</div>
<?php } ?>

</div>
</div>
</div>


