<?php $sessionmembre = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
		<style media="screen">
		.table tbody tr.level-heigh > td{
			background-color:#06065a;color: #FFF;
		}
		</style>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<?php
$days = array(
 "1"=>"1","2"=>"2","3"=>"3","4"=>"4","5"=>"5","6"=>"6","7"=>"7","8"=>"8","9"=>"9",
 "10"=>"10","11"=>"11","12"=>"12","13"=>"13","14"=>"14","15"=>"15","16"=>"16","17"=>"17","18"=>"18","19"=>"19","20"=>"20","21"=>"21","22"=>"22","23"=>"23","24"=>"24","25"=>"25","26"=>"26","27"=>"27","28"=>"28","29"=>"29","30"=>"30","31"=>"31");
$years = array("2016"=>"2016","2017"=>"2017","2018"=>"2018","2019"=>"2019","2020"=>"2020","2021"=>"2021","2022"=>"2022","2023"=>"2023","2024"=>"2024","2025"=>"2025","2026"=>"2026","2027"=>"2027","2028"=>"2028","2029"=>"2029","2030"=>"2030","2031"=>"2031","2032"=>"2032","2033"=>"2033","2034"=>"2034","2035"=>"2035","2036"=>"2036","2037"=>"2037","2038"=>"2038","2039"=>"2039","2040"=>"2040");

$months = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
  if(count($this->entries) > 0){?>
		
	<blockquote><p>Liste des Tickets de Support archivés </p></blockquote>
<table class="table table-striped table-hover table-condensed" id="example">
   <thead>
 	<tr>
 		<th>Reference</th>
 		<th>Telecharger le Ticket</th>
		<th>Telecharger cette piece jointe</th>
 		<th>Date de confirmation du ticket</th>
 	</tr>
   </thead>
   <tbody>
   	 	<?php foreach ($this->entries as $key => $value): ?>

        <tr class="level-heigh">
        	<td><?php echo $value->numero_demandeur; ?></td>
          <td>
            <a class="btn btn-mini btn-primary" href="pdfticketarchive/id/<?php echo $value->id_ticket; ?>"><i class="icon-cog icon-white"></i>Telecharger ce ticket de Support </a>
          </td>
					<td>
						<?php if ($value->file_name !== null): ?>
							<a class="btn btn-mini btn-primary" href="/pdf_upload/<?php echo $value->file_name; ?>"><i class="icon-cog icon-white"></i> Telecharger cette piece jointe</a>
            <?php elseif($value->renseignement_id > 0): ?>
							<a class="btn btn-mini btn-primary" href="fileedit/id/<?php echo $value->renseignement_id; ?>"><i class="icon-cog icon-white"></i> Telecharger cette piece jointe</a>
            <?php else: ?>
							<span>Aucune pièce jointe pour ce ticket</span>
						<?php endif; ?>
					</td>

					<td>
						<?php
						$true_month = "";
						$ex_date = explode('-',$value->created);

						    foreach ($months as $ky => $vad) {
							    if($ex_date[1] == $ky){
								    $true_month = $vad;
							    }
						    }
						   $next_ex_date = explode(' ', $ex_date[2]);
						   $true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0]." à ".$next_ex_date[1];
						 ?>

						<?php echo $true_date ;?>
					</td>

        </tr>
 	<?php endforeach ?>
   </tbody>

 </table>
<?php } else {?>
<div class="alert alert-info">
  Aucun Ticket de Support traité n'a été encore enregistré
</div>
<?php }?>
</div>

</div>
</div>
