<?php $sessionmembre = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
<style media="screen">
.table tbody tr.marron > td{
	    background-color: #dc942d;
}
.table tbody tr.marron > td{
	    background-color: #dc942d;
}

.table tbody tr.marron:hover > td{
	    background-color: #dc942d;
}

/**
					<td>
						<?php if ($valentry->file_name === "true"):
					 ?>
					  <?php
               $new_code_file = str_replace('/','_',$valentry->numero_demandeur);
               $true_new_code_file = str_replace('TS','FILES',$new_code_file);
               $src_file = "../../webfiles/pdf_upload/".$true_new_code_file;
							  if ($folder = opendir($src_file)) {
                   while (false !== ($files = readdir($folder))) {
                      if($files != "." && $files != ".." && $files != "index.php"){
                       $ex_files = explode('.',$files);
											  if (in_array($ex_files[1], array('jpg','jpeg','png'))){ ?>
          <a href="http://webfiles.gacsource.net/pdf_upload/<?php echo $true_new_code_file ?>/<?php echo $files ?>" class="btn btn-mini btn-primary" style="display:block;"><?php echo $files ?></a>
      <?php
       }
       }
			 }
    }?>
					  <?php elseif($valentry->renseignement_id > 0): ?>
							<a class="btn btn-mini btn-primary" href="<?php echo $this->baseUrl(); ?>/ticketsupport/fileedit/id/<?php echo $valentry->renseignement_id; ?>"><i class="icon-cog icon-white"></i> Telecharger cette piece jointe</a>
            <?php else: ?>
							<span>Aucune pièce jointe pour ce ticket</span>
						<?php endif; ?>
					</td>
*/

</style>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<?php if(count($this->entries) > 0){?>
	<blockquote><p>Liste des Tickets de Support traités par les differentes sections</p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
   <thead>
 	<tr>
 		<th>Reference</th>
		<th>Nom & Prénoms</th>
		<th>Date de traitement</th>
    <th>Actions</th>
 	</tr>
   </thead>
   <tbody>
      <?php foreach ($this->entries as $kentry => $valentry): ?>
    
        <tr class="marron">
        	<td><?php echo $valentry->numero_demandeur; ?></td>

					<td>
						<?php if ($valentry->membre_section_comite_ticket != ""): ?>
							<span><?php echo $valentry->membre_section_comite_ticket; ?></span>
						<?php endif; ?>
					</td>
					<?php
							$month = array('01'=>'Janvier','02'=>'Février','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
							$true_month = "";
							$ex_date = explode('-',$valentry->date_observation);

							foreach ($month as $ky => $vad) {
								if($ex_date[1] == $ky){
									$true_month = $vad;
								}
							}
							$next_ex_date = explode(' ', $ex_date[2]);

							$true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0]." à ".$next_ex_date[1];
					 ?>
					<td>
							<span><?php echo $true_date; ?></span>
					</td>

          <td>
            <a href="<?php echo $this->baseUrl(); ?>/ticketsupport/edittickettraite/id/<?php echo $valentry->id_ticket ?>" class="btn btn-mini btn-primary " ><i class="icon-cog icon-white"></i> Valider</a>
          </td>
        </tr>
   <?php endforeach; ?>
   </tbody>

 </table>
<?php } else {?>
<div class="alert alert-info">
  Aucun Ticket de Support n'a été encore enregistré
</div>
<?php }?>
</div>

</div>
</div>
