<?php $sessionmembre = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
		<style media="screen">
			.table tbody tr.primary > td{
				background-color: #96d1e2;
			}
		</style>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<?php if(count($this->entries) > 0){?>
	<blockquote><p>Liste des Tickets de Support disponible pour signature </p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
   <thead>
 	<tr>
 		<th>Reference</th>
		<th>Telecharger cette piece jointe</th>
		<th>Date d'émission du ticket</th>
		<th>Date de dernière validation</th>
    <th>Visa 1</th>
 	</tr>
   </thead>
   <tbody>
   	 	<?php foreach ($this->entries as $key => $value): ?>
        <tr class="primary">
        	<td ><?php echo $value->numero_demandeur; ?></td>
					<td>
						<?php if ($value->file_name !== null): ?>
							<a class="btn btn-mini btn-primary" href="/pdf_upload/<?php echo $value->file_name; ?>"><i class="icon-cog icon-white"></i> Telecharger cette piece jointe</a>
            <?php elseif($value->renseignement_id > 0): ?>
							<a class="btn btn-mini btn-primary" href="fileedit/id/<?php echo $value->renseignement_id; ?>"><i class="icon-cog icon-white"></i> Telecharger cette piece jointe</a>
            <?php else: ?>
							<span>Aucune pièce jointe pour ce ticket</span>
						<?php endif; ?>
					</td>
					<?php
					    $month = array('01'=>'Janvier','02'=>'Février','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
					    $true_month = "";
							$true_val_month = "";

					    $ex_date = explode('-',$value->created);
							$ex_val_date = explode('-',$value->date_validation);

					    foreach ($month as $ky => $vad) {
						    if($ex_date[1] == $ky){
							    $true_month = $vad;
						    }
								if($ex_val_date[1] == $ky){
									$true_val_month = $vad;
								}
					    }
					    $next_ex_date = explode(' ', $ex_date[2]);
							$next_ex_val_date = explode(' ', $ex_val_date[2]);

					    $true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0]." à ".$next_ex_date[1];
							$true_val_date = $next_ex_val_date[0]." ".$true_val_month." ".$ex_val_date[0]." à ".$next_ex_val_date[1];

					 ?>
					<td>
             <?php echo $true_date ?>
					</td>
					<td>
						 <?php echo $true_val_date ?>
					</td>
          <td>
               <a class="btn btn-mini btn-primary" href="<?php echo $this->baseUrl(); ?>/ticketsupport/editticketgerantfirstvisa/id/<?php echo $value->id_ticket ?>"><i class="icon-cog icon-white"></i>Apposer le visa</a>
          </td>
        </tr>

 	<?php endforeach ?>
   </tbody>

 </table>
<?php } else {?>
<div class="alert alert-info">
  Aucun Ticket de Support n'a été encore enregistré
</div>
<?php }?>
</div>

</div>
</div>
