<?php
$new_code_file = str_replace('/','_',$this->entries[0]['numero_demandeur']);
$true_new_code_file = str_replace('TS','FILES',$new_code_file);

$src_file = "../../webfiles/pdf_upload/".$true_new_code_file;

if ($folder = opendir($src_file)) {
  while (false !== ($files = readdir($folder))) {
    if($files != "." && $files != ".." && $files != "index.php"){?>
      <?php
   $ex_files = explode('.',$files);
       ?>
      <?php if (in_array($ex_files[1], array('jpg','jpeg','png'))): ?>
     <div style="position:relative;">
      <div style="position:relative;width:800px;height:auto;margin:0px auto;border:1px solid #000;overflow:scroll" >
         <img src="http://webfiles.gacsource.net/pdf_upload/<?php echo $true_new_code_file ?>/<?php echo $files ?>" style="width:800px" id="jointe-img-container" data-scale="0" alt="" />
       </div>
       <div class="btn-zoom-image" style="position: absolute;top:0;right:162px">
         <button type="button" name="button" id="up-zoom" style="display: block;border-top-left-radius: 32px;border-top-right-radius: 32px;padding: 19px;position: relative;right: -33px;border: none;box-shadow: 3px 3px 10px;outline:none;-webkit-appearance:none">^</button>
         <button type="button" name="button" id="down-zoom" style="position: relative;border-bottom-left-radius: 32px;border-bottom-right-radius: 32px;padding: 19px;top: 1px;box-shadow: 1px 0px 5px #000;right: -33px;border: none;-webkit-appearance:none">v</button>
       </div>
     </div>

    <?php endif; ?>

<?php
    }
  }
}
?>
