<?php $sessionmembre = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>
<style media="screen">
.table tbody tr.dangerous > td{
	background-color: #e296a1
}
.table tbody tr.dangerous > td:hover{
	background-color: #e296a1
}
.table tbody tr.dangerous:hover > td{
	background-color: #e296a1
}
</style>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<?php if(count($this->entries) > 0){?>
	<blockquote><p>Liste des Tickets de Support en cours de traitement chez les intervenants</p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
   <thead>
 	<tr>
 		<th>Nom de l'intervenant</th>
		<th>Nombre de ticket</th>
 	</tr>
   </thead>
   <tbody>
   	 	<?php foreach ($this->entries as $key => $value): ?>
        <tr class="dangerous">
        	<td ><?php echo $value->membre_section_comite_ticket; ?></td>
          <td>
            <?php echo $value->number_ticket; ?>
				  </td>
        </tr>
 	<?php endforeach ?>
   </tbody>

 </table>
<?php } else {?>
<div class="alert alert-info">
  Aucun Ticket de Support n'est encore disponible
</div>
<?php }?>

</div>

</div>
</div>
