<?php $sessionmembreasso = new Zend_Session_Namespace('mcnp');?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>
            
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques2.js"></script>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/fondateurs.js"></script><?php */?>
<?php /*?><script language="javascript1.3" src="<?php echo $this->baseUrl();?>/capasenrolement.js"></script><?php */?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banquespays.js"></script>


  <div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>


<blockquote><p>Souscription au Bon d'Achat neutre (BAn) </p></blockquote>
  <?php if(isset($sessionmembreasso->error) && $sessionmembreasso->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembreasso->error; $sessionmembreasso->error = ""; ?>
    </div>
  <?php } ?>
  
<blockquote>
    <?php /*if(isset($sessionmembreasso->code_BAn) && $sessionmembreasso->code_BAn != "") { ?>
  <?php if($sessionmembreasso->membre_code != "" && $sessionmembreasso->membre_code != NULL){ ?>
    
    <?php }else{ ?>
    <a href="/souscriptionbon/bonachatneutrepdf/code/<?php echo $sessionmembreasso->code_BAn; ?>" target="_blank"><span style="color:#800080;">Télécharger votre Bon d'Achat neutre (<strong>BAn</strong>)</span></a> <br /><br />                            
    <?php } ?>
  
  <?php }*/?>

    <?php if(isset($sessionmembreasso->code_BAn) && $sessionmembreasso->code_BAn != "") { ?>
    <?php if($sessionmembreasso->membre_code != "" && $sessionmembreasso->membre_code != NULL) { ?>
    
    <?php } else { ?>
    <a href="/bons/recudepayementdebanintegrateur/id/<?php echo $sessionmembreasso->bon_neutre_detail_id; ?>" target="_blank"><span style="color:#800080;">Télécharger le reçu de votre Bon d'Achat neutre (<strong>BAn</strong>)</span></a> <br /><br />                            
    <?php } ?>
  
  <?php } ?>

  <?php if(isset($sessionmembreasso->code_BAn) && $sessionmembreasso->code_BAn != "") { ?>
  <?php if(isset($this->paramban) && $this->paramban > 0){?>
  <?php if($this->paramban == 1){?>
  <a href="/integrateur/enrolementsms2int" target="_blank"><span style="color:#800080;">Activation Personne Physique PP</span></a> <br />
  <a href="/integrateur/enrolementpmsms2int" target="_blank"><span style="color:#800080;">Activation Personne Morale PM</span></a>
  <?php }else if($this->paramban == 2){?>
  <?php $typeintegrateurM = new Application_Model_EuTypeIntegrateurMapper();
        $typeintegrateur = $typeintegrateurM->fetchAllByTypeParamBan(2);?>
    <?php foreach ($typeintegrateur as $entry): ?>
  <a href="/index/addintegrateur/param/<?php echo $entry->id_type_integrateur; ?>" target="_blank"><span style="color:#800080;"><?php echo $entry->libelle_type_integrateur; ?></span></a> <br />
    <?php endforeach; ?>
  <?php }else if($this->paramban == 3){?>
  <?php $typeintegrateurM = new Application_Model_EuTypeIntegrateurMapper();
        $typeintegrateur = $typeintegrateurM->fetchAllByTypeParamBan(3);?>
    <?php foreach ($typeintegrateur as $entry): ?>
  <a href="/index/addintegrateur/param/<?php echo $entry->id_type_integrateur; ?>" target="_blank"><span style="color:#800080;"><?php echo $entry->libelle_type_integrateur; ?></span></a> <br />
    <?php endforeach; ?>
  <?php }else if($this->paramban == 4){?>
  <?php $typeintegrateurM = new Application_Model_EuTypeIntegrateurMapper();
        $typeintegrateur = $typeintegrateurM->fetchAllByTypeParamBan(4);?>
    <?php foreach ($typeintegrateur as $entry): ?>
  <a href="/index/addintegrateur/param/<?php echo $entry->id_type_integrateur; ?>" target="_blank"><span style="color:#800080;"><?php echo $entry->libelle_type_integrateur; ?></span></a> <br />
    <?php endforeach; ?>
  <?php }else if($this->paramban == 5){?>
  <?php $typeoffreurprojetM = new Application_Model_EuTypeOffreurProjetMapper();
        $typeoffreurprojet = $typeoffreurprojetM->fetchAllByTypeParamBan(5);?>
    <?php foreach ($typeoffreurprojet as $entry): ?>
  <a href="/index/addoffreurprojet/param/<?php echo $entry->id_type_offreur_projet; ?>" target="_blank"><span style="color:#800080;"><?php echo $entry->libelle_type_offreur_projet; ?></span></a> <br />
    <?php endforeach; ?>
  <?php }else if($this->paramban == 6){?>
  <?php $typeoffreurprojetM = new Application_Model_EuTypeOffreurProjetMapper();
        $typeoffreurprojet = $typeoffreurprojetM->fetchAllByTypeParamBan(6);?>
    <?php foreach ($typeoffreurprojet as $entry): ?>
  <a href="/index/addoffreurprojet/param/<?php echo $entry->id_type_offreur_projet; ?>" target="_blank"><span style="color:#800080;"><?php echo $entry->libelle_type_offreur_projet; ?></span></a> <br />
    <?php endforeach; ?>
  <?php }else if($this->paramban == 7){?>
  <?php $typeoffreurprojetM = new Application_Model_EuTypeOffreurProjetMapper();
        $typeoffreurprojet = $typeoffreurprojetM->fetchAllByTypeParamBan(7);?>
    <?php foreach ($typeoffreurprojet as $entry): ?>
  <a href="/index/addoffreurprojet/param/<?php echo $entry->id_type_offreur_projet; ?>" target="_blank"><span style="color:#800080;"><?php echo $entry->libelle_type_offreur_projet; ?></span></a> <br />
    <?php endforeach; ?>
  <?php }?>
  
  
  <?php $sessionmembreasso->code_BAn = "";?>
  <?php } ?>
  <?php } ?>
</blockquote>

              <blockquote>Informations concernant le versement à la banque</blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription1" name="addsouscription1">
<fieldset>
<legend>Remplir le formulaire </legend>
  
  
 
<div class="control-group">
  <label class="control-label" for="bon_neutre_autonome">Etes vous déjà membre de l'ESMC ? *</label>
  <div class="controls">
  <label for="bon_neutre_autonome_0" class="radio">
  <input name="bon_neutre_autonome" type="radio" id="bon_neutre_autonome_0" value="0" required onclick="document.getElementById('code_membre').removeAttribute('required'); document.getElementById('bon_neutre_email').setAttribute('required', true);" />
  Non
  </label>

  <label for="bon_neutre_autonome_1" class="radio">
  <input type="radio" name="bon_neutre_autonome" id="bon_neutre_autonome_1" value="1" required onclick="document.getElementById('code_membre').setAttribute('required', true); document.getElementById('bon_neutre_email').removeAttribute('required');" />
  Oui
  </label>
  
  </div>
</div>
 
<div class="control-group">
<label class="control-label" for="code_membre">Code Membre du souscripteur  </label>
<div class="controls">
  <input type="text" name="bon_neutre_code_membre" id="code_membre" placeholder="Code Membre du souscripteur" class="input-xxlarge" />
<span class="help-block"><p class="text-error" style="color:red">Veuillez saisir votre <strong>Code Membre</strong> si vous disposez dèjà d'un Compte Marchand ESMC </p></span>
</div>
</div>
        
         <div class="control-group">
         <label class="control-label" > Désignation souscripteur * </label>
         <div class="controls">
         <input type="text" name="nom_membre" id="nom_membre" placeholder="Désignation souscripteur"  class="input-block-level"  />
         </div>
         </div>

<div class="control-group">
<label class="control-label" for="bon_neutre_code_ban">Code BAn précèdent </label>
<div class="controls">
  <input type="text" name="bon_neutre_code_ban" id="bon_neutre_code_ban" placeholder="Code BAn précèdent" class="input-xxlarge" />
<span class="help-block"><p class="text-error" style="color:red">Veuillez saisir votre <strong>Code BAn précèdent</strong> si vous voulez le cumuler. </p></span>
</div>
</div>


<div class="control-group">
  <label class="control-label" for="bon_neutre_personne">Type du souscripteur *</label>
  <div class="controls">

  <label class="radio">
  <input name="bon_neutre_personne" type="radio" id="bon_neutre_personne_pp" value="PP" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='none';
  document.getElementById('bon_neutre_raison').removeAttribute('required');
  ">
  Personne Physique</label>
  
  <label class="radio">
  <input type="radio" name="bon_neutre_personne" id="bon_neutre_personne_pm" value="PM" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('bon_neutre_nom').setAttribute('required', true);
  document.getElementById('bon_neutre_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='block';
  document.getElementById('bon_neutre_raison').setAttribute('required', true);
  " >
  Personne Morale</label>
  
</div>
</div>

<div id="pp" style="display:none;">
<div class="control-group">
<label class="control-label" for="bon_neutre_nom">Nom du souscripteur  * </label>
<div class="controls">
<input type="text" name="bon_neutre_nom" id="bon_neutre_nom" placeholder="Nom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required"  />
<span class="help-block"><p class="text-error" style="color:red">Veuillez saisir votre <strong>Nom</strong> réel. </p></span>
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="bon_neutre_prenom">Prénoms du souscripteur * </label>
<div class="controls">
<input type="text" name="bon_neutre_prenom" id="bon_neutre_prenom" placeholder="Prénom du souscripteur sur le reçu de banque ou de la transaction" class="input-xxlarge" required="required"  />
<span class="help-block"><p class="text-error" style="color:red">Veuillez saisir vos <strong>Prénoms</strong> réels. </p></span>
</div>
</div>
</div>

<div id="pm" style="display:none;">
<div class="control-group">
<label class="control-label" for="bon_neutre_raison">Raison sociale du souscripteur * </label>
<div class="controls">
  <input type="text" name="bon_neutre_raison" id="bon_neutre_raison" placeholder="Raison sociale du souscripteur" class="input-xxlarge" required="required" />
<span class="help-block"><p class="text-error" style="color:red">Veuillez saisir la <strong>Raison Sociale</strong> réelle de votre personne morale s'il y en a. </p></span>
</div>
</div>
</div>


<div class="control-group">
<label class="control-label" for="bon_neutre_mobile">Cellulaire du souscripteur  *</label>
<div class="controls">
<input type="number" name="bon_neutre_mobile" id="bon_neutre_mobile" placeholder="Cellulaire du souscripteur " class="input-xxlarge"  required="required" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="bon_neutre_email">E-mail du souscripteur * </label>
<div class="controls">
<div class="input-prepend">
      <span class="add-on"><i class="icon-envelope"></i></span>
    <input type="email" name="bon_neutre_email" id="bon_neutre_email" placeholder="E-mail du souscripteur" class="input-xxlarge"  required="required" />
    </div>
</div>
</div>
  
  
  

  <legend> Localités </legend>

                        <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Zone M.</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="code_zone" name="code_zone">
                                            <option value="">Choisir une zone monétaire</option>
                                            <?php foreach ($this->zones as $value) { ?>
                                            <option
                                                    value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Pays</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_pays" name="id_pays" onchange="ouvre_banquespays(this.value, 'nivo_banquespays');">
                                            <option value="">Choisir un pays</option>
                                            <?php foreach ($this->pays as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Régions</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_region" name="id_region">
                                            <option value="">Choisir une région</option>
                                            <?php foreach ($this->regions as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Préfectures</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_prefecture" name="id_prefecture">
                                            <option value="">Choisir une préfecture</option>
                                            <?php foreach ($this->prefectures as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="span4">
                                <div class="control-group">
                                    <label class="control-label span4">Cantons *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_canton" name="id_canton" required="required">
                                            <option value="">Choisir un canton</option>
                                            <?php foreach ($this->cantons as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>                         
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>


<?php /*?>
<div class="control-group">
<label class="control-label" for="id_region">R&eacute;gion du souscripteur  *</label>
<div class="controls">
<select  name ="id_region" id="id_region"  required="required" onchange="ouvre_decoupage(this.value);" class="input-xxlarge">
     <?php  $region_mapper = new Application_Model_EuRegionMapper();
        $selectregions = $region_mapper->fetchAll();?>
            <option value="">Choisir la région </option>
            <?php foreach ($selectregions as $selectregion): ?>
            <option value="<?php echo $selectregion->id_region; ?>"><?php echo $selectregion->nom_region; ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

<div id="nivpref">
<div class="control-group">
<label class="control-label" for="id_prefecture">Pr&eacute;fecture du souscripteur *</label>
<div class="controls">
<select name="id_prefecture" id="id_prefecture"  class="input-xxlarge" >
  <option value="">Choisir la Pr&eacute;fecture</option>
</select>
</div>
</div>
</div>


<div id="nivcant">
<div class="control-group">
<label class="control-label" for="id_canton">Canton du Souscripteur *</label>
<div class="controls">
<select name="id_canton" id="id_canton"  class="input-xxlarge" >
  <option value="">Choisir le canton </option>
</select>
</div>
</div>
</div>
<?php */?>



  
  
  
  
  <legend> Le versement à la banque </legend>
  
  
<div id="nivo_banquespays">
<div class="control-group">
<label class="control-label" for="bon_neutre_banque">Moyen de payement *</label>
<div class="controls">
<select name="bon_neutre_banque" id="bon_neutre_banque"  class="input-xxlarge" required="required">
  <option value="">Choisir le moyen</option>
</select>
</div>
</div>
</div>

<div class="control-group">
<label class="control-label" for="bon_neutre_numero">Numéro de reçu de banque ou Numéro de transaction  * </label>
<div class="controls">
  <input type="text" name="bon_neutre_numero" id="bon_neutre_numero" placeholder="Numero de reçu de banque ou Numéro de transaction" class="input-xxlarge"  required="required" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="bon_neutre_date_numero">Date de reçu de banque ou de transaction  * </label>
<div class="controls">
  <input type="text" name="bon_neutre_date_numero" id="bon_neutre_date_numero" placeholder="Date de reçu de banque ou de transaction" class="input-xxlarge datepicker" data-provide="datepicker"  required="required" readonly />
<span class="help-block"><p class="text-error" style="color:red">Cliquez dans le champ pour choisir la date du reçu de banque ou de transaction</p></span>
</div>
</div>

<?php /*?><div class="control-group">
<label class="control-label" for="bon_neutre_vignette">Scanne du reçu  </label>
<div class="controls">
  <input type="file" name="bon_neutre_vignette" id="bon_neutre_vignette" class="input-xxlarge"  />
<span class="help-block"><p class="text-error">JPEG, JPG, PNG et PDF sont les extentions autorisées</p></span>
</div>
</div><?php */?>
  
  <div class="control-group">
<label class="control-label" for="bon_neutre_montant">Montant du versement à la banque ou de la transaction * </label>
<div class="controls">
  <input type="number" name="bon_neutre_montant" id="bon_neutre_montant" placeholder="Montant du versement à la banque ou de la transaction" class="input-xxlarge"  required="required" />
<span class="help-block"><p class="text-error" style="color:red">Veuillez saisir le montant de votre reçu de banque ou de la transaction</p></span>
</div>
</div>

</fieldset>
<div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enregistrer la souscription au Bon d'Achat neutre BAn</button>
</div>
 
                            
  
</form>

<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
outilqr('addsouscription1');
//outilqrformobligatoire("addsouscription1","submit");
</script>


    


<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php */?>
</div>
</div>
</div>








