<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php //include("../application/layouts/scripts/menuasso.phtml"); ?>


<blockquote><p> Mise à jour de Code Membre Personne Physique </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addcodemembreasso">
  <?php if(isset($sessionmembreasso->error) && $sessionmembreasso->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembreasso->error; $sessionmembreasso->error = ""; ?>
    </div>
  <?php }?>
  
<fieldset>
<legend> Formulaire de mise à jour de Code Membre Personne Physique. </legend>
    
<div class="alert alert-success">
     Veuillez saisir votre <strong> Code Membre Personne Physique </strong> afin que nous puissions relier votre Espace Intégrateur à votre Compte Marchand.
</div>
  
<div class="control-group">
<label class="control-label" for="code_membre"> Votre Code Membre  Personne Physique *</label>
<div class="controls">
<input type="text" name="code_membre" id="code_membre" placeholder="Votre Code Membre Personne Physique " class="input-xlarge"  value="<?php echo $sessionmembreasso->code_membre; ?>" />
</div>
</div>
    
</fieldset> 
   
<div class="form-actions">
<input type="hidden" name="membreasso_id" id="membreasso_id" value="<?php echo $sessionmembreasso->membreasso_id; ?>" />

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" id="submit" class="btn btn-primary">Enregistrer votre Code Membre  Personne Physique</button>
</div>                           
  
</form>

<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
//outilqrformobligatoire("addcodemembreasso","submit");
</script>

<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








