<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>


  <blockquote><p>Mise à jour de son profil utilisateur avec sa souscription</p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addappeloffres">
  <?php if(isset($sessionmembreasso->error) && $sessionmembreasso->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembreasso->error; $sessionmembreasso->error = ""; ?>
    </div>
  <?php }?>
  
<fieldset>
<legend>Formulaire de mise à jour</legend>
    

<div class="control-group">
<label class="control-label" for="membreasso_nom">Numéro de quittance  *</label>
<div class="controls">
<input type="text" name="souscription_ordre" id="souscription_ordre" placeholder="Numéro de quittance " class="input-xlarge" required />
</div>
</div>
    

</fieldset> 
   
    
    

<div class="form-actions">
<input type="hidden" name="membreasso_id" id="membreasso_id" value="<?php echo $sessionmembreasso->membreasso_id; ?>" />

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enregistrer</button>
</div>
 
                            
  
</form>





<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








