<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/integrateur.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script src="<?php echo $this->baseUrl();?>/bootstrap/js/jquery.js"></script>

<script type="text/javascript">
$(document).ready(function() {
	$('#code_membre').blur(function(e) {
	    if($(this).val() !== '') {
            $.get('/integrateur/recupnom',{
                code_membre: $(this).val()
            },
            function success(data) {
                $("#nom_membre").val(data);
	        })
        } else {
            $("#nom_membre").val("");
        }		   
	});
	
    $('#code_membre_beneficiaire').blur(function(e) {
	    if($(this).val() !== '') {
            $.get('/integrateur/recupnom',{
                 code_membre: $(this).val()
            },
            function success(data) {
                $("#beneficiaire").val(data);
	        })
        } else {
            $("#beneficiaire").val("");
        }		   
	});
})
</script>




<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

<blockquote><p class=""> Offreur d'Intégration au Programme de Souscription au Bon de Consommation (BC) pour Tiers </p></blockquote>

<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="inscriptionbc">
  <?php if(isset($sessionmembreasso->error) && $sessionmembreasso->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembreasso->error; $sessionmembreasso->error = ""; ?>
  </div>
  <?php } ?>
  
  <?php if(isset($this->error) && $this->error !="") { ?>
  <div class="alert alert-error">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <?php echo $this->error; ?>
  </div>
  <?php } ?>
  
  <legend>Souscripteur</legend>
    <!--<div class="control-group">
    <label class="control-label" for="type_activation">Type inscription *</label>
    <div class="controls">
    <label for="type_inscription" class="radio">
    <input name="type_inscription" type="radio" checked="checked"  id="inscription_public" value="SansListe" onclick="document.getElementById('active').style.display ='none'; document.getElementById('code_membre_apporteur').required = false;" />
    Personne Non Ciblée</label> </br>

    <label for="type_activation" class="radio">
    <input type="radio" name="type_inscription" id="inscription_prive" value="AvecListe"    onclick="document.getElementById('active').style.display ='block'; document.getElementById('code_membre_apporteur').required = true;" />
    Personne Ciblée </label>
    </div>
    </div>
	-->
	
    <div id="active" class="control-group">
	<label class="control-label" for="code_membre">Code Membre * </label>
    <div class="controls">
    <input name="code_membre_apporteur" type="text" id="code_membre" class="input-xxlarge" placeholder="Entrer Le Code Membre Apporteur de la Souscription pour Tiers au BC" readonly />
	<!--<input name="type_inscription" type="hidden" id="type_inscription" value="AvecListe" class="input-xxlarge" />-->
	</div>
    </div>
	
	         
         <div class="control-group">
         <label class="control-label" > Souscripteur  * </label>
         <div class="controls">
         <input type="text" name="nom_membre" id="nom_membre" placeholder="Désignation "  class="input-block-level" readonly />
         </div>
         </div>
    
<!--<div class="control-group">
    <label class="control-label" for="code_membre">Souscripteur </label>
	<div class="controls">
    <input type="text" name="souscripteur" id="souscripteur" placeholder="" readonly    class="input-xxlarge"  required="required" />
    </div>
    </div>
	
	<div id="active" class="control-group">
	<label class="control-label" for="montant_bc">Montant du BC souscrit * </label>
    <div class="controls">
    <input name="montant_bc" type="number" id="montant_bc" value="<?php //echo $this->montant_bc; ?>" class="input-xxlarge" placeholder="Entrer le Bon de Consommation Minimum (BC) souscrit" required />
	</div>
    </div>
	-->
	
	<div class="control-group">
    <label class="control-label" for="type_souscription">Type Souscription * </label>
    <div class="controls">
    <select name="type_souscription" id="type_souscription"  class="input-xxlarge" >
        <option value=""> Choisir un type de souscription </option>
        <option value="CMIT">Souscription Marchande de type CMIT </option>
        <option value="CAPU">Souscription Marchande de type CAPU </option>
        <option value="CAIPC">Souscription Non Marchande de type CAIPC </option>
		<option value="BPS">Souscription pour Tiers contre BPS</option>
    </select>
    </div>
    </div>
	
    <legend> Bénéficiaire </legend>
	<div class="control-group">
	<label class="control-label" for="liste"> Type Liste *</label>
    <div class="controls">
    <label for="type_inscription0" class="radio">
    <input name="type_inscription" type="radio" id="type_inscription0" checked="checked"  value="AvecListe" required />
    Personne Ciblée
    </label>
	
    <!--
    <label for="type_inscription1" class="radio">
    <input type="radio" name="type_inscription" id="type_inscription1" value="FIFO" required />
    Oui
    </label>
    </div>
    </div>
	-->
	
	
    <div class="control-group">
    <label class="control-label" for="code_membre_beneficiaire"> Code membre * </label>
    <div class="controls">
    <input type="text" name="code_membre_beneficiaire" id="code_membre_beneficiaire" placeholder="Code Membre du Bénéficiaire"  value="<?php echo $this->code_membre; ?>"  class="input-xxlarge"  required />
    </div>
    </div>
	
	
    <div class="control-group">
    <label class="control-label" for="code_membre">Nom & Prenom * </label>
	<div class="controls">
    <input type="text" name="nom_membre" id="beneficiaire" placeholder="" readonly    class="input-xxlarge"  required="required" />
    </div>
    </div>
	
	
	
		 
    <div class="form-actions">
    <input name="publier" type="hidden" id="publier" value="0" />
    <input name="ok" type="hidden" id="ok" value="ok" />
    <button type="reset" class="btn">Annuler</button>
    <button type="submit" id="submit" class="btn btn-primary">Enregistrer</button>
    </div>
</form>

<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
//outilqr('addeli');
outilqrformobligatoire("inscriptionbc","submit");
</script>

</div>

</div>
</div>








