<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/capsenrolement.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/autorisation.js"></script>

<script src="<?php echo $this->baseUrl();?>/bootstrap/js/jquery.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadpays.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadregion.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadprefecture.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadcanton.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadtel.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
		$('#code_membre').blur(function(e) {
	    if($(this).val() !== '') {
            $.get('/integrateur/recupnom',{
                code_membre: $(this).val()
            },
            function success(data) {
                $("#souscripteur").val(data);
	        })
        } else {
            $("#souscripteur").val("");
        }});
		
		
		/*
        $('#id_pays').change(function(e) {
            if($(this).val() !== '') {
	            $('#display_telephone').css('display', 'block'); 
                $('#tab_telephone').css('display', 'block');
                $.get('/integrateur/codetelephonique',{
                    id_pays: $(this).val()
                },
                function success(data) {
                    $('#code_telephonique0').val(data);
			        if($('#cpteur').val() >= 1) {
			            for(var i=1;i < $('#cpteur').val();i++) {
				            $('#code_telephonique' + i).val($('#code_telephonique0').val());
			            }
			        }
                });
                e.preventDefault(); 
	        } else {
	            $('#display_telephone').css('display','none');
			    $('#tab_telephone').css('display','none');
			    $('#numero_telephone0').setAttribute("required","false");
	        }
	        e.preventDefault();
        });
		
		*/
		
    })
	
	
	

    var compteur = 1;
    function addRow(tableID)  {
      var table = document.getElementById(tableID);
      var rowCount = table.rows.length;
      var cpte = rowCount;
      var row = table.insertRow(rowCount);
     
	  var cell1 = row.insertCell(0);
      var element0 = document.createElement("input");
      element0.type = "text";
      element0.setAttribute("id", "code_telephonique" + cpte);
      //element0.setAttribute("name", "code_telephonique" + cpte);
	  
	  element0.setAttribute("name", "code_telephonique[]");
	  element0.setAttribute("readonly", "true");
	  element0.setAttribute("class","input-small");
	  element0.setAttribute("value", $('#code_telephonique0').val());
      cell1.appendChild(element0);
	  
	  var cell2 = row.insertCell(1);
      var element1 = document.createElement("input");
      element1.type = "text";
      element1.setAttribute("id", "numero_telephone" + cpte);
      //element1.setAttribute("name", "numero_telephone" + cpte);
	  
	  element1.setAttribute("name", "numero_telephone[]");
      element1.setAttribute("placeholder","Numéro téléphone");
      cell2.appendChild(element1);
	  
	  compteur = compteur + 1;
      document.getElementById("cpteur").setAttribute('value', compteur);  
  }
  
  function deleteRow(tableID)  {
     try {
         var table = document.getElementById(tableID);
         var rowCount = table.rows.length - 1;
         if (rowCount >= 1) {
            table.deleteRow(rowCount);
            compteur = compteur - 1;
            document.getElementById("cpteur").setAttribute('value', compteur);
         }
      } catch (e) {
         alert(e);
      }
  }


</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

<blockquote><p class="">Offre d'Intégration au Programme de Souscription aux Comptes Marchands pour tiers</p></blockquote>

<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="enrolement">
  
  <?php if(isset($sessionmembreasso->errorlogin) && $sessionmembreasso->errorlogin!="") { ?>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembreasso->errorlogin; $sessionmembreasso->errorlogin = ""; ?>
    </div>
  <?php } ?>
  
  <?php if(isset($this->message) && $this->message!="") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->message; ?>
    </div>
  <?php } ?>
  
  
  <legend>Souscripteur</legend>
    <div class="control-group">
    <label class="control-label" for="type_activation">Type inscription *</label>
    <div class="controls">
    <label for="type_inscription" class="radio">
    <input name="type_inscription" type="radio" checked="checked"  id="inscription_public" value="SansListe" onclick="document.getElementById('active').style.display ='none'; document.getElementById('code_membre').required = false;" />
    Sans Liste</label> </br>
	

    <label for="type_activation" class="radio">
    <input type="radio" name="type_inscription" id="inscription_prive" value="AvecListe"    onclick="document.getElementById('active').style.display ='block'; document.getElementById('code_membre').required = true;" />
    Avec Liste </label>
    </div>
    </div>
	
	<div id="active"  style="display:none;">
    <div class="control-group" >
	<label class="control-label" for="code_membre">Code Membre * </label>
    <div class="controls">
    <input name="code_membre_apporteur" type="text" id="code_membre" class="input-xxlarge" placeholder="Entrer Le Code Membre Apporteur de la Souscription pour Tiers" readonly />
	</div>
    </div>
	
         
         <div class="control-group">
         <label class="control-label" > Désignation  * </label>
         <div class="controls">
         <input type="text" name="nom_membre" id="nom_membre" placeholder="Désignation "  class="input-block-level" readonly />
         </div>
         </div>
    
	
	<!--<div class="control-group">
    <label class="control-label" for="code_membre">Souscripteur </label>
	<div class="controls">
    <input type="text" name="souscripteur" id="souscripteur" readonly  class="input-xxlarge"  required="required" />
    </div>
    </div>
	-->
	</div>
	
	<legend>Remplir le formulaire d'enrôlement</legend>
	
    <legend>Etat civil</legend>
    <div class="">
    <div class="span6">
    <div class="control-group">
    <!-- <label class="control-label" for="code_agence">Agence *</label>
    <div class="controls">
    <select name="code_agence" id="code_agence" required>
        <?php //$tagence = new Application_Model_DbTable_EuAgence();
	      //$select = $tagence->select();
	      //$select->where('code_agence like ? ','001001001001');
          //$results = $tagence->fetchAll($select);?>
          <option value="">Choisir l'agence</option>
          <?php //foreach ($results as $agence): ?>
          <option value="<?php //echo $agence->code_agence; ?>"><?php //echo ($agence->libelle_agence); ?></option>
        <?php //endforeach; ?>
    </select>
    </div>
	-->
    </div>
  
    <div class="control-group">
    <label class="control-label" for="nom_membre">Nom *</label>
    <div class="controls">
    <input type="text" name="nom_membre" id="nom_membre" placeholder="Nom" value="<?php echo $this->nom_membre; ?>" required />
    </div>
    </div>
  
    <div class="control-group">
    <label class="control-label" for="sexe_membre">Genre *</label>
    <div class="controls">
    <select name="sexe_membre" id="sexe_membre" required>
        <option value="">Choisir le genre</option>
        <option value="M" <?php if($this->sexe == 'M') {echo ' selected="selected"';}?>>Masculin</option>
        <option value="F" <?php if($this->sexe == 'F') {echo ' selected="selected"';}?>>Féminin</option>
    </select>
    </div>
    </div>
  
  <div class="control-group">
  <label class="control-label" for="nationalite_membre">Nationalité *</label>
  <div class="controls">
  <select name="nationalite_membre" id="nationalite_membre" required>
       <?php  
	     $pays = new Application_Model_EuPaysMapper();
		 $selectpays = $pays->fetchAll();?>
         <option value="">Choisir une nationalité</option>
         <?php foreach ($selectpays as $selectpays): ?>
         <option value="<?php echo $selectpays->id_pays; ?>" <?php if($this->nation == $selectpays->id_pays){echo ' selected="selected"';}?>><?php echo htmlentities($selectpays->nationalite); ?></option>
       <?php endforeach; ?>
  </select>
  </div>
  </div>
  
  <div class="control-group">
  <label class="control-label" for="pere_membre">Nom du père </label>
  <div class="controls">
  <input type="text" name="pere_membre" id="pere_membre" value="<?php echo $this->pere; ?>" placeholder="Nom du père" />
  </div>
  </div>
  
  <div class="control-group">
  <label class="control-label" for="sitfam_membre">Situation matrimoniale *</label>
  <div class="controls">
  <select name="sitfam_membre" id="sitfam_membre" required>
     <option value="">Choisir situation</option>
     <option value="C" <?php if($this->sitfam == 'C'){echo ' selected="selected"';}?>>Célibataire</option>
     <option value="D" <?php if($this->sitfam == 'D'){echo ' selected="selected"';}?>>Divorcé(e)</option>
     <option value="M" <?php if($this->sitfam == 'M'){echo ' selected="selected"';}?>>Marié(e)</option>
     <option value="V" <?php if($this->sitfam == 'V'){echo ' selected="selected"';}?>>Veuf(ve)</option>
  </select>
  </div>
  </div>
  
</div>
  <div class="span6">
  
  <div class="control-group">
  <label class="control-label" for=""></label>
  <div class="controls">
  &nbsp;<br />&nbsp;
  </div>
  </div>

  
  <div class="control-group">
  <label class="control-label" for="prenom_membre">Prénoms *</label>
  <div class="controls">
  <input type="text" name="prenom_membre" id="prenom_membre" value="<?php echo $this->prenom_membre; ?>" placeholder="Prénoms" required />
  </div>
  </div>
    
  <div class="control-group">
  <label class="control-label" for="date_nais_membre">Date de naissance *</label>
  <div class="controls">
  <input type="date" name="date_nais_membre" id="date_nais_membre" value="<?php echo $this->datnais; ?>" class="input-large datepicker" data-provide="datepicker"  placeholder="Date de naissance" required />
  </div>
  </div>
    
  <div class="control-group">
  <label class="control-label" for="lieu_nais_membre">Lieu de naissance *</label>
  <div class="controls">
  <input type="text" name="lieu_nais_membre" id="lieu_nais_membre" value="<?php echo $this->lieu_nais; ?>" placeholder="Lieu de naissance" required />
  </div>
  </div>
    
  <div class="control-group">
  <label class="control-label" for="mere_membre">Nom de la mère</label>
  <div class="controls">
  <input type="text" name="mere_membre" id="mere_membre" value="<?php echo $this->mere; ?>" placeholder="Nom de la mère" />
  </div>
  </div>
    
  <div class="control-group">
  <label class="control-label" for="nbr_enf_membre">Nombre d'enfant *</label>
  <div class="controls">
  <input type="text" name="nbr_enf_membre" id="nbr_enf_membre" value="<?php echo $this->nbre_enf; ?>" placeholder="Nombre d'enfant" required />
  </div>
  </div>
  
  </div>
  </div>


  <legend>Adresse</legend>
  <div class="">
  <div class="span6">
  <div class="control-group">
  <label class="control-label" for="bp_membre">BP</label>
  <div class="controls">
  <input type="text" name="bp_membre" id="bp_membre" value="<?php echo $this->bp; ?>" placeholder="BP" />
  </div>
  </div>

  <div class="control-group">
  <label class="control-label" for="quartier_membre">Quartier *</label>
  <div class="controls">
  <input type="text" name="quartier_membre" id="quartier_membre" value="<?php echo $this->quartier_membre; ?>" placeholder="Quartier" required />
  </div>
  </div>

  </div>
  
  <div class="span6">

  <div class="control-group">
  <label class="control-label" for="email_membre">Email *</label>
  <div class="controls">
  <input type="text" name="email_membre" id="email_membre" value="<?php echo $this->email; ?>" placeholder="Email" required />
  </div>
  </div>
  
  <div class="control-group">
  <label class="control-label" for="ville_membre">Ville *</label>
  <div class="controls">
  <input type="text" name="ville_membre" id="ville_membre" value="<?php echo $this->ville_membre; ?>" placeholder="Ville" required />
  </div>
  </div>
 
  </div>
  
  </div>  
  
  
  <legend> Localités </legend>

                        <div class="row-fluid">
                            <div class="span4">
							    <div id="nivo_zone">
                                <div class="control-group">
                                    <label class="control-label span4">Zone Monétaire *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="code_zone" name="code_zone" required onchange="ouvre_loadpays(this.value,'nivo_pays');">
                                            <option value="">Choisir une zone monétaire</option>
                                            <?php foreach ($this->zones as $value) { ?>
                                            <option
                                                    value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?></option>
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
								</div>
                            </div>
                            <div class="span4">
							    <div id="nivo_pays">
                                <div class="control-group">
                                    <label class="control-label span4">Pays *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_pays" name="id_pays" required onblur="ouvre_loadtel(this.value,'nivo_telephone');" onchange="ouvre_loadregion(this.value,'nivo_region');" >
                                            <option value="">Choisir un pays</option>
                                            <?php foreach ($this->pays as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
								</div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="span4">
							    <div id="nivo_region">
                                <div class="control-group">
                                    <label class="control-label span4">Régions *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_region" name="id_region" required onchange="ouvre_loadprefecture(this.value,'nivo_prefecture');">
                                            <option value="">Choisir une région</option>
                                            <?php foreach ($this->regions as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
								</div>
                            </div>
                            <div class="span4">
							    <div id="nivo_prefecture">
                                <div class="control-group">
                                    <label class="control-label span4">Préfectures *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_prefecture" name="id_prefecture" required  onchange="ouvre_loadcanton(this.value,'nivo_canton');">
                                            <option value="">Choisir une préfecture</option>
                                            <?php foreach ($this->prefectures as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
								</div>
                            </div>
                            <div class="span4">
							    <div id="nivo_canton">
                                <div class="control-group">
                                    <label class="control-label span4">Cantons *</label>
                                    <div class="controls span8">
                                        <select class="input-block-level" id="id_canton" name="id_canton" required >
                                            <option value="">Choisir un canton</option>
                                            <?php foreach ($this->cantons as $value) { ?>
                                            <option
                                                    value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?></option>
                                                <?php } ?>
                                        </select>
                                    </div>
                                </div>
								</div>
                            </div>
                        </div>
						
	<div class="span12">&nbsp </div>	
  
    <legend>Numéro de téléphone</legend>
	
	<div class="control-group">
	    <label class="control-label" for="numero_telephone">Numéro de téléphone * </label>
        <div class="controls">
		    <div id="nivo_telephone">
		        <input type="text" id="code_telephonique" name="code_telephonique"  class="input-small" readonly />
			</div>
            <input type="text" name="numero_telephone" id="numero_telephone" class="input-xxlarge"  placeholder="Numéro de téléphone" required />
	    </div>
	</div>
    
	
	<!--
	<div id="nivo2">     
    </div>
	
    <div class="control-group" id="display_telephone" style="display:none;">
         <label class="control-label" for="numero_telephone">Numéro de téléphone * </label>
	     <div class="controls">
	          <table id="tab_telephone">
                 <tr>
					 <input type="hidden" name="cpteur" id="cpteur" value="1"/>
                     <td>
					    <input type="text" id="code_telephonique0" name="code_telephonique[]"  class="input-small" readonly />
					 </td>
                     <td>					 
					    <input id="numero_telephone0" type="text" name="numero_telephone[]" placeholder="Numéro de téléphone" class="input-large" required /> 
					 </td>
					 <td>
				        <input class="btn btn-mini"  id="add"     type="button"  value="+"  onclick ="addRow('tab_telephone');"   /> 
					    <input class="btn btn-mini"  id="remove"  type="button"  value="-"  onclick="deleteRow('tab_telephone');" /> 
				     </td>
				 </tr>
              </table>			
	      </div>
     </div>
	 -->
  
  
  <legend>Autres informations</legend>
  <div class="">
  <div class="span6">
  <div class="control-group">
  <label class="control-label" for="profession_membre">Profession *</label>
  <div class="controls">
  <input type="text" name="profession_membre" id="profession_membre" value="<?php echo $this->profession; ?>" placeholder="Profession" required />
  </div>
  </div>

  <div class="control-group">
  <label class="control-label" for="formation">Formation</label>
  <div class="controls">
  <input type="text" name="formation" id="formation" value="<?php echo $this->formation; ?>" placeholder="Formation" />
  </div>
  </div>

  </div>
  
  <div class="span6">

  <div class="control-group">
         <label class="control-label" for="religion_membre">Religion *</label>
         <div class="controls">
         <select name="religion_membre" id="religion_membre" required>
             <?php  $religion = new Application_Model_EuReligionMapper();
		            $selectreligion = $religion->fetchAll();?>
                    <option value="">Choisir une religion</option>
                    <?php foreach ($selectreligion as $selectreligion): ?>
                    <option value="<?php echo $selectreligion->id_religion_membre; ?>" <?php if($this->religion == $selectreligion->id_religion_membre){echo ' selected="selected"';}?>><?php echo htmlentities($selectreligion->libelle_religion); ?></option>
             <?php endforeach; ?>
          </select>
          </div>
    </div>

    <div class="control-group">
    <div class="controls">&nbsp;</div>
    </div>
	
    </div>  
    </div> 
     
    <div id="">&nbsp;</div>
    <div id=""></div>
    <div class="span12">&nbsp </div>
	<legend> Domaines d'activités</legend>
	<div class="control-group">
    <label class="control-label" for="code_activite">Domaine d'activité *</label>
    <div class="controls">
    <select name="code_activite" id="code_activite" onchange="ouvre_competences(this.value);" required="required" class="input-xxlarge">
        <?php $tactivite = new Application_Model_DbTable_EuActivite();
        $results = $tactivite->fetchAll();?>
        <option value="">Choisir le domaine </option>
        <?php foreach ($results as $activite): ?>
               <option value="<?php echo $activite->code_activite; ?>"><?php echo ($activite->nom_activite); ?></option>
        <?php endforeach; ?>
    </select>
    </div>
    </div>

    <div id="niv2">

    <div class="control-group">
    <label class="control-label" for="id_metier">Métiers </label>
    <div class="controls">
    <select name="id_metier" id="id_metier"  class="input-xxlarge" >
       <option value="">Choisir le métier</option>
    </select>
    </div>
    </div>

    <div class="control-group">
    <label class="control-label" for="id_competence" >Compétences </label>
    <div class="controls">
    <select name="id_competence" id="id_competence" class="input-xxlarge" >
       <option value="">Choisir la compétence</option>
    </select>
    </div>
    </div>
    </div>
	
  
    <div class="form-actions">
        <input name="ok" type="hidden" id="ok" value="ok" />
        <button type="reset" class="btn">Annuler</button>
        <button type="submit" class="btn btn-primary">Offrir une intégration</button>
    </div>

</form>

<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
outilqr('enrolement');
//outilqrformobligatoire("enrolement","submit");
</script>

</div>

<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








