<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script><!-- -->

<!--<link href="<?php echo $this->baseUrl();?>/bootstrap/css/bootstrap.css" rel="stylesheet"> -->

<script type="text/javascript" charset="utf-8">			
$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

<blockquote><p>Liste des Offres d'Intégration Sans Liste du Programme de Souscription au BC pour Tiers </p></blockquote>
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
<thead>
	  <tr>
			<th>Date</th>
			<th>Code Membre</th>
			<th>Nom & prénom(s)</th>
			<th>Cellulaire</th>
			<th>Date et lieu de naissance</th>
			<th>Canton</th>
			<th>Ville/Quartier</th>
			<th>Actions</th>
	  </tr>
</thead>
						  
<tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->date_identification); ?> <?php echo ($entry->heure_identification); ?></td>
      <td><?php echo ($entry->code_membre); ?></td>
      <td><?php echo ($entry->nom_membre); ?> <?php echo ($entry->prenom_membre); ?></td>
      <td><?php echo ($entry->portable_membre); ?></td>
      <!--<td><?php echo ($entry->email_membre); ?></td>-->
      <td><?php echo ($entry->date_nais_membre); ?> <?php echo ($entry->lieu_nais_membre); ?></td>
      <td>
	  <?php 
	   if($entry->id_canton > 0) {
           $canton = new Application_Model_EuCanton();
           $cantonM = new Application_Model_EuCantonMapper();
           $cantonM->find($entry->id_canton, $canton);
           echo $canton->nom_canton;
       } ?>
	  </td>
	  <td>
	      <?php
          $reponsetraiter = str_replace("&eacute;","e",strtoupper($entry->ville_membre));		  
		  $reponsetraiter = str_replace("&EACUTE;","E",$reponsetraiter);
		  $reponsetraiter = str_replace("A©","E",$reponsetraiter);
		  echo ucfirst(htmlentities($reponsetraiter));
		  
		  ?> / 
		  
		  <?php echo ucfirst(htmlentities($entry->quartier_membre));?> 
	  </td>
      <td>
	  <div align="center">
	  <?php 
           $mstierslistebc_m = new Application_Model_EuMstiersListebcMapper();
           $mstierslistebc   = $mstierslistebc_m->fetchAllByMembrebeneficiaireTypeliste($entry->code_membre, "AvecListe");
	  ?>
	   <!--
       <?php //if($mstierslistebc == NULL) { ?>
         <a class="btn btn-mini btn-primary" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir envoyer ce membre dans la liste FIFO ?')) location='<?php echo $this->baseUrl(); ?>/integrateur/editmstierslistebc/code_membre/<?php echo $entry->code_membre; ?>'"><i class="icon-trash icon-white"></i> Mettre dans liste FIFO</a>
       <?php //} else { ?>
       <?php //if($mstierslistebc->status == 1) { ?>
			<a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i>  Traité</a>&nbsp;
       <?php //} else { ?>
			<a class="btn btn-mini btn-warning"><i class="icon-off icon-white"></i>  Pas Traité</a>&nbsp;
       <?php //} ?>
	   
       <?php //} ?>
	   -->

	   <!--
       <a class="btn btn-mini btn-info" href="<?php //echo $this->baseUrl(); ?>/integrateur/traiterfifo/id/<?php //echo $entry->code_membre;?>"><i class="icon-edit icon-white"></i>Trier</a>&nbsp;	                        
	   <a class="btn btn-mini btn-success" href="<?php //echo $this->baseUrl(); ?>/integrateur/desactiverfifo/id/<?php //echo $entry->code_membre; ?>/publier/0"> <i class="icon-ok icon-white"> </i> Désactiver </a>&nbsp;
	   <a class="btn btn-mini btn-warning" href="<?php //echo $this->baseUrl(); ?>/integrateur/substituerfifo/id/<?php //echo $entry->code_membre; ?>">Substituer</a>&nbsp;
       -->
	   
       <?php
	        //$db_membrefifo = new Application_Model_EuModel_DbTable_EuMembreFifo();
			//$select = $db_membrefifo->select();
			//$select->where('code_membre_benef = ?',$entry->code_membre);
			//$select->where('valider = ?',1);
			
			//$entries = $db_membrefifo->fetchAll($select);
			//if(count($this->entries) > 0) {
			$entries = 0;
			if($entries > 0) {
       ?>
            <a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i> Déjà Trié </a>&nbsp; 
			
       <?php } else { ?>			
	   
       <a class="btn btn-mini btn-primary" onClick="javascript: if (confirm('&Ecirc;tes vous s&ucirc;r de vouloir trier ce membre ?')) 
		   location='<?php echo $this->baseUrl(); ?>/integrateur/trierfifo/id/<?php echo $entry->code_membre;?>'">
	       <i class="icon-edit icon-white"></i>
		   Trier
	   </a>
	   &nbsp;
	   <?php } ?>
	   
	   <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl();?>/integrateur/desactiverfifo/id/<?php echo $entry->code_membre;?>">
	   <i class="icon-edit icon-white"></i> Désactiver</a>&nbsp;
	   &nbsp;
	   
	   <?php
	   
			//$db_membrefifo = new Application_Model_EuModel_DbTable_EuMembreFifo();
			//$select = $db_membrefifo->select();
			//$select->where('code_membre_benef = ?',$entry->code_membre);
			//$select->where('substituer = ?',1);
			//$select->where('valider = ?',1);
			
			//$entries1 = $db_membrefifo->fetchAll($select);
			//if(count($this->entries1) > 0) {
			$entries1 = 0;
			if($entries > 0) {
	   
	   ?>
	   
	   <a class="btn btn-mini btn-success"><i class="icon-ok icon-white"></i> Substitué </a>&nbsp; 
			
       <?php } else { ?>
	   
	   <a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/integrateur/substituerfifo/id/<?php echo $entry->code_membre;?>">
	   <i class="icon-edit icon-white"></i> Substituer </a>&nbsp;
       
       <?php } ?>	   
	 	
	</div></td> 
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php } else {?>
<div class="alert alert-info">
  Aucun membre trouvé 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








