<?php $sessionmembre = new Zend_Session_Namespace('membre');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

  <blockquote><p>Liste de mes allocations de souscriptions pour tiers</p></blockquote>
<?php if(count($this->entries)>0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:9px;">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>CMFH</th>
								  <th>Code Allocation</th>
								  <th>Montant Utilisé</th>
								  <th>Nombre allouée</th>
								  <th>Nombre utilisé</th>
								  <th>Nombre restant</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo datejourfr($entry->allocation_cmfh_date); ?></td>
      <td><?php if (substr($entry->allocation_cmfh_code_membre_cmfh, -1) == "P") {
$membreM = new Application_Model_EuMembreMapper();
$membre = new Application_Model_EuMembre();
$membreM->find($entry->allocation_cmfh_code_membre_cmfh, $membre);?>
<?php echo htmlentities($membre->nom_membre); ?> <?php echo htmlentities($membre->prenom_membre); ?>
<?php } else if (substr($entry->allocation_cmfh_code_membre_cmfh, -1) == "M") {
$membremoraleM = new Application_Model_EuMembreMoraleMapper();
$membremorale = new Application_Model_EuMembreMorale();
$membremoraleM->find($entry->allocation_cmfh_code_membre_cmfh, $membremorale);?>
<?php echo htmlentities($membremorale->raison_sociale);?>
<?php }	?></td>
      <td><?php echo $entry->allocation_cmfh_code; ?></td>
      <td><?php echo $entry->allocation_cmfh_montant_utilise; ?></td>
      <td><?php echo $entry->allocation_cmfh_nombre; ?></td>
      <td><?php echo $entry->allocation_cmfh_nombre_utilise; ?></td>
      <td><?php echo $entry->allocation_cmfh_nombre_solde; ?></td>
      <td>

<?php if($entry->allocation_cmfh_actif == 1){?>			<i class="icon-ok icon-white"></i>  Activé&nbsp;
<?php }else{?>			<i class="icon-off icon-white"></i>  Désactivé&nbsp;
<?php }?>
            </td>
      </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else {?>
<div class="alert alert-info">
  Aucune allocation 
</div>
<?php }?>


<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








