<?php $sessionmembreasso = new Zend_Session_Namespace('membreasso');?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/integrateur.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script src="<?php echo $this->baseUrl();?>/bootstrap/js/jquery.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('#code_membre_beneficiaire').blur(function(e) {
    if($(this).val() !== '') {
        $.get('/integrateur/recupnom',{
            code_membre: $(this).val()
        },
        function success(data) {
            $("#nom_membre_benef").val(data); 
        })
    } else {
        $("#nom_membre_benef").val("");
    }       
    });
});

</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>

</div>
</div>
</div>




