<div id="view-content">
    <table id="tbl-categorie"></table>
    <div id="pg-categorie"></div>
</div>
<script type="text/javascript">
    $("#tbl-categorie").jqGrid({
           url:'<?php echo $this->url(array('action'=>'data')); ?>',
           editurl:'<?php echo $this->url(array('action'=>'save')); ?>',
        datatype: "json",
        mtype: 'GET',
        colNames:['Code','Libelle','Description'],
        height:440, width:828,
        colModel:[
            {name:'code_categorie',index:'code_categorie', width:75, sorttype:"int", editable: true,align:"left"},
            {name:'libelle_categorie',index:'libelle_categorie', width: 300, editable: true,align:"left"},
            {name:'description_categorie',index:'description_categorie', width: 300, align:"left", editable: true},
        ],
        rowNum:10,
        rowList:[10,20,30],
        pager: '#pg-categorie',
        sortname:"code_categorie",
        viewrecords: true,
        sortorder: "ASC",
        caption:"Liste des catégories de produits"
    });
  
    $("#tbl-categorie").jqGrid('navGrid','#pg-categorie',{edit:true,add:true,del:true,search:true});
</script>