<div id="view-content" title="Transferts effectués sur le GCP" style="font-size:12px;">
    <div style="margin-bottom: 3px; width: 800px">
        <fieldset id="rech_field">
            <legend style=" font-weight:bold">Recherche</legend>
            <table align="center">
                <tr>
                    <td>Date début</td><td><input type="text" id="date_debut" name="date_debut" size="20"/></td>
                    <td>Date fin</td><td><input type="text" id="date_fin" name="date_fin" size="20"/></td>
                    <td><input id="ok" type="button" value="OK" /></td>
                </tr>
            </table>
        </fieldset>
    </div>
    <table id="tbl-domicilie"></table>
    <div id="pg-domicilie"></div>
</div>

<script type="text/javascript">
    $("#tbl-domicilie").jqGrid({
        url:'/eu-dom-pbf/rembourselist?date_deb='+''+'&date_fin='+'',
        editurl:'',
        datatype: "json",
        mtype: 'GET',
        colNames:['Distributeur','Date transfert','Heure transfert','Montant transféré'],
        height:350, width:800,
        colModel:[
            {name:'distributeur',index:'distributeur', width: 160, editable: false,align:"left"},
            {name:'date_op',index:'date_op', width: 110, align:"left", editable: false},
            {name:'heure_op',index:'heure_op', width: 110, align:"left", editable: false},
            {name:'mt_transfert',index:'mt_transfert', width: 150, align:"right",sorttype:'number',formatter:'number',summaryType:'sum'},
        ],
        rowNum:100,
        rowList:[100,200,300],
        rownumbers:true,
        pager: '#pg-domicilie',
        sortname:"code_domici",
        viewrecords: true,
        sortorder: "desc",
        caption:"Liste des transferts sur le compte GCP",
        footerrow: true,
        userDataOnFooter: true
    });
    $("#tbl-domicilie").jqGrid('navGrid','#pg-domicilie',{edit:false,add:false,del:false,search:true});
    
    $(document).ready(function ()
    { 
        $(function(){
            var pickerOpts = {
                dateFormat: "dd/mm/yy",
                changeMonth:true,
                changeYear:true,
                showOtherMonths: true
            };
            $.datepicker.setDefaults( $.datepicker.regional[ "fr" ] );
            $("#date_debut").datepicker(pickerOpts);
            $("#date_fin").datepicker(pickerOpts);
            $('#rech_field').puifieldset();
            $('#view-content').puipanel();
        });
        $('#ok').button();
        $('#ok').click(function(){
            jQuery("#tbl-domicilie").jqGrid('setGridParam',{url:"/eu-dom-pbf/rembourselist?date_deb="+$('#date_debut').val()+"&date_fin="+$('#date_fin').val()}).trigger('reloadGrid');
        });
        
    })
    
</script>