<style>
  .mcnp_loader{
  width: 30px;
  height: 30px;
  display: inline-block;
  vertical-align: middle;
  position: relative;
  margin-left: 25px;
}
.mcnp_loader_quart{

    border-radius: 30px;
    border:6px solid #e29090;
}

.mcnp_loader_quart::after{
     content: "";
     position: absolute;
     top: -6px;
     left: -6px;
     bottom: -6px;
     right: -6px;
     border-radius: 30px;
     border: 6px solid transparent;

     border-top-color: #000;
     -webit-animation : spin 1s linear infinite;
     -moz-animation : spin 1s linear infinite;
     -o-animation : spin 1s linear infinite;

     animation : spin 1s linear infinite;
}

@-webkit-keyframes spin{
  0%{ -webkit-transform:rotate(0deg); -moz-transform:rotate(0deg); -o-transform:rotate(0deg);transform:rotate(0deg); }
  100%{ -webkit-transform:rotate(360deg); -moz-transform:rotate(360deg); -o-transform:rotate(360deg); -ms-transform:rotate(360deg); transform:rotate(360deg); }
}

@-moz-keyframes spin{
  0%{ -webkit-transform:rotate(0deg); -moz-transform:rotate(0deg); -o-transform:rotate(0deg);transform:rotate(0deg); }
  100%{ -webkit-transform:rotate(360deg); -moz-transform:rotate(360deg); -o-transform:rotate(360deg); -ms-transform:rotate(360deg); transform:rotate(360deg); }
}
@-o-keyframes spin{
  0%{ -webkit-transform:rotate(0deg); -moz-transform:rotate(0deg); -o-transform:rotate(0deg);transform:rotate(0deg); }
  100%{ -webkit-transform:rotate(360deg); -moz-transform:rotate(360deg); -o-transform:rotate(360deg); -ms-transform:rotate(360deg); transform:rotate(360deg); }
}

@keyframes spin{
  0%{ -webkit-transform:rotate(0deg); -moz-transform:rotate(0deg); -o-transform:rotate(0deg);transform:rotate(0deg); }
  100%{ -webkit-transform:rotate(360deg); -moz-transform:rotate(360deg); -o-transform:rotate(360deg); -ms-transform:rotate(360deg); transform:rotate(360deg); }
}


</style>


<?php

$month = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
$true_month = "";
$ex_date = explode('-',$this->entriesavaliderparlatechnopoleapreslegerant[0]->date_demande);

foreach ($month as $key => $value) {
  if($ex_date[1] == $key){
    $true_month = $value;
  }
}
$next_ex_date = explode(' ', $ex_date[2]);
$true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0];

?>

<h3>DEMANDE D'ACHAT N° <?php echo $this->entriesavaliderparlatechnopoleapreslegerant[0]->reference_demande_achat ;?></h3>

<p style="text-align: right;font-weight: bold;">Date:<?php echo $true_date ;?></p>

<table class="table table-stripped">
    <thead>
        <tr>
			<th>Références</th>
			<th>Désignation des Articles </th>
			<th>Quantité </th>
			<th>Prix Unitaire</th>
			<th>TOTAL</th>
		</tr> 
    </thead>
    <tbody>
     <?php foreach ($this->detailachatavaliderparlatechnopoleapreslegerant as $key => $value): ?>
     <?php
       $quantite = $this->detailachatavaliderparlatechnopoleapreslegerant[0]->quantite;
       $prix_unitaire = $this->detailachatavaliderparlatechnopoleapreslegerant[0]->prix_unitaire;
       $total = $quantite * $prix_unitaire;
      ?>
      <tr>
        
        <td><?php echo $value->reference_article ;?></td>
        <td><?php echo $value->designation_article ;?></td>
        <td><?php echo $value->quantite;?></td>
        <td><?php echo $value->prix_unitaire;?></td>
        <td id="total_visa_demande_achat"><?php echo $total;?></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><label for="">Montant demande d’Achat</label></td>
		<td id="montant_total_visa_demande_achat"><?php echo $this->entriesavaliderparlatechnopoleapreslegerant[0]->montant_demande_achat;?></td>			                     
	 </tr>
    </tbody>
 	<?php endforeach ?>
</table> 

<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
  <strong ><i><span style="text-decoration:underline">NB</span>: Cadre reservé à la Technopole/ l’Agent Filière.</i></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
 <strong style="margin-bottom:15px;"> Visa de la technopole/Filiere <input type="text" style="border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 80%;height: 28px;font-size: 1.8em;font-family: Matura MT Script Capitals;text-transform:uppercase;margin-top: -29px;margin-left: 176px;background: transparent;padding: 0;" id="visa_technofiliere_demande_achat" value="ok" readonly="true"></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
</div>

<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
  <strong ><i><span style="text-decoration:underline">NB</span>: Cadre reservé au gérant.</i></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
 <strong style="margin-bottom:15px;"> Visa du gérant <input type="text" style="border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 80%;height: 28px;font-size: 1.8em;font-family: Matura MT Script Capitals;text-transform:uppercase;margin-top: -29px;margin-left: 176px;background: transparent;padding: 0;" id="visa_technofiliere_demande_achat" value="ok" readonly="true"></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
</div>


<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
   <a class="btn btn-success" href="" data-iddemandeachattechnopoletoacnev="<?php echo $this->entriesavaliderparlatechnopoleapreslegerant[0]->id_demande_achat; ?>" id="btn_demandeachat_gerant_to_technopole_to_acnev"><i class="icon-cog icon-white"></i>Transmettre la demande à l'acnev</a>
   <span id="chargement_revendeurdemandeachatgeranttoacnev" style="position: relative;display:none;top: 8px;">
        <div class="mcnp_loader mcnp_loader_quart"></div>
        <span style="display: inline-block;font-size: 1.6em;">Chargement...</span>
   </span>
</div>
