<?php

$month = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
$true_month = "";
$true_month_livraison = "";
$true_demande_achat = "";


$ex_bon_commande_date = explode('-',$this->searchdunbondecommandeenfonctiondufournisseur[0]->date_bon_commande);
$ex_livraison_date = explode('-',$this->searchdunbondecommandeenfonctiondufournisseur[0]->date_livraison);
foreach ($month as $key => $value) {
  if($ex_bon_commande_date[1] == $key){
    $true_month = $value;
  }

  if($ex_livraison_date[1] == $key){
    $true_month_livraison = $value;
  }


}
$next_ex_bon_commande_date = explode(' ', $ex_bon_commande_date[2]);
$true_date = $next_ex_bon_commande_date[0]." ".$true_month." ".$ex_bon_commande_date[0];

$next_ex_livraison_date = explode(' ', $ex_livraison_date[2]);
$true_date_livraison = $next_ex_livraison_date[0]." ".$true_month_livraison." ".$ex_livraison_date[0];

?>

<h3>BON DE COMMANDE N° <?php echo $this->searchdunbondecommandeenfonctiondufournisseur[0]->reference_bon_commande ;?></h3>

<p style="text-align: right;font-weight: bold;">Date:<?php echo $true_date ;?></p>

  <div class="control-group">
	  <label class="control-label" for="code_membre_fournisseur" style="font-weight:bold;display:inline-block">
	        Code membre du fournisseur:
	  </label>
	  <div class="controls" style="display:inline-block">
    <?php echo $this->searchdunbondecommandeenfonctiondufournisseur[0]->code_membre_fournisseur_bon_commande ;?>
		 </div>
	</div>

  <div class="control-group">
	  <label class="control-label" for="code_membre_fournisseur" style="font-weight:bold;display:inline-block">
	        Date de livraison:
	  </label>
	  <div class="controls" style="display:inline-block">
    <?php echo $true_date_livraison ;?>
    
    </div>
	</div>
<table class="table table-stripped">
    <thead>
        <tr>
			<th>Références</th>
			<th>Désignation des Articles </th>
			<th>Quantité </th>
			<th>Prix Unitaire</th>
			<th>TOTAL</th>
		</tr> 
    </thead>
    <tbody>
     <?php foreach ($this->searchdetaildubondecommandeenfonctiondufournisseur as $key => $value): ?>
     <?php
       $quantite = $value->quantite;
       $prix_unitaire = $value->prix_unitaire;
       $total = $quantite * $prix_unitaire;
      ?>
      <tr>
        
        <td><?php echo $value->reference_article ;?></td>
        <td><?php echo $value->designation_article ;?></td>
        <td><?php echo $value->quantite;?></td>
        <td><?php echo $value->prix_unitaire;?></td>
        <td><?php echo $total;?></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><label for="">Montant du bon de commande</label></td>
	     	<td><?php echo $this->searchdunbondecommandeenfonctiondufournisseur[0]->montant_bon_commande;?><</td>			                     
	 </tr>
    </tbody>
 	<?php endforeach ?>
</table>