<?php

$month = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
$true_month = "";
$true_month_livraison = "";
$true_demande_achat = "";


$ex_bon_commande_date = explode('-',$this->entriesparlatechnopoleapreslafiliere[0]->date_bon_commande);
$ex_livraison_date = explode('-',$this->entriesparlatechnopoleapreslafiliere[0]->date_livraison);
$ex_demande_achat = explode('-',$this->entriesparlatechnopoleapreslafiliere[0]->date_demande);
foreach ($month as $key => $value) {
  if($ex_bon_commande_date[1] == $key){
    $true_month = $value;
  }

  if($ex_livraison_date[1] == $key){
    $true_month_livraison = $value;
  }

  if($ex_demande_achat[1] == $key){
    $true_demande_achat = $value;
  }

}

$next_ex_bon_commande_date = explode(' ', $ex_bon_commande_date[2]);
$true_date = $next_ex_bon_commande_date[0]." ".$true_month." ".$ex_bon_commande_date[0];

$next_ex_livraison_date = explode(' ', $ex_livraison_date[2]);
$true_date_livraison = $next_ex_livraison_date[0]." ".$true_month_livraison." ".$ex_livraison_date[0];

$next_ex_demande_achat = explode(' ', $ex_livraison_date[2]);
$true_date_demande_achat = $next_ex_demande_achat[0]." ".$true_demande_achat." ".$ex_demande_achat[0];
?>

<h3>BON DE COMMANDE N° <?php echo $this->entriesparlatechnopoleapreslafiliere[0]->reference_bon_commande ;?></h3>

<p style="text-align: right;font-weight: bold;">Date:<?php echo $true_date ;?></p>

  <div class="control-group">
	  <label class="control-label" for="code_membre_fournisseur" style="font-weight:bold;display:inline-block">
	        Code membre du fournisseur:
	  </label>
	  <div class="controls" style="display:inline-block">
    <?php echo $this->entriesparlatechnopoleapreslafiliere[0]->code_membre_fournisseur_bon_commande ;?>
		 </div>
	</div>

  <div class="control-group">
	  <label class="control-label" for="code_membre_fournisseur" style="font-weight:bold;display:inline-block">
	        Date de livraison:
	  </label>
	  <div class="controls" style="display:inline-block">
    <?php echo $true_date_livraison ;?>
    
    </div>
	</div>
<table class="table table-stripped">
    <thead>
        <tr>
			<th>Références</th>
			<th>Désignation des Articles </th>
			<th>Quantité </th>
			<th>Prix Unitaire</th>
			<th>TOTAL</th>
		</tr> 
    </thead>
    <tbody>
     <?php foreach ($this->detailbondecommandeparlatechnopoleapreslafiliere as $key => $value): ?>
     <?php
       $quantite = $value->quantite;
       $prix_unitaire = $value->prix_unitaire;
       $total = $quantite * $prix_unitaire;
      ?>
      <tr>
        
        <td><?php echo $value->reference_article ;?></td>
        <td><?php echo $value->designation_article ;?></td>
        <td><?php echo $value->quantite;?></td>
        <td><?php echo $value->prix_unitaire;?></td>
        <td id="total_visa_demande_achat"><?php echo $total;?></td>
      </tr>
 	<?php endforeach ?>
      
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><label for="">Montant total de la commande</label></td>
		<td id="montant_total_visa_demande_achat"><?php echo $this->entriesparlatechnopoleapreslafiliere->montant_bon_commande;?></td>			                     
	 </tr>
    </tbody>
</table>
<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
  <strong ><i><span style="text-decoration:underline">NB</span>: Cadre reservé à l’Agent Filière.</i></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
 <strong style="margin-bottom:15px;"> Visa de la Filiere <input type="text" style="border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 80%;height: 28px;font-size: 1.8em;font-family: Matura MT Script Capitals;text-transform:uppercase;margin-top: -29px;margin-left: 176px;background: transparent;padding: 0;" id="visa_technofiliere_demande_achat" value="ok" readonly="true"></strong></div><div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
</div>

<!--Apposer le visa sur la demande d'achat si le budget le permet -->
<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
   <a class="btn btn-success" href="" data-idcommandetechnopoletogerant="<?php echo $this->entriesparlatechnopoleapreslafiliere[0]->id_bon_commande; ?>" id="btn_commande_filiere_to_technopole_to_gerant"><i class="icon-cog icon-white"></i>Transmettre la demande au gérant</a>
   <span id="chargement_valid_commandetechnopoletogerant" style="position: relative;display:none;top: 8px;">
        <div class="mcnp_loader mcnp_loader_quart"></div>
        <span style="display: inline-block;font-size: 1.6em;">Chargement...</span>
   </span>
</div>