<style>
#separator{
    border: 0;
    height: 1px;
    background: #333;
    background-image: -webkit-linear-gradient(left, #ccc, #333, #ccc);
    background-image: -moz-linear-gradient(left, #ccc, #333, #ccc);
    background-image: -ms-linear-gradient(left, #ccc, #333, #ccc);
    background-image: -o-linear-gradient(left, #ccc, #333, #ccc);
    margin-bottom: 15px;
}

.wrap_error_forms_procedure{
  border: 2px solid #FF0000;
  color: #FF0000;
  
}

.wrap_error_forms_procedure::-webkit-input-placeholder{
  color: #FF0000;
  opacity: 1;
}

.wrap_error_forms_procedure::-ms-input-placeholder{
  color: #FF0000;
  opacity: 1;
}

.wrap_error_forms_procedure::placeholder{
  color: #FF0000;
  opacity: 1;
}

</style>



<?php

$month = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
$true_month = "";
$true_month_livraison = "";
$true_demande_achat = "";


$ex_bon_commande_date = explode('-',$this->recherchedubondecommandeenfonctiondeid[0]->date_bon_commande);
$ex_livraison_date = explode('-',$this->recherchedubondecommandeenfonctiondeid[0]->date_livraison);
foreach ($month as $key => $value) {
  if($ex_bon_commande_date[1] == $key){
    $true_month = $value;
  }

  if($ex_livraison_date[1] == $key){
    $true_month_livraison = $value;
  }

}
$next_ex_bon_commande_date = explode(' ', $ex_bon_commande_date[2]);
$true_date = $next_ex_bon_commande_date[0]." ".$true_month." ".$ex_bon_commande_date[0];

$next_ex_livraison_date = explode(' ', $ex_livraison_date[2]);
$true_date_livraison = $next_ex_livraison_date[0]." ".$true_month_livraison." ".$ex_livraison_date[0];
?>

			<?php if (isset($_SESSION["validationdemandeerrors"])): ?>
				<div class="alert alert-danger">
					<?php echo implode('<br>', $_SESSION['validationdemandeerrors']) ?>
				</div>
			<?php unset($_SESSION['validationdemandeerrors']); endif ?>
			<?php if (isset($_SESSION["validationpertesuccess"])): ?>
				<div class="alert alert-success">
					<li><?php echo implode('<br>',$_SESSION['validationpertesuccess']) ?></li>
				</div>
			<?php unset($_SESSION['validationpertesuccess']); endif ?>


<h3>BON DE COMMANDE N° <?php echo $this->recherchedubondecommandeenfonctiondeid[0]->reference_bon_commande ;?></h3>

<p style="text-align: right;font-weight: bold;">Date:<?php echo $true_date ;?></p>

  <div class="control-group">
	  <label class="control-label" for="code_membre_fournisseur" style="font-weight:bold;display:inline-block">
	        Code membre du fournisseur:
	  </label>
	  <div class="controls" style="display:inline-block">
    <?php echo $this->recherchedubondecommandeenfonctiondeid[0]->code_membre_fournisseur_bon_commande ;?>
		 </div>
	</div>

  <div class="control-group">
	  <label class="control-label" for="code_membre_fournisseur" style="font-weight:bold;display:inline-block">
	        Date de livraison:
	  </label>
	  <div class="controls" style="display:inline-block">
    <?php echo $true_date_livraison ;?>
    
    </div>
	</div>
    <hr id="separator">

    <blockquote>
      Détail du Bon de commande
    </blockquote>
    <hr id="separator">


<table class="table table-stripped">
    <thead>
        <tr>
			<th>Références</th>
			<th>Articles Commandés</th>
			<th>Quantité Commandé</th>
			<th>Prix Unitaire</th>
			<th>TOTAL</th>
		</tr> 
    </thead>
    <tbody>
     <?php foreach ($this->detaildubondecommande as $key => $value): ?>
     <?php
       $quantite = $value->quantite;
       $prix_unitaire = $value->prix_unitaire;
       $total = $quantite * $prix_unitaire;
      ?>
      <tr>
        
        <td><?php echo $value->reference_article ;?></td>
        <td><?php echo $value->designation_article ;?></td>
        <td><?php echo $value->quantite;?></td>
        <td><?php echo $value->prix_unitaire;?></td>
        <td><?php echo $total;?></td>
      </tr>
    </tbody>
 	<?php endforeach ?>
     <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><label for="">Montant du bon de commande</label></td>
        <td id="montant_total_visa_demande_achat"><?php echo $this->recherchedubondecommandeenfonctiondeid[0]->montant_bon_commande ;?></td>			                     
	 </tr>
</table>
<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
  <strong >
     <i>
       <span style="text-decoration:underline">NB</span>: Cadre reservé à la Technopole/ l’Agent Filière.</i>
  </strong>
</div>
<div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
 <strong style="margin-bottom:15px;"> Visa de la technopole/Filiere
    <span style="display:block;border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 80%;height: 28px;font-size: 1.8em;font-family: Matura MT Script Capitals;text-transform:uppercase;margin-top: -29px;margin-left: 176px;background: transparent;padding: 0;"><?php echo $this->recherchedubondecommandeenfonctiondeid[0]->visatechfiliere ;?></span>
 </strong>
 </div>


<div style="text-align:left;margin-bottom:5px;margin-top:5px;">
  <strong >
     <i>
       <span style="text-decoration:underline">NB</span>: Cadre reservé au gérant.</i>
  </strong>
</div>
<div style="text-align:left;padding:5px;padding-top:20px;border:1px solid #000">
 <strong style="margin-bottom:15px;"> Visa du gérant
    <span style="display:block;border: none;outline: none;box-shadow: 0px 0px 0px #FFF;color: #000;width: 80%;height: 28px;font-size: 1.8em;font-family: Matura MT Script Capitals;text-transform:uppercase;margin-top: -29px;margin-left: 176px;background: transparent;padding: 0;"><?php echo $this->recherchedubondecommandeenfonctiondeid[0]->visagerant ;?></span>
 </strong>
 </div>

    <hr id="separator">

    <blockquote>
      Etablissement du bon de livraison
    </blockquote>

    <hr id="separator">

      <div class="control-group">
	      <label class="control-label" for="libellé du bon de livraison" style="font-weight:bold">
	        Libellé du bon de livraison *:
	      </label>
	      <div class="controls">
		     <input type="text" name="libelle_bon_livraison" class="input-block-level" id="libelle_bon_livraison" placeholder="Mettre ici le libellé du bon de livraison" required="required"/>
	      
        </div>
	    </div>

      <div class="control-group">
	      <label class="control-label" for="montant du bon de livraison" style="font-weight:bold">
	        Montant du bon de livraison *:
	      </label>
	      <div class="controls">
		     <input type="text" name="montant_bon_livraison" class="input-block-level" id="montant_bon_livraison" placeholder="Mettre ici le montant du bon de livraison" required="required"/>
	      </div>
	    </div>
   <div class="alert alert-danger" id="alert-correspondance-livraison-procedure" style="display:none"></div>

    <table class="table table-stripped">
    <thead>
        <tr>
			<th>Références</th>
			<th>Designation</th>
			<th>Quantité Commandée</th>
			<th>Quantité livrée</th>
			<th>Quantité restant à livré</th>
			<th>Observations</th>
      
      
		</tr> 
    </thead>
    <tbody id="tabdetaildesarticlesalivrer">
    <?php foreach ($this->detaildubondecommande as $key => $value): ?>
       <tr>
        <td> <input type="text" id="ref_article_bon_livraison" style="background-color: transparent;border: none;cursor: default;" name="ref_article_bon_livraison[]" value="<?php echo $value->reference_article ;?>" required="required" readonly="true"></td>
        <td><input type="text" id="designation_article_bon_livraison" style="background-color: transparent;border: none;cursor: default;" name="designation_article_bon_livraison[]" value="<?php echo $value->designation_article ;?>" required="required" readonly="true"></td>
        <td><input type="text" id="qte_commande_bon_livraison" name="qte_commande_bon_livraison[]" required="required" value="<?php echo $value->quantite ;?>" readonly="true"></td>
        <td><input type="text" id="qte_livraison_bon_livraison" name="qte_livraison_bon_livraison[]" required="required" value="0"></td>
        <td><input type="text" id="qte_restant_bon_livraison" name="qte_restant_bon_livraison[]" required="required" readonly="true" value="0"></td>
        
        <td>
          <textarea id="observation_bon_livraison" name="observation_bon_livraison[]" cols="30"></textarea>
        </td>
        
       </tr>

   	<?php endforeach ?>
     <input type="hidden" value="<?php echo $this->recherchedubondecommandeenfonctiondeid[0]->id_bon_commande ;?>">
    </tbody>
</table>
    
<button class="btn btn-primary" id="clone_bon_livraison_plus">Ajouter</button>
     
    
    
