
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
        $('#example').dataTable({
          "sPaginationType": "full_numbers",
          "aaSorting": []
        });
      });
    </script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>



  <blockquote>Achat Vente Reciproque - centrale d'achat: liste de tous les demandes d'achat AR</blockquote>
 
  
<?php if($this->arraylistdesavr > 0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
   <thead>
  <tr>
    <th>Code membre de l'acheteur</th>
    <th>Nom & Prénoms/Raison sociale de l'acheteur</th>
    <th>Référence de l'avr</th>
    <th>Montant total </th>    
    <th>Mode de paiement</th>
    <th>Date de soumission de la demande</th>
    <th>Actions</th>

  </tr>         
   </thead>
   <tbody>
      <?php foreach ($this->arraylistdesavr as $key => $value): ?>
        <tr>
          <td><?php echo $value['code_membre_acheteur'] ;?></td>
           
          <?php 
           $arcode_membre = $value['code_membre_acheteur'];
           if (substr($arcode_membre,-1) == "P"): ?>
            <td><?php echo $value['nometprenomsar'] ;?></td>
           <?php endif;?>
           <?php if (substr($arcode_membre,-1) == "M"): ?>
            <td><?php echo $value['raison_socialear'] ;?></td>
           <?php endif;?>
          <td><?php echo $value['reference_ar'] ;?></td>
          <td><?php echo $value['montant_total_avr'];?></td>
          <td><?php echo $value['mode_paiement'];?></td>          
          <td><?php echo $value['date_achat_ar'];?></td>
          
          <td><a href="centraledachatlistedesdetailsdesavr/id/<?php echo $value['id_ar'] ?>" class="btn btn-danger" target="_blank">Détails</a></td>
          
        </tr>
  <?php endforeach ?>
   </tbody>

 </table>
<?php } else {?>
<div class="alert alert-info">
  Aucune demande avr disponible
</div>
<?php }?>




</div>

</div>
</div>
