
<section id="ar-vr-container">
                                                                     
    <div id="ar-content">
                                                                   
        <div id="ar-content-header">AR</div>
                                                                   
        <article id="ar-content-body">
            <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </article>
                                                                   
        <div id="ar-content-footer">
            <span>Nbre de </span>
            <span>2 </span>
                                                                      
        </div>
                                                                         
    </div>
                                                                   
    <div id="vr-content">   
                                                                   
        <div id="vr-content-header">VR</div>
                                                                   
            <article id="ar-content-body">
                <ul>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ul>
            </article>
                                                                   
            <div id="ar-content-footer">
                <span>Nbre de </span>
                <span>3 </span>
            </div>
                                                                     
    </div>
</section>