
<div class="row">
  <div class="span12">
    <blockquote>Achat Vente Reciproque - centrale de vente: Détails du produit avr non listés</blockquote>
  
    <div class="span6">
        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Code membre du fournisseur*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->code_membre_morale ;?>
          </div>
        </div>

        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Raison sociale du fournisseur*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->raison_sociale ;?>
          </div>
        </div>

        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Nom et prénoms du représentant*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->nomsetprenoms ;?>
          </div>
        </div>

    </div>

    <div class="span6">
        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Designation du produit*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->designation ;?>
          </div>
        </div>
        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Reference du produit*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->reference ;?>
          </div>
        </div>

        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Terminal d'Echange*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->categorie ;?>
          </div>
        </div>

        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Quantité en stock *:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->qte_stock ;?>
          </div>
        </div>

        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Quantité vendue *:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->qte_vendu ;?>
          </div>
        </div>

        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Quantité restant *:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->qte_solde ;?>
          </div>
        </div>



        


        <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold;display:inline-block">
	        Prix unitaire*:
	      </label>
	      <div class="controls" style="display:inline-block">
          <?php  echo $this->articlestockesdejavalider[0]->prix_eli ;?>
          </div>
        </div>
    </div>
    
  </div>

</div>