
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
        $('#example').dataTable({
          "sPaginationType": "full_numbers",
          "aaSorting": []
        });
      });
    </script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>


  <blockquote>Achat Vente Reciproque - centrale de vente: Détails du produit avr non listés</blockquote>
 
  <div class="span6">

    <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold">
	        Code membre de l'acheteur*:
	      </label>
	      <div class="controls">
          <?php  echo $this->lalistedesdetailstouslesautresproduitsavrnonlistes[0]->code_membre_acheteur ;?>
          </div>
    </div>
    <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold">
	        Nom de l'acheteur*:
	      </label>
	      <div class="controls">
          <?php  echo $this->lalistedesdetailstouslesautresproduitsavrnonlistes[0]->nom_membre ;?>
          </div>
	</div>
    <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold">
	        Prénoms de l'acheteur*:
	      </label>
	      <div class="controls">
          <?php  echo $this->lalistedesdetailstouslesautresproduitsavrnonlistes[0]->prenom_membre ;?>
          </div>
	</div>
  </div>

  <div class="span6">
    <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold">
	        Nom du produit*:
	      </label>
	      <div class="controls">
          <?php  echo $this->lalistedesdetailstouslesautresproduitsavrnonlistes[0]->nom_produit ;?>
          </div>
    </div>
    <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold">
	        Quantitié du produit demandé*:
	      </label>
	      <div class="controls">
          <?php  echo $this->lalistedesdetailstouslesautresproduitsavrnonlistes[0]->qte_demande ;?>
          </div>
    </div>
    <div class="control-group">
	      <label class="control-label" for="avr-produit-inexistant" style="font-weight:bold">
	        Caractéristique du produit demandé*:
	      </label>
	      <div class="controls">
          <?php  echo $this->lalistedesdetailstouslesautresproduitsavrnonlistes[0]->caracteristique_produit ;?>
          </div>
    </div>
  </div>
</div>
</div>
</div>