
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
    <script type="text/javascript" charset="utf-8">
      /*$(document).ready(function() {
        $('#example').dataTable();
      } );*/
      $(document).ready(function() {
        $('#example').dataTable({
          "sPaginationType": "full_numbers",
          "aaSorting": []
        });
      });
    </script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>


  <blockquote>Achat Vente Reciproque - centrale de vente: La liste des autres produits demandés par l'acheteur</blockquote>
 
  
<?php if($this->countlalistedetouslesautresproduitsavrnonlistes > 0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
   <thead>
  <tr>
    <th>Code membre de l'acheteur</th>
    <th>Nom du produit</th>
    <th>Quantité de la demande</th>
    <th>Date de mise en service</th>
    <th>Actions</th>

  </tr>         
   </thead>
   <tbody>
      <?php foreach ($this->lalistedetouslesautresproduitsavrnonlistes as $key => $value): ?>
        <tr>
          <td><?php echo $value->code_membre_acheteur ;?></td>
          <td><?php echo $value->nom_produit ;?></td>
          <td><?php echo $value->qte_demande ;?></td>
          <td><?php echo $value->date_demande ;?></td>
          <td><a href="interfacelistedesdetailsdesautresproduitsavr/id/<?php echo $value->id ?>" class="btn btn-danger" target="_blank">Détails</a></td>
          
        </tr>
  <?php endforeach ?>
   </tbody>

 </table>
<?php } else {?>
<div class="alert alert-info">
  Aucun autre articles avr  disponible
</div>
<?php }?>




</div>

</div>
</div>
