<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
	<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Detail d'une souscription</p></blockquote>
  
    

<fieldset>
  <legend>Detail d'une souscription </legend>
    

<div class="control-group">
   <label class="control-label" for="souscription_membreasso">L'utilisateur :<?php 
        $membreasso = new Application_Model_EuMembreasso();
        $membreassoM = new Application_Model_EuMembreassoMapper();
        $membreassoM->find($this->souscription->souscription_membreasso, $membreasso);
        echo $membreasso->membreasso_nom." ".$membreasso->membreasso_prenom; ?>
    </label>
</div>

<div class="control-group">
  <label class="control-label" for="souscription_personne">Type du souscripteur : <?php echo $this->souscription->souscription_personne; ?></label>
 </div>
  
<div class="control-group">
   <label class="control-label" for="souscription_autonome">Souscription Autonome : <?php if($this->souscription->souscription_autonome == 1){echo 'La Souscription Autonome est compris dans la souscription';}?></label>
</div>

<div class="control-group">
<label class="control-label" for="souscription_nom">Nom du souscripteur : <?php echo $this->souscription->souscription_nom; ?> </label>
</div>
    
<div class="control-group">
<label class="control-label" for="souscription_prenom">Prénom du souscripteur : <?php echo $this->souscription->souscription_prenom; ?></label>
</div>

<div class="control-group">
  <label class="control-label" for="souscription_raison">Raison sociale du souscripteur : <?php echo $this->souscription->souscription_raison; ?></label>
</div>

<div class="control-group">
<label class="control-label" for="type_acteur">
Type Agrément OSE/OE : <?php 
  if($this->souscription->code_type_acteur == 'EI'){
    echo 'Entreprise Industrie';
  }else if($this->souscription->code_type_acteur == 'OE') {
    echo 'Opérateur Economique';
  }else if($this->souscription->code_type_acteur == 'OSE'){
    echo 'Opérateur Socio-Economique';
  }else if($this->souscription->code_type_acteur == 'PEI'){
    echo 'Partenaire Entreprise Industrie';
  }else if($this->souscription->code_type_acteur == 'POE'){
    echo 'Partenaire Opérateur Economique';
  }else if($this->souscription->code_type_acteur == 'POSE'){
    echo 'Partenaire Opérateur Socio-Economique';
  }
  ?>
  </label>
</div>

<div class="control-group">
<label class="control-label" for="statut_juridique">Statut juridique : <?php 
        $statutjuridique = new Application_Model_EuStatutJuridique();
        $statutjuridiqueM = new Application_Model_EuStatutJuridiqueMapper();
        $statutjuridiqueM->find($this->souscription->code_statut, $statutjuridique);
echo $statutjuridique->libelle_statut; ?></label>

</div>

<div class="control-group">
<label class="control-label" for="souscription_mobile">Cellulaire du souscripteur : <?php echo $this->souscription->souscription_mobile; ?></label>
</div>

<div class="control-group">
<label class="control-label" for="souscription_email">
E-mail du souscripteur : <?php echo $this->souscription->souscription_email; ?></label>
</div>

<div class="control-group">
<label class="control-label" for="souscription_ville">
 Ville du souscripteur : <?php echo $this->souscription->souscription_ville; ?>
 </label>
</div>

<div class="control-group">
  <label class="control-label" for="souscription_quartier">Quartier du souscripteur : <?php echo $this->souscription->souscription_quartier; ?>
  </label>
</div>

<div class="control-group">
  <label class="control-label" for="souscription_programme">Type de programme : <?php echo $this->souscription->souscription_programme; ?></label>
</div>
  
<div class="control-group">
<label class="control-label" for="souscription_type_candidat">Type CMFH : 
<?php if($this->souscription->souscription_type_candidat > 0 && $this->souscription->souscription_type_candidat != ""){
    $type_candidatM = new Application_Model_DbTable_EuTypeCandidat();
        $type_candidat = $type_candidatM->find($this->souscription->souscription_type_candidat);
    $row = $type_candidat->current();
echo $row->libelle_type_candidat;} ?>
</label>
</div>

<?php /*?><div class="control-group">
<label class="control-label" for="souscription_filiere">Filière </label>
<div class="controls">
<?php 
        $filiere = new Application_Model_EuFiliere();
        $filiereM = new Application_Model_EuFiliereMapper();
        $filiereM->find($this->souscription->souscription_filiere, $filiere);
echo $filiere->nom_filiere; ?>
</div>
</div><?php */?>

<div class="control-group">
<label class="control-label" for="code_activite">
   Activité : <?php if($entry->code_activite > 0){
        $activiteM = new Application_Model_DbTable_EuActivite();
        $activite = $activiteM->find($this->souscription->code_activite);
    $row = $activite->current();
echo $row->nom_activite;} ?>
</label>
</div>

<div class="control-group">
<label class="control-label" for="id_metier">
  Métier : <?php if($entry->id_metier > 0){
        $metierM = new Application_Model_DbTable_EuMetier();
        $metier = $metierM->find($this->souscription->id_metier);
    $row = $metier->current();
echo $row->libelle_metier;} ?></label>
</div>

<div class="control-group">
<label class="control-label" for="id_competence">
   Compétence :<?php if($entry->id_competence > 0){
        $competenceM = new Application_Model_DbTable_EuCompetence();
        $competence = $competenceM->find($this->souscription->id_competence);
        $row = $competence->current();
        echo $row->libelle_competence;} ?></label>
</div>

<div class="control-group">
  <label class="control-label" for="souscription_type">Type payement : <?php echo $this->souscription->souscription_type; ?></label>
  </div>
  
<div class="control-group">
<label class="control-label" for="souscription_banque">
   Banque : <?php 
        $banque = new Application_Model_EuBanque();
        $banqueM = new Application_Model_EuBanqueMapper();
        $banqueM->find($this->souscription->souscription_banque, $banque);
echo $banque->libelle_banque; ?></label>
</div>

  <div class="control-group">
    <label class="control-label" for="souscription_numero">
      Numero de reçu de banque ou de transation Flooz  : <?php echo $this->souscription->souscription_numero; ?>
    </label>
  </div>

  <div class="control-group">
     <label class="control-label" for="souscription_date_numero">
     Date de reçu de banque ou de transation Flooz : <?php echo $this->souscription->souscription_date_numero; ?> </label>
  </div>

<div class="control-group">
   <label class="control-label" for="souscription_vignette">Scanne du reçu : <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->souscription->souscription_vignette; ?>" target="_blank" class="btn btn-primary">Télécharger le reçu</a>
   </label>
</div>

<div class="control-group">
   <label class="control-label" for="souscription_nombre">
  Nombre de compte marchant souscris : <?php echo $this->souscription->souscription_nombre; ?>
   </label>
</div>

  <div class="control-group">
     <label class="control-label" for="souscription_montant"> 
       Montant de la souscription  
     </label>
     <div class="controls">
       <?php echo $this->souscription->souscription_montant; ?>
     </div>
  </div>

<div class="control-group">
  <label class="control-label" for="souscription_date">
   Date Création : <?php echo $this->souscription->souscription_date; ?></label>
  </div>


</fieldset>







<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








