<div id="view-content" class="ui-widget">
    <div id="c_header" class="ui-widget-header ui-corner-top" style="padding-left: 5px; height: 35px;">
        <h4>Mise à jour de cours</h4>
    </div>
    <div class="ui-widget-content ui-corner-bottom" style="height: 500px;">
        <form id="up_cours_form" method="post" action="/eu-devise/cupdate">
            <table id="tab_cours" style="width: 400px; margin-top: 17px;margin-left: auto; margin-right: auto;">
                <tr>
                    <td><label for="code_dev">Code Devise initiale * :</label></td>
                    <td>
                        <input readonly="true" class="validate[required]" type="text" id="code_dev_init" name="code_dev_init" value="<?php echo $this->cours->code_dev_init; ?>" />
                    </td>
                </tr>
                <tr><td><label for="lib_dev">Code Devise finale*:</label></td>
                    <td>
                        <input readonly="true" class="validate[required]" type="text" id="code_dev_fin" name="code_dev_fin" value="<?php echo $this->cours->code_dev_fin; ?>" />
                    </td>
                </tr>
                <tr>
                    <td><label for="val_dev">Valeur initiale *:</label></td>
                    <td><input class="validate[required number]" type="text" id="val_dev_init" name="val_dev_init" value="<?php echo $this->cours->val_dev_init; ?>"/></td>
                </tr>
                <tr>
                    <td><label for="val_nat">Cours *:</label></td>
                    <td><input class="validate[required number]" type="text" id="val_dev_fin" name="val_dev_fin" value="<?php echo $this->cours->val_dev_fin; ?>"/></td>
                </tr>
                <tr><td></td><td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="Annuler"/></td></tr>
            </table>
        </form>
    </div>
</div>
<script>
    $("#up_cours_form").validationEngine();
    $('#val').button();
    $('#reset').button();
</script>
