<div id="view-content" title="Compensation FGFN" style="font-size: 12px;">
    <div class="ui-widget-content ui-corner-bottom" style="height: 500px;">
        <form id="echange_form" method="Post" action="/compensation/gcpechu">
            <table>
                <tr>
                    <td style="text-align: right;"><label for="compte">Compte :</label></td>
                    <td>
                        <select  id="compte" name="compte" value="<?php echo $this->compte ?>">
                            <option value="GCP">GCP</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: right;"><label for="e_membre">Membre :</label></td>
                    <td><input type="text" size="30" id="e_membre" name="e_membre" value="<?php echo $this->e_membre ?>" required="true"/></td>
                </tr>
                <tr>
                    <td style="text-align: right;"><label for="raison_soc">Raison sociale :</label></td><td><input size="30" type="text" id="raison_soc" name="raison_soc" value="<?php echo $this->raison_soc ?>" readonly="true"/></td>
                </tr>
                <tr>
                    <td style="text-align: right;"><label for="nom_rep">Nom Représentant :</label></td>
                    <td><input size="30" type="text" id="nom_rep" name="nom_rep" value="<?php echo $this->nom_rep ?>" readonly="true"/>
                        <input size="30" type="text" id="prenom_rep" name="prenom_rep" value="<?php echo $this->prenom_rep ?>" readonly="true"/>
                        <button id="afficher" >Afficher</button></td>
                </tr>
                <tr><td colspan="2">
                        <table id="gcp_table"></table>
                        <div id="gcp_div"></div>
                    </td>
                </tr>
                <tr><td style="text-align: right;"><label for="montant">Montant :</label></td>
                    <td><input type="text" style="text-align: right;" id="montant" name="montant" value="<?php echo $this->montant ?>" readonly="true" required="true"/></td></tr>
                <tr><td></td><td><input type="submit" id="val"/><input type="reset" id="reset"/></td></tr>
            </table>
        </form>
    </div>
    <script type="text/javascript">
        $("#gcp_table").jqGrid({
            url: '',
            datatype: "json",
            mtype: 'GET',
            colNames: ['Code', 'Compte', 'Membre', 'Montant', 'Nombre', 'Valeur/P', 'Montant echu', 'Debut', 'Fin', 'Debut tranche', 'Fin tranche '],
            height: 220, width: 800,
            colModel: [
                {name: 'id_compens', index: 'id_compens', sorttype: "int", editable: true, align: "left", hidden: true},
                {name: 'code_compte', index: 'code_compte', width: 160, sorttype: "int", editable: true, align: "left", hidden: true},
                {name: 'code_membre_pbf', index: 'code_membre_pbf', width: 105, editable: true, align: "left"},
                {name: 'mont_compens', index: 'mont_compens', width: 80, align: "right", editable: true},
                {name: 'ntf', index: 'ntf', width: 60, sorttype: "int", editable: true, align: "left"},
                {name: 'mont_tranche', index: 'mont_tranche', width: 100, sorttype: "int", editable: false, align: "left"},
                {name: 'mont_echu', index: 'mont_echu', width: 100, sorttype: "int", editable: false, align: "left"},
                {name: 'date_deb', index: 'date_deb', width: 80, sorttype: "int", editable: false, align: "left", hidden: true},
                {name: 'date_fin', index: 'date_fin', width: 80, sorttype: "int", editable: true, align: "left", hidden: true},
                {name: 'date_deb_tranche', index: 'date_deb_tranche', width: 80, sorttype: "int", editable: false, align: "left", hidden: true},
                {name: 'date_fin_tranche', index: 'date_fin_tranche', width: 80, sorttype: "int", editable: true, align: "left"},
            ],
            rowNum: 10,
            rowList: [10, 20, 30],
            rownumbers: true,
            pager: '#gcp-div',
            sortname: "id_compens",
            multiselect: true,
            viewrecords: true,
            sortorder: "ASC",
            caption: "Liste des GCP disponibles",
            onSelectRow: function(id, status) {
                var montant = $('#montant').val();
                if (id !== 0 || id !== null) {
                    var data = jQuery('#gcp_table').jqGrid('getRowData', id);
                    var value = 0;
                    var tranche = data.mont_echu;
                    if (montant === '') {
                        montant = 0;
                    } else {
                        montant = parseFloat(montant, 10);
                    }
                    if (status === true) {
                        value = parseFloat(montant) + parseFloat(tranche);
                        $('#montant').val(value);
                    } else {
                        value = montant - tranche;
                        $('#montant').val(value);
                    }
                    lastsel = id;
                }
            },
            onSelectAll: function(ids, status) {
                var montant = $('#montant').val();
                if (status) {
                    if (montant === '') {
                        montant = 0;
                    } else {
                        montant = parseFloat(montant, 10);
                    }
                    for (var i = 0; i < ids.length; i++) {
                        var id = ids[i];
                        var data = jQuery('#gcp_table').jqGrid('getRowData', id);
                        var tranche = data.mont_echu;
                        montant = montant + parseFloat(tranche);
                    }
                    $('#montant').val(montant);
                } else {
                    $('#montant').val(0);
                }
            }
        });

        $("#gcp_table").jqGrid('navGrid', '#gcp_div', {edit: true, add: true, del: false, search: true});
        $(document).ready(function()
        {
            $(function() {
                $('#view-content').puipanel();
            });
            $.get("/compensation/membre",
                    function success(data)
                    {
                        $('#e_membre').autocomplete({"source": data});
                    });
                    $('#e_membre').blur(function(e) {
                        $.get("/compensation/recupnom",
                                {num_membre: $(this).val()},
                        function success(data)
                        {
                            if (data !== false) {
                                $("#nom_rep").val(data[0]);
                                $("#prenom_rep").val(data[1]);
                                $("#raison_soc").val(data[2]);
                            } else {
                                $("#id_message").html('Ce membre n\'existe pas !!!');
                            }
                        });
                        e.preventDefault();
                    });
                    $('#afficher').button().click(function(e)
                    {
                        if ($('#e_membre').val() !== '') {
                            jQuery("#gcp_table").jqGrid('setGridParam', {url: "/compensation/gcp?membre=" + $('#e_membre').val()}).trigger('reloadGrid');
                        } else {
                            alert('Il faut entrer un numero de membre');
                        }
                        e.preventDefault();
                    });

                    $('#val').button();
                    $('#reset').button();

                    $('form#echange_form').submit(function(event) {
                        event.preventDefault();
                        var sel = jQuery("#gcp_table").jqGrid('getGridParam', 'selarrrow');
                        $.post('/compensation/echgcp',
                                {
                                    gcp: sel,
                                    compte: $('#compte').val(),
                                    membre: $('#e_membre').val(),
                                    montant: $('#montant').val()
                                }
                        , function(data) {
                            if (data === true) {
                                alert('Opération effectuée avec succes');
                                $(location).attr("href", "/compensation/index");
                            } else {
                                alert(data);
                            }
                        });
                    });
                });
    </script>
</div>
