<style>
 
  article#article_candidature_ot {

    text-align:justify;font-size:1.3em

  }

  h1 {

    text-align:center;
    
  }

  h1{
    
    text-shadow:1px 1px 1px, 0px 2px 2px, 2px 3px 0px; 
    
    margin-top:15px; 
    
    margin-bottom:45px

  }

  h3{
      text-shadow:1px 1px 1px, 0px 2px 2px, 2px 1px 0px
  }

  section {

    margin:10px 0 10px 0

  }

  .search_post_candidature{


  }

  .search_number_poste{

      display:inline-block;

      width:30% 

  }

  #badge_candidat_candidature_ot{

     position:fixed;

     background-color:#000;

     padding:5px;

     z-index:99999999
    
  }

  #selection_candidat_ot_parent{
      
      cursor:pointer;
  }

</style>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" \>

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">

<script type="text/javascript" charset="utf-8">

$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
        "iDisplayLength":10,
		"aaSorting": []
    } );
} );

</script>


<?php

$days = array(
 "1"=>"1","2"=>"2","3"=>"3","4"=>"4","5"=>"5","6"=>"6","7"=>"7","8"=>"8","9"=>"9",
 "10"=>"10","11"=>"11","12"=>"12","13"=>"13","14"=>"14","15"=>"15","16"=>"16","17"=>"17","18"=>"18","19"=>"19","20"=>"20","21"=>"21","22"=>"22","23"=>"23","24"=>"24","25"=>"25","26"=>"26","27"=>"27","28"=>"28","29"=>"29","30"=>"30","31"=>"31");

$years = array("2016"=>"2016","2017"=>"2017","2018"=>"2018","2019"=>"2019","2020"=>"2020","2021"=>"2021","2022"=>"2022","2023"=>"2023","2024"=>"2024","2025"=>"2025","2026"=>"2026","2027"=>"2027","2028"=>"2028","2029"=>"2029","2030"=>"2030","2031"=>"2031","2032"=>"2032","2033"=>"2033","2034"=>"2034","2035"=>"2035","2036"=>"2036","2037"=>"2037","2038"=>"2038","2039"=>"2039","2040"=>"2040");

$months = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');

?>

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>



<article id="article_candidature_ot">

     <h1>APPEL A CANDIDATURE POUR LES OFFREURS DE TRAVAIL (OT) <span id="badge_candidat_candidature_ot"><?php echo $this->countcandidatureselectionner ?> candidats</span></h1>

     <section>

         Dans le cadre de la réalisation des recommandations de l’Organisation des Nations Unies (ONU) en ce qui concerne les attentes de l’article 25 de la Déclaration Universelle des Droits de l’Homme (DUDH) et des 17 Objectifs de Développement Durable (ODD) répondant au PND du Togo et aux défis de l’économie sociale de marché commun, le Groupement d’Intérêt Economique dénommé Economie Sociale de Marché Commun (GIE ESMC), pour la mise en place de son premier centre communal, lance un appel à tout Offreur de Travail (Hauts cadres et assimilés) pouvant exercer en toute autonomie sur sa plateforme.
     
     </section>

     <section>

         L’Offreur de Travail (OT) est un prestataire de services, un auto-entrepreneur, un employé indépendant avec présence physique au poste qui offre du travail, c’est-à-dire qui propose des prestations à la Production Commune sur la plateforme GIE ESMC. Cet OT adhère au GIE ESMC et devient membre, agent de la Production Commune sur la plateforme du GIE.
     
     </section>

     <h3>Connaissances et Aptitudes </h3>

     <section>

        <label class="control-label" for="Diplômes et compétences" style="font-weight:bold">

             Diplômes et compétences :

        </label>
        
         <p>

         <?php echo $this->detailcandidatureforselection[0]->competences ;?>            

         </p>
     
     </section>

     <section>

        <label class="control-label" for="Diplômes et compétences" style="font-weight:bold">

             Nombre d'année d'expérience:

        </label>
        
         <p>

              <?php echo $this->detailcandidatureforselection[0]->annee_experience ?>            

         </p>
     
     </section>


      <ul>
      
          <li>	Bonne aptitude à travailler en équipe et sous pression ; </li>

          <li>	Bonne expression écrite et orale et parfaite connaissance de la langue française ; </li>

          <li>	Parfaite connaissance des langues officielles dans les zones de couverture de la Structure ESMC ;</li>

          <li>	Disposer de son Kit de Solvabilité Universelle (KSU) d’une valeur de soixante-dix mille francs (70.000 F CFA) sur la plateforme du GIE ESMC, pour ses rémunérations.</li>
      
      </ul>

     <h3>Mode de rémunération de l’Offre de Travail </h3>

     <section>
       
     L’Agent OT est rémunéré par Bons de Livraison numérique (BL) ESMC échangeables, au besoin, sous réserve des conditions y afférentes, en monnaie bancaire auprès des Acteurs OBPSD (Offreurs de Biens, Produits et services Dématérialisés) qui sont des banques partenaires du GIE ESMC.
     
     </section>

     <h3>Les différents postes de l’OT</h3>

     <section>
        
     Le personnel communal du groupement est désigné par le terme « Agent » qui, par les présents, ne peuvent être salariés, mais des Prestataires de la Production Commune du GIE ESMC, Acteurs ou Fournisseurs Offreurs de Travail (Travailleurs Indépendants ou Employés Autonomes).
     
     </section>

     <form action="#" method="POST">

         <div class="control-group" style="line-height:2px">

             <div class="controls">

                 <input type="checkbox" id="all-selection-prestaires">

            </div>
	       
             <label class="control-label" for="selection de tous les prestataires" style="font-weight: bold;position: relative;top: -16px;left: 25px;" >
	    
                 Tout selectionner

	         </label>

        </div>

     <table class="table table-striped table-condensed table-hover table-selection-all-prestataire" id="example">

     <thead>

        <tr>

                <th >Cochez</th>    

                 <th>Code membre du candidat</th>

                 <th>Nom & Prénoms du candidat</th>

                 <th>Nom du poste postulé</th>

                 <th>Date du postulat</th>

                 <th>Voir le profil</th>


         </tr>

    </thead>

    <tbody>

         <?php foreach($this->candidatureaselectionner as $key => $value): ?>

           <?php 
             
                 $nom_membre = $value->nom_membre;

                 $prenoms_membre = $value->prenom_membre;

                 $nometprenom_membre = $nom_membre." ".$prenoms_membre;

                 $true_month = "";
                        
                 $ex_date = explode('-',$value->date_postulat);

                    foreach ($months as $ky => $vad) {

                        if($ex_date[1] == $ky){

                            $true_month = $vad;
                         
                        }
                    }

                $next_ex_date = explode(' ', $ex_date[2]);
                
                $true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0]." à ".$next_ex_date[1];

                $code_membre = $value->code_membre;

                $libelle_roles = $value->libelle_roles;

                $tokenkey = "GENERATE TOKEN KEY FOR VALIDATING THE PRESELECTION ACTION BY CODE MEMBRE = '$code_membre' AND FIRSTNAMEWITHLASTNAME = '$nometprenom_membre' FOR THE POST '$libelle_roles'";

           ?>


            <tr id="selection_candidat_ot_parent">

               <td>
                   <?php if ($value->preselection >= 1): ?>

                    <input type="checkbox" id="select_candidat_ot" name="check_select_candidat_ot[]" value="<?php echo $value->id_candidature_membre; ?>" checked="checked"></td>

                   
                  <?php elseif($value->preselection == 0): ?>
               
                         <input type="checkbox" id="select_candidat_ot" name="check_select_candidat_ot[]" value="<?php echo $value->id_candidature_membre; ?>"></td>

                   <?php endif ;?>

                <td><?php echo $code_membre ?></td>

                <td><?php echo $nometprenom_membre ?></td>

                <td><?php echo $libelle_roles ?></td>

                <td><?php echo $true_date ;?></td>

                <td><a href="detaildunappelacandidature/iddetailcandidature/<?php echo $value->id_candidature_membre ?>" class="btn btn-success" data-idcandidaat = "<?php echo $value->id_candidature_membre ;?>">Voir son profil</a></td>

                <input type="hidden" name="id_roles_candidature[]" value="<?php echo $value->id_roles ?>">

                <input type="hidden" name = "id_candidature_membre[]" value="<?php echo $value->id_candidature_membre ?>">

                <input type="hidden" name="id_candidature_post[]" value="<?php echo $value->id_candidature_postes ?>">

                <input type="hidden" name="id_candidature[]" value="<?php echo $value->id_candidature?>">

                <input type="hidden" name ="code_membre[]" value = "<?php echo $value->code_membre ?>">

            </tr>

         <?php endforeach ?>

    </tbody>

</table>

<button class="btn btn-danger" style="position: relative;right: 0;width: 200px;float: right;">

     Valider la préselection
     
</button>

</form>

</article>