<style>
  #prestation_title{
    text-align: center;
    font-size: 2.9em;
    font-weight: lighter;
  }

  #prestation_article_title {
      font-weight: bold;
      text-decoration: underline;
  }

  section>p,li{
      text-align: justify;
      font-size: 18px;
  }

</style>
<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">
	<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

<header id="prestation_title">
Contrat de prestation de services pour la production commune
</header>

<form action="" method="POST">

<section>
<p id="prestation_article_title">Entre les soussignés :</p>
<p>
<strong>L’Entreprise Sociale de Marché Commun (<span style="color:#c30c60">ESMC</span> SARL-U)</strong> dont le siège social est à Lomé, Wuiti-Atchati, angle rue Sagouda, Kiyéou et Bandjéli, immatriculée au Registre du Commerce et du Crédit Mobilier sous le numéro TG-LOM 2018 M 203, représentée par son Gérant, ci-après désigné “l’Entreprise”  d’une part,
</p>

<p>ET</p>


<p>
  <strong>Monsieur/ Madame </strong>
      
  <input type="text" value="<?php echo $this->prestatairesignature[0]->travailleur_libelle ;?>" style="width: 500px;display: inline-block;padding-left: 0;border: 0;background-color: transparent;">
</p>
<p>
Date et lieu de naissance : <input type="date" placeholder="........................." style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">à <input type="text" value="<?php echo $this->prestatairesignature[0]->lieu_nais_membre ;?>" placeholder="........................." style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">
</p>

<p style="display:inline-block">
CIN°: <input type="text" placeholder="......................................" style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">
</p>

<p style="display:inline-block">
délivrée le : <input type="date" data-inputmask="'alias': 'date'" placeholder="......................................" style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">
</p>

<p style="display:inline-block">
expirant le  : <input type="date" data-inputmask="'alias': 'date'" placeholder="......................................" style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">
</p>

<p>
Tél : <input type="text" value="<?php echo $this->prestatairesignature[0]->portable_membre ;?>" placeholder="......................................" style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">
</p>

<p>
Profession: <input type="text" value="<?php echo $this->prestatairesignature[0]->profession_membre ;?>" placeholder="......................................" style="width:200px;display:inline-block;padding-left:0;border:0;background-color:transparent">
</p>

<p>Ci-après désigné “… Fournisseurs, Prestataire de la Production Commune …………………”  </p>
<p>D’autre part,</p>


</section>

<section>
<p><strong>IL A ETE PREALABLEMENT EXPOSE :</strong></p>
<p>L’ESMC, dans le cadre de ses activités sollicite la fourniture de services de Surveillants et d’Exécutants, Prestataires de la Production Commune, Conseillers Membres Fondateurs d’Honneur (CMFH).</p>
<p>C’est dans cette circonstance que <strong>Monsieur/ Madame </strong><input type="text" placeholder="............................................................" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent"> souscrit à la mission de prestations de services, Surveillants et Exécutants, Prestataires de la Production Commune, Conseillers Membres Fondateurs d’Honneur.</p>
</section>

<section>
<p><u><strong>CECI PREALABLEMENT EXPOSE, IL A ETE CONVENU ET ARRETE CE QUI SUIT :</strong></u></p>
<p><strong><u>ARTICLE 1 – OBJET DU CONTRAT</u></strong></p>
<p>Ce présent contrat est régi par la Convention de collaboration entre l’<span style="color:#c30c60">ESMC</span> et les fournisseurs de Biens, Produits et Services : Utilisateurs, Fournisseurs spécifiques et Fournisseurs externes pour la réalisation par le marché des 17 Objectifs de Développement Durable et par l’Engagement de Livraison Irrévocable (ELI) signés par le prestataire avec l’<span style="color:#c30c60">ESMC</span>. </p>

<p>Par le présent contrat, <strong>Monsieur/ Madame </strong><input type="text" value="<?php echo $this->prestatairesignature[0]->travailleur_libelle ;?>" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent">  s’engage à :</p>
<p>
<ul>
  <li>Mobiliser les ressources (à intégrer chaque être humain de sa communauté dans la Production Commune à travers son KIT de Solvabilité Universelle et à mettre sur chaine de valeurs de ladite Production Commune les personnes morales marchandes et non marchandes),  </li>
  <li>Déployer ces ressources (mise en place et opérationnalité de la chaine de valeurs de la Production Commune) et </li>
  <li>Exploiter ces ressources à travers la chaine de valeurs de la Production Commune mise en place et rendue opérationnelle.</li>
</ul>
</p>

<strong>NB:</strong>
<p><i>Les ressources à Mobiliser, à Déployer et à Exploiter sont regroupées par les aspects : espaces, matériels, outils et ressources humaines</i>
Ce sont ces aspects qui, une fois mobilisés, mis en place et rendus opérationnels, constituent la chaine de valeurs de la Production Commune destinée à l’exploitation pour le développement durable dans les communautés de la plateforme <span style="color:#c30c60">ESMC</span>.
</p>
</section>

<section>
<p><strong><u>ARTICLE 2 – DECLARATIONS ET ENGAGEMENTS</u></strong></p>
<p><strong>Monsieur/ Madame </strong><input type="text" value="<?php echo $this->prestatairesignature[0]->travailleur_libelle ;?>" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent">   déclare reconnaître le caractère confidentiel des documents et informations relevant de la propriété exclusive de l’<span style="color:#c30c60">ESMC</span> et s’engage, de ce fait, à respecter les obligations de confidentialité prévues par l’article 3 ci-dessous.</p>
<p> <strong>Monsieur/ Madame </strong><input type="text" value="<?php echo $this->prestatairesignature[0]->travailleur_libelle ;?>" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent"> s’engage à exécuter la mission qui lui est confiée sur le territoire togolais, dans les locaux de l’<span style="color:#c30c60">ESMC</span> et à tout autre endroit selon les besoins de l’<span style="color:#c30c60">ESMC</span>. Il s’engage également à respecter les règles de sécurité applicables au sein de l’<span style="color:#c30c60">ESMC</span>.</p>
</section>

<section>
<p><strong><u>ARTICLE 3- OBLIGATION DE CONFIDENTIALITE</u></strong></p>
<p><strong>Monsieur/ Madame </strong><input type="text" value="<?php echo $this->prestatairesignature[0]->travailleur_libelle ;?>" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent">s’engage pendant toute la durée du présent contrat et même après sa cessation, à tenir comme strictement confidentiels et, par conséquent, sous réserve de la législation en vigueur, à ne pas divulguer à des tiers quels qu’ils soient, directement et/ou indirectement, sous quelque forme que ce soit, l’ensemble des documents et informations dont il a eu connaissance dans le cadre des présentes.</p>
<p>Toute violation des stipulations du présent contrat engagera sa responsabilité personnelle à l’égard de l’ESMC qui se réserve le droit de saisir la juridiction compétente.</p>
</section>

<section>
<p><strong><u>ARTICLE 4 – ENTREE EN VIGUEUR – DUREE </u></strong></p>
<p>Le présent contrat prend effet à compter de la date de signature. Il est conclu pour une période indéterminée.</p>
</section>

<section>
<p><strong><u>ARTICLE 5 – RESILIATION DU CONTRAT </u></strong></p>
<p>La partie qui renonce à ce contrat doit aviser par écrit l’autre partie trente (30) jours avant la fin du contrat.</p>
</section>

<section>
<p><strong><u>ARTICLE 6 – REMUNERATION </u></strong></p>
<p>En contrepartie de la fourniture de sa prestation, <strong>Monsieur/ Madame</strong> <input type="text" value="<?php echo $this->prestatairesignature[0]->travailleur_libelle ;?>" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent"> recevra sur son Compte Marchand  des Bons de Livraison (<strong>BL</strong>) d’un montant de <input type="text" value="Pas encore fixé" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent"> morcelé en  12 périodes de 30 jours ouvrés, chacune, convertible en Ordre de Prélèvement Irrévocable (OPI), Bons d’Achat interne (BAi) et en Bons d’Achat neutre (BAn).</p>
<strong>Des retenues de 5% ou 10% s’il n’a pas un numéro d’identification fiscale seront prélevées sur la valeur des Bons de Livraison  à titre d’impôt sur prestation de service.</strong>
</section>

<section>
<p><strong><u>ARTICLE 7 - LOI APPLICABLE / COMPETENCE DES TRIBUNAUX </u></strong></p>
<p>Le présent contrat est régi par la loi togolaise. Tout différend qui naitrait de l’interprétation ou de l’application du présent contrat sera réglé à l’amiable et à défaut, à la CATO.</p>
<p>Fait en deux (02) exemplaires originaux à Lomé, le <input type="text" placeholder="............................................................" style="width:250px;display:inline-block;padding-left:0;border:0;background-color:transparent"> </p>
</section>
<input type="hidden" name="id_contrat_prestataire" value="<?php echo $this->prestatairesignature[0]->travailleur_id ;?>">

<button>Signer ce contrat</button>

</form>
</div>
</div>
</div>