<div class="span12" style="text-align:text">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

</div>

<style>

.table-bordered {

    border:1px solid #2e2e2e
}

#article_tdr_header {

    font-size:1.4rem;

    font-weight:bold;

    text-align:center;

    margin-bottom:10px;
}

</style>




<article id="article_grille">


<header id="article_tdr_header">

LA GRILLE DES REMUNERATIONS

</header>


<section>

  <p><strong>Pour un Contrat de service à durée limitée – Court terme </strong></p>

  <div style="padding:10px;border:1px solid #2e2e2e;margin-bottom:25px">

      <p><strong>Ce contrat concerne : UNE PERSONNE INDIVIDUELLE </strong></p>

      <p><strong>Prénoms : </strong> <?php echo $this->prenoms_membre_ot ?></p>

      <p><strong>NOM:</strong> <?php echo $this->nom_membre_ot ?></p>
   
      <p><strong>Nationalité : </strong> <?php echo $this->nationality_ot ?> </p>
  
  </div>

</section>

<table class="table table-striped table-bordered table-hover table-condensed">

<div style="text-align:center;font-weight:bold;border:1px solid #2e2e2e">FRAIS STANDARDS DU PRESTATAIRE AGENT OT </div>

<thead>

    <tr>

        <th><strong>NIVEAU D’ETUDE</strong></th>

        <th></th>

        <th>Tranche1 débutant</th>

        <th>Tranche2 junior</th>

        <th>Tranche3 sénior</th>

        <th>Avantages</th>

    </tr>

</thead>

<tbody>

     <tr id="line_selection" >

       <td rowspan="3" style="">Titulaire d’un doctorat ou diplôme équivalent / Directeur Général/Bac +5 (Master)/ Titulaire du diplôme de l’ENA Cycle III ou diplôme équivalent / Titulaire du DESS / Master professionnel / Titulaire du diplôme d’ingénieur / Titulaire d’un BAC + 4 ans de formation professionnelle  ou diplôme équivalent/ Master recherche/ BAC+3 avec  au minimum 20 ans d’expériences professionnelles</td>
   
       <td>CSS-SG/CD-DGA/CP-APGA/CG/CC</td>

       <td></td>

       <td></td>

       <td></td>

       <td></td>

    </tr>

    <tr>
    

        <td>SG /DD/ DS/ DE/ ROSCE-PC/RPPE-PC</td>

        <td>
        
             <span style="display:block"> 984.000 <span style="display:inline-block;color:#62A0E1">BCi</span> </span>

             <span style="display:block"> </span>

        </td>

        <td>
        
             <span style="display:block"> 1.312.000  <span style="display:inline-block;color:#62A0E1">BCi</span> </span>

             <span style="display:block"></span>
        
        </td>

        <td>

             <span style="display:block">2.624.000 <span style="display:inline-block;color:#62A0E1">BCi</span></span>
            
             <span style="display:block"></span>
        
        </td>

        <td></td>

    </tr>

    <tr>
          
       <td>T/ F/A/O/S/ Sous -Regroupement</td>

       <td>836.400 <span style="display:inline-block;color:#62A0E1">BCi</span></td>

       <td>1.115.200 <span style="display:inline-block;color:#62A0E1">BCi</span></td>

       <td>2.230.400 <span style="display:inline-block;color:#62A0E1">BCi</span></td>

       <td></td>

    </tr>

</tbody>


</table>

<p style="font-weight:bold;font-style:italic;text-align:center">NB : Le <span style="display:inline-block;color:#62A0E1">BCi</span> est le prix en CFA de la prestation de l’OT ………………</p>


<p>Le GIE <span style="color:#c30c60">ESMC</span> étant une entreprise de marché, quand bien-même, elle est sociale et commune, les retombées ou produits issus des activités portées par son objet social peuvent être assimilées à des produits imposables au regard de la législation fiscale. En effet, les activités économiques <span style="color:#c30c60">ESMC</span>, porteuses de gains, sont passibles de certains impôts et taxes. </p>


<p><strong>Pour les Acteurs « Offreurs de Travail » (OT) </strong></p>

<p>Les revenus issus des diverses activités de prestations de la « Production Commune » <span style="color:#c30c60">ESMC</span> sont des sommes payées en rémunération des services rendus sur la plateforme et se présentent sous deux formes :</p>

<ul>
    <li>les bénéfices non commerciaux (BNC) et revenus assimilés : entrent dans cette catégorie de revenus les sommes versées aux Acteurs Offreurs de la plateforme (les professions libérales, les produits de droits d’auteurs perçus par les écrivains ou compositeurs, les produits perçus par les inventeurs etc.). Ces sommes doivent faire l’objet de retenue à la source par le prestataire GIE <span style="color:#c30c60">ESMC</span> de : </li>
  
    <li>10% pour les bénéficiaires n’ayant pas un numéro d’identification fiscale, et de</li>

    <li>5% pour les autres bénéficiaires (Article 1186 du CGI). </li>

</ul>

<p>Il est à noter que toutes ces sommes facturées sur la plateforme doivent supporter la TVA (Articles 308 et 310 du CGI).   </p>

</article>