<div class="span12" style="text-align:text">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

</div>

<table class="table table-striped table-condensed table-bordered table-hover">

<div style="text-align:center;font-weight:bold;border:1px solid #2e2e2e">

     TABLEAU D’ILLUSTRATION DE LA MODALITE DE REMUNERATION DE L’OFFRE DE TRAVAIL ET DE LA DEDUCTION D’IMPOTS POUR L’OTR 
     SUR LA PLATEFORME DU GIE ESMC (EN CAS D’ECHANGE AU BESOIN DES BONS DE LIVRAISON EN MONNAIE BANCAIRE)

</div>

  
   <thead>

      <tr>
      
          <th rowspan="3" style="vertical-align:middle">Mensualités</th>

          <th colspan="2" style="text-align:center;padding:10px">Equivalent en monnaie bancaire</th>

          <th colspan="2" style="text-align:center;padding:10px">Montant de la prestation progressive sur 12 mensualités</th>

          <th colspan="4" style="text-align:center;padding:10px">Montant net à payer en monnaie bancaire (après déductions des impôts)</th>

      </tr>

      <tr>

           <th style="text-align:center;vertical-align:middle" rowspan="2">Montant en Euros</th>

           <th style="text-align:center;vertical-align:middle" rowspan="2">Montant en FCFA</th>

           <th style="text-align:center;vertical-align:middle" rowspan="2">Montant en Euros</th>

           <th style="text-align:center;vertical-align:middle" rowspan="2">Montant en FCFA</th>

           <th style="text-align:center" colspan="2">Taux de déductions des impôts -5%</th>

           <th style="text-align:center" colspan="2">Taux de déductions des impôts -10%</th>


      </tr>

      <tr>

           <th style="text-align:center">Montant en Euros</th>

           <th style="text-align:center">Montant en FCFA</th>

           <th style="text-align:center">Montant en Euros</th>

           <th style="text-align:center">Montant en FCFA</th>

      </tr>
   
   </thead>

   <tbody>
   
      <tr>
       
         <td>1er mois</td>

         <td>221,666</td>

         <td>145 413,333</td>
      
         <td>221,666</td>

         <td>145 413,333</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>

      </tr>

      <tr>
      
        <td>2è mois</td>

        <td>221,666</td>

        <td>145 413,333</td>

        <td>443,332</td>

        <td>290 825,792</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>

      </tr>

      <tr>
      
         <td>3è mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>664,998</td>

         <td>436 238,688</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>

      </tr>

      <tr>
      
          <td>4ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>886,664</td>

         <td>581 651,584</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>
   
      <tr>
      
          <td>5ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>1 108,33</td>

         <td>727 064,480</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

      <tr>
      
          <td>6ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>1 329,996</td>

         <td>872 477,376</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

      <tr>
      
          <td>7ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>1 551,662</td>

         <td>1 017 890,272</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

      <tr>
      
          <td>8ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>1773,328</td>

         <td>1 163 303,168</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

     <tr>
      
          <td>9ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>1 994,994</td>

         <td>1 308 716,064</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

     <tr>
      
          <td>10ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>2 216,66</td>

         <td>1 454 128,960</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

      <tr>
      
          <td>11ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>2 438,326</td>

         <td>1 599 541,856</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>

     <tr>
      
          <td>12ème mois</td>

         <td>221,666</td>

         <td>145 413,333</td>

         <td>2 659,992</td>

         <td>1 744 954,752</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
      
      </tr>
   
   </tbody>

</table>

<h2>Acteurs Offreurs de Travail (OT)</h2>

<i>2) Les activités de prestataires de la Production Commune contre OPI
Les revenus issus de ces diverses activités de prestations sont des sommes payées en rémunération des services rendus sur la plateforme et se présentent sous deux formes :
</i>

<ul>
   <i>
    
     <li>Bénéfices non commerciaux (BNC) et revenus assimilés : Entrent dans cette catégorie de revenus les sommes versées aux professions libérales, les produits de droits d’auteurs perçus par les écrivains ou compositeurs, les produits perçus par les inventeurs etc., tous utilisateurs de la plateforme. Ces sommes doivent faire l’objet de retenue à la source par le prestataire de : </li>
     <li>10% pour les bénéficiaires n’ayant pas un numéro d’identification fiscale,</li>
     <li>5% pour les autres bénéficiaires (Article 1186 du CGI).</li>
     
   </i>
</ul>

<p>Il est à noter que toutes ces sommes facturées sur la plateforme doivent supporter la TVA (Articles 308 et 310 du CGI).</p>