<div class="row-fluid">

<blockquote>INTERFACE D'ENVOI DE DOCUMENTS (CURRICULUM VITAE, DIPLOMES)</blockquote>

<?php if (isset($_SESSION["validationerrors"])): ?>

				<div class="alert alert-danger">

					<?php echo implode('<br>', $_SESSION['validationerrors']) ?>

				</div>

			<?php unset($_SESSION['validationerrors']); endif ?>

			<?php if (isset($_SESSION["validationpertesuccess"])): ?>

				<div class="alert alert-success">

					<li><?php echo implode('<br>',$_SESSION['validationpertesuccess']) ?></li>

				</div>

<?php unset($_SESSION['validationpertesuccess']); endif ?>

<form action="#" enctype="multipart/form-data" method="post" class="form-horizontal">

    <div class="control-group" id="piece_existance_justificative">

         <label class="control-label" for="integrateur_description_probleme" style="font-weight:bold">

                Curriculum vitae détaillé et actualisé

		 </label>

		 <div class="controls">

			<input type="file" name="ticket_multiple_upload_file[]" multiple="multiple" style="position:relative">

				 <div class="alert alert-danger">
           <strong>Seul les formats jpg, png et jpeg sont supportés. Vous avez la possibilité de selectionner plusieurs pieces justificatives en même temps:</strong>
				 </div>
			</div>

	</div>

   <blockquote>DIPLOMES SCANNES ET ACTUALISES</blockquote>

   <blockquote>BEPC</blockquote>

	<table class="table table-bordered" id = "tabs_outils">

		<thead>

				<tr>
					
					<th>Document</th>

				</tr>

		</thead>

				   
			<tbody>

				      <tr id="line_file_outils_op">

						 <td>
						     
							  <input  type="file" name="diplome_be" id="outils_fichier" class="input-xxlarge"/>  
							  
						 </td>

					  </tr>

			</tbody>

	</table>

    <blockquote>BAC </blockquote>

    <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de BAC</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de bac</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <blockquote>BTS (Brevet de Technicien Supérieur): BAC + 2</blockquote>

    <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de Formations</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de bac</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <blockquote>LICENCE: BAC + 3</blockquote>

    <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de Formations</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de bac</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <blockquote>MATRISE: BAC + 4</blockquote>

    <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de Formations</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de formation</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <blockquote>MASTER: BAC + 5</blockquote>

        <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de Formations</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de formation</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <blockquote>MASTERE SPECIALISE: BAC + 6</blockquote>

        <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de Formations</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de formation</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <blockquote>DOCTORAT: BAC + 7</blockquote>

            <table class="table table-bordered" id = "tabs_outils">

		<thead>
        
				<tr>
					
					<th>Type de Formations</th>

					<th>Document</th>

				</tr>

		</thead>
				   
		<tbody>
         
			<tr id="line_file_outils_op">

                <td>
              
                     <select class="input-block-level formations_bac_candidature" name="formations_bac_candidature">

                         <option value>Choisir le type de formation</option>

                          <?php foreach($this->allformationbac as $key => $value): ?>

                              <option value="<?php echo $value->id_formations_bac ?>"><?php echo $value->libelle_formations_bac ?></option>

                          <?php endforeach ?>
                   
                   </select>
             
                </td>

				<td>
						     
					<input  type="file" name="detail_outils_fichier[]" id="outils_fichier" class="input-xxlarge"/>  
							  
				</td>

			</tr>

		</tbody>

	</table>

    <div class="control-group" >

          <button type="submit" class="btn btn-large btn-primary" style="position:relative">

          Valider le formulaire

          </button>

    </div>

</form>

</div>