
<style>
 
  article#article_candidature_ot {

    text-align:justify;font-size:1.3em

  }

  h1 {

    text-align:center;
    
  }

  h1{
    
    text-shadow:1px 1px 1px, 0px 2px 2px, 2px 3px 0px; 
    
    margin-top:15px; 
    
    margin-bottom:45px

  }

  h3{
      text-shadow:1px 1px 1px, 0px 2px 2px, 2px 1px 0px;
  }

  section {

    margin:10px 0 10px 0;

  }

  .search_post_candidature{


  }

  .search_number_poste{

      display:inline-block;

      width:30% 

  }

  #candidature_candidat_poste_btn {
    
      position:absolute;

      top:5px;

      right:5px;

      font-weight:bold;

  }

  #candidature_candidat_flag_already {
    
    position: absolute;

    top: 3px;

    right: 5px;

    background-color: #D50A0A;

    font-size: 1rem;

    color: #FFF;

    font-weight: bold;

    padding-left: 5px;

    padding-right: 5px;

    border-radius: 3px;

    -webkit-border-radius:3px;

    -moz-border-radius:3px;

    -ms-border-radius:3px;

    -o-border-radius:3px
  }


</style>


<article id="article_candidature_ot">

     <h1>APPEL A CANDIDATURE POUR LES OFFREURS DE TRAVAIL (OT)</h1>

     <section>

         Dans le cadre de la réalisation des recommandations de l’Organisation des Nations Unies (ONU) en ce qui concerne les attentes de l’article 25 de la Déclaration Universelle des Droits de l’Homme (DUDH) et des 17 Objectifs de Développement Durable (ODD) répondant au PND du Togo et aux défis de l’économie sociale de marché commun, le Groupement d’Intérêt Economique dénommé Economie Sociale de Marché Commun (GIE ESMC), pour la mise en place de son premier centre communal, lance un appel à tout Offreur de Travail (Hauts cadres et assimilés) pouvant exercer en toute autonomie sur sa plateforme.
     
     </section>

     <section>

         L’Offreur de Travail (OT) est un prestataire de services, un auto-entrepreneur, un employé indépendant avec présence physique au poste qui offre du travail, c’est-à-dire qui propose des prestations à la Production Commune sur la plateforme GIE ESMC. Cet OT adhère au GIE ESMC et devient membre, agent de la Production Commune sur la plateforme du GIE.
     
     </section>

     <h3>Connaissances et Aptitudes </h3>

     <section>

        <label class="control-label" for="Diplômes et compétences" style="font-weight:bold">

             Diplômes et compétences :

        </label>
        
         <p>

         <?php echo $this->selectallcandidature[0]->competences ;?>            

         </p>
     
     </section>

     <section>

        <label class="control-label" for="Diplômes et compétences" style="font-weight:bold">

             Nombre d'année d'expérience:

        </label>
        
         <p>

              <?php echo $this->selectallcandidature[0]->annee_experience ?>            

         </p>
     
     </section>


      <ul>
      
          <li>	Bonne aptitude à travailler en équipe et sous pression ; </li>

          <li>	Bonne expression écrite et orale et parfaite connaissance de la langue française ; </li>

          <li>	Parfaite connaissance des langues officielles dans les zones de couverture de la Structure ESMC ;</li>

          <li>	Disposer de son Kit de Solvabilité Universelle (KSU) d’une valeur de soixante-dix mille francs (70.000 F CFA) sur la plateforme du GIE ESMC, pour ses rémunérations.</li>
      
      </ul>

     <h3>Mode de rémunération de l’Offre de Travail </h3>

     <section>
       
     L’Agent OT est rémunéré par Bons de Livraison numérique (BL) ESMC échangeables, au besoin, sous réserve des conditions y afférentes, en monnaie bancaire auprès des Acteurs OBPSD (Offreurs de Biens, Produits et services Dématérialisés) qui sont des banques partenaires du GIE ESMC.
     
     </section>

     <h3>Les différents postes de l’OT</h3>

     <section>
        
     Le personnel communal du groupement est désigné par le terme « Agent » qui, par les présents, ne peuvent être salariés, mais des Prestataires de la Production Commune du GIE ESMC, Acteurs ou Fournisseurs Offreurs de Travail (Travailleurs Indépendants ou Employés Autonomes).
     
     </section>

     <div class="liste_postes_candidature_container" style="clear:both;margin-top:20px;margin-bottom:20px">

       <?php if ($this->countalreadycandidatureposts > 0): ?>

          <?php foreach($this->alreadypostcandidature as $ky => $val): ?>

            <div id="liste_postes_candidature_content" name="poste_candidature_container" style="display:inline-block;position:relative;padding:3px;border-radius:5px;-moz-border-radius:5px;-webkit-border-radius:5px;-o-border-radius:5px;background-color:#35ceb1;width:100%;margin-top:10px;margin-bottom:30px">
                      
                      <div id="libelle_poste_candidature" style="width:90%;">
           
                          <input type="text" value="<?php echo $val->libelle_roles ?>" style="padding: 3px;width: 97%;border: none;background-color: transparent;font-size: 1rem;color:#000">  
           
                          <input type="hidden" value="<?php echo $val->id_roles ?>" id="id_post" name="id_poste_candidature_postulat[]">
                          
                      </div>
           
                      <div id="label_nbre_personne_candidature" style="position: absolute;top: -27px;left: -13px;background-color: #c40707;border-radius: 100px;box-shadow: 2px 0px 9px #000;color: #FFF;font-weight: bold;text-shadow: 0px 1px 1px;width: 34px;height: 34px;line-height: 32px;text-align: center;"> 
                      
                            <input type="text" value="<?php echo $val->nbre_personnes?>" id="nbre_personne_candidature" name="label_nbre_personne_candidature_postulat[]" style="width: 34px;padding: 0;color: #FFF;background-color: transparent;border: 0;line-height: 34px;text-align: center;font-weight: bold;text-shadow: 0px 1px 1px;font-size:1rem">  
                      
                      </div>

                      <span id="candidature_candidat_flag_already">Déja postulé</span>
                                                    
                   </div>

          <?php endforeach ;?>

       <?php endif;?>

       <?php foreach ($this->detaildunecandidaturepourpostuler as $key => $value):?>

        <div id="liste_postes_candidature_content" name="poste_candidature_container" style="display:inline-block;position:relative;padding:3px;border-radius:5px;-moz-border-radius:5px;-webkit-border-radius:5px;-o-border-radius:5px;background-color:#35ceb1;width:100%;margin-top:10px;margin-bottom:30px">
                      
           <div id="libelle_poste_candidature" style="width:90%;">

               <input type="text" value="<?php echo $value->libelle_roles ?>" style="padding: 3px;width: 97%;border: none;background-color: transparent;font-size: 1rem;color:#000">  

               <input type="hidden" value="<?php echo $value->id_roles ?>" id="id_post" name="id_poste_candidature_postulat[]">
               
           </div>

           <div id="label_nbre_personne_candidature" style="position: absolute;top: -27px;left: -13px;background-color: #c40707;border-radius: 100px;box-shadow: 2px 0px 9px #000;color: #FFF;font-weight: bold;text-shadow: 0px 1px 1px;width: 34px;height: 34px;line-height: 32px;text-align: center;"> 
           
                 <input type="text" value="<?php echo $value->nbre_personnes?>" id="nbre_personne_candidature" name="label_nbre_personne_candidature_postulat[]" style="width: 34px;padding: 0;color: #FFF;background-color: transparent;border: 0;line-height: 34px;text-align: center;font-weight: bold;text-shadow: 0px 1px 1px;font-size:1rem">  
           
           </div>

        
          <input type="hidden" value="<?php echo $value->id_candidature_postes ?>" id = "id_candidature_post_ot" name="id_candidature_postulat_poste[]" >

          <a href="#" id="candidature_candidat_poste_btn" class="btn btn-small btn-primary"> Postuler </a>
                   
        </div>

        <?php endforeach ?>
     
        <input type="hidden" value="<?php echo $this->tokencsrf ?>" id="Token-Csrf-ot" name="token_csrf_ot">

        <input type="hidden" value="<?php echo $this->idcandidature ?>" id="id_candidature">

     </div>


</article>

