<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
</script>

<?php
$days = array(
 "1"=>"1","2"=>"2","3"=>"3","4"=>"4","5"=>"5","6"=>"6","7"=>"7","8"=>"8","9"=>"9",
 "10"=>"10","11"=>"11","12"=>"12","13"=>"13","14"=>"14","15"=>"15","16"=>"16","17"=>"17","18"=>"18","19"=>"19","20"=>"20","21"=>"21","22"=>"22","23"=>"23","24"=>"24","25"=>"25","26"=>"26","27"=>"27","28"=>"28","29"=>"29","30"=>"30","31"=>"31");
$years = array("2016"=>"2016","2017"=>"2017","2018"=>"2018","2019"=>"2019","2020"=>"2020","2021"=>"2021","2022"=>"2022","2023"=>"2023","2024"=>"2024","2025"=>"2025","2026"=>"2026","2027"=>"2027","2028"=>"2028","2029"=>"2029","2030"=>"2030","2031"=>"2031","2032"=>"2032","2033"=>"2033","2034"=>"2034","2035"=>"2035","2036"=>"2036","2037"=>"2037","2038"=>"2038","2039"=>"2039","2040"=>"2040");

$months = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
?>

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<?php if ($this->level_validation == "secretaire"): ?>

<blockquote>  Secretariat:Page de validation des contrats des prestaires de la production commune  </blockquote>

<?php endif ?>

<?php if ($this->level_validation == "technopole"): ?>

<blockquote>  Technopole:Page de validation des contrats des prestaires de la production commune   </blockquote>

<?php endif ?>

<?php if ($this->level_validation == "filiere"): ?>

<blockquote>  Filière:Page de selection des prestataires de la production commune  </blockquote>

<?php endif ?>

<?php if ($this->level_validation == "acnev"): ?>

<blockquote>  Acnev:Page de selection des prestataires de la production commune  </blockquote>

<?php endif ?>

<?php if (isset($_SESSION["validationerrors"])): ?>
	<div class="alert alert-danger">
		<?php echo implode('<br>', $_SESSION['validationerrors']) ?>
	</div>
<?php unset($_SESSION['validationerrors']); endif ?>
<?php if (isset($_SESSION["validationsuccess"])): ?>
	<div class="alert alert-success">
		<li><?php echo implode('<br>',$_SESSION['validationsuccess']) ?></li>
	</div>
<?php unset($_SESSION['validationsuccess']); endif ?>

<table class="table table-striped table-condensed table-hover table-selection-all-prestataire" id="example">

<thead>
    <tr>
        <th style="width:202px">Code membre du travail</th>
        <th>Nom du travailleur</th>  
        <th>Lecture du contrat</th>             
        <th>Date du postulat</th>
        <th>Actions</th>
    </tr>
</thead>

<tbody>

<?php foreach ($this->prestatairecontratvalidation as $key => $value): ?>
    <td><?php echo $value->travailleur_code_membre; ?></td>
    <td><?php echo $value->travailleur_libelle; ?></td>
    <td><a href="/gestionoffredetravail/editiondecontratdeprestataireenadministration/id/<?php echo $value->travailleur_id; ?>" class="btn btn-danger" target="_blank">Lire son contrat</a></td>
    <td>
        
        <?php
						$true_month = "";
						$ex_date = explode('-',$value->travailleur_date);

						    foreach ($months as $ky => $vad) {
							    if($ex_date[1] == $ky){
								    $true_month = $vad;
							    }
						    }
						   $next_ex_date = explode(' ', $ex_date[2]);
						   $true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0]." à ".$next_ex_date[1];
		?>
        <?php echo $true_date ;?>
    </td>
    
    <?php if ($this->level_validation == "secretaire"): ?>
    
    <td><a href="#" class="btn btn-primary"  id="btn-sendone-to-another" data-idsento= "<?php echo $value->travailleur_id; ?>" data-sendonetoanother="technopole" data-codemembresento = "<?php echo $value->travailleur_code_membre; ?>" data-libellemembresento = "<?php echo $value->travailleur_libelle; ?>">Envoyer à la technopole</a></td>
    
   <?php endif ?>

    <?php if ($this->level_validation == "technopole"): ?>
    
    <td><a href="#" class="btn btn-danger"  id="btn-sendone-to-another"  data-idsento= "<?php echo $value->travailleur_id; ?>" data-sendonetoanother="filiere" data-codemembresento = "<?php echo $value->travailleur_code_membre; ?>" data-libellemembresento = "<?php echo $value->travailleur_libelle; ?>">Envoyer à la filiere</a></td>
    
   <?php endif ?>

   <?php if ($this->level_validation == "filiere"): ?>
    
    <td><a href="#" class="btn btn-success" id="btn-sendone-to-another"  data-idsento= "<?php echo $value->travailleur_id; ?>" data-sendonetoanother="acnev" data-codemembresento = "<?php echo $value->travailleur_code_membre; ?>" data-libellemembresento = "<?php echo $value->travailleur_libelle; ?>">Envoyer à l'acnev</a></td>
    
   <?php endif ?>

    <?php if ($this->level_validation == "acnev"): ?>
    
    <td><a href="#" class="btn btn-info" id="btn-sendone-to-another"  data-idsento= "<?php echo $value->travailleur_id; ?>" data-sendonetoanother="contractant" data-codemembresento = "<?php echo $value->travailleur_code_membre; ?>" data-libellemembresento = "<?php echo $value->travailleur_libelle; ?>">Envoyer au contractant</a></td>
    
   <?php endif ?>

    
<?php endforeach ?>

</tbody>
</table>