
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
        "iDisplayLength":10,
		"aaSorting": []
    } );
} );
</script>

<style>
   #line_selection:hover{
      cursor:pointer;
   }

   #detail_article_prestataire{

      border: 2px solid #09abab;
      background-color: #02fef4;
      width: 610px;
      padding: 15px;
      font-weight: lighter;
      /*overflow: hidden;*/
      
   }

   #detail_article_prestataire_title_separator{
      border:3px solid #13a2e4
   }

   #detail_article_prestataire_title{
  
   }

   #article_items_prestation_container{
       clear:both;
   }

   #article_items_prestation_container span{
        font-size: 1.6em;
        position: relative;
        width: 481px;
   }

   #article_items_prestation_container label {
    display: inline-block;
    color: #087271;
    font-size: 1.4em;
   }

   #swipe_selection_prestataire{
       overflow: hidden;
       position: relative;
   }

   #table-selection-all-prestataire_container_left{
    position: relative;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    transform: translate3d(-67%,0,0);
    transition-duration: 0.4s;
    
    }
    #table-selection-all-prestataire_container{
       transition-duration: 0.4s;
        
    }

    #detail_article_prestataire {
        position: absolute;
        top: 103px;
        transform: translate3d(182%,0,0);
        transition-duration: 0.4s;
        
    }

    #detail_article_prestataire_right {
        display:block;
        border: 2px solid #09abab;
        background-color: #02fef4;
        width: 610px;
        padding: 15px;
        font-weight: lighter;
        position: absolute;
        top: 103px;

        transform: translate3d(51%,0,0);
        -ms-transform: translate3d(51%,0,0);
        -o-transform: translate3d(51%,0,0);
        -moz-transform: translate3d(51%,0,0);
        -webkit-transform: translate3d(51%,0,0);
        
        transition-duration: 0.4s;
        -o-transition-duration: 0.4s;
        -ms-transition-duration: 0.4s;
        -moz-transition-duration: 0.4s;
        -webkit-transition-duration: 0.4s;
        
        
        box-shadow: 3px 3px 9px;
        -moz-box-shadow: 3px 3px 9px;
        -o-box-shadow: 3px 3px 9px;
        -ms-box-shadow: 3px 3px 9px;
        -webkit-box-shadow: 3px 3px 9px;
        
        
        background: linear-gradient(#03ffe4, #07bfa5);
    }

    #detail_article_prestataire_title_close{
        display: block;
        width: 35px;
        height: 35px;

        border-radius: 100%;
        -webkit-border-radius: 100%;
        -moz-border-radius: 100%;
        -ms-border-radius: 100%;
        -o-border-radius: 100%;
        
        background-color: #067a93;
        color: #FFF;
        line-height: 29px;
        text-align: center;
        font-weight: lighter;
        position: absolute;
        top: -15px;
        right: -10px;
        cursor:pointer;
        font-size: 36px;
    }

    


</style>


<?php
$days = array(
 "1"=>"1","2"=>"2","3"=>"3","4"=>"4","5"=>"5","6"=>"6","7"=>"7","8"=>"8","9"=>"9",
 "10"=>"10","11"=>"11","12"=>"12","13"=>"13","14"=>"14","15"=>"15","16"=>"16","17"=>"17","18"=>"18","19"=>"19","20"=>"20","21"=>"21","22"=>"22","23"=>"23","24"=>"24","25"=>"25","26"=>"26","27"=>"27","28"=>"28","29"=>"29","30"=>"30","31"=>"31");
$years = array("2016"=>"2016","2017"=>"2017","2018"=>"2018","2019"=>"2019","2020"=>"2020","2021"=>"2021","2022"=>"2022","2023"=>"2023","2024"=>"2024","2025"=>"2025","2026"=>"2026","2027"=>"2027","2028"=>"2028","2029"=>"2029","2030"=>"2030","2031"=>"2031","2032"=>"2032","2033"=>"2033","2034"=>"2034","2035"=>"2035","2036"=>"2036","2037"=>"2037","2038"=>"2038","2039"=>"2039","2040"=>"2040");

$months = array('01'=>'Janvier','02'=>'Fevrier','03'=>'Mars','04'=>'Avril','05'=>'Mai','06'=>'Juin','07'=>'Juillet','08'=>'Aout','09'=>'Septembre','10'=>'Octobre','11'=>'Novembre','12'=>'Decembre');
?>

<article id="swipe_selection_prestataire">
<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>
<?php echo $this->idisplay_lenth;?>
<?php echo $this->display_lenth;?>


<blockquote>  Page de selection des prestataires de la production commune  </blockquote>

<?php if (isset($_SESSION["validationerrors"])): ?>
	<div class="alert alert-danger">
		<?php echo implode('<br>', $_SESSION['validationerrors']) ?>
	</div>
<?php unset($_SESSION['validationerrors']); endif ?>
<?php if (isset($_SESSION["validationpertesuccess"])): ?>
	<div class="alert alert-success">
		<strong><?php echo implode('<br>',$_SESSION['validationpertesuccess']) ?></strong>
	</div>
<?php unset($_SESSION['validationpertesuccess']); endif ?>

<section id="table-selection-all-prestataire_container">


<form action="#" method="POST">


<button class="btn btn-danger" style="position: relative;right: 0;width: 200px;float: right;">Valider la selection</button>
<div class="control-group" style="line-height:2px">
<div class="controls">
           <input type="checkbox" id="all-selection-prestaires">
            </div>
	       <label class="control-label" for="selection de tous les prestataires" style="font-weight: bold;position: relative;top: -16px;left: 25px;" >
	         Tout selectionner
	       </label>

</div>


<table class="table table-striped table-condensed table-hover table-selection-all-prestataire" id="example">

<thead>
    <tr>
        <th style="width:64px">Cocher</th>    
        <th style="width:202px">Code membre du travail</th>
        <th>Nom du travailleur</th>        
        <th>Date du postulat</th>
        <th>Actions</th>
    </tr>
</thead>

<tbody>
<?php foreach ($this->prestatairelist as $key => $value): ?>

    <tr id="line_selection">
    
        <td><input type="checkbox" id="one_selection_prestataire" name="check_one_selection_prestataire[]" value="<?php echo $value->travailleur_id; ?>"></td>
        <td><?php echo $value->travailleur_code_membre; ?></td>
        <td><?php echo $value->travailleur_libelle; ?></td>
        
        <td>
        
        <?php
						$true_month = "";
						$ex_date = explode('-',$value->travailleur_date);

						    foreach ($months as $ky => $vad) {
							    if($ex_date[1] == $ky){
								    $true_month = $vad;
							    }
						    }
						   $next_ex_date = explode(' ', $ex_date[2]);
						   $true_date = $next_ex_date[0]." ".$true_month." ".$ex_date[0]." à ".$next_ex_date[1];
		?>
        <?php echo $true_date ;?>
        </td>
        <td><a href="#" class="btn btn-primary" id="btn-view-detail" data-idprestataire = "<?php echo $value->travailleur_id ;?>">Voir les détails</a></td>        
    </tr>
<?php endforeach ?>
</tbody>
</table>
</form>


</section>


<section id="detail_article_prestataire">  
<span id="detail_article_prestataire_title_close">x</span>
<span id="detail_article_prestataire_content"></span>
  
   </article>
   </section>

</article>
