<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<script src="<?php echo $this->baseUrl();?>/procuration.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf-8">
		
  $(document).ready(function() {
    $('#example').dataTable({
       "sPaginationType": "full_numbers",
       "aaSorting":[]
    });
  });
  
</script>
        
<script type="text/javascript">

function checkAllInput(form,action) {
   var i = document.forms[form].getElementsByTagName("input"); 
   for(var cpt = 0; cpt < i.length; cpt++) { 
      i[cpt].checked = (action)? true : false ;
   }
}

</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p> Liste des Procurations  </p></blockquote>
  
  <?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
    </div>
  <?php } ?>
  
<?php 

if(count($this->entries) > 0)  { 
?> 


<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
	   <thead>
			  <tr>
				  <th>Date</th>
				  <th>Code membre mandant</th>
				  <th>Membre mandant</th>
				  <th>Code membre mandataire</th>
				  <th>Membre mandataire</th>
				  <th>Action</th>				  
			  </tr>
	   </thead>
<tbody>
<?php 
foreach($this->entries as $entry):
   $membremorale = new Application_Model_EuMembreMorale();
   $m_membremorale = new Application_Model_EuMembreMoraleMapper();

   $membre = new Application_Model_EuMembre();
   $m_membre = new Application_Model_EuMembreMapper();
   
   $nom = "";
   $nommandataire = "";
   
   $membremandataire = new Application_Model_EuMembre();
   $m_membremandataire = new Application_Model_EuMembreMapper();

   if(substr($entry->code_membre_mandant,19,1) == 'M') {
     $m_membremorale->find($entry->code_membre_mandant,$membremorale);
	 $nom = $membremorale->raison_sociale;
   } else {
	 $m_membre->find($entry->code_membre_mandant,$membre);
     $nom = $membre->nom_membre." ".$membre->prenom_membre;	 
   }
   $m_membremandataire->find($entry->code_membre_mandataire,$membremandataire);
   $nommandataire = $membremandataire->nom_membre." ".$membremandataire->prenom_membre;
   
?>
<tr>
    <td> <?php echo datejourfr($entry->date_procuration); ?> </td>
    <td> <?php echo($entry->code_membre_mandant); ?></td>
    <td> <?php echo($nom); ?></td>
	<td> <?php echo($entry->code_membre_mandataire); ?></td>
    <td> <?php echo($nommandataire);?></td>
    <td>
	   <div id="nivo<?php echo $entry->id_procuration; ?>">
	        <?php if($entry->activer == 1) { ?>
            <a class="btn btn-mini btn-warning" onclick="ouvre_procuration('<?php echo $entry->id_procuration; ?>_0', 'nivo<?php echo $entry->id_procuration; ?>');"><i class="icon-off icon-white"></i>Désactiver</a>&nbsp;
            <?php } else { ?>
            <a class="btn btn-mini btn-success" onclick="ouvre_procuration('<?php echo $entry->id_procuration; ?>_1', 'nivo<?php echo $entry->id_procuration; ?>');"><i class="icon-ok icon-white"></i>Activer</a>&nbsp;
            <?php } ?>
	    </div>
	</td>
</tr>
<?php 
endforeach; 
?>
</tbody>
</table>

<?php } else { ?>
<div class="alert alert-info">
  Aucune Procuration enregistrée 
</div>
<?php } ?>

</div>

</div>
</div>








