<div id="view-content">
    <div style="width:800px; font-family:Gill, Helvetica, sans-serif">
        <form action="/eu-html2-pdf-contrat/licence" name="" method="POST" target="_blank">
            <input id="apercu" type="submit" value="Aperçu" class="ui-widget button"/>
            <input type="hidden" name="membre" id="membre"/>
        </form>    
    </div>
    <table id="tbl-placement"></table>
    <div id="pg-placement"></div>
</div>

<script type="text/javascript">
    $("#tbl-placement").jqGrid({
        url: '/eu-carte/licenses',
        datatype: "json",
        mtype: 'GET',
        colNames: ['ID', 'Date', 'Membre', 'Libellé', 'Montant', 'type d\'opérations'],
        height: 500, width: 827,
        colModel: [
            {name: 'id_operation', index: 'id_operation', width: 60, align: "left", editable: false, hidden: true},
            {name: 'date_op', index: 'date_op', width: 100, align: "left", editable: true},
            {name: 'code_membre', index: 'code_membre', width: 190, align: "left", editable: true},
            {name: 'lib_op', index: 'lib_op', width: 250, align: "left", editable: true},
            {name: 'montant_op', index: 'montant_op', width: 140, editable: true, align: "right"},
            {name: 'type_op', index: 'type_op', width: 170, editable: true, align: "left"}
        ],
        rowNum: 20,
        rowList: [20, 30, 40],
        pager: '#pg-placement',
        sortname: "id_operation",
        viewrecords: true,
        sortorder: "ASC",
        caption: "Frais de licences"
    });
    $("#tbl-placement").jqGrid('navGrid', '#pg-placement', {edit: false, add: false, del: false, search: true});

    $("#apercu").click(function() {
        var sel;
        sel = jQuery("#tbl-placement").jqGrid('getGridParam', 'selrow');
        data = jQuery("#tbl-placement").jqGrid('getRowData', sel);
        $('#membre').val(data.code_membre);

    });
    $("#apercu").button();

</script>