<div id="view-content" style="font-size: 12px;min-height: 520px;" title="Creation des comptes pour les membres personnes morales">
     <form id="compte_form" method="Post" action="/eu-carte/donewcompte">
           <table style="margin-left:auto;margin-right: auto;margin-top: 10px;" id="tab_compte">
               <tbody>
			        <tr>
                    <td colspan="2">
                        <fieldset>
                            <table>
                                <tbody>
                                    <tr><td>Code Membre    : </td> <td><input id="code_membre" type="text" name="code_membre" value="" required="true" style="width: 170px;"/></td></tr>
                                    <tr><td>Raison sociale : </td><td><input id="raison_membre" type="text" name="raison_membre_fl" value="" style="width: 200px;" readonly="readonly"/></td></tr>
                                </tbody>
                            </table>
                        </fieldset>
                    </td> 
                </tr>
				<tr>
                    <td></td>
                    <td><input type="submit" id="val" value="Valider"/><input type="reset" id="reset" value="Annuler"/></td>
                </tr>
			   </tbody>
			   </table>
     </form>
</div>
<script>
    $(document).ready(function() {
    $('#val').button();
    $('#reset').button();
    $(function() {
       $('#view-content').puipanel();
       $('fieldset').puifieldset();
       $("#compte_form").validationEngine();
    });
	
	 $('form#compte_form').submit(function(event) {
            event.preventDefault();
            $.post('/eu-carte/donewcompte',{
			  code_membre : $('#code_membre').val(),                 
            }
            , function success(data) {
                if (data === true) {
                    alert('Operation effectuee avec succes');
                    $(location).attr("href", "/eu-carte/listelicence");
                } else {
                    alert(data);
                }
            });
        });
	
	$.get("/eu-carte/membrem",
      function success(data) {
      $("#code_membre").autocomplete({minLength: 5, "source": data});
    });
	$('#code_membre').blur(function(e)
        {
            if ($(this).val() !== '')
            {
                $.get(
                        '/eu-carte/recupraison',
                        {
                            num_membre: $(this).val()
                        },
                function success(data)
                {
                    if (data !== '') {
                        $("#raison_membre").val(data[1]);
                    } else {
                        alert('Ce membre n\existe pas!!!');
                    }
                });
            }
            e.preventDefault();
        });
	
	
	
		
	 });		
</script>