<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
 $('#example').dataTable( {
    "sPaginationType": "full_numbers",
    "aaSorting": []
 });
});
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<blockquote><p>Liste des appareils mobiles </p></blockquote>
<?php if(isset($sessionutilisateur->error) && $sessionutilisateur->error!="") { ?>
   <div class="alert alert-error">
   <button type="button" class="close" data-dismiss="alert">&times;</button>
   <?php echo $sessionutilisateur->error; $sessionutilisateur->error = ""; ?>
   </div>
<?php } ?>
			
<?php if(isset($this->error) && $this->error!="") { ?>
   <div class="alert alert-error">
   <button type="button" class="close" data-dismiss="alert">&times;</button>
   <?php echo $this->error; ?>
   </div>
<?php } ?>

<?php if(count($this->entries) > 0) { ?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
<thead>
	<tr>
		<th>Code Membre Propriétaire</th>
		<th>Propriétaire</th>
	    <th>Nom Appareil</th>
		<th>Marque Appareil</th>
		<th>Modèle Appareil</th>
		<th>Actions</th>
	</tr>
</thead>
						  
<tbody>
<?php 
foreach($this->entries as $entry):
   $proprietaire = "";
   if(substr($entry->code_membre,19,1) == 'P')  {
	  $membreM = new Application_Model_EuMembreMapper();
      $membre = new Application_Model_EuMembre();
      $membreM->find($entry->code_membre,$membre);
	  $proprietaire = $membre->nom_membre." ".$membre->prenom_membre;
   } else if(substr($entry->code_membre,19,1) == 'M') {
	  $membreM = new Application_Model_EuMembreMoraleMapper();
      $membre = new Application_Model_EuMembreMorale();
      $membreM->find($entry->code_membre,$membre);
      $proprietaire = $membre->raison_sociale;	  
   } 

?>

<tr>
      <td><?php echo ($entry->code_membre); ?></td>
	  <td><?php echo ($proprietaire); ?></td>
      <td><?php echo ($entry->nom_appareil); ?></td>
	  <td><?php echo ($entry->marque_appareil); ?></td>
	  <td><?php echo ($entry->modele_appareil); ?></td>
	  
      <td>
	    <div align="center">
          <?php if($entry->lock_status == 2) { ?>
		  <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/representation/editstatus/id/<?php echo $entry->id; ?>/publier/1"> <i class="icon-ok icon-white"></i>Activer</a>&nbsp;
          <?php } else if($entry->lock_status == 1) { ?>
          <a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/representation/editstatus/id/<?php echo $entry->id; ?>/publier/2"><i class="icon-off icon-white"></i>Désactiver</a>&nbsp;
          <?php } ?>
        </div>
	   </td>
      
    </tr>
<?php endforeach; ?>
</tbody>
</table>
<?php } else { ?>
<div class="alert alert-info">
  Aucun appareil enrégistré 
</div>
<?php } ?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








