<?php $sessionutilisateur = new Zend_Session_Namespace('utilisateur');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

  <blockquote><p>Liste des travailleurs</p></blockquote>
<?php //echo $sessionutilisateur->id_canton;?> 
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Nom et prénom(s)</th>
								  <th>Type</th>
								  <th>Niveau scolaire</th>
								  <!--<th>Formation</th>
								  <th>Education </th>-->
								  <th>Adresse</th>
								  <th>Canton</th>
								  <th>Code Membre</th>
								  <th>Observation</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo $entry->travailleur_date; ?></td>
      <td><?php echo $entry->travailleur_libelle; ?></td>
      <td><?php echo $entry->travailleur_type; ?></td>
      <td><?php echo $entry->travailleur_niveau; ?></td>
      <!--<td><?php echo $entry->travailleur_formation; ?></td>
      <td><?php echo $entry->travailleur_education; ?></td>-->
      <td><?php echo $entry->travailleur_adresse; ?></td>
<?php 
        $canton = new Application_Model_EuCanton();
        $cantonM = new Application_Model_EuCantonMapper();
        $cantonM->find($entry->id_canton, $canton);
?>
      <td><?php echo $canton->nom_canton; ?></td>
      <td><?php echo $entry->travailleur_code_membre; ?></td>
      <td><?php echo $entry->travailleur_observation; ?></td>
      <td><div align="center">
<?php if($entry->publier == 2){?>
			<a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/travailleur/publiertravailleuradmin/id/<?php echo $entry->travailleur_id; ?>/publier/1"><i class="icon-ok icon-white"></i>  Activé</a>&nbsp;
<?php }else{?>
			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/travailleur/publiertravailleuradmin/id/<?php echo $entry->travailleur_id; ?>/publier/2"><i class="icon-off icon-white"></i>  Désactivé</a>&nbsp;
<?php }?>

			<a class="btn btn-mini btn-info" href="<?php echo $this->baseUrl(); ?>/travailleur/detailtravailleuradmin/id/<?php echo $entry->travailleur_id; ?>"><i class="icon-edit icon-white"></i>  Details</a>&nbsp;

			<a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/travailleur/edittravailleuradmin/id/<?php echo $entry->travailleur_id; ?>"><i class="icon-edit icon-white"></i>  Modifier</a>&nbsp;

			<a class="btn btn-mini" href="<?php echo $this->baseUrl(); ?>/travailleur/listdetailtravailleuradmin/id/<?php echo $entry->travailleur_id; ?>"><i class="icon-edit icon-white"></i>  Fichiers</a>&nbsp;
			</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun travailleur  enregistré 
</div>
<?php }?>




<?php /*?></div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?><?php */?>
</div>
</div>
</div>








