<div id="view-content" title="<?php echo $this->type; ?>" style="font-size: 11px;min-height: 520px;">
    <form id="bnp_cacb" method="post" action="/eu-bnp/traiterbnp">
        <table style="width: 800px;" align="center">
		    <tbody>
		        <tr>	
			        <td colspan="2">
					    <fieldset id="cacb_field">
						    <legend>Type</legend>
						    <table align="left">
                                <tbody>
                                    <tr>
									    <td><label style="text-align: right;" for="bnp_type">Type BNP *</label></td>
                                        <td><input type="text" id="bnp_type" name="bnp_type" readonly="true" value="<?php echo $this->type; ?>"/></td>
									    <td><label>Mode de financement *</label></td>
                                        <td>
                                            <select id="mode_finance" name="mode_finance">
						<?php  if($this->type == 'CACB') {    ?>
                                                    <option value="N">Numéraire</option>
                                                    <option value="GCP">GCP PBF</option>
						<?php } else { ?>
						                        <option value="N">Numéraire</option>
						                        <?php } ?>
                                            </select>
                                        </td>
									
						            </tr> 
                                </tbody>
                            </table>
					    </fieldset>
					</td>
		        </tr>
				<tr>
                    <td colspan="2">
                        <fieldset id="cat_field">
                                <legend>CATEGORIE BNP</legend>
                                <table>
                                       <tbody>
                                            <tr>
                                                <td><input type="radio" id="cat_bnp" name="cat_bnp" value="bnps" required="true" checked="checked" ></td><td><label>BNP STANDARD</label></td>
						<td width="260px"></td>
						<td><input type="radio" id="cat_bnp" name="cat_bnp" value="bnpp" required="true"></td><td>BNP PERENNE</td>
                                            </tr>
                                       </tbody>
                                </table>

                        </fieldset>
                    </td>
               </tr>
				<tr>
				    <td colspan="2">
                        <fieldset id="benef_cacb">
                            <legend>Bénéficiaire</legend>
							<table align="left">
							    <tbody>
								    <tr>
								        <td><label>Type Membre*</label></td>
				                        <td>
					                        <select id="type_membre" type="text" name="type_membre" required="true"/>
					                            <option value=""></option>
                                                <option value="P">Physique</option>
                                                <option value="M">Morale</option>
					                        </select>	  
					                    </td>
										<td><label>N° Membre *</label></td>
										<td><input class="validate[required]" size="25" name="code_membre_benef" id="code_membre_benef"  value="<?php echo $this->code_membre_benef ?>" readonly /></td>
									    <td><label>Désignation membre *</label></td>
										<td><input class="validate[required]" size="25" name="nom_membre" id="nom_membre"  value="<?php echo $this->nom_membre ?>"/></td>
									</tr>
							    </tbody>
							</table>
				        </fieldset>	
					</td>	       
				</tr>
				<tr>
				    <td colspan="2">
                        <fieldset id="benef_cacb">
                            <legend>BNP</legend>
							<table>
							    <tr>
								    <td><label>Produit BNP *</label></td>
									<td>
									    <select id="bnp_produit" name="bnp_produit" value="" required="true">
										    <?php if ($this->type == 'CSCOE') { ?>
                                                <option value=""></option>
                                                <option value="I">Investissement</option>
                                            <?php } else { ?>
                                                <option value=""></option>
                                                <option value="I">Investissement</option>
                                                <option value="RPG">RPG</option>
                                            <?php } ?>
										</select>
									</td>
                                    <td><label style="text-align:right;">Catégorie *</label></td>
                                    <td>
                                        <select id="bnp_compte" name="bnp_compte" required="true">
                                           <option value="r">Récurrent</option>
                                        </select>
                                    </td>									
							    </tr>
								<tr>
								    <td colspan="4" height="15px"></td>
								</tr>
								<tr>
								    <td><label>Code SMS *</label></td>
									<td><input size="16" id="code_sms" name="code_sms" required="true" /></td>
									<td><label >Montant BNP *</label></td>
                                    <td>
                                       <input size="16" class="validate[required number]" type="text" id="mont_capa" name="mont_capa" value="<?php echo $this->mont_capa; ?>" readonly />
                                       <select class="validate[required]" type="text" id="dev_capa" name="dev_capa" value=""></select>
									</td>									
								</tr>
								<tr>
								    <td colspan="4" height="15px"></td>
								</tr>
								<tr>
								    <td><label>Montant Bon Consommation BNP *</label></td>
									<td><input size="16" class="validate[required]" type="text" id="mont_credit" name="mont_credit" value="<?php echo $this->mont_credit; ?>" readonly /> </td>
								    <td><label>Montant Usufruitier *</label></td>
									<td><input size="16" class="validate[required]" type="text" id="part_usu" name="part_usu" value="<?php echo $this->part_usu; ?>" readonly /> </td>
								</tr>
							</table>
				        </fieldset>
					</td>	       
				</tr>
				<tr>
                    <td>
                        <fieldset>
                            <table align="center">
                                <tr>
                                    <td colspan="2">
                                        <input id="bt_valider" type="submit" value="Valider"/>
                                        <input id="bt_reset"   type="reset"    value="Annuler"/>
                                    </td>
                                </tr>
                            </table>
                        </fieldset>
                    </td>
                </tr>	
		    </tbody>
		</table> 
    </form>
	<div id="pdialog">
	    <table>
	        <tbody>
			    <tr>
                    <td><label>Mode Financement :</label></td>
                    <td><input type="text" id="finance_mode" name="finance_mode" readonly="true" size="10"/></td>
                </tr>
			    <tr>
                    <td><label>Type BNP :</label></td>
                    <td><input type="text" id="type_bnp" name="type_bnp" readonly="true" size="10"/></td>
                </tr>
			    <tr>
                    <td><label>N° Membre Bénéficiaire :</label></td>
                    <td><input type="text" id="membre_code" name="membre_code" readonly="true" size="26"/></td>
                </tr>
                <tr>
                    <td><label>Désignation membre :</label></td>
                    <td><input type="text" size="30" id="membre_nom" name="membre_nom" readonly="true"/></td>
                </tr>
				<tr>
                    <td><label>Produit BNP :</label></td>
                    <td><input type="text" id="produit_bnp" name="produit_bnp" readonly="true"/></td>
                </tr>
				<tr>
                    <td><label>Catégorie Produit BNP :</label></td>
                    <td><input type="text" id="compte_bnp" name="compte_bnp" readonly="true"/>
					
                </tr>
				<tr>
                    <td><label>Code SMS :</label></td>
                    <td><input type="text" id="sms_code" name="sms_code" readonly="true"/></td>
                </tr>
                <tr>
                    <td><label>Montant BNP :</label></td>
                    <td>
					    <input size="20" type="text" id="capa_mont" name="capa_mont" readonly="true"/>
					    <input type="text" id="capa_dev" name="capa_dev" readonly="true" size="3" /></td>
					</td>
                </tr>
                <tr>
                    <td><label>Montant Bon consommation :</label></td>
                    <td><input type="text" size="20" id="credit_mont" name="credit_mont" readonly="true"/></td>
                </tr>
                <tr>
                    <td><label>Part Usufruitier :</label></td>
                    <td><input type="text" id="conus" name="conus" readonly="true"/></td>
                </tr>
			</tbody>
	    </table>
	</div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(function() {
            $('#view-content').puipanel();
            $('fieldset').puifieldset();
		    $.get('/eu-bnp/devise',function success(data) {
                var options = '';
                for (var i = 0; i < data.length; i++) {
                    if (data[i] === 'XOF') {
                        options += '<option value="' + data[i] + '" selected>' + data[i] + ' </option>';
                    } else {
                        options += '<option value="' + data[i] + '">' + data[i] + ' </option>';
                    }
                }
                $('select#dev_capa').html(options);
            });
			
			$("#pdialog").dialog({
				autoOpen: false,
                height: 450,
                width: 550,
                title: 'Confirmez-vous cette opération ?',
                modal: true,
				buttons: {
				    "OUI": function() {
					    $.post('/eu-bnp/traiterbnp', {
                          mode_finance      : $('#mode_finance').val(),
                          bnp_type          : $('#bnp_type').val(),
					      cat_bnp           : $('#cat_bnp').val(),
                          code_membre_benef : $('#code_membre_benef').val(),
                          bnp_produit       : $('#bnp_produit').val(),
                          bnp_compte        : $('#bnp_compte').val(),
                          code_sms          : $('#code_sms').val(),
                          mont_capa         : $('#mont_capa').val(),
						  dev_capa          : $('#dev_capa').val(),
						  mont_credit       : $('#mont_credit').val(),
						  part_usu          : $('#part_usu').val()
                        },
                        function success(data) {
                            if (data === true) {
                                alert('Opération effectuée avec succes');
                                $(location).attr("href", "/eu-bnp/index");
                            } else {
                                $('#message').html(data);
                            }
                        });
                        $(this).dialog("close");       
					},
                    "NON":function() {
					  $('#bnp_type').val($('#type_bnp').val());
                      $(this).dialog("close");
                    }
			    },
				close: function() {
				
                }
			});
			
			
			$("#bt_valider").button().click(function(e) {
			    e.preventDefault();
				
				if($('#code_membre_benef').val() == '' || $('#code_sms').val() == '' || $('#bnp_produit').val() == '') {
				    alert('Veuillez renseigner les champs obligatoires');
				} 				
				else {
			       $('#type_bnp').val($('#bnp_type').val());
			       if ($('#mode_finance').val() === 'N') {
                   $('#finance_mode').val('Numéraire');
                } else {
                   $('#finance_mode').val('GCP PBF');
                }
				$('#membre_code').val($('#code_membre_benef').val()); 
                $('#membre_nom').val($('#nom_membre').val());
				$('#produit_bnp').val($('#bnp_produit').val());
                if ($('#bnp_compte').val() === 'r') {
                  $('#compte_bnp').val('Récurrent');
                } else {
                  $('#compte_bnp').val('Non Récurrent');
                }
                $('#sms_code').val($('#code_sms').val());
                $('#capa_mont').val($('#mont_capa').val());
				$('#capa_dev').val($('#dev_capa').val());
				$('#credit_mont').val($('#mont_credit').val());
				$('#conus').val($('#part_usu').val());
			    $("#pdialog").dialog("open");
				}
			
			});
			
			
			
            $("#type_membre").change(function(e) {
		        if ($(this).val() != '') {
		           $('#code_membre_benef').attr('readonly',false);
			       $('#code_membre_benef').val('');
			       $('#nom_membre').val('');
			       $.get("/eu-bnp/membreapporteur",{
                    type_membre : $('#type_membre').val()
                },
                function success(data) {
                   $("#code_membre_benef").autocomplete({"source": data});
                }); 
		    } else {
		        $('#code_membre_benef').attr('readonly',true);
				$('#code_membre_benef').val('');
                $('#nom_membre').val('');				
		    }
		    });
              
			$('#code_membre_benef').blur(function(e) {
            e.preventDefault();
            var membre = $(this).val();
            if ($(this).val() !== '') {
                $.get('/eu-bnp/recupnom',{num_membre: $(this).val() },
                function success(data) {
                    if (membre.slice(-1) === 'M') {
                        $("#nom_membre").val(data[1]);
                    } else {
                        $("#nom_membre").val(data[1]);
                    }
                });
            }
        });

        $('#code_sms').blur(function(e) {
            if ($(this).val() !== '') {
                $.get(
                    '/eu-bnp/codesms', {code: $(this).val(), cat: $('#bnp_compte').val() , type_bnp: $('#bnp_type').val()},
                function success(data) {
                    if (data !== 0) {
                        $('#mont_capa').val(data[0]);
                        $('#mont_credit').val(data[1]);
						$('#dev_capa').val(data[2]);
						$('#part_usu').val(data[3]);
                        $('#mont_capa').attr('readonly', true);
                        $('#mont_credit').attr('readonly', true);
						$('#part_usu').attr('readonly', true);
                    } else {
                        $('#mont_capa').attr('readonly', false);
                        $('#mont_credit').attr('readonly', false);
                        $("#id_message").html("<label>Ce code est invalide</label>");
                    }
                });
            } else {
                $('#mont_capa').attr('readonly', false);
                $('#mont_credit').attr('readonly', false);
				$('#part_usu').attr('readonly', false);
                $('#mont_capa').val('');
                $('#mont_credit').val('');
				$('#part_usu').val('');
            }
            e.preventDefault();
        });
         

		 
		var dev = 'XOF';
        $('#dev_capa').change(function()  {
            var dev1 = $('#dev_capa').val();
            if (dev !== dev1) {
                if ($('#mont_capa').val() !== '' && parseInt($('#mont_capa').val()) > 0 && $('#bnp_compte').val() !== '') {
                    $.get(
                            '/eu-bnp/convertir',{
                                montant: $('#mont_capa').val(),cat: $('#bnp_compte').val(),type_bnp: $('#bnp_type').val(),dev:dev,dev1:dev1,credit:'',conus:''
                            },
                    function success(data) {
                        if (data !== false) {
                            $('#mont_capa').val(data[0]);
                            $('#mont_credit').val(data[1]);
							$('#part_usu').val(data[2]);
                            dev = dev1;
                        } else {
                            alert('Ce cours n\'est pas défini: ' + dev + '-' + dev1);
                            $('#dev_capa').val(dev);
                        }
                    });
                } else if ($('#mont_credit').val() !== '' && parseInt($('#mont_credit').val()) > 0 && $('#bnp_compte').val() !== '')  {
                    $.get('/eu-bnp/convertir',{
                        credit: $(this).val(), cat: $('#bnp_compte').val(), type_bnp: $('#bnp_type').val(),dev: dev, dev1: dev1, montant: ''
                    },
                    function success(data) {
                        if (data !== false) {
                            $('#mont_capa').val(data[0]);
                            $('#mont_credit').val(data[1]);
							 $('#part_usu').val(data[2]);
                            dev = dev1;
                        } else {
                            alert('Ce cours n\'est pas défini: ' + dev + '-' + dev1);
                            $('#dev_capa').val(dev);
                        }
                    });
                }
            }
        });
		
			
        });
    });
</script>