<div class="row-fluid">

<blockquote>Formulaire de demande de services</blockquote>

<?php if (isset($_SESSION["validationerrors"])): ?>

	<div class="alert alert-danger">

		<?php echo implode('<br>', $_SESSION['validationerrors']) ?>
				
    </div>
	
    <?php unset($_SESSION['validationerrors']); endif ?>
    
	<?php if (isset($_SESSION["validationpertesuccess"])): ?>

		<div class="alert alert-success">

			<li><?php echo implode('<br>',$_SESSION['validationpertesuccess']) ?></li>

		</div>


<?php unset($_SESSION['validationpertesuccess']); endif ?>


<form action="#" method="post" class="form-horizontal">

    <div class="control-group">

	    <label class="control-label" for="code_membre_client_franchise" style="font-weight:bold">

	        Votre code membre :
	    
        </label>

	    <div class="controls">

		      <input type="text" name="code_membre_demande" class="input-block-level code_membre_demande" placeholder="Mettre ici votre code membre" required="required"/>
	      
        </div>
	
    </div>

    <div class="control-group">

	    <label class="control-label" for="libellé de votre demande" style="font-weight:bold">

	        Libellé de votre demande :
	    
        </label>

	    <div class="controls">

		      <input type="text" name="libelle_demande" class="input-block-level libelle_demande" placeholder="Mettre ici le libellé de votre demande" required="required"/>
	      
        </div>
	
    </div>

    
    <div class="control-group">

	       <label class="control-label" for="contenu détaillé de la demande" style="font-weight:bold;">

	          Contenu détaillé de la demande:

	       </label>

	       <div class="controls">

              <textarea name="contenu_demande" rows="8" cols="40" class="input-xxlarge" style="width:674px" required="required"></textarea>

	       </div>

	</div>

    <div class="control-group" >
		
        <button type="submit" class="btn btn-large btn-primary">
        
					Valider le formulaire
		</button>
	
    </div>


</form>

</div>