<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Page d'achat d'un franchisé</title>

	<link rel="stylesheet" href="/designfranchise/css/bootstrap.css" type="text/css" />

	<link rel="stylesheet" href="/designfranchise/css/font-icons.css" type="text/css" />

    <link rel="stylesheet" href="/designfranchise/css/style.css" type="text/css" />
    
	<link rel="stylesheet" href="/designfranchise/css/custom.css" type="text/css" />

	<link rel="stylesheet" href="/designfranchise/demos/news/css/fonts.css" type="text/css" />

	<link rel="stylesheet" type="text/css" href="/designfranchise/include/rs-plugin/css/navigation.css">

    <!-- SLIDER REVOLUTION 5.x CSS SETTINGS -->

    <link rel="stylesheet" type="text/css" href="/designfranchise/css/settings.css" media="screen" />
    
    <link rel="stylesheet" type="text/css" href="/designfranchise/css/layers.css">
    
	<link rel="stylesheet" type="text/css" href="/designfranchise/css/navigation.css">


    <style>

   body {

       margin:0;
   }

   #header_franchise {
       
       height: 600px;

       margin: 0;

       background-color: #9b0e36;

       position: relative;
   }

   #header_franchise_center {

    display: flex;

    flex-direction: row;

    justify-content: center;

    width: auto;

    height: 390px;

    align-items: flex-end;

    box-shadow: 0px -1px 30px #FFF inset ;


   }


   #header_franchise_center_image_container{

       width: 300px;

       border: 15px solid #FFF;

       margin-left:25px;

       position: relative;

       height: 380px;

       font-size: 2.3rem;

       display: block;

       text-align: center;

       font-family: "Franklin Gothic Heavy";

       text-transform: uppercase;

       font-style: italic;

       color: #FFF;
   }

   #header_franchise_center img {

       width: 300px;

       border-radius: 2px;

       opacity: 0.9;

       position:relative;

       z-index: 12;

   }


   #text_center {

    position:relative;

    text-align: center;

    color: #FFF;

    font-family: "Franklin Gothic Heavy";

    font-weight: bold;

    font-style: italic;

    font-size: 2.8rem;

    text-transform: uppercase;

   }

    #text_center::before {

        position: absolute;

        content:"";

        width:346px;

        height:1px;

        background-color: #FFF;

        top:33px;

        left:0px;
    }

    #text_center::after {

        position: absolute;

        content:"";

        width:346px;

        height:1px;

        background-color: #FFF;

        top:33px;

        right:0px;
    }


  #franchise_navigation {
    
    display: flex;

    flex-direction: row;

    flex-wrap: wrap;

    align-items: center;

    justify-content: center;


    margin:60px;
    
    width: auto;
  }

  #wrap_image_container{

      padding:10px;

      border: 4px dotted #FF0054;

      margin-left:35px;

      margin-top:35px

  }
  #wrap_image_container img {

      width: 340px;


  }

  #header_menu_franchise {
      
      clear: both;

      position: relative;
  }

  #header_menu_franchise li {

      float: left;

      position:absolute;
  }
    </style>

</head>

<body>

    <header id="header" class="header-size-sm" data-sticky-shrink="false">

    <div class="container">
        <div class="header-row justify-content-between">

            <div class="w-100 d-block d-md-none"></div>

            <div class="col-12 col-sm-6 col-md-4 justify-content-center justify-content-sm-start d-flex order-md-1 mb-4 mb-sm-0" style="margin-top:10px">
                <a href="https://facebook.com/semiColonWeb" class="social-icon si-small si-rounded si-dark si-mini si-facebook mb-0">
                    <i class="icon-facebook"></i>
                    <i class="icon-facebook"></i>
                </a>
                <a href="https://twitter.com/__semicolon" class="social-icon si-small si-rounded si-dark si-mini si-twitter mb-0">
                    <i class="icon-twitter"></i>
                    <i class="icon-twitter"></i>
                </a>
                <a href="https://instagram.com/semicolonweb" class="social-icon si-small si-rounded si-dark si-mini si-instagram mb-0">
                    <i class="icon-instagram"></i>
                    <i class="icon-instagram"></i>
                </a>
            </div>

        </div>
    </div>

    <div id="header-wrap" class="border-top border-f5">
        <div class="container">
            <div class="header-row justify-content-between flex-row-reverse flex-lg-row top-search-parent">

                <div id="primary-menu-trigger">
                    <svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
                </div>

                <!-- Primary Navigation
                ============================================= -->
                <nav class="primary-menu with-arrows">

                    <ul class="menu-container">
                        <li class="menu-item current menu-color-home"><a class="menu-link" href="demo-news.html"><div>Acceuil</div></a></li>
                        <li class="menu-item menu-color-market mega-menu mega-menu-small sub-menu"><a class="menu-link" href="demo-news-category.html"><div>Franchise Interface communauté<i class="icon-angle-down"></i></div></a>
                        
                            <div class="mega-menu-content border-top-0 mega-menu-style-2" style="width: 470px;">

                                <div class="container" style="">

                                    <div class="row">

                                        <ul class="sub-menu-container mega-menu-column" style="">

                                            <ul class="sub-menu-container" style="">

                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-light.html"><div>OI : Offreurs d'Intégration <i class="icon-angle-down"></i></div></a>

                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-dark.html"><div>OKSU : Offreurs de Kits de Solvabilité Universelle <i class="icon-angle-down"></i></div></a>

                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-transparent.html"><div>OBPSD : Offreurs de Biens Produits et Services Dématérialisés <i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OBPS : Offreurs de Biens Produits et Services<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OP : Offreurs de Produits<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OT : Offreurs de Travail<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                            </ul>

                                        </ul>

                                    </div>

                                </div>

                            </div>
                        
                        </li>
                        <li class="menu-item menu-color-market mega-menu mega-menu-small sub-menu"><a class="menu-link" href="demo-news-category.html"><div>Franche Interface acteurs <i class="icon-angle-down"></i></div></a>
                        
                            
                            <div class="mega-menu-content border-top-0 mega-menu-style-2" style="width: 470px;">

                                <div class="container" style="">

                                    <div class="row">

                                        <ul class="sub-menu-container mega-menu-column" style="">

                                            <ul class="sub-menu-container" style="">

                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-light.html"><div>OI : Offreurs d'Intégration <i class="icon-angle-down"></i></div></a>

                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-dark.html"><div>OKSU : Offreurs de Kits de Solvabilité Universelle <i class="icon-angle-down"></i></div></a>

                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-transparent.html"><div>OBPSD : Offreurs de Biens Produits et Services Dématérialisés <i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OBPS : Offreurs de Biens Produits et Services<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OP : Offreurs de Produits<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OT : Offreurs de Travail<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                            </ul>

                                        </ul>

                                    </div>

                                </div>

                            </div>
                        
                        
                        </li>
                        <li class="menu-item menu-color-market mega-menu mega-menu-small sub-menu"><a class="menu-link" href="demo-news-category.html"><div>Franchise Interface partenaires ODD <i class="icon-angle-down"></i></div></a>
                        
                        
                                                    
                            <div class="mega-menu-content border-top-0 mega-menu-style-2" style="width: 470px;">

                                <div class="container" style="">

                                    <div class="row">

                                        <ul class="sub-menu-container mega-menu-column" style="">

                                            <ul class="sub-menu-container" style="">

                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-light.html"><div>OI : Offreurs d'Intégration <i class="icon-angle-down"></i></div></a>

                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-dark.html"><div>OKSU : Offreurs de Kits de Solvabilité Universelle <i class="icon-angle-down"></i></div></a>

                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-transparent.html"><div>OBPSD : Offreurs de Biens Produits et Services Dématérialisés <i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>
                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OBPS : Offreurs de Biens Produits et Services<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OP : Offreurs de Produits<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                                <li class="menu-item sub-menu" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>OT : Offreurs de Travail<i class="icon-angle-down"></i></div></a>
                                                    <ul class="sub-menu-container mega-menu-dropdown" style="">
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                        </li>
                                                        <li class="menu-item" style="">
                                                            <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                        </li>
                                                    </ul>
                                                    <button class="sub-menu-trigger icon-chevron-right"></button>
                                                </li>

                                            </ul>

                                        </ul>

                                    </div>

                                </div>

                            </div>
                        
                        
                        
                        </li>

                    </ul>

                    <!-- Mobile Menu
                    ============================================= -->
                    <ul class="menu-container mobile-primary-menu">
                        <li class="menu-item current menu-color-home"><a class="menu-link" href="demo-news.html"><div>Home</div></a></li>
                        <li class="menu-item menu-color-travel"><a class="menu-link" href="demo-news-category.html"><div>Travel</div></a></li>
                        <li class="menu-item menu-color-lifestyle"><a class="menu-link" href="demo-news-category.html"><div>Lifestyle</div></a></li>
                        <li class="menu-item menu-color-tech"><a class="menu-link" href="demo-news-category.html"><div>Tech</div></a></li>
                        <li class="menu-item menu-color-fashion"><a class="menu-link" href="demo-news-category.html"><div>Fashion</div></a></li>
                        <li class="menu-item menu-color-sports"><a class="menu-link" href="demo-news-category.html"><div>Sports</div></a></li>
                        <li class="menu-item menu-color-food"><a class="menu-link" href="demo-news-category.html"><div>Food</div></a></li>
                        <li class="menu-item menu-color-market sub-menu"><a class="menu-link" href="demo-news-category.html"><div>More<i class="icon-angle-down"></i></div></a>
                            <ul class="sub-menu-container" style="">
                                <li class="menu-item sub-menu" style=""><a class="menu-link" href="#"><div>Header<i class="icon-angle-down"></i></div></a>
                                    <ul class="sub-menu-container" style="">
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="header-light.html"><div>Light Version</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="header-dark.html"><div>Dark Version</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="header-transparent.html"><div>Transparent</div></a>
                                        </li>
                                        <li class="menu-item sub-menu" style="">
                                            <a class="menu-link" href="header-semi-transparent.html"><div>Semi Transparent<i class="icon-angle-down"></i></div></a>
                                            <ul class="sub-menu-container" style="">
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-semi-transparent.html"><div>Light Version</div></a>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-semi-transparent-dark.html"><div>Dark Version</div></a>
                                                </li>
                                            </ul>
                                        <button class="sub-menu-trigger icon-chevron-right"></button></li>
                                        <li class="menu-item sub-menu" style="">
                                            <a class="menu-link" href="header-side-left.html"><div>Left Side Header<i class="icon-angle-down"></i></div></a>
                                            <ul class="sub-menu-container" style="">
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-side-left.html"><div>Fixed Position</div></a>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-side-left-open.html"><div>OnClick Open</div></a>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-side-left-open-push.html"><div>Push Content</div></a>
                                                </li>
                                            </ul>
                                        <button class="sub-menu-trigger icon-chevron-right"></button></li>
                                        <li class="menu-item sub-menu" style="">
                                            <a class="menu-link" href="header-side-right.html"><div>Right Side Header<i class="icon-angle-down"></i></div></a>
                                            <ul class="sub-menu-container" style="">
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-side-right.html"><div>Fixed Position</div></a>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-side-right-open.html"><div>OnClick Open</div></a>
                                                </li>
                                                <li class="menu-item" style="">
                                                    <a class="menu-link" href="header-side-right-open-push.html"><div>Push Content</div></a>
                                                </li>
                                            </ul>
                                        <button class="sub-menu-trigger icon-chevron-right"></button></li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="header-floating.html"><div>Floating Version</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="static-sticky.html"><div>Static Sticky</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="responsive-sticky.html"><div>Responsive Sticky</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="logo-changer.html"><div>Alternate Logos</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="alternate-mobile-menu.html"><div>Alternate Mobile Menu</div></a>
                                        </li>
                                    </ul>
                                <button class="sub-menu-trigger icon-chevron-right"></button></li>
                            </ul>
                            <ul class="sub-menu-container" style="">
                                <li class="menu-item mega-menu-title sub-menu" style=""><a class="menu-link" href="#"><div>Layouts</div></a>
                                    <ul class="sub-menu-container" style="">
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="blog-single.html"><div>Default Layout</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="blog-single-left-sidebar.html"><div>Left Sidebar</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="blog-single-both-sidebar.html"><div>Both Sidebar</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="both-left-sidebar.html"><div>Both Left Sidebar</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="both-right-sidebar.html"><div>Both Right Sidebar</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="blog-single-full.html"><div>Full Width</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="blog-single-small.html"><div>Small Image</div></a>
                                        </li>
                                        <li class="menu-item" style="">
                                            <a class="menu-link" href="blog-single-split-right-sidebar.html"><div>Split Layout</div></a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        <button class="sub-menu-trigger icon-chevron-right"></button></li>
                    </ul>

                </nav><!-- #primary-menu end -->

                <form class="top-search-form" action="search.html" method="get" style="width: 1110px;">
                    <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter.." autocomplete="off">
                </form>

            </div>
        </div>
    </div>
    <div class="header-wrap-clone" style="height: 61px;"></div>

</header>

    <header id="header_franchise">

        <div id="header_franchise_center">

            <div id="header_franchise_center_image_container">

                <img src="/designfranchise/img/utilisateurs.jpg" alt="Franchise utilisateurs">

                <span>Interface Acteurs</span>

            </div>

            <div id="header_franchise_center_image_container">

                <img src="/designfranchise/img/partenaire_odd.jpg" alt="Partenaire ODD">

                <span>Interface Partenaire ODD</span>

            </div>

            <div id="header_franchise_center_image_container">

                <img src="/designfranchise/img/communaute.jpg" alt="ODD">

                <span>Interface Communauté</span>

            </div>

        </div>

        <div style="text-align: center;">

        <h1 id="text_center">Franchise d'implantation</h1>

        </div>

        <img src="/designfranchise/img/backgroun-image.PNG" alt="" style="position:absolute;left:45px;opacity: 0.5;width:50px;height:50px;top:10px">

        <img src="/designfranchise/img/backgroun-image.PNG" alt="" style="position:absolute;left:437px;opacity: 0.1;width:90px;height:175px;transform:rotate(130deg);top:10px;z-index: 10;">


        <img src="/designfranchise/img/odd.jpg" width = "75px" height= "75px" alt="" style="position: absolute;right:45px;border-radius:45px;">


    </header>

     <section id="franchise_navigation">

        <div id="wrap_image_container">

            <img src="/designfranchise/img/guichet_unique_interface_utilisateurs_pbf.jpg" alt="">

        </div>

        <div id="wrap_image_container">

           <img src="/designfranchise/img/guichet_unique_utilisateurs_bps.jpg" alt="">

        </div>

        <div id="wrap_image_container">

           <img src="/designfranchise/img/guichet_unique_interface_partenaire_odd.jpg" alt="">

        </div>

        <div id="wrap_image_container">

            <img src="/designfranchise/img/guichet_unique_interface_communaute.jpg" alt="">
 
         </div>

         <div id="wrap_image_container">

            <img src="/designfranchise/img/guichet_unique_communaute.jpg" alt="">

         </div>

         <div id="wrap_image_container">

             <img src="/designfranchise/img/guichet_unique_utilisateurs_pbf.jpg" alt="">

         </div>

         <div id="wrap_image_container">

            <img src="/designfranchise/img/guichet_unique_odd.jpg" alt="">

         </div>

         <div id="wrap_image_container">

            <img src="/designfranchise/img/guichet_unique_utilisateurs_bps.jpg" alt="">
            
         </div>

     </section>
<script src="/designfranchise/js/jquery.js" defer></script>

</body>
</html>