<script type="text/javascript" charset="utf-8">

$(document).ready(function() {

    $('#example').dataTable( {

        "sPaginationType": "full_numbers",

        "iDisplayLength":10,

		"aaSorting": []

    } );
} );
</script>

<?php if (isset($_SESSION["validationerrors"])): ?>

	<div class="alert alert-danger">

		<?php echo implode('<br>', $_SESSION['validationerrors']) ?>

	</div>

	<?php unset($_SESSION['validationerrors']); endif ?>

	<?php if (isset($_SESSION["validationsuccess"])): ?>

	<div class="alert alert-success">

		<?php echo implode('<br>',$_SESSION['validationsuccess']) ?>

	</div>

<?php unset($_SESSION['validationsuccess']); endif ?>

<?php include("../application/layouts/scripts/menuasso.phtml"); ?>


<blockquote>    

   <strong>Liste de tous les types de guichets</strong>

</blockquote>


<?php if ($this->countallguichets > 0): ?>

<table class="table table-striped" id="example">

   <thead> 

        <tr>

             <th>Nom de l'utilisateur</th>

             <th>Prénoms de l'utilisateur</th>

             <th> Responsabilité </th>  

             <th>Nom du poste occupé</th>

         </tr>

   </thead>

   <tbody>

   <?php foreach ($this->listdetouslesguichets as $key => $value): ?>

   
      <td><?php echo $value->code_type_guichet ;?> </td>   


   <?php endforeach ?> 
   
   </tbody>

</table>


<?php else: ?>

   <div class="alert alert-danger">

      <strong>Vous n'avez pas encore enregistré aucun type de guichet</strong>
       
   </div>

<?php endif ?>