
     
<a href="/guichets/listedesdecoupagesgeographiques/searchkeyfranchises/franchise_implantation_locale"><span style="display:block;font-size:1.3rem;color:#aa325f;font-weight:bold">Franchise implantation locale</span></a>

<a href="/guichets/listedesdecoupagesgeographiques/searchkeyfranchises/franchise_entite_membre"><span style="display:block;font-size:1.3rem;color:#aa325f;font-weight:bold">Franchise entité Localité membre</span></a>

<a href="/guichets/listedesdecoupagesgeographiques/searchkeyfranchises/franchise_locale"><span style="display:block;font-size:1.3rem;color:#aa325f;font-weight:bold">Franchise localité de base</span></a>
