<blockquote>
   INTERFACE D'AJOUT DE CIBLE
</blockquote>

<?php if (isset($_SESSION["validationerrors"])): ?>

	<div class="alert alert-danger">

		<?php echo implode('<br>', $_SESSION['validationerrors']) ?>

	</div>

	<?php unset($_SESSION['validationerrors']); endif ?>

	<?php if (isset($_SESSION["validationpertesuccess"])): ?>

		<div class="alert alert-success">

			<li><?php echo implode('<br>',$_SESSION['validationpertesuccess']) ?></li>

		</div>
        
<?php unset($_SESSION['validationpertesuccess']); endif ?>


<form action="#" method="POST">

    <div class="control-group">

	      <label class="control-label" for="Libelle du cible" style="font-weight:bold">

	        Libelle du cible *:

	      </label>

	      <div class="controls">

		     <input type="text" name="agence_libelle_cible" class="input-block-level agence_libelle_cible" placeholder="Saisir le nom de la cible" required="required"/>
	      
          </div>

	</div>

    <div class="control-group"> 

				<label for="organisation_agence_odd" style="font-weight:bold;float:left">

					Liste des odd*: 
                    
                </label>

				<select class="input-block-level" name="cible_odd" id="input_organisation_agence_odd">

 					<option value>Selectionner un ODD</option>

 					<?php foreach ($this->listedesodd as $key => $value): ?>

 					     <option value="<?php echo $value->id_odd ?>" data-idroles="<?php echo $value->code_odd ?>"><?php echo "ODD N°".$value->id_odd." : ".$value->titre ?></option>
 					
                     <?php endforeach; ?>

 				</select>

	</div>

    <div class="control-group">

	      <label class="control-label" for="Contenu de la cible" style="font-weight:bold">

	        Contenu de la cible *:

	      </label>

	      <div class="controls">

             <textarea name="agence_description_cible" class="input-block-level agence_description_cible" cols="30" rows="10" placeholder="Saisir le contenu de la cible" required="required"></textarea>
	      
          </div>

	</div>

    <div class="control-group" >

        <button type="submit" class="btn btn-large btn-primary" style="position:relative">

             Valider le formulaire

        </button>
    </div>


</form>