<?php if (isset($_SESSION["validationerrors"])): ?>

<div class="alert alert-danger">

    <?php echo implode('<br>', $_SESSION['validationerrors']) ?>

</div>

<?php unset($_SESSION['validationerrors']); endif ?>

<?php if (isset($_SESSION["validationsuccess"])): ?>

    <div class="alert alert-success">

        <li><?php echo implode('<br>',$_SESSION['validationsuccess']) ?></li>

    </div>
    
<?php unset($_SESSION['validationsuccess']); endif ?>

<form action="#" method="POST">


    <div class="control-group"> 

				<label for="organisation_roles" style="font-weight:bold;float:left">

					Liste des roles*: 
                    
                </label>

				<select class="input-block-level" name="roles_cibles" id="input_organisation_agence_odd">

 					<option value>Selectionner un rôle</option>

 					<?php foreach ($this->selectallroles as $key => $value): ?>

 					     <option value="<?php echo $value->id_roles ?>" data-idroles="<?php echo $value->id_roles ?>"><?php echo $value->libelle_roles ?></option>
 					
                     <?php endforeach; ?>

 				</select>

	</div>

    <div class="control-group">

       			<blockquote style = "font-weight:bold">

				      Selectionner les roles parents distant:	
				
				</blockquote>

 			    <?php foreach ($this->selectallroles as $key => $value): ?>

                    <div class="span4" style="height:200px">
				      
                      <div class="control-group">
                      
                           <label class="radio">

                               <input type="checkbox" name="roles_parent_distant[]" id="roles_parent_distant" value="<?php echo $value->id_roles ?>" data-idrrole="<?php echo $value->idrrole ?>">
                               
                               <span style="font-size:1.2em"> <span style="font-weight:bold"><?php echo $value->libelle_roles ?></span></span>
                           
                           </label>
                      </div>
                
                </div>
    
                <?php endforeach; ?>
    
    </div>

    <div class="control-group" >

          <button type="submit" class="btn btn-large btn-primary" id ="validguichet" style="position:relative">

              Valider le formulaire

          </button>

    </div>
</form>