<script type="text/javascript" charset="utf-8">

$(document).ready(function() {

    $('#example').dataTable( {

        "sPaginationType": "full_numbers",

        "iDisplayLength":10,

		"aaSorting": []

    } );
} );
</script>

<?php if (isset($_SESSION["validationerrors"])): ?>

	<div class="alert alert-danger">

		<?php echo implode('<br>', $_SESSION['validationerrors']) ?>

	</div>

	<?php unset($_SESSION['validationerrors']); endif ?>

	<?php if (isset($_SESSION["validationsuccess"])): ?>

	<div class="alert alert-success">

		<?php echo implode('<br>',$_SESSION['validationsuccess']) ?>

	</div>

<?php unset($_SESSION['validationsuccess']); endif ?>

<?php include("../application/layouts/scripts/menuadmin.phtml"); ?>

<?php if ($this->countitemsusersdungroupederolescible > 0): ?>


<blockquote>

    <strong>LISTE DES AGENTS CREES (<?php echo $this->nomdugroupederolecible[0]->libelle_groupe_roles ?>)</strong>

</blockquote>


<table class="table table-striped" id="example">

   <thead> 

        <tr>

             <th>Nom de l'agent</th>

             <th>Prénoms de l'agent</th>

             <th> Login </th>

             <th> Responsabilité </th>  


             <th>Nom du poste occupé</th>

         </tr>

   </thead>

   <tbody>

   <?php foreach ($this->listedesuserdungroupederolescible as $key => $value): ?>

       <tr>

             <td><?php echo $value->nom_utilisateur ;?> </td>   

             <td><?php echo $value->prenom_utilisateur ;?> </td>

             <?php if ($value->responsabilite == 1): ?>

                <td><?php echo $value->libelle_responsabilite ;?> </td> 

             <?php elseif($value->responsabilite == 0):  ?>

                <td> <?php echo $value->login ;?> </td> 

             <?php endif ?>

             <td> <?php echo $value->libelle_responsabilite ;?> </td> 


             <?php if ($this->nomdugroupederole[0]->libelle_groupe_roles  == "CIBLES" || $this->nomdugroupederole[0]->libelle_groupe_roles  == "INDICATEURS"): ?>

                <td>Agent <?php echo $value->code_roles ;?> </td>    

             <?php else: ?>

                 <td><?php echo $value->libelle_roles ;?> </td>    
             
             <?php endif ?>
                 
       </tr>


   <?php endforeach ?> 
   
   </tbody>

</table>

<?php else: ?>

   <div class="alert alert-danger">

      <strong>Vous n'avez pas encore enregistré aucun utilisateur</strong>
       
   </div>

<?php endif ?>