<?php $sessionmembre = new Zend_Session_Namespace('membre');?>


<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<?php include("../application/layouts/scripts/menuperso.phtml"); ?>

  <blockquote><p>Liste de mes bons d'achat </p></blockquote>
  <?php if(isset($sessionmembre->error) && $sessionmembre->error!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmembre->error; $sessionmembre->error = ""; ?>
    </div>
  <?php }?>
  
<?php if(count($this->entries)>0){?> 

<table class="table table-striped table-bordered table-hover table-condensed" id="example">
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Numéro</th>
								  <th>Proposition</th>
								  <th>Salaire</th>
								  <th>Montant</th>
								  <th>Distributeur</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php foreach ($this->entries as $entry): ?>
    <tr>
      <td><?php echo ($entry->bon_date); ?></td>
      <td><?php echo ($entry->bon_numero); ?></td>
      <td><?php echo ($entry->bon_proposition); ?></td>
      <td><?php echo ($entry->bon_montant_salaire); ?></td>
      <td><?php echo ($entry->bon_montant); ?></td>
      <td><?php echo ($entry->bon_code_membre_distributeur); ?></td>
      <td><div align="center">
            <a class="btn btn-mini btn-primary" href="<?php echo $this->baseUrl(); ?>/bonachat/pdfbonachat/id/<?php echo $entry->bon_id; ?>" target="_blank"><i class="icon-cog icon-white"></i>  Générer le pdf</a>&nbsp;
		</div></td>
      
    </tr>
<?php endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun bon enrégistré 
</div>
<?php }?>




</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








