<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
  
<div class="card3">
<div class="row">
<div class="col-xl-12" style="text-align:left">
  
<blockquote class="blockquote"> BPS Fournisseurs </blockquote>

<?php if(count($this->entries) > 0) { ?>

<?php foreach ($this->entries as $entry) { 

$morale = new Application_Model_EuMembreMorale();
$moraleM = new Application_Model_EuMembreMoraleMapper();
$moraleM->find($entry->code_membre,$morale);

if($morale->desactiver == 0) {
?>

<div class="card">
     <div class="card-header" role="tab" id="headingOne_<?php echo ($entry->code_membre); ?>">
      <h6 class="mb-0">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne_<?php echo ($entry->code_membre); ?>" aria-expanded="true" aria-controls="collapseOne_<?php echo ($entry->code_membre); ?>">
           <?php 
		       $morale = new Application_Model_EuMembreMorale();
               $moraleM = new Application_Model_EuMembreMoraleMapper();
               $moraleM->find($entry->code_membre,$morale);
               echo ($morale->raison_sociale); 
		   ?>
        </a>
      </h6>
    </div>
	
	
	<div id="collapseOne_<?php echo ($entry->code_membre); ?>" class="collapse" role="tabpanel" aria-labelledby="headingOne_<?php echo ($entry->code_membre); ?>">
     <div class="card-block" style="padding: 0;">
          <?php
                $tegc = new Application_Model_EuTegc();
                $tegcM = new Application_Model_EuTegcMapper();
                $rowste  = $tegcM->fetchByMembreConfig($entry->code_membre);		  
                
				
   		  ?>
          <table class="table table-striped table-hover table-sm">
		  <thead>
          <tr>
              <th>Terminal de vente</th>
              <th>Information sur Les Produits</th>
			  <th>Panier</th>
          </tr>
          </thead>
		  <?php if(count($rowste) > 0) { ?>
		  <tbody>
		      <?php foreach($rowste as $rowte): ?>
			    <tr>
				   <td> <?php echo($rowte->nom_tegc) ;?></td>
				   <td><a class="btn btn-mini btn-warning" href="<?php echo $this->baseUrl(); ?>/index/detailproduit/id/<?php echo $rowte->code_tegc; ?>"><i class="icon-info-sign icon-white"></i>DETAILS</a>
		           </td>
				   <td>
	                  <a class="btn btn-mini btn-success" href="<?php echo $this->baseUrl(); ?>/boutiqueligne/acteurcreneaumembremoralearticle/membre/<?php echo $morale->code_membre_morale; ?>/categorie/<?php echo $rowte->code_tegc; ?>"> <i class="icon-info-sign icon-white"></i>PANIER</a><?php /*?><?php */?>			   
				   </td>
			    </tr>
              <?php endforeach; ?>			  
		  </tbody>
		  <?php } ?>
		  </table>
	 </div>
    </div>
</div>



<?php } ?>

<?php  }

}  

?>





</div>
</div>
</div>