<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences2.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>
<script src="<?php echo $this->baseUrl();?>/bootstrap/js/jquery.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadtepre.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
		
		/*
		$('#offreur_projet_membre').blur(function(e) {      
        $.get('/index/codetegc',{
          code_membre : $(this).val()
        },
        function success(data)  {
		    if(data != "") {
			    $('#div_login').css('display','none');
				$('#div_fournisseur').css('display','none');
				$('#offreur_projet_produit').attr("required",false);
				$('#offreur_projet_filiere').attr("required",false);
                
            } else {
			    if($('#offreur_projet_membre').val() != "") {
			        $('#div_login').css('display','block');
					$('#div_fournisseur').css('display','block');
				    $('#offreur_projet_produit').attr("required",true);
				    $('#offreur_projet_filiere').attr("required",true);
			    }
            }		  
        });
        e.preventDefault();		 
    });
	*/
		
		
		
		$('#souscription_nombre').val(100);
		$('#souscription_montant').val(218750);
	    $('#offreur_projet_type').change(function(e) {
	        $.get('/index/montant1',{
                integrateur_type : $(this).val()
            },
		    function success(data)  {
			    $('#souscription_montant').val(data);
		    });
		    e.preventDefault();
	    });


        
	$('#offreur_projet_type').change(function(e) {
		if($('#offreur_projet_type').val() >= 4) {
			$('#div_cap').css('display','block');
		} else {
			$('#div_cap').css('display','none');
		}
		
		if($('#offreur_projet_type').val() == 1) {
			$('#div_vendre').css('display','block');
			$('#div_stock').css('display','block');
			$('#nom_entrepot').html("Nom de l'entrepôt *");
			$('#adresse_entrepot').html("Adresse de l'entrepôt *");
			$('#offreur_projet_nom_entrepot').attr("required",true);
			$('#offreur_projet_adresse_entrepot').attr("required",true);
		} else if($('#offreur_projet_type').val() == 2) {
			$('#div_vendre').css('display','block');
			$('#div_stock').css('display','block');
			$('#nom_entrepot').html("Nom du magasin *");
			$('#adresse_entrepot').html("Adresse du magasin *");
			$('#offreur_projet_nom_entrepot').attr("required",true);
			$('#offreur_projet_adresse_entrepot').attr("required",true);
		} else if($('#offreur_projet_type').val() == 3) {
			$('#div_vendre').css('display','block');
			$('#div_stock').css('display','block');
            $('#nom_entrepot').html("Nom de la boutique *");
			$('#offreur_projet_nom_entrepot').attr("required",true);
			$('#offreur_projet_adresse_entrepot').attr("required",true);
			$('#adresse_entrepot').html("Adresse de la boutique *");
		} else if($('#offreur_projet_type').val() == 4 || $('#offreur_projet_type').val() == 5 || $('#offreur_projet_type').val() == 6) {
			$('#div_vendre').css('display','block');
			$('#div_stock').css('display','block');
			$('#nom_entrepot').html("Nom du lieu de transformation");
			$('#adresse_entrepot').html("Adresse du lieu de transformation");
			$('#offreur_projet_nom_entrepot').attr("required",true);
			$('#offreur_projet_adresse_entrepot').attr("required",true);
        } else if($('#offreur_projet_type').val() == 7 || $('#offreur_projet_type').val() == 8 || $('#offreur_projet_type').val() == 9) {
			$('#div_vendre').css('display','block');
			$('#div_stock').css('display','block');
			$('#nom_entrepot').html("Nom du lieu de production");
			$('#adresse_entrepot').html("Adresse du lieu de production");
			$('#offreur_projet_nom_entrepot').attr("required",true);
			$('#offreur_projet_adresse_entrepot').attr("required",true);
	    } else {
			$('#div_vendre').css('display','none');
			$('#div_stock').css('display','none');
			$('#offreur_projet_nom_entrepot').attr("required",true);
			$('#offreur_projet_adresse_entrepot').attr("required",true);
		}
		
	});
		
	});


    function calculmontant(nombre) {
        document.getElementById('souscription_montant').value = document.getElementById('souscription_nombre').value * 2187.5;
	    document.getElementById('souscription_montant').readOnly = true;
    }
	
    function nbremontantcmfh(type) {
	if((type > 0 && type <= 5) || (type > 0 && type > 9)) {
	    document.getElementById('souscription_nombre').value = 500;
		document.getElementById('souscription_montant').value = 500 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;	
	} else if((type > 5 && type <= 7)) {
	    document.getElementById('souscription_nombre').value = 100;
		document.getElementById('souscription_montant').value = 100 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;	
	} else if(type == 9) {
	    document.getElementById('souscription_nombre').value = 10;
		document.getElementById('souscription_montant').value = 10 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;		
	} else if(type == 8) {
	    document.getElementById('souscription_nombre').value = 10;
		document.getElementById('souscription_montant').value = 10 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = false;
		document.getElementById('souscription_montant').readOnly = false;		
	}
	}

    



	
</script>

<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">
<?php 
//$typeoffreur_projet = new Application_Model_EuTypeOffreurProjet();
//$typeoffreur_projetM = new Application_Model_EuTypeOffreurProjetMapper();
//$typeoffreur_projetM->find($this->param, $typeoffreur_projet);

    $titre = "";
    if($this->param == 1) {
	    $titre = "Acteur Offreur de Bien,Produit ou Service (BPS)";
    } elseif($this->param == 2) {
	    $titre = "Acteur Partenaire Bancaire et Financier";
	}


?>

  <blockquote><p><?php echo $titre." - Phase Pré-Souscription"; ?> </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addacteur">
  <?php if(isset($sessionmcnp->error) && $sessionmcnp->error != "") { ?>
  <div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <?php echo $sessionmcnp->error; $sessionmcnp->error = ""; ?>
  </div>
  <?php } ?>
  
<fieldset>


<legend>Code BAn</legend>
<div class="control-group">
  <label class="control-label" for="code_BAn">Code BAn *</label>
  <div class="controls">
  <input name="code_BAn" type="text" id="code_BAn" placeholder="Entrer le Code BAn" required="required" />
	<span id="nivban"><button type="button" class="btn btn-info" onclick="ouvre_bonachatneutres(document.getElementById('code_BAn').value, 'nivban');">Vérifier</button></span>
    <span class="help-block"><p class="text-error" style="color:red">Veuillez saisir le Code BAn affiché lors de la souscription BAn</p></span>
  </div>
</div>



<legend> Remplir les informations sur le Souscripteur </legend>
<div class="control-group">
<label class="control-label" for="code_membre">Code membre * </label>
<div class="controls">
    <input type="text" onchange="ouvre_loadtepre(this.value,'nivo_te');" name="code_membre" id="code_membre" placeholder="Code Membre Morale Souscripteur"  value="<?php echo $this->code_membre; ?>"  class="input-block-level"  readOnly />
</div>
</div>


<div id="nivo_te">

</div>


<div class="control-group">
    <label class="control-label" for="offreur_projet_type">Type Souscripteur *</label>
    <div class="controls">
    <select  class="input-block-level" name="offreur_projet_type" id="offreur_projet_type" >
        <?php  
	        $typeoffreur_projet2 = new Application_Model_EuTypeOffreurProjetMapper();
		    $selecttypeoffreur_projet2 = $typeoffreur_projet2->fetchAll();?>
            <option value="">Choisir un type </option>
                <?php foreach ($selecttypeoffreur_projet2 as $selecttypeoffreur_projet): ?>
            <option value="<?php echo $selecttypeoffreur_projet->id_type_offreur_projet; ?>" <?php if($selecttypeoffreur_projet->id_type_offreur_projet == $typeoffreur_projet->id_type_offreur_projet){echo ' selected="selected"';}?>><?php echo ($selecttypeoffreur_projet->libelle_type_offreur_projet); ?></option>
        <?php endforeach; ?>
    </select>
</div>
</div>




<div class="control-group" id="div_login" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_login">Login du souscripteur </label>
<div class="controls">
  <input type="text" name="souscription_login" id="souscription_login" placeholder="Login du souscripteur" class="input-block-level" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="souscription_passe">Mot de passe du souscripteur </label>
<div class="controls">
  <input type="password" name="souscription_passe" id="souscription_passe" placeholder="Mot de passe du souscripteur" class="input-block-level" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="confirme">Confirmer Mot de passe du souscripteur </label>
<div class="controls">
  <input type="password" name="confirme" id="confirme" placeholder="Confirmer Mot de passe du souscripteur" class="input-block-level" />
</div>
</div>
</div>



<div class="control-group">
<label class="control-label" for="souscription_montant">Nombre de comptes marchands souscrits * </label>
<div class="controls">
  <input type="text" name="souscription_nombre" id="souscription_nombre" placeholder="Nombre de comptes marchands souscrits"  value="<?php echo $this->souscription_nombre; ?>"   onblur="calculmontant(this.value);"  class="input-block-level"  required="required" />
</div>
</div>


<div class="control-group">
<label class="control-label" for="souscription_montant">Montant de la souscription * </label>
<div class="controls">
  <input type="text" name="souscription_montant" id="souscription_montant" placeholder="Montant de la souscription aux comptes marchands pour tiers"  value="<?php echo $this->souscription_montant; ?>"  class="input-block-level"  required="required" />
</div>
</div>


<div class="control-group">
<label class="control-label" for="offreur_projet_zone">Zone Monétaire *</label>
<div class="controls">
<select name="code_zone" id="code_zone" class="input-block-level" required>
   <option value="">Choisir une zone monétaire</option>
   <?php foreach ($this->zones as $value) { ?>
   <option
      value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?>
   </option>
   <?php } ?>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="id_pays">Pays *</label>
<div class="controls">
<select name="id_pays" id="id_pays" class="input-block-level" required>
   <option value="">Choisir un pays</option>
   <?php foreach ($this->pays as $value) { ?>
      <option value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?></option>
   <?php } ?>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="offreur_projet_region">Régions *</label>
<div class="controls">
<select name="id_region" id="id_region" class="input-block-level" required>
   <option value="">Choisir une région</option>
   <?php foreach ($this->regions as $value) { ?>
      <option value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?></option>
   <?php } ?>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="id_prefecture">Préfectures *</label>
<div class="controls">
<select name="id_prefecture" id="id_prefecture" class="input-block-level" required>
   <option value="">Choisir une préfecture</option>
   <?php foreach ($this->prefectures as $value) { ?>
      <option value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?></option>
   <?php } ?>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="id_canton">Canton *</label>
<div class="controls">
<select name="id_canton" id="id_canton" class="input-block-level" required>
   <option value="">Choisir un canton</option>
   <?php foreach ($this->cantons as $c) { ?>
      <option value="<?php echo $c->id_canton; ?>"><?php echo $c->nom_canton; ?></option>
   <?php } ?>
</select>
</div>
</div>


<div class="control-group" id="div_fournisseur"  style="display:none;">
<div class="control-group">
<label class="control-label" for="offreur_projet_produit">Produit *</label>
<div class="controls">
<input type="text" name="offreur_projet_produit" id="offreur_projet_produit" placeholder="Produit" class="input-block-level" required  />
</div>
</div>

<div class="control-group">
<label class="control-label" for="offreur_projet_filiere">Filière * </label>
<div class="controls">
<select name="offreur_projet_filiere" id="offreur_projet_filiere" class="input-block-level" required>
    <option value=""> Choisir une filière </option>
    <?php foreach ($this->filieres as $value) { ?>
          <option value="<?php echo $value->id_filiere; ?>"><?php echo $value->nom_filiere; ?></option>
    <?php } ?>
</select>
</div>
</div>
</div>


<div class="control-group">
<label class="control-label" for="offreur_projet_description_projet">Description du projet </label>
<div class="controls">
  <textarea name="offreur_projet_description_projet" class="input-block-level" id="offreur_projet_description_projet" placeholder="Description du projet"></textarea>
</div>
</div>

<div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <input type="checkbox" name="offreur_projet_operationnel" id="offreur_projet_operationnel" value="1"> Je suis opérationnel
      </label>
    </div>
</div>


<?php if($this->param == 1) {?>

<div id="div_cap" style="display:none;">
<div class="control-group">
<label class="control-label" for="offreur_projet_capacite_production">Capacité de production *</label>
<div class="controls">
<input type="text" name="offreur_projet_capacite_production" id="offreur_projet_capacite_production" placeholder="Capacité de production" class="input-block-level"  />
</div>
</div>
</div>

<?php //}?>


<div id="div_stock" style="display:none;">
<div class="control-group">
<label class="control-label" for="offreur_projet_stock_disponible">Stock disponible </label>
<div class="controls">
<input type="text" name="offreur_projet_stock_disponible" id="offreur_projet_stock_disponible" placeholder="Stock disponible" class="input-block-level"   />
</div>
</div>

<div class="control-group">
<label class="control-label" for="offreur_projet_qte_max">Quantité maximale </label>
<div class="controls">
<input type="text" name="offreur_projet_qte_max" id="offreur_projet_qte_max" placeholder="Quantité maximale" class="input-block-level"  />
</div>
</div>

<div class="control-group">
<label class="control-label" for="offreur_projet_qte_moyen">Quantité moyenne </label>
<div class="controls">
<input type="text" name="offreur_projet_qte_moyen" id="offreur_projet_qte_moyen" placeholder="Quantité moyenne" class="input-block-level"  />
</div>
</div>

<div class="control-group">
<label class="control-label" for="offreur_projet_qte_min">Quantité minimale </label>
<div class="controls">
<input type="text" name="offreur_projet_qte_min" id="offreur_projet_qte_min" placeholder="Quantité minimale" class="input-block-level"  />
</div>
</div>
</div>



<?php

/* 
if($this->param == 1){
	$offreur_projet_nom_entrepot = "Nom de l'entrepôt";
	$offreur_projet_adresse_entrepot = "Adresse de l'entrepôt";
}else if($this->param == 2){
	$offreur_projet_nom_entrepot = "Nom du magasin";
	$offreur_projet_adresse_entrepot = "Adresse du magasin";
}else if($this->param == 3){
	$offreur_projet_nom_entrepot = "Nom de la boutique";
	$offreur_projet_adresse_entrepot = "Adresse de la boutique";
}else if($this->param == 4 || $this->param == 5 || $this->param == 6) {
	$offreur_projet_nom_entrepot = "Nom du lieu de transformation";
	$offreur_projet_adresse_entrepot = "Adresse du lieu de transformation";
}else if($this->param == 7 || $this->param == 8 || $this->param == 9) {
	$offreur_projet_nom_entrepot = "Nom du lieu de production";
	$offreur_projet_adresse_entrepot = "Adresse du lieu de production";
	}
*/
	
?>

<div id="div_vendre" style="display:none;">
<div class="control-group">
<label class="control-label" id="nom_entrepot">Nom Entreprise </label>
<div class="controls">
<input type="text" name="offreur_projet_nom_entrepot" id="offreur_projet_nom_entrepot" placeholder="" class="input-block-level" />
</div>
</div>

<div class="control-group">
<label class="control-label" id="adresse_entrepot">Adresse Entreprise </label>
<div class="controls">
  <textarea name="offreur_projet_adresse_entrepot" class="input-block-level" id="offreur_projet_adresse_entrepot" placeholder=""></textarea>
</div>
</div>
</div>
<?php } ?>


<div class="control-group">
<label class="control-label" for="offreur_projet_attestation">Attestation  *  </label>
<div class="controls">
<label class="checkbox">
<input name="offreur_projet_attestation" type="checkbox" id="offreur_projet_attestation" value="1" required /> Je, soussigné, certifie, en toute conscience, que les renseignements ci-dessus rendent fidèlement compte de ma situation, de mes qualifications et de mon expérience. J’accepte que toute fausse déclaration volontaire puisse entraîner ma disqualification de la présente procédure.
</label>
</div>
</div>

</fieldset> 
   
<div class="form-actions">
<input name="publier" type="hidden" id="publier" value="0" />
<input name="param" type="hidden" id="param" value="<?php echo $this->param; ?>"/>
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" id="submit" class="btn btn-primary">Enregistrer</button>
</div>
 
</form>

<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
outilqrformobligatoire("addacteur","submit");
</script>


</div>
<div class="span3">
<?php //include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








