<?php $sessionmcnp = new Zend_Session_Namespace('mcnp'); ?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/integrateur.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/banques.js"></script>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bonachatneutres3.js"></script>

<script src="<?php echo $this->baseUrl();?>/bootstrap/js/jquery.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadbanque.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadte2.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/loadcandidat.js"></script>

<script type="text/javascript">
 $(document).ready(function() {
	
	$('#integrateur_type').change(function(e) {
	    $.get('/index/montantbc',{
          integrateur_type : $(this).val()
        },
		function success(data)  {
			$('#integrateur_montant').val(parseInt(data,10));
		});
	});
	
	$('#integrateur_type').change(function(e) {
		if($('#integrateur_type').val() == 15 || $('#integrateur_type').val() == 16 || $('#integrateur_type').val() == 17 || $('#integrateur_type').val() == 18
		    || $('#integrateur_type').val() == 22 || $('#integrateur_type').val() == 29 || $('#integrateur_type').val() == 30) {
			$('#div_poste').css('display','block');
			$('#div_affiliation').css('display','block');
			$('#div_cursus').css('display','block');
			
		} else if($('#integrateur_type').val() == 19 || $('#integrateur_type').val() == 20) {
			$('#div_cursus').css('display','block');
			$('#div_poste').css('display','none');
			$('#div_affiliation').css('display','none');
		} else {
			$('#div_poste').css('display','none');
			$('#div_affiliation').css('display','none');
			$('#div_cursus').css('display','none');
		}
        e.preventDefault();
	});
	
	
	$('#type_souscription_cm').change(function(e) {
	    if($(this).val() == "BPS") {
			$('#div_banque').css('display','none');
			$('#div_bps').css('display','block');
			$('#code_banque').attr('required',false);
			$('#num_compte').attr('required',false);
			$('#bps_demande').attr('required',true);
			$('#delai_souscription').attr('required',true);
		} else {
			$('#div_banque').css('display','block');
			$('#div_bps').css('display','none');
			$('#code_banque').attr('required',true);
			$('#num_compte').attr('required',true);
			$('#bps_demande').attr('required',false);
			$('#delai_souscription').attr('required',false);
		}
    });
	
	
	$('#type_souscription_bc').change(function(e) {
	    if($(this).val() == "BPS") {
			$('#div_banque').css('display','none');
			$('#div_bps').css('display','block');
			$('#code_banque').attr('required',false);
			$('#num_compte').attr('required',false);
			$('#bps_demande').attr('required',true);
			$('#delai_souscription').attr('required',true);
		} 
		else {
			$('#div_banque').css('display','block');
			$('#div_bps').css('display','none');
			$('#code_banque').attr('required',true);
			$('#num_compte').attr('required',true);
			$('#bps_demande').attr('required',false);
			$('#delai_souscription').attr('required',false);
		}  
    });


    $('#id_pays').change(function(e) {      
    $.get('/index/listbanque',{
        id_pays : $(this).val()
    },
    function success(data)  {
        var options = '<option/>';
        for(var i = 0; i < data.length; i++) {
            options += '<option value="' + data[i][0] + '" >' + data[i][1] + ' </option>';
        }       
        $('select#code_banque').html(options);               
    });
        e.preventDefault();		 
    });

    });
	
	function souscrirekitsu()  {
	   $('#div_formation').css('display','none');
       $('#id_cycle_formation').attr("required",false);
       $('#div_kit').css('display','none');
	   $('#mont_bc').attr("required",false);	   
	}
	
	function souscrirekittech()  {
	   $('#div_formation').css('display','block');
	   $('#id_cycle_formation').attr("required",true);
	}
	
	function  findnokit()  {
	  $('#div_kit').css('display','none');
	  $('#mont_bc').attr("required",false);
	}
	
	function  findkit() {
	  if(document.getElementById('kit_1').checked) {
		$('#div_kit').css('display','block');
		$('#mont_bc').attr("required",true);
	  }
    }
	
	
</script>


<div class="well3">
<div class="row-fluid">
<div class="span12" style="text-align:left">

<?php 
    $titre = "";
    if($this->param == 1) {
	    $titre = "Intégrateurs (CMFH)";
    } elseif($this->param == 2) {
	    $titre = "Surveillance(CMFH)";
	} elseif($this->param == 3) {
		$titre = "Travailleurs de la Production Commune";
	} elseif($this->param == 4) {
		$titre = "Partenaires ODD";
	} elseif($this->param == 5) {
		$titre = "Intégrateurs(Utilisateurs)";
	}
  
?>

<blockquote><p><?php echo $titre." - Phase Souscription"; ?> </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addintegrateur">
      <?php if(isset($sessionmcnp->error) && $sessionmcnp->error != "") { ?>
      <div class="alert alert-error">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <?php echo $sessionmcnp->error; $sessionmcnp->error = ""; ?>
      </div>
      <?php } ?>
	  
	  <?php if(isset($this->error) && $this->error !="") { ?>
      <div class="alert alert-error">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <?php echo $this->error; ?>
      </div>
      <?php } ?>
	  
	  <fieldset>
	  
	  <legend> Code BAn </legend>
	  <div align="right"><a href="<?php echo $this->baseUrl(); ?>/index/addintegrationpre/param_int/<?php echo $this->param;  ?>">Formulaire de la Phase Pre-Souscription </a></div>
      <br/>
	  
	  <div class="control-group">
      <label class="control-label" for="code_BAn">Code BAn *</label>
      <div class="controls">
      <input name="code_BAn" type="text" id="code_BAn" placeholder="Entrer le Code BAn" required="required" />
	  <span id="nivban"><button type="button" class="btn btn-info" onclick="ouvre_bonachatneutres(document.getElementById('code_BAn').value, 'nivban');">Vérifier</button></span>
      <span class="help-block"><p class="text-error" style="color:red"> Veuillez saisir le Code BAn affiché lors de la souscription BAn </p></span>
      </div>
      </div>
	  
	  
	  <legend> Programme Souscription </legend>
	  <div class="control-group">
      <label class="control-label" for="programme"></label>
      <div class="controls">
      <label for="programme_cm" class="radio">
      <input name="programme" disabled  type="radio" id="programme_cm" value="CM" required 
	  onclick="document.getElementById('div_cm').style.display ='block'; document.getElementById('div_bc').style.display ='none'; document.getElementById('type_souscription_cm').required = true;document.getElementById('type_souscription_bc').required = false;" />
      Compte Marchand (CM)
      </label>

      <label for="programme_bc" class="radio">
      <input type="radio" name="programme" id="programme_bc" value="BC"  checked="checked" required  
	  onclick="document.getElementById('div_bc').style.display ='block';document.getElementById('div_cm').style.display ='none';document.getElementById('type_souscription_bc').required = true; document.getElementById('type_souscription_cm').required = false;" />
      Bon de Consommation (BC)
      </label>
      </div>
      </div>
	  
	  
	  <legend> Remplir les informations sur le Souscripteur </legend>
	  <div class="control-group">
	  <label class="control-label" for="liste"> Voudriez-vous souscrire à quel type de KIT ? *</label>
	  <div class="controls">
	  <label for="kit_0" class="radio">
      <input name="kit"  type="radio" id="kit_0" value="KITSU" checked="checked" required onclick="souscrirekitsu()"  />
      Kit de Solvabilité Universelle
      </label>

      <label for="kit_1" class="radio">
      <input type="radio" name="kit" id="kit_1" value="KITTECH" required onclick="souscrirekittech()" />
      Kit Technopole
      </label>
	  </div>
	  </div>
		
      <div class="control-group">
      <label class="control-label" for="liste"> Avez-vous une liste de bénéficiaires de votre souscription * </label>
      <div class="controls">
      <label for="liste_0" class="radio">
      <input name="liste"  type="radio" id="liste_0" value="SansListe" required onclick="findnokit()"  />
      Non
      </label>

      <label for="liste_1" class="radio">
      <input type="radio" name="liste" id="liste_1" value="AvecListe" required onclick="findkit()" />
      Oui
      </label>
      </div>
      </div>
	  
	  
	  
		
	  <div class="control-group">
             <label class="control-label" for="integrateur_membre"> Code membre * </label>
             <div class="controls">
                <input type="text" onblur="ouvre_loadte2(this.value,'nivo_te');" name="code_membre" id="code_membre" placeholder="Code Membre Souscripteur"  value="<?php echo $this->code_membre; ?>"  class="input-block-level"  readonly />
             </div>
      </div>
		
	  <div id="nivo_te">

      </div>
		
		
	  <div class="control-group">
      <label class="control-label" for="integrateur_type"> Type de postulat * </label>
      <div class="controls">
      <select  onchange="ouvre_loadcandidat(this.value, 'nivo_candidat');"  class="input-block-level" name="integrateur_type" id="integrateur_type" required="required">
      <?php  
	  $typeintegrateur2 = new Application_Model_EuTypeIntegrateurMapper();
	  $selecttypeintegrateur2 = "";
	  if($this->param == 1) {
	    $selecttypeintegrateur2 = $typeintegrateur2->fetchAllIntegrateur();
      } elseif($this->param == 2) {
	    $selecttypeintegrateur2 = $typeintegrateur2->fetchAllSurveillant();
	  } elseif($this->param == 3) {
		$selecttypeintegrateur2 = $typeintegrateur2->fetchAllTravailleur();
	  } elseif($this->param == 4) {
		$selecttypeintegrateur2 = $typeintegrateur2->fetchAllODD();
	  } elseif($this->param == 5) {
        $selecttypeintegrateur2 = $typeintegrateur2->fetchAllIntegrateur();
	  }
				 
	  ?>
      <option value="">Choisir un type</option>
	  <?php if($selecttypeintegrateur2 != "") { ?>
      <?php foreach ($selecttypeintegrateur2 as $selecttypeintegrateur): ?>
      <option value="<?php echo $selecttypeintegrateur->id_type_integrateur; ?>" <?php if($selecttypeintegrateur->id_type_integrateur == $this->id_type_integrateur){echo ' selected="selected"';}?>><?php echo ($selecttypeintegrateur->libelle_type_integrateur); ?></option>
      <?php endforeach; } ?>
      </select>
      </div>
      </div>
		
		<?php if(($this->param != 4) &&  ($this->param != 5)) { ?>
		<div id="nivo_candidat">
	    <div class="control-group">
	    <label class="control-label" for="souscription_type_candidat"> Type Souscripteur * </label>
	    <div class="controls">
		<select name="integrateur_type_candidat" id="integrateur_type_candidat" required="required" class="input-block-level">
	    <option value=""> Choisir un type de candidat </option>
		</select>
		</div>
	    </div>
		</div>
		<?php } ?>
	  
	    <div class="control-group">
        <label class="control-label" for="integrateur_montant"> Montant de la souscription * </label>
        <div class="controls">
             <input type="number" name="integrateur_montant" id="integrateur_montant" placeholder="Montant de la souscription"  value="<?php echo $this->integrateur_montant; ?>" class="input-block-level"  required="required" />
        </div>
        </div>
		
		
		<div class="control-group" id="div_cm"  style="display:none;">
            <label class="control-label" for="type_souscription_bc"> Type Souscription * </label>
            <div class="controls">
            <select name="type_souscription_cm" id="type_souscription_cm"  class="input-block-level" >
                <option value=""> Choisir un type de souscription </option>
                <option value="CAPS">Souscription pour Tiers de type CAPS</option>
                <option value="BPS">Souscription pour Tiers contre BPS</option>
            </select>
            </div>
        </div>
		
	    <div class="control-group" id="div_bc"  style="display:block;">
             <label class="control-label" for="type_souscription_bc"> Type Souscription * </label>
             <div class="controls">
             <select name="type_souscription_bc" id="type_souscription_bc"  class="input-block-level" >
                <option value=""> Choisir un type de souscription </option>
                <option value="CMIT">Souscription Marchande de type CMIT </option>
                <option value="CAPU">Souscription Marchande de type CAPU </option>
                <option value="CAIPC">Souscription Non Marchande de type CAIPC </option>
			    <option value="BPS">Souscription pour Tiers contre BPS</option>
             </select>
             </div>
        </div>
		
		
		<div class="control-group" id="div_bps"  style="display:none;">
		<div class="control-group">
             <label class="control-label" for="bps_demande">Bien, Produit ou Service à acquérir *</label>
             <div class="controls">
                  <textarea name="bps_demande" class="input-block-level" id="bps_demande" placeholder="" required></textarea>
             </div>
        </div>
		
		<div class="control-group">
        <label class="control-label" for="delai_souscription"> Nombre de périodes d'Acquisition *</label>
        <div class="controls">
             <input type="text" name="delai_souscription" id="delai_souscription" placeholder="Nombre de Périodes d'Acquisition du Bien,Produit ou Service" required class="input-block-level" />
        </div>
        </div>
		</div>
		
		<div class="control-group" id="div_formation"  style="display:none;">
        <label class="control-label" for="id_cycle_formation"> Cycle de formation * </label>
        <div class="controls">
             <select name="id_cycle_formation" id="id_cycle_formation" class="input-block-level" >
             <option value=""> Choisir un cycle de formation </option>
             <?php foreach ($this->formations as $value) { ?>
             <option
               value="<?php echo $value->id; ?>"><?php echo ucfirst(utf8_encode($value->nom_cycle_formation)); ?>
             </option>
             <?php } ?>
             </select>
        </div>
        </div>
		
		<div class="control-group" id="div_kit" style="display:none;">
		     <div class="control-group">
             <label class="control-label" for="mont_bc"> Montant du BC / période * </label>
             <div class="controls">
             <input type="text" name="mont_bc" id="mont_bc" placeholder="Montant du Bon de Consommation (BC) par Période"  class="input-block-level" />
             </div>
             </div>
		</div>
	  

        <div class="control-group">
        <label class="control-label" for="code_activite">Domaine d'activité *</label>
        <div class="controls">
        <select name="code_activite" id="code_activite" required onchange="ouvre_competences2(this.value);"  class="input-block-level" required="required">
        <?php $tactivite = new Application_Model_DbTable_EuActivite();
        $results = $tactivite->fetchAll();?>
        <option value="">Choisir le domaine </option>
        <?php foreach ($results as $activite): ?>
        <option value="<?php echo $activite->code_activite; ?>"  <?php if($activite->code_activite == $this->code_activite) {echo'selected="selected"';} ?> ><?php echo ($activite->nom_activite); ?></option>
        <?php endforeach; ?>
        </select>
        </div>
        </div>
	   
	   
	    <div id="niv2">
        <div class="control-group">
        <label class="control-label" for="id_metier">Métiers </label>
        <div class="controls">
        <select name="id_metier" id="id_metier" class="input-block-level">
        <option value="">Choisir le métier</option>
        </select>
        </div>
        </div>


        <div class="control-group">
        <label class="control-label" for="id_competence">Compétence </label>
        <div class="controls">
        <select name="id_competence" id="id_competence" class="input-block-level">
        <option value="">Choisir la compétence</option>
        </select>
        </div>
        </div>
        </div>
	   
	    <div class="control-group" id="div_poste"  style="display:none;">
	    <div class="control-group">
        <label class="control-label" for="integrateur_poste">Poste occupé </label>
        <div class="controls">
        <input type="text" name="integrateur_poste" id="integrateur_poste" placeholder="Poste occupé" class="input-block-level"  />
        </div>
        </div>
	    </div>
	   
	    <div class="control-group" id="div_affiliation"  style="display:none;">
	    <div class="control-group">
        <label class="control-label" for="integrateur_affiliation"> Affiliation à des associations/groupements professionnels   </label>
        <div class="controls">
        <textarea name="integrateur_affiliation" class="input-block-level" id="integrateur_affiliation" placeholder="Affiliation à des associations/groupements professionnels"></textarea>
        </div>
        </div>
		</div>
      
	    <div class="control-group" id="div_cursus"  style="display:none;">
	    <div class="control-group">
        <label class="control-label" for="integrateur_education"> Education / Formation / Cursus  </label>
        <div class="controls">
        <textarea name="integrateur_education" class="input-block-level" id="integrateur_education" placeholder="Education/Formation/Cursus" ></textarea>
        <span class="help-block">Indiquer les études universitaires et autres études spécialisées ainsi que les noms des institutions fréquentées, les diplômes obtenus et les dates auxquelles ils l’ont été</span>
        </div>
        </div>
	  
	    <div class="control-group">
        <label class="control-label" for="integrateur_formation">Autres formations   </label>
        <div class="controls">
        <textarea name="integrateur_formation" class="input-block-level" id="integrateur_formation" placeholder="Autres formations"></textarea>
        <span class="help-block">Indiquer toute autre formation reçue</span>
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="integrateur_langue">Langues </label>
        <div class="controls">
        <textarea name="integrateur_langue" class="input-block-level" id="integrateur_langue" placeholder="Langues" ></textarea>
        <span class="help-block">Indiquer pour chacune le degré de connaissance : bon, moyen, médiocre pour ce qui est de la langue parlée, lue et écrite</span>
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="integrateur_experience">Expérience professionnelle    </label>
        <div class="controls">
        <textarea name="integrateur_experience" class="input-block-level" id="integrateur_experience" placeholder="Expérience professionnelle"></textarea>
        <span class="help-block">En commençant par son poste actuel, donner la liste par ordre chronologique inverse de tous les emplois exercés  depuis la fin des études. Pour chaque emploi, donner les dates, le nom, le poste occupé et le nom, titre et téléphone de la personne de référence.</span>
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="integrateur_diplome">Dernier diplôme  </label>
        <div class="controls">
        <input type="file" name="integrateur_diplome" id="integrateur_diplome" class="input-block-level" />
        </div>
        </div>

        <div class="control-group">
        <label class="control-label" for="integrateur_document">Curriculum Vitae  </label>
        <div class="controls">
        <input type="file" name="integrateur_document" id="integrateur_document" class="input-block-level" />
        </div>
        </div>
	    </div>
	  
	    <div class="control-group">
        <label class="control-label" for="integrateur_attestation">Attestation  *  </label>
        <div class="controls">
        <label class="checkbox">
        <input name="integrateur_attestation" type="checkbox" id="integrateur_attestation" value="1" required /> Je, soussigné, certifie, en toute conscience, que les renseignements ci-dessus rendent fidèlement compte de ma situation, de mes qualifications et de mon expérience. J’accepte que toute fausse déclaration volontaire puisse entraîner ma disqualification de la présente procédure.
        </label>
        </div>
        </div>
        </fieldset>
	  
	    <div class="form-actions">
        <input name="publier" type="hidden" id="publier" value="0" />
        <input name="ok" type="hidden" id="ok" value="ok" />
        <button type="reset" class="btn">Annuler</button>
        <button type="submit" id="submit" class="btn btn-primary">Enregistrer</button>
        </div>
</form>

<script src="/qrcode-decoder/qcode-decoder.min.js"></script>
<script src="/outil-qr.js"></script>
<script type="text/javascript">
//outilqr('addeli');
outilqrformobligatoire("addintegrateur","submit");
</script>



</div>
<div class="span3">
<?php //include("../application/layouts/scripts/droite_esmc.phtml"); ?>
</div>
</div>
</div>