<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>
<?php 
if($this->param < 14){
$typecandidat = new Application_Model_EuTypeCandidat();
$typecandidatM = new Application_Model_EuTypeCandidatMapper();
$typecandidatM->find($this->param, $typecandidat);
$libelletypecandidat = $typecandidat->libelle_type_candidat;
}else if($this->param == 14){
$libelletypecandidat = "Personnes Physiques";
}else if($this->param == 15){
$libelletypecandidat = "Personnes Morales";
	}
?>
<script>
function nbremontantcmfh(type){
	if(type == 1 || type == 2 || type == 3 || type == 4 || type == 5 || type == 10 || type == 11){
		
			document.getElementById('nombre_mini').style.display='none';
			document.getElementById('mini').value = 500;
		
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 500 + 1;
			document.getElementById('souscription_montant').value = (500 * 2187.5) + 5000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 500 + 1;
			document.getElementById('souscription_montant').value = (500 * 2187.5) + 70000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}else{
			document.getElementById('souscription_nombre').value = 500;
			document.getElementById('souscription_montant').value = 500 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}	
	}else if(type == 6 || type == 7 || type == 12){
		
			document.getElementById('nombre_mini').style.display='none';
			document.getElementById('mini').value = 100;
		
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 100 + 1;
			document.getElementById('souscription_montant').value = (100 * 2187.5) + 5000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 100 + 1;
			document.getElementById('souscription_montant').value = (100 * 2187.5) + 70000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}else{
			document.getElementById('souscription_nombre').value = 100;
			document.getElementById('souscription_montant').value = 100 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}	
	}else if(type == 9){
		
			document.getElementById('nombre_mini').style.display='none';
			document.getElementById('mini').value = 10;
		
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 10 + 1;
			document.getElementById('souscription_montant').value = (10 * 2187.5) + 5000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 10 + 1;
			document.getElementById('souscription_montant').value = (10 * 2187.5) + 70000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}else{
			document.getElementById('souscription_nombre').value = 10;
			document.getElementById('souscription_montant').value = 10 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
		}	
	}else if(type == 8 || type == 13){
		
			document.getElementById('nombre_mini').style.display='block';
			document.getElementById('mini').value = 10;
		
		if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 10 + 1;
			document.getElementById('souscription_montant').value = (10 * 2187.5) + 5000;
		document.getElementById('souscription_nombre').readOnly = false;
		document.getElementById('souscription_montant').readOnly = false;
		}else if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome_1').checked == true){
			document.getElementById('souscription_nombre').value = 10 + 1;
			document.getElementById('souscription_montant').value = (10 * 2187.5) + 70000;
		document.getElementById('souscription_nombre').readOnly = false;
		document.getElementById('souscription_montant').readOnly = false;
		}else{
			document.getElementById('souscription_nombre').value = 10;
			document.getElementById('souscription_montant').value = 10 * 2187.5;
		document.getElementById('souscription_nombre').readOnly = false;
		document.getElementById('souscription_montant').readOnly = false;
		}	
	}
	}
	
function nbremontantkacm(){
	if(document.getElementById('souscription_personne_pp').checked == true && document.getElementById('souscription_autonome_1').checked == true){
		document.getElementById('souscription_nombre').value = 1;
		document.getElementById('souscription_montant').value = 5000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
	}
	if(document.getElementById('souscription_personne_pm').checked == true && document.getElementById('souscription_autonome_1').checked == true){
		document.getElementById('souscription_nombre').value = 1;
		document.getElementById('souscription_montant').value = 70000;
		document.getElementById('souscription_nombre').readOnly = true;
		document.getElementById('souscription_montant').readOnly = true;
	}
	}
	
function mobilisation() {
	if(document.getElementById('souscription_type_candidat').value == 8 && document.getElementById('souscription_personne_pp').checked == true) {
		document.getElementById('mobilisation').style.display = 'block';
		document.getElementById('souscription_mobilisateur_0').setAttribute('required', true);
		document.getElementById('souscription_mobilisateur_1').setAttribute('required', true);
	} else {
		document.getElementById('mobilisation').style.display = 'none';
		document.getElementById('souscription_mobilisateur_0').removeAttribute('required');
		document.getElementById('souscription_mobilisateur_1').removeAttribute('required');
	}
}
	
</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">


<blockquote><p>Formulaire de souscription : <?php echo $libelletypecandidat; ?></p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription">
  <?php if(isset($sessionmcnp->error) && $sessionmcnp->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->error; $sessionmcnp->error = ""; ?>
    </div>
  <?php } ?>
  
<fieldset>
<legend>Formulaire de souscription </legend>
<div align="right"><a href="<?php echo $this->baseUrl(); ?>/index/recherchesouscription">Recherche de souscription par numéro de banque ou de flooz </a> </div>
<div align="right"><a href="<?php echo $this->baseUrl(); ?>/index/addsouscriptioncomplement">Formulaire de complément de souscription </a> </div>

<div class="control-group">
  <label class="control-label" for="souscription_personne">Type du souscripteur *</label>
  <div class="controls">

  <label class="radio">
  <input name="souscription_personne" type="radio" id="souscription_personne_pp" value="PP" required onclick="
  document.getElementById('pp').style.display='block'; 
  document.getElementById('souscription_nom').setAttribute('required', true);
  document.getElementById('souscription_prenom').setAttribute('required', true);
  document.getElementById('pm').style.display='none';
  document.getElementById('souscription_raison').removeAttribute('required');
  document.getElementById('type_acteur').removeAttribute('required');
  document.getElementById('statut_juridique').removeAttribute('required');
  nbremontantkacm(); 
  nbremontantcmfh(document.getElementById('souscription_type_candidat').value);
  " <?php if($this->param == 15 || $this->param == 6 || $this->param == 7 || $this->param == 12 || $this->param == 13){?> disabled="disabled"<?php }?>>
  Personne Physique</label>
  
  <label class="radio">
  <input type="radio" name="souscription_personne" id="souscription_personne_pm" value="PM" required onclick="
  document.getElementById('pp').style.display='none'; 
  document.getElementById('souscription_nom').removeAttribute('required');
  document.getElementById('souscription_prenom').removeAttribute('required');
  document.getElementById('pm').style.display='block';
  document.getElementById('souscription_raison').setAttribute('required', true);
  document.getElementById('type_acteur').setAttribute('required', true);
  document.getElementById('statut_juridique').setAttribute('required', true);
  nbremontantkacm(); 
  nbremontantcmfh(document.getElementById('souscription_type_candidat').value);
  " <?php if($this->param == 14 || $this->param == 1 || $this->param == 2 || $this->param == 3 || $this->param == 4 || $this->param == 5 || $this->param == 8 || $this->param == 9 || $this->param == 10 || $this->param == 11){?> disabled="disabled"<?php }?>>
  Personne Morale</label>
  
</div>
</div>
  
<div class="control-group">
  <label class="control-label" for="souscription_autonome">Ancien Membre ou déjà souscris pour soi même *</label>
  <div class="controls">
  <label for="souscription_autonome_0" class="radio">
  <input name="souscription_autonome" type="radio" id="souscription_autonome_0" value="0" required onclick="
  nbremontantkacm();
  nbremontantcmfh(document.getElementById('souscription_type_candidat').value);
  " <?php if($this->param == 14 || $this->param == 15) { ?> disabled="disabled"<?php } ?> />
  Oui
  </label>
  <!--document.getElementById('membre').style.display='block'; 
  document.getElementById('souscription_membre').setAttribute('required', true);-->
  

  <label for="souscription_autonome_1" class="radio">
  <input type="radio" name="souscription_autonome" id="souscription_autonome_1" value="1" required onclick="
  nbremontantkacm(); 
  nbremontantcmfh(document.getElementById('souscription_type_candidat').value);
  " />
  Non
  </label>
  <!--document.getElementById('membre').style.display='none'; 
  document.getElementById('souscription_membre').removeAttribute('required');-->
  
  
  </div>
</div>

<!--<div id="membre" style="display:none">
<div class="control-group">
<label class="control-label" for="souscription_membre">Code membre du souscripteur * </label>
<div class="controls">
<input type="text" name="souscription_membre" id="souscription_membre" placeholder="Code Membre du souscripteur " class="input-xxlarge" required  />
</div>	 
</div>
</div>-->
  
<div id="pp" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_nom">Nom du souscripteur * </label>
<div class="controls">
<input type="text" name="souscription_nom" id="souscription_nom" placeholder="Nom du souscripteur " class="input-xxlarge"  />
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="souscription_prenom">Prénom du souscripteur * </label>
<div class="controls">
<input type="text" name="souscription_prenom" id="souscription_prenom" placeholder="Prénom du souscripteur " class="input-xxlarge"  />
</div>
</div>
</div>

<div id="pm" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_raison">Raison sociale du souscripteur * </label>
<div class="controls">
  <input type="text" name="souscription_raison" id="souscription_raison" placeholder="Raison sociale du souscripteur" class="input-xxlarge" />
</div>
</div>

<div class="control-group">
  <label class="control-label" for="type_acteur">Type Agrément OSE/OE *</label>
  <div class="controls">
  <select name="type_acteur" id="type_acteur" class="input-xxlarge" >
  <option value="">Choisir le type</option>
    <option value="EI">Entreprise Industrie</option>
    <option value="OE">Opérateur Economique</option>
    <option value="OSE">Opérateur Socio-Economique</option>
    <option value="PEI">Partenaire Entreprise Industrie</option>
    <option value="POE">Partenaire Opérateur Economique</option>
    <option value="POSE">Partenaire Opérateur Socio-Economique</option>
   </select>
</div>
</div>
  
<div class="control-group">
  <label class="control-label" for="statut_juridique">Statut juridique *</label>
  <div class="controls">
  <select  class="input-xxlarge" name="statut_juridique" id="statut_juridique" >
       <?php  $statutjuridique = new Application_Model_EuStatutJuridiqueMapper();
		$selectstatutjuridique = $statutjuridique->fetchAll();?>
               <option value="">Choisir un statut juridique</option>
    <?php foreach ($selectstatutjuridique as $selectstatutjuridique): ?>
               <option value="<?php echo $selectstatutjuridique->code_statut; ?>"><?php echo htmlentities($selectstatutjuridique->libelle_statut); ?></option>
    <?php endforeach; ?>
               </select>
  </div>
  </div>

</div>

<div class="control-group">
<label class="control-label" for="souscription_mobile">Cellulaire du souscripteur  *</label>
<div class="controls">
<input type="number" name="souscription_mobile" id="souscription_mobile" placeholder="Cellulaire du souscripteur" class="input-xxlarge" required />
</div>
</div>

<div class="control-group">
<label class="control-label" for="souscription_email">E-mail du souscripteur * </label>
<div class="controls">
<input type="email" name="souscription_email" id="souscription_email" placeholder="E-mail du souscripteur" class="input-xxlarge" required />
</div>
</div>


    
<div class="control-group">
<label class="control-label" for="souscription_ville">Ville du souscripteur  </label>
<div class="controls">
<input type="text" name="souscription_ville" id="souscription_ville" placeholder="Ville du souscripteur " class="input-xxlarge"  />
</div>
</div>
    
<div class="control-group">
<label class="control-label" for="souscription_quartier">Quartier du souscripteur  </label>
<div class="controls">
<input type="text" name="souscription_quartier" id="souscription_quartier" placeholder="Quartier du souscripteur " class="input-xxlarge"  />
</div>
</div>


<div class="control-group">
<label class="control-label" for="id_canton">R&eacute;gion du souscripteur  </label>
<div class="controls">
<select  class="input-xxlarge" name ="id_region" id="id_region" required onchange="ouvre_decoupage(this.value);">
     <?php  $region_mapper = new Application_Model_EuRegionMapper();
		    $selectregions = $region_mapper->fetchAll();?>
            <option value="">Choisir la région </option>
            <?php foreach ($selectregions as $selectregion): ?>
            <option value="<?php echo $selectregion->id_region; ?>"><?php echo $selectregion->nom_region; ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

<div id="nivpref">
<div class="control-group">
<label class="control-label" for="id_prefecture">Pr&eacute;fecture du souscripteur </label>
<div class="controls">
<select name="id_prefecture" id="id_prefecture"  class="input-xxlarge">
  <option value="">Choisir la Pr&eacute;fecture</option>
</select>
</div>
</div>
</div>


<div id="nivcant">
<div class="control-group">
<label class="control-label" for="id_canton">Canton du Souscripteur </label>
<div class="controls">
<select name="id_canton" id="id_canton"  class="input-xxlarge">
  <option value="">Choisir le canton </option>
</select>
</div>
</div>
</div>


<div class="control-group">
  <label class="control-label" for="souscription_programme">Type de programme *</label>
  <div class="controls">

  <label class="radio">
  <input name="souscription_programme" type="radio" required id="souscription_programme_kacm" value="KACM" onclick="
  document.getElementById('cmfh').style.display='none'; 
  document.getElementById('souscription_login').removeAttribute('required'); 
  document.getElementById('souscription_passe').removeAttribute('required'); 
  document.getElementById('confirme').removeAttribute('required'); 
  document.getElementById('souscription_type_candidat').removeAttribute('required'); 
  nbremontantkacm(); 
  nbremontantcmfh(document.getElementById('souscription_type_candidat').value);
  " <?php if($this->param == 1 || $this->param == 2 || $this->param == 3 || $this->param == 4 || $this->param == 5 || $this->param == 6 || $this->param == 7 || $this->param == 8 || $this->param == 9 || $this->param == 10 || $this->param == 11 || $this->param == 12 || $this->param == 13){?> disabled="disabled"<?php }?> />
  Souscription pour soi (KACM)</label>

  <!--<label for="souscription_programme_caps" class="radio">
  <input name="souscription_programme" type="radio" required id="souscription_programme_caps" value="CAPS" onclick="document.getElementById('cmfh').style.display='none';">
  CAPS</label>-->


  <label class="radio">
  <input name="souscription_programme" type="radio" required id="souscription_programme_cmfh" value="CMFH" onclick="
  document.getElementById('cmfh').style.display='block'; 
  document.getElementById('souscription_login').setAttribute('required', true); 	
  document.getElementById('souscription_passe').setAttribute('required', true); 
  document.getElementById('confirme').setAttribute('required', true); 
  document.getElementById('souscription_type_candidat').setAttribute('required', true); 	
  nbremontantkacm(); 
  nbremontantcmfh(document.getElementById('souscription_type_candidat').value);
  " <?php if($this->param == 14 || $this->param == 15){?> disabled="disabled"<?php }?> />
  Souscription pour tiers (CMFH)</label>
  
  </div>
  </div>
  
<div id="cmfh" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_type_candidat">Type CMFH *</label>
<div class="controls">
<select name="souscription_type_candidat" id="souscription_type_candidat" onchange="nbremontantcmfh(this.value); mobilisation();" >
    <?php $ttype_candidat = new Application_Model_EuTypeCandidatMapper();
if($this->param < 14){
    $results = $ttype_candidat->fetchAllByType($this->param);
	?>
    <?php foreach ($results as $type_candidat): ?>
    <option value="<?php echo $type_candidat->id_type_candidat; ?>"><?php echo ($type_candidat->libelle_type_candidat); ?> (<?php if($type_candidat->id_type_candidat == 8 || $type_candidat->id_type_candidat == 13){?>à partir de <?php }?><?php echo ($type_candidat->option_type_candidat); ?> Comptes Marchands)</option>
    <?php endforeach; ?>
<?php }else{?>
    <option value="0">Choisir le type</option>
<?php }?>
</select>
</div>
</div>




<div id="mobilisation" style="display:none;">
<div class="control-group">
  <label class="control-label" for="souscription_mobilisateur">Vous souhaitez être un Mobilisateur Sensibilisateur  *</label>
  <div class="controls">
  <label for="souscription_mobilisateur_0" class="radio">
  <input name="souscription_mobilisateur" type="radio" id="souscription_mobilisateur_0" value="0" checked="checked" />
  Non</label>

  <label for="souscription_mobilisateur_1" class="radio">
  <input type="radio" name="souscription_mobilisateur" id="souscription_mobilisateur_1" value="1" />
  Oui</label>
  
  </div>
  </div>
  </div>





<div class="control-group">
<label class="control-label" for="souscription_login">Login du souscripteur * </label>
<div class="controls">
  <input type="text" name="souscription_login" id="souscription_login" placeholder="Login du souscripteur" class="input-xxlarge" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="souscription_passe">Mot de passe du souscripteur  * </label>
<div class="controls">
  <input type="password" name="souscription_passe" id="souscription_passe" placeholder="Mot de passe du souscripteur" class="input-xxlarge" />
</div>
</div>

<div class="control-group">
<label class="control-label" for="confirme">Confirmer Mot de passe du souscripteur *  </label>
<div class="controls">
  <input type="password" name="confirme" id="confirme" placeholder="Confirmer Mot de passe du souscripteur" class="input-xxlarge" />
</div>
</div>

</div>

<?php /*?><div class="control-group">
<label class="control-label" for="souscription_filiere">Filière </label>
<div class="controls">
<select name="souscription_filiere" id="souscription_filiere" >
        <?php $tfiliere = new Application_Model_DbTable_EuFiliere();
        $results = $tfiliere->fetchAll();?>
  <option value="">Choisir la filière</option>
    <?php foreach ($results as $filiere): ?>
               <option value="<?php echo $filiere->id_filiere; ?>"><?php echo ($filiere->nom_filiere); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div><?php */?>

<div class="control-group">
<label class="control-label" for="code_activite">Domaine d'activité *</label>
<div class="controls">
<select name="code_activite" id="code_activite" required onchange="ouvre_competences(this.value);" class="input-xxlarge">
        <?php $tactivite = new Application_Model_DbTable_EuActivite();
        $results = $tactivite->fetchAll();?>
  <option value="">Choisir le domaine </option>
    <?php foreach ($results as $activite): ?>
               <option value="<?php echo $activite->code_activite; ?>"><?php echo ($activite->nom_activite); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>

<div id="niv2">

<div class="control-group">
<label class="control-label" for="id_metier">Métiers </label>
<div class="controls">
<select name="id_metier" id="id_metier"  class="input-xxlarge">
  <option value="">Choisir le métier</option>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="id_competence">Compétences </label>
<div class="controls">
<select name="id_competence" id="id_competence"  class="input-xxlarge">
  <option value="">Choisir la compétence</option>
</select>
</div>
</div>

</div>

<div class="control-group">
  <label class="control-label" for="souscription_type">Type de payement *</label>
  <div class="controls">
  <label for="souscription_type_banque" class="radio">
  <input name="souscription_type" type="radio" required id="souscription_type_banque" onclick="
  document.getElementById('banque').style.display='block';  
  document.getElementById('souscription_banque').setAttribute('required', true);
  document.getElementById('banque2').style.display='block'; 
  document.getElementById('souscription_vignette').setAttribute('required', true);
  document.getElementById('flooz').style.display='none';
  " value="Banque">
  Banque</label>

  <label for="souscription_type_flooz" class="radio">
  <input type="radio" name="souscription_type" id="souscription_type_flooz" value="Flooz" required onclick="
  document.getElementById('banque').style.display='none'; 
  document.getElementById('souscription_banque').removeAttribute('required');
  document.getElementById('banque2').style.display='none';  
  document.getElementById('souscription_vignette').removeAttribute('required');
  document.getElementById('flooz').style.display='block';
  ">
  Flooz</label>
  
  </div>
  </div>
  
  <div id="banque" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_banque">Banque *</label>
<div class="controls">
<select name="souscription_banque" id="souscription_banque"  class="input-xxlarge">
        <?php $tbanque = new Application_Model_DbTable_EuBanque();
        $results = $tbanque->fetchAll();?>
  <option value="">Choisir la banque</option>
    <?php foreach ($results as $banque): ?>
               <option value="<?php echo $banque->code_banque; ?>"><?php echo ($banque->libelle_banque); ?></option>
    <?php endforeach; ?>
</select>
</div>
</div>
</div>

  <div id="flooz" style="display:none;">
</div>

  <div class="control-group">
<label class="control-label" for="souscription_numero">Numéro de reçu de banque ou Numéro de transation Flooz  * </label>
<div class="controls">
  <input type="text" name="souscription_numero" id="souscription_numero" placeholder="Numero de reçu de banque ou Numéro de transation Flooz" class="input-xxlarge" required />
</div>
</div>


  <div class="control-group">
<label class="control-label" for="souscription_date_numero">Date de reçu de banque ou de transation Flooz  * </label>
<div class="controls">
  <input type="text" name="souscription_date_numero" id="souscription_date_numero" placeholder="Date de reçu de banque ou de transation Flooz" class="input-xxlarge datepicker" data-provide="datepicker" required />
<span class="help-block"><p class="text-error">Utiliser le calendier du champ pour choisir la date du reçu de banque ou de transation Flooz</p></span>
</div>
</div>

  <div id="banque2" style="display:none;">
<div class="control-group">
<label class="control-label" for="souscription_vignette">Scanne du reçu *  </label>
<div class="controls">
  <input type="file" name="souscription_vignette" id="souscription_vignette" class="input-xxlarge"  />
<span class="help-block"><p class="text-error">JPEG, JPG, PNG et PDF sont les extentions autorisées</p></span>
</div>
</div>
</div>

  <div class="control-group">
<label class="control-label" for="souscription_nombre">Nombre de compte marchand souscris * </label>
<div class="controls">
  <input type="text" name="souscription_nombre" id="souscription_nombre" placeholder="Nombre de compte marchand souscris" class="input-xxlarge" required />
<span class="help-block" id="nombre_mini" style="display:none;"><p class="text-error">Le nombre doit être supérieur à <script> document.writeln(document.getElementById('mini').value); </script></p></span>
</div>
</div>
  
  <div class="control-group">
<label class="control-label" for="souscription_montant">Montant de la souscription * </label>
<div class="controls">
  <input type="text" name="souscription_montant" id="souscription_montant" placeholder="Montant de la souscription" class="input-xxlarge" required />
</div>
</div>





</fieldset> 
   
    
    

<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn btn-large btn-block btn-info" data-toggle="modal">Enregistrer la souscription</a>
 
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><!-- style="width:800px; left: 30%;"-->
<!-- Modal -->
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 id="myModalLabel">Formulaire de souscription : <?php echo $libelletypecandidat; ?></h4>
  </div>
  <div class="modal-body" data-spy="scroll" data-target=".navbar">
    <h5>Cochez la mention « Je suis sûr des informations saisies » si c'est le cas.</h5>
<?php //require("contrat_compte_marchant.php"); ?>
<br />
<br />
  <label for="lu_et_approuve" class="checkbox">
  <input type="checkbox" name="lu_et_approuve" id="lu_et_approuve" value="1" required onclick="if(document.getElementById('lu_et_approuve').checked == true){
	document.getElementById('submit').disabled = false;
	}else{
	document.getElementById('submit').disabled = true;
		}">
  <strong>Je suis sûr des informations saisies</strong></label>

  </div>
  <div class="modal-footer">
<input name="ok" type="hidden" id="ok" value="ok" />
<input name="mini" type="hidden" id="mini" value="0" />
<button type="reset" class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
<button id="submit" type="submit" class="btn btn-primary" disabled>Enregistrer la souscription</button>
  </div>

</div>


<?php /*?><div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Enregistrer</button>
</div><?php */?>
 
                            
  
</form>





</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








