<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">
  <blockquote><p class="text-info">R&eacute;-activation  des ressources de Membres Fondateurs 11000 ( MF11000 )</p></blockquote>

<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="ancienpp">
  <?php if(isset($sessionmcnp->errorlogin) && $sessionmcnp->errorlogin!=""){?>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->errorlogin; $sessionmcnp->errorlogin = ""; ?>
    </div>
  <?php }?>
  <?php if(isset($this->message) && $this->message!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->message; ?>
    </div>
  <?php }?>
  <legend>Recherche par Num&eacute;ro Bon</legend>
  <div class="control-group">
  <label class="control-label" for="num_bon">Num&eacute;ro Bon *</label>
  <div class="controls">
  <input type="text" name="num_bon" id="num_bon" placeholder="Num&eacute;ro Bon" value="<?php echo $this->num_bon; ?>" required>
  </div>
  </div> 
<legend></legend>
<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<button type="reset" class="btn">Annuler</button>
<button type="submit" class="btn btn-primary">Rechercher</button>
</div>
</form>
</div>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








