<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>

<script type="text/javascript">

    function calculmontant(prk) {
	    var pck = document.getElementById('pck').value;
	    var taux = document.getElementById('tauxescompte').value;
	    var mont_msbcnr = document.getElementById('mont_msbcnr').value;
		
		var id_prk = document.getElementById('id_prk').value;
	    var parties = id_prk.split("-");
		
		var code_credit = parties[0];
		var prk = parties[1];
		//var prk = document.getElementById('id_prk').value;
	 
	    if(code_credit == "AG") {
			var mont_bc = Math.floor((mont_msbcnr * prk) / pck);
		} else {
	        var diviser = ((pck * 100) + (taux * pck))/100;
	        var mont_bc = Math.floor((prk * mont_msbcnr) / diviser); 
		}
	    document.getElementById('mont_bc').value = mont_bc
        document.getElementById('mont_bc').readOnly = true;
    }

    function annuler(montant) {
       document.getElementById('id_prk').value = "";
       document.getElementById('mont_bc').value = "";
    }

   /*
   function calculmontant(prk) {
	 var pck = document.getElementById('pck').value;
	 var prk = document.getElementById('id_prk').value;
	 var taux = document.getElementById('tauxescompte').value;
	 var mont_msbcnr = document.getElementById('mont_msbcnr').value;
	 
	 var diviser = ((pck * 100) + (taux * pck))/100;
	 var mont_bc = Math.round((prk * mont_msbcnr) / diviser); 
	 document.getElementById('mont_bc').value = mont_bc
     document.getElementById('mont_bc').readOnly = true;
   }

   function annuler(montant) {
     document.getElementById('id_prk').value = "";
     document.getElementById('mont_bc').value = "";
   } 
   
*/   
     
</script>


<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<blockquote><p>Calcul du Montant du Bon de Consommation Non Récurrente ( BCnr )</p></blockquote>
  <?php if(isset($sessionmcnp->error) && $sessionmcnp->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->error; $sessionmcnp->error = ""; ?>
    </div>
  <?php } ?>
  


<blockquote></blockquote>
<form  action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="" name="">

<fieldset>
<legend> Montant du Bon de Consommation Non Récurrente (MBCnr)  </legend>

<div class="control-group">
<label class="control-label" for="mont_msbcnr">Montant de Souscription au Bon de Consommation  *</label>
<div class="controls">
<input type="text" name="mont_msbcnr" id="mont_msbcnr" placeholder="Montant de Souscription au Bon de Consommation Non recurrente" class="input-xxlarge" onblur="annuler(this.value);"  required="required" />
</div>
</div>

<br/><br/>  
    
<div class="control-group">
<label class="control-label" for="">Produit à souscrire * </label>
<div class="controls">
     <select name="id_prk" id="id_prk" class="input-xxlarge" required="required" onchange="calculmontant(this.value);">
     <option value="">Choisir un produit </option>
     <?php foreach ($this->prks as $prk) { ?>
           <option value="<?php echo $prk->code_type_credit."-".$prk->prk;?>">  <?php echo ucfirst(utf8_encode($prk->lib_type_credit));?></option>
     <?php } ?>
     </select>
</div>
</div>

<br/><br/>

<div class="control-group">
<label class="control-label" for="bon_neutre_raison">Montant du Bon de Consommation *</label>
<div class="controls">
     <input type="text" name="mont_bc" id="mont_bc" placeholder="Montant du Bon de Consommation" class="input-xxlarge" />
</div>
</div>
</fieldset>

<div class="form-actions">
     <input name="ok" type="hidden" id="ok" value="ok" />
     <input  type="hidden"  name="tauxescompte"  id="tauxescompte"  placeholder="Taux Escompte"  readonly="true"  value="<?php echo $this->tauxescompte ; ?>" />
     <input  type="hidden"  name="pck"  id="pck"  placeholder="PCK"  readonly="true"  value="<?php echo $this->pck; ?>" />
     <button type="reset" class="btn">Annuler</button>
</div> 
</form>
</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








