<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>

<script type="text/javascript">
  function calculmontant() {
      if((document.getElementById('type_activation1').checked) && (document.getElementById('produit').value == "PO"))  {
         document.getElementById('mont_msbcm').value = Math.floor((document.getElementById('mont_bc').value * document.getElementById('bnpmpo').value));
      } else if((document.getElementById('type_activation2').checked) && (document.getElementById('produit').value == "PO")) {
         document.getElementById('mont_msbcm').value = Math.floor((document.getElementById('mont_bc').value * document.getElementById('bnpmpo').value));
      
      } else if((document.getElementById('type_activation1').checked) && (document.getElementById('produit').value == "PS")) {
         document.getElementById('mont_msbcm').value = Math.floor((document.getElementById('mont_bc').value * document.getElementById('bnpmpsfs').value));
      
      } else if((document.getElementById('type_activation2').checked) && (document.getElementById('produit').value == "PS")) {
         document.getElementById('mont_msbcm').value = Math.floor((document.getElementById('mont_bc').value * document.getElementById('bnpmps').value));
      
      }	  
  }

  function annuler() {
     document.getElementById('produit').value = "";
     document.getElementById('mont_msbcm').value = "";
	 document.getElementById('type_activation1').checked = true;
  }

  function annulation1() {
     document.getElementById('produit').value = "";
     document.getElementById('mont_msbcm').value = "";
  }

  function annulation2() {
     document.getElementById('produit').value = "";
     document.getElementById('mont_msbcm').value = "";
  }  
   

   
</script>


<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<blockquote><p>Calcul du Montant de Souscription Marchande au Bon de Consommation (BC) pour tiers</p></blockquote>
  <?php if(isset($sessionmcnp->error) && $sessionmcnp->error != "") { ?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->error; $sessionmcnp->error = ""; ?>
    </div>
  <?php } ?>
  
<blockquote></blockquote>
<form  action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="calculermsbcr" name="calculermsbcm">

<fieldset>

<legend> Montant de Souscription Marchande au Bon de Consommation (BC) pour tiers </legend>

<div class="control-group">
<label class="control-label" for="mont_bc">Montant du Bon de Consommation *</label>
<div class="controls">
<input type="text" name="mont_bc" id="mont_bc" placeholder="Montant du Bon de Consommation" class="input-xxlarge" onblur="annuler();"  required="required" />
</div>
</div>

<div class="control-group" id="type">
     <label class="control-label"></label>
	 <div class="controls">
                <input type="radio" checked="checked"  name="type_activation" id="type_activation1" value="avecfs"  
				 onclick="annulation1()" />
	        AVEC FS &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                  
		<input type="radio"  name="type_activation" id="type_activation2" value="sansfs" onclick="annulation2()" />
                SANS FS 			 
		   
     </div>
</div>

<br/><br/>

<div class="control-group">
<label class="control-label" for="produit">Produit à souscrire * </label>
<div class="controls">
     <select name="produit" id="produit" class="input-xxlarge" required="required" onchange="calculmontant();">
     <option value="">Choisir un produit </option>
     <?php foreach ($this->produits as $produit) { ?>
           <option value="<?php echo $produit->type_produit; ?>"> <?php echo $produit->lib_type_credit;?> </option>
     <?php } ?>
     </select>
</div>
</div>

<br/><br/>

<div class="control-group">
<label class="control-label" for="mont_msbcr">Montant à Souscrire *</label>
<div class="controls">
<input type="text" name="mont_msbcm" id="mont_msbcm" placeholder="Montant A Souscrire" class="input-xxlarge" readonly="true" />
<input  type="hidden"  name="bnpmpo"  id="bnpmpo"  placeholder="bnpmpo"  readonly="true"  value="<?php echo $this->bnpmpo; ?>" /> 
<input  type="hidden"  name="bnpmps"  id="bnpmps"  placeholder="bnpmps"  readonly="true"  value="<?php echo $this->bnpmps; ?>" />
<input  type="hidden"  name="bnpmpsfs"  id="bnpmpsfs"  placeholder="bnpmpsfs"  readonly="true"  value="<?php echo $this->bnpmpsfs; ?>" />
</div>
</div>

</fieldset>
<div class="form-actions">
<button type="reset" class="btn">Annuler</button>
</div>  
</form>
</div>

<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php /*?><?php */?>
</div>

</div>
</div>








