  <?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<style>
/* hardware accelatator class */  
  .trans3d
  {
    -webkit-transform-style: preserve-3d;
    -webkit-transform: translate3d(0, 0, 0);
    -moz-transform-style: preserve-3d;
    -moz-transform: translate3d(0, 0, 0);
    -ms-transform-style:preserve-3d;
    -ms-transform: translate3d(0, 0, 0);
    transform-style:preserve-3d;
    transform: translate3d(0, 0, 0);

    /*-webkit-backface-visibility: hidden;
    -moz-backface-visibility: hidden;
    -ms-backface-visibility:hidden;
    backface-visibility:hidden;*/
  }
  
  #contentContainer
  {
    position:absolute;
    margin-left:-500px;
    margin-top:-200px;
    left:50%;
    top:50%;
    width:1000px;
    height:400px;
    z-index:-10;
  }
  
  #carouselContainer
  {
    position:absolute;
    margin-left:-500px;
    margin-top:-200px;
    left:50%;
    top:50%;
    width:1000px;
    height:400px;
    z-index:-10;
  }
  
  .carouselItem
  {
    width:250px;
    height:130px;
    position:absolute;
    left:50%;
    top:50%;
    margin-left:-160px;
    margin-top:-90px;
    visibility:hidden;
  }
  
  .carouselItemInner
  {
    /*width:250px;
    height:130px;
    position:absolute;
    background-color:rgba(255, 255, 255, .75);
    border:10px solid rgba(255, 255, 255, .5);
    color:aqua;
    font-size:72px;
    left:50%;
    top:50%;
    margin-left:-160px;
    margin-top:-90px;
    text-align:center;
    padding-top:50px;*/
    
  }
    </style>

<div class="row">
    <div class="col-xl-12">
    <h3>Les Certificats</h3>
  <p class="lead">L'<span style="color:#7030A0; ">ESMC</span> (Entreprise Sociale de Marché Commun) est  concessionnaire d'un ensemble de 57 certificats et marques déposés auprès de  l'Organisation Africaine de Propriété Intellectuelle (OAPI). Ces certificats et  marques lui confèrent l'exclusivité d'exploitation dans leurs domaines  respectifs. </p>
  </div>
    

<div class="col-xl-12">



  <div id="contentContainer" class="trans3d"> 
  <section id="carouselContainer" class="trans3d">
<figure id="item1" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TCNCSRECTO.jpg" alt="TCNCS" /></figure>
<figure id="item2" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPAGCIRECTO.jpg" alt="TPAGCI" /></figure>
<figure id="item3" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPAGCpRECTO.jpg" alt="TPAGCp" /></figure>
<figure id="item4" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPAGCRPGRECTO.jpg" alt="TPAGCRPG" /></figure>
<figure id="item5" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPaNuRECTO.jpg" alt="TPaNu" /></figure>
<figure id="item6" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPaRRECTO.jpg" alt="TPaR" /></figure>
<figure id="item7" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TRRECTO.jpg" alt="TR" /></figure>
<figure id="item8" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TSMCIPNRECTO.jpg" alt="TSMCIPN" /></figure>

<figure id="item9" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TCNCSRECTO.jpg" alt="TCNCS" /></figure>
<figure id="item10" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPAGCIRECTO.jpg" alt="TPAGCI" /></figure>
<figure id="item11" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPAGCpRECTO.jpg" alt="TPAGCp" /></figure>
<figure id="item12" class="carouselItem trans3d"><img src="<?php echo $this->baseUrl();?>/cartes/TPAGCRPGRECTO.jpg" alt="TPAGCRPG" /></figure>  
  </section>
  </div>
  
  
  

<script>var __links = document.querySelectorAll('a');function __linkClick(e) { parent.window.postMessage(this.href, '*');} ;for (var i = 0, l = __links.length; i < l; i++) {if ( __links[i].getAttribute('data-t') == '_blank' ) { __links[i].addEventListener('click', __linkClick, false);}}</script>
<script src="<?php echo $this->baseUrl();?>/bootstrap/libs.min.js"></script>
<script>// set and cache variables
    var w, container, carousel, item, radius, itemLength, rY, ticker, fps; 
    var mouseX = 0;
    var mouseY = 0;
    var mouseZ = 0;
    var addX = 0;
    
    
    // fps counter created by: https://gist.github.com/sharkbrainguy/1156092,
    // no need to create my own :)
    var fps_counter = {
      
      tick: function () 
      {
        // this has to clone the array every tick so that
        // separate instances won't share state 
        this.times = this.times.concat(+new Date());
        var seconds, times = this.times;
        
        if (times.length > this.span + 1) 
        {
          times.shift(); // ditch the oldest time
          seconds = (times[times.length - 1] - times[0]) / 1000;
          return Math.round(this.span / seconds);
        } 
        else return null;
      },
 
      times: [],
      span: 20
    };
    var counter = Object.create(fps_counter);
    
    
    
    $(document).ready( init )
    
    function init()
    {
      w = $(window);
      container = $( '#contentContainer' );
      carousel = $( '#carouselContainer' );
      item = $( '.carouselItem' );
      itemLength = $( '.carouselItem' ).length;
      fps = $('#fps');
      rY = 360 / itemLength;
      radius = Math.round( (250) / Math.tan( Math.PI / itemLength ) );
      
      // set container 3d props
      TweenMax.set(container, {perspective:600})
      TweenMax.set(carousel, {z:-(radius)})
      
      // create carousel item props
      
      for ( var i = 0; i < itemLength; i++ )
      {
        var $item = item.eq(i);
        var $block = $item.find('.carouselItemInner');
        
        //thanks @chrisgannon!        
        TweenMax.set($item, {rotationY:rY * i, z:radius, transformOrigin:"50% 50% " + -radius + "px"});
        
        animateIn( $item, $block )            
      }
      
      // set mouse x and y props and looper ticker
      window.addEventListener( "mousemove", onMouseMove, false );
      ticker = setInterval( looper, 8000/60 );      
    }
    
    function animateIn( $item, $block )
    {
      var $nrX = 360 * getRandomInt(2);
      var $nrY = 360 * getRandomInt(2);
        
      var $nx = -(2000) + getRandomInt( 4000 )
      var $ny = -(2000) + getRandomInt( 4000 )
      var $nz = -4
      000 +  getRandomInt( 4000 )
        
      var $s = 1.5 + (getRandomInt( 10 ) * .1)
      var $d = 1 - (getRandomInt( 8 ) * .1)
      
      TweenMax.set( $item, { autoAlpha:1, delay:$d } )  
      TweenMax.set( $block, { z:$nz, rotationY:$nrY, rotationX:$nrX, x:$nx, y:$ny, autoAlpha:0} )
      TweenMax.to( $block, $s, { delay:$d, rotationY:0, rotationX:0, z:0,  ease:Expo.easeInOut} )
      TweenMax.to( $block, $s-.5, { delay:$d, x:0, y:0, autoAlpha:1, ease:Expo.easeInOut} )
    }
    
    function onMouseMove(event)
    {
      mouseX = -(-(window.innerWidth * .5) + event.pageX) * .0025;
      mouseY = -(-(window.innerHeight * .5) + event.pageY ) * .01;
      mouseZ = -(radius) - (Math.abs(-(window.innerHeight * .5) + event.pageY ) - 200);
    }
    
    // loops and sets the carousel 3d properties
    function looper()
    {
      addX += mouseX
      TweenMax.to( carousel, 1, { rotationY:addX, rotationX:mouseY, ease:Quint.easeOut } )
      TweenMax.set( carousel, {z:mouseZ } )
      fps.text( 'Framerate: ' + counter.tick() + '/60 FPS' )  
    }
    
    function getRandomInt( $n )
    {
      return Math.floor((Math.random()*$n)+1);  
    }//@ sourceURL=pen.js
</script>

</div>

  </div>

