<?php $sessionmcnp = new Zend_Session_Namespace('mcnp'); ?>

<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/competences.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/decoupage1.js"></script>
<script language="javascript1.3" src="<?php echo $this->baseUrl();?>/bsics.js"></script>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js"></script>


<script type="text/javascript" charset="utf-8">		
	$(document).ready(function() {
        $('#example').dataTable({
            "sPaginationType": "full_numbers",
            "aaSorting": []
        });
    });
</script>


<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

<blockquote><p> Liste des postulants </p></blockquote>

<div class="accordion" id="accordion2">
    <div class="accordion-group">
    <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
            Formulaire de trie par critères
        </a>
    </div>
	
	<div id="collapseOne">
	    <div class="accordion-inner">
		    <form method="post" enctype="multipart/form-data" role="form" name="postulat" id="postulat" action="" class="">
			    <div class="">
				    <div class="span4">
			            <div class="control-group">
                        <label class="control-label"> Catégorie </label>
                        <div class="controls">
                        <select  id="id_type_candidat" name="id_type_candidat">
                        <option value="">Choisir une catégorie </option>
                        <?php foreach ($this->candidats as $value) { ?>
                        <option
                        value="<?php echo $value->id_type_candidat; ?>"><?php echo $value->libelle_type_candidat; ?>
						</option>                         
                        <?php } ?>
                        </select>
                        </div>
                        </div>
						
						<div class="control-group">
                        <label class="control-label"> Région </label>
                        <div class="controls">
                        <select  id="id_region" name="id_region">
                        <option value="">Choisir une région </option>
                        <?php foreach ($this->regions as $value) { ?>
                        <option
                        value="<?php echo $value->id_region; ?>"><?php echo $value->nom_region; ?>
						</option>                         
                        <?php } ?>
                        </select>
                        </div>
                        </div>
						
						
			        </div>
					
					<div class="span4">
					    <div class="control-group">
                        <label class="control-label"> Zone M.</label>
                        <div class="controls">
                        <select class="input-block-level" id="code_zone" name="code_zone">
                        <option value="">Choisir une zone monétaire</option>
                        <?php foreach ($this->zones as $value) { ?>
                        <option
                        value="<?php echo $value->code_zone; ?>"><?php echo $value->nom_zone; ?>
						</option>                         
                        <?php } ?>
                        </select>
                        </div>
                        </div>
						
						
						<div class="control-group">
                        <label class="control-label"> Préfecture </label>
                        <div class="controls">
                        <select class="input-block-level" id="id_prefecture" name="id_prefecture">
                        <option value="">Choisir une préfecture </option>
                        <?php foreach ($this->prefectures as $value) { ?>
                        <option
                        value="<?php echo $value->id_prefecture; ?>"><?php echo $value->nom_prefecture; ?>
						</option>                         
                        <?php } ?>
                        </select>
                        </div>
                        </div>
						
						
					</div>
					
					<div class="span4">
					    <div class="control-group">
                        <label class="control-label"> Pays </label>
                        <div class="controls">
                        <select class="input-block-level" id="id_pays" name="id_pays">
                        <option value="">Choisir un pays</option>
                        <?php foreach ($this->pays as $value) { ?>
                        <option
                        value="<?php echo $value->id_pays; ?>"><?php echo $value->libelle_pays; ?>
						</option>                         
                        <?php } ?>
                        </select>
                        </div>
                        </div>
						
						
						<div class="control-group">
                        <label class="control-label"> Canton </label>
                        <div class="controls">
                        <select class="input-block-level" id="id_canton" name="id_canton">
                        <option value="">Choisir un canton </option>
                        <?php foreach ($this->cantons as $value) { ?>
                        <option
                        value="<?php echo $value->id_canton; ?>"><?php echo $value->nom_canton; ?>
						</option>                         
                        <?php } ?>
                        </select>
                        </div>
                        </div>	
					</div>
		        </div>
				
				<div class="">
                <div class="span12">
                <div class="form-actions">
                <input name="ok" type="hidden" id="ok" value="ok" />
                <button type="submit" class="btn btn-primary">Rechercher</button>
                </div>    
                </div>
                </div>
            </form>
		</div>
	</div>	
    </div>
</div>

<BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/><BR/>



<?php if(count($this->entries) > 0) { ?>
<table class="table table-striped table-bordered table-hover table-condensed" id="example" style="font-size:12px;">
    <thead>
		<tr>
			<th>Postulat</th>
			<th>Date</th>
			<th>Nom & prénom(s) / Raison sociale</th>
			<th>Cellulaire</th>
			<th>Zone</th>
			<th>Pays</th>
			<th>Région</th>
			<th>Préfecture</th>
			<th>Canton</th>
		</tr>
	</thead>
	
	
	<tbody>
	    <?php foreach ($this->entries as $entry): ?>
		<tr>
	    <td><?php echo ($entry->libelle_type_candidat); ?></td>
		<td><?php echo datejourfr($entry->date_postulat); ?></td>
		<td><?php echo ($entry->nom_postulat)." ".($entry->prenom_postulat); ?></td>
		<td><?php echo ($entry->mobile_postulat); ?></td>
		<td><?php echo ($entry->nom_zone); ?></td>
		<td><?php echo ($entry->libelle_pays); ?></td>
		<td><?php echo ($entry->nom_region); ?></td>
		<td><?php echo ($entry->nom_prefecture); ?></td>
		<td><?php echo ($entry->nom_canton); ?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
	
</table>

<?php } else { ?>
<div class="alert alert-info">
  Aucun postulat enrégistré 
</div>
<?php } ?>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?>
</div>
</div>
</div>
       










