<div class="col-xl-12" style="margin-bottom:20px">
  
  <div class="col-xl-2" style="display:inline-block">

    <span style="display: inline-block;background-color: #aa325f;color: #FFF;width: 102px;height: 66px;text-align: center;line-height: 60px;border-radius:5px;-webkit-border-radius:5px;-moz-border-radius:5px;-o-border-radius:5px;text-shadow:-1px 2px 1px">
    
       <span style="font-size: 2rem;font-weight:block">OBPS</span></span>  
    
    </span>
  
  </div>

  <div class="col-xl-9" style="display:inline-block">
   
     <a href="/index/acteurcreneau">
     
           <span style="display:block;font-size:1.4rem;color:#aa325f">Offreurs de Biens Produits & Services</span>

      </a>

  </div>

</div>

<div class="col-xl-12" style="margin-bottom:20px">
  
  <div class="col-xl-2" style="display:inline-block">

    <span style="display: inline-block;background-color: #aa325f;color: #FFF;width: 102px;height: 66px;text-align: center;line-height: 60px;border-radius:5px;-webkit-border-radius:5px;-moz-border-radius:5px;-o-border-radius:5px;text-shadow:-1px 2px 1px">
    
       <span style="font-size: 2rem;font-weight:block">OBPSD</span> <span style="font-size:1.4rem"></span>  
    
    </span>
  
  </div>

  <div class="col-xl-9" style="display:inline-block">
   
     <a href="/guichets/listedesfranchiseszonesmonetaires/searchkeyfranchises">
     
           <span style="display:block;font-size:1.4rem;color:#aa325f">Offreurs de Biens Produits & Services Dématérialisés</span>

      </a>

  </div>

</div>