<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">
  <blockquote><p class="text-info">Espace KACM (enrôlement et mise sur chaîne)</p>
  <small>Les Partenaires Bancaires et Financiers, les Distributeurs de codes SMS</small></blockquote>








</div>
<div class="span3">
	<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








