<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>

<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen" />

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

	<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">

  <blockquote><p>Recherche de souscription par numéro de banque ou de flooz </p></blockquote>
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="addsouscription">

  <?php if(isset($sessionmcnp->error) && $sessionmcnp->error != ""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->error; $sessionmcnp->error = ""; ?>
    </div>
  <?php }?>
  
  
 <div class="control-group">
<label class="control-label" for="souscription_numero">Numéro de reçu de banque ou Numéro de transation Flooz  </label>
<div class="controls">
<input type="text" name="souscription_numero" id="souscription_numero" placeholder="Numéro de reçu de banque ou Numéro de transation Flooz " class="input-xlarge" <?php if(isset($_POST['souscription_numero']) && $_POST['souscription_numero'] != ""){?> value="<?php echo $_POST['souscription_numero']; ?>"<?php }?>  />
</div>
</div> 
  
  
<div class="form-actions">

<input name="ok" type="hidden" id="ok" value="ok" />
<button type="submit" class="btn btn-primary">Rechercher</button>
</div>

</form>


<?php if(isset($this->souscription) && count($this->souscription)>0){?> 
  <blockquote><p>Résultats </p></blockquote>

<table class="table table-striped table-bordered table-hover table-condensed"><!-- id="example"-->
						  <thead>
							  <tr>
								  <th>Date</th>
								  <th>Type</th>
								  <th>Banque</th>
								  <th>Numero</th>
								  <th>Personne</th>
								  <th>Programme</th>
								  <th>Nombre</th>
								  <th>Montant</th>
								  <th>Actions</th>
							  </tr>
						  </thead>  
                    <tbody>
<?php //foreach ($this->entries as $entry): ?>
<?php 
        $relevebancairedetailM = new Application_Model_EuRelevebancairedetailMapper();
        if($relevebancairedetail = $relevebancairedetailM->fetchAllByBanqueNumeroDate($this->souscription->souscription_banque, $this->souscription->souscription_numero, $this->souscription->souscription_date_numero)){
	  $ok = 1; }else{$ok = 0; }?>
    <tr <?php if($ok == 1){?> class="success"<?php }?>>
      <td><?php echo datefr3($this->souscription->souscription_date_numero); ?></td>
      <td><?php echo ($this->souscription->souscription_type); ?></td>
      <td><?php echo ($this->souscription->souscription_banque); ?></td>
      <td><?php echo ($this->souscription->souscription_numero); ?></td>
      <td><?php echo ($this->souscription->souscription_personne); ?></td>
      <td><?php echo ($this->souscription->souscription_programme); ?></td>
      <td><?php echo ($this->souscription->souscription_nombre); ?></td>
      <td><?php echo ($this->souscription->souscription_montant); ?></td>
      <td><div align="center"><?php if($ok == 1){?><span class="badge badge-success"><i class="icon-ok icon-white"></i>Vérifié</span><?php }else{?><span class="badge badge-important"><i class="icon-off icon-white"></i>Non vérifie</span><?php }?>
      </div></td>
      
    </tr>
<?php //endforeach; ?>
</tbody>
					  </table>
<?php }else{?>
<div class="alert alert-info">
  Aucun resultat enrégistré 
</div>
<?php }?>


<br />
<br />
<br />
<br />


</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite_esmc.phtml"); ?><?php /*?><?php */?>
</div>
</div>
</div>








