<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
$(document).ready(function() {
 $('#example').dataTable({
     "sPaginationType": "full_numbers",
     "aaSorting": []
  });
});
</script>

<div class="well3">
<div class="row-fluid">

<div class="span9" style="text-align:left">
<blockquote><p class="text-info">Faire le recouvrement des credits RPG/I</p></blockquote>

<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="ancienpp">
    <?php if(isset($sessionmcnp->errorlogin) && $sessionmcnp->errorlogin!="") { ?>
    <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <?php echo $sessionmcnp->errorlogin; $sessionmcnp->errorlogin = ""; ?>
    </div>
      <?php } ?>
      <?php if(isset($this->message) && $this->message!="") { ?>
      <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <?php echo $this->message; ?>
      </div>
    <?php } ?>
	
	<legend>Faire le recouvrement des credits RPG/I</legend>
	<div class="control-group">
	<?php if (isset($_POST['code_membre']) && $_POST['code_membre']!="") { 
	 $x =1;
         $compteur=0;
	?>
	<label class="control-label" for="code_membre">Ancien Code Membre *</label>
        <div class="controls">
        <input type="text" name="code_membre" id="code_membre" placeholder="Ancien Code Membre" value="<?php echo $this->code_membre; ?>" readonly required>
	</div>
    <br/>
    <br/>	
	<table class="table table-striped table-bordered table-hover table-condensed" id="example">
	    <thead>
            <tr>
			        <th>#</th>
                                <th><div align="left">Id</div></th>
				<th><div align="left">Produit</div></th>
				<th><div align="left">Origine ressource</div></th>
				<th><div align="left">Montant CAPA</div></th>
				<th><div align="left">Montant Crédit</div></th>
			</tr>
	    </thead>
	    <tbody>
	        <?php foreach ($this->credits as $entry): ?>
			<tr>
			    <td><div>
                            <input type="checkbox" name="<?php echo "credit".$x ?>" id="<?php echo "credit".$x ?>" value="<?php echo $entry->id_credit;?>"/>
                            
                            </div></td>
                            <td><div align="left"><?php echo $entry->id_credit;?></div></td>
			    <td><div align="left"><?php echo $entry->code_produit;?></div></td>
				<td><div align="left"><?php echo $entry->compte_source;?></div></td>
				<td><div align="left"><strong><?php echo number_format($entry->montant_place,0,',',' ');?></strong></div></td>
				<td><div align="left"><strong><?php echo number_format($entry->montant_credit,0,',',' ');?></strong></div></td> 
			</tr>
			<?php 
			     $x++;$compteur++;endforeach; 
			?>
			<tr>
			   <td colspan="6">
		           <div align="center">
                           <input type="hidden" name="compteur" value="<?php echo $compteur ?>"/>
                           <input name="ok1" type="hidden" id="ok1" value="ok1"/>
                           <button type="submit" class="btn btn-success">Recouvrer</button>
		           </div>
			   </td>   
		   	</tr>	 
			
	    </tbody>
	</table>
	<?php } else { ?>
        <label class="control-label" for="code_membre">Ancien Code Membre *</label>
             <div class="controls">
             <input  type="text"   name="code_membre" id="code_membre" placeholder="Ancien Code Membre" value="<?php echo $this->code_membre; ?>" required>
             <input  name="ok"     type="hidden" id="ok" value="ok" />
             <button type="submit" class="btn btn-primary">Valider</button>
             </div>
	<?php } ?>	
		
    </div>
</form>
</div>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








