<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">
  <blockquote><p class="text-info">Relevé des unités MF11000 Ancien Membre Personne Morale</p></blockquote>

<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="ancienpp">
  <?php if(isset($sessionmcnp->errorlogin) && $sessionmcnp->errorlogin!=""){?>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->errorlogin; $sessionmcnp->errorlogin = ""; ?>
    </div>
  <?php }?>
  <?php if(isset($this->message) && $this->message!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->message; ?>
    </div>
  <?php }?>
  
  <legend>Relevé des unités MF11000 Ancien Membre Personne Morale</legend>
  
  
  <div class="control-group">
  <label class="control-label" for="code_membre">Ancien Code Membre CYBER *</label>
  <div class="controls">
  <input type="text" name="code_membre" id="code_membre" placeholder="Ancien Code Membre CYBER" value="<?php echo $this->code_membre; ?>" required>

<input name="ok" type="hidden" id="ok" value="ok" />
<!--<button type="reset" class="btn">Annuler</button>-->
<button type="submit" class="btn btn-primary">Afficher le relevé</button>
<?php if (isset($_POST['code_membre']) && $_POST['code_membre']!="" && ($this->relevedeja == 0)) {?>
<a target="_blank" class="btn btn-danger" href="<?php echo $this->baseUrl(); ?>/index/relevemf11000pmpdf/code/<?php echo $_POST['code_membre']; ?>">Générer le PDF du relevé</a>
<?php }else if($this->relevedeja == 1){?>
<span class="alert alert-success">Relevé déja demandé</span>
<?php }?>
  </div>
  </div>
  

</form>

<?php 
  if (isset($_POST['ok']) && $_POST['ok']=="ok") {
  if (isset($_POST['code_membre']) && $_POST['code_membre']!="") {
?>

  <blockquote>Récapitulatif</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th><div align="right">Total Unité MF11000 reçu</div></th>
            <th><div align="right">Total Unité MF11000 vendu</div></th>
            <th><div align="right">Total Unité MF11000 restant</div></th>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td><div align="right"><strong><?php echo number_format($this->mf11000_recu,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($this->mf11000_vendu,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($this->mf11000_restant,0,',',' ');?></strong></div></td>
        </tr>
    </tbody>
</table>


<br />
<br />


  <blockquote>Détails MF11000</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
    <thead>
        <tr>
            <!--<th><div align="left"></div></th>-->
            <th><div align="left">Numero Bon / Code membre</div></th>
            <th><div align="center">Ressource</div></th>
            <th><div align="right">Montant reçu</div></th>
            <th><div align="right">Montant vendu</div></th>
            <th><div align="right">Solde</div></th>
        </tr>
    </thead>
    <tbody>
    <?php 
			   $tot_entrees = 0;
			   $tot_sorties = 0;
			   $tot_solde = 0;
	?>
<?php foreach ($this->detailmf11000 as $entry): ?>
<?php 
		        if($entry->num_bon == null) {
				  $numero = $entry->code_membre;
			    } else {
			      $numero = $entry->num_bon;
			    }
?>
        <tr>
          <?php /*?><td><div align="left"><?php echo $entry->id_detail_smsmoney;?></div></td><?php */?>
          <td><div align="left"><?php echo $numero;?></div></td>
          <td><div align="center"><?php echo $entry->origine_sms.'11000';?></div></td>
          <td><div align="right"><strong><?php echo number_format($entry->mont_sms,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($entry->mont_vendu,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($entry->solde_sms,0,',',' ');?></strong></div></td>
        </tr>
    <?php 
			    $tot_entrees += $entry->mont_sms;
			    $tot_sorties += $entry->mont_vendu;
			    $tot_solde += $entry->solde_sms;
	?>
<?php endforeach; ?>
        <tr>
          <?php /*?><td><div align="left">&nbsp;</div></td><?php */?>
          <td><div align="left">&nbsp;</div></td>
          <td><div align="right"><strong>Total</strong></div></td>
          <td><div align="right"><strong><?php echo number_format($tot_entrees,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($tot_sorties,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($tot_solde,0,',',' ');?></strong></div></td>
        </tr>
    </tbody>
</table>



<br />
<br />
&nbsp;

<?php }?>
<?php }?>
</div>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








