<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
    $('#example2').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
    $('#example3').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">
  <blockquote><p class="text-info">Relevé Salaire CNCS Ancien Membre</p></blockquote>

<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="ancienpp">
  <?php if(isset($sessionmcnp->errorlogin) && $sessionmcnp->errorlogin!=""){?>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->errorlogin; $sessionmcnp->errorlogin = ""; ?>
    </div>
  <?php }?>
  <?php if(isset($this->message) && $this->message!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->message; ?>
    </div>
  <?php }?>
  
  <legend>Relevé Salaire CNCS Ancien Membre</legend>
  
  
  <div class="control-group">
  <label class="control-label" for="code_membre">Ancien Code Membre *</label>
  <div class="controls">
  <input type="text" name="code_membre" id="code_membre" placeholder="Ancien Code Membre" value="<?php echo $this->code_membre; ?>" required>

<input name="ok" type="hidden" id="ok" value="ok" />
<!--<button type="reset" class="btn">Annuler</button>-->
<button type="submit" class="btn btn-primary">Afficher le relevé</button>
<?php if (isset($_POST['code_membre']) && $_POST['code_membre']!="" && ($this->relevedeja == 0)) {?>
<a target="_blank" class="btn btn-danger" href="<?php echo $this->baseUrl(); ?>/index/relevesalairepdf/code/<?php echo $_POST['code_membre']; ?>">Générer le PDF du relevé</a>
<?php }else if($this->relevedeja == 1){?>
<span class="alert alert-success">Relevé déja demandé</span>
<?php }?>
  </div>
  </div>
  

</form>

<?php 
  if (isset($_POST['ok']) && $_POST['ok']=="ok") {
  if (isset($_POST['code_membre']) && $_POST['code_membre']!="") {
?>

  <blockquote>Récapitulatif</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th><div align="right">CNCS Global</div></th>
            <th><div align="right">CNCS Escompté</div></th>
            <th><div align="right">CNCS Echangé</div></th>
            <!--<th><div align="right">CNCS Non Mature</div></th>-->
            <th><div align="right">Solde CNCS</div></th>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td><div align="right"><strong><?php echo number_format($this->cncs,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($this->escompte,0,',',' ');?></strong></div></td>
          <td><div align="right"><strong><?php echo number_format($this->echange,0,',',' ');?></strong></div></td>
          <?php /*?><td><div align="right"><strong><?php echo number_format($this->soldenr,0,',',' ');?></strong></div></td><?php */?>
          <td><div align="right"><strong><?php echo number_format($this->soldenn,0,',',' ');?></strong></div></td>
        </tr>
    </tbody>
</table>


<br />
<br />


  <blockquote>Détails salaires affectés</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed" id="example">
    <thead>
        <tr>
            <!--<th><div align="left">Crédit</div></th>-->
            <th><div align="left">Compte origine</div></th>
            <th><div align="center">Produit</div></th>
            <th><div align="right">Montant</div></th>
            <th><div align="center">Date</div></th>
        </tr>
    </thead>
    <tbody>
    <?php $montant = 0;?>
<?php foreach ($this->detailsalaire as $entry): ?>
        <tr>
          <?php /*?><td><div align="left"><?php echo $entry->id_credit;?></div></td><?php */?>
          <td><div align="left"><?php echo $entry->compte_source;?></div></td>
          <td><div align="center"><?php echo $entry->code_produit;?></div></td>
          <td><div align="right"><strong><?php echo number_format($entry->montant_place,0,',',' ');?></strong></div></td>
          <?php $date_op = new Zend_Date($entry->date_octroi, Zend_Date::ISO_8601);?>
          <td><div align="center"><?php echo $date_op->toString('dd/MM/yyyy');?></div></td>
        </tr>
    <?php $montant += $entry->montant_place;?>
<?php endforeach; ?>
        <tr>
          <?php /*?><td><div align="left">&nbsp;</div></td><?php */?>
          <td><div align="left">&nbsp;</div></td>
          <td><div align="right"><strong>Total</strong></div></td>
          <td><div align="right"><strong><?php echo number_format($montant,0,',',' ');?></strong></div></td>
          <td><div align="center">&nbsp;</div></td>
        </tr>
    </tbody>
</table>



<br />
<br />


  <blockquote>Détails salaires escomptés</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed" id="example2">
    <thead>
        <tr>
            <!--<th><div align="left">Echange</div></th>-->
            <th><div align="center">Produit</div></th>
            <th><div align="left">Compte Destinataire</div></th>
            <th><div align="right">Montant</div></th>
            <th><div align="center">Date</div></th>
        </tr>
    </thead>
    <tbody>
    <?php $montant = 0;?>
<?php foreach ($this->escomptesalaire as $entry): ?>
        <tr>
          <?php /*?><td><div align="left"><?php echo $entry->id_echange;?></div></td><?php */?>
          <td><div align="center"><?php echo $entry->cat_echange;?></div></td>
          <td><div align="left"><?php echo $entry->code_compte_obt;?></div></td>
          <td><div align="right"><strong><?php echo number_format($entry->montant,0,',',' ');?></strong></div></td>
          <?php $date_op = new Zend_Date($entry->date_echange, Zend_Date::ISO_8601);?>
          <td><div align="center"><?php echo $date_op->toString('dd/MM/yyyy');?></div></td>
        </tr>
    <?php $montant += $entry->montant;?>
<?php endforeach; ?>
        <tr>
          <?php /*?><td><div align="left">&nbsp;</div></td><?php */?>
          <td><div align="left">&nbsp;</div></td>
          <td><div align="right"><strong>Total</strong></div></td>
          <td><div align="right"><strong><?php echo number_format($montant,0,',',' ');?></strong></div></td>
          <td><div align="center">&nbsp;</div></td>
        </tr>
    </tbody>
</table>





<br />
<br />


  <blockquote>Détails salaires échangés</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed" id="example3">
    <thead>
        <tr>
            <!--<th><div align="left">Echange</div></th>-->
            <th><div align="left">Compte origine</div></th>
            <th><div align="left">Compte Destinataire</div></th>
            <th><div align="right">Montant</div></th>
            <th><div align="center">Date</div></th>
        </tr>
    </thead>
    <tbody>
    <?php $montant = 0;?>
<?php foreach ($this->echangesalaire as $entry): ?>
        <tr>
          <?php /*?><td><div align="left"><?php echo $entry->id_credit;?></div></td><?php */?>
          <td><div align="left"><?php echo $entry->compte_source;?></div></td>
          <td><div align="left"><?php echo $entry->code_compte;?></div></td>
          <td><div align="right"><strong><?php echo number_format($entry->montant_place,0,',',' ');?></strong></div></td>
          <?php $date_op = new Zend_Date($entry->date_octroi, Zend_Date::ISO_8601);?>
          <td><div align="center"><?php echo $date_op->toString('dd/MM/yyyy');?></div></td>
        </tr>
    <?php $montant += $entry->montant_place;?>
<?php endforeach; ?>
        <tr>
          <?php /*?><td><div align="left">&nbsp;</div></td><?php */?>
          <td><div align="left">&nbsp;</div></td>
          <td><div align="right"><strong>Total</strong></div></td>
          <td><div align="right"><strong><?php echo number_format($montant,0,',',' ');?></strong></div></td>
          <td><div align="center">&nbsp;</div></td>
        </tr>
    </tbody>
</table>


<br />
<br />
&nbsp;

<?php }?>
<?php }?>
</div>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








