<?php $sessionmcnp = new Zend_Session_Namespace('mcnp');?>
<link href="<?php echo $this->baseUrl();?>/bootstrap/dataTables/css/jquery.dataTables.css" rel="stylesheet" media="screen">

<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo $this->baseUrl();?>/bootstrap/dataTables/js/jquery.dataTables.js">
</script>
		<script type="text/javascript" charset="utf-8">
			/*$(document).ready(function() {
				$('#example').dataTable();
			} );*/
			$(document).ready(function() {
    $('#example').dataTable( {
        "sPaginationType": "full_numbers",
		"aaSorting": []
    } );
} );
		</script>

<div class="well3">
<div class="row-fluid">
<div class="span9" style="text-align:left">
  <blockquote><p class="text-info">Retrouver Numéro Identité</p></blockquote>

<div class="">
<form action="" method="post" enctype="multipart/form-data"  class="well form-horizontal" id="ancienpp">
  <?php if(isset($sessionmcnp->errorlogin) && $sessionmcnp->errorlogin!=""){?>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $sessionmcnp->errorlogin; $sessionmcnp->errorlogin = ""; ?>
    </div>
  <?php }?>
  <?php if(isset($this->message) && $this->message!=""){?>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $this->message; ?>
    </div>
  <?php }?>
  
  <legend>Retrouver Numéro identité</legend>
  <div class="">
  <div class="span6">
  
  <div class="control-group">
  <label class="control-label" for="nom">Nom </label>
  <div class="controls">
  <input type="text" name="nom" id="nom" placeholder="Nom" value="<?php echo $this->nom; ?>" >
  </div>
  </div>
  
<div class="control-group">
  <label class="control-label" for="prenom">Prénom </label>
  <div class="controls">
  <input type="text" name="prenom" id="prenom" placeholder="Prénom" value="<?php echo $this->prenom; ?>" >
  </div>
  </div>
  
  </div>
  
  <div class="span6">
  
  <div class="control-group">
  <label class="control-label" for="raison_sociale">Raison sociale </label>
  <div class="controls">
  <input type="text" name="raison_sociale" id="raison_sociale" placeholder="Raison sociale" value="<?php echo $this->raison_sociale; ?>" >
  </div>
  </div>  
  
  <div class="control-group">
  <label class="control-label" for="code_membre">Code Membre </label>
  <div class="controls">
  <input type="text" name="code_membre" id="code_membre" placeholder="Code Membre" value="<?php echo $this->code_membre; ?>" >
  </div>
  </div> 
   
  </div>
  </div>
   <legend></legend>
 

<div class="form-actions">
<input name="ok" type="hidden" id="ok" value="ok" />
<!--<button type="reset" class="btn">Annuler</button>-->
<button type="submit" class="btn btn-primary">Rechercher</button>
</div>

</form>

<?php 
  if (isset($_POST['ok']) && $_POST['ok']=="ok") {
  if ((isset($_POST['nom']) && $_POST['nom']!="") || (isset($_POST['prenom']) && $_POST['prenom']!="") || (isset($_POST['raison_sociale']) && $_POST['raison_sociale']!="") || (isset($_POST['code_membre']) && $_POST['code_membre']!="")) {
?>

  <blockquote>Résultat</blockquote>
<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th><div align="center">Numéro identité</div></th>
            <th><div align="left">Nom & prénom(s)</div></th>
            <th><div align="left">Raison sociale</div></th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->recherche as $entry): ?>
        <tr>
          <td><div align="center"><span class="label label-info"><?php if(isset($entry->numidentp))  {echo $entry->numidentp;} elseif(isset($entry->numidentm)) {echo $entry->numidentm;}?></span></div></td>
          <td><div align="left"><?php   if(isset($entry->nom)) {echo $entry->nom;}?> <?php if(isset($entry->prenom)) { echo $entry->prenom;} ?> <?php if(isset($entry->representant)) { echo $entry->representant ;} ?></div></td>
          <td><div align="left"><?php if(isset($entry->nomm))  {echo $entry->nomm;}?></div></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>



<br />
<br />
&nbsp;

<?php }?>
<?php }?>
</div>

</div>
<div class="span3">
<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
</div>








