<style> 

    /* MARKETING CONTENT
    -------------------------------------------------- */

    /* Center align the text within the three columns below the carousel */
    .marketing .span4 {
      text-align: center;
    }
    .marketing h2 {
      font-weight: normal;
    }
    .marketing .span4 p {
      margin-left: 10px;
      margin-right: 10px;
    }


    /* Featurettes
    ------------------------- */

    .featurette-divider {
      margin: 40px 0; /* Space out the Bootstrap <hr> more */
    }
    .featurette {
      padding-top: 30px; /* Vertically center images part 1: add padding above and below text. */
      overflow: hidden; /* Vertically center images part 2: clear their floats. */
    }
    .featurette-image {
      margin-top: -30px; /* Vertically center images part 3: negative margin up the image the same amount of the padding to center it. */
    }

    /* Give some space on the sides of the floated elements so text doesn't run right into it. */
    .featurette-image.pull-left {
      margin-right: 30px;
    }
    .featurette-image.pull-right {
      margin-left: 30px;
    }

    /* Thin out the marketing headings */
    .featurette-heading {
      font-size: 30px;
      font-weight: 200;
      line-height: 1;
      letter-spacing: -1px;
    }



</style>
<br />
<br />
<br />

<div class="row-fluid">
        <div class="span9">      
<?php if(count($this->video) > 0){?>
<div class="featurette" align="justify">
        <h2 class="featurette-heading" align="left"><?php echo ($this->video->video_libelle); ?></h2>
        <p align="justify"><?php echo ($this->video->video_description); ?></p>
      </div>
      <hr class="featurette-divider" />
<?php }?>


</div>

<div class="span3">
	<?php include("../application/layouts/scripts/droite.phtml"); ?>
</div>
</div>
      <hr class="featurette-divider" />



